### DISCUSSION TITLE
Question about arbitrary variants and problem with generate  multiple time of keyframes

### DISCUSSION THREAD

**Discussion by prpanto** [tailwindlabs/tailwindcss#10038] [Help] [answered]
Hello everyone,
I have create this [playground](https://play.tailwindcss.com/8U4KcgzmxE) and first question is why the arbitrary variants don't change the duration and delay and second is the tailwind generate multiple times the keyframes  code:
```css
@keyframes move-forever{
  0%{
    transform: translate3d(-90px, 0, 0);
  }

  100%{
    transform: translate3d(85px, 0, 0);
  }
}
```
