### DISCUSSION TITLE
How can I set `column-rule-style|column-rule-width|column-rule-col` for column layout in tailwind ?

### DISCUSSION THREAD

**Discussion by joisun** [tailwindlabs/tailwindcss#10133] [Ideas]
I‘m trying use Column Layout with tailwind, but I did not find  where the document mentioned about related properties.
How can I set `column-rule-style|column-rule-width|column-rule-col` for column layout in tailwind ?

**Comment by wongjn** [comment]
You could use [arbitrary property classes](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties) like `[column-rule-style:value]` or you could use a [plugin to create class utilities](https://tailwindcss.com/docs/plugins#dynamic-utilities).

**Reply by kachkaev** [reply]
Out of curiosity, what prevents TailwindCSS from supporting these fields? The syntax would be the same as for `outline-*`.

```
[column-rule-color:#ff0000]
[column-rule-style:dotted]
[column-rule-width:4px]
↓
column-rule-[#ff0000]
column-rule-dotted
column-rule-4
```

**Reply by rozsazoltan** [reply]
@kachkaev In the meantime, you can implement them into your own projects.

```css
@utility column-rule-* {
  column-rule-color: --value(--column-rule-color-*, --color-*, [color]);
  column-rule-style: --value("hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset");
  column-rule-width: --spacing(--value(integer));
  column-rule-width: --value([length]);
}
```

* https://play.tailwindcss.com/psMIBcpuEW

<img width="716" height="618" alt="image" src="https://github.com/user-attachments/assets/1243b41c-33e5-48bb-a084-a84acc4a9963" />
