### DISCUSSION TITLE
Can you stack linear gradients?

### DISCUSSION THREAD

**Discussion by do-kevin** [tailwindlabs/tailwindcss#10146] [Help] [answered]
Hey there,

I'm trying to figure out if you can stack linear gradients. I am trying to create a gradient border for an element.

I've tried to do it in the tailwind config file, like in the [Tailwind Docs: Customizing Your Theme](https://tailwindcss.com/docs/background-image#customizing-your-theme):

```
module.exports = {
  .
  .
  theme: {
    extend: {
      backgroundImage: {
        "gradient-border": "linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255)) padding-box,
        linear-gradient(to right, rgb(147, 197, 253), rgb(124, 58, 237)) border-box",
      }
    },
  },
  .
  .
```

But that did not work when I applied my `.bg-gradient-border`. And the gradient only seems to work if I remove the second gradient and `padding-box` and `border-box`. Is this doable in Tailwind?

**Comment by wongjn** [comment]
It does not work because the value is invalid for the `background-image` CSS property – you cannot have white-space separated values in it and `padding-box` and `border-box` are invalid keyword values – they belong in the `background-clip` CSS property. ~~You could split these up like so~~:

```js
module.exports = {
  // …
  theme: {
    extend: {
      backgroundImage: {
        "gradient-border": "linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255)),
        linear-gradient(to right, rgb(147, 197, 253), rgb(124, 58, 237))",
      },
      // Edit: below does not work!
      backgroundClip: {
        "gradient-border": "padding-box, border-box",
      },
    },
  },
  // …
}
```
~~And then apply these values together like `bg-gradient-border bg-clip-gradient-border`.~~

**Reply by do-kevin** [reply]
> It does not work because the value is invalid for the `background-image` CSS property – you cannot have white-space separated values in it and `padding-box` and `border-box` are invalid keyword values – they belong in the `background-clip` CSS property. You could split these up like so:
> 
> ```js
> module.exports = {
>   // …
>   theme: {
>     extend: {
>       backgroundImage: {
>         "gradient-border": "linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255)),
>         linear-gradient(to right, rgb(147, 197, 253), rgb(124, 58, 237))",
>       },
>       backgroundClip: {
>         "gradient-border": "padding-box, border-box",
>       },
>     },
>   },
>   // …
> }
> ```
> 
> And then apply these values together like `bg-gradient-border bg-clip-gradient-border`.

Thanks for pointing out that `padding-box` and `border-box` are part of `background-clip`. It seems the other issue I'm running into is extending background clip. [https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L43](https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L43) doesn't seem to show background clip and it's not applying in my project or in my [Tailwind Play](https://play.tailwindcss.com/6KzDXjZsO5?layout=horizontal). It isn't `backgroundClip`?

**Reply by wongjn** [reply]
Ah yes, sorry, I should have double-checked – indeed you cannot add extra values to `bg-clip-*` utilities, so the next best thing is using an [arbitrary property](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties) like `[background-clip:padding-box,border-box]` or declare it in your CSS like:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .bg-clip-gradient-border {
    background-clip: padding-box, border-box;
  }
}
```
But then you might as well combine these classes if these two property values are always used together (instead of the Tailwind configuration stated initially):
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .bg-gradient-border {
    background-image:
      linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255)),
      linear-gradient(to right, rgb(147, 197, 253), rgb(124, 58, 237));
    background-clip: padding-box, border-box;
  }
}
```
