### DISCUSSION TITLE
Composing @media into one when using addUtilities in plugin.

### DISCUSSION THREAD

**Discussion by itekhi** [tailwindlabs/tailwindcss#10248] [Help]
**What version of Tailwind CSS are you using?**

`3.2.4`

**What build tool (or framework if it abstracts the build tool) are you using?**

`create-react-app`

**What version of Node.js are you using?**

`v16.14.2`

**What browser are you using?**

`Firefox 108.0.1`

**What operating system are you using?**

`macOS`

**Reproduction URL**

https://github.com/itekhi/tailwindcss-fully-fluid

There's a `testapp` in it, you can run it and see what's going on.

This is the plugin that I am working on right now, I didn't provide a tailwind play link because I can't add the plugin to it as I didn't yet release it to npm... I thought of codesandbox, but it is harder to show the CSS file.

**Describe your issue**

Plugin adds utility classes, and there's a config option `useMediaReset` which adds `@media` classes to reset the classes to tailwind's defaults.

In the end it looks like this:

```js
addUtilities({
    '.text-vw-xl': {
        'font-size': 'clamp(10px, 1.5625vw, 30px)',
        'line-height': 1.25',
        // if `useMediaReset`
        '@media (min-width: 1920px)': {
            'font-size': '1.25rem'
        },
        '@media (max-width: 639.99px)': {
            'font-size': '1.25rem'
        }
    },
    '.text-vw-2xl': {
        'font-size': 'clamp(12px, 1.875vw, 36px)',
        'line-height': 1.25',
        // if `useMediaReset`
        '@media (min-width: 1920px)': {
            'font-size': '1.5rem'
        },
        '@media (max-width: 639.99px)': {
            'font-size': '1.5rem'
        }
    },
    // other classes for `xs`, `sm`, etc.
})
```

The problem with this is that all of the classes now have their own `@media` in a generated css file, which leads to enormous file size...

This is the same after `npm run build`.

```css
.text-vw-xl {
  font-size: clamp(10px, 1.5625vw, 30px);
  line-height: 1.25;
}

@media (max-width: 639.99px) {
  .text-vw-xl {
    font-size: 1.25rem;
  }
}

@media (min-width: 1920px) {
  .text-vw-xl {
    font-size: 1.25rem;
  }
}

.text-vw-2xl {
  font-size: clamp(12px, 1.875vw, 36px);
  line-height: 1.25;
}

@media (max-width: 639.99px) {
  .text-vw-2xl {
    font-size: 1.5rem;
  }
}

@media (min-width: 1920px) {
  .text-vw-2xl {
    font-size: 1.5rem;
  }
}
```

I understand that this could be because there should be an order of classes, but I think in the most cases it could be combined into one. For example combining `@media`s into one when they are inside one `addUtilities` function, same thing inside other `addUtilities`.
