### DISCUSSION TITLE
Dark mode using semantic colors

### DISCUSSION THREAD

**Discussion by nareshbhatia** [tailwindlabs/tailwindcss#10274] [Help] [answered]
I am trying to implement dark mode using semantic color tokens instead of the `dark` variant provided by tailwind. Wanted to run my approach by this group to see if it makes sense directionally.

### Context
This approach was outlined by the Figma team in their Config 2022 presentation titled [The hardest part about building dark mode is that people think it’s easy](https://www.youtube.com/watch?v=1DTnojio89Y). The basic concept is to use a single semantic token to represent a color instead two atomic tokens, one for light mode and another for dark mode. For example, a single semantic token called `bg-brand` instead of two atomic tokens `bg-blue-800` & `dark:bg-blue-600`. The supposed advantage of such a system is that it can scale to large teams by reducing the chance of picking inconsistent colors.

Here's an example of how I have been able to simplify my Hero banner which should show a different shade of blue in light vs. dark mode:

```html
<!-- Before --->
<div className="bg-primary-800 dark:bg-primary-600 text-white flex flex-col items-center py-16">
  ...
</div>

<!-- After --->
<div className="bg-brand text-onbrand flex flex-col items-center py-16">
  ...
</div
```

### Implementation Approach
My basic implementation approach is to introduce the semantic tokens as custom utility classes in my global CSS. For example,

```css
@layer utilities {
  .bg-default {
    background-color: theme(colors.white);
  }
  .dark .bg-default {
    background-color: theme(colors.neutral.900);
  }

  .text-default {
    color: theme(colors.black);
  }
  .dark .text-default {
    color: theme(colors.white);
  }

  .bg-brand {
    background-color: theme(colors.primary.800);
  }
  .dark .bg-brand {
    background-color: theme(colors.primary.600);
  }

  .bg-brand-hover {
    background-color: theme(colors.primary.700);
  }

  .text-onbrand {
    color: theme(colors.white);
  }

  .bg-brand-secondary {
    background-color: theme(colors.primary.100);
  }

  .bg-brand-secondary-hover {
    background-color: theme(colors.primary.200);
  }

  .text-onbrand-secondary {
    color: theme(colors.primary.700);
  }

  .bg-default-hover {
    background-color: theme(colors.neutral.900 / 5%);
  }
  .dark .bg-default-hover {
    background-color: theme(colors.white / 5%);
  }
}
```

For the most part this is working well. I have run into only one snag so far - I don't know how to implement focus ring colors (e.g. focus:ring-primary-500) because these are implemented using CSS variables and not as straight class selectors. Would appreciate any ideas from this group.

### Question
What do you think about the overall approach? Can you suggest any improvements or a different approach?

P.S. The full source code of my POC is available here: https://github.com/nareshbhatia/tailwindcss-dark-mode-semantic-colors

**Comment by wongjn** [comment]
You should still be able to make ring colors like you have already done, like:
```css
@layer utilities {
  .ring-brand {
    --tw-ring-color: theme(colors.primary.800);
  }
  .dark .ring-brand {
    --tw-ring-color: theme(colors.primary.600);
  }
}
```
And then in HTML:
```html
<button class="focus:ring focus:ring-brand">
```
