### DISCUSSION TITLE
`@screen` for max width

### DISCUSSION THREAD

**Discussion by justingolden21** [tailwindlabs/tailwindcss#10281] [Ideas]
# The problem

Currently, we can use `@screen lg` to apply styles only to `lg` screens and up.

I know tailwind is mobile first, and I know we can add unique screen selectors to our tailwind config under `screens`, but it feels dumb to me that I have to manually write out a vanilla CSS selector:

`@media max-width(1024px) {`

And then comment that it's `lg` and note that anytime I change screen sizes, I have to change that value. It seems like one of the consistency things that Tailwind is meant to fix. Even in mobile first code, I find myself writing code that's only for mobile and not wanting to override every property back to default on larger screens.

For example, I have a class that prevents scroll on mobile, `noscroll-sm` , and I add overflow hidden, position relative, and height 100%. In vanilla CSS:

```css
@media max-width(1024px) {
  .noscroll-sm {
    overflow: hidden;
    position: relative;
    height: 100%; 
  }
}
```

But I can't use the `@screen` directive and any time my `lg` size changes my code breaks.

Alternatively, I could write

```css
  .noscroll-sm {
    overflow: hidden;
    position: relative;
    height: 100%; 
  }
@screen lg {
  .noscroll-sm {
    overflow: auto;
    position: inherit;
    height: auto; 
  }
}
```

But you can see why this is way worse, more confusing, can create conflicts, and scales horribly with more code.

There are others online looking to use this feature as well, and it wouldn't conflict with anything existing

# Proposed Solution

`@screen max(lg)`

And then `@screen lg` could just be an alias for `@screen min(lg)`. Intuitive, no breaking changes, and solves all problems.

### Side Note

As a side note, your [Screens documentation](https://tailwindcss.com/docs/screens) could use a section about using `@screen`

![image](https://user-images.githubusercontent.com/30274440/211426211-f50c025a-2544-4217-9837-80fcb5a7d4cf.png)

It would be a nice (and expected) thing to have in the docs there :)

Could just be as simple as linking to or quoting https://tailwindcss.com/docs/functions-and-directives#screen although I know we want to avoid duplicate info in docs.

Thanks for listening

**Comment by adamwathan** [comment]
Hey! I would write it like this, which will work in Tailwind already:

```css
@media not all and screen(lg) {
  .noscroll-sm {
    overflow: hidden;
    position: relative;
    height: 100%; 
  }
}
```

https://play.tailwindcss.com/j7uenBQqMY?file=css

That has the exact same behavior as:

```css
@media max-width(1023px) {
  .noscroll-sm {
    overflow: hidden;
    position: relative;
    height: 100%; 
  }
}
```

...which I'm guessing is what you actually want so there isn't a 1px overlap. The `not all and...` trick is helpful because it works even with `em`/`rem` breakpoints where otherwise you have to do gross stuff like `max-width(39.9999em)` to avoid the overlap.

This is how our built-in `max-*` modifier works for working with `max-width` media queries:

https://tailwindcss.com/docs/responsive-design#targeting-a-breakpoint-range

If you really do want `1024px` then you can just use the `theme()` function:

```css
@media max-width(theme(screens.lg)) {
  .noscroll-sm {
    overflow: hidden;
    position: relative;
    height: 100%; 
  }
}
```

https://play.tailwindcss.com/0bguhIb6Yc?file=css

Made a note for myself to add some more documentation around this stuff when I have a chance 👍 BTW — I would recommend using `screen()` over `@screen` — `@screen` is sort of quietly deprecated because it causes issues with some CSS nesting plugins that only bubble `@media` at-rules and don't have any awareness of the fact that `@screen` is a `@media` at-rule under the hood.
