### DISCUSSION TITLE
Button custom bg color not working

### DISCUSSION THREAD

**Discussion by TheBossDragon** [tailwindlabs/tailwindcss#10284] [Help]
Using 

tailwindcss v3.2.4
Nodejs16.17.0
Nextjs 10
Chrome browser
Windows OS

tailwind.config.js
`
theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#073655',
          50: '#D9EEFC',
          100: '#B4DDF9',
          200: '#63B9F2',
          300: '#1897EC',
          400: '#0D65A0',
          500: '#073655',
          600: '#052A42',
          700: '#042134',
          800: '#031521',
          900: '#020C13',
        }
     }
  }
}   
`

Button code
`<button type="button" className="bg-primary">Button</button>`

The bg color on buttons is not working. It works everywhere else on divs, text, etc.

Any thoughts?

**Comment by kevinashworth** [comment]
I see the same. Removing `type="button"` is the key to get it to behave how I expect. 

But I can't see where that would be documented? Putting that type on a button is valid HTML and serves a purpose (no default behavior that you have to prevent). I'm still pretty new to Tailwind, but this seems like a bug?

**Reply by radianrad** [reply]
I'm running into this issue as well. The Tailwind reset CSS is overtaking. Removing the type may work, but `type=reset` has a special function applied to it, and I would like to use that.

```css
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}
```
