### DISCUSSION TITLE
Why is the css defined in the layers not wrapped in layers in production

### DISCUSSION THREAD

**Discussion by stijns96** [tailwindlabs/tailwindcss#10299] [Help] [answered]
Hi there,

I don't think the css is wrapped in `@layers`, because otherwise it would cause too much css. But can't all the css of e.g. the base `@layer` be wrapped in a `@layer base {}` in production?

If I now create a component with `.class-1 .class-2 {}` and want to put a utility on it that overrides a property, then the utility is not specific enough...

### Example:
**HTML**
```html
<div class="container container--full">
  <header class="container__header">
    <h1 class="container__title">Title</h1>
  </header>
  <div class="container__content max-w-screen-xs">
    <p>Some content</p>
  </div>
</div>
```

**CSS**
```scss
@layer components {
  .container {
    @apply my-[var(--container-spacing)];
    &--background {
      @apply my-0 py-[var(--container-spacing)];
    }
    &__header,
    &__content,
    &__footer {
      @apply mx-auto
      mb-[var(--element-spacing)]
      max-w-screen-2xl
      px-[var(--site-side-spacing)]
      last:mb-0;

      // Container sizes
      .container--xs & {
        @apply max-w-screen-xs;
      }
      .container--sm & {
        @apply max-w-screen-sm;
      }
      .container--md & {
        @apply max-w-screen-md;
      }
      .container--lg & {
        @apply max-w-screen-lg;
      }
      .container--xl & {
        @apply max-w-screen-xl;
      }
      .container--2xl & {
        @apply max-w-screen-2xl;
      }
      .container--wide & {
        @apply max-w-full;
      }
      .container--full & {
        @apply max-w-full px-0;
      }
    }
  }
}

```

**Output**
<img width="396" alt="image" src="https://user-images.githubusercontent.com/47820758/212037752-c676f888-5679-4b65-a94a-dfd07fd2c882.png">

### The problem
<img width="471" alt="image" src="https://user-images.githubusercontent.com/47820758/212037937-a9699b17-c95f-4de5-af45-ab6196e81b66.png">

Since `.container--full .container__content` is not wrapped in a `@layer components {}`, it is obviously more specific than the .max-w-screen-xs utility. What I would actually like is the following:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/47820758/212041566-b185aee9-3df1-4808-8ef8-37d38953343d.png">

As you can see the utility classes are all wrapped in 1 `@layer utilities {}` and the component classes in 1 `@layer components {}`.

**Example**
```css
@layer utilities {
    /*  ↑ All other classes    */
    
    .max-w-screen-2xl {
        max-width: 1440px
    }
    
    .max-w-full {
        max-width: 100%
    }
    
    .max-w-\[80ch\] {
        max-width: 80ch
    }
    
    .max-w-xs {
        max-width: 20rem
    }
    
    .max-w-none {
        max-width: none
    }
    
    .max-w-sm {
        max-width: 24rem
    }
    
    .max-w-\[120rem\] {
        max-width: 120rem
    }
    
    .max-w-md {
        max-width: 28rem
    }
    
    .max-w-screen-xs {
        max-width: 360px
    }

    /*  ↓ All other classes    */
}
```

Of course I may be doing something wrong, since I use SCSS in combination with Rollup, but I don't see it on the current tailwind site either.

I really hope that this can be added as a feature or that someone can give a clear reason why this might not be possible. Or a workaround of course.

Thank you in advance!
