### DISCUSSION TITLE
[intelliSense] Getting intelliSense extension to work with Magento pwa-studio

### DISCUSSION THREAD

**Discussion by Youhan** [tailwindlabs/tailwindcss#10308] [Help] [answered]
## Short Version

How would you get the vscode intelliSense extension to work if you use tailwind classes on places other than `className, class, ngClass`?

We are using Tailwind classes inside CSS modules like this:

```CSS
.pageWrapper {
    composes: pt-16 from global;
    composes: max-w-menu from global;
    composes: mx-auto from global;
    composes: px-20 from global;
}
```

## Long Version

I am working on a project created using [pwa-studio](https://github.com/magento/pwa-studio). For [some reasons](https://github.com/magento/pwa-studio/discussions/3241) they have combined TailwindCSS and CSS Modules in React components.

So instead of 
```javascript
const Panel = props => (
    <article className="px-4">
       // ....
    </article>
)
```

Their workflow is to do it in two files (🤔 🤨)
```javascript
/* panel.js */
import classes from "./panel.module.css"

const Panel = props => (
    <article className={classes.root}>
        // ....
    </article>
)
```
```CSS
/* panel.module.css */
.root{
    composes: px-4 from global;
}
```

The problem is now you'll lose the functionality of the [TailwindCSS extension](https://github.com/tailwindlabs/tailwindcss-intellisense) which is essential in my personal workflow. 

So, I am trying to find out if there is any way to get the TailwindCSS extension to work in the module.css files?
