### DISCUSSION TITLE
CSS Reset

### DISCUSSION THREAD

**Discussion by Liberate30** [tailwindlabs/tailwindcss#10431] [Help]
The default form handling is really frustrating. The inputs and textarea have a background color of white by default.

**Comment by wongjn** [comment]
You could add your own additional resets for this, like:
```css
@layer base {
  input,
  textarea {
    background-color: transparent;
  }
}
```
