### DISCUSSION TITLE
Modifier functions at @apply level

### DISCUSSION THREAD

**Discussion by mrtnbroder** [tailwindlabs/tailwindcss#10479] [Ideas]
Hey there, not really sure how to call this feature but I was thinking that I'd really like to write this:

```css
.ingo {
  @apply:before h-175 w-175 top-75 relative max-w-full flex-shrink-0 flex-grow-0;
}
```

instead of this:

```css
.ingo {
  @apply before:h-175 before:w-175 before:top-75 before:relative before:max-w-full before:flex-shrink-0 before:flex-grow-0;
}
```

This would work for all modifiers (before, after, checked, focus, hover etc.) so e.g. `@apply:hover`, `@apply:focus` etc.

Whaddya think about this Tailwind Team?
