### DISCUSSION TITLE
Make shadow opacity composable

### DISCUSSION THREAD

**Discussion by brandonmcconnell** [tailwindlabs/tailwindcss#10487] [Ideas]
It would help to make opacity a configurable variable, even if there isn't a dedicated Tailwind utility for it.

So instead of this:

```css
body.cv-body .shadow-md {
    --tw-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
    --tw-shadow-colored: 0 4px 6px -1px var(--tw-shadow-color), 0 2px 4px -2px var(--tw-shadow-color);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
}
```

It would be this:

```css
body.cv-body .shadow-md {
    --tw-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / var(--tw-shadow-opacity, 0.1));
    --tw-shadow-colored: 0 4px 6px -1px var(--tw-shadow-color), 0 2px 4px -2px var(--tw-shadow-color);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
}
```

☝🏼 Note `var(--tw-shadow-opacity, 0.1)` instead of `0.1`
