### DISCUSSION TITLE
flex-center

### DISCUSSION THREAD

**Discussion by imMatheus** [tailwindlabs/tailwindcss#10495] [Ideas]
Why isn't **flex-center** a utility class in Tailwind already? It seems like a pretty logic thing to exist as it is very often used. Is there a reason this class should not exist? It would be super nice to have this as i find myself adding the **flex justify-center items-center** classes very often.

With **flex-center** i am referring to the following css code:

```css
.flex-center {
    display: flex;
    justify-content: center;
    align-items: center;
}
```

This could also be extended to have **absolute-center**
