### DISCUSSION TITLE
How do I customize the margin value

### DISCUSSION THREAD

**Discussion by laterdayi** [tailwindlabs/tailwindcss#10517] [Ideas]
How do I customize the margin value

The default mr mt ml mb is 1em，How to set mr ml mt mb Custom 18px or 20px

How to do it margin & padding

my: margin : 20px 0
mx: margin : 0 20px
ml : margin-left: 20px
mt: margin-top: 20px

**Comment by wongjn** [comment]
You could either write it in a CSS file like:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .my {
    margin: 20px 0;
  }
  .mx {
    margin: 0 20px;
  }
  .ml {
    margin-left: 20px;
  }
  .mt {
    margin-top: 20px;
  }
}
```
Or in a plugin:
```js
module.exports = {
  // …
  plugins: [
    require('tailwindcss/plugin')(({ addUtilities }) => {
      addUtilities({
        '.my': {
          margin: '20px 0';
        },
        '.mx': {
          margin: '0 20px';
        },
        '.ml': {
          marginLeft: '20px';
        },
        '.mt': {
          marginTop: '20px';
        },
      });
    }),
  ],
  // …
};
```
