### DISCUSSION TITLE
[IntelliSense] Autocomplete for custom directives

### DISCUSSION THREAD

**Discussion by unional** [tailwindlabs/tailwindcss#10547] [Ideas]
e.g. in `styles.css`:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
@import 'codemirror/lib/codemirror.css';

@layer components {
  .alice {
    background-color: aliceblue;
  }
}
```

Right now `alice` does not show up in completion:

```tsx
// x.tsx

function Foo() {
  return <div className="/* alice does not show up/*">blah</div>
}
```
