### DISCUSSION TITLE
Base font styles plugin with screen sizes

### DISCUSSION THREAD

**Discussion by TheRealFlyingCoder** [tailwindlabs/tailwindcss#10642] [Help] [answered]
I'm looking to set up base styles for my font sizes, with respect to screen size but it doesn't seem possible?

Right now you can go:

```
module.exports = plugin(({ addBase, theme }) =>
	addBase([
		{
			p: {
				fontSize: theme('fontSize.base'),
			},
		},
	]),
);
```

Which works fine but doesn't change based on screen size... Is there a way to solve this using a method like:

```
module.exports = plugin(({ addBase, theme }) =>
	addBase([
		{
			p: {
				fontSize: theme('fontSize.base'),
			},			
			lg: {
			        p: {
				        fontSize: theme('fontSize.lg'),
			        },
			}
		},
	]),
);
```

**Comment by adamwathan** [comment, marked as answer]
You can do this in a plugin like this:

```js
module.exports = plugin(({ addBase, theme }) =>
  addBase([
    {
      p: {
        fontSize: theme("fontSize.base"),
      },
      '@media screen(lg)': {
        p: {
          fontSize: theme("fontSize.lg"),
        },
      },
    },
  ])
);
```

Personally if I were going to do this though I'd just do it in CSS, simpler than all the extra boilerplate of trying to do it in JS:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  p {
    font-size: theme(fontSize.base);
  } 
  @media screen(lg) {
    font-size: theme(fontSize.lg);
  }
}
```
