### DISCUSSION TITLE
[IntelliSense] Autocomplete for CSS custom properties (variables) in arbitrary value (square bracket notation)

### DISCUSSION THREAD

**Discussion by soc221b** [tailwindlabs/tailwindcss#10652] [Ideas]
Hi there,

We sometimes need to use vars in `calc`, for example:

```css
@layer base {
  :root {
    --font-size: 14px;
  }
}
```

```html
<h1 class="h-[calc(var(--font-size)*1.5)]">Title</h1>
```

---

Related extension: Auto complete it when using style properties: https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables
