### DISCUSSION TITLE
Is it possible to use `@apply` in tailwindcss for keyframes?

### DISCUSSION THREAD

**Discussion by krishnaacharyaa** [tailwindlabs/tailwindcss#10760] [Help]
I need to apply the following entering and leaving animation

They are presented using tailwindcss classes

```
      Entering: "transform ease-out duration-300 transition"
        From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
        To: "translate-y-0 opacity-100 sm:translate-x-0"
      Leaving: "transition ease-in duration-100"
        From: "opacity-100"
        To: "opacity-0"
```
I tried to use the following but doesn't seem to work.

```
@tailwind base;
@tailwind components;
@tailwind utilities;


@layer components {
  .alt-pop {
    animation: alt-pop-enter, alt-pop-leave;
  }
  @keyframes alt-pop-enter {
    @apply transform ease-out duration-300 transition;
    from { @apply translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2; }
    to   { @apply translate-y-0 opacity-100 sm:translate-x-0; }
  }
  @keyframes alt-pop-leave {
    @apply transition ease-in duration-100;
    from { @apply opacity-100; }
    to   { @apply opacity-0; }
  }
}
```
My suspicions are that:

keyframes doesn't work with @apply
keyframes work exclusively with from and to, so cannot add extra css styles within the keyframe
How do I use css as much as possible to setup this entering and leaving animation instead of JS?

And how do I use tailwindcss classes as much as possible?

And how do I set the delay before switching from entering to leaving?

One approach I can think of is convert all the tailwind classes back to the actual tailwind then write my own keyframes and animation css class.

Is there a better approach than this?

**Comment by wongjn** [comment]
There are some invalid syntax/conceptions with the provided code:

- ```css
  .alt-pop {
    animation: alt-pop-enter, alt-pop-leave;
  }
  ```
  This applies both of these named animations at the same time - probably not you'd want. Also note that no duration has been provided so the duration for both these animations is `0s` and thus there would be no visual effect.

- ```css
  @keyframes alt-pop-enter {
    @apply transform ease-out duration-300 transition;
    /* … */
  }
  @keyframes alt-pop-leave {
    @apply transition ease-in duration-100;
    /* … */
  }
  ```
  You can't use `@apply` as immediate "child" of `@keyframes`, since this would *conceptually* output something like:

  ```css
  @keyframes alt-pop-enter {
    transform: /* … */;
    transition-timing-function: /* … */;
    /* … */
  }
  ```
  And this is invalid CSS.

- ```css
  @apply transform ease-out duration-300 transition;
  /* … */
  @apply transition ease-in duration-100;
  ```
  It feels like you are trying to manipulate the `animation`, but you are using classes that set `transition-*` properties. These properties do not affect `animation`.

---

> How do I use css as much as possible to setup this entering and leaving animation instead of JS?

There will always be some aspect of JavaScript needed, since the CSS needs to be applied on the event when the animation needs to play.

> And how do I use tailwindcss classes as much as possible?

Use your existing solution with the enter/leave classes.

> And how do I set the delay before switching from entering to leaving?

This would be best done in the JavaScript that controls the enter/leaving classes. Otherwise, you could add a `delay-*` class to the `leaving` set of classes.

> One approach I can think of is convert all the tailwind classes back to the actual tailwind then write my own keyframes and animation css class.
>
> Is there a better approach than this?

Yes, your existing enter/leave classes.

**Reply by krishnaacharyaa** [reply]
How about this  https://play.tailwindcss.com/uLgEAAd5Of?file=css ?

**Reply by wongjn** [reply]
```css
@keyframes alt-pop-enter {
  from {
    @apply translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2;
  }
  to {
    @apply translate-y-0 opacity-100 sm:translate-x-0;
  }
}
```

You can't use variants in `@keyframes` since it would produce invalid CSS. In this instance, you'd create a separate `@keyframes` for the `sm:` case and then apply that to the `.alt-pop` class. Something like:

```css
.alt-pop {
  animation: 300ms ease-out alt-pop-enter, 100ms ease-in 500ms alt-pop-leave;
}

@media screen(sm) {
  .alt-pop {
    animation: 300ms ease-out alt-pop-enter-sm, 100ms ease-in 500ms alt-pop-leave;
  }
}

@keyframes alt-pop-enter {
  from {
    @apply translate-y-2 opacity-0;
  }
  to {
    @apply translate-y-0 opacity-100;
  }
}

@keyframes alt-pop-enter-sm {
  from {
    @apply opacity-0 translate-x-2;
  }
  to {
    @apply opacity-100 translate-x-0;
  }
}
```

**Reply by krishnaacharyaa** [reply]
Thank you for the reply but It doesn't seem to produce invalid CSS as you can see in the components tab in generated CSS for tailwind playground. The responsive variation seem to work as intended. Have I got it wrong?

**Reply by wongjn** [reply]
Your `@keyframes` compile to:
```css
@keyframes alt-pop-enter {
  from {
    --tw-translate-y: 0.5rem;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
    opacity: 0;
  }

  @media (min-width: 640px) {
    from {
      --tw-translate-y: 0px;
      --tw-translate-x: 0.5rem;
      transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
    }
  }

  to {
    --tw-translate-y: 0px;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
    opacity: 1;
  }

  @media (min-width: 640px) {
    to {
      --tw-translate-x: 0px;
      transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
    }
  }
}
```

Where the `@media` rules inside the `@keyframes` is invalid CSS.
