### DISCUSSION TITLE
darkMode in combination with important configuration

### DISCUSSION THREAD

**Discussion by gizburdt** [tailwindlabs/tailwindcss#10763] [Help]
Hi,

I'm creating a nova package: https://github.com/appstract/nova-horizon.

In this package i would like to style some elements, so I'm including tailwind. Because Nova also includes its own tailwind, I use the `important` configuration: `important: '.nova-horizon'`. This works like a charm. Yesterday someone created a PR to enable dark mode for my package. He removed the `important` configuration, and added `darkMode: 'class'` to the config. So now darkMode works. But now the css breaks the css of Nova, because the `important` configuration is removed. When I enable it, darkMode won't work. So it looks like the `important Is this a bug, or meant this way, or am I doing something wrong?

Thanks! :)

**Comment by wongjn** [comment]
Ensure the `dark` class is applied to an element inside the element with the `nova-horizon` class:
```html
<!-- Should work -->
<div class="nova-horizon">
  <div class="dark">
    <p class="dark:text-red-500">
```
```html
<!-- Won't work -->
<div class="dark">
  <div class="nova-horizon">
    <p class="dark:text-red-500">
```
```html
<!-- Won't work -->
<div class="nova-horizon dark">
  <p class="dark:text-red-500">
```

**Reply by macbookandrew** [reply]
I created another PR using that approach: https://github.com/appstract/nova-horizon/pull/15

However, it would be awesome if there was a configuration option to switch the order of the `darkMode`  class and the `important` selector:

What we need:

```css
.dark .nova-horizon .dark\:border-gray-700 {
  --tw-border-opacity: 1;
  border-color: rgb(55 65 81 / var(--tw-border-opacity));
}
```

What we get:

```css
.nova-horizon .dark .dark\:border-gray-700 {
  --tw-border-opacity: 1;
  border-color: rgb(55 65 81 / var(--tw-border-opacity));
}
```
