### DISCUSSION TITLE
How to get Tailwind to include my theme variables? it's ignoring them on build

### DISCUSSION THREAD

**Discussion by SHxKM** [tailwindlabs/tailwindcss#10775] [Help] [answered]
Hi, I'm supporting multiple themes (actually just the `base` theme and another one, here's a snippet from my `styles.scss`:

This is just part of the file:

```scss
@layer base {

  :root {
    --color-primary: theme(colors.rose.500);
    --color-primary-content: theme(colors.rose.50);

  .theme-midnight {

    --color-primary: theme(colors.rose.500);
    --color-primary-ring: theme(colors.rose.400);
    --color-primary-content: theme(colors.rose.50);

}
```

I want to be able to use `theme(colors.X.Y)` because copying the color codes manually is a chore. However it seems that when I run:

```
npx tailwindcss -o stylesheets/styles.min.css --minify
```

Tailwind is throwing away these colors, notice below how Chrome colors the variable in grey/disabled color, as if it's not able to find it at all.

<img width="479" alt="Screenshot 2023-03-11 at 20 37 58" src="https://user-images.githubusercontent.com/6573474/224505856-5c5ab037-9610-4805-97f8-02b82eda3788.png">

Is there any way to not have Tailwind throw these variables away?
