### DISCUSSION TITLE
How to get the whole object in SCSS, and not one property from the TailwindCSS configuration?

### DISCUSSION THREAD

**Discussion by Mike-Ro** [tailwindlabs/tailwindcss#10797] [Help] [answered]
Hi!

Now I have to get each property from the Tailwind configuration in order to then insert it into the scss class. If there are a lot of classes, then you have to write a lot with your hands, which is unpleasant...

package.json:
```json
{
  "name": "1",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "next dev",
    "build": "next build"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "^13.1.6",
    "autoprefixer": "^10.4.13",
    "circular-dependency-plugin": "^5.2.2",
    "clsx": "^1.2.1",
    "cross-env": "^7.0.3",
    "next": "^13.2.4",
    "next-compose-plugins": "^2.2.1",
    "sass": "^1.59.2",
    "tailwindcss": "^3.2.6"
  }
}
```

```js
/** @type {import('tailwindcss').Config} */
const config = {

  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],

  theme: {
    extend: {
      fontSize: {
        small: '10px',
        medium: '20px',
        large: '30px',
      },
    },
  },

}

module.exports = config;
```

style.scss:
```scss
@import 'tailwindcss/components';

@layer components {
  .font-size {

    &--small { font-size: theme('fontSize.small') }
    &--medium { font-size: theme('fontSize.medium') }
    &--large { font-size: theme('fontSize.large') }

    // you need to write with your hands...

  }
}
```

Please tell me how to get the entire Tailwind configuration object at once (rather than individual properties)? For example, for its iteration in scss (example below)?

```scss
@import 'tailwindcss/components';

@layer components {
  .font-size {

    @each $k, $v in theme('fontSize') {
      &--#{$k} { font-size: #{$v} }
    }

  }
}
```

Thank you so much for any response!
