### DISCUSSION TITLE
How to overwrite existing classes and add breakpoints to custom the class

### DISCUSSION THREAD

**Discussion by meotimdihia** [tailwindlabs/tailwindcss#10809] [Help]
How to overwrite existing classes and add breakpoints to custom the class

Currently, this is my code on the file `index.css`
*(the existing `swiper-button-prev` came from the package `swipejs`)*
```css
div.swiper-button-prev,
div.swiper-button-next {
  /* does work but I don't know if this is the right way because I have a dark/light theme. */
  color: #ccc;
  background-color: rgba(0, 0, 0, 0.5);
  border-radius: 9999px;
  height: 10px !important;

  /* doesn't work */
  @media screen(sm) {
    padding: 0.5em;
  }
  @media screen(md) {
    padding: 0.5em;
  }
  @media screen(xl) {
    padding: 1.5em;
  }
}
```

Edit:  I wrote it as: 
```css
@media screen(sm) {
  div.swiper-button-prev,
  div.swiper-button-next {
    padding: 0.5em;
  }
}
```
