### DISCUSSION TITLE
How to use multiple tailwind.config.js files?

### DISCUSSION THREAD

**Discussion by francoism90** [tailwindlabs/tailwindcss#10860] [Help] [answered]
In our project we would like to use multiple`tailwind.config.js` files, as we use a multi-domain/site setup.

This is our project's root `tailwind.config.js` file:
```css
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: [
      './vendor/filament/**/*.blade.php',
    ],
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
```

This is an example of a domain `tailwind.config.js` file, e.g. `src/domain/foo/tailwind.config.js`:
```css
/** @type {import('tailwindcss').Config} */
module.exports = {
content: {
    relative: true,
    files: [
      './resources/**/*.php',
      './resources/**/*.blade.php',
      './resources/**/*.blade.js',
      './resources/**/*.blade.vue',
    ],
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans-family)', 'sans-serif'],
        serif: ['var(--font-serif-family)', 'serif'],
      },
    }
  },
};
```

To import the actual domain `tailwind.config.js` file, we use something like this, e.g. `src/domain/foo/app.css`:
```css
@config "tailwind.config.js";

@tailwind base;
@tailwind components;
@tailwind utilities;
```

This works fine, however the problem is that the combined CSS doesn't use the project's root anymore, it simple overwrites them. This means `'./vendor/filament/**/*.blade.php'`, will not be parsed.

We have tried presets, however this doesn't merge the `content`/`files` array, it simple replaces them.

Are there any other solutions we could try?

Thanks!
