### DISCUSSION TITLE
Specificity issue after upgrading to 3.3.1

### DISCUSSION THREAD

**Discussion by krampstudio** [tailwindlabs/tailwindcss#11077] [Help] [answered]
I have the following setup:
```
darkMode : 'class'
```

in a css file 
```css
@layer base {
	.dark .text-black {
		@apply text-gray-200;
	}
}
```

And in my HTML, I have some places I override the `text-black` to have black on white, ie

```html
<button class="dark:bg-white dark:text-black">I'm a black text on a white background even in dark mode</button>
```

With tailwind 3.2 it was working, getting in the generated code:

```css
.dark .text-black{
  --tw-text-opacity: 1;
  color: rgb(229 231 235/var(--tw-text-opacity));
}
.dark .dark\:text-black {
  --tw-text-opacity: 1;
  color: rgb(0 0 0/var(--tw-text-opacity));
}
```

But with tailwind 3.3, the specificity of the base style increases:
```css
.dark :is(.dark .dark\:text-black) {
  --tw-text-opacity: 1;
  color: rgb(229 231 235 / var(--tw-text-opacity));
}
:is(.dark .dark\:text-black) {
  --tw-text-opacity: 1;
  color: rgb(0 0 0 / var(--tw-text-opacity));
}
```

I'm wondering why there's an additional `.dark` in front of the `:is()`?
