### DISCUSSION TITLE
Inheritance of `selection`-modifier for highlighted behaves strange

### DISCUSSION THREAD

**Discussion by gruberro** [tailwindlabs/tailwindcss#11093] [General]
Hi community,

I might be wrong, but according the docs the inheritance of the `selection`-modifier might be able to re-style highlighted text for child elements in common. It at least did so in previous version (`2.x`). But again, I might have misunderstood the docs 🙃.

Did some tests [here](https://play.tailwindcss.com/y6vlEc5Pxo) and from my understanding variant `A)` should inherit `selection:text-red-900`. IMHO it shouldn't be necessary to do the "tricks" used in variant `B)` and `C)`.

Maybe some of you have a useful hint for me ❤️

**Comment by wongjn** [comment]
If you look in the *Generated CSS*, you'll see the following generated rules that are the main focus of your discussion:

```css
.selection\:text-red-900 *::selection {
  --tw-text-opacity: 1;
  color: rgb(127 29 29 / var(--tw-text-opacity));
}

.selection\:text-white *::selection {
  --tw-text-opacity: 1;
  color: rgb(255 255 255 / var(--tw-text-opacity));
}
```

The `.selection\:text-white *::selection` is the same specificity as `.selection\:text-red-900 *::selection` and appears later in the order of rules in the CSS, so `selection:text-white` takes precedence.

In [Tailwind v2](https://play.tailwindcss.com/PwayWVSB9p), the generated rules would be:
```css
.selection\:text-white::selection {
  --tw-text-opacity: 1;
  color: rgba(255, 255, 255, var(--tw-text-opacity));
}

.selection\:text-red-900::selection {
  --tw-text-opacity: 1;
  color: rgba(127, 29, 29, var(--tw-text-opacity));
}
```

The rule selectors and the order of the rules are different which is why it behaves as you'd like in v2.
