### DISCUSSION TITLE
Is it possible to set css variable like arbitrary values?

### DISCUSSION THREAD

**Discussion by cawa-93** [tailwindlabs/tailwindcss#11106] [Help] [answered]
I have simple css components like so:
```css
.component-with-colored-bg {
    background-color: hsla(
        var(--component-with-colored-bg--hue, 0),
        var(--component-with-colored-bg--saturation, 0%),
        var(--component-with-colored-bg--lightness, 0%),
        var(--component-with-colored-bg--alpha, 1)
    );
}
```

I want to set `--component-with-colored-bg--alpha` value for element on `:hover` state. Is it possible to set css variable like arbitrary values?
Like below or any syntax 🤷🏻‍♂️
```html
<div class="component-with-colored-bg hover:--component-with-colored-bg--alpha-[0.5]">
```
