### DISCUSSION TITLE
How to use non-width @media query?

### DISCUSSION THREAD

**Discussion by cawa-93** [tailwindlabs/tailwindcss#11176] [Help] [answered]
There are many media features, not only viewport width. How I can use `height` or `hover` or anything else? 

How I can generate CSS like below from tailwind classes?
```css
@media (hover: hover) {
    .container:not(:where(:hover, :focus-visible)) button {
        opacity: 0;
    }
}
```
