### DISCUSSION TITLE
[IntelliSense] Add support for HSL color preview

### DISCUSSION THREAD

**Discussion by mattiaz9** [tailwindlabs/tailwindcss#11194] [Ideas]
It would be nice to have color preview when setting hsl colors. I think it would be possible if the css variables are set inside a @layer scope.

Example:

tailwind.config.js
```javascript
extend: {
  colors: {
    ...
    primary: "hsl(var(--primary))",
    ...
  }
}
```

global.css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    --primary: 222.2 47.4% 11.2%;
}
```
