### DISCUSSION TITLE
Group hover is not working on image.

### DISCUSSION THREAD

**Discussion by kevalrathod** [tailwindlabs/tailwindcss#11288] [Help] [answered]
Tailwind version:  v3 
Next: 13.3.0

Brave: 1.51.118
Safari: 16.1
Chrome: 113.0.5672.126 (Official Build) (arm64)

I am trying group hover on image which is working super good in my development but not working in production. Here is my snippet have a look.

```
<Link key={index} href="#" className="group">
  <div className="overflow-hidden  aspect-video bg-slate-100 cursor-pointer rounded-xl relative group">
    <div className="z-50 opacity-0 group-hover:opacity-100 transition duration-300 ease-in-out cursor-pointer absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-white">
      <i className="bi bi bi-play-fill" style={{fontSize:"4rem"}}></i>
    </div>
    <div className="rounded-xl z-50 opacity-0 group-hover:opacity-100 transition duration-300 ease-in-out cursor-pointer absolute from-black/80 to-transparent bg-gradient-to-t inset-x-0 -bottom-2 pt-8 text-white flex items-end">
      <div>
        <div className="transform-gpu  p-4 space-y-1 text-xl group-hover:opacity-100 group-hover:translate-y-0 translate-y-4 pb-8 transform transition duration-300 ease-in-out">
          <div className="font-bold capitalize text-base overflow-hidden">{data.title ? data.title.slice(0,30) : 'No title'}</div>
          <div className="opacity-60 text-xs ">
            {data.description ? data.description.slice(0,80) +'...' : ''}
          </div>
        </div>
      </div>
    </div>
    <img 
      loading="lazy"
      alt={data.asset_id} 
      className="object-cover w-full h-full aspect-square group-hover:scale-110 transition duration-300 ease-in-out group-hover::opacity-75" 
      src={data.thumbnail_url} />
  </div>
</Link>
```

<img width="1299" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/14817175/bb55117e-6d2a-4333-9c4a-b49000d330e3">

**Comment by adamwathan** [comment]
Hey! Seems to work fine here:

https://play.tailwindcss.com/Jm7tf0VnBR

I did have to change `group-hover::opacity-75` to `group-hover:opacity-75` but otherwise didn't do anything.

**Reply by kevalrathod** [reply]
@adamwathan Thanks for the support. But please check this: 
https://next-website-gumlet.vercel.app/channel/5fc5d468e648a0354be583cc/ 

i don't know what is missing from my end.

**Reply by wongjn** [reply, marked as answer]
You are missing the following CSS rules that should have been generated by Tailwind:

```css
.-bottom-2 {
  bottom: -0.5rem;
}

.z-50 {
  z-index: 50;
}

.space-y-1 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.25rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.25rem * var(--tw-space-y-reverse));
}

.from-black\/80 {
  --tw-gradient-from: rgb(0 0 0 / 0.8) var(--tw-gradient-from-position);
  --tw-gradient-to: rgb(0 0 0 / 0) var(--tw-gradient-to-position);
  --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to);
}

.to-transparent {
  --tw-gradient-to: transparent var(--tw-gradient-to-position);
}

.opacity-60 {
  opacity: 0.6;
}

.group:hover .group-hover\:translate-y-0 {
  --tw-translate-y: 0px;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}

.group:hover .group-hover\:opacity-100 {
  opacity: 1;
}
```

You can verify this by copy-pasting the above code into devtools in the `inspector-stylesheet` (or equivalent).

This is a common symptom of when the `content` file globs does not sufficiently cover source code. Consider checking that the file that has the code that produces the undesired behavior is covered by the `content` file globs in the Tailwind configuration.
