### DISCUSSION TITLE
Some input native icons do not change the color in chrome

### DISCUSSION THREAD

**Discussion by ZirionNeft** [tailwindlabs/tailwindcss#11300] [Help]
What I have:
![image](https://github.com/tailwindlabs/tailwindcss/assets/23456328/e1e13bac-9f4b-4b98-9177-457eede2334d)

Should be:
![image](https://github.com/tailwindlabs/tailwindcss/assets/23456328/a3060677-d585-445c-9952-9a010d2100c2)

Depending on this:
https://github.com/skeletonlabs/skeleton/issues/1503

Problem seen on inputs with types: date, search, time and etc where is icon

I've get that 
`input::-webkit-calendar-picker-indicator {
		@apply dark:invert
	}
` generated to 
```
:is(.dark input::-webkit-calendar-picker-indicator) {
  --tw-invert: invert(100%);
  filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
}
```
but styles not applying to any targets

TailwindCSS v3.3.2
Vite v4.3.9
Postcss v8.4.21

**Comment by wongjn** [comment]
Seems related to #10835, #10903, et al.

As a workaround, you could define `dark:` "manually", like:

```css
.dark input::-webkit-calendar-picker-indicator {
  @apply invert;
}
/* Or */
.dark input::-webkit-calendar-picker-indicator {
  filter: invert(100%);
}
```
