### DISCUSSION TITLE
How can i set a color to current value?

### DISCUSSION THREAD

**Discussion by JamDev0** [tailwindlabs/tailwindcss#11334] [Help]
I want to set a color to the current key word. How can i do it?

**Comment by wongjn** [comment]
Do you mean [`currentcolor`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword)? You can use the `current` value for color-related utilities, for example, `text-current` would generate:

```css
.text-current {
  color: currentcolor;
}
```
