### DISCUSSION TITLE
overflow-clip-margin css property

### DISCUSSION THREAD

**Discussion by stormynight9** [tailwindlabs/tailwindcss#11367] [Ideas]
Any plans on adding overflow-clip-margin css property to TailwindCSS?

**Comment by catinrage** [comment]
why is this feature not implemented yet ? its just so simple.

**Reply by rozsazoltan** [reply]
https://caniuse.com/?search=overflow-clip-margin

**Comment by rozsazoltan** [comment]
Browsers don't fully support this feature yet. I assume that's the reason for the delayed adoption. However, if it's not important for you that the feature works perfectly across all browsers supported by Tailwind CSS v4, you can easily add it to your project using the `@utility` directive.

The visual box values for [`content`](https://caniuse.com/mdn-css_properties_overflow-clip-margin_content-box), [`padding (default)`](https://caniuse.com/mdn-css_properties_overflow-clip-margin_padding-box), and [`border`](https://caniuse.com/mdn-css_properties_overflow-clip-margin_border-box) have been supported for quite a while by most Chromium-based browsers (Chrome, Edge, Opera, ...), with the exception of Safari and Firefox. I've declared these separately.

As for a relatively newer [value-based margin definition](https://caniuse.com/mdn-css_properties_overflow-clip-margin), it's still very much in the experimental phase and not available by default in most browsers. Nevertheless, I’ve created a utility for that as well.

```css
@import "tailwindcss";

@utility clip-box-* {
  overflow-clip-margin: --value('inherit', 'initial', 'unset', [*]);
  overflow-clip-margin: calc(var(--spacing) * --value(integer));
}
@utility clip-box-content {
  overflow-clip-margin: content-box;
}
@utility clip-box-padding {
  overflow-clip-margin: padding-box;
}
@utility clip-box-border {
  overflow-clip-margin: border-box;
}
```

* [Tailwind Play](https://play.tailwindcss.com/Fed9aq2Esx?file=css)

![image](https://github.com/user-attachments/assets/6647564a-232c-413d-9d94-37a7148877bf)
