### DISCUSSION TITLE
@apply rotate-* not working

### DISCUSSION THREAD

**Discussion by CodingButter** [tailwindlabs/tailwindcss#11406] [Help] [answered]
I'm trying to use the sibling selector and :checked selector to get a expand collapse to work. while the selectors are targeting correctly, the rotate-180 isn't being respected. I'm not sure what is wrong but it's only happening within the @apply. I can get rotate to work correctly when placing it directly into the class attribute. 
[Play Example](https://play.tailwindcss.com/kpouUNW412)

Minimal code example:
HTML:
```HTML
<input type="checkbox" id="PanelOneExpandCollapse"/>
<div>
    <span>Element</span>
    <label for="PanelOneExpandCollapse">
        <div>
          <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
            <path fill="none" d="M0 0h24v24H0z"></path><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"></path>
          </svg>
        </div>
    </label>
</div>
```
CSS:
```CSS
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer{
  input:checked + div label[for=PanelOneExpandCollapse]{
    @apply rotate-180;
  }
}
```

**Comment by wongjn** [comment, marked as answer]
It does not work because the `input:checked + div label[for=PanelOneExpandCollapse]` rule is defined in an anonymous `@layer`, and any non-`!important` properties in rules in `@layer`s will be overridden by rules not in a `@layer`:

```css
.foo {
  background-color: red;
}

@layer {
  .foo[class] {
    background-color: green;
  }
}
```
The `background-color` of `.foo` would be `red`.

Hence, extending this to your example:

```css
*, ::before, ::after {
  /* … */
  --tw-rotate: 0;
  /* … */
}

@layer {
  /* … */
  input:checked + div label[for=PanelOneExpandCollapse] {
    --tw-rotate: 180deg;
  }
}
```
So the `--tw-rotate` value will always be `0` since the `*, ::before, ::after` is not in a `@layer` while `input:checked + div label[for=PanelOneExpandCollapse]` is in a `@layer`.

Consider either:
- Specifying the rotation outside the `@layer`:
  ```css
  @layer {
    /* … */
  }

  input:checked + div label[for=PanelOneExpandCollapse]{
    @apply rotate-180;
  }
  ```
  [Tailwind Play example](https://play.tailwindcss.com/lkuit9bFhK?file=css)
- Using `!important`:
  ```css
  @layer {
    /* … */
 
    input:checked + div label[for=PanelOneExpandCollapse]{
      @apply bg-gray-500;
      @apply rotate-180 !important;
    }
  }
  ```
  [Tailwind Play example](https://play.tailwindcss.com/mN5qwdXnWE?file=css)
- Using a utility class on the `<label>` element:
  ```html
  <label for="PanelOneExpandCollapse" class="[input:checked+div_&]:rotate-180">
  ```
  [Tailwind Play example](https://play.tailwindcss.com/mIxdTuta04)
