### DISCUSSION TITLE
Styling of indeterminate <progress> element seems broken - why?

### DISCUSSION THREAD

**Discussion by vsajip** [tailwindlabs/tailwindcss#11432] [Help]
This [Play snippet](https://play.tailwindcss.com/q6rFuXmWFD) illustrates. An indeterminate progress bar
```html
<progress id="main-progress" class="w-full"></progress>
```
with CSS
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

#main-progress {
  height: 4px;
}
```
should be animated, but just shows as a blue filled rectangle (similar to 100% progress). However, normally the bar should be animated to indicate its indeterminate nature, as seen in the first pen below.

[Pen showing styling with BS4](https://codepen.io/vsajip/pen/OJaMOWe)
[Pen showing what happens with Tailwind CSS](https://codepen.io/vsajip/pen/wvQMPdv)

For the second pen, I copy-pasted the generated CSS from the Play snippet into the pen's CSS.

Can anyone explain why this happens with Tailwind?

**Comment by wongjn** [comment]
It seems like the `border` styles from [Tailwind preflight](https://tailwindcss.com/docs/preflight):

```css
*,
::before,
::after {
  …
  border-width: 0;
  border-style: solid;
  border-color: #e5e7eb;
}
```

Interferes with the animation.
