### DISCUSSION TITLE
Unset CSS variable ?

### DISCUSSION THREAD

**Discussion by neviaumi** [tailwindlabs/tailwindcss#11564] [Help] [answered]
I am using `@tailwindcss/forms` for make radio input more customisable 

Everything is working fine. after install plugin the radio element was much simple to modify.

here is my code.

```html
<Label htmlFor={id} {...slotProps?.label}>
      <input
        id={id}
        name={name}
        onBlur={onBlur}
        onChange={onChange}
        onFocus={onFocus}
        type="radio"
        value={value}
        className='tw-form-radio tw-h-0 tw-w-0 tw-border-0 focus:tw-shadow-[0_0_rgb(0,0,0)]'
      />
      {children}
    </Label>
``` 

It was working on normal state of radio group.

But when the element in focus state below css will be generated

```css
.tw-form-radio:focus {
   outline: 2px solid transparent;
    outline-offset: 2px;
    --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
    --tw-ring-offset-width: 2px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: #2563eb;
    --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
    --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);
    box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
}
```

it would make my `focus:tw-shadow-[0_0_rgb(0,0,0)]` class not working because

```css
--tw-shadow: 0 0 rgb(0,0,0);
--tw-shadow-colored: 0 0 var(--tw-shadow-color);
box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
```

will reuse the value.

I have workaround by add `style=''--tw-ring-shadow': '0''` to input. 

but did it have better way to do that ?
