### DISCUSSION TITLE
Drop shadow not working

### DISCUSSION THREAD

**Discussion by tanerijun** [tailwindlabs/tailwindcss#11615] [Help] [answered]
**What version of Tailwind CSS are you using?**

For example: v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Remix v1.18.1

**What version of Node.js are you using?**

v18

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/j18fc6gFQJ

**Describe your issue**

The `drop-shadow` utility class is not working correctly. 

It's producing this class:
```css
.drop-shadow-2xl {
  --tw-drop-shadow: drop-shadow(0 25px 25px rgb(0 0 0 / 0.15));
  filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
}
```

When it should be the one below (according to the docs):
```css
filter: drop-shadow(0 25px 25px rgb(0 0 0 / 0.15));
```
