### DISCUSSION TITLE
Add items-last-baseline

### DISCUSSION THREAD

**Discussion by emctague** [tailwindlabs/tailwindcss#11623] [Ideas]
`last baseline` aligns items via their last, rather than first, baseline. This would be a useful addition to the `items-` classes:

```css
.items-last-baseline {
  align-items: last baseline;
}
```

There was an old discussion about this but it appears to have petered out without being acknowledged. It also suggested adding a `first-baseline`, but as far as I can tell, `first baseline` is equivalent to `baseline`.
