### DISCUSSION TITLE
Is there any way to generate class with custom logic with tailwindcss

### DISCUSSION THREAD

**Discussion by Yrobot** [tailwindlabs/tailwindcss#11668] [Help]
## the problem im facing
I want to change svg fill color and opacity for a svg icon, but `fill-red-700` not working, because the fill and fill-opacity are set in the svg file under path tag.

## possible solution

I find that overwrite the fill for fill class will work, for example:
```css
.icon path{
  fill: red;
}
```

then add the .icon class to svg. finally the icon color turns to red.

So, i was wondering that is there a way to generate the `.icon path` class by typing `icon-path-red` for the tag class.

## the repreduce demo 
https://play.tailwindcss.com/Y35oVktC3Q
<img width="1086" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/28182882/c6978199-0f25-43a4-8076-56ce0ac68766">

**Comment by Yrobot** [comment]
## A template solution for this
```css
.icon path {
    fill: var(--svg-fill, #000);
    fill-opacity: var(--svg-fill-opacity, 1);
 }
```
```jsx
<Icon icon="info" className="icon [--svg-fill:red]" />
```
