### DISCUSSION TITLE
Add `all-inherit` utility

### DISCUSSION THREAD

**Discussion by williamsjokvist** [tailwindlabs/tailwindcss#11675] [Ideas]
For inheriting all CSS properties from the parent element and resetting the elements own:
```css
.all-inherit {
    all: inherit;
}
```
It's a niche property but can come handy at times. WDYT?

[Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/all)
