### DISCUSSION TITLE
How do I make a dynamic `border-color` using a Tailwind `className`?

### DISCUSSION THREAD

**Discussion by hirehamir** [tailwindlabs/tailwindcss#11754] [Help] [answered]
```css
/* @TODO: Push this into a Tailwind `className`. */
#test {
  border-color: rgb(var(--foreground-rgb));
}
```
What `className` do I give to the element with id `test` so that its `border-color` changes dynamically depending on what the foreground RGB is?
