### DISCUSSION TITLE
Why can't modifiers set arbitrary classes with `group` for children to use?

### DISCUSSION THREAD

**Discussion by MaxMonteil** [tailwindlabs/tailwindcss#11862] [Help] [answered]
Hello everyone!
I've run into a situation where I expected some styles to work but they don't.

The idea is to have a parent element with `.group` and an arbitrary class that gets toggled based on a custom directive/modifier. I could then style children elements with `group-[.is-active]:some-style`.

I created a minimal example along with some hand written CSS that I think matches what I expected Tailwind to generate.
The DIY CSS does work and I'm not sure why it doesn't in Tailwind.

[Tailwind Play example](https://play.tailwindcss.com/MgsRYnTPWk)

In case the link above doesn't work:

```html
<section class="has-active-checkbox:border-green-500 has-active-checkbox:is-active group arbitrary m-4 border-2 border-blue-500 p-4">
  <label>
    <input type="checkbox" />
    <p class="block group-[.arbitrary]:font-bold group-[.is-active]:hidden">Is not active</p>
    <p class="hidden group-[.arbitrary]:font-bold group-[.is-active]:block">Is active</p>
  </label>
</section>
```

```css
.has-active-checkbox\:is-active:has(input[type='checkbox']:checked) .group-\[\.is-active\]\:block {
    display: block;
}

.has-active-checkbox\:is-active:has(input[type='checkbox']:checked) .group-\[\.is-active\]\:hidden {
    display: none;
}
```

```js
// tailwind config
module.exports = {
  plugins: [
    require('tailwindcss/plugin')(({ addVariant }) => {
      addVariant('has-active-checkbox', "&:has(input[type='checkbox']:checked)")
    }),
  ],
}
```
