### DISCUSSION TITLE
Arbitrary values don't work when using a responsive variant for grid-template-columns

### DISCUSSION THREAD

**Discussion by sebpowell** [tailwindlabs/tailwindcss#11873] [Help]
**What version of Tailwind CSS are you using?**

For example: v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 13.4.1

**What version of Node.js are you using?**

18.14.0

**What browser are you using?**

Brave

**What operating system are you using?**

OSX

**Reproduction URL**

https://play.tailwindcss.com/Qt1wDyijtD

**Describe your issue**

I'm trying to get `.grid-cols` to work using arbitrary values and responsive variants. The example provided at the end [here](https://tailwindcss.com/docs/grid-template-columns) seems to work fine, but not if targeting a breakpoint (e.g. `grid-cols-[200px_minmax(900px,_1fr)_100px]` works, but `lg:grid-cols-[200px_minmax(900px,_1fr)_100px]` doesn't – see the playground link). 

I can't see anything in the docs that suggests this shouldn't work, so I'm guessing this might be a bug?

**Comment by wongjn** [comment]
Thank you for the report! Could you provide more details about how it doesn't work? Your linked Tailwind Play does output the expected CSS:

```css
@media (min-width: 1024px){
  .lg\:grid-cols-\[200px_minmax\(900px\2c _1fr\)_100px\]{
    grid-template-columns: 200px minmax(900px, 1fr) 100px
  }
}
```
