### DISCUSSION TITLE
Tailwindcss classes leaking beyond the context of the library?

### DISCUSSION THREAD

**Discussion by jayarjo** [tailwindlabs/tailwindcss#11920] [Help] [answered]
I have created a certain library for the client using Tailwindcss, however a client now has a problem he says that classes in the my lib conflict with styles on his site. Technically my lib is transpiled and bundled as a single js file, so I don't quite understand what he means by conflicting. How can it be conflicting with anything when I'm using scss modules and apply Tailwindcss classes only in dedicated files via @apply clause? Do Tailwindcss classes somehow leak beyond library boundaries, is this even possible?

**Comment by jayarjo** [comment]
I've now examined generated css file and noticed that at the end it has appended some tailwindcss classes that I used directly in html. That's an obvious problem and I've stripped them now. I believe I do not have any other places in my library where I use classes directly. However after the build the following still gets appended to the generated css file:

```css
.container{
    width:100%
}
@media (min-width: 600px){
    .container{
        max-width:600px
    }
}
@media (min-width: 640px){
    .container{
        max-width:640px
    }
}
@media (min-width: 768px){
    .container{
        max-width:768px
    }
}
@media (min-width: 1024px){
    .container{
        max-width:1024px
    }
}
@media (min-width: 1280px){
    .container{
        max-width:1280px
    }
}
@media (min-width: 1536px){
    .container{
        max-width:1536px
    }
}
.visible{
    visibility:visible
}
.absolute{
    position:absolute
}
.relative{
    position:relative
}
.block{
    display:block
}
.flex{
    display:flex
}
.hidden{
    display:none
}
.transform{
    transform:translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skew(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
}
.border{
    border-width:1px
}
 
```

Is there a way to prevent this somehow?

Does anybody even know where does it come from? Clearly it's tailwindcss (because of tw- prefix)
