### DISCUSSION TITLE
Multiple CSS selectors

### DISCUSSION THREAD

**Discussion by cmi23** [tailwindlabs/tailwindcss#12029] [Help]
Is it possible to write this with tailwind?

```css
[data-scope="parent"] [data-part="child1"] {
  background-color: red;
}
```

```tsx
<div data-scope="parent" className="...">
   <div data-part="child1" />
   <div data-part="child2" />
</div>
```

I want to only modify the parent's `className`.
