### DISCUSSION TITLE
Combination of TW JS based config and a class causes malformed CSS

### DISCUSSION THREAD

**Discussion by robdekort** [tailwindlabs/tailwindcss#12106] [Help] [answered]
Hey folks, I'm running into an odd issue that I can't wrap my head around. Maybe someone here understand why this happens. 

 What I have is this:

**A Tailwind config file with the following:**
```js
'@media screen(md)': {
  '.outer-grid': {
    rowGap: theme('spacing.16'),
    paddingTop: theme('spacing.16'),
    paddingBottom: theme('spacing.16'),
  },
  '.outer-grid>*:last-child:is(.w-full)': {
    marginBottom: `-${theme('spacing.16')}`,
  },
},
```

**A class in my templates**
 `[&>*]:after:w-full`

The combination of this JS config and this class trips up something and results in compilation warings and the following CSS in my compiled file:

```css
@media (min-width: 768px) {
        {
        content: var(--tw-content);
        row-gap: 4rem;
        padding-top: 4rem;
        padding-bottom: 4rem
    }

    .outer-grid>*:last-child:is(.\[\&\>\*\]\:before\:w-full>*):before {
        content: var(--tw-content);
        margin-bottom: -4rem
    }
}
```

I noticed this because of the error `npm run build` produces:

```
warnings when minifying css:
▲ [WARNING] Unexpected "{" [css-syntax-error]

    <stdin>:2610:3:
      2610 │    {
```

And I can even see in VS code with the TW extension the malformed CSS when I hover over this one class:
<img width="893" alt="Screenshot_2023-09-28_at_17 09 03" src="https://github.com/tailwindlabs/tailwindcss/assets/69107412/a8730642-f74d-43e7-8439-0c0903778464">

When I either:

- Remove the class from my templates, or
- Remove the ` '.outer-grid>*:last-child:is(.w-full)'` statement from the `@media sceen(md)` query,

the warning and malformed CSS is gone. Note that the ` '.outer-grid>*:last-child:is(.w-full)'` statement _not_ in a media query compiles without issues.

Does anyone know what could be the issue here?

Thanks in advance!
