### DISCUSSION TITLE
`@dark` directive for applying selector only when tailwind's dark mode is active.

### DISCUSSION THREAD

**Discussion by henriquekirchheck** [tailwindlabs/tailwindcss#12163] [Ideas]
The idea is to have a `@dark` directive that would modify the selector to only be applied only when tailwind's dark mode is active, something like:

```css
.backgroud {
  @apply bg-local bg-center bg-repeat;
  background-image: linear-gradient(
      to bottom,
      #d3d3d3 0%,
      transparent 8%,
      transparent 92%,
      #d3d3d3 100%
    ),
    url("/img/light-bg.png");
}
@dark .background {
  background-image: linear-gradient(
      to bottom,
      #262626 0%,
      transparent 8%,
      transparent 92%,
      #262626 100%
    ),
    url("/img/dark-bg.png");
}
```

or even something like a media selector, like this:

```css
.backgroud {
  @apply bg-local bg-center bg-repeat;
  background-image: linear-gradient(
      to bottom,
      #d3d3d3 0%,
      transparent 8%,
      transparent 92%,
      #d3d3d3 100%
    ),
    url("/img/light-bg.png");
}
@dark {
  .background {
    background-image: linear-gradient(
        to bottom,
        #262626 0%,
        transparent 8%,
        transparent 92%,
        #262626 100%
      ),
      url("/img/dark-bg.png");
  }
}
```
---

For me to get a similar result, I added this to the tailwind config:

```ts
const config = {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  // darkMode: "class",

  theme: {
    extend: {
      backgroundImage: {
        "dark-bg": `
        linear-gradient(to bottom, #262626 0%, transparent 8%, transparent 92%, #262626 100%),
        url('/img/dark-bg.png')
        `,
        "light-bg": `
        linear-gradient(to bottom, #d3d3d3 0%, transparent 8%, transparent 92%, #d3d3d3 100%),
        url('/img/light-bg.png')
        `,
      },
    },
  },
};
```
but this seems wasteful because I'm only going to use this once in the entire page.

I know I could just write out the media query or the class, but it would be more convenient for this to be managed by tailwind.

All the other discussions mentioning something like this were asking for help, and in the most part the replies mentioned that you should write the media query or the class.
