### DISCUSSION TITLE
Opacity does not works if fallback colors are passed to hsl() while defining custom colors

### DISCUSSION THREAD

**Discussion by hashedalgorithm** [tailwindlabs/tailwindcss#12243] [Help] [answered]
@wongjn
Setup:

These are the fallback colors. which i defined in the global.css.
```
@layer base {
  :root {
    --primary: 346.8 77.2% 49.8%;
    --primary-foreground: 355.7 100% 97.3%;
  }
  .dark {
    --primary: 346.8 77.2% 49.8%;
    --primary-foreground: 355.7 100% 97.3%;
  }
}
```
So i am trying to like set fallback color to primary if my custom-primary is not availbale.
tailwin.config.ts.
```
primary: {
          DEFAULT: "hsl(var(--custom-primary, var(--primary)))",
          foreground:
            "hsl(var(--custom-primary-foreground, var(--primary-foreground)))",
        },
```

Theme Context Provider.tsx

```
<Head>
          <style>
            {`
                :root {
                  ${
                    theme.light.primary
                      ? `--primary: ${theme.light.primary};`
                      : ""
                  }
                  ${
                    theme.light.primaryForeground
                      ? `--custom-primary-foreground: ${theme.light.primaryForeground};`
                      : ""
                  }
                }
              
              .dark {
                ${
                  theme.dark.primary
                    ? `--custom-primary: ${theme.dark.primary};`
                    : ""
                } 
                ${
                  theme.dark.primaryForeground
                    ? `--custom-primary-foreground: ${theme.dark.primaryForeground};`
                    : ""
                }
              }
              
            `}
          </style>
        </Head>
```
In my context provider which wraps the whole application I set the custom colors which i fetch from db respective to the user.

The issue: 
```
<div className="w-20 h-20 bg-primary/90 border border-red-500"></div>
      <div className="w-20 h-20 bg-primary border border-green-500"></div>
```
If try to change opacity of my primary color it does'nt work.

Output:
![image](https://github.com/tailwindlabs/tailwindcss/assets/53309069/8c60d2c1-cd91-49c0-a5a7-f9e8ef9d7bad)

If i pass only one color below code this works perfectly. is this tailwind's bug or something.?
 "hsl(var(--custom-primary-foreground))"

**Comment by wongjn** [comment, marked as answer]
As per [the documentation](https://tailwindcss.com/docs/customizing-colors#using-css-variables):

> Then define your colors in your configuration file, being sure to include the color space you’re using, and the special `<alpha-value>` placeholder that Tailwind will use to inject the alpha value when using an opacity modifier:
>
> ```js
> /** @type {import('tailwindcss').Config} */
> module.exports = {
>   theme: {
>     colors: {
>       // Using modern `rgb`
>       primary: 'rgb(var(--color-primary) / <alpha-value>)',
>       secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
> 
>       // Using modern `hsl`
>       primary: 'hsl(var(--color-primary) / <alpha-value>)',
>       secondary: 'hsl(var(--color-secondary) / <alpha-value>)',
> 
>       // Using legacy `rgba`
>       primary: 'rgba(var(--color-primary), <alpha-value>)',
>       secondary: 'rgba(var(--color-secondary), <alpha-value>)',
>     }
>   }
> }
> ```

So for your case, you colors should look like:

```js
primary: {
  DEFAULT: "hsl(var(--custom-primary, var(--primary)) / <alpha-value>)",
  foreground:
    "hsl(var(--custom-primary-foreground, var(--primary-foreground)) / <alpha-value>)",
},

**Reply by lord007tn** [reply]
not working in my case for tailwind 3.4.1
when using hsl tailwind cant read color when i remove alpha-value it seems to work okay but can't use opacity

**Reply by wongjn** [reply]
Consider not removing the `<alpha-value>`.

**Reply by lord007tn** [reply]
when i add <alpha-value> colors don't work at all
so i removed it

when i use hex values for colors everything works fine
so there is a problem in hsl representation

**Reply by wongjn** [reply]
How do you add you colors? It could be that you are adding them in an incorrect way.

**Reply by lord007tn** [reply]
this is the scss file 
```scss
@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 212.05 63.48% 22.55%;

    --card: 0 0% 100%;
    --card-foreground: 212.05 63.48% 22.55%;

    --popover: 0 0% 100%;
    --popover-foreground: 212.05 63.48% 22.55%;

    --primary: 43.29 100% 50%;
    --primary-foreground: 210 40% 98%;

    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;

    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;

    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;

    --destructive: 0, 98.78%, 67.84%;
    --destructive-foreground: 210 40% 98%;

    --success: 141.86, 60.34%, 54.51%;
    --success-foreground: 210 40% 98%;

    --warning: 46.03, 96.48%, 55.49%;
    --warning-foreground: 210 40% 98%;

    --info: 200.39, 100%, 60.2%;
    --info-foreground: 210 40% 98%;

    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 43.29 100% 50%;
    --radius: 0.5rem;
  }
  }
```
this is my colors: 
```js
colors: {
        border: 'hsl(var(--border) / <alpha-value></alpha-value>)',
        input: 'hsl(var(--input) / <alpha-value>)',
        ring: 'hsl(var(--ring) / <alpha-value>)',
        background: 'hsl(var(--background) / <alpha-value>)',
        foreground: 'hsl(var(--foreground) / <alpha-value>)',
        primary: {
          DEFAULT: 'hsl(var(--primary) / <alpha-value>)',
          foreground: 'hsl(var(--primary-foreground) / <alpha-value>)'
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary) / <alpha-value>)',
          foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)'
        },
        muted: {
          DEFAULT: 'hsl(var(--muted) / <alpha-value>)',
          foreground: 'hsl(var(--muted-foreground) / <alpha-value>)'
        },
        accent: {
          DEFAULT: 'hsl(var(--accent) / <alpha-value>)',
          foreground: 'hsl(var(--accent-foreground) / <alpha-value>)'
        },
        popover: {
          DEFAULT: 'hsl(var(--popover) / <alpha-value>)',
          foreground: 'hsl(var(--popover-foreground) / <alpha-value>)'
        },
        card: {
          DEFAULT: 'hsl(var(--card) / <alpha-value>)',
          foreground: 'hsl(var(--card-foreground) / <alpha-value>)'
        },
      },
```
