### DISCUSSION TITLE
Add grid subgrid util

### DISCUSSION THREAD

**Discussion by csprle** [tailwindlabs/tailwindcss#12276] [Ideas]
As subgrid is now supported for the major browsers ([see Can I use](https://caniuse.com/?search=subgrid)) I think it would make sense to include this into the grid-cols and grid-rows utility. 

My proposal would be 

``` css
.grid-cols-subgrid {
  grid-template-columns: subgrid;
}

.grid-rows-subgrid {
  grid-template-rows: subgrid;
}
```

More info about subgrid can be found [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid).
