### DISCUSSION TITLE
How to make border animation like this?

### DISCUSSION THREAD

**Discussion by yuxxeun** [tailwindlabs/tailwindcss#12348] [Help] [answered]
I found [this site](https://ranboofashion.vercel.app/) and starting wondering.

How to make animation like in this section with Tailwindcss, border come from right and then when mouse leaving border leaving to left

![image](https://github.com/tailwindlabs/tailwindcss/assets/50067865/d3075b10-4bab-4f68-b5f4-efd704cb5f3b)

and i just look the source code (which is using vanilla css), look like this:
```css
.link-foot:after {
    content: '';
    position: absolute;
 
    width: 100%;
    transform: scaleX(0);
    height: 1px;
    bottom: 0;
    left: 0;
    background-color: white;
    transform-origin: bottom right;
    transition: transform 1s ease-out;
}
.link-foot:hover:after {
    transform: scaleX(1);
    transform-origin: bottom left;
}
```
