### DISCUSSION TITLE
declaring nested animations in tailwind.config.js?

### DISCUSSION THREAD

**Discussion by wolfspyre** [tailwindlabs/tailwindcss#12389] [Ideas]
so... perhaps I'm just odd; 
however I was trying to extend my theme's animation declarations:

`tailwind.config.js`:
```js
module.exports = {
  theme: {
    ...
    extend: {
      animation: { 
        'grow-left-worky':       'grow-left 200ms 500ms   1 both alternate linear',
        'grow-left-noworky':      { name: 'grow-left', duration: '200ms', timingFunction: 'linear', iterationCount: '1', delay: '500ms' },
      },
      keyframes: {
        'grow-left': {
          '0%': { transform: 'scaleX(0.0)', transformOrigin: 'right'},
          '100%': {transform: 'scaleX(1.0)', transformOrigin: 'right'},
        }, 
      },
    },
  },
},

```

results in:
```
TypeError: input.split is not a function
   at parseAnimationValue (node_modules/tailwindcss/lib/util/parseAnimationValue.js:50:28)
   at animate (node_modules/tailwindcss/lib/corePlugins.js:1302:67)
```
Which afaict is referring to [this line in parseAnimationValue.js][parseAnimationValue.js][^1]...  My question is 
 
### Shouldn't one be able to explicitly declare the parameters of an animation, given that the same declaration format is encouraged for keyframes?

From my perspective, it seems like a nice bit of sugar to permit the user to just throw a pile of attributes at the parser and expect it to 'do what I mean' ....  (thank you, it really is quite pleasant and friendly)

but I fail to see the downside to of supporting, if not actively encouraging the equivalent declaration syntax of related properties...  

I'd imagine it would be (admittedly marginally) faster to consume a blob of kv pairs as named  than trying to iteratively invoke voodoo against (reasonably predictable) values and hoping for a match... 

Am I missing something really obvious?

[parseAnimationValue.js]: <https://github.com/tailwindlabs/tailwindcss/blob/master/src/util/parseAnimationValue.js#L22>
[^1]: <https://github.com/tailwindlabs/tailwindcss/blob/master/src/util/parseAnimationValue.js#L22>

**Comment by wongjn** [comment]
> Shouldn't one be able to explicitly declare the parameters of an animation, given that the same declaration format is encouraged for keyframes?

As per the line you linked:

https://github.com/tailwindlabs/tailwindcss/blob/1648b864c16f95d5cada83b2a3011099408d4467/src/util/parseAnimationValue.js#L22

The function expects a string, so an object would indeed produce an error as per your original post.

I believe the `keyframes` format is the way it is because in CSS, it follows a similar pattern:

```css
@keyframes grow-left {
  '0%' {
    transform: scaleX(0.0);
    transform-origin: right;
  '100%' {
    transform: scaleX(1.0);
    transform-origin: right;
  }, 
},
```
```js
keyframes: {
  'grow-left': {
    '0%': {
      transform: 'scaleX(0.0)',
      transformOrigin: 'right'
    },
    '100%': {
      transform: 'scaleX(1.0)',
      transformOrigin: 'right'
    },
  }, 
},
```

But this is not the same for `animation`, which expects a value. This means this equivalent in CSS would be invalid:

```css
.animation-grow-left-noworky {
  animation {
    name: grow-left;
    duration: 200ms;
    timing-function: linear;
    iteration-count: 1;
    delay: 500ms;
  }
}
```
Though I presume you may wish for it to work like:

```css
.animation-grow-left-noworky {
  animation-name: grow-left;
  animation-duration: 200ms;
  animation-timing-function: linear;
  animation-iteration-count: 1;
  animation-delay: 500ms;
}
```
Or for Tailwind to flatten the object down all the way down to a single `animation` shorthand declaration. This seems more like an feature request than a help request at this point.

> Am I missing something really obvious?

"Obvious" is a matter of perspective, though I'd say in the utility-based paradigm of Tailwind, there isn't much benefit than to have it in a single `animation` declaration like `grow-left-worky`.

If you really wanted the object-based version in your configuration, you could consider flattening the object yourself like:

```js
'grow-left-noworky':
  Object.values({
    name: 'grow-left',
    duration: '200ms',
    timingFunction: 'linear',
    iterationCount: '1',
    delay: '500ms'
  }).join(' '),
```

Though again, if your point is that Tailwind should do this for you, I feel like this post would have been more appropriate as an 💡Idea post, rather than a 🙏Help post.
