### DISCUSSION TITLE
Fallback for custom font to Tailwind's font-sans

### DISCUSSION THREAD

**Discussion by mitar** [tailwindlabs/tailwindcss#12384] [Help] [answered]
I use font-sans for most of my content on the website. But for the logo & name I want to use a custom font. The issue is that I would like to have a fallback to font-sans list of fonts if that custom font fails to load (instead of browser going for Times New Roman). How can I do that?

The following for example does not work:

```css
@layer components {
  .mylogo {
    font-family: 'CustomFont', @apply font-sans;
  }
}
```
