### DISCUSSION TITLE
Add stretch value to length width, height styles.

### DISCUSSION THREAD

**Discussion by goldnite** [tailwindlabs/tailwindcss#12424] [Ideas]
Stretch is not supported currently.

I think it would be nice if we add these values.

```css
.w-stretch {
  width: -webkit-fill-available;
  width: -moz-available;
  width: stretch;
}

.min-w-stretch {
  min-width: -webkit-fill-available;
  min-width: -moz-available;
  min-width: stretch;
}

.max-w-stretch {
  max-width: -webkit-fill-available;
  max-width: -moz-available;
  max-width: stretch;
}

.h-stretch {
  height: -webkit-fill-available;
  height: -moz-available;
  height: stretch;
}

.min-h-stretch {
  min-height: -webkit-fill-available;
  min-height: -moz-available;
  min-height: stretch;
}

.max-h-stretch {
  max-height: -webkit-fill-available;
  max-height: -moz-available;
  max-height: stretch;
}
```
