### DISCUSSION TITLE
Custom themes/variants based on prefix (similar to "dark")

### DISCUSSION THREAD

**Discussion by marknuyens** [tailwindlabs/tailwindcss#12421] [Ideas]
Perhaps this is an idea so simple that it has already been considered inside and out, but perhaps it's so simple it hasn't. ;-)

Anyway, I was thinking on ways to create a few themes and couldn't quite figure out how to do so. I did find ways like adjusting some config rules, setting CSS variables, etc.

My idea would suggest using the same method as `dark`, implying this is essentially a theme. Similar to how we handle `dark` styling, we could style an element using a custom keyword, e.g. "onyx" in case we're designing a theme called "Onyx".

Styling would then look like this:

```html
<section class="bg-white text-black p-8 font-sans onyx:font-serif onyx:bg-stone-800 onyx:text-gray-200">
...
</section>
```

In conclusion, this idea would allow users to create their own custom theme keyword, of which `dark` is a default example, and would match any other elements using that same theme name (in our case `onyx`).

Let me know what you all think! ;-) Including @adamwathan, of course.

**Comment by dario-baumberger** [comment]
This config should work for you:

```ts
/** @type {import('tailwindcss').Config} */

const plugin = require("tailwindcss/plugin");

module.exports = {
  plugins: [
    plugin(function ({ addVariant, e }) {
      addVariant("onyx", ".onyx &");
    })
  ]
};
```

With `addVariant("onyx", ".onyx &");` the result is roughly the same as if `darkMode: 'class'` is set, simply without `is()` in the generated css.

```css
.onyx .onyx\:border-green-500 { --tw-border-opacity: 1; border-color: rgb(34 197 94 / var(--tw-border-opacity)); }
```

The difference between with `is` and without `is`, is the specificity of the selector. 

If you want to have it with `is`, you can try this. I haven't tried it myself, but it should work: 
```ts
addVariant("onyx", `:is(.onyx &)`)
```

Result:
```css
:is(.onyx .onyx\:border-green-500) {
  --tw-border-opacity: 1;
  border-color: rgb(34 197 94 / var(--tw-border-opacity));
}
```
