### DISCUSSION TITLE
How to custom `*, ::before, ::after`, in uniapp of mp-weixin not support unexpected token "*"

### DISCUSSION THREAD

**Discussion by seepine** [tailwindlabs/tailwindcss#12437] [Help]
## Question
postcss.config.js
```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

tailwind.config.js
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
    }
  },
  plugins: [],
}
```

And got
```sh
[自动热重载错误 WXSS 文件编译错误] ./app.wxss
 unexpected token "*"
   6 | */
   7 | 
>  8 | *,
     | ^
   9 | ::before,
  10 | ::after {
  11 |   box-sizing: border-box; /* 1 */
at files://app.wxss#8(env: macOS,mp,1.06.2307250; lib: 3.2.1)
```

the app.wxss
```css
/*
! tailwindcss v3.3.5 | MIT License | https://tailwindcss.com
*//*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/

*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}

/* ...... */
```

## 

how to make 
```css
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}
```
transform like this

```css
page,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}
```
