### DISCUSSION TITLE
Invalid css rules generated

### DISCUSSION THREAD

**Discussion by scv057** [tailwindlabs/tailwindcss#12449] [Help]
I want to make my dialog component to be in the center of screen, I got css rules as below, but it doesn't work. I guess it's caused by empty css variables, after I deleted ` rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))` it works.
``` css
.-translate-x-1\/2 {
    --tw-translate-x: -50%;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
```

**Comment by wongjn** [comment]
You should have a rule like:

```css
*, ::before, ::after{
  /* … */
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  --tw-skew-y: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
  /* … */
}
```
Generated from Tailwind CSS. If you do not, consider checking you have included the `@tailwind base` directive in your source CSS.
