### DISCUSSION TITLE
How to achieve something like `w-xl`?

### DISCUSSION THREAD

**Discussion by frank-laemmer** [tailwindlabs/tailwindcss#12501] [Help] [answered]
There is `max-w-xl`, `max-w-2xl` and so on. I would like to have `w-xl`, `w-2xl` and so on. What's the best way to set that up? I also want to able to combine it with media queries like `xl:w-2xl` and so on. At best I can later change values for `xl` globally.

I know there is `w-[32rem]` but I consider that to be too fragile. Thanks!

Something like:

```css
/* dummy code */
@layer utilities {
  .w-xl  { width: var(--xl) }
  .w-2xl { width: var(--2xl) }
  .w-3xl { width: var(--3xl) }
  .w-4xl { width: var(--4xl) }
  .w-5xl { width: var(--5xl) }
  .w-6xl { width: var(--6xl) }
}
```

```html
<div class=w-[(theme(screen.xl))]>Or like so?</div>
```
