### DISCUSSION TITLE
Issue with Multi-Level theme() Transformations in tailwind.config.ts

### DISCUSSION THREAD

**Discussion by amotarao** [tailwindlabs/tailwindcss#12612] [Help]
I've been working with design tokens in Tailwind CSS and frequently use the `theme()` function in my tailwind.config.ts file to leverage these tokens. However, I've encountered an issue when applying `theme()` at multiple levels.

In cases where `theme()` is used in successive stages, it appears that only the first level of transformation is being processed, leaving subsequent levels unchanged. This behavior limits the utility of nested design tokens, which are crucial for a more dynamic and scalable styling strategy.

I'm looking for a way to ensure that theme() processes transformations through all levels, achieving the desired end result. If anyone has insights or solutions to this issue, your input would be greatly appreciated.

## Sample

https://github.com/amotarao/tailwindcss-theme-recursion

```ts
// tailwind.config.ts
export default {
  theme: {
    extend: {
      height: {
        nav: "theme(spacing.16)",
      },
    },
  },
} satisfies Config;
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html class="scroll-pt-[theme(height.nav)]">
  <body>
    <nav class="h-nav">navigation</nav>
  </body>
</html>
```

```css
/* output.css */
.h-nav {
  height: 4rem; /* <- transformed */
}

.scroll-pt-\[theme\(height\.nav\)\] {
  scroll-padding-top: theme(spacing.16); /* <- only first level was transformed */
}
```
