### DISCUSSION TITLE
Dark mode on printers

### DISCUSSION THREAD

**Discussion by dario-baumberger** [tailwindlabs/tailwindcss#12628] [Help] [answered]
We have an application that has a light mode and a dark mode. We need to be able to print some pages. If dark mode is active, this means that the page is printed in dark mode. I assume that nobody wants this - after all, we all put white paper in the printer. :)

Here is a code example with a simple HTML file and a simple tailwind setup: https://stackblitz.com/~/github.com/dario-baumberger/taiwlindcss-dark-mode-print-dialog

- `npm i`
- `npm run tw`
- `npm run serve`

In the printer preview there is the setting whether "background graphics" should be printed. It works in the code example. The switch button removes the background and adjusts the font colour. This is basically okay, but we should be able to define the behaviour more precisely.

![image](https://github.com/tailwindlabs/tailwindcss/assets/10287381/2cf1dc25-54e6-4f0f-8e91-615669bc7460)

![image](https://github.com/tailwindlabs/tailwindcss/assets/10287381/a8cd86e5-dfe7-4833-8434-7fc111724d42)

We could set the colours explicitly for light: dark: and print:, that should work. However, light: and print: would always be exactly the same. 

We have tried various things. The desired output should look like this:
```css
@media not print {
.dark .dark\:border-green-500 {
    --tw-border-opacity: 1;
    border-color: rgb(34 197 94 / var(--tw-border-opacity));
  }
...
}
```

Unfortunately, we didn't manage to do this...

For this to work with the dark class `darkMode: "false"? in tailwind.config.js, 
must be set. Otherwise all addVariant('dark', '...') which have dark as variantName will not work.

---

With `addVariant("dark", ".dark &");` the result is roughly the same as if darkMode: 'class' is set, simply without is().

```css
.dark .dark\:border-green-500 { --tw-border-opacity: 1; border-color: rgb(34 197 94 / var(--tw-border-opacity)); }
```
---

In the documentation there is an example with @media https://tailwindcss.com/docs/plugins#static-variants

None of this worked:

---
tailwind.config.js:
```ts
 addVariant('dark', '@media not print .dark &')
```

Result:
```css
@media not print .dark & {
  .dark\:border-green-500 {
    --tw-border-opacity: 1;
    border-color: rgb(34 197 94 / var(--tw-border-opacity));
  }
...}
```
no valid css or results

---

tailwind.config.js:
```ts
addVariant('dark', '@media not print .dark');
```

Result:
```css
@media not print .dark {
  .dark\:border-green-500 {
    --tw-border-opacity: 1;
    border-color: rgb(34 197 94 / var(--tw-border-opacity));
  }
...
}
``` 
no valid css or results

---

In the v2.2.16 documentation there are further examples of how to extend flexibly:
https://v2.tailwindcss.com/docs/plugins#complex-variants

That didn't work either:

---
tailwind.config.js:
```ts
addVariant("dark", ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `@media not print {.dark .${e(
            dark${separator}${className}
          )}}`;
        });
      });
```

Result:
```css
@media not print {.dark .dark\:border-green-500} {
  --tw-border-opacity: 1;
  border-color: rgb(34 197 94 / var(--tw-border-opacity));
}
```
no valid css or results

---

Is there a way to solve this? I haven't found anything in the documentation. I have looked at the code, but have not found a solution either?

**Comment by fordaaron** [comment, marked as answer]
To get your desired output, you can update your addVariant to
```js
addVariant('dark', '@media not print { .dark & }')
```

This will output css of
```css
@media not print {
  .dark .dark\:border-green-500{
    --tw-border-opacity: 1;
    border-color: rgb(34 197 94 / var(--tw-border-opacity))
  
  /* ... */
}
```

Additionally, using `darkMode: null`, instead of `darkMode: 'false'`, will resolve the ts error.

Example: https://play.tailwindcss.com/ARHjiqGpf5?file=config

---

If you want to have the same css output as v3.4.0 of tailwind, but within the `@media not print {...}`, you could do 
```js
addVariant('dark', '@media not print { :is(:where(.dark) &) }')
```

This will output css of
```css
@media not print {
  :is(:where(.dark) .dark\:border-green-500){
    --tw-border-opacity: 1;
    border-color: rgb(34 197 94 / var(--tw-border-opacity))
  
  /* ... */
}
```

Example: https://play.tailwindcss.com/M8YQLdVeki?file=config
