### DISCUSSION TITLE
Prevent using the checkout token

### DISCUSSION THREAD

**Discussion by spencerdcarlson** [tailwindlabs/tailwindcss#12685] [Ideas]
for [stefanzweifel/git-auto-commit-action@v5](https://github.com/stefanzweifel/git-auto-commit-action) Is it possible to prevent using the checkout token by overriding it with `${{github.token}}`? I have to use a github personal token for checkout so I can checkout submodules, but I do not want my push to master to trigger another pipeline.

[checkout multiple repos private](https://github.com/actions/checkout?tab=readme-ov-file#checkout-multiple-repos-private)

Here is the relevant part of my current config. The push to master triggers a cyclical pipeline.  

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true              # required for submodules (client)
          token: ${{ secrets.GH_PAT }}  # required for submodules
          ...
     - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
```

**Comment by spencerdcarlson** [comment]
I was able to work around this by overriding the commit message

```yaml
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: "[skip actions] Update deployment.yaml to use ${{ env.tag }} image"
```
