### DISCUSSION TITLE
Exploring shadow layering

### DISCUSSION THREAD

**Discussion by tcolinpa** [tailwindlabs/tailwindcss#12732] [Ideas]
As of v3.4, tailwind doesn't support shadow layering since the box-shadow utility outputs something like this

```css
/* md example */
.shadow-md {
  --tw-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
  --tw-shadow-colored: 0 4px 6px -1px var(--tw-shadow-color), 0 2px 4px -2px var(--tw-shadow-color);
  box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
}
```

One problem I keep finding while using this is a way to keep consistent shadows and being able to be creative on the fly, without the need to reach out to tailwind.config or/and globals.css. Yes, one simple way is just to use arbitrary values and you're good to go.

However if you want to tokenize these single shadows to then layer and sequence them the way you want is pretty hard.

For sake of convenience, let's say a "shade" is one layer of one "shadow" as in `box-shadow: var(--shade-1), var(--shade-2), [...]`. One utility could just simply put together all these shades and the order you put is respected on the output, but I got no clue on how to do that and be simplistic and intuitive. Some problems:

- there's no practical way to know how much layers there is on one shadow (is there?)
- how can the layer sequence be guaranteed?
