### DISCUSSION TITLE
`group-aria-[activedescendant=value_with_underscores]` breaks

### DISCUSSION THREAD

**Discussion by foca** [tailwindlabs/tailwindcss#12760] [Help]
**What version of Tailwind CSS are you using?**

v3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CLI with PostCSS (8.4.32)

**What version of Node.js are you using?**

v20.10.0

**What browser are you using?**

Safari desktop

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/zQJUaXXLSs?size=540x720

**Describe your issue**

I'm trying to implement a combobox and using `aria-activedescendant` to mark the currently focused item. I attempted to use `group-aria` styles to style the active element in the listbox, but it's not working.

From that reproduction URL, you can see that the class `group-aria-[activedescendant=option_1]/listbox:text-white` generates the following CSS:

``` css
.group\/listbox[aria-activedescendant=option 1] .group-aria-\[activedescendant\=option_1\]\/listbox\:text-white{
  --tw-text-opacity: 1;
  color: rgb(255 255 255 / var(--tw-text-opacity))
}
```

Where the parent element has a space in the attribute value (`option 1` instead of `option_1`). This happens for any value of `aria-activedescendant` with an underscore. However, if the values used dashes, like `option-1`, it works.
