### DISCUSSION TITLE
How to automatically switch to dark mode

### DISCUSSION THREAD

**Discussion by ponjs** [tailwindlabs/tailwindcss#12766] [Help] [answered]
This is my configuration:
```js
// tailwind.config.js
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ...
        tahiti: {
          DEFAULT: '#06b6d4',
          dark: '#0e7490',
        },
        // ...
      },
    },
  },
}
```
Normally, if you want to adapt to dark mode, you need to write two class names
```html
<div class="bg-tahiti dark:bg-tahiti-dark" />
```
The following style will be generated
```css
.bg-tahiti {
  --tw-bg-opacity: 1;
  background-color: rgb(6 182 212 / var(--tw-bg-opacity));
}

:is(.dark .dark\:bg-tahiti-dark) {
  --tw-bg-opacity: 1;
  background-color: rgb(14 116 144 / var(--tw-bg-opacity));
}
```
**Now I want to implement the above two styles through one class name (such as `auto:dark:bg-tahiti`). How to do this?**

**Comment by wongjn** [comment, marked as answer]
Generally, the maintainers don't really recommend this approach and thus is probably why there is not a more "built-in" way of achieving this.

For example, from [Simon Vrachliotis](https://github.com/tailwindlabs/tailwindcss/discussions/3583#discussioncomment-368696):
> When implementing dark mode interfaces, you likely don't always want to just "swap" or invert colors, and often need much more "fine control", to make contextual decisions on a lot of parts of the UI.

And from [Adam Wathan](https://github.com/tailwindlabs/tailwindcss/discussions/10274#discussioncomment-4627634):
> Personally I think doing dark mode this way is seductive but not as practical as you expect. Tons of situations where you end up swapping the same color in light mode for two different colors in dark mode depending on how it’s used, and then you need to come up with different names for those two colors and it quickly becomes a very big project. 

---

However, if you still do want to do this, you could look at [using CSS variables](https://tailwindcss.com/docs/customizing-colors#using-css-variables):

```js
tahiti: {
  DEFAULT: 'rgb(var(--colors--tahiti) / <alpha-value>)',
```
```css
:root {
  --colors--tahiti: 6 182 212;
}

[class="dark"] {
  --colors--tahiti: 14 116 144;
}
```
