### DISCUSSION TITLE
Add text-shadow utility

### DISCUSSION THREAD

**Discussion by Kacktide** [tailwindlabs/tailwindcss#12780] [Ideas]
As we all know just like the shadow property for box-shadow, we need same for text-shadow

**Comment by SilasRodrigues19** [comment]
Hey @Kacktide 

This has been ignored by Tailwind for now because it is possible to customize and create a utility, as said by Adam Wathan, creator of Tailwind:

>  We're not opposed to adding this at some point, but going to skip it for now since it's so easy to add utilities yourself. We may revisit this sooner once we've made it easy to opt in/out of different modules.

_Originally posted by @adamwathan in https://github.com/tailwindlabs/tailwindcss/issues/162#issuecomment-343172613_

In your main CSS file, you can create a utility like this:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
    @variants responsive {
        .text-shadow {
          text-shadow: 0 2px 4px rgba(0,0,0,0.10);
        }

        .text-shadow-md {
          text-shadow: 0 4px 8px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.08);
        }

        .text-shadow-lg {
          text-shadow: 0 15px 30px rgba(0,0,0,0.11), 0 5px 15px rgba(0,0,0,0.08);
        }

        .text-shadow-none {
          text-shadow: none;
        }
    }
}
```
