### DISCUSSION TITLE
Missing variables during build (?!)

### DISCUSSION THREAD

**Discussion by dimitrisnl** [tailwindlabs/tailwindcss#12823] [Help] [answered]
Hello, I noticed an issue and it's 100% on my setup. I'm just not sure where to look.

Take for instance this element
```jsx
<div className='bg-gradient-to-b to-blue-100'>...</div>
```

I notice on my production build that the class is present

```css
.to-blue-100 {
    --tw-gradient-to: #eff3fa var(--tw-gradient-to-position)
}
```

but what's crazy is that I'm missing the `--tw-gradient-to-position` variable!
I don't see in under the `*, :;before, ::after` declaration. 

I inspect the generated CSS file and it's obviously missing many of these variables.

In dev mode I don't see anything wrong. But I struggle to understand how this happens.

- Version `3.4.1`
- Using Postcss

Any ideas how to debug this?
