### DISCUSSION TITLE
supports-[...] rule with background-image

### DISCUSSION THREAD

**Discussion by jb-alvarado** [tailwindlabs/tailwindcss#12849] [Help] [answered]
Hello,
I would like to use the supports rule with different background images, like:

```CSS
#sunrise {
    background-image: url('/img/earth-sunrise_1920.jpg');

    @supports (background-image: url('/img/earth-sunrise_1920.webp')) {
        background-image: url('/img/earth-sunrise_1920.webp');
    }

    @supports (background-image: url('/img/earth-sunrise_2560.avif')) {
        background-image: url('/img/earth-sunrise_2560.avif');
    }
}
```

But when I try:

```HTML
<div class=supports-[bg-[url(/img/earth-sunrise_1920.webp)]]:bg-[url(/img/earth-sunrise_1920.webp)]
```

its not working.

Can I not apply that rule to background images?
