### DISCUSSION TITLE
Time to change x and y padding and margin to logical equivalents?

### DISCUSSION THREAD

**Discussion by hfournier** [tailwindlabs/tailwindcss#12921] [Ideas]
There are obvious upsides to using logical properties, so are there any reasons not to change `px-`, `py-`, `mx-` and `my-` to output their logical equivalents?
For example, currently px-_value_ results in:
```css
{
    padding-left: value;
    padding-right: value;
}
```
Wouldn't it be preferable to have:
```css
{
    padding-inline: value;
}
```
instead? Seems logical 😉 
This was mentioned in #10166, but was not addressed.
