### DISCUSSION TITLE
Hover link effect in Tailwind

### DISCUSSION THREAD

**Discussion by albertcito** [tailwindlabs/tailwindcss#12965] [Help] [answered]
How can I do this effect in tailwind? [preview here](https://play.tailwindcss.com/AQl9PsuLFc)

```css
.link {
  font-weight: 700;
  text-shadow: 0.2px 0.2px 0px #af2466;
  color: #af2466;
  background: linear-gradient(to bottom, rgba(63, 74, 80, 0.1) 0%, rgba(63, 74, 80, 0.1) 100%);
  background-position: 5px 100%;
  background-repeat: repeat-x;
  background-size: 6px 6px;
  text-decoration: none;
  transition: all 0.8s cubic-bezier(0.195, 0.765, 0.42, 1);
}

.link:hover {
  background-size: 6px 55px;
}
```
