### DISCUSSION TITLE
[Feature Proposal]: Add "line-clamp" utility

### DISCUSSION THREAD

**Discussion by frontsideair** [tailwindlabs/tailwindcss#1303] [Ideas]
I think there should be a `line-clamp` utility, even though it's non-standard, it has [good support](https://caniuse.com/#feat=css-line-clamp) across the board. I'm interested in adding it myself if you think it's a good idea.

**Comment by benface** [comment]
FWIW, it is on the standards track: https://www.w3.org/TR/css-overflow-3/#line-clamp

**Comment by dwightwatson** [comment]
I implemented this as a component as it requires a few properties in order to work properly - including some `-webkit` hackery and `overflow: hidden`.

```js
const _ = require('lodash');
const plugin = require('tailwindcss/plugin');

module.exports = plugin.withOptions(function (lineCounts = []) {
  return function ({ addComponents, e }) {
    const components = _.map(lineCounts, lineCount => ({
      [`.${e(`clamp-${lineCount}`)}`]: {
        '-webkit-box-orient': 'vertical',
        '-webkit-line-clamp':`${lineCount}`,
        'display': '-webkit-box',
        'lineClamp': lineCount,
        'overflow': 'hidden',
      }
    }));

    addComponents(components);
  };
});
```

Had to use string interpolation on `-webkit-line-clamp` otherwise it had `px` appended to the line count for some odd reason.

Would be good to see this feature make it into the core.

**Comment by vricop** [comment]
This is what I do in the scss utility library I'm working on –you won't find in in github yet, as it is a private repository.

```css
/* _base.scss */

/* Required pre-setup declarations for `line-clamp-{size} */
[class*=line-clamp-] {
  overflow: hidden;
  display: -webkit-box;
  -webkit-box-orient: vertical;
}
```
```scss
/* _line-clamp.scss */

.line-clamp#{$modifier} {
  -webkit-line-clamp: $value;
}
```
**Note**: I omitted a lot of scss code for the shake of simplicity. Those variables came from an `@each` loop.

`_base.scss` would be what tailwind calls `preflight.css`. That's where I put my pre-setup declarations with the attribute selector `[class*=line-clamp-]` (specificity: 0,0,1,0). Now the `_line-clmap.scss`: this should be placed in your `lineClamp.js` plugin utility.

Then the config file will hold all values for the `-webkit-line-clamp`.

**Update**:  The attribute selector avoids repeating the _required_ properties for `line-clamp` utility. Then you can use `line-clamp-{count}` utility without redeclaring those properties.
