### DISCUSSION TITLE
generic input type selector

### DISCUSSION THREAD

**Discussion by taanning** [tailwindlabs/tailwindcss#13033] [Help]
So i worked with trying to apply some classes based on selectors across my solution. 

I found out that using the selctor input[type=text] does not work. 

"input" renders as "input[type=text]"
"input[type=text]" fails
"input[type=password]" renders as "input[type=password]"

Example : 

```
    plugins: [
        plugin(function ({ addBase,}) {
            addBase({
                'input': {
                    '@apply w-full p-4 bg-white rounded-md border-1 text-text-lighter border-borders-light': {}, // works on input[type=text] elements 
                },
                'input[type=text]': {
                    '@apply w-full p-4 bg-white rounded-md border-1 text-text-lighter border-borders-light': {}, // does not work
                },,
                'input[type=password]': {
                    '@apply w-full p-4 bg-white rounded-md border-1 text-text-lighter border-borders-light': {}, // works on input[type=password] elements 
                },
            })
        }),
    ]
```

**Comment by alex-krasikau** [comment]
Hey @Terningen!

I tried your configuration and it works as expected. Please check out the example - https://play.tailwindcss.com/1fYqPCAesb?file=config.

I slightly updated the configuration to work with the default configuration:
```js
export default {
  theme: {},
  plugins: [
    require('tailwindcss/plugin')(function ({ addBase }) {
      addBase({
        input: {
          '@apply bg-red-100': {},
        },
        'input[type=text]': {
          '@apply bg-blue-100': {},
        },
        'input[type=password]': {
          '@apply bg-green-100': {},
        },
      })
    }),
  ],
}
```

These leads to the following generated CSS:
```css
input{
  --tw-bg-opacity: 1;
  background-color: rgb(254 226 226 / var(--tw-bg-opacity))
}

input[type=text]{
  --tw-bg-opacity: 1;
  background-color: rgb(219 234 254 / var(--tw-bg-opacity))
}

input[type=password]{
  --tw-bg-opacity: 1;
  background-color: rgb(220 252 231 / var(--tw-bg-opacity))
}
```

If you still encounter the issue, try stopping your project, cleaning up the cache as recommended by the framework you use and starting the project again. If that doesn't help, can try replicating your issue in https://play.tailwindcss.com/.
