### DISCUSSION TITLE
how to combine arbitrary value with pointer events utility?

### DISCUSSION THREAD

**Discussion by codenoobforreal** [tailwindlabs/tailwindcss#13047] [Help] [answered]
I have a tailwind play example to demonstrate my question
https://play.tailwindcss.com/ffI67XebKk

```html
<div class="p-10">
  <div class="my-container_all">
    <button class="pointer-events-[var(--ui-pointerEvents)]">all</button>
  </div>
  <div class="my-container_none">
    <button class="pointer-events-[var(--ui-pointerEvents)]">none</button>
  </div>
</div>
```

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .pointer-events-all {
    pointer-events: all;
  }
}

.my-container_none {
  --ui-pointerEvents: none
}

.my-container_all {
  --ui-pointerEvents: all
}
```
What i expected is you will get a default cursor when you hover the none button.
any solutions?
After that i can change the `--ui-pointerEvents` value by javascript to do whatever i want.
