### DISCUSSION TITLE
Embedd markdown within a special div container

### DISCUSSION THREAD

**Discussion by dibog** [tailwindlabs/tailwindcss#13135] [Help]
I would like to render markdown code (which is transformed on the backend into html) on a page which is using Tailwindcss.
But the tags like h1, h2, ..., ul, li are changed by base TailWind (and for the rest of my app that is very fine so), but I would like
to emit that markdown into a special dev, so that it is rendered nicely. I can't get that working, e.g. here is some of my tries to enable this:

```css
@layer components {
  .markdown h1 {
    @apply text-2xl;
  }
  .markdown h2 {
    @apply text-xl;
  }
  .markdown ul {
    list-style: circle;
  }
  .markdown ul li {
    list-style-position: outside;
    list-style-type: circle;
  }
}
```

But this fragment renders only the changes to `h1` and `h2` but not to the `ul` or `li`.
Example:

```html
<div id="test" class="markdown">
  <h1>Header #1</h1>
  <h2>Header #2</h2>
  <ul>
    <li>one</li>
    <li>two</li>
    <li>three</li>
  </ul>
</div>
```

Which looks roughly like this:
![example](https://github.com/tailwindlabs/tailwindcss/assets/1060258/80fe1fb5-ef5e-4a2b-8180-16a1e8aeae4a)

Any ideas what I am doing wrong or missing?

Btw, here the things in the generated styles.css:

```css
.markdown h1 {
  font-size: 1.5rem;
  line-height: 2rem;
}

.markdown h2 {
  font-size: 1.25rem;
  line-height: 1.75rem;
}

.markdown ul {
  list-style: circle;
}

.markdown ul li {
  list-style-position: outside;
  list-style-type: circle;
}
````
