### DISCUSSION TITLE
[V4]: Only use my theme colors

### DISCUSSION THREAD

**Discussion by djmtype** [tailwindlabs/tailwindcss#13209] [Help]
Using V4, I just want to use my colors; all without having to import Tailwind utilities and preflight.

This doesn't seem to work: 

```css
@import "tailwindcss/theme" layer(theme);
/* Also, tried: @import "tailwindcss/theme"; */

@theme {
--color-mustard: #cc0;
}
```

Expected the output: 

```css
:root {
--color-mustard: #cc0;
}

.text-mustard {
  color: #cc0;
}
```

Instead, it was ignored, and returned as: 

```css
@theme {
--color-mustard: #cc0;
}
```

**Comment by wongjn** [comment]
Wouldn't `text-mustard` be a Tailwind utility from your `--color-mustard` configuration? If so, you'd need to import `@tailwind/utilities` and for it to be used in code found by Tailwind's template scanning heuristics for it to be generated. This would also transform `@theme` to `:root` properly. If you don't want the default colors, do `--color-*: initial` like:

```css
@layer theme, base, components, utilities;

@import "tailwindcss/theme" layer(theme);
@import "tailwindcss/utilities" layer(utilities);

@theme {
  --color-*: initial;
  --color-mustard: #cc0;
}
```

**Reply by djmtype** [reply]
The issue is, importing TW utilities adds in a bunch of unnecessary utility classes my project will never use.

Here is what happens when I include `@utilities`. My color isn't the only item returned.

```css
@layer utilities {
  .visible {
    visibility: visible;
  }
  .sr-only {
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    position: absolute;
    overflow: hidden;
  }
  .absolute {
    position: absolute;
  }
  .relative {
    position: relative;
  }
  .static {
    position: static;
  }
  .z-index {
    z-index: index;
  }
  .\!inline {
    display: inline !important;
  }
  .block {
    display: block;
  }
  .contents {
    display: contents;
  }
  .flex {
    display: flex;
  }
  .grid {
    display: grid;
  }
  .hidden {
    display: none;
  }
  .inline {
    display: inline;
  }
  .table {
    display: table;
  }
  .flex-direction {
    flex: direction;
  }
  .\!transform {
    transform: skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) !important;
  }
  .transform {
    transform: skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y));
  }
  .flex-wrap {
    flex-wrap: wrap;
  }
  .border {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }
  .lowercase {
    text-transform: lowercase;
  }
  .uppercase {
    text-transform: uppercase;
  }
  .italic {
    font-style: italic;
  }
  .text-mustard {
    color: #cc0;
  }
  .underline {
    text-decoration-line: underline;
  }
  .filter {
    filter: var(--tw-blur,) var(--tw-brightness,) var(--tw-contrast,)
      var(--tw-grayscale,) var(--tw-hue-rotate,) var(--tw-invert,)
      var(--tw-saturate,) var(--tw-sepia,) var(--tw-drop-shadow,);
  }
  .transition {
    transition-property:
      color,
      background-color,
      border-color,
      text-decoration-color,
      fill,
      stroke,
      opacity,
      box-shadow,
      transform,
      translate,
      scale,
      rotate,
      filter,
      -webkit-backdrop-filter,
      -webkit-backdrop-filter,
      backdrop-filter;
    transition-timing-function: var(--default-transition-timing-function);
    transition-duration: var(--default-transition-duration);
  }
  .focus\:not-sr-only:focus {
    clip: auto;
    white-space: normal;
    width: auto;
    height: auto;
    margin: 0;
    padding: 0;
    position: static;
    overflow: visible;
  }
}
```
