### DISCUSSION TITLE
Add example for shadcn-ui

### DISCUSSION THREAD

**Discussion by fernandortec** [tailwindlabs/tailwindcss#13211] [Ideas]
If you wish to migrate to the newest version of Tailwind v4.0.0-alpha, for most people it will be a bit harsh to do so if they're using shadcn-ui.

Adding tailwind v4 and Postcss is fine, but the layout won't look like it was on the previous version, because all of the variables that shadcn set automatically on tailwind.config.ts, will need to be rewritten using a regular CSS file.
I've just migrated a project from tailwind v3.4.1 to v4.0.0-alpha successfully, and I'd like to share my .css file with the theme already configurated for shadcn-ui, so other people that are also migrating can get their variables re-defined in a simple copy and paste.

It would be great if that could be available in [this](https://tailwindcss.com/blog/tailwindcss-v4-alpha) post you guys did. 

```
@import "tailwindcss";

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;

    --card: 0 0% 100%;
    --card-foreground: 240 10% 3.9%;

    --popover: 0 0% 100%;
    --popover-foreground: 240 10% 3.9%;

    --primary: 240 5.9% 10%;
    --primary-foreground: 0 0% 98%;

    --secondary: 240 4.8% 95.9%;
    --secondary-foreground: 240 5.9% 10%;

    --muted: 240 4.8% 95.9%;
    --muted-foreground: 240 3.8% 46.1%;

    --accent: 240 4.8% 95.9%;
    --accent-foreground: 240 5.9% 10%;

    --destructive: 0 72.22% 50.59%;
    --destructive-foreground: 0 0% 98%;

    --border: 240 5.9% 90%;
    --input: 240 5.9% 90%;

    --ring: 240 5% 64.9%;

    --radius: 0.5rem;
  }

  .dark {
    --background: 224 71% 4%;
    --foreground: 213 31% 91%;

    --muted: 223 47% 11%;
    --muted-foreground: 215.4 16.3% 56.9%;

    --accent: 216 34% 17%;
    --accent-foreground: 210 40% 98%;

    --popover: 224 71% 4%;
    --popover-foreground: 215 20.2% 65.1%;

    --border: 216 34% 17%;
    --input: 216 34% 17%;

    --card: 224 71% 4%;
    --card-foreground: 213 31% 91%;

    --primary: 210 40% 98%;
    --primary-foreground: 222.2 47.4% 1.2%;

    --secondary: 222.2 47.4% 11.2%;
    --secondary-foreground: 210 40% 98%;

    --destructive: 0 63% 31%;
    --destructive-foreground: 210 40% 98%;

    --ring: 216 34% 17%;

    --radius: 0.5rem;
  }
}

@theme {
  --color-border: hsl(var(--border));
  --color-input: hsl(var(--input));
  --color-ring: hsl(var(--ring));
  --color-background: hsl(var(--background));
  --color-foreground: hsl(var(--foreground));

  --color-primary: hsl(var(--primary));
  --color-primary-foreground: hsl(var(--primary-foreground));

  --color-secondary: hsl(var(--secondary));
  --color-secondary-foreground: hsl(var(--secondary-foreground));

  --color-destructive: hsl(var(--destructive));
  --color-destructive-foreground: hsl(var(--destructive-foreground));

  --color-muted: hsl(var(--muted));
  --color-muted-foreground: hsl(var(--muted-foreground));

  --color-accent: hsl(var(--accent));
  --color-accent-foreground: hsl(var(--accent-foreground));

  --color-popover: hsl(var(--popover));
  --color-popover-foreground: hsl(var(--popover-foreground));

  --color-card: hsl(var(--card));
  --color-card-foreground: hsl(var(--card-foreground));

  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);

  --font-family-poppins: var(--font-poppins);
  --font-family-inter: var(--font-inter);

  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;

  @keyframes accordion-down {
    from {
      height: 0;
    }

    to {
      height: var(--radix-accordion-content-height);
    }
  }

  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height);
    }

    to {
      height: "0";
    }
  }
}


.border {
  border-color: #e4e5e9;
}

button {
  cursor: pointer;
}
```

**Comment by ajayvignesh01** [comment]
As of a few weeks ago, plugins became supported in tailwind v4 alpha. And recently, [p3 colors](https://github.com/tailwindlabs/tailwindcss/pull/14693) were added to the tailwind color palette. If you're using zinc theme (default), you can use the following config to get the tailwindcss-animate plugin and p3 colors working:

tailwind.css
```css
@import 'tailwindcss';
@import './shadcn.css';
@plugin 'tailwindcss-animate';

@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);

  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);

  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);

  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);

  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);

  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);

  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);

  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);

  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);

  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);

  --radius-radius: var(--radius);

  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);

  --font-family-sans: var(--font-geist-sans);
  --font-family-mono: var(--font-geist-mono);

  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;

  @keyframes accordion-down {
    from {
      height: 0;
    }

    to {
      height: var(--radix-accordion-content-height);
    }
  }

  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height);
    }

    to {
      height: 0;
    }
  }
}

* {
  @apply border-border;
}
body {
  @apply bg-background text-foreground;
}

```

shadcn.css
```css
:root {
  --background: 0 0% 100%;
  --foreground: var(--color-zinc-950); /* 240 10% 3.9% */

  --card: 0 0% 100%;
  --card-foreground: var(--color-zinc-950); /* 240 10% 3.9% */

  --popover: 0 0% 100%;
  --popover-foreground: var(--color-zinc-950); /* 240 10% 3.9% */

  --primary: var(--color-zinc-900); /* 240 5.9% 10% */
  --primary-foreground: var(--color-zinc-50); /* 0 0% 98% */

  --secondary: var(--color-zinc-100); /* 240 4.8% 95.9% */
  --secondary-foreground: var(--color-zinc-900); /* 240 5.9% 10% */

  --muted: var(--color-zinc-100); /* 240 4.8% 95.9% */
  --muted-foreground: var(--color-zinc-500); /* 240 3.8% 46.1% */

  --accent: var(--color-zinc-100); /* 240 4.8% 95.9% */
  --accent-foreground: var(--color-zinc-900); /* 240 5.9% 10% */

  --destructive: var(--color-red-500); /* 0 84.2% 60.2% */
  --destructive-foreground: var(--color-zinc-50); /* 0 0% 98% */

  --border: var(--color-zinc-200); /* 240 5.9% 90% */
  --input: var(--color-zinc-200); /* 240 5.9% 90% */
  --ring: var(--color-zinc-900); /* 240 5.9% 10% */

  --radius: 0.5rem;

  --chart-1: 12 76% 61%;
  --chart-2: 173 58% 39%;
  --chart-3: 197 37% 24%;
  --chart-4: 43 74% 66%;
  --chart-5: 27 87% 67%;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: var(--color-zinc-950); /* 240 10% 3.9% */
    --foreground: var(--color-zinc-50); /* 0 0% 98% */

    --card: var(--color-zinc-950); /* 240 10% 3.9% */
    --card-foreground: var(--color-zinc-50); /* 0 0% 98% */

    --popover: var(--color-zinc-950); /* 240 10% 3.9% */
    --popover-foreground: var(--color-zinc-50); /* 0 0% 98% */

    --primary: var(--color-zinc-50); /* 0 0% 98% */
    --primary-foreground: var(--color-zinc-900); /* 240 5.9% 10% */

    --secondary: var(--color-zinc-800); /* 240 3.7% 15.9% */
    --secondary-foreground: var(--color-zinc-50); /* 0 0% 98% */

    --muted: var(--color-zinc-800); /* 240 3.7% 15.9% */
    --muted-foreground: var(--color-zinc-400); /* 240 5% 64.9% */

    --accent: var(--color-zinc-800); /* 240 3.7% 15.9% */
    --accent-foreground: var(--color-zinc-50); /* 0 0% 98% */

    --destructive: var(--color-red-900); /* 0 62.8% 30.6% */
    --destructive-foreground: var(--color-zinc-50); /* 0 0% 98% */

    --border: var(--color-zinc-800); /* 240 3.7% 15.9% */
    --input: var(--color-zinc-800); /* 240 3.7% 15.9% */
    --ring: var(--color-zinc-300); /* 240 4.9% 83.9% */

    --chart-1: 220 70% 50%;
    --chart-2: 160 60% 45%;
    --chart-3: 30 80% 55%;
    --chart-4: 280 65% 60%;
    --chart-5: 340 75% 55%;
  }
}
```

**Reply by guugg** [reply]
Wrong example

**Comment by damien-schneider** [comment]
For people who are still looking for a solution, here's one that works well for me.
> Note that I haven't managed to make it work with `:root` and `@media (prefers-color-scheme: dark){...}`
> I am temporarily using `.dark` and `.light` which are applied on `<html>` for now.

```css
/* ./index.css */
@import "tailwindcss";
@import "./style/shadcn.css" layer(base);

@variant dark (&:where(.dark, .dark *));

@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);

  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);

  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);

  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);

  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);

  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);

  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);

  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);

  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);

  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);

  --radius-radius: var(--radius);

  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);

  --font-family-sans: var(--font-geist-sans);
  --font-family-mono: var(--font-geist-mono);

  --chart-1: var(--chart-1);
  --chart-2: var(--chart-2);
  --chart-3: var(--chart-3);
  --chart-4: var(--chart-4);
  --chart-5: var(--chart-5);

  --sidebar-background: var(--sidebar-background);
  --sidebar-foreground: var(--sidebar-foreground);
  --sidebar-primary: var(--sidebar-primary);
  --sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --sidebar-accent: var(--sidebar-accent);
  --sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --sidebar-border: var(--sidebar-border);
  --sidebar-ring: var(--sidebar-ring);
}

```

```css
/* ./style/shadcn.css */

.dark {
  --radius: 0.5rem;

  --background: var(--color-neutral-900);
  --foreground: var(--color-neutral-50);

  --card: var(--color-neutral-950);
  --card-foreground: var(--color-neutral-50);

  --popover: var(--color-neutral-900);
  --popover-foreground: var(--color-neutral-50);

  --primary: var(--color-neutral-50);
  --primary-foreground: var(--color-neutral-900);

  --secondary: var(--color-neutral-800);
  --secondary-foreground: var(--color-neutral-50);

  --muted: var(--color-neutral-800);
  --muted-foreground: var(--color-neutral-400);

  --accent: var(--color-neutral-800);
  --accent-foreground: var(--color-neutral-50);

  --destructive: var(--color-red-900);
  --destructive-foreground: var(--color-neutral-50);

  --border: var(--color-neutral-800);
  --input: var(--color-neutral-800);
  --ring: var(--color-neutral-300);

  --chart-1: var(--color-neutral-600);
  --chart-2: var(--color-neutral-700);
  --chart-3: var(--color-neutral-800);
  --chart-4: var(--color-neutral-900);
  --chart-5: var(--color-neutral-950);

  --sidebar-background: var(--color-neutral-900);
  --sidebar-foreground: var(--color-neutral-100);
  --sidebar-primary: var(--color-neutral-800);
  --sidebar-primary-foreground: var(--color-neutral-50);
  --sidebar-accent: var(--color-neutral-700);
  --sidebar-accent-foreground: var(--color-neutral-100);
  --sidebar-border: var(--color-neutral-800);
  --sidebar-ring: var(--color-neutral-600);
}

.light {
  --radius: 0.5rem;

  --background: var(--color-white);
  --foreground: var(--color-neutral-950);

  --card: var(--color-white);
  --card-foreground: var(--color-neutral-950);

  --popover: var(--color-white);
  --popover-foreground: var(--color-neutral-950);

  --primary: var(--color-neutral-900);
  --primary-foreground: var(--color-neutral-50);

  --secondary: var(--color-neutral-100);
  --secondary-foreground: var(--color-neutral-900);

  --muted: var(--color-neutral-100);
  --muted-foreground: var(--color-neutral-500);

  --accent: var(--color-neutral-100);
  --accent-foreground: var(--color-neutral-900);

  --destructive: var(--color-red-500);
  --destructive-foreground: var(--color-neutral-50);

  --border: var(--color-neutral-200);
  --input: var(--color-neutral-200);
  --ring: var(--color-neutral-900);

  --chart-1: var(--color-neutral-500);
  --chart-2: var(--color-neutral-600);
  --chart-3: var(--color-neutral-700);
  --chart-4: var(--color-neutral-800);
  --chart-5: var(--color-neutral-900);

  --sidebar-background: var(--color-neutral-100);
  --sidebar-foreground: var(--color-neutral-800);
  --sidebar-primary: var(--color-neutral-700);
  --sidebar-primary-foreground: var(--color-neutral-50);
  --sidebar-accent: var(--color-neutral-300);
  --sidebar-accent-foreground: var(--color-neutral-900);
  --sidebar-border: var(--color-neutral-200);
  --sidebar-ring: var(--color-neutral-600);
}
```

**Reply by chunlea** [reply]
`@media (prefers-color-scheme: dark)` works for me like this, but I didn't manage to make it work for both the media query and the `.dark` class.

```css
@import "tailwindcss";

:root {
  --background: hsl(0, 0%, 100%);
  --foreground: hsl(0, 0%, 3.9%);
  --card: hsl(0, 0%, 100%);
  --card-foreground: hsl(0, 0%, 3.9%);
  --popover: hsl(0, 0%, 100%);
  --popover-foreground: hsl(0, 0%, 3.9%);
  --primary: hsl(0, 0%, 9%);
  --primary-foreground: hsl(0, 0%, 98%);
  --secondary: hsl(0, 0%, 96.1%);
  --secondary-foreground: hsl(0, 0%, 9%);
  --muted: hsl(0, 0%, 96.1%);
  --muted-foreground: hsl(0, 0%, 45.1%);
  --accent: hsl(0, 0%, 96.1%);
  --accent-foreground: hsl(0, 0%, 9%);
  --destructive: hsl(0, 84.2%, 60.2%);
  --destructive-foreground: hsl(0, 0%, 98%);
  --border: hsl(0, 0%, 89.8%);
  --input: hsl(0, 0%, 89.8%);
  --ring: hsl(0, 0%, 3.9%);
  --chart-1: hsl(12, 76%, 61%);
  --chart-2: hsl(173, 58%, 39%);
  --chart-3: hsl(197, 37%, 24%);
  --chart-4: hsl(43, 74%, 66%);
  --chart-5: hsl(27, 87%, 67%);
  --radius: 0.5rem;
  --sidebar-background: hsl(0, 0%, 98%);
  --sidebar-foreground: hsl(240, 5.3%, 26.1%);
  --sidebar-primary: hsl(240, 5.9%, 10%);
  --sidebar-primary-foreground: hsl(0, 0%, 98%);
  --sidebar-accent: hsl(240, 4.8%, 95.9%);
  --sidebar-accent-foreground: hsl(240, 5.9%, 10%);
  --sidebar-border: hsl(220, 13%, 91%);
  --sidebar-ring: hsl(217.2, 91.2%, 59.8%);
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: hsl(0, 0%, 3.9%);
    --foreground: hsl(0, 0%, 98%);
    --card: hsl(0, 0%, 3.9%);
    --card-foreground: hsl(0, 0%, 98%);
    --popover: hsl(0, 0%, 3.9%);
    --popover-foreground: hsl(0, 0%, 98%);
    --primary: hsl(0, 0%, 98%);
    --primary-foreground: hsl(0, 0%, 9%);
    --secondary: hsl(0, 0%, 14.9%);
    --secondary-foreground: hsl(0, 0%, 98%);
    --muted: hsl(0, 0%, 14.9%);
    --muted-foreground: hsl(0, 0%, 63.9%);
    --accent: hsl(0, 0%, 14.9%);
    --accent-foreground: hsl(0, 0%, 98%);
    --destructive: hsl(0, 62.8%, 30.6%);
    --destructive-foreground: hsl(0, 0%, 98%);
    --border: hsl(0, 0%, 14.9%);
    --input: hsl(0, 0%, 14.9%);
    --ring: hsl(0, 0%, 83.1%);
    --chart-1: hsl(220, 70%, 50%);
    --chart-2: hsl(160, 60%, 45%);
    --chart-3: hsl(30, 80%, 55%);
    --chart-4: hsl(280, 65%, 60%);
    --chart-5: hsl(340, 75%, 55%);
    --sidebar-background: hsl(240, 5.9%, 10%);
    --sidebar-foreground: hsl(240, 4.8%, 95.9%);
    --sidebar-primary: hsl(224.3, 76.3%, 48%);
    --sidebar-primary-foreground: hsl(0, 0%, 100%);
    --sidebar-accent: hsl(240, 3.7%, 15.9%);
    --sidebar-accent-foreground: hsl(240, 4.8%, 95.9%);
    --sidebar-border: hsl(240, 3.7%, 15.9%);
    --sidebar-ring: hsl(217.2, 91.2%, 59.8%);
  }
}

@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);

  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);

  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);

  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);

  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);

  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);

  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);

  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);

  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);

  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);

  --radius-radius: var(--radius);

  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);

  --font-family-sans: var(--font-geist-sans);
  --font-family-mono: var(--font-geist-mono);

  --chart-1: var(--chart-1);
  --chart-2: var(--chart-2);
  --chart-3: var(--chart-3);
  --chart-4: var(--chart-4);
  --chart-5: var(--chart-5);

  --color-sidebar-background: var(--sidebar-background);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
}
```

**Comment by XavierGeerinck** [comment]
Adding the full solution here as nothing above worked for me, also separated colors a bit for maintainability

> Note: I would maybe rename this discussion to "Add Dark and Light mode support to ShadCN" or create a dedicated section in the dark mode. I'll see if I can make a PR for this

**tailwind.css**

```css
@import 'tailwindcss';
@import "./colors.css" layer(base);

@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *, .dark, .dark *));

@theme {
  --color-background: var(--color-background);
  --color-background-foreground: var(--color-foreground);
  --color-foreground: var(--color-foreground);
  --color-foreground-primary: var(--color-primary-foreground);
  --color-primary: var(--color-primary);
  --color-primary-foreground: var(--color-primary-foreground);
  --color-secondary: var(--color-secondary);
  --color-secondary-foreground: var(--color-secondary-foreground);
  --color-destructive: var(--color-destructive);
  --color-destructive-foreground: var(--color-destructive-foreground);
  --color-muted: var(--color-muted);
  --color-muted-foreground: var(--color-muted-foreground);
  --color-accent: var(--color-accent);
  --color-accent-foreground: var(--color-accent-foreground);
  --color-popover: var(--color-popover);
  --color-popover-foreground: var(--color-popover-foreground);
  --color-card: var(--color-card);
  --color-card-foreground: var(--color-card-foreground);
  --color-border: var(--color-border);
  --color-input: var(--color-input);
  --color-ring: var(--color-ring);
  --color-chart-1: var(--color-chart-1);
  --color-chart-2: var(--color-chart-2);
  --color-chart-3: var(--color-chart-3);
  --color-chart-4: var(--color-chart-4);
  --color-chart-5: var(--color-chart-5);
  --color-sidebar: var(--color-sidebar-background);
  --color-sidebar-foreground: var(--color-sidebar-foreground);
  --color-sidebar-primary: var(--color-sidebar-primary);
  --color-sidebar-primary-foreground: var(--color-sidebar-primary-foreground);
  --color-sidebar-accent: var(--color-sidebar-accent);
  --color-sidebar-accent-foreground: var(--color-sidebar-accent-foreground);
  --color-sidebar-border: var(--color-sidebar-border);
  --color-sidebar-ring: var(--color-sidebar-ring);
}
```

**colors.css**

```css
html {
  color-scheme: light dark;

  &[data-theme="light"] {
    --color-background: var(--color-white);
    --color-foreground: var(--color-neutral-950);

    --color-card: var(--color-white);
    --color-card-foreground: var(--color-neutral-950);
  
    --color-popover: var(--color-white);
    --color-popover-foreground: var(--color-neutral-950);
  
    --color-primary: var(--color-neutral-900);
    --color-primary-foreground: var(--color-neutral-50);
  
    --color-secondary: var(--color-neutral-100);
    --color-secondary-foreground: var(--color-neutral-900);
  
    --color-muted: var(--color-neutral-100);
    --color-muted-foreground: var(--color-neutral-500);
  
    --color-accent: var(--color-neutral-100);
    --color-accent-foreground: var(--color-neutral-900);
  
    --color-destructive: var(--color-red-500);
    --color-destructive-foreground: var(--color-neutral-50);
  
    --color-border: var(--color-neutral-200);
    --color-input: var(--color-neutral-200);
    --color-ring: var(--color-neutral-900);
  
    --color-chart-1: var(--color-neutral-500);
    --color-chart-2: var(--color-neutral-600);
    --color-chart-3: var(--color-neutral-700);
    --color-chart-4: var(--color-neutral-800);
    --color-chart-5: var(--color-neutral-900);
  
    --color-sidebar-background: var(--color-neutral-100);
    --color-sidebar-foreground: var(--color-neutral-800);
    --color-sidebar-primary: var(--color-neutral-700);
    --color-sidebar-primary-foreground: var(--color-neutral-50);
    --color-sidebar-accent: var(--color-neutral-300);
    --color-sidebar-accent-foreground: var(--color-neutral-900);
    --color-sidebar-border: var(--color-neutral-200);
    --color-sidebar-ring: var(--color-neutral-600);
  }


  &[data-theme="dark"] {
    --color-background: var(--color-neutral-900);
    --color-foreground: var(--color-neutral-50);
  
    --color-card: var(--color-neutral-950);
    --color-card-foreground: var(--color-neutral-50);
  
    --color-popover: var(--color-neutral-900);
    --color-popover-foreground: var(--color-neutral-50);
  
    --color-primary: var(--color-neutral-50);
    --color-primary-foreground: var(--color-neutral-900);
  
    --color-secondary: var(--color-neutral-800);
    --color-secondary-foreground: var(--color-neutral-50);
  
    --color-muted: var(--color-neutral-800);
    --color-muted-foreground: var(--color-neutral-400);
  
    --color-accent: var(--color-neutral-800);
    --color-accent-foreground: var(--color-neutral-50);
  
    --color-destructive: var(--color-red-900);
    --color-destructive-foreground: var(--color-neutral-50);
  
    --color-border: var(--color-neutral-800);
    --color-input: var(--color-neutral-800);
    --color-ring: var(--color-neutral-300);
  
    --color-chart-1: var(--color-neutral-600);
    --color-chart-2: var(--color-neutral-700);
    --color-chart-3: var(--color-neutral-800);
    --color-chart-4: var(--color-neutral-900);
    --color-chart-5: var(--color-neutral-950);
  
    --color-sidebar-background: var(--color-neutral-900);
    --color-sidebar-foreground: var(--color-neutral-100);
    --color-sidebar-primary: var(--color-neutral-800);
    --color-sidebar-primary-foreground: var(--color-neutral-50);
    --color-sidebar-accent: var(--color-neutral-700);
    --color-sidebar-accent-foreground: var(--color-neutral-100);
    --color-sidebar-border: var(--color-neutral-800);
    --color-sidebar-ring: var(--color-neutral-600);
  }
}
```

et voila

![image](https://github.com/user-attachments/assets/fe4fc295-7ea4-4045-84b6-fee4bdc28f04)

![image](https://github.com/user-attachments/assets/56ddb2df-8466-4291-bcc4-09b1f07d8ba8)
