### DISCUSSION TITLE
[v4] Is there a way to keep underscores in theme variables?

### DISCUSSION THREAD

**Discussion by Gomah** [tailwindlabs/tailwindcss#13238] [Help] [answered]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.9

**What build tool (or framework if it abstracts the build tool) are you using?**

React 18.2.0, Vite 5.1.6

**What version of Node.js are you using?**

Bun 1.0.30

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

Tailwind play: https://play.tailwindcss.com/iSxc1ooIhz – But it doesn't support v4 yet,

```css
@tailwind base;

@theme {
  --text-color-primary: var(--text-primary);
  --text-primary_on-brand: var(--text-primary_on-brand);
}

:root {
  --text-primary: var(--color-gray-900);
  --text-primary_on-brand: var(--color-base-white);
}

.dark {
  --text-primary: var(--color-gray-50);
  --text-primary_on-brand: var(--color-gray-50);
}
```

**Describe your issue**

Theme variables containing underscores are translated to dots, e.g:
<img width="652" alt="Screenshot 2024-03-14 at 10 29 05 AM" src="https://github.com/tailwindlabs/tailwindcss/assets/2362138/88b618dc-9ff4-4bc6-823b-0e04c19a301c">

It makes sense though as I use underscore to translate into dots, e.g : `ring-width-1_5`, but is there a way to keep the underscore intact somehow? I tried with `\_` but no luck.
