### DISCUSSION TITLE
Multiple Tailwind Directives Usage Duplicate CSS Content

### DISCUSSION THREAD

**Discussion by yordis** [tailwindlabs/tailwindcss#13343] [Help]
Working on fixing the Tailwind setup in the scaffold repo (https://github.com/straw-hat-team/nextjs-starter-kit/pull/178), I came across the following situation,

I have a reusable design component package, `@monoturborepo/ui,` `@monoturborepo/ui,` with a CSS file with some basic styles.

```css
/* File: packages/@monoturborepo/ui/src/styles/index.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
/* other stuff */
```

Under my application, I have the following code:
```css
/* File: webapps/web1/src/styles/index.css */
@import '@monoturborepo/ui/src/styles/index.css';

/*
TODO: this is not work unless we add `@tailwind base;` but if we add `@tailwind base;` the bundle
  size becomes bigger.

We need to investigate how we are supposed to have shared styles between apps using tailwinds.

@layer base {
  html {
    background: red !important;
  }
}
*/
```

The problem is that if I want to call `@layer` I must add the `@tailwind base;` otherwise, it wouldn't work:

```
 `@layer base` is used but no matching `@tailwind base` directive is present.
```

If I add the `@tailwnd base;` directory, it will duplicate the directory's content again.

I am not sure what the right resolution would be to share Tailwind styles from packages with my applications.
