### DISCUSSION TITLE
[v4] How to utilize `--breakpoint-*` variables in CSS

### DISCUSSION THREAD

**Discussion by corneliusio** [tailwindlabs/tailwindcss#13371] [Help]
I'm not sure if I'm missing something here, but I haven't quite figured out how the `--breakpoint-*` variables are intended to be used in v4 when writing media queries in your CSS files.

The fundamental issue is that CSS variables can't be used in `@media` queries as conditions. I know we can still `@apply` media query variants and that's fine, but it's pretty official at this point that `@apply` is not recommended.

And to the team, loving v4 so far. Thanks for all the incredible work!

**Comment by corneliusio** [comment]
Still curious about this if anyone has an answer.

**Reply by corneliusio** [reply]
So far I've opted into using `postcss-custom-media` like so:

```css
@custom-media --screen-sm (width >= 640px);
@custom-media --screen-md (width >= 768px);
@custom-media --screen-lg (width >= 1024px);
@custom-media --screen-xl (width >= 1280px);
@custom-media --screen-2xl (width >= 1536px);
```

But this is just a workaround as it really has nothing to do with what TailwindCSS is doing.

**Reply by adamwathan** [reply]
Hey! Started quickly hacking on support for this in v4 — one thing I'm wondering is would you expect to have any way to produce the max-width version of a breakpoint?

```css
@media (--breakpoint-sm but somehow a max-width) {
  ...
}
```

...similar to how you can with utilities?

```html
<div class="max-sm:flex">
```

**Reply by corneliusio** [reply]
Hmm… that's a great question. Maybe a product of the era of webdev I came up in but I rarely reach for max-width media queries. That said, it's not never. Could there be a path here simply utilizing the `not` keyword?
```css
@media not (--breakpoint-sm) {
  ...
}
```
Intuitive to understand at first glance, clean, follows existing CSS patterns. This may be one of those "way easier said than done" approaches, but I do see the feature itself being useful for a lot of people.

**Comment by corneliusio** [comment]
On a related note, the ability to resolve theme values at build time vs run time more generally would also be incredibly helpful. Take this pseudo-code for example:
```css
&::before {
    content: url('data:image/svg+xml;utf8,<svg><path fill="var(--color-red-500)"></svg>');
}
/* or */
&::before {
    content: url('data:image/svg+xml;utf8,<svg><path class="fill-red-500"></svg>');
}

```
This obviously wouldn't work. The svg simply does not have access to the stylesheets scope. But, if we had a method to resolve these values:
```css
&::before {
    content: url('data:image/svg+xml;utf8,<svg><path fill="some-tailwind-function(--color-red-500)"></svg>');
}
```
We could also use this same approach for media queries:
```css
@media (some-tailwind-function(--breakpoint-sm)) {
  ...
}
```
