### DISCUSSION TITLE
Feature request: `tab-size` classes

### DISCUSSION THREAD

**Discussion by silverwind** [tailwindlabs/tailwindcss#13414] [Ideas]
It would be useful if tailwind had classes to set integer [`tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size). For example:

- `tab-size-2` -> `tab-size: 2;`
- `tab-size-4` -> `tab-size: 4;`
- `tab-size-8` -> `tab-size: 8;`

Units like `tab-size-[1em]` could be supported as well. Classes like `tab-4` are already [supported in unocss](https://unocss.dev/interactive/?s=tab-4), albeit with unnecessary vendor-prefixes.

**Comment by mathieucaroff** [comment]
In the meanwhile, use `[tab-size:X]` e.g.:

```html
<pre className="[tab-size:8]"></pre>
```

**Comment by rozsazoltan** [comment]
Can create new utility for yourself:
```css
@utility tab-size-* {
  tab-size: --value(integer, [integer], [length]);
}
```
```html
<pre class="tab-size-8"></pre>
```

Or just:
```css
@utility tab-* {
  tab-size: --value(integer, [integer], [length]);
}
```
```html
<pre class="tab-8"></pre>
```
