### DISCUSSION TITLE
Support @media (prefers-color-scheme: dark) within @theme

### DISCUSSION THREAD

**Discussion by The-Code-Monkey** [tailwindlabs/tailwindcss#13436] [Ideas]
I had an idea to support color differences using inbuilt css rather than prefixing and writing this media query everywhere.

I have tested this out and in chrome adding this to the theme directive seems to work

```
@theme {
  --color-text: #000;
  --color-text-inverse: #fff;
  @media (prefers-color-scheme: dark) {
    --color-text: #fff;
    --color-text-inverse: #000;
  }
}
```

I think logic like this should be allowed and would allow for a lot more flexibility especially in component libraries made using tailwind v4

**Comment by The-Code-Monkey** [comment]
Bump

**Comment by The-Code-Monkey** [comment]
Bump

**Comment by The-Code-Monkey** [comment]
Any update on this

**Comment by The-Code-Monkey** [comment]
Bump

**Comment by adamwathan** [comment]
You can do this without `@theme`:

```css
@theme {
  --color-text: #000;
  --color-text-inverse: #fff;
}

@media (prefers-color-scheme: dark) {
  :root {
    --color-text: #fff;
    --color-text-inverse: #000;
  }
}
```
