### DISCUSSION TITLE
Significant performance penalty when using "space-" space between class

### DISCUSSION THREAD

**Discussion by longzheng** [tailwindlabs/tailwindcss#13445] [Help] [answered]
We noticed in a React app that using the ["space between" utility classes](https://tailwindcss.com/docs/space) (e.g. `space-y-2`) in a layout that has a lot of child nodes introduces a significant performance penalty that makes it almost unusable.

For example

```html
<div class="space-x-1">
    <div>
        <div>test 0</div>
        ...
        <div>test 9999</div>
    </div>
</div>
```

The bizarre thing about this is that the child nodes are **not** direct descendants of the container that has the `space-` class.

I created a repro test case that illustrates this issue https://codesandbox.io/p/sandbox/sharp-faraday-hw99dy?file=%2Fsrc%2FApp.tsx%3A35%2C13 with 10,000 child nodes (two levels inside the container with the `space-x-1` classname)

To repro
- click "hide content" and "show content"
- rendering of the 10,000 nodes should be almost instant
- check the "apply space-x-1 class" checkbox
- click "hide content" and "show content"
- when showing content, the rendering will be noticeably slower

The generated CSS output of the `space-x-1` utility is as follows

```css
.space-x-1 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-x-reverse: 0;
  margin-right: calc(0.25rem * var(--tw-space-x-reverse));
  margin-left: calc(0.25rem * calc(1 - var(--tw-space-x-reverse)));
}
```

I'm assuming the ` > :not([hidden]) ~ :not([hidden])` part of the selector is complex and causes the rendering delays.

I'm not sure if there's any reasonable workarounds except to not use space between and switch to [gap](https://tailwindcss.com/docs/gap) instead, but I'm keen to hear if anyone else has run into this problem.
