### DISCUSSION TITLE
Reset user-select value for buttons

### DISCUSSION THREAD

**Discussion by lukewarlow** [tailwindlabs/tailwindcss#13461] [Ideas]
If you load https://play.tailwindcss.com/tBNhFrg3X7 in Chromium, or Safari you'll be able to select the text content of the button. However, in Firefox you won't be able to. This is because Firefox has a UA stylesheet rule like below.

```css
button,
::file-selector-button,
input:is([type=color], [type=reset], [type=button], [type=submit]) {
  user-select: none;
}
```

Tailwind should maybe consider normalising as part of the reset included in the framework?

I'm not sure if Firefox's behaviour is considered good or not so that would need checking with the community (especially a11y?).
