### DISCUSSION TITLE
How to define custom color names with alpha/opacity support using default colors & having the same name in dark & light mode

### DISCUSSION THREAD

**Discussion by kpvhn** [tailwindlabs/tailwindcss#13483] [Help] [answered]
I'd like to use something like `bg-primary` to apply a primary color to the background.

The color can be different in light and dark mode, e.g. resolve to Red 300 in light mode and to Red 800 in dark mode.

While I know of the possibility to define color variants as shown below and use them as `bg-primary-light/80 dark:bg-primary-dark/80`, I'd rather like to just use `bg-primary/80` for brevity.

```ts
  theme: {
    extend: {
      colors: {
        primary: {
          light: colors.red["300"],
          dark: colors.red["800"],
        },
    },
  },
```

With CSS variables, I can define different values and refer to them in `tailwind.config.ts` like this:

```ts
colors: {
    primary: "var(--color-primary)",
}
```

To support alpha/opacity modifiers like `bg-primary/80`, I think I'd need this:

```ts
colors: {
    primary: "rgb(var(--color-focus-contrast) / <alpha-value>)",
}
```

To refer to tailwindcss colors, I'd use something like this:

```scss
@layer base {
    :root {
        --color-primary: theme(colors.red.300);
    }

    // alternatively, use some document-level CSS class / selectors etc.
    @media (prefers-color-scheme: dark) {
        :root {
            --color-primary: theme(colors.red.800);
        }
    }
}
```

However, `theme(colors.red.300)` apparently resolves to something like `#rrggbb`, rather than the color channels `rrr ggg bbb`, as required and documented by tailwindcss to support opacity modifiers as shown above.

So, what's the suggested approach here?
Is there anything effectively similar or equal to `bg-primary/80`, or do I have to use `bg-primary-light/80 dark:bg-primary-dark/80`?
