### DISCUSSION TITLE
Spacing vs Sizing

### DISCUSSION THREAD

**Discussion by ng-hai** [tailwindlabs/tailwindcss#13504] [Help]
I'm working on an internal Design Language System, the designers organize their tokens in a different way with us developers. For example, from a Scaling unit set, they use it to calculate `margin|padding` and `width|height`:

```css
:root {
  --unit-0x: 0px;
  --unit-x: 1px;
  --unit-2x: 2px;
  --unit-4x: 4px;
  --unit-6x: 6px;
  --unit-8x: 8px;
  --unit-10x: 10px;
  --unit-12x: 12px;
  --unit-14x: 14px;
  --unit-16x: 16px;
  --unit-18x: 18px;
  --unit-20x: 20px;
  --unit-24x: 24px;
  --unit-32x: 32px;
  --unit-40x: 40px;
  --unit-48x: 48px;
  --unit-56x: 56px;
  --unit-64x: 64px;
  --unit-72x: 72px;
  --unit-80x: 80px;

  /* space */
  --measurement-space-0x: var(--unit-0x);
  --measurement-space-2x: var(--unit-2x);
  --measurement-space-4x: var(--unit-4x);
  --measurement-space-6x: var(--unit-6x);
  --measurement-space-8x: var(--unit-8x);
  --measurement-space-10x: var(--unit-10x);
  --measurement-space-12x: var(--unit-12x);
  --measurement-space-14x: var(--unit-14x);
  --measurement-space-16x: var(--unit-16x);
  --measurement-space-20x: var(--unit-20x);
  --measurement-space-24x: var(--unit-24x);
  --measurement-space-32x: var(--unit-32x);
  --measurement-space-48x: var(--unit-48x);
  --measurement-space-64x: var(--unit-64x);

  /* size */
  --measurement-size-4x: var(--unit-4x);
  --measurement-size-6x: var(--unit-6x);
  --measurement-size-8x: var(--unit-8x);
  --measurement-size-12x: var(--unit-12x);
  --measurement-size-14x: var(--unit-14x);
  --measurement-size-16x: var(--unit-16x);
  --measurement-size-18x: var(--unit-18x);
  --measurement-size-20x: var(--unit-20x);
  --measurement-size-24x: var(--unit-24x);
  --measurement-size-32x: var(--unit-32x);
  --measurement-size-40x: var(--unit-40x);
  --measurement-size-48x: var(--unit-48x);
  --measurement-size-56x: var(--unit-56x);
  --measurement-size-64x: var(--unit-64x);
  --measurement-size-72x: var(--unit-72x);
  --measurement-size-80x: var(--unit-80x);
}
``` 

This is when the frustration comes to me, because I don't know to transform those tokens into Tailwind config properly, since it only has `theme.spacing` API only.

As our DLS: 
- `theme.{margin,padding,...}` would use `--measurement-space-**`
- `theme.{width,height,...}` would use `--measurement-size-**`

Is there any shorter way to do it instead of manually override option by option? I believe that Tailwind 4 could be the answer, but I still think Tailwind 3 can overcome this.
