### DISCUSSION TITLE
Add unprefixed versions of align/justify properties to align/justify classes

### DISCUSSION THREAD

**Discussion by Dan503** [tailwindlabs/tailwindcss#1354] [Ideas]
>  @gcoda 
> did i miss a note on justify\align\content ?
>
>.content-stretch { align-content: stretch } is possible and useful on grid.
I am also missing ~ self-justify-center: { justify-self: center } and i am not sure hot this should be called, but already using it...
> https://github.com/tailwindcss/tailwindcss/pull/1274#issuecomment-576042422

These should technically already be supported since CSS Grid and Flexbox both share the justify and align properties. However based on the Tailwind documentation, it looks like it only supports the old Flexbox only syntax.

```css
.justify-start {
    justify-content: flex-start;
}
```

https://tailwindcss.com/docs/justify-content/#app

These justify and alignment properties should be updated to also support CSS Grid.

```css
.justify-start {
   /* "flex-start" in-case the browser doesn't understand "start" on it's own */
    justify-content: flex-start;
    justify-content: start;
}
```

Affected properties:

- align-content
- justify-content
- place-content
- align-items
- justify-items
- place-items
- align-self
- justify-self
- place-self
