### DISCUSSION TITLE
v4 + svelte, specify :dark variant for a color in app.css

### DISCUSSION THREAD

**Discussion by yanismarkin** [tailwindlabs/tailwindcss#13612] [Help]
is there a way to specify :dark variant for a color in app.css:

```
--color-pink: #FF00FE;
--color-pink:dark: #FF00AA;
```

to simply use one color name in html:

`<p class="text-pink bg-pink">123</p>`

**Comment by wongjn** [comment]
You could do:
```css
@theme {
  --color-pink: #FF00FE;
}

@media (prefers-color-mode: dark) {
  :root {
    --color-pink: #FF00AA;
  }
}
```
See this working in [this Tailwind Play](https://play.tailwindcss.com/vTVyHPlfGW?file=css) (you can use your browser's developer tools or your system settings to toggle `prefers-color-mode` to see the color changing).
