### DISCUSSION TITLE
add @supports not

### DISCUSSION THREAD

**Discussion by theLeroy** [tailwindlabs/tailwindcss#13619] [Ideas]
Tailwind supports the[ @supports css query](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports?retiredLocale=de) but not with the 'not' operator.

This would be so useful, especially in the age where container queries are not yet supported everywhere. The problem currently is that the fallback for container query are not easily done at the moment. The problem is that if you want to implement fallback query the querys are always active and will overwrite the container querrys. their support-not will provide a solution for this.

My suggestion would be simply to add the support util support-not.

The md Docs:
https://developer.mozilla.org/en-US/docs/Web/CSS/@supports?retiredLocale=de#the_not_operator

**Comment by fordaaron** [comment]
The `not` operator can currently be passed into `supports-[...]`. 
```html
<div class="supports-[not(container-type:inline-size)]:md:grid-cols-2"></div>
```
```css
@supports not (container-type:inline-size) {
  @media (min-width: 768px) {
    .supports-\[not\(container-type\:inline-size\)\]\:md\:grid-cols-2 {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
  }
}
```
[Tailwind Play Demo](https://play.tailwindcss.com/nb8cbbUTx2)

---

Alternatively, you could configure a shortcut for this within your `tailwind.config` if this is commonly reused to allow for a class like this to work:
```html
<div class="supports-not-container:md:grid-cols-2"></div>
```
[Tailwind Play Demo](https://play.tailwindcss.com/iyAyec8Qq5) | [Related Documentation](https://tailwindcss.com/docs/hover-focus-and-other-states#supports-rules)
