### DISCUSSION TITLE
How to override a plugin's styling?

### DISCUSSION THREAD

**Discussion by ryanvelbon** [tailwindlabs/tailwindcss#13681] [Help] [answered]
I want to override Tailwind CSS Typography's styling of all `<code>` elements (except code blocks - i.e., those which are nested in `<pre>`).

I've added this to my stylesheet which works fine except that some utility classes (e.g. `font-medium text-red-500`) are then overridden by the plugin.

```css
.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *))::before {
   content: "";
}

.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *))::after {
   content: "";
}

:not(pre) > code {
   @apply bg-gray-300 font-medium text-red-500 px-2 py-0.5;
}
```

Here's my tailwind.config.js file

```js
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.vue',
        './content/**/*.md',
    ],

    theme: {
        extend: {
            typography: {
                
            },
        },
    },

    plugins: [
        require('@tailwindcss/typography'),
    ],
};
```

So is there a way to apply this styling after the plugin is imported?
