### DISCUSSION TITLE
Setup VSCode for composing Tailwind utility classes in CSS files

### DISCUSSION THREAD

**Discussion by ldm-acn** [tailwindlabs/tailwindcss#13732] [Help]
I'm considering a setup with Tailwind and css modules, using VSCode this yields a few warnings whenever I try to compose Tailwind responsive selectors inside a css module file. These are my settings.json and my css file, resulting in a `) expected` error after the colon.

```json
{
    "css.validate": true,
    "css.lint.validProperties": [
        "composes"
    ],
}
```

```css
.custom-class {
    composes:
      global(text-blue-600);
  
    composes:
      global(md:flex)
}
```

![Screenshot 2024-05-23 153211](https://github.com/tailwindlabs/tailwindcss/assets/103132174/2b49d82b-c14a-444d-bd4a-1a44e13dfd55)

Do you have any suggestion on how to setupo the IDE for cases like this?
