### DISCUSSION TITLE
How i can set rgba-color from theme?

### DISCUSSION THREAD

**Discussion by projct1** [tailwindlabs/tailwindcss#13762] [Help] [answered]
In `app.css` i write this:
```css
@layer utilities {
    .my-class {
        background: theme('colors.purple.500/50');
    }
}
```
But output this:
```css
.my-class {
    color: rgb(168 85 247 / 50);
}
```
Excepted behaviour is:
```css
.my-class {
    color: rgba(168, 85, 247, .5);
}
```

**Comment by wongjn** [comment]
If you are using a PostCSS build pipeline, you could consider having a PostCSS plugin that runs after Tailwind that converts the `rgb()` colors into the legacy format.

**Reply by projct1** [reply]
I dont understand, what are you mean :(
RGBA is legacy format?
My `postcss.config.js` is:
```js
export default {
    plugins: {
        'tailwindcss/nesting': {},
        tailwindcss: {},
        autoprefixer: {}
    }
}
```

**Reply by wongjn** [reply]
Yes, `rgba()` is considered the legacy format for using the `rgb()` function.

**Reply by projct1** [reply]
Hmm, i'll know, thanks.
I dont need legacy format, i need opacity)
Why this not working?
```css
.my-class {
    color: rgb(168 85 247 / 50);
}
```
Opacity is not applied.
