### DISCUSSION TITLE
[Intellisense] Syntax highlighting should work in CSS modules with the `composes` and `global` keywords

### DISCUSSION THREAD

**Discussion by ldm-acn** [tailwindlabs/tailwindcss#13764] [Ideas]
I'm considering relying on a mix of CSS modules and Tailwind and it'd be useful to be able to mix CSS modules' `compose` keyword with the `global` keyword to compose several tailwind class names in a single rule.

The following code works in that `custom-class` adds the proper CSS rules for font-size, color and display, but in VSCode I currently don't get any syntax highlightning.

```css
.custom-class {
    font-size: theme('spacing.10');

    composes:
        global(text-blue-600);
  
    composes:
        global(md:flex)
}
```

![Screenshot 2024-05-30 102650](https://github.com/tailwindlabs/tailwindcss/assets/103132174/b27eca00-8ce2-42cb-bd35-ebf66aefc9c7)
