### DISCUSSION TITLE
Provide Official Docker Image with Tailwindcss CLI

### DISCUSSION THREAD

**Discussion by alephao** [tailwindlabs/tailwindcss#13822] [Ideas]
Hello, I'm wondering if providing an official docker image with the tailwindcli is something the maintainers are interested in?

It's a really nice extra for anyone using docker during any phase of the development cycle. I personally setup docker compose with all tooling needed so I'm sure the whole team is using the correct tooling always.

It's not a big burden to maintain too, it only requires a Dockerfile, a place to store the images like https://hub.docker.com and a CI pipeline to build and push the image.

With an official tailwindcss image, people would be able to run the cli via docker like so:

```bash
docker run -v .:/app --rm tailwindlabs/tailwindcss:3.4.4 -o ./tailwindcss
``` 

Below is an example of a I setup I do locally to get an image with the CLI installed and run it via docker-compose.

**Dockerfile**

```dockerfile
FROM alpine:3.19

RUN apk --no-cache add curl

RUN curl -sLo tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.4/tailwindcss-linux-arm64
RUN chmod +x tailwindcss
RUN mv tailwindcss /usr/bin

ENTRYPOINT ["tailwindcss"]
```

**docker-compose.yml**

```yml
version: '3.7'

name: tools
services:
  tailwindcss:
    profiles: [tools]
    image: tailwindcss
    build: tailwind.Dockerfile
    volumes:
    - .:/app
    working_dir: /app
```

**commands**

```bash
# Run once
docker compose run --rm tailwindcss -o ./tailwind.css
	
# Watch
docker compose run --rm -d tailwindcss -o ./tailwind.css --watch
```
