### DISCUSSION TITLE
Supporting sybling selector for darkmode.

### DISCUSSION THREAD

**Discussion by mayank1513** [tailwindlabs/tailwindcss#13835] [Ideas]
Currently, class selector is supported for applying dark mode. This works very well for client side applications. However, in many cases I need to use sibling selector (~). For example, checkout this one - https://github.com/vercel/next.js/pull/66794

## Proposal

Extend plugin configuration to support something like `darkMode: "class:sibling"`. This should generate CSS similar to follows

```css
.dark .dark\:bg-gray-800, /* children */
.dark ~ .dark\:bg-gray-800, /* sibling */
.dark ~ * .dark\:bg-gray-800 { /* sibling children */
    background-color: #2d3748;
}
```
