### DISCUSSION TITLE
How to add a custom font in Tailwind 4

### DISCUSSION THREAD

**Discussion by tembbo** [tailwindlabs/tailwindcss#13890] [Help] [answered]
I have a newly created project with SvelteKit and Vite, and have upgraded to the NEWEST Tailwind version (v4 alpha). But I'm wondering how you would add a custom font (let's say font.woff2). I have tried setting it with the `@font-face` in app.css but that doesn't work. Thank you.

**Comment by adamwathan** [comment]
Can you share an example project? What you've described sounds right to me, you just do it the same way you do with regular CSS.

**Reply by tembbo** [reply]
This is what i tried in the app.css

```css
@import "tailwindcss";

@font-face {
    font-family: "font";
    display: swap;
    src: url("/font.woff2");
}
```

and then my +layout.svelte

```svelte
<script>
    import "../app.css";
</script>

<slot></slot>
```

then the +page.svelte
```svelte
<div>
    <h1>Thank you!</h1>
</div>
```



btw, im using tailwind with vite:

```js
import { sveltekit } from "@sveltejs/kit/vite";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vite";

export default defineConfig({
    plugins: [sveltekit(), tailwindcss()],
});

```

**Comment by corneliusio** [comment]
@gu5e Make sure you're adding something like the following to generate/update the classes and custom properties.
```css
@theme {
    --font-family-sans: "font", sans-serif;
}
```

**Reply by tembbo** [reply]
Thank you so much @corneliusio!

**Reply by 7flash** [reply, marked as answer]
I think your answer should be updated to 

```
@theme {
    --font-sans: "font", sans-serif;
}
```

**Reply by brunobely** [reply]
What if I want to do what was previously done like this?

```ts
import { fontFamily } from 'tailwindcss/defaultTheme';

// ...

fontFamily: {
  sans: ['font', ...fontFamily.sans],
},
```

**Reply by tembbo** [reply]
@brunobely I don't think there's anyway of doing this in the new css config, the closest you could come is via importing the tailwind js config with `@config` into the css config. Or if you wanna use css you could write the default fonts + the new custom font like this:

```css
@theme {
	--font-sans: "font", ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```

Or you could just use `sans-serif`:

```css
@theme {
	--font-sans: "font", sans-serif;
}
```

**Reply by kurumeii** [reply]
> Or you could just use sans-serif

@realguse will it be enough, though? just curious and all

**Reply by tembbo** [reply]
The average user would probably not see the difference. This is how I'm currently doing it on my website:

```css
@font-face {
    font-family: Geist;
    font-display: swap;
    src: url("/geist.woff2") format("woff2");
}

@font-face {
    font-family: Calistoga;
    font-display: swap;
    src: url("/calistoga.woff2") format("woff2");
}

@theme {
    --font-sans: Geist, sans-serif;
    --font-serif: Calistoga;
}
```

It's simple, but it just works

**Reply by SalathielGenese** [reply]
I have exactly that with Angular v19 and:
- my style.css in browser got it
- my override is simply ignored
- my custom fonts are never even loaded

**Reply by tembbo** [reply]
@SalathielGenese I'm no angular expert but I would recommend looking at the docs (https://tailwindcss.com/docs/installation/framework-guides/angular) and checking if everything is configured properly. If that doesn't work, maybe try ti initialise a new project and seeing if it works then. Sorry for not providing a proper answer

**Reply by pradeepdreamzsop** [reply]
it not working for me

**Reply by tembbo** [reply]
@kurumeii and @brunobely, according to the tailwind website, they seem to advocate using `sans-serif` instead of `ui-sans-serif, system-ui, sans-serif, "Appl...`

![image](https://github.com/user-attachments/assets/db16d158-b6f8-48aa-86ce-ae8e9a10d9df)
(https://tailwindcss.com/docs/theme)

**Reply by victusen** [reply]
It's works this way for me. In your input.css file. NG


@import "tailwindcss";

@font-face {
  font-family: "Bricolage";
  src: url(../assets/fonts/Bricolage_Grotesque/static/BricolageGrotesque-Bold.ttf)
}

@font-face {
  font-family: "DM-sans";
  src: url(../assets/fonts/DM_Sans/DMSans-VariableFont_opsz\,wght.ttf);
}

**Comment by CustomEntity** [comment]
Hello, it doesn't work when I upgrade to the following version `4.0.0-alpha.34`.

**Reply by RobinMalfait** [reply]
Hey! We renamed `--font-family` to `--font`, if you update your CSS then this should start working again 👍

See: https://github.com/tailwindlabs/tailwindcss/pull/14885 for more info

**Comment by mdalmamunit427** [comment]
There I'm doing this way to customizing fonts, using google fonts and override it tailwind's default fonts:

@theme{

//override default fonts
--font-*: initial
--font-sans: "Satoshi", "sans-serif";

// custom fonts( to be safe I imported it from Google fonts)
--font-primary : "Poppins", "serif";  
--font-secondary: "Roboto", "serif";
}

If need how I did this, here is a [video](https://youtu.be/SbBSgy1HyBI)

**Reply by tembbo** [reply]
Remember to use `sans-serif` as a fallback font instead of `serif` @mdalmamunit427

**Reply by mdalmamunit427** [reply]
I was actually followed Google Fonts Family, there was serif that why I used it. Thank you for your feedback

**Reply by tembbo** [reply]
Hmmmm, that's weird. `sans-serif` should be the most obvious option here, since neither Poppins or Roboto has serifs

**Comment by formbook** [comment]
if its not broke dont fix it

what a fking shambles

**Reply by titusdecali** [reply]
Indeed. I prefer this type of config to be in the tailwind.config file

**Comment by tobyweb3x** [comment]
@RobinMalfait @realguse 

really sorry to bother, i've tried all i can think about and followed the instruction you gave, still does not work. please help.
![tai](https://github.com/user-attachments/assets/7cdfeaf9-3c9e-470b-947d-53b052532da7)

**Reply by tembbo** [reply]
Hi @tobyweb3x, it looks like you've forgot to add `--font-sans` to `@theme` which is what tailwind looks at for the default font. 

Corrected:
```css
@theme {
	--font-sans: "DM Sans-Regular";
}
```

You could also add the `--font-dmSansRegular` class in every place you'd like to use it

**Reply by tobyweb3x** [reply]
```css
@theme {
  --font-dmSansRegular: "DM Sans-Regular";
}
```

this is how exactly i have it, looks the same with what you mentioned now (or what am i not getting please? @realguse ). also the intelisense is not picking it up... i do have the tailwindcss extension.

i very much appreciate the quick response.

**Reply by tembbo** [reply]
I belive that I don't quite understand. Just for clarification, do you want to make DM Sans your default sans-serif font, or use it sparingly, by adding it as a class in your markup manually?

This is what you would do if you want to set it as the default sans font (just replace Brush Script MT with your font): https://play.tailwindcss.com/RDIkgD6aJ9 

This is what you would do if you would like to use it only in specific places (notice the addition of setting the class manually in the markup): https://play.tailwindcss.com/e8A7FSv8wU

**Reply by tobyweb3x** [reply]
Please allow me to clarify better in a lots of words, so this is my current setup — changed the font to `Archivo`.

```css
@font-face {
  font-family: "Archivo SemiCondensed-regular";
  font-style: normal;
  font-weight: 400;
  src: url("/public/assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Regular.ttf")
    format("truetype");
}

@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentcolor);
  }
}

@theme {
  --font-archivo: "Archivo SemiCondensed-regular", san-serif;
}

@utility themed-btn {
  background-image: linear-gradient(88.93deg, #9945ff -4.48%, #12db88 114.18%);
}

/* .font-archivo {
  font-family: "Archivo SemiCondensed", sans-serif;
} */

```

the html:
```html
<body class="text-[#EBEBEB] bg-[#06001B] font-archivo">
```

With this setup, it doesn’t work. But when I uncomment the native CSS font-archivo, everything works fine — so it’s clearly not a src issue (which I initially suspected).

I also noticed that Tailwind CSS IntelliSense in VSCode doesn’t recognize font-ar... — no autocomplete or hover info. That got me thinking it might be a Tailwind-related issue.

After digging deeper, I found out it was actually an override issue.

<img width="459" alt="Screenshot 2025-05-05 at 12 48 50 PM" src="https://github.com/user-attachments/assets/3ef8dc46-6a6c-4a1a-abbc-9ef07791e820" />

If I use the ! (important operator — not sure if that’s the correct term), the issue gets resolved and the font works. But even then, Tailwind CSS IntelliSense still doesn’t recognize the class.

So I have two questions:
	1.	How can I get it working without needing the !?
	2.	How do I fix Tailwind IntelliSense in VSCode? (The extension is already installed.)
	
```html
<body class="text-[#EBEBEB] bg-[#06001B] !font-archivo">
```

<img width="385" alt="Screenshot 2025-05-05 at 12 53 02 PM" src="https://github.com/user-attachments/assets/d0cb9ef3-43b4-4b24-9875-7b2b762b6ef8" />

Thanks 🙏, @realguse .

**Comment by nnx0r** [comment]
This is how you'd change default `font-family` by keeping fallback options from Tailwind and without introducing additional custom class for your font.

```css
@theme {
  --default-font-family: 'Inter', var(--font-sans);
}
```

Enjoy!

**Comment by harrison-broadbent** [comment]
For anyone finding this thread, I've collated it into a short blog post: [custom fonts in Tailwind v4 & v3.](https://harrisonbroadbent.com/blog/tailwind-custom-fonts/)

At a guess though: you're probably missing a line like this (goes after `@import 'tailwindcss'`):
```css
@theme {
  --font-[name]: "your font name", sans-serif;
}
```

ie: 

`--font-mono: "Jetbrains Mono", monospace;`

**Reply by mustansirr** [reply]
Hey @harrison-broadbent, I believe i've done everything correctly, however i still can't manage to get the correct fonts to display. I'm using google fonts, ive embedded the '@import' link in my globals.css with '@import "tailwindcss";'

Ive also added the fonts i wanna use.

@theme {
  --font-inter: 'Inter', 'Arial', 'sans-serif';
  --font-bebas: 'Bebas Neue', 'Arial', 'sans-serif';

Could you help me find a solution for this?

**Reply by harrison-broadbent** [reply]
@mustansirr the `@import "tailwindcss"` line needs to go after the `@import url('...')` line, did you do that?

For instance, my `application.css` looks like:

```css
@import url("https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap");

@import "tailwindcss";
@theme {
  --font-mono: "Jetbrains Mono", monospace;
}

...
```

Also, you'll need to use classes like `font-inter` and `font-bebas` in your HTML. Was that intentional? You can try renaming the inter class to `--font-sans` which is the default font family in Tailwind. That might help you quickly test if the font is loading. 

Otherwise, can you post more of your `global.css` file?
And what is your framework? Make sure you've followed the steps here to correctly configure Tailwind CSS for whatever framework you're using: https://tailwindcss.com/docs/installation/framework-guides

**Comment by PaulSinghDev** [comment]
If anyone else stumbles onto the issue of font-weights not taking effect check whether you have the `@font-face` rule defined in an `@layer` block. Removing them from the `@layer` solved it for me. 

Not working:

```css
@layer base {
  @font-face {
    font-family: "Bw Gradual";
    src: url("./assets/fonts/Bw-Gradual-Regular/BwGradual-Regular.woff2")
        format("woff2"),
      url("./assets/fonts/Bw-Gradual-Regular/BwGradual-Regular.woff")
        format("woff");
    font-weight: 400 600;
    font-style: normal;
  }

  @font-face {
    font-family: "Bw Gradual";
    src: url("./assets/fonts/Bw-Gradual-Regular-Italic/BwGradual-RegularItalic.woff2")
        format("woff2"),
      url("./assets/fonts/Bw-Gradual-Regular-Italic/BwGradual-RegularItalic.woff")
        format("woff");
    font-weight: 400 600;
    font-style: italic;
  }

  @font-face {
    font-family: "Bw Gradual";
    src: url("./assets/fonts/Bw-Gradual-Medium/BwGradual-Medium.woff2")
        format("woff2"),
      url("./assets/fonts/Bw-Gradual-Medium/BwGradual-Medium.woff")
        format("woff");
    font-weight: 700 800;
    font-style: normal;
  }

  @font-face {
    font-family: "Bw Gradual";
    src: url("./assets/fonts/Bw-Gradual-Medium-Italic/BwGradual-MediumItalic.woff2")
        format("woff2"),
      url("./assets/fonts/Bw-Gradual-Medium-Italic/BwGradual-MediumItalic.woff")
        format("woff");
    font-weight: 700 800;
    font-style: italic;
  }

  @font-face {
    font-family: "Bw Gradual";
    src: url("./assets/fonts/Bw-Gradual-Black/BwGradual-Black.woff2")
        format("woff2"),
      url("./assets/fonts/Bw-Gradual-Black/BwGradual-Black.woff") format("woff");
    font-weight: 900;
    font-style: normal;
  }

  @font-face {
    font-family: "Bw Gradual";
    src: url("./assets/fonts/Bw-Gradual-Light/BwGradual-Light.woff2")
        format("woff2"),
      url("./assets/fonts/Bw-Gradual-Light/BwGradual-Light.woff") format("woff");
    font-weight: 100 300;
    font-style: normal;
  }
}
```

Working: 

```css
@font-face {
  font-family: "Bw Gradual";
  src: url("./assets/fonts/Bw-Gradual-Regular/BwGradual-Regular.woff2")
      format("woff2"),
    url("./assets/fonts/Bw-Gradual-Regular/BwGradual-Regular.woff")
      format("woff");
  font-weight: 400;
  font-style: normal;
}

@font-face {
  font-family: "Bw Gradual";
  src: url("./assets/fonts/Bw-Gradual-Regular-Italic/BwGradual-RegularItalic.woff2")
      format("woff2"),
    url("./assets/fonts/Bw-Gradual-Regular-Italic/BwGradual-RegularItalic.woff")
      format("woff");
  font-weight: 400;
  font-style: italic;
}

@font-face {
  font-family: "Bw Gradual";
  src: url("./assets/fonts/Bw-Gradual-Medium/BwGradual-Medium.woff2")
      format("woff2"),
    url("./assets/fonts/Bw-Gradual-Medium/BwGradual-Medium.woff") format("woff");
  font-weight: 700;
  font-style: normal;
}

@font-face {
  font-family: "Bw Gradual";
  src: url("./assets/fonts/Bw-Gradual-Medium-Italic/BwGradual-MediumItalic.woff2")
      format("woff2"),
    url("./assets/fonts/Bw-Gradual-Medium-Italic/BwGradual-MediumItalic.woff")
      format("woff");
  font-weight: 700;
  font-style: italic;
}

@font-face {
  font-family: "Bw Gradual";
  src: url("./assets/fonts/Bw-Gradual-Black/BwGradual-Black.woff2")
      format("woff2"),
    url("./assets/fonts/Bw-Gradual-Black/BwGradual-Black.woff") format("woff");
  font-weight: 900;
  font-style: normal;
}

@font-face {
  font-family: "Bw Gradual";
  src: url("./assets/fonts/Bw-Gradual-Light/BwGradual-Light.woff2")
      format("woff2"),
    url("./assets/fonts/Bw-Gradual-Light/BwGradual-Light.woff") format("woff");
  font-weight: 100;
  font-style: normal;
}
```
