### DISCUSSION TITLE
Gradients do not work in Firefox in v4.0.0-alpha.16, potentially caused by special `@supports (-moz-orient: inline)` selector

### DISCUSSION THREAD

**Discussion by sceee** [tailwindlabs/tailwindcss#13941] [Help] [answered]
Gradients do not seem to work in Firefox in `v4.0.0-alpha.16` whereas they work in Chrome.

See the following example in Chrome vs. Firefox:
https://play.tailwindcss.com/ASf2fh5fiH

In Chrome it works but in Firefox the gradient is not displayed.
While I applied layers in the example, the same issue occurs if I just `@import 'tailwindcss';` instead:
https://play.tailwindcss.com/MPNPWOGHdL?file=css

It seems in Firefox there is a special ruling applied to the element based on the `@supports (-moz-orient: inline)` selector. It seems this is injected here: https://github.com/tailwindlabs/tailwindcss/blob/62de02a37946c48c5fa6cdb800173b54198ebb9b/packages/tailwindcss/src/ast.ts#L202
```css
@supports (-moz-orient: inline) {
  @layer base {
    *, ::before, ::after, ::backdrop {
      --tw-gradient-from: #0000;
      --tw-gradient-to: #0000;
      --tw-gradient-via: transparent;
      --tw-gradient-stops: ;
      --tw-gradient-via-stops: ;
      --tw-gradient-from-position: 0%;
      --tw-gradient-via-position: 50%;
      --tw-gradient-to-position: 100%;
    }
  }
}
```

According to the Browser dev tools, `--tw-gradient-from`, `--tw-gradient-to` and `--tw-gradient-stops` are overwritten (and therefore not applied) but `--tw-gradient-via-stops` is set to [nothing] which seems to cause this issue.

If I disable the `--tw-gradient-via-stops` setting from this rule in the dev tools, the gradient also appears in Firefox.

Is this a known issue or shall I open a issue for this?
