### DISCUSSION TITLE
Why the `container -> screens` uses values as media query?

### DISCUSSION THREAD

**Discussion by 7iomka** [tailwindlabs/tailwindcss#13969] [Help]
**What version of Tailwind CSS are you using?**

v3.4.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite

**What version of Node.js are you using?**

v18.18.2

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/ZD4y2b0WTo?file=config

**Describe your issue**

Why the `screens` under `container` uses values as media query?

For example for `lg` breakpoint I have 992px value (62em equivalent), and I want the max-width of container for this breakpoint to be 960px (60em eq).

Expected result: 
```css
@media (min-width: 62em) {
    .container {
        max-width: 60rem;
    }
}
```

Actual result:
```css
@media (min-width: 60em) {
    .container {
        max-width: 60em;
    }
}
```
