### DISCUSSION TITLE
[V4] BG-OPACITY

### DISCUSSION THREAD

**Discussion by NicolasCassunde** [tailwindlabs/tailwindcss#14002] [Help]
How can I use bg-opacity in Tailwind CSS v4?

**Comment by wongjn** [comment]
You'd use the slash syntax, like `bg-red-500/50`.

**Reply by MadisoMelese** [reply]
Thank you Wongjn

**Comment by davidhellmann** [comment]
Is it possible to use it within CSS files? This isn't working. 
```css
.yo {
  border-right: 1px solid theme(--color-white / 10%);
  color: theme(--color-white / 20%);
}

**Reply by wongjn** [reply]
You could do:

```css
.yo {
  border-right: 1px solid theme(colors.white / 10%);
  color: theme(colors.white / 20%);
}
```

https://play.tailwindcss.com/do3KHFRGuk
