### DISCUSSION TITLE
Possible duplicate CSS generation?

### DISCUSSION THREAD

**Discussion by thevipinmishra** [tailwindlabs/tailwindcss#14001] [General]
Hi there, a very strange thing I came across while checking the generated CSS on the Tailwind play website.

Consider the following HTML.

```html
<p class="lg:text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
```

and Tailwind generates the following CSS. (excludingPreflight CSS)

```css
.text-sm {
  font-size: 0.875rem;
  line-height: 1.25rem;
}
@media (min-width: 1024px) {
  .lg\:text-sm {
    font-size: 0.875rem;
    line-height: 1.25rem;
  }
}
```

This got me thinking, why is it like this?

only 1 class was supposed to be generate right? only inside media query, not the vanilla version.

Just to confirm this, I ran it without it and it just worked fine.

Am I missing something?
