### DISCUSSION TITLE
How to Prevent Class Sorting in Tailwind CSS Compilation?

### DISCUSSION THREAD

**Discussion by MonaAghili** [tailwindlabs/tailwindcss#14077] [Help] [answered]
I have default classes for my components:

```html
text-[#3E3E3E] border-[#DADADA]
```

Users can change colors by adding their own classes:

```html
<Badge.badge
  size="medium"
  rounded="full"
  class="text-[#3538CD] border-[#C7D7FE]"
>
  Marketing
</Badge.badge>
```

And the component in the DOM ends up with:

```html
<div class="text-[#3E3E3E] border-[#DADADA] text-[#6941C6] border-[#E9D7FE]">
</div>
```

The problem is that the colors should change to what the user adds to the classes, but they won't apply. The output CSS looks like this:

```css
.text-\[\#3538CD\] {
  --tw-text-opacity: 1;
  color: rgb(53 56 205 / var(--tw-text-opacity));
}

.text-\[\#3E3E3E\] {
  --tw-text-opacity: 1;
  color: rgb(62 62 62 / var(--tw-text-opacity));
}
```

The issue is that the default class is after the class we add to the component in CSS output file, causing the styles not to update as intended.

How can we solve this issue so that the user's added classes take precedence over the default classes?  Is there a way to solve this problem by modifying the tailwind config?
