### DISCUSSION TITLE
What `future` config option properties do?

### DISCUSSION THREAD

**Discussion by babakfp** [tailwindlabs/tailwindcss#14112] [Help]
Hi 👋

These are the options:

```js
{
    future: {
        hoverOnlyWhenSupported: true,
        disableColorOpacityUtilitiesByDefault: true,
        respectDefaultRingColorOpacity: true,
        relativeContentPathsByDefault: true,
    },
}
```

It would be great if there was jsDoc comments to explain what these do.

### `hoverOnlyWhenSupported`

```html
<button class="hover:bg-green-600" />
```

When the `hoverOnlyWhenSupported` option is enabled, on mobile, when pressing/holding the button, the background color won't change.

### `disableColorOpacityUtilitiesByDefault`

When is `false`:

```css
.bg-green-700 {
    --tw-bg-opacity: 1;
    background-color: rgb(21 128 61 / var(--tw-bg-opacity)) /* #15803d */;
}
```

When is `true`:

```css
.bg-green-700 {
    background-color: #15803d;
}
```

### `respectDefaultRingColorOpacity`

The only thing that this does, is to change this:

```css
--tw-ring-color: #3b82f67f;
```

To this:

```css
--tw-ring-color: rgb(59 130 246 / 0.5);
```

### `relativeContentPathsByDefault`

https://github.com/tailwindlabs/tailwindcss/pull/9396
