### DISCUSSION TITLE
[V4] Themeable utilities use properties

### DISCUSSION THREAD

**Discussion by tryoxiss** [tailwindlabs/tailwindcss#14219] [Ideas]
For V4, the [blog post](https://tailwindcss.com/blog/tailwindcss-v4-alpha#zero-configuration-content-detection) mentions that it exposes the custom properties used for config as CSS variables. Does it already or could it use the custom properties that are defined, since they are output.

For example:

```css
@theme {
    --color-gray-50: #f8fafc;
}

// could output something along the lines of

:root {
  --color-gray-50: #f8fafc;
}

.text-gray-50 { color: var(--color-gray-50); }

// rather than using the value directly

.text-gray-50 { color: #f8fafc; }
```

This would make arbitrary theming near trivial, as the properties could just be overloaded by another stylesheet.

```
// output.css
:root {
  --color-gray-50: #f8fafc;
}

.text-gray-50 { color: var(--color-gray-50); }

// my-theme.css
:root {
  --color-gray-50: #f8f8f8;
}

// now `--color-gray-50` evaluates to `f8f8f8`. This can be combined with media queries to easily accomodate for all combinations of `prefers-color-scheme: dark | light`, and `prefers-contrast: less | no-preference | more`, or even just custom color schemes. 
```

I don't see this being super important for most websites, but it would be hugely useful for web apps. And its a very small change (if its not already how it works, I dont know how to check 😖)
