### DISCUSSION TITLE
How do I convert this to TailwindCSS?

### DISCUSSION THREAD

**Discussion by codesfromshad** [tailwindlabs/tailwindcss#14242] [Help]
```TSX
// list.tsx
import React, {forwardRef} from "react";
import { cn } from "~/lib/utils";

import styles from "./list.module.css";

export interface Props {
  children: React.ReactNode;
  columns?: number;
  style?: React.CSSProperties;
  horizontal?: boolean;
}

export const List = forwardRef<HTMLUListElement, Props>(
  ({children, columns = 1, horizontal, style}: Props, ref) => {
    return (
      <ul
        ref={ref}
        style={
          {
            ...style,
            "--columns": columns,
          } as React.CSSProperties
        }
        className={cn(
          styles.List,
          horizontal && styles.horizontal
        )}
      >
        {children}
      </ul>
    );
  }
);
```
```css
/* list.module.css */
.List {
  display: grid;
  grid-auto-rows: max-content;
  box-sizing: border-box;
  min-width: 350px;
  grid-gap: 10px;
  padding: 20px;
  padding-bottom: 0;
  margin: 10px;
  border-radius: 5px;
  /* min-height: 200px; */
  transition: background-color 350ms ease;
  grid-template-columns: repeat(var(--columns, 1), 1fr);

  &:after {
    content: '';
    height: 10px;
    grid-column-start: span var(--columns, 1);
  }

  &.horizontal {
    width: 100%;
    grid-auto-flow: column;
  }
}
```
