### DISCUSSION TITLE
[v4] Cannot apply unknown utility class: ...

### DISCUSSION THREAD

**Discussion by EliasVal** [tailwindlabs/tailwindcss#14491] [Help]
Hello! I am attempting to upgrade to Tailwind V4 in my existing Next.js project (15.0.0-canary) and as soon as I run the app, the console is spammed with errors like this:
```
./**/*.scss.css
Error evaluating Node.js code
Error: Cannot apply unknown utility class: (utility class)
``` 

Example for an offending class:
```css
.tooltipContent {
  @apply fixed px-2 py-2;
  @apply rounded-lg text-start text-white text-sm pointer-events-none;
}
```

My `globals.scss` file imports tailwind like so:
```css
@import "tailwindcss";
@import "tailwindcss/preflight" layer(base);
@import "tailwindcss/utilities" layer(utilities);
```

PostCSS config:
```js
/** @type {import('postcss-load-config').Config} */
module.exports = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
```

Tailwind config:
```js
/** @type {import('tailwindcss').Config} */
const config = {
  important: true,
  theme: {
    extend: {
      colors: {
        'brand-primary': 'var(--brand-primary)',
        'brand-secondary': 'var(--brand-secondary)',
        'mui-gray': 'var(--mui-gray)',
        'shelly-gray': 'var(--shelly-gray)',
        'danger': 'var(--danger)',
        'success': 'var(--success)',
        'form': 'var(--form-bg)',
        'lightest-gray': 'var(--lightest-gray)',
        'shelly-disabled-gray': 'var(--shelly-disabled-gray)',
        'shelly-disabled-gray-text': 'var(--shelly-disabled-gray-text)',
        'brand-light': 'var(--brand-light)',
        'excel-green': 'var(--excel-green)',
      },
      fontWeight: {
        bold: '500',
      },
      fontSize: {
        'sm': '0.625rem',
        'base': '0.75rem', // 12px
        'lg': '0.875rem', // 14px
        'xl': '1rem', // 16px
        '2xl': '1.125rem',
        '3xl': '1.25rem',
        '4xl': '1.5rem',
        '5xl': '1.75rem',
        '6xl': '2rem',
        'custom-size': '1.75rem',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
```

**Comment by adamwathan** [comment]
Hey! Can you tell me specifically which class or classes it’s saying are invalid? Based on your setup I’d expect all the ones you’ve shown in your first snippet to work but if it’s stuff like `bg-brand-primary` it’s likely because you haven’t registered your config file using the `@config` directive which is necessary in v4.

You can also simplify your CSS file to just `@import “tailwindcss”`, you don’t need the other two lines 👍🏻

**Reply by EliasVal** [reply]
Hello! it seems that all classes included in `@apply` are reported as invalid, even classes such as `gap-*`, `p-*`, etc

**Reply by kirill-konshin** [reply]
In my case: `Error: Cannot apply unknown utility class: md:p-8`, `p-4`, `text-white`, `bg-black` and so on. This happens after migration to 4.0 using the tool.

**Reply by ikevinmejia** [reply]
In my case: `Error: Cannot apply unknown utility class:` `h-16v` `hover:bg-indigo-700` `hover:bg-opacity-20` `text-white` `text-opacity-50` `text-xl` `font-light`

 This happens after install v4

**Reply by kirill-konshin** [reply]
FYI I fixed it by @reference main.css with the theme into all css modules. It was a bit hard to find docs for this, and probably the migration tool should highlight stuff like that. Or even fix.

**Reply by Diogo-Falardo** [reply]
@kirill-konshin hey can u help? how can i do that ?

**Reply by kirill-konshin** [reply]
@Diogo-Falardo @ikevinmejia @EliasVal 

```css
/* src/global.css */
@import 'tailwindcss';
layer(utilities);
@plugin "@tailwindcss/typography";

@theme {
  --font-helios: 'HeliosCondCRegular', 'Impact', 'Sans-Serif';
  --breakpoint-sm: 640px;
  --breakpoint-md: 768px;
  --breakpoint-lg: 1024px;
  --breakpoint-xl: 1100px;
}

/* src/some.module.css */
@reference "./global.css";

.content {
  @apply flex flex-1 flex-col bg-white text-black;
}
```
