### DISCUSSION TITLE
There seems to be an issue with tailwindcss/nesting plugin

### DISCUSSION THREAD

**Discussion by AlemTuzlak** [tailwindlabs/tailwindcss#14529] [Help] [answered]
**What version of Tailwind CSS are you using?**

3.4.13

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.29

**What version of Node.js are you using?**

20

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

 https://github.com/forge42dev/Remix-Dev-Tools/pull/150

**Describe your issue**

So I have a very unique use-case with tailwind, I use it to style `remix-development-tools` which is an OSS library and as such it can't override global styles or anything on the users project/app. I decided to create a class on the root called "remix-dev-tools" and use the tailwind nesting plugin to append it to every class generated by tailwind so it does not conflict with users config in any way. This works great for 90% of classes but I've noticed that modifiers such as hover, after, before etc do not get nested, here is an example output of the script:
```css
// this part works awesome!
.remix-dev-tools .transition-all {
  transition-property: all;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 150ms;
}
.remix-dev-tools .transition-transform {
  transition-property: transform;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 150ms;
}
.remix-dev-tools .duration-1000 {
  transition-duration: 1000ms;
}
.remix-dev-tools .duration-200 {
  transition-duration: 200ms;
}
// this part doesn't :(
.after\:absolute::after {
  content: var(--tw-content);
  position: absolute;
}
.after\:-left-2::after {
  content: var(--tw-content);
  left: -0.5rem;
}
.after\:top-1\/2::after {
  content: var(--tw-content);
  top: 50%;
}
.after\:h-0::after {
  content: var(--tw-content);
  height: 0px;
}
.after\:w-0::after {
  content: var(--tw-content);
  width: 0px;
}
.after\:-translate-y-1\/2::after {
  content: var(--tw-content);
  --tw-translate-y: -50%;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
.after\:-rotate-90::after {
  content: var(--tw-content);
  --tw-rotate: -90deg;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
.after\:border-x-4::after {
  content: var(--tw-content);
  border-left-width: 4px;
  border-right-width: 4px;
}
.after\:border-b-\[6px\]::after {
  content: var(--tw-content);
  border-bottom-width: 6px;
}
.after\:border-x-transparent::after {
  content: var(--tw-content);
  border-left-color: transparent;
  border-right-color: transparent;
}
.after\:border-b-gray-700::after {
  content: var(--tw-content);
  --tw-border-opacity: 1;
  border-bottom-color: rgb(55 65 81 / var(--tw-border-opacity));
}
.hover\:cursor-pointer:hover {
  cursor: pointer;
}
.hover\:bg-\[\#121212\]:hover {
  --tw-bg-opacity: 1;
  background-color: rgb(18 18 18 / var(--tw-bg-opacity));
}
.hover\:bg-\[\#212121\]\/50:hover {
  background-color: rgb(33 33 33 / 0.5);
}
.hover\:text-gray-500:hover {
  --tw-text-opacity: 1;
  color: rgb(107 114 128 / var(--tw-text-opacity));
}
.hover\:text-green-600:hover {
  --tw-text-opacity: 1;
  color: rgb(22 163 74 / var(--tw-text-opacity));
}
.hover\:text-red-600:hover {
  --tw-text-opacity: 1;
  color: rgb(220 38 38 / var(--tw-text-opacity));
}
.hover\:opacity-50:hover {
  opacity: 0.5;
}
.hover\:ring-2:hover {
  --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
  --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);
  box-shadow:
    var(--tw-ring-offset-shadow),
    var(--tw-ring-shadow),
    var(--tw-shadow, 0 0 #0000);
}
.hover\:ring-offset-2:hover {
  --tw-ring-offset-width: 2px;
}
.focus\:bg-\[\#121212\]:focus {
  --tw-bg-opacity: 1;
  background-color: rgb(18 18 18 / var(--tw-bg-opacity));
}
.focus\:outline-none:focus {
  outline: 2px solid transparent;
  outline-offset: 2px;
}
.focus\:ring-2:focus {
  --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
  --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);
  box-shadow:
    var(--tw-ring-offset-shadow),
    var(--tw-ring-shadow),
    var(--tw-shadow, 0 0 #0000);
}
.focus\:ring-offset-2:focus {
  --tw-ring-offset-width: 2px;
}
.disabled\:cursor-not-allowed:disabled {
  cursor: not-allowed;
}
.disabled\:opacity-50:disabled {
  opacity: 0.5;
}
.group:hover .group-hover\:visible {
  visibility: visible;
}
.group:hover .group-hover\:opacity-100 {
  opacity: 1;
}
.data-\[disabled\]\:pointer-events-none[data-disabled] {
  pointer-events: none;
}
.data-\[side\=bottom\]\:translate-y-1[data-side=bottom] {
  --tw-translate-y: 0.25rem;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
.data-\[side\=left\]\:-translate-x-1[data-side=left] {
  --tw-translate-x: -0.25rem;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
.data-\[side\=right\]\:translate-x-1[data-side=right] {
  --tw-translate-x: 0.25rem;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
.data-\[side\=top\]\:-translate-y-1[data-side=top] {
  --tw-translate-y: -0.25rem;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
@keyframes accordion-up {
  from {
    height: var(--radix-accordion-content-height);
  }
  to {
    height: 0;
  }
}
.data-\[state\=closed\]\:animate-accordion-up[data-state=closed] {
  animation: accordion-up 0.2s ease-out;
}
@keyframes accordion-down {
  from {
    height: 0;
  }
  to {
    height: var(--radix-accordion-content-height);
  }
}
.data-\[state\=open\]\:animate-accordion-down[data-state=open] {
  animation: accordion-down 0.2s ease-out;
}
.data-\[disabled\]\:opacity-50[data-disabled] {
  opacity: 0.5;
}
@media (min-width: 1024px) {
  .lg\:\!flex-row {
    flex-direction: row !important;
  }
}
.\[\&\[data-state\=open\]\>svg\]\:rotate-180[data-state=open] > svg {
  --tw-rotate: 180deg;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}

```
here is my PostCSS config:
```ts
import tailwindcss from "tailwindcss";
import tailwindcssNesting from "tailwindcss/nesting/index.js";
import autoprefixer from "autoprefixer";
import config from "./tailwind.config.js";
export default {
  plugins: [tailwindcss(config),tailwindcssNesting(), autoprefixer()],
};
```
and tailwind.config.js:
```ts
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{tsx,ts,js}"],
  theme: {
    extend: {
      colors: {
        popover: "#212121",
        main: "#212121",
        "popover-foreground": "#fff",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in-left": {
          "0%": { opacity: 0, transform: "translateX(-100%)" },
          "100%": { opacity: 1, transform: "translateX(0)" },
        },
        "fade-in": {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-left": "fade-in-left 0.5s ease-in",
        "fade-in": "fade-in 0.5s ease-in",
      },
    },
  }, 
  plugins: [await import("tailwindcss-animate")],
 
};

```

I guess my question is: 
Is this some sort of misconfiguration on my end where I'm missing something obvious as the docs are very minimal in terms of GOTCHAs? Or is there some sort of limitation/restriction I'm not aware of that causes this behavior? I've provided the url so you can see it, it's enough to run npm install and npm run build and open up `dist/client.css`
