### DISCUSSION TITLE
Theme -> Extend -> Fallback: not working on negative margin

### DISCUSSION THREAD

**Discussion by ionurboz** [tailwindlabs/tailwindcss#14563] [Help]
I have this variable:
```css
--space-container: clamp(1rem, 3vw, 3rem);
```

I have also extended "padding" and "margin" spacings via name of "container" below.

```mjs
export default {
      padding: {
        container: ["1rem", "var(--space-container)"]
      },
      margin: {
        container: ["1rem", "var(--space-container)"]
      },
}
```

I have add "1rem" fallback if browser doesn't support `clamp` feature. In this case, "p-container" and "m-container" works well,

```css
.pr-container {
    padding-right: 1rem;
    padding-right: var(--space-container);
}
.ml-container {
    margin-left: 1rem;
    margin-left: var(--space-container);
}
```

but negative margin be confused while making css;

```css
.-ml-container {
    margin-left: calc(1rem, var(--space-container)* -1);
}
```

expected behavior:

```css
.-ml-container {
    margin-left: -1rem;
    margin-left: calc(var(--space-container)* -1);
}
```

Do I have a problem?
