### DISCUSSION TITLE
[v4] theme colors mode via css classes

### DISCUSSION THREAD

**Discussion by khinshankhan** [tailwindlabs/tailwindcss#14619] [Help]
Heya, I know the blog post mentioned

> Support for other dark modes — right now we only support dark mode using media queries, and still need to reimplement the selector and variant strategies.

however, I tend to prefer using classes and rarely use inline `dark:`. I got the following to work:

```css
@import "tailwindcss";

@theme {
  --color-*: initial;
  --color-background: #000; /* this lets tailwind reference the variable */
}

:root,
.light {
  --color-background: #f0f; /* this sets the variable for light mode */
}

.dark {
  --color-background: #0ff; /* this sets the variable for dark mode */
}

.orange {
  --color-background: #f90; /* this sets the variable for orange mode */
}
```

I think it should be simple enough to refactor if need be but I was wondering if this may break any future plans.
