### DISCUSSION TITLE
`@apply` inheritance, is this expected?

### DISCUSSION THREAD

**Discussion by phegman** [tailwindlabs/tailwindcss#14641] [Help] [answered]
I am seeing some inheritance with `@apply` that I would not expect. See https://play.tailwindcss.com/YgpNNlFOFi?file=css for an example. In that example I wouldn't expect "Nested foo bar" to be green but it is. Is this expected?

Here is the input and output of the example

### Input

```css
.foobar {
  @apply truncate;
}

.nested .truncate {
  color: green;
}
```

### Output

```css
.truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.foobar {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.nested .foobar {
  color: green;
}
.nested .truncate {
  color: green;
}
```
