### DISCUSSION TITLE
[v4] Theme specific corePlugin

### DISCUSSION THREAD

**Discussion by rj-elias** [tailwindlabs/tailwindcss#14817] [Help]
In v3, you can do

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    backgroundColor: {
      brand: colors.blue[600]
    },
    borderColor: {
      brand: colors.blue[300]
    }
  }
}
```

Is it possible to do the same in v4?

```css
@ theme {
    --color-*: initial; /* works for all colors */
    --color-brand: blue; /* works to set 'blue' to 'brand' */
    --background-color-*: initial; /* doesn't seem to work */
    --background-color-brand: blue; /* doesn't seem to work */
    --border-color-brand: lightblue; /* doesn't seem to work */
}
```
