### DISCUSSION TITLE
[v4] color-mix utilities

### DISCUSSION THREAD

**Discussion by stefanprobst** [tailwindlabs/tailwindcss#14827] [Ideas]
usecase: i would love to have an easy way with tailwind to add a semitransparent overlay to an element (which has a solid background color) on hover/press/etc interactions.

something like:

```html
<button class="bg-sky-600 hover:mix-black/10">Click me</button>
```

currently i am adding an `::after` pseudo-element, but since tailwind v4 has added support for css `color-mix()` i was wondering if the team has any plans to add dedicated color-mix utilities, which would make usecases like the above a bit easier?

thanks!

**Comment by emmnull** [comment]
This feature would be great, however maybe the syntax would need to account for a few things:

- It should explicitly target specific properties since the concept doesn't only apply to backgrounds
- It should maybe support [percentage values](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix#percentage) for both colors (`p1` and `p2`)
- It should avoid confusion with the alpha modifier syntax

For example, what would happen in this case:

```html
<!-- is the mix applied to bg or to text color ? -->
<button class="bg-sky-600 text-slate-50 hover:mix-black/10">Click me</button>
```

Or, with an alternate syntax:

```html
<!-- Are the color modifiers used as alpha values or mix percentages ? -->
<button class="bg-sky-600 text-slate-50 hover:bg-sky-600/75-mix-black/10">Click me</button>
```

**Reply by thesmartwon** [reply]
> is the mix applied to bg or to text color ?

I proposed a syntax below that addresses what the mix is applied to via a prefix (i.e. `bg-mix-black` instead of `mix-black`).

> Are the color modifiers used as alpha values or mix percentages ?

I think the `-600` syntax should use alpha values and the `/10` syntax should use percentages. This matches how v4 works today. Examples:
```html
<a class="bg-sky-600/10 bg-mix-slate-100/75">Click me</button>
```
```css
background-color: color-mix(in srgb, var(--color-sky-600) 10%, var(--color-slate-100) 75%);
```
and
```html
<a class="bg-sky/20 bg-mix-slate/75">Click me</button>
```
```css
background-color: color-mix(in srgb, var(--color-sky) 20%, var(--color-slate) 75%);
```

**Comment by thesmartwon** [comment]
The color-mix plugin in #13085 is broken in v4 because it can no longer capture `bg-*` tags to add a CSS variable for later use in `background-color`.

I briefly tried working around the issue, but sadly found that default plugins cannot be extended or overriden. As far as I can tell, creating functional plugins like `bg-*` is not currently possible.

As such, I think there should be a native syntax for colors like this:
```html
<a class="bg-mix-in/srgb bg-sky/10 bg-mix-white/30">asdf</a>
```

```css
background-color: color-mix(in srgb, var(--color-sky) 10%, var(--color-white) 30%);
```

The default color space should match the default used elsewhere. [The syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix#syntax) allows for any values as the percentages of the 2 colors. That means this minimal example is also valid:
```html
<a class="bg-sky bg-mix-white">asdf</a>
```

```css
background-color: color-mix(in oklab, var(--color-sky), var(--color-white));
```

Would a PR for this be welcome?

Related: #14712

**Comment by seancheung** [comment]
You could achive with `@utility` + `--modifier`

```css
@utility text-tint-* {
  color: color-mix(in srgb, --value(--color-*, [*]), white calc(--modifier(integer) * 1%));
}

@utility text-shade-* {
  color: color-mix(in srgb, --value(--color-*, [*]), black calc(--modifier(integer) * 1%));
}

@utility bg-tint-* {
  background-color: color-mix(
    in srgb,
    --value(--color-*, [*]),
    white calc(--modifier(integer) * 1%)
  );
}

@utility bg-shade-* {
  background-color: color-mix(
    in srgb,
    --value(--color-*, [*]),
    black calc(--modifier(integer) * 1%)
  );
}

@utility border-tint-* {
  border-color: color-mix(in srgb, --value(--color-*, [*]), white calc(--modifier(integer) * 1%));
}

@utility border-shade-* {
  border-color: color-mix(in srgb, --value(--color-*, [*]), black calc(--modifier(integer) * 1%));
}
```

And use them like:

```html
<a class="text-tint-base-content/10  bg-shade-[#000]/50 border-tint-primary/5">Click me</button>
```
![image](https://github.com/user-attachments/assets/fd2a1ec1-1edb-4f62-b787-be8a005c35f8)
