### DISCUSSION TITLE
Invalid css selector generated

### DISCUSSION THREAD

**Discussion by kdy1** [tailwindlabs/tailwindcss#14901] [Help]
**What version of Tailwind CSS are you using?**

v3.4.14

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js + turbopack, but reproducible on playground.

**What version of Node.js are you using?**

Playground

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/obgZakKyiO?file=css

**Describe your issue**

Generated CSS file is 

```css

p.my-4 {
  margin: 0px;
}
.\[\&_\:is\(p\)\]\:my-4 :is(p)p {
  margin: 0px;
}

```

where `:is(p)p` is invalid
