### DISCUSSION TITLE
Scoped colors in v4

### DISCUSSION THREAD

**Discussion by thefrana** [tailwindlabs/tailwindcss#14968] [Help] [answered]
Hi,
in v3, I could have following config:

```ts
export default {
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
    },
    backgroundColor: {
      primary: "var(--color-bg-primary)",
    },
    textColor: {
      primary: "var(--color-text-primary)",
    },
  },
}
```

Is there equivalent in v4? I tried `--color-bg-primary`, but it does not work.

Thanks

EDIT: I need `class="bg-primary"` to be different than `class="text-primary"`

**Comment by wongjn** [comment, marked as answer]
You can do:

```css
@import "tailwindcss";

@theme {
  --text-color-primary: red;
  --background-color-primary: blue;
}
```

https://play.tailwindcss.com/KO3RwOhlLC?file=css
