### DISCUSSION TITLE
[v4] Improve the usage of CSS variables for dark/light mode

### DISCUSSION THREAD

**Discussion by IonianPlayboy** [tailwindlabs/tailwindcss#15083] [Ideas]
Hello everyone, congratulations to the team for the launch of the v4 beta ! It's very exciting, and it looks amazing.

I have started playing with the new version with the 100% CSS config, and the only thing that did not convince so far is setting up dark/light mode colors with CSS variables.

>[!NOTE]
> I am only talking about dark/light mode to keep this simple, but this could apply to any number of theme configured in your main CSS file.

# The problem

## `dark` variant usage

It's very easy to declare a custom `dark` variant to customize dark mode detection, as showed in [the beta docs](https://tailwindcss.com/docs/v4-beta#configuring-dark-mode) :

```css
@variant dark (&:where(.dark, .dark *)); /* <body class="dark"> */ 
@variant dark (&:where([data-theme="dark"], [data-theme="dark"] *); /* <body data-theme="dark"> */ 
``` 

You can then use the `dark` variant anywhere in your app, and it will work just fine. 

Even if at some point you need to change your dark mode detection strategy, or you create a lib that is consumed by other projects with a different dark mode logic, you just need to update/set one line of CSS to have all your app updated.

## CSS variables usage

This is sadly not the case if you are working with CSS variables, instead of relying on the `dark` variant.

Your config would most likely look like something like this (see #14091 & #14095) : 

```css
:root {
  --text-fg: #000; 

  :where(.dark) {
    --text-fg: #fff;
  }
}

/* `inline` is necessary to make it work */
@theme inline {
  --color-fg: var(--text-fg);
}
``` 

On a local/personal project, this will work exactly like using the `dark` variant, and it is still pretty easy to change the detection logic by updating only one line of CSS.

However, this is much more problematic if you are publishing a lib. Your users can't override your dark mode detection logic without rewriting all the dark mode values themselves or with a hacky way to change the css file you provide.

# Compared to v3

If I am being 100% honest, working with CSS variables in dark mode was not that much easier in v3. The main difference I see is that since v3 is based on a JS config file, libraries would most of the time read the `darkMode`config option to generate their colors in a way that would be compatible with the user's dark mode detection. 

Since in v4 the JS config is optional, it is not a reliable technique anymore, and I don't see an alternative solution to solve this issue without forcing libraries to create their own, self-maintained custom config in JS to handle this.

# Proposed solution

In my opinion, this is a pain point that is going to be encountered by a lot of users, since CSS variables for dark/light mode are very common when using design systems with design tokens. I find it worthwhile to improve the UX out of the box for this setup, and I believe that you should be able to stay 100% in your main CSS file to configure your dark mode to stay in the spirit of v4.

A potential solution could look like this : 

```css
/* Step 1: define your `dark` mode variant */
@variant dark (&:where(.dark, .dark *)); 

/* Step 2: define your color values, independently from the detection logic */
@variations {
  --text-fg: #000; /* this would be the default value */

  @dark {
    --text-fg: #fff; /* this would be the value when the dark mode variant selector matches the element */
  }
}

/* Step 3: define your theme colors as usual */
@theme inline {
  --color-fg: var(--text-fg);
}
``` 

This would compile to the same CSS as the example above, but the mode detection should be overridable by users of the lib by simply overriding the `dark` mode variant definition in their own CSS.

Now obviously this is most likely not the best syntax possible, but I think that the mental model of separating your color definitions from the theme/mode detection is sound.

**Comment by minht11** [comment]
If you are supporting only relative newish browsers you can use [light-dark](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) css function. 
```css
--color-primary: light-dark(red, magenta);
```
and the only thing you need to change is `color-scheme` for colors to change. I am prototyping with this and this cleaned up a lot of code.

**Reply by IonianPlayboy** [reply]
That's definitely a nicer way to work with CSS variables. If you are starting a new project in V4 where you have full ownership on the theme management, I think that's the best approach. Do you have any codebases where you mix this approach with the `dark`variant ? I wonder how easy it would be to make them coexist in the same project.

I would love an alternative baked into Tailwind to support other dark mode detection strategies, and to let librairies detect the user's config. Otherwise you would be out of luck if you are using [light-dark](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) everywhere but your component library is expecting a `.dark`class or a data attribute to toggle the dark/light mode. It sadly does not help if you want to support more than one theme too.

**Reply by rozsazoltan** [reply]
Related:
* [How can I safely introduce the use of `light-dark()` without increasing the minimum browser version requirement?](https://stackoverflow.com/a/79739830/15167500)

Required minimum browser versions:

|Tailwind CSS v4 (without `light-dark()`)|with `light-dark()`||with `var(--tw-light, ...) var(--tw-dark, ...)`||
|---|---|---|---|---|
|Chrome 111|Chrome 123|(+)|Chrome 111|(=)|
|Safari 16.4|Safari 17.5|(+)|Safari 16.4|(=)|
|Firefox 128|Firefox 128|(=)|Firefox 128|(=)|

* https://caniuse.com/usage-table

**Comment by shavonn** [comment]
I was also curious about this support since you could set the dark color in the tailwind config file in 3. What I ended up doing that has worked in v4 is this:

```
@theme {
  --text-color: var(--color-zinc-950);
}
@layer base {
    .dark {
       --text-color: var(--color-white);
    }
}
```

I'm new to using Tailwind's more advanced features, so I don't know how it _should_ be done, but this did work for me.

**Reply by pdas9647** [reply]
Hey Shavonn, could you please help me? How are you using the text-color in the HTML elements?
Are you using "**dark:...**" or it is automatically adjusted?

**Comment by 0x2f0** [comment]
I don't know what is wrong but registering a `custom-variant` for `dark` class is not working.
Even the example shown in the docs is not working for custom dark mode selection.

Here is what i tired reading docs.
https://play.tailwindcss.com/NKoulCfDGM

Is there something wrong with the above implementation or there is some bug regarding this feature.

**Reply by gaojunran** [reply]
write `@variant` instead of `@custom-variant` works. And I don't know why, but should be fixed or clarified in the document.

**Reply by maiconcarraro** [reply]
@gaojunran still the same, not working 
![image](https://github.com/user-attachments/assets/f36a7152-a6bf-4df6-b602-87de05b870b8)

**Reply by wongjn** [reply]
Tailwind Play strips `<html>` and `<body>` elements. Changing it to a `<div>` works: https://play.tailwindcss.com/7XspA9mJzw

**Reply by 0x2f0** [reply]
thank you @wongjn  for pointing that out. Around 1-2 weeks earlier it was not working properly. I tried it locally as well.
It appears that it has been fixed  and is working properly.
https://play.tailwindcss.com/qF3sOqlkjn?file=css

Now a little more complex selection with system theme support and custom override with class are working perfectly.
And  both `@custom-variant` and `@variant` appears to be working fine.

**Comment by joshuabaker** [comment]
The [`light-dark()` CSS function](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) is a nice option.

Alternatively, we can just make use of [bracket variable syntax](https://tailwindcss.com/docs/color#using-a-custom-value:~:text=For-,CSS%20variables,-%2C%20you%20can%20also).

```css
@layer base {
  :root {
    --background: var(--color-stone-100);
    --foreground: var(--color-stone-800);
    @variant dark {
    --background: var(--color-stone-900);
    --foreground: var(--color-stone-200);
    }
  }
}
```

```html
<div class="bg-(--background) text-(--foreground)">
  …
</div>
```

Playground: https://play.tailwindcss.com/IlolEC84Tm

I’d hoped that we could’ve just used `@variant dark` within `@theme`/`@theme inline`.

**Reply by TheoryOfNekomata** [reply]
Unfortunately the `light-dark()` function would only work when `color-scheme` is set to `light dark`.

Would have been nice if Tailwind tried to "hijack" `light-dark()` to creating its own variables. It wouldn't be confusing if the `color-*` theme variables had a special way of being resolved in CSS.

Something like

```css
@theme {
  --color-background: light-dark(white, black);
  --color-foreground: light-dark(black, white);
}
```

would have compiled to

```css
:root {
  --color-background--light: white;
  --color-background--dark: black;
  --color-foreground--light: black;
  --color-foreground--dark: white;
}

/* assuming "light" is the default variant */
:root {
  --color-background: var(--color-background--light);
  --color-foreground: var(--color-foreground--light);
}

@media (prefers-color-scheme: dark) {
  :root {
    --color-background: var(--color-background--dark);
    --color-foreground: var(--color-foreground--dark);
  }
}
```

Of course this could have been extensible to other variants than `light` or `dark`, but the `light-dark()` function is a way to define different colors for those 2 variants.

**Reply by rozsazoltan** [reply]
Related:
* [How can I safely introduce the use of `light-dark()` without increasing the minimum browser version requirement?](https://stackoverflow.com/a/79739830/15167500)

Required minimum browser versions:

|Tailwind CSS v4 (without `light-dark()`)|with `light-dark()`||with `var(--tw-light, ...) var(--tw-dark, ...)`||
|---|---|---|---|---|
|Chrome 111|Chrome 123|(+)|Chrome 111|(=)|
|Safari 16.4|Safari 17.5|(+)|Safari 16.4|(=)|
|Firefox 128|Firefox 128|(=)|Firefox 128|(=)|

* https://caniuse.com/usage-table

**Comment by kwiat1990** [comment]
For some reason using this approach:
```css
:root {
  --text-fg: #000; 

  :where(.dark) {
    --text-fg: #fff;
  }
}

/* `inline` is necessary to make it work */
@theme inline {
  --color-fg: var(--text-fg);
}
```
a value of the `text-fg` variable stays unchanged although the `.dark` class was added/removed. I ended up doing something like this but I would rather say it’s neither clean nor intuitive:
```css
@import "tailwindcss";

@custom-variant dark (&:where(.dark, .dark *));

@layer base {
    :root {
        --current-mode: var(--color-black);

        @variant dark {
            --current-mode: var(--color-white);
        }
    }
}

@theme inline {
    --color-current-mode: var(--current-mode);
}

@theme {
    --shadow: 2px 2px 0 0 var(--color-current-mode); /* I wanted to have a color, which changes depending on current color theme */
}
```

**Reply by naymurdev** [reply]
thanks @kwiat1990 
 it works for me 🎉

**Comment by viktorHadz** [comment]
Hey guys and gal! Absolute newbie here so please take with a huge grain of salt. But this is how I solve the problem:

```css
@import 'tailwindcss';
@custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));
@custom-variant light (&:where([data-theme=light], [data-theme=light] *));

/*For example*/
[data-theme='light'] {
  --color-primary: oklch(100% 0 0);
  --color-sec: oklch(0.31 0.1637 263.98);
  --color-sec-mute: oklch(0.33 0.1637 263.98);
  --color-acc: oklch(0.74 0.1373 42.52);
}

[data-theme='dark'] {
  --color-primary: oklch(23.93% 0 0);
  --color-sec: oklch(0.205 0 0);
  --color-sec-mute: oklch(0.22 0 0);
  --color-acc: oklch(0.74 0.1373 42.52);
}

@theme {
  --color-primary: var(--color-primary);
  --color-sec: var(--color-sec);
  --color-sec-mute: var(--color-sec-mute);
  --color-acc: var(--color-acc);
}
```

I then on click change the `data-theme` to `light` or `dark`.  
**I use Vue so this may not be relevant to you. But in case it is, this is how I do it:**

```vue
<script setup>
import { SunIcon, MoonIcon } from '@heroicons/vue/24/outline'
import { useColorMode } from '@vueuse/core'

const mode = useColorMode({
  attribute: 'data-theme',
  modes: {
    light: 'light',
    dark: 'dark',
  },
  disableTransition: false,
})

const toggleMode = () => {
  mode.value = mode.value === 'dark' ? 'light' : 'dark'
}
</script>

<template>
  <button @click="toggleMode" class="cursor-pointer">
    <transition name="rotate-element" mode="out-in">
      <div :key="mode" class="icon-wrapper">
        <component :is="mode === 'dark' ? SunIcon : MoonIcon" class="w-8 h-8 stroke-1" />
      </div>
    </transition>
  </button>
</template>
```
Anyways hope this helps.

**Comment by mkaradeniz** [comment]
I was using this approach:

`theme.css`
```css
@import './theme.dark.css' layer(theme);

@custom-variant dark (&:where(.dark, .dark *));

@theme {
  --color-primary: oklch(62.796% 0.25768 29.23494);
}
```

`theme.dark.css`
```css
.dark {
  --color-primary: oklch(16.991% 0.06084 257.21786);
}
```

This works perfectly for `--color-*` theme variables. When I switch between dark & light mode (via setting the `dark` class on `<html />`. But it does not work for box-shadows.



`theme.css`
```css
@import './theme.dark.css' layer(theme);

@custom-variant dark (&:where(.dark, .dark *));

@theme {
  --color-primary: oklch(62.796% 0.25768 29.23494);
  --shadow-base: 4px 2px 2px 20px oklch(68.127% 0.117 191.87655);
}
```

`theme.dark.css`
```css
.dark {
  --color-primary: oklch(16.991% 0.06084 257.21786);
  --shadow-base: 36px 28px 8px 36px oklch(67.401% 0.20941 20.7674);
}
```

It seems this approach is not actually supported? I'm not sure why it does work for colors though.

**Reply by serhiybondarenkogithub** [reply]
Maybe this could be some solution
```css
@custom-variant dark (&:where(.dark, .dark *));

@theme {  
  --spacing-layout: 1280px;
  --font-sans: "Inter", "sans-serif"; 
  --color-bg: #f6f9fb;
  --color-common: #ffffff;
  --color-shadow: #ecf1f440;
  --shadow-box: 1px 2px 7.2px 0px var(--color-shadow);
}

@layer base {
  @variant dark {
    --color-common: #05080b;
    --color-bg: #000000;
    --color-shadow: #0b111340;
  }
}
```
