### DISCUSSION TITLE
Disable core (default) colors in v4

### DISCUSSION THREAD

**Discussion by krstivoja** [tailwindlabs/tailwindcss#15095] [Help] [answered]
Is it possible to disable default colors, as I want to add custom ones?

I do not want to have all the colors in the autocomplete. Only the brand specific.

**Comment by wongjn** [comment, marked as answer]
Yep! As per [the documentation](https://tailwindcss.com/docs/v4-beta#overriding-the-default-theme):

> To override an entire namespace, unset the namespace using syntax like `--font-*: initial`:
>
> ```css
> @import "tailwindcss";
> 
> @theme {
>   --font-*: initial;
>   --font-display: "Satoshi", "sans-serif";
> }
> ```

So following this, colors use the `color` namespace, so you'd do:

```css
@import "tailwindcss";

@theme {
  --color-*: initial;
  --color-brand-primary: …;
}
```
