### DISCUSSION TITLE
[v4] Custom variables in `@theme` directive not work as expected

### DISCUSSION THREAD

**Discussion by lkwr** [tailwindlabs/tailwindcss#15122] [Help] [answered]
Hi,

How can I use CSS variables defined in a data-* selector in the `@theme` directive?
I expected this example to work, but unfortunately it does not.

CSS:
```css
@import "tailwindcss";

[data-theme="dark"] {
  --theme-color-background: red;
  --theme-color-foreground: blue;
}

[data-theme="light"] {
  --theme-color-background: blue;
  --theme-color-foreground: red;
}

@theme {
  --color-background: var(--theme-color-background);
  --color-foreground: var(--theme-color-foreground);
}
```

HTML:
```html
<div>
  <div data-theme="dark">
    <p class="bg-background p-4 text-foreground">Text</p>
  </div>
  <div data-theme="light">
    <p class="bg-background p-4 text-foreground">Text</p>
  </div>
</div>
```

[(playground link)](https://play.tailwindcss.com/xyVIdj652B)

I want to be able to change the theme based on the data attribute on every element on the html. With tailwind v3 everything works fine by using css variables in the `tailwind.config.ts`

**Comment by wongjn** [comment, marked as answer]
You'd want to use the `inline` tag with `@theme`: https://play.tailwindcss.com/nSlymBjv3E?file=css

This changes the CSS rules from:

```css
.bg-background {
  background-color: var(--color-background);
}
```

To:

```css
.bg-background {
  background-color: var(--theme-color-background);
}
```

Allowing your CSS variables to be resolved correctly.

**Reply by lkwr** [reply]
Thank you so much! 👍🏼🚀

**Comment by kelvin2200** [comment]
@wongjn What does the inline keyword do, and why does it solve the problem above?

**Reply by wongjn** [reply]
See https://github.com/tailwindlabs/tailwindcss/pull/14095 for details on the `inline` option.

## How it fixes the problem

### Without `inline`:

Tailwind compiles to something like:

```css
:root {
  …
  --color-background: var(--theme-color-background);
}

[data-theme="dark"] {
  --theme-color-background: red;
  --theme-color-foreground: blue;
}

[data-theme="light"] {
  --theme-color-background: blue;
  --theme-color-foreground: red;
}

@layer utilities {
  .bg-background {
    background-color: var(--color-background);
  }
}
```
With the following HTML:

```html
<html>
  <head>…</head>
  <body>
    <div>
      <div data-theme="dark">
        <p class="bg-background p-4 text-foreground">Text</p>
      </div>
      <div data-theme="light">
        <p class="bg-background p-4 text-foreground">Text</p>
      </div>
    </div>
  </body>
</html>
```
So if we look at the `background-color` resolution steps for `bg-background`:

1. `var(--color-background)` means look for a definition of `--color-background` on itself or DOM parents.
2. The browser finds it at `<html>` (from the `:root` rule).
3. `--color-background` has value of `var(--theme-color-background)`. The browser again, looks for a definition of `--theme-color-background` on itself or DOM parents.
4. No definition is found. Invalid (?) value, so discard (?) or use default.

### With `inline`:

```css
:root {
  …
  --color-background: var(--theme-color-background);
}

[data-theme="dark"] {
  --theme-color-background: red;
  --theme-color-foreground: blue;
}

[data-theme="light"] {
  --theme-color-background: blue;
  --theme-color-foreground: red;
}

@layer utilities {
  .bg-background {
    background-color: var(--theme-color-background);
  }
}
```

(Same HTML)

The resolution steps for `bg-background` become:

1. `var(--theme-color-background)` means look for a definition of `--theme-color-background` on itself or DOM parents.
2. The browser finds it at `<div data-theme="dark">` or `<div data-theme="light">` from our custom CSS rules.
3. `--theme-color-background` has valid `<color>` value of `red` or `blue` respectively.
4. Browser uses the `<color>` value for `background-color`.

## Comparison

| Without `inline` | With `inline` |
| --- | --- |
| `background-color: var(--color-background)` | `background-color: var(--theme-color-background)` |
| Looks for `--color-background` definition | Looks for `--theme-color-background` definition |
| Finds definition at `:root` | Finds definition at `[data-theme="dark"]` or `[data-theme="light"]` |
| Resolves to `var(--theme-color-background)` | Resolves to `red` or `blue` |
| Looks for `--theme-color-background` definition  | |
| Not found, invalid value | |
