### DISCUSSION TITLE
[v4] VSCode extension not working when using only @theme directive

### DISCUSSION THREAD

**Discussion by kelvin2200** [tailwindlabs/tailwindcss#15132] [Help]
How is the VSCode extension supposed to provide autocomplete in v4 given there's no more tailwind.config file.
The extension no longer works if I delete the `tailwind.config.ts` file.
I want to use the css only theme config, but now I'm supposed to have the same config duplicated in the config file.
I know I can import the config in the css file, but then again how does one test the new `@theme` directive?
Tailwind is 50% unusable without the autocomplete

**Comment by kylekz** [comment]
it's meant to automatically discover tailwind-related .css files, but if you're like me and split your config up into multiple files with multiple `@layer base` statements, then you might need to explicitly disambiguate the config. add this to `.vscode/settings.json`

```json
{
  "tailwindCSS.experimental.configFile": "./path/to/your/tailwind/entrypoint.css",
}
```

**Reply by AqibTG** [reply]
This worked for me  
"@tailwindcss/vite": "^4.0.0",
 "react": "^18.3.1",
"react-dom": "^18.3.1",
 "tailwindcss": "^4.0.0"

**Reply by emirefek** [reply]
thanks this make it work.

**Reply by xDivisionByZerox** [reply]
I can confirm that this works for angular 19 projects as well:


```
{
  "dependencies": {
    [...]
    "@angular/core": "^19.1.0",
    [...]
  },
  "devDependencies": {
    [...]
    "@tailwindcss/postcss": "^4.0.12",
    "postcss": "^8.5.3",
    "tailwindcss": "^4.0.12"
  }
}
```

**Reply by qingzhoufeihu** [reply]
it does not work

**Reply by bravo680git** [reply]
Great, It works for me
```
{
  "tailwindCSS.experimental.configFile": "src/style.css"
}
```

**Reply by jeromflo** [reply]
> it's meant to automatically discover tailwind-related .css files, but if you're like me and split your config up into multiple files with multiple `@layer base` statements, then you might need to explicitly disambiguate the config. add this to `.vscode/settings.json`
> 
> ```json
> {
>   "tailwindCSS.experimental.configFile": "./path/to/your/tailwind/entrypoint.css",
> }
> ```

It´s works for me too. I am working on angular 19.

**Comment by kelvin2200** [comment]
@kylekz thank you for the reply, but I still can't get the intellisense to work without a `tailwind.config` file.
this is what I have in Tailwind CSS Intellisense OUTPUT
```bash
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"","config":"/app/src/index.css","selectors":[{"priority":0,"pattern":"/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config-as-project","relative-content-paths","transpiled-configs"],"isDefaultVersion":true}}]
[Global] Preparing projects...
[Global] Adding watch patterns: /app/src/index.css, /app/src, /app, , /app/src/css/roboto.css, /app/src/css
[Global] Initializing projects...
[app/src/index.css] Initializing...
[app/src/index.css] supported features: ["css-at-theme","layer:base","content-list"]
[Error - 00:20:43] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/.yarn/cache/tailwindcss-npm-4.0.0-beta.2-2417a383bd-520432cd07.zip/node_modules/tailwindcss/dist/lib.js' imported from .vscode/extensions/bradlc.vscode-tailwindcss-0.13.59/dist/tailwindServer.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:940:10)
    at defaultResolve (node:internal/modules/esm/resolve:1176:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:472:34)
    at defaultImportModuleDynamicallyForScript (node:internal/modules/esm/utils:227:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:249:12)
    at I (.vscode/extensions/bradlc.vscode-tailwindcss-0.13.59/dist/tailwindServer.js:1762:11505) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///.yarn/cache/tailwindcss-npm-4.0.0-beta.2-2417a383bd-520432cd07.zip/node_modules/tailwindcss/dist/lib.js'
}
[app/src/index.css] Failed to load workspace modules.
[app/src/index.css] Using bundled version of `tailwindcss`: v3.4.4
[app/src/index.css] Using bundled version of `postcss`: v8.4.31
[app/src/index.css] Building...
[Error - 00:20:43] Tailwind CSS: Invalid or unexpected token
/app/src/index.css:1
@import "tailwindcss";
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1385:20)
    at Module._compile (node:internal/modules/cjs/loader:1435:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at require$$0.Module._extensions..js (/.pnp.cjs:10563:33)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at require$$0.Module._load (/.pnp.cjs:10411:31)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at If._require.Tc.default.require (.vscode/extensions/bradlc.vscode-tailwindcss-0.13.59/dist/tailwindServer.js:1696:1543)
[Global] Initialized 1 projects
```

I run a Yarn PNP monorepo on a MacBook.
Changing the `"tailwindCSS.experimental.configFile"` seems to do something, but not nearly what is expected.
1. the extension seems to be using "version":"3.4.4"
2. seems it does try to load the 4.0.0 beta version from the zip, but it can't

UNPLUGGING tailwindcss seems to tell the extension to load the beta version, but autocomplete still doesn't work
```bash
----------
RESTARTING
----------
[Info  - 00:29:41] [GLOBAL] No matching project for document {
  fsPath: '/new-dealer-tool/app/src/index.css',
  normalPath: '/new-dealer-tool/app/src/index.css'
}
[Error - 00:29:41] (node:6864) Warning: [Warning] The runtime detected new information in a PnP file; reloading the API instance (/new-dealer-tool/.pnp.cjs)
(Use `Code Helper (Plugin) --trace-warnings ...` to show where the warning was created)
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"/new-dealer-tool","config":"/new-dealer-tool/app/src/index.css","selectors":[{"priority":0,"pattern":"/new-dealer-tool/**"}],"user":true,"tailwind":{"version":"4.0.0-beta.2","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Adding watch patterns: /new-dealer-tool/app/src/index.css, /new-dealer-tool/app/src, /new-dealer-tool/app, /new-dealer-tool, /new-dealer-tool/app/src/css/roboto.css, /new-dealer-tool/app/src/css
[Global] Initializing projects...
[app/src/index.css] Initializing...
[app/src/index.css] supported features: ["css-at-theme","layer:base","content-list"]
[app/src/index.css] Loaded tailwindcss v4.0.0-beta.2: /new-dealer-tool/.yarn/unplugged/tailwindcss-npm-4.0.0-beta.2-2417a383bd/node_modules/tailwindcss
[app/src/index.css] Building...
[Global] Initialized 1 projects
[app/src/index.css] Initializing...
[app/src/index.css] supported features: ["css-at-theme","layer:base","content-list"]
[app/src/index.css] Loaded tailwindcss v4.0.0-beta.2: /new-dealer-tool/.yarn/unplugged/tailwindcss-npm-4.0.0-beta.2-2417a383bd/node_modules/tailwindcss
[app/src/index.css] Building...
```

Tried with both extension versions (release and pre-release)

**Reply by cuquo** [reply]
I fixed it by putting in the css file where the tailwind config file it was

**Reply by kelvin2200** [reply]
That's technically not a fix... as long as there's a `tailwind.config` file, the intellisense works.
But it kinda defeats the purpose of having a css-only config.
The point is, we're using code-generation for some utilities, spacing, different measurements, effects etc...
and we want to remove those in favor of css, but we can't.

I get that it's a beta, but it's unusable atm. We're only gonna be releasing in a few months, but there are 6 teams working on our project and the dev-ex needs to exist. We're gonna stick to v3 ti'll this gets sorted out.

This would have been a good moment to migrate though... I'm very sad we can't

**Reply by cuquo** [reply]
not always (tailwind.config), specially in a monorepo, if you debug the extension you'll notice that it looks for certain patterns for css files when it starts, ergo why just putting a root css targeting the main css (in another package) works as a fix at least in a monorepo setup.

**Reply by kelvin2200** [reply]
Either you got some specific setup/extension/IDE that makes your intellisense work like that, or we're not talking about the same thing. The extension does work, it finds the root css, it can see the config, compilation works etc, but the intellisense doesn't.

**Reply by codersaadi** [reply]
@kelvin2200 
have you found a solution without tailwind.config?
why would we want to have a config file for only intellisense, that's really annoying and defeats the purpose of single source of truth , initially tailwind was built on that , that there will be a config file as the single source of truth, but then they realized that it should not be different than the css file(nice work) but now it has been stable and still we got problems with the intellisense . 
extension. 
is it working with this 
in monorepo 
`  "tailwindCSS.experimental.configFile": "packages/design-system/styles/globals.css",
`

**Comment by debarup24** [comment]
Yes, in V4 of Taiwind CSS ,  the autocompletion is not working as there is no tailwind.config file in the V4. 

if you want the autocompletion or class suggestions in V4 , you have to create tailwind.config file in the root and perform the old step as V3.4.17 
paste this in  tailwind.config  :  and then intellisense will start working 
   _```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```_

**Reply by yeasin2002** [reply]
so, If I use anything new in my /css @theme, How would I get that suggetions?

**Reply by gustavo-alberto** [reply]
worked for me! I'm using Vite React Typescript and had to set this configurations on files.

```
my-app/
├─ node_modules/
├─ public/
├─ src/
│  ├─ index.css
├─ tailwind.config.ts //create this file manually
├─ vite.config.ts

```

# vite.config.ts
``` typescript
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
})
```

# tailwind.config.ts
``` typescript
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
}

```

# index.css
```
@import 'tailwindcss';

```

After this, Tailwind CSS IntelliSense VSCode extension worked with Tailwind V4.

**Comment by asplunds** [comment]
The extension stopped working for us after the extension updated to 1.14.12. After downgrading to 1.14.11 it inexplicably started working again. The output tab didn't say anything useful. For context we're using a monorepo, tailwind 4, no tailwind.config.js/ts needed in the project. We also use Cursor.

Hopefully this helps someone struggling to find the issue.

**Reply by mahdi739** [reply]
I just ran into the same issue. It was working in version 0.14.11 without a `tailwind.config.js` file. After updating to 0.14.12, it now needs that file to activate.
(I added my css file to `tailwindCSS.experimental.configFile`, it still didn't work)

**Reply by mahdi739** [reply]
I think I found the root cause in my case. When I add the DaisyUI plugin locally with `@plugin "./daisyui.js";`, the IntelliSense doesn't work anymore. I use the standalone Tailwind CSS CLI and don't have Node.js or npm installed, so I added DaisyUI as a local plugin. The VS Code extension works correctly without that line, so I assume my configurations are correct. The Tailwind CLI generates the correct output, but the VS Code extension breaks when the plugin is included.

**Comment by kirmola** [comment]
I can confirm :   "tailwindCSS.experimental.configFile" setting works, just provide a valid entrypoint css file and its good to go.

**Comment by kylepillay** [comment]
A bit late here. But the easiest option is to update the file associations in your VSCode settings json. Like this.

``` json
  "files.associations": {
      "*.css": "tailwindcss"
  }
```

**Reply by roycevanle** [reply]
12.16.25 reply here, this is the solution that worked for me... Only took 1-2 hours to find... T_T

**Reply by phuongnam-code** [reply]
> A bit late here. But the easiest option is to update the file associations in your VSCode settings json. Like this.
> 
> ```json
>   "files.associations": {
>       "*.css": "tailwindcss"
>   }
> ```

worked, my usecase:
go + htmx + templ + tailwindcss v4 (tailwind cli gen css file)
IDE: vs-code, anti grafity, windsurf ...

**Comment by Apricosma** [comment]
Intellisense inexplicably stopped working when it was working fine all day. Attempted solutions I've done are
- Reinstall tailwindcss extension and prettier extension
- Change tailwindCSS experimental configFile to nextjs css entry point `src/app/globals.css`
- Remove tailwindCSS experimental configFile line
- Adding tailwind config manually
- Adding files.associations as suggested directly above
- Restarting extension server, and vscode after each step

Referenced docs for integration with Next: https://nextjs.org/docs/app/guides/tailwind-css

Absolutely nothing works, and output displays that it's stuck on Building:
```
[src\app\globals.css] Initializing...
[src\app\globals.css] supported features: ["css-at-theme","layer:base","content-list","source-inline","source-not"]
[src\app\globals.css] Loaded tailwindcss v4.1.11: [harddrive path]\node_modules\tailwindcss
[src\app\globals.css] Building...
```

Projects structure looks as follows:
```
my-project
|_ src
   |_ app
     |- globals.css
     |- layout.tsx
     |_ page.tsx
...
next.config.ts
package.json
postcss.config.mjs
```

inside of `postcss.config.mjs` is:
```css
const config = {
  plugins: ["@tailwindcss/postcss"],
};

export default config;
```

`globals.css` contains `@import "tailwindcss";`

`layout.tsx` contains `import "./globals.css";

Any help would be appreciated

**Reply by kylepillay** [reply]
Are you comfortable with sharing the global.css file?

**Reply by kylepillay** [reply]
Before you do that though, have you tried clearing your node_modules folder?

``` bash
rm -rf node_modules package-lock.json
npm install
```

**Reply by kylepillay** [reply]
What version of Node.js are you using? It needs to be 18 or higher.

**Reply by kylepillay** [reply]
Lastly, you can try increase your memory limit.

``` bash
node --max-old-space-size=4096 <Your Build Command Here>
```

**Reply by Apricosma** [reply]
Apologies for the late response. I'm on node v20.11.1, using NEXT 15.3.5.
Reinstalling npm packages didn't fix the issue unfortunately. 
My globals.css is essentially vanilla except for ShadCN colours, but maybe there's a problem somewhere from the shadcn scripts

```css
@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
  --color-sidebar-ring: var(--sidebar-ring);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar: var(--sidebar);
  --color-chart-5: var(--chart-5);
  --color-chart-4: var(--chart-4);
  --color-chart-3: var(--chart-3);
  --color-chart-2: var(--chart-2);
  --color-chart-1: var(--chart-1);
  --color-ring: var(--ring);
  --color-input: var(--input);
  --color-border: var(--border);
  --color-destructive: var(--destructive);
  --color-accent-foreground: var(--accent-foreground);
  --color-accent: var(--accent);
  --color-muted-foreground: var(--muted-foreground);
  --color-muted: var(--muted);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-secondary: var(--secondary);
  --color-primary-foreground: var(--primary-foreground);
  --color-primary: var(--primary);
  --color-popover-foreground: var(--popover-foreground);
  --color-popover: var(--popover);
  --color-card-foreground: var(--card-foreground);
  --color-card: var(--card);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}

:root {
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);
}

.dark {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.205 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.205 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.6996 0.201959 44.4414);
  --primary-foreground: oklch(0.985 0 0);;
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.704 0.191 22.216);
  --border: oklch(1 0 0 / 10%);
  --input: oklch(1 0 0 / 15%);
  --ring: oklch(0.556 0 0);
  --chart-1: oklch(0.488 0.243 264.376);
  --chart-2: oklch(0.696 0.17 162.48);
  --chart-3: oklch(0.769 0.188 70.08);
  --chart-4: oklch(0.627 0.265 303.9);
  --chart-5: oklch(0.645 0.246 16.439);
  --sidebar: oklch(0.205 0 0);
  --sidebar-foreground: oklch(0.985 0 0);
  --sidebar-primary: oklch(0.488 0.243 264.376);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.269 0 0);
  --sidebar-accent-foreground: oklch(0.985 0 0);
  --sidebar-border: oklch(1 0 0 / 10%);
  --sidebar-ring: oklch(0.556 0 0);
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}

```
