### DISCUSSION TITLE
[v4] weird issue with compiled code for spacing

### DISCUSSION THREAD

**Discussion by dev-ctrl480** [tailwindlabs/tailwindcss#15143] [Help] [answered]
Hello everyone, 

I'm facing this weird issue where the spacing utilities are not working and I'm seeing there's a difference between my compiled css code and the code from play.tailwindcss.com

For example:

block from my compiled app-[...].css: 
`.space-x-6 :where(>:not(:last-child)) {
--tw-space-x-reverse: 0;
margin-inline-start:calc(calc(var(--spacing) * 6) * var(--tw-space-x-reverse));
margin-inline-end:calc(calc(var(--spacing) * 6) * calc(1 - var(--tw-space-x-reverse)))
}`

block from play.tailwindcss.com:
`.space-x-6 {
  :where(& > :not(:last-child)) {
    --tw-space-x-reverse: 0;
    margin-inline-start: calc(calc(var(--spacing) * 6) * var(--tw-space-x-reverse));
    margin-inline-end: calc(calc(var(--spacing) * 6) * calc(1 - var(--tw-space-x-reverse)));
  }
}`

I'm using vite v5.4.11 for the build. Any ideas what could be causing this or how to fix it?

Thank you!

**Comment by adamwathan** [comment]
Hey! Mind creating a reproduction? I am not seeing this when I try to test this locally — I get this:

```css
  :where(.space-x-6 > :not(:last-child)) {
    --tw-space-x-reverse: 0;
    margin-inline-start: calc(calc(var(--spacing) * 6) * var(--tw-space-x-reverse));
    margin-inline-end: calc(calc(var(--spacing) * 6) * calc(1 - var(--tw-space-x-reverse)));
  }
```
