### DISCUSSION TITLE
[V4] How to use multiple Presets in monorepo?

### DISCUSSION THREAD

**Discussion by ManasMadrecha** [tailwindlabs/tailwindcss#15161] [Help] [answered]
How to import or enable preset configs in the CSS file in V4?

## Use Case
- Single source of truth for brand colors, etc. 
- Enable requisite plugins in one file, and then use (or disable) such plugins in another repo

Based on this https://github.com/tailwindlabs/tailwindcss/discussions/15119#discussioncomment-11364330, it seems Presets are dead. 😢 Is it so?

## Real world use case

I have a Monorepo with multiple repo present in `src` folder and a "base" Nuxt Module present in `packages` folder. This Nuxt Module needs Tailwind on its own (for its UI components that it will export) as well as needs to enable Tailwind for any repo that uses this module. 

Currently, this is the Nuxt Module's css file:

```css
// packages/base-module/src/runtime/assets/tw.css

@import "tailwindcss" source(none);

@source "../../components";

/* @plugin "@tailwindcss/typography"; */
@plugin "tailwindcss-animate";

@variant dark (&:where(.dark, .dark *));

@theme {
  --font-suse: "SUSE", sans-serif;
  --color-primary-50: var(--color-orange-50);
  --color-primary-100: var(--color-orange-100);
  --color-secondary-50: var(--color-lime-50);
  --color-secondary-100: var(--color-lime-100);
  --color-surface-50: var(--color-gray-50);
  --color-surface-100: var(--color-gray-100);
  ...
}
```

This file is being unshifted in the `nuxt.options.css` array so that it is globally available to the repo that uses this Nuxt Module. 

Now, in another Nuxt app (call it MAIN), the Nuxt Module is used in the nuxt config.  
This main app also has its own global Css file like this:

```css
// src/main-app/assets/tw.css

@import "tailwindcss" source(none);
```

### Points of consideration 

1. Despite source being set to none in main app (and no other source specified), the MAIN Nuxt app displays proper tailwind classes. Maybe it is because the Module's css file had `../../components` source which is also being applied in the Main app (but that is just co-incidence). If the Module's file structure was different, this won't work. This also raises another issue: In current architecture, where should a Css file be applied in being set in the file itself. Is that good? Shouldn't the source be independent? Example, have a base css file, and then apply it anywhere we want via imports. Is it possible in V4?

2. Is it possible to write the theme in separate base file (separate from where `@import tailwind` and sources are written)? This way, the main app can simply import the themes file inside the main apps's css file. This way, even Module's base css file won't need to pushed globally into the repo using this Module; plus, the Module can still use its own base css file for its own components. 

3. How to override the base theme in the main app? If I use `@theme {--color-primary-50: var(--color-blue-50);}` in the Main css file, the color displayed is still orange (and not blue) while using the color classes anywhere in the app. So, unable to override the Base css file. As mentioned above, the Nuxt Module's css file is unshifted (and not pushed); still, the Main app's css file (which comes after the Base css file) is unable to override it. 

4. Overall alternative solutions, if any?
