### DISCUSSION TITLE
[v4] theme DEFAULT values

### DISCUSSION THREAD

**Discussion by cosn** [tailwindlabs/tailwindcss#15186] [Help] [answered]
Hello,

I'm migrating my v3 config to v4, and had a question about default values, specifically, how would one set them in v4, when there's no measure to it. For example:

``` 
transitionTimingFunction: {
    DEFAULT: 'cubic-bezier(0.25, 1, 0.5, 1)',
},
transitionDuration: {
    DEFAULT: '0.35s',
},
```

Also on the same line but not necessarily DEFAULT value, how would this be moved over:

```
borderStyle: {
    inset: 'inset',
},
```

Thanks!

**Comment by wongjn** [comment, marked as answer]
`DEFAULT` keys are in the `default` namespace, so you'd do:

```css
@theme {
  --default-transition-duration: 0.35s;
  --default-transition-timing-function: cubic-bezier(0.25, 1, 0.5, 1);
}
```

---

In v3,

```js
borderStyle: {
    inset: 'inset',
},
```
wouldn't actually do anything – the `border-style` utilities are static and thus do not read from configuration:
https://github.com/tailwindlabs/tailwindcss/blob/6069a811871c58a9b202fbb3a6f13774c57278c0/src/corePlugins.js#L1654-L1661

However, I can infer what you mean, and you can create your own utility for this like:

```css
@utility border-inset {
  border-style: inset;
}
```

**Reply by cosn** [reply]
Thanks so much!

**Reply by rodogir** [reply]
@wongjn 

What is the recommended way of handling spacing? We currently use the `DEFAULT` key for spacing and padding in our v3 config. I haven't found anywhere how to configure v4 so that "bare" `p` works. With v3 the config below would allow us to use `p` and all its variants (px, pt, etc.). Same for `gap`.

```js
spacing: {
  DEFAULT: "16px"
},
padding: {
  DEFAULT: "16px"
}
```

**Reply by wongjn** [reply]
I don't think there's anyway to get that to work in v4 with theme configuration only. You may need to use `@utility` like:

```css
@utility p {
  padding: 16px;
}

@utility px {
  padding-inline: 16px;
}

…

@utility gap {
  gap: 16px;
}
```
