### DISCUSSION TITLE
[v4] Referencing the default theme font stack is unclear in CSS-first configuration

### DISCUSSION THREAD

**Discussion by romansp** [tailwindlabs/tailwindcss#15253] [Help]
In v3 it was really easy to extend default `font-family` configuration by prepending `sans`:

```ts
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    extend: {
      fontFamily: {
        'sans': ['"Inter"', ...defaultTheme.fontFamily.sans],
      },
    }
  }
}
```

In v4 there doesn't seem to be a way to reference that default font stack anymore via CSS-first configuration.

If I use the following definition `—font-sans: "Inter";` it will negate default font stack causing browser to fallback to `serif` font while custom font is loading (`font-display: swap` is applied). So I need to somehow to reference default font stack in `--font-sans` variable. 

Current workaround seems to be to copy default stack and declare 
```css
--font-sans: "Inter", ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```
But this feels really unnecessary. 

Is there a more elegant solution to this problem? Or maybe tailwindcss v4 could declare css variable with default font stack for others to reference?

**Comment by RobinMalfait** [comment]
Hey!

Our goal with Tailwind CSS v4 is to keep things simple. If you want to customize your theme values then you can, but if you want to rely on default values that existed before, then you currently have to copy & paste them. It's a tiny bit more work, but luckily you typically only have to do that once.

We could make it work with some fancy syntax, but that would only introduce new syntax that you'd have to learn. Something that comes to mind: `--font-sans: "Inter", theme(--font-sans);` and then we'd have to make sure that that `theme(--font-sans)` uses the _old_ values to prevent infinite loops.

**Reply by romansp** [reply]
Thanks @RobinMalfait. Fully support the idea to keep things simple. Thought it's not particularly clear how to migrate v3 config to v4 and not introduce `serif` font fallback issue. Migration guide doesn't cover that. Especially when v3 docs have this section https://tailwindcss.com/docs/font-family#customizing-the-default-font showing how to reference default theme.

Having `--font-sans: "Inter", theme(--font-sans);` would be amazing to be honest but also understand potential complexity to prevent infinite loop.

**Reply by MattIPv4** [reply]
👋 Would also like to note that I'm running into this as well and the solution of copy/pasting the values from within Tailwind v3 to my config in v4 feels really dirty. It'd be nice to have the default font stacks available as dedicated variables that can be referenced if you want to extend font-sans etc.

**Reply by aczw** [reply]
I agree. It's not very futureproof, and I trust Tailwind's default theme the most in terms of staying up to date to the latest CSS features.

**Reply by dgordon-iqx** [reply]
I see that on `4.0.3` it generates the following css.

```css
 html, :host {
    line-height: 1.5;
    -webkit-text-size-adjust: 100%;
    tab-size: 4;
    font-family: var( --default-font-family, ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji" );
    font-feature-settings: var(--default-font-feature-settings, normal);
    font-variation-settings: var( --default-font-variation-settings, normal );
    -webkit-tap-highlight-color: transparent;
  }
  ```
  
  Would the most semantic way then not be to override the `--default-font-family` variable?
  
  So you would define `--default-font-family: "Inter", system-ui, sans-serif;`?

**Reply by joshua-saraceni** [reply]
I currently append `var(--font-sans)` to the end of the CSS variable, and set `font-roboto` on the `<body>` or containing `<div>`:

```css
@theme {
    --font-roboto: "Roboto Flex", "Roboto", var(--font-sans);
}
```

```html
<body class="font-roboto">
    <!-- Content goes here... -->
</body>
```

This way, it doesn't touch the default `--font-sans` variable at all.

**Comment by aholbreich** [comment]
I'm using Tailwind with Astro (5.2)
now hot to migrate this type of default Font overwrite configuration to Tailwind 4? 

```
const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Bricolage Grotesque Variable",
          "Inter Variable",
          "Inter",
          ...defaultTheme.fontFamily.sans,
        ],
      },
    },
  },
};
```
With tailwindcss 3 the above configuration +

import "@fontsource-variable/inter/index.css";
import "@fontsource-variable/bricolage-grotesque";

in the Layout.astro was enough to make it work.

Now it's not picking up in Tailwind 4 ?

**Comment by egucciar** [comment]
Would love actual guidance on how to properly override `--default-font-family` in tailwind v4...it's pretty confusing as it stands right now

**Reply by wongjn** [reply]
You can do:

```css
@theme {
  --default-font-family: Inter, Arial, sans-serif; /* Replace value with your desired value. */
}
```
Though typically you'd want to replace it with an existing font stack (so it is consistent with an existing font stack already in your config:

```css
@theme {
  --default-font-family: var(--font-serif);
}
```
