### DISCUSSION TITLE
[v4] How to use dark/light mode custom varialbes defined in :root in @theme directive?

### DISCUSSION THREAD

**Discussion by IvanKalinin** [tailwindlabs/tailwindcss#15280] [Help] [answered]
Here is a code example that works fine with tailwind v3 and tailwind.config.js but does not in v4 and @theme directive.

```html
<div>
  <div class="w-48 h-48 bg-main border"></div>
</div>

<div data-mode="dark">
  <div class="w-48 h-48 bg-main border"></div>
</div>
```

```css
:root {
  --v3-color-mono-100: #ffffff;
}

:is([data-mode="dark"]) {
  --v3-color-mono-100: #111111;
}

@theme {
  --background-color-main: var(--v3-color-mono-100)
}
```

https://play.tailwindcss.com/3wmtDX8LP5

The browser understands the overridden value, but computed value in light
![image](https://github.com/user-attachments/assets/7b804a14-b5c8-456b-a2b0-34c9c7a53b5c)

And the same thing with config.
https://play.tailwindcss.com/J2UDUtnjyT?file=config

![image](https://github.com/user-attachments/assets/651fd388-b6b4-4859-bc05-6ccaf5bac642)
