### DISCUSSION TITLE
Make a custom class with native tailwind classes

### DISCUSSION THREAD

**Discussion by Trandx** [tailwindlabs/tailwindcss#15306] [Ideas]
Hi! 
I don't know if it is already possible. I think that it will be cool if we can make our custom class based on native tailwind class.
I talk about something like this:

```css
@utility btn {
    bg: primary-500;
    text: sm;
    font: bold;
    mt: 4;
    p: 4;
    border: 2;
    rounded: sm;
}
```
