### DISCUSSION TITLE
I need help with Tailwindcss v4 and Inter font

### DISCUSSION THREAD

**Discussion by didix16** [tailwindlabs/tailwindcss#15415] [Help] [answered]
Hello there,

I'm trying to move on to taildwindcss 4 with a new project and I want to include the Inter font.

I'm following this: [https://rsms.me/inter/#usage](https://rsms.me/inter/#usage)
And this: [https://tailwindcss.com/docs/v4-beta#customizing-your-theme](https://tailwindcss.com/docs/v4-beta#customizing-your-theme).

I want to include this:

```css
:root {
  font-family: Inter, sans-serif;
  font-feature-settings: 'liga' 1, 'calt' 1; /* fix for Chrome */
}
@supports (font-variation-settings: normal) {
  :root { font-family: InterVariable, sans-serif; }
}
```

Into the scss file that tailwindcss have to process, but I don't know how to be done...

I've downloaded the font to have it locally. Then I wanted to include the font in mi app.scss file and try it something like this:

```css
@layer theme, base, components, utilities;

@source "../js";
@source "../views";

@import "tailwindcss/theme" layer(theme);
@import "tailwindcss/preflight" layer(base);
@import "tailwindcss/utilities" layer(utilities);
@import "inter.css";

@theme {
    --font-inter: Inter, sans-serif;
    font-feature-settings: 'liga' 1, 'calt' 1;

    @supports (font-variation-settings: normal) {
      --font-inter: InterVariable, sans-serif;
    }
}
```

But it fails:
```bash
[vite] Internal server error: [postcss] `@theme` blocks must only contain custom properties or `@keyframes`.   

  @theme {
>   @supports (font-variation-settings: normal) {
>     --font-inter: InterVariable, sans-serif;
>   }
  }
```

So I'm looking for some ideas of how it must be done to work properly with the new tailwindcss ecosystem.

Thanks in advance.
