### DISCUSSION TITLE
Components are not working with utilities classes

### DISCUSSION THREAD

**Discussion by dany68** [tailwindlabs/tailwindcss#15444] [Help] [answered]
**What version of Tailwind CSS are you using?**

Tailwind v4.0.0-beta.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite v5.4.11, in an electron-vite app

**What version of Node.js are you using?**

v22.11.0

**What browser are you using?**

Chrome (electronjs version 31.7.6  app)

**What operating system are you using?**

MacOS

**Describe your issue**

Hi,

It seems components cannot have utilities such as md:, lg: or dark: applied to it. For instance, I defined a button.css file:
```
@layer components {
   .btn {
        @apply
            inline-flex items-center justify-center
            gap-1.5 px-3 py-1 font-semibold text-base text-white
            rounded-xl border-1 border-white/40 select-none
            focus:outline-4 focus:outline-blue-800/80 focus:outline-offset-2;
   }
   .btn-lg {
         @apply text-lg px-5 py-2;
   }
}

// Then using it as follows does not work, the btn-lg is not applied on medium and up:
<button class="btn md:btn-lg">Click Me</button>
```

On a different nuxtjs project with tailwind v3 everything is working as expected.

Thanks for you help

**Comment by philipp-spiess** [comment]
`@layer components` is v3 syntax that doesn't exist in v4 anymore. What you instead want to do is to migrate your example to the new `@utility` syntax like so: https://tailwindcss.com/docs/v4-beta#adding-custom-utilities-1


```css
@utility btn-lg {
  @apply text-lg px-5 py-2;
}

@utility btn {
  @apply inline-flex items-center justify-center
    gap-1.5 px-3 py-1 font-semibold text-base text-white
    rounded-xl border-1 border-white/40 select-none
    focus:outline-4 focus:outline-blue-800/80 focus:outline-offset-2;
}
```


https://play.tailwindcss.com/UVQi1qRc6k
