### DISCUSSION TITLE
[v4] add `--radius`, similar to `--spacing`

### DISCUSSION THREAD

**Discussion by RebeccaStevens** [tailwindlabs/tailwindcss#15468] [Ideas]
Spacing can be customized for all variants with:

```css
@theme {
  --spacing: 4px;
}
```

It would be great if this could also be done for other things such as radius as well:

```css
@theme {
  --radius: 4px;
}
```

Currently, all the different radius variants need to be declared:

```css
@theme {
  --radius: 4px;
  --radius-xs: calc(var(--radius) * 0.5);
  --radius-sm: calc(var(--radius) * 1);
  --radius-md: calc(var(--radius) * 1.5);
  --radius-lg: calc(var(--radius) * 2);
  --radius-xl: calc(var(--radius) * 3);
  --radius-2xl: calc(var(--radius) * 4);
  --radius-3xl: calc(var(--radius) * 6);
  --radius-4xl: calc(var(--radius) * 8);
}
```
