### DISCUSSION TITLE
Should you use `@apply` in svelte

### DISCUSSION THREAD

**Discussion by tembbo** [tailwindlabs/tailwindcss#15481] [Help] [answered]
In the tailwind v4 documentation, spesifically https://tailwindcss.com/docs/v4-beta#using-apply-in-vue-svelte, it states that you should still use the `@apply` syntax, but I've also got recommended using plain css variables like this:

```css
body {
    background-color: var(--color-zinc-950);
    color: var(--color-white);
}
```

Which one should I use?
