### DISCUSSION TITLE
Tailwindcss vscode extension preview not work properly with custom css variables

### DISCUSSION THREAD

**Discussion by Genuifx** [tailwindlabs/tailwindcss#15483] [Help]
define css variables following [docs](https://tailwindcss.com/docs/customizing-colors#using-css-variables)

with something like:
```css
  :root {
    /* For rgb(255 115 179 / 1) */
    --color-primary: 255 115 179;

    /* For hsl(333deg 100% 73% / 1) */
    --color-primary: 333deg 100% 73%;

    /* For rgba(255, 115, 179, 1) */
    --color-primary: 255, 115, 179;
  }
```

but the vscode plugin cannot recognize the custom color, how to make it work?
