### DISCUSSION TITLE
How to define multiple transitions with arbitrary syntax?

### DISCUSSION THREAD

**Discussion by Strandedpirate** [tailwindlabs/tailwindcss#15500] [Help]
This syntax isn't working. Is this supported or on the horizon?
```
--slideBoxTransitionBezier: cubic-bezier(0.68, -0.25, 0.265, 1.65);
.myClass {
    @apply transition-[opacity_var(--slideBoxTransitionBezier)_.5s,border-color_var(--slideBoxTransitionBezier)_.7s];
}
```

My expectation is this:
```
.myClass {
    transition: opacity 0.5s var(--slideBoxTransitionBezier),
          border-color 0.7s var(--slideBoxTransitionBezier);
}
```

**Comment by wongjn** [comment]
Adam Wathan, creator of Tailwind advocates avoiding `@apply`:
<https://twitter.com/adamwathan/status/1226511611592085504>
<https://twitter.com/adamwathan/status/1559250403547652097>

So it would be simpler for you to do:

```css
.myClass {
  transition: opacity 0.5s var(--slideBoxTransitionBezier), border-color 0.7s var(--slideBoxTransitionBezier);
}
```
