### DISCUSSION TITLE
Pause animation class name

### DISCUSSION THREAD

**Discussion by 1mehdifaraji** [tailwindlabs/tailwindcss#15512] [Ideas]
There is no class name for pausing an animation so we have to make a `utility` class name like this
```css
@layer utilities {
  .pause-animation {
    animation-play-state: paused;
  }
}
```
Would be better If there was a tailwind class name to pause an animation.
