### DISCUSSION TITLE
is it possible to change --tw to any custom name?

### DISCUSSION THREAD

**Discussion by suresh-ramani** [tailwindlabs/tailwindcss#15520] [Help]
I want to change --tw to any custom name.

Current:

```css
*, :before, :after {
    --tw-border-spacing-x: 0;
    --tw-border-spacing-y: 0;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-pan-x: ;
    --tw-pan-y: ;
    --tw-pinch-zoom: ;
    --tw-scroll-snap-strictness: proximity;
    --tw-gradient-from-position: ;
    --tw-gradient-via-position: ;
    --tw-gradient-to-position: ;
    --tw-ordinal: ;
    --tw-slashed-zero: ;
    --tw-numeric-figure: ;
    --tw-numeric-spacing: ;
    --tw-numeric-fraction: ;
    --tw-ring-inset: ;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgb(59 130 246 / .5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
    --tw-backdrop-blur: ;
    --tw-backdrop-brightness: ;
    --tw-backdrop-contrast: ;
    --tw-backdrop-grayscale: ;
    --tw-backdrop-hue-rotate: ;
    --tw-backdrop-invert: ;
    --tw-backdrop-opacity: ;
    --tw-backdrop-saturate: ;
    --tw-backdrop-sepia: ;
    --tw-contain-size: ;
    --tw-contain-layout: ;
    --tw-contain-paint: ;
    --tw-contain-style: ;
}
```

Need to change like:

```css
*, :before, :after {
    --mytw-border-spacing-x: 0;
    --mytw-border-spacing-y: 0;
    --mytw-translate-x: 0;
    --mytw-translate-y: 0;
    --mytw-rotate: 0;
    --mytw-skew-x: 0;
    --mytw-skew-y: 0;
    --mytw-scale-x: 1;
    --mytw-scale-y: 1;
    --mytw-pan-x: ;
    --mytw-pan-y: ;
    --mytw-pinch-zoom: ;
    --mytw-scroll-snap-strictness: proximity;
    --mytw-gradient-from-position: ;
    --mytw-gradient-via-position: ;
    --mytw-gradient-to-position: ;
    --mytw-ordinal: ;
    --mytw-slashed-zero: ;
    --mytw-numeric-figure: ;
    --mytw-numeric-spacing: ;
    --mytw-numeric-fraction: ;
    --mytw-ring-inset: ;
    --mytw-ring-offset-width: 0px;
    --mytw-ring-offset-color: #fff;
    --mytw-ring-color: rgb(59 130 246 / .5);
    --mytw-ring-offset-shadow: 0 0 #0000;
    --mytw-ring-shadow: 0 0 #0000;
    --mytw-shadow: 0 0 #0000;
    --mytw-shadow-colored: 0 0 #0000;
}
```

is it possible to change like this? If it is the How can i change it?
