### DISCUSSION TITLE
NextJS/React: Is there way/tool to combine classes into single obfuscated after build?

### DISCUSSION THREAD

**Discussion by fakeman2332** [tailwindlabs/tailwindcss#15541] [Help] [answered]
I want to combine all classes into obfuscated like `mt-4 flex flex-col sm:flex-row gap-4` to `asdfg123` after build.
I'm using Next 15 (app router).

**Comment by fakeman2332** [comment]
I've tried https://github.com/soranoo/next-css-obfuscator, but it obfuscating every class and not merge them after all

**Comment by supersenior624** [comment]
You can define a custom class in your CSS file and include all these Tailwind classes:

.asdfg123{
  @apply mt-4 flex flex-col sm:flex-row gap-4;
}

**Reply by fakeman2332** [reply]
I don't want do it manually.

**Reply by fakeman2332** [reply]
I need to clarify what I’m looking for. After the build process, I want all classes to be merged into a single one.

During development, I use a class like `mt4 flex flex-column sm:flex-row <etc>`. But once I run `npm run build`, the element should retain only one class that combines the properties of all the original ones.  
For example, `flex flex-column sm:flex-row` should transform into `asdf123`:  
```css
.asdf123 {
  display: flex;
  flex-direction: column;
}
@media (min-width: 480px) {
  .asdf123 {
    flex-direction: row;
  }
}
```
