### DISCUSSION TITLE
Configure the import resolution

### DISCUSSION THREAD

**Discussion by oscarotero** [tailwindlabs/tailwindcss#15546] [Help]
I'm looking for a way to configure an alias or a default folder to import files in v4
I know `@source` but, afaik it seems to work only with `node_modules` dependencies?

What I need is a way to import css files from a specific folder. For example, let's say I have the `_includes/styles` folder in the root of my project:

```css
/* resolve to _includes/styles/my-styles.css */
@import "my-styles.css";

/* Or using a prefix */
@import "includes:my-styles.css";
```

Is there any way to do this in the standalone CLI version? (I'm not using node).

Maybe a CLI argument: `./tailwind --imports=_includes/styles`.

Or a CSS config like:

```css
@aliases {
  includes: "./_includes/styles";
  other: "./my-company/ui";
}

@import "includes:file1.css";
@import "other:file2.css";
```
