### DISCUSSION TITLE
[popover] add polyfill support for :popover-open

### DISCUSSION THREAD

**Discussion by eloyesp** [tailwindlabs/tailwindcss#15557] [Ideas]
Currently on v4-beta8, the class `open:visible` is transformed on the following css:

``` css
.open\:visible {
  &:is([open], :popover-open) {
    visibility: visible;
  }
}
```

I would use this instead to make it compatible with [a still required polyfill](https://github.com/oddbird/popover-polyfill).

``` css
.open\:visible {
  &:is([open], :popover-open, .\:popover-open) {
    visibility: visible;
  }
}
```

I'm not sure if there is a better place to add this change than on tailwind itself, or how easy would be to fix that on the config.
