### DISCUSSION TITLE
v4: define all Tailwind CSS Variables using ":root, :host" selector for Shadow DOM compatibility

### DISCUSSION THREAD

**Discussion by ibarral** [tailwindlabs/tailwindcss#15556] [Ideas]
Hello,

I'm using Tailwind v4 with Vite on a project where I want to create Web Component using React and Tailwind for the styles.

I noticed that all the CSS Variables included on the @theme layer are inside a ":root" selector, as is mentioned on the [Tailwind v4.0 Beta Documentation](https://tailwindcss.com/docs/v4-beta#css-theme-variables):

```
:root {
  --font-display: "Satoshi", "sans-serif";

   /* ... */
}
```

I would be great if all the theme variables are included using ":root, :host" selector for Shadow DOM compatibility. Example:

```
:root, :host {
  --font-display: "Satoshi", "sans-serif";

   /* ... */
}
```

You can check why on this article:

https://techblog.skeepers.io/create-a-web-component-from-a-react-component-bbe7c5f85ee6

Thanks!

**Comment by bella964** [comment]
Hello,
You're right that by default, Tailwind v4 generates the CSS variables in the :root selector, which is not directly compatible with the Shadow DOM's :host selector. This could cause issues when you're working with Web Components, as styles inside the Shadow DOM are encapsulated and need the :host selector for proper styling.    [JPMCB Card
](https://www.jpmcbcard.com)

To add compatibility for the Shadow DOM, you can modify the Tailwind configuration to include :host in addition to :root. Here's how you can approach it:

Customizing the Tailwind Configuration:

In your tailwind.config.js file, you can extend Tailwind's CSS variables to be included in both :root and :host. You might need to write a custom PostCSS plugin or use Tailwind's @layer to ensure this gets applied.

Using PostCSS with Tailwind (or Tailwind Plugin):

You can customize the @theme layer to prepend :root, :host like this:

js
// tailwind.config.js
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}', // Adjust according to your project structure
  ],
  theme: {
    extend: {
      // You can add custom CSS variables here
    },
  },
  plugins: [
    function ({ addBase }) {
      addBase({
        ':root, :host': {
          '--font-display': '"Satoshi", sans-serif',
          // Add other theme variables here
        },
      });
    },
  ],
};
This ensures that all theme variables are applied within both :root and :host, making them available both globally and within any shadow DOMs.

Ensure Tailwind's CSS is Applied in Shadow DOM:

When you generate your Web Component, ensure that the generated CSS is encapsulated within the component's shadow root. Here's a basic example:

jsx

class MyComponent extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    const style = document.createElement('style');
    style.textContent = `
      :host {
        font-family: var(--font-display, sans-serif);
        /* Other styles */
      }
    `;
    this.shadowRoot.appendChild(style);
  }
}

customElements.define('my-component', MyComponent);

**Reply by ibarral** [reply]
Thanks for your help @bella964 !

I just want to use all the default theme variables of Tailwind, but change the selector to ":root, :host".

I think that the example that you send requires the re-define all the Tailwind variables, and uses the tailwind.config.js, that is not recommended on v4.

Is there any other better way?

Anyway, I think that Tailwind should use the ":root, :host" selector by default for Shadow DOM compatibility ;)

Thanks!

**Reply by andreafmdev** [reply]
Any news on that? 

Thanks!

**Comment by wongjn** [comment]
There was [a similar question asked in the Discord server](https://discord.com/channels/486935104384532500/486935104384532502/1326561436239138817) with a maintainer response as follows:

> > Is there a way (or plan to support this) to make `@theme` directive define the theming variables with different than `:root` selector. I'd need to do it on `:host` (shadow DOM root)?
>
> No plans right now, I guess you could add a custom PostCSS plugin that converts `:root` into `:root, :host` or something. However, shadow dom has other issues around `@property` which we rely on in v4 (see: https://github.com/w3c/csswg-drafts/issues/10541)

**Comment by vincaslt** [comment]
I was testing v4 inside shadow dom, and I faced this issue with `:root` -> `:host`, and I solved that by importing css inline then string-replace w/ `.replaceAll(':root', ':host')` as a quick workaround. However, v4 still won't work in shadow dom because theme variables and some utility properties don't work, i.e. the ones added as `@property`. Is there a solution for this, or do we stick to v3? Is there going to be a solution for shadow dom?

**Reply by guyathomas** [reply]
This isn't perfect, but i've done this as a workaround for now.


```
@import "tailwindcss";

:host {
  --tw-border-style: solid;
  --tw-font-weight: initial;
  --tw-tracking: initial;
  --tw-shadow: 0 0 #0000;
  --tw-shadow-color: initial;
  --tw-inset-shadow: 0 0 #0000;
  --tw-inset-shadow-color: initial;
  --tw-ring-color: initial;
  --tw-ring-shadow: 0 0 #0000;
  --tw-inset-ring-color: initial;
  --tw-inset-ring-shadow: 0 0 #0000;
  --tw-ring-inset: initial;
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-offset-shadow: 0 0 #0000;
}

```

**Reply by j-hit** [reply]
Thanks @guyathomas your workaround solved my issue after multiple hours of debugging and research! 🙏 

I ended up adding some more `@property` variables as standard CSS variables to my `globals.css` file.

```
@import 'tailwindcss';

:host {
    --tw-divide-y-reverse: 0;
    --tw-border-style: solid;
    --tw-font-weight: initial;
    --tw-tracking: initial;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-translate-z: 0;
    --tw-rotate-x: rotateX(0);
    --tw-rotate-y: rotateY(0);
    --tw-rotate-z: rotateZ(0);
    --tw-skew-x: skewX(0);
    --tw-skew-y: skewY(0);
    --tw-space-x-reverse: 0;
    --tw-gradient-position: initial;
    --tw-gradient-from: #0000;
    --tw-gradient-via: #0000;
    --tw-gradient-to: #0000;
    --tw-gradient-stops: initial;
    --tw-gradient-via-stops: initial;
    --tw-gradient-from-position: 0%;
    --tw-gradient-via-position: 50%;
    --tw-gradient-to-position: 100%;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-color: initial;
    --tw-inset-shadow: 0 0 #0000;
    --tw-inset-shadow-color: initial;
    --tw-ring-color: initial;
    --tw-ring-shadow: 0 0 #0000;
    --tw-inset-ring-color: initial;
    --tw-inset-ring-shadow: 0 0 #0000;
    --tw-ring-inset: initial;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-blur: initial;
    --tw-brightness: initial;
    --tw-contrast: initial;
    --tw-grayscale: initial;
    --tw-hue-rotate: initial;
    --tw-invert: initial;
    --tw-opacity: initial;
    --tw-saturate: initial;
    --tw-sepia: initial;
    --tw-drop-shadow: initial;
    --tw-duration: initial;
    --tw-ease: initial;
}
```

**Reply by janogale** [reply]
Thanks, this solved my issue

**Reply by ivandamyanov** [reply]
Thanks a lot I used that and it solved my bare project not being able to render Tailwind. I will start building and see if I face any issues later on.

**Reply by tuxiu21** [reply]
thanks!!

**Comment by joezappie** [comment]
I actually have the exact opposite issue as it looks like it is applying to `:root, :host` in v4 which is strange unless this was changed.

![image](https://github.com/user-attachments/assets/7e872800-f885-4d85-b0f6-e5d770ee4b64)

This issue with this is now any properties defined in the upper scope get overwritten which means nothing propagates to the shadowdom children.


```
@theme { --font-sans: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji"; }
:root[silly-mode] { --font-sans: 'comic sans'; }

<html silly-mode></html> // Shadow dom elements will be ui-san-serif
```

The work around is to set the `@theme` variables to inherit:
```
@theme { --font-sans: inherit; }
:root { --font-sans: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji"; } 
:root[silly-mode] { --font-sans: 'comic sans'; }

<html silly-mode></html> // Shadow dom elements will be comic sans
```

Did this get changed so it applies on :host as well?

**Comment by doits** [comment]
I'm chiming in here, too, with the request to be able to *disable* outputting `:host` selectors at all (I can open a new discussion if this fits better):

I'm using tailwindcss to style pdf documents that are generated by [WeasyPrint](https://github.com/Kozea/WeasyPrint). It worked fine with v3 and I mostly got it to work with v4, too: I could disable some `calc()`s for example (which WeasyPrint doesn't support) by specifying the `--spacing-*` manually etc., but I have one remaining thing that makes it incompatible:

Tailwindcss outputs selectors like `:root, :host {` and WeasyPrint doesn't support `:host`. This leads to all styles inside `:root, :host {` to be ignored (which I [thought was a bug in WeasyPrint but actually isn't](https://github.com/Kozea/WeasyPrint/issues/2373)) and this breaks everything completely.

I know that tailwindcss doesn't target such document generators, but maybe it makes sense to reduce the css anyways when one is sure there is never any shadow DOM used and a tailwindcss config option could be provided to do so?

Maybe it is possible already and I just don't know how?

**Comment by joezappie** [comment]
There's several discussions about wanting tailwind v4 to include the `:root, :host` selector so I'm just confused if this was a change that was made. I even tried to go back to beta-9 from two months ago but I still see the `:host` selector. So a little clarity from the dev team if this is intended or not would be helpful.

Heres a fresh vite + tailwind repo that shows that 
https://github.com/joezappie/tailwind-shadow-dom-test

I can see two scenarios though so I think there needs to be some sort of selector for this:
- If you're using tailwind for your entire project, then you probably want to to propagate your colors and variables from the root.
- If your using tailwind only inside a shadow dom element on a non tailwind site, then the element needs to declare these variables or else you have no colors.

I'm a little torn for my use case. Having it _not_ include `:host` works the way I'd expect it to. Having it include `:host`, I have to declare all my `@theme` variables as `inherit` just to get tailwind to recognize them and then define them later in a `:root` selector, but this has the added benefit of being able to force a fixed color even if the root changes it (such as an important brand color):

```css
@theme {
  --color-primary: inherit;
  --fixed-color: blue;
}

/* Default theme */
:root:not([color-theme]) {
  --color-primary: blue;
}

/* Additional Theme */
:root[color-theme=red] {
  --color-primary: red;
  --fixed-color: red;
}
```

In this example, the primary color would inherit from the root document, but the fixed color would be reset for every component. 

*edit* 
Another potential solution for the problem I described could be importing the theme layer only into the root, and having a separate shadowdom style sheet for my theme that excludes the theme layer:

main.css
```css 
@import "tailwindcss";

@theme {
  --color-primary: blue;
}
```

shadow-dom.css
```css
@layer theme, base, components, utilities;
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css" layer(utilities);
```

This seems to error though not being able to find utility classes.

**Comment by ibqn** [comment]
are there any updates on this topic?

**Comment by astro-stan** [comment]
I am writing an app composed entirely of web components (using lit). 

This worked for me:

```css
/* index.css */

@import "tailwindcss";

/* Look for the presense of a `dark` class in the shadown dom host element or
 * regular elements to apply dark theme */
@custom-variant dark (&:where(.dark, .dark *), :host(.dark));

@theme {
    --color-primary: #F00;
    /* ... */
}

@layer theme {
    @variant dark {
        --color-primary: #0F0;
        /* ... */
    }
}
```


```ts
// MyBaseElement.ts

import style from "index.css?inline";

import { CSSResultGroup, LitElement, unsafeCSS } from "lit";

const darkThemeClass = "dark";

/** The base class of all project web components. */
export class MyBaseElement extends LitElement {
    /* Apply tailwind styles */
    static styles: CSSResultGroup = [unsafeCSS(style)];

    private themeObserver?: MutationObserver;

    connectedCallback() {
        super.connectedCallback();

        /* Sync theme on connection */
        this.syncTheme();

        this.themeObserver = new MutationObserver(() => {
            this.syncTheme();
        });

        /* Observe changes to the 'class' attribute of the html element */
        this.themeObserver.observe(document.documentElement, {
            attributes: true,
            attributeFilter: ["class"],
        });
    }

    disconnectedCallback() {
        super.disconnectedCallback();
        if (this.themeObserver) {
            this.themeObserver.disconnect();
        }
    }

    /**
     * Sync the theme settings with this component.
     *
     * Current implementation is purely CSS based, thus no re-rendering
     * of the component is needed. However this can be overridden to
     * also call `this.requestUpdate()` if for some reason it is necessary to
     * re-render the component on theme change. */
    protected syncTheme() {
        /* Check for the presense of a `darkThemeClass` class in the `<html>` tag */
        const isDark = document.documentElement.classList.contains(darkThemeClass);

        /* Toggle the class on the shadow root.
         * This allows theme color overrides to work (e.g. `--color-myColor` to
         * have different values depending on the current theme) */
        this.classList.toggle(darkThemeClass, isDark);

        /* Also apply or remove the class on all top-level elements in the
         * shadow root (if present).
         * This allows individual theme modifiers (e.g. the `dark:` prefix
         * to classes) to work. */
        if (this.shadowRoot) {
            for (const el of this.shadowRoot.children) {
                el.classList.toggle(darkThemeClass, isDark);
            }
        }
    }
}

```

The above should work on all browsers, including Firefox and Safari, as it does not rely on the `:host-context` pseudo-class. All you need to do is inherit `MyBaseElement` class when implementing your lit components:

```ts
import { TemplateResult, html } from "lit";
import { customElement } from "lit/decorators.js";
import MyBaseElement from "./MyBaseElement.ts"

@customElement("test-component")
export default class TestComponent extends MyBaseElement {
    render(): TemplateResult {
        return html`
            <!-- bg-primary color value and the applied text classes will change depending on the currently set theme -->
            <div class="w-full h-full text-blue dark:text-red bg-primary">
                Test 
            </div>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        "test-component": TestComponent;
    }
}

```

**Reply by agungsb** [reply]
This approach also works for me. But I made a tweak in `connectedCallback`. I add:

```
    /* Sync theme on connection */
    const st = setTimeout(()=> {
      this.syncTheme();
      clearTimeout(st);
    }, 50);
```

By doing that, when the current theme is `dark` and page is refreshed, it would automatically load the dark mode.

The key to this is in "setTimeout". The 50 ms delay is the shortest delay possible to make the component load the correct mode.

**Comment by andreafmdev** [comment]
Any news on this topic? 
in my case i'm building a web component and it seems work after adding the :host selector to my global.css

```css

/* :host, :root  for shadow dom and root for global component compatibility */

:host, :root {
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);
}
``` 

  
  but it seems are missing some utility classes that are not working,like (just for example) "animate-spin" or just a simple -> 
  bg-gradient-to-r from-purple-500 to-pink-500
  
 i can not add every class to the vite config or overwrite with a custom css class...
 
 Someone have an idea? 
 
 Thanks guys

**Reply by ivandamyanov** [reply]
I think I understand your problem and I am also hoping for a solution. In the meantime, I used @j-hit's snippet and bg-gradient-to-r from-purple-500 to-pink-500 specifically works.

**Comment by ivandamyanov** [comment]
I'm highly interested in an official solution for this or support as everyone who wants to develop overlays and similar solutions could face this issue and this limits TailwindCSS's usability!

**Comment by Kanti** [comment]
For me this worked:
````js
import styles from './assets/main.css?inline';

const sheet = new CSSStyleSheet();
sheet.replaceSync(styles.replace('(((-webkit-hyphens:none)) and (not (margin-trim:inline))) or ((-moz-orient:inline) and (not (color:rgb(from red r g b))))', '(display: block)'));
const shadow = hostDiv.attachShadow({mode: "open"});
````
As it will fix the fallback mechanism inside the generated .css file:

````css
/*! tailwindcss v4.1.10 | MIT License | https://tailwindcss.com */
@layer properties {
    @supports (((-webkit-hyphens:none)) and (not (margin-trim:inline))) or ((-moz-orient:inline) and (not (color:rgb(from red r g b)))) {
        *, :before, :after, ::backdrop {
            --tw-rotate-x: initial;
            --tw-rotate-y: initial;
            --tw-rotate-z: initial;
            --tw-skew-x: initial;
            --tw-skew-y: initial;
            --tw-scroll-snap-strictness: proximity;
            --tw-font-weight: initial;
            --tw-shadow: 0 0 #0000;
            --tw-shadow-color: initial;
            --tw-shadow-alpha: 100%;
            --tw-inset-shadow: 0 0 #0000;
            --tw-inset-shadow-color: initial;
            --tw-inset-shadow-alpha: 100%;
            --tw-ring-color: initial;
            --tw-ring-shadow: 0 0 #0000;
            --tw-inset-ring-color: initial;
            --tw-inset-ring-shadow: 0 0 #0000;
            --tw-ring-inset: initial;
            --tw-ring-offset-width: 0px;
            --tw-ring-offset-color: #fff;
            --tw-ring-offset-shadow: 0 0 #0000;
            --tw-outline-style: solid;
            --tw-backdrop-blur: initial;
            --tw-backdrop-brightness: initial;
            --tw-backdrop-contrast: initial;
            --tw-backdrop-grayscale: initial;
            --tw-backdrop-hue-rotate: initial;
            --tw-backdrop-invert: initial;
            --tw-backdrop-opacity: initial;
            --tw-backdrop-saturate: initial;
            --tw-backdrop-sepia: initial;
            --tw-duration: initial
        }
    }
}
````
