### DISCUSSION TITLE
[v4] unable style `&:before` with `dark:` modifier

### DISCUSSION THREAD

**Discussion by dimaMachina** [tailwindlabs/tailwindcss#15595] [Help]
Hi, I am not sure what caused this issue but I am unable to  style `:before` pseudo selector with `dark:` variant

[Playground](https://play.tailwindcss.com/fUGr61v6wl?file=css)

As you can see generated selector

```css
.nextra-steps {
  h2 {
    &:before {
      --tw-content: 'dada';
      content: var(--tw-content);
      &:where(.dark *) {
        background-color: var(--color-red-500);
      }
    }
  }
  h3 {
    &:where(.dark *) {
      background-color: var(--color-red-500);
    }
  }
}
```

it styles background for `.h3` but not for  `.h2:before`
