### DISCUSSION TITLE
Colors not updating synchronously when applying "transition-colors" property to all elements on Chromium

### DISCUSSION THREAD

**Discussion by GHaxZ** [tailwindlabs/tailwindcss#15598] [Help] [answered]
So I want to make the themes on my website changeable, meaning there is a dark and light mode. To achieve this, I utilize CSS custom properties.

In my global app.css (SvelteKit):
```css
.light {
	--foreground: 32, 32, 32;
	--background: 242, 240, 227;

	color: rgba(var(--foreground));
	background: rgba(var(--background));
}

.dark {
	--background: 32, 32, 32;
	--foreground: 242, 240, 227;

	color: rgba(var(--foreground));
	background: rgba(var(--background));
}

* {
	/* Transition colors when switching theme */
	@apply transition-colors duration-300 ease-in-out;
}
```

In my global app.html I have this script, to load saved themes or get the system theme, before any components are mounted, so I can avoid theme flickering when the page loads up:
```html
<script>
  const savedTheme = localStorage.getItem('theme');
  const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches
    ? 'dark'
    : 'light';
  const theme = savedTheme || systemTheme;

  document.documentElement.classList.add(theme);
</script>
```

### The strange part
This works perfectly fine on Firefox based browsers, meaning the colors of all elements on the page change their color at the same time with the specified transition.

When testing this on Chromium based browsers, the elements do not update at the same time, they change their colors one after the other. This causes some elements to still have the old foreground colors even after the background has changed, resulting in them not being visible, until they eventually also update their colors (around 3 seconds later).

So after looking for some information about this odd behavior, I found some information stating that Chromium applies styles to child elements asynchronously, leading to this issue.

I have not found a way of mitigating the issue yet and I'm also not sure if this is a mistake on my end, or if this could be a bug.

If you need any video demonstration footage, please let me know.

Thank you!

**Comment by wongjn** [comment, marked as answer]
Elements that don't have an explicit `color` set have `inherit` as their effective value. This means that the element resolves its value from its parent:

```html
<div style="color: blue">
  I am blue.
  <p>I am blue also because I inherit from parent.</p>
</div>
```

In Chrome, when a parent's `color` value is switched, it seems like child elements with `inherit` value get the new value *after* transitions happen, and then switch their own resolved value, playing their own transition, thus causing the cascading delay.

Thus, you could consider only applying the `color` transition to element(s) that *don't* have `inherit` as a value for `color`. If you only set the `color` on the `.light`/`.dark` element, then that makes things simple:

```css
* {
  transition: background-color theme(transitionDuration.300) theme(transitionTimingFunction.in-out);
}

:is(.light, .dark) {
  transition-property: background-color, color;
}
```
[JSFiddle Demo](https://jsfiddle.net/s0t89dho/2/)

---
As an aside, Adam Wathan (creator of Tailwind) does seem to advocate avoiding `@apply`:
- https://twitter.com/adamwathan/status/1226511611592085504
- https://twitter.com/adamwathan/status/1559250403547652097
