### DISCUSSION TITLE
How should the theme colors for dark mode and regular mode be defined?

### DISCUSSION THREAD

**Discussion by Sweet-KK** [tailwindlabs/tailwindcss#15592] [Help] [answered]
```scss
@import 'tailwindcss';
@variant dark (&:where(.dark, .dark *));
@theme {
  // regular mode
  --color-secondary: rgba(244, 173, 12, 1);
  // Then dark mode? --color-secondary: rgba(215, 156, 50, 1);
}
```
