### DISCUSSION TITLE
[v4] :root css variables overriden but not usable

### DISCUSSION THREAD

**Discussion by kelvin2200** [tailwindlabs/tailwindcss#15609] [Help]
I'm migrating a personal project to Tailwind v4, and I'm trying a simple dark/light theme case via css variables.

I have a root container which has a different value for a css variable, depending on the theme:
```css
:root {
	--c-surface-container-highest: 230 224 233;
}

#root.dark-mode {
	--c-surface-container-highest: 54 52 58;
}
```
As seen in the following screenshot, the variable gets overriden, but the old one is still used
![chrome-page1](https://github.com/user-attachments/assets/4b20f2e9-ade0-4350-9326-35f9e7453d35)

Here's how my theme variables look:

![chrome-page2](https://github.com/user-attachments/assets/bd45a520-a0f8-4499-a086-32c497f7e1b5)
I remember seeing a similar issue somewhere, and I believe I actually commented on it, but I can't find it anymore.
Also, this worked in v3...

What am I missing?

**Comment by wongjn** [comment]
You are missing the understanding of how CSS variables work. See https://github.com/tailwindlabs/tailwindcss/discussions/15122#discussioncomment-11356322 for a detailed explanation but the `--c-surface-container-highest` variable is resolved where it is used in `var()`, which is `:root`. Changing it further down the DOM tree doesn't do anything because `--color-surface-container-highest` has already been resolved to a value.

**Reply by kelvin2200** [reply]
@wongjn yeah, I'm lost... What you say makes sense, but I don't understand why it worked in v3... can't fire up the repo to see what's different, but anyway, can you give me an example of how to do this properly?
Basically overwrite a `:root` variable... dunno exactly what understanding I'm missing, but maybe there's some magic I fail to see.

**Reply by wongjn** [reply]
Define your theme variables with `@theme inline`:

```css
@theme inline {
  --color-surface-container-highest: var(--c-surface-container-highest);
}
```

It worked in v3 because `@theme inline` was the "default" way in v3.
