### DISCUSSION TITLE
[v4] Best method to use CSS variables for multiple themes?

### DISCUSSION THREAD

**Discussion by Boston343** [tailwindlabs/tailwindcss#15600] [Help] [answered]
What's the recommended method for using CSS variables for color theming? As a basic example, take the following CSS v4 config which does not work (which you can also see here https://play.tailwindcss.com/V8n8xj1DFD?file=css):

```css
@import "tailwindcss";

@theme {
  --color-primary: var(--primary);
}

@layer base {
  :root {
    --primary: red;
  }

  .blue {
    --primary: blue;
  }
}
```

The goal is to have various classes which, when added to any element, change the variables and therefore the color styles of that element. However, the above does not work. I duplicated this in a non-tailwind project just using CSS layers and saw the same thing, which is super unfortunate as I was hoping it was specific to tailwind. 

What happens is if you inspect, the text in this tailwind play https://play.tailwindcss.com/V8n8xj1DFD?file=css , you should see the variable `--primary` on the element does show it's blue. But the `--color-primary` variable appears to be using the value that's on the :root at all times. So if you were to add the `blue` class to the `html` element, which you can't in the playground but I tested in my own project, things work as expected.

The best solution I've come up with at this point is to override the --color-primary variable itself. So the CSS will instead look like https://play.tailwindcss.com/yOEsY950qB 

```css
@import "tailwindcss";

@theme {
  --color-primary: red;
}

@layer base {
  .blue {
    --color-primary: blue;
  }
}
```

Is there a better method out there or something I'm missing?

**Comment by wongjn** [comment, marked as answer]
Yes, you are missing the `inline` tag with `@theme` (#14095):

```css
@import "tailwindcss";

@theme inline {
  --color-primary: var(--primary);
}

@layer base {
  :root {
    --primary: red;
  }

  .blue {
    --primary: blue;
  }
}
```

[Your Play with this change](https://play.tailwindcss.com/UVXhuiyxNZ?file=css).

Though, your second method would seem like it could work well too.

**Reply by Boston343** [reply]
By god thank you. I did not see this documented anywhere (nor do I really know what it's doing that makes it now work).

**Reply by wongjn** [reply]
Explanations of the `inline` tag:
- https://github.com/tailwindlabs/tailwindcss/pull/14095
- https://github.com/tailwindlabs/tailwindcss/discussions/15122#discussioncomment-11356322

**Reply by Boston343** [reply]
Fantastic, thank you.

**Reply by kschiffer** [reply]
The problem I have with this solution is that it doesn't really reflect how tokens for different themes are used in the wild.
Usually, you'd have a token like `--color.text.button.default` pointing to a primitive `--primitive.white` for a light theme. Then, when you'd add a dark theme, you'd add a token definition to point to another primitive, eg. `--primitive.black`. In order to make this happen, you'd now have to define a third group of variables:

```less
@theme inline {
  --color-text-button-default: var(--token-color-text-button-default); // Additional group of variables needed here (notice the token prefix)
}

@layer base {
  :root {
    // Global theme-independent primitive definitions
    --primitive-white: #FFF;
    --primitive-black: #000;
  }
  
  .light-theme {
    // Default theme token definitions
    --token-color-text-button-default: var(--primitive-white)
  }

  // Dark theme token definitions
  .dark-theme {
    --token-color-text-button-default: var(--primitive-black)
  }
}
```

When ideally, I'd like to do something like this:

```less
@theme light {
  --token-color-text-button-default: var(--primitive-white)
}

@theme dark {
  --token-color-text-button-default: var(--primitive-black)
}

@layer base {
  :root {
    // Global theme-independent primitive definitions
    --primitive-white: #FFF;
    --primitive-black: #000;
  }
}
```

Now this is pseudo code and I'm sure there's a lot of implications I don't take into account but still wanted to raise this use case.
