### DISCUSSION TITLE
[v4] Shouldn't `--value(--color-*)` output `var(--color-*)` instead of inlining the value?

### DISCUSSION THREAD

**Discussion by diegohaz** [tailwindlabs/tailwindcss#15615] [Help] [answered]
Hi! I'm testing the new functional utilities feature and encountered an issue that I'm unsure is intentional:

```css
@utility test-* {
  color: --value(--color);
}
```

`test-blue-50` currently outputs:

```css
.test-blue-50 {
  color: oklch(0.97 0.014 254.604) /* #eff6ff */;
}
```

However, I expected it to be similar to `text-blue-50`:

```css
.test-blue-50 {
  color: var(--color-blue-50);
}
```

Is this how it's supposed to work? If so, will there be a way to avoid inlining the values in functional utilities? I was hoping to use this feature to let users update the theme on the fly (by updating `--color-blue-50` with JS, for example).
