### DISCUSSION TITLE
Is it possible to use the new *: to apply a class defined in the TailwindCSS 4.0 beta config?

### DISCUSSION THREAD

**Discussion by nstuyvesant** [tailwindlabs/tailwindcss#15625] [Help]
I want to have all classes in this example including the custom class I created in the TailwindCSS 4.0 config (@layer utilities) sit on the parent div because the contents of the div is going to be variable.

Here is my example:
 https://play.tailwindcss.com/Gno7K0pfyV

Is there a way to move the text-shadow class to the parent div?

Sorry, I'm very new to TailwindCSS.

**Comment by nstuyvesant** [comment]
Arg... it was very simple. I was trying to find more of a TailwindCSS way to do it vs. traditional CSS...
https://play.tailwindcss.com/m5mPRwz20V?file=css

This is how I defined the text-shadow class so I could apply it to the div:
```css
@layer utilities {
  .text-shadow > * {
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2) !important;
  }
}
```
