### DISCUSSION TITLE
[V4] Add z-index to @theme

### DISCUSSION THREAD

**Discussion by stijns96** [tailwindlabs/tailwindcss#15649] [Ideas]
With V4 there is no option to extend the z-index utility. 

I know had to add the code below myself.

```css
@utility z-* {
  z-index: --value(--z- *, integer, [integer]);
}
```

In addition to this, `[integer]` doesn't really do much. I can simply add `z-[hidden]` and it is transformed to:

```css
.z-\[hidden\] {
    z-index: hidden;
  }
```

**Comment by wongjn** [comment]
You can do:

```css
@theme {
  --z-index-foo: foo;
}
```
To add custom values. Though for integer values, it works out of the box without the need for any theme extension required.
