### DISCUSSION TITLE
[V4-beta.9] Allow @media inside @theme

### DISCUSSION THREAD

**Discussion by stijns96** [tailwindlabs/tailwindcss#15650] [Ideas]
We normally create responsive variables. This is not possible in V4.

`Error: `@theme` blocks must only contain custom properties or `@keyframes`.`

**Comment by stijns96** [comment]
I can imagine that @theme is just for creating the variable itself and overriding this needs to be done outside of @theme.

```css
@theme {
  --margin-block-container: --spacing(4);
}

:root {
  @media (width >= theme(--breakpoint-md)) {
    --margin-block-container: --spacing(8);
  }
}
```

**Reply by stijns96** [reply]
Although... I still have to wrap it into the @layer theme as well.

```css
@theme {
  --margin-block-container: --spacing(4);
}

@layer theme {
  :root {
    @media (width >= theme(--breakpoint-md)) {
      --margin-block-container: --spacing(8);
    }
  }
}
```
