### DISCUSSION TITLE
[V4-beta.9] Transform inline and block properties to x and y

### DISCUSSION THREAD

**Discussion by stijns96** [tailwindlabs/tailwindcss#15651] [Ideas]
I want to add an util like `my-container`. For this I'm adding

```css
@theme {
  --margin-block-container: --spacing(4);
}
```

It converts to `my-block-container` instead of `my-container`

<img width="556" alt="image" src="https://github.com/user-attachments/assets/092e73b6-ed72-4ad4-8202-ddc1284294f1" />
