### DISCUSSION TITLE
How do you customize Tailwind CSS colors?

### DISCUSSION THREAD

**Discussion by Hadyen888** [tailwindlabs/tailwindcss#15668] [Help] [answered]
I want to change the overall theme of my website without reassigning the variables everywhere

**Comment by AidenJastrzembski** [comment, marked as answer]
Edit the theme.extend.colors section in tailwind.config.js.
it would look like this

```module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          light: '#6D28D9', // Custom light shade
          DEFAULT: '#4C1D95', // Default primary color
          dark: '#3B0764', // Custom dark shade
        },
        secondary: '#14B8A6', // Single custom color
        danger: '#EF4444', // Another custom color
      },
    },
  },
  plugins: [],
};
```

**Reply by AbdushukurRasulov** [reply]
How this can be done with Tailwind v4 in css file ?
@AidenJastrzembski

**Reply by wongjn** [reply]
```css
@theme {
  --color-primary-light: #6D28D9;
  --color-primary: #4C1D95;
  --color-primary-dark: #3B0764;
  --color-secondary: #14B8A6;
  --color-danger: #EF4444;
}
```
