### DISCUSSION TITLE
Customizing typography in V4 (beta)

### DISCUSSION THREAD

**Discussion by Avaray** [tailwindlabs/tailwindcss#15670] [Help]
In V3 I configured typography in `tailwind.config.mjs` like this:
```ts
export default {
  theme: {
    extend: {
      typography: () => ({
          DEFAULT: {
            css: {},
          },
          md: {
            css: {
              h1: {
                fontSize: '2.25em',
                lineHeight: '1.2',
              },
            },
          },
        }
      }
    }
  }
}
```
As you can see in the example, I changed the default font size and line height of the `<h1>` element for the `md` breakpoint.

How to do the same in V4 (without using Legacy `tailwind.config.js` file)?

**Comment by dvzrd** [comment]
I have a separate typography.css file that I import into a base layer.

```css
@import "./base/typography.css" layer(base);
```

In that file, I just have typography related styles, for example:

```css
h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: var(--font-heading);
  line-height: var(--leading-tight);
}

h1 {
  font-weight: var(--font-weight-extrabold);
  font-size: var(--text-12xl);
}

...
```

But the easiest way would be to have a base layer in your main css file like this:

```css
@layer base {
  h1 {
    @media (min-width: theme(--breakpoint-md)) {
      font-size: 2.25em;
      line-height: 1.2;
    }
  }
}
```

**Reply by Avaray** [reply]
Are you using this approach in V4?

**Reply by dvzrd** [reply]
yea, I have a typography css file I import into a base layer. I have a monorepo so Im relying on a lot of separate files that I import into my apps as needed from different ui packages (i.e. blog, shop, etc).

I don't really scale my base font sizes for larger screens, I usually do that for specific components. I wanted to have a modular-scale plugin to handle that at some point. But you can totally add media queries to scale your font-sizes for larger screens if you wanted to. Here's my full typography.css file:

```css
body {
  font-family: var(--font-body);
  font-weight: var(--font-weight-normal);
  line-height: var(--leading-normal);
  font-size: var(--text-base);
}

h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: var(--font-heading);
  line-height: var(--leading-tight);
}

h1,
h2 {
  font-weight: var(--font-weight-bold);
  line-height: var(--leading-start);
}

h3,
h4 {
  font-weight: var(--font-weight-semibold);
}

h5,
h6 {
  font-weight: var(--font-weight-medium);
  line-height: var(--leading-normal);
}

h1 {
  font-weight: var(--font-weight-extrabold);
  font-size: var(--text-12xl);
}

h2 {
  font-size: var(--text-8xl);
}

h3 {
  font-size: var(--text-6xl);
}

h4 {
  font-size: var(--text-4xl);
}

h5 {
  font-size: var(--text-2xl);
}

h6 {
  font-size: var(--text-xl);
}

p,
a {
  font-weight: var(--font-weight-normal);
  line-height: var(--leading-normal);
}

button,
label,
th {
  font-weight: var(--font-weight-medium);
  line-height: var(--leading-start);
}
```

My main.css file looks something like this (depends on the package or app):

```css
@import "tailwindcss" source(none);
@import "./source.css";
@import "./plugins.css";
@import "./variants.css";
@import "./theme.css";
@import "./base.css";
@import "./components.css";
@import "./utilities.css";
```

the base.css file has multiple imports, including different themes (for dark and light theme variables):

```css
@import "./themes/dark.css" layer(base);
@import "./themes/light.css" layer(base);
@import "./variables.css" layer(base);
@import "./base/layout.css" layer(base);
@import "./base/typography.css" layer(base);
```

If I were to scale my base typography font-sizes, I'd do something like this for example:

```css
h1 {
  font-weight: var(--font-weight-extrabold);
  font-size: var(--text-12xl);
  
  @media (min-width: theme(--breakpoint-md)) {
      font-size: var(--text-14xl);
   }
   
   @media (min-width: theme(--breakpoint-xl)) {
      font-size: var(--text-16xl);
   }
}
```

You would of course need to set those text variables in your theme as well:

```css
@theme inline {
  --text-xs: 0.75em;
  --text-sm: 0.875em;
  --text-base: 1em;
  --text-md: 1.125em;
  --text-lg: 1.25em;
  --text-xl: 1.375em;
  --text-2xl: 1.5em;
  --text-3xl: 1.625em;
  --text-4xl: 1.75em;
  --text-5xl: 1.875em;
  --text-6xl: 2em;
  --text-7xl: 2.125em;
  --text-8xl: 2.25em;
  --text-9xl: 2.375em;
  --text-10xl: 2.5em;
  --text-11xl: 2.625em;
  --text-12xl: 2.75em;
  --text-13xl: 2.875em;
  --text-14xl: 3em;
  --text-15xl: 3.125em;
  --text-16xl: 3.25em;
}
```

You may want to use `calc` or a custom function to do this, in case you want to more easily change the scale. I think I've seen some examples floating around in the discussions here before. But to be honest, with AI you can automate writing out a long list of variables just fine.

**Reply by deebov** [reply]
I think this is a good first step but unfortunately it doesn't handle the `not-prose` class.

**Reply by wongjn** [reply]
You could wrap the selectors as such:

```css
@layer components {
  .prose :where(:not(.not-prose,.not-prose *)) {
    &:is(h1) {
      …
    }

    …
  }
}
```
https://play.tailwindcss.com/jmZZKnbeyP?file=css

**Reply by deebov** [reply]
@wongjn Appreciate the response. But our sase seem to be a little bit more advanced than this. Basically, we have two different sizes for prose: `prose` and `prose-lg`. And our common case is that `prose-lg` should be applied only on desktop in some place `md:prose-lg`. And also, we should be able to use `not-prose` inside `prose` as before.

This is what I have written so far:

```
.prose :not(:where([class~="not-prose"], [class~="not-prose"] *)) {
    &:where(p) {
        margin-top: calc(var(--spacing) * 4);
        margin-bottom: calc(var(--spacing) * 4);
    }
}

.prose.prose-lg :not(:where([class~="not-prose"], [class~="not-prose"] *)),
.prose[class*=":prose-lg"] :not(:where([class~="not-prose"], [class~="not-prose"] *)) {
    &:where(p) {
        margin-top: calc(var(--spacing) * 4.5);
        margin-bottom: calc(var(--spacing) * 4.5);
    }
}
```

But the problem with this is that `prose-lg` won't work automatically with any breakpoint selectors unless specified manually here ^.

**Reply by deebov** [reply]
Although, adding this inside `@layer components` solve that problem, I couldn't seem to make it work easily.

**Reply by deebov** [reply]
It also seems like that the layer `component` is overridden by the layer `utilities` which the default typography plugin inserts into.

**Reply by wongjn** [reply]
You'd need to use `@utility` for variants to work: https://play.tailwindcss.com/77lsNoDnXu?file=css

**Reply by deebov** [reply]
It's still overridden by the default typography styles:

<img width="367" alt="image" src="https://github.com/user-attachments/assets/b173ad35-8951-4acf-b530-31ce0ee06db1" />

(bottom is what I wrote as a utility)

**Reply by KorigamiK** [reply]
Exactly what happens for me, did you every figure it out?

**Reply by tifandotme** [reply]
I've managed to migrate my prose configuration to a CSS file. Hope this helps

<details>
<summary>from</summary>

```js
import colors from "tailwindcss/colors"
import defaultTheme from "tailwindcss/defaultTheme"

/** @type {import("tailwindcss").Config} */
const config = {
  theme: {
    extend: {
      typography: {
        // default prose styles: ./node_modules/@tailwindcss/typography/src/styles.js
        DEFAULT: {
          css: {
            "h2::before": {
              display: "block",
              marginBottom: "1rem",
              height: "3px",
              width: "1.5rem",
              background: "hsl(var(--foreground))",
              content: "''",
            },
            h2: {
              marginTop: "3rem",
              marginBottom: "1.5rem",
              fontFamily: [
                "var(--font-heading)",
                ...defaultTheme.fontFamily.serif,
              ].join(", "),
              letterSpacing: defaultTheme.letterSpacing.wide,
              fontWeight: defaultTheme.fontWeight.normal,
              fontSize: defaultTheme.fontSize["4xl"][0],
              ...defaultTheme.fontSize["4xl"][1],
            },
            h3: {
              marginTop: "1.3rem",
              fontWeight: defaultTheme.fontWeight.semibold,
              fontSize: defaultTheme.fontSize["xl"][0],
              ...defaultTheme.fontSize["xl"][1],
            },
            "blockquote p:last-of-type": {
              marginBottom: "0",
            },
            "blockquote p:first-of-type::before": null,
            "blockquote p:last-of-type::after": null,
            "blockquote p:first-of-type": {
              marginTop: "0",
            },
            "p + p, blockquote + p, ol, ul": {
              marginTop: "0",
            },
            blockquote: {
              marginTop: "0",
              fontWeight: defaultTheme.fontWeight.normal,
            },
            pre: null,
            "code::before": null,
            "code::after": null,
            code: {
              fontWeight: defaultTheme.fontWeight.extrabold,
              color: "hsl(var(--bold)) !important",
            },
            a: {
              fontWeight: defaultTheme.fontWeight.normal,
              textUnderlineOffset: "1px",
            },
            figure: {
              marginTop: "1.25rem",
              marginBottom: "1.25rem",
            },
            "--tw-prose-body": "hsl(var(--foreground))",
            "--tw-prose-headings": "hsl(var(--heading))",
            "--tw-prose-lead": colors.zinc[600],
            "--tw-prose-links": "hsl(var(--foreground))",
            "--tw-prose-bold": "hsl(var(--bold))",
            "--tw-prose-counters": colors.zinc[500],
            "--tw-prose-bullets": colors.zinc[300],
            "--tw-prose-hr": "hsl(var(--border))",
            "--tw-prose-quotes": "hsl(var(--foreground))",
            "--tw-prose-quote-borders": colors.zinc[300],
            "--tw-prose-captions": colors.zinc[500],
            "--tw-prose-code": "hsl(var(--foreground))",
            "--tw-prose-pre-code": colors.zinc[200],
            "--tw-prose-pre-bg": "var(--codeblock)",
            "--tw-prose-th-borders": colors.zinc[300],
            "--tw-prose-td-borders": colors.zinc[200],
            "--tw-prose-invert-body": "hsl(var(--foreground))",
            "--tw-prose-invert-headings": "hsl(var(--heading))",
            "--tw-prose-invert-lead": colors.zinc[400],
            "--tw-prose-invert-links": "hsl(var(--foreground))",
            "--tw-prose-invert-bold": "hsl(var(--bold))",
            "--tw-prose-invert-counters": colors.zinc[400],
            "--tw-prose-invert-bullets": colors.zinc[600],
            "--tw-prose-invert-hr": "hsl(var(--border))",
            "--tw-prose-invert-quotes": "hsl(var(--foreground))",
            "--tw-prose-invert-quote-borders": colors.zinc[700],
            "--tw-prose-invert-captions": colors.zinc[400],
            "--tw-prose-invert-code": "hsl(var(--foreground))",
            "--tw-prose-invert-pre-code": colors.zinc[300],
            "--tw-prose-invert-pre-bg": "var(--codeblock)",
            "--tw-prose-invert-th-borders": colors.zinc[600],
            "--tw-prose-invert-td-borders": colors.zinc[700],
          },
        },
      },
    },
  }
}

export default config
```

</details>

<details>
<summary>to</summary>

```css
@import "tailwindcss"

...

@plugin "@tailwindcss/typography";

@utility prose {
  :where(:not(.not-prose, .not-prose *)) {
    --tw-prose-body: hsl(var(--foreground));
    --tw-prose-headings: hsl(var(--heading));
    --tw-prose-links: hsl(var(--foreground));
    --tw-prose-bold: hsl(var(--bold));
    --tw-prose-counters: hsl(var(--color-zinc-500));
    --tw-prose-bullets: hsl(var(--color-zinc-300));
    --tw-prose-hr: hsl(var(--border));
    --tw-prose-quotes: hsl(var(--foreground));
    --tw-prose-quote-borders: hsl(var(--color-zinc-300));
    --tw-prose-captions: hsl(var(--color-zinc-500));
    --tw-prose-code: hsl(var(--foreground));
    --tw-prose-pre-code: hsl(var(--color-zinc-200));
    --tw-prose-pre-bg: var(--codeblock);
    --tw-prose-th-borders: hsl(var(--color-zinc-300));
    --tw-prose-td-borders: hsl(var(--color-zinc-200));

    --tw-prose-invert-body: hsl(var(--foreground));
    --tw-prose-invert-headings: hsl(var(--heading));
    --tw-prose-invert-links: hsl(var(--foreground));
    --tw-prose-invert-bold: hsl(var(--bold));
    --tw-prose-invert-counters: hsl(var(--color-zinc-400));
    --tw-prose-invert-bullets: hsl(var(--color-zinc-600));
    --tw-prose-invert-hr: hsl(var(--border));
    --tw-prose-invert-quotes: hsl(var(--foreground));
    --tw-prose-invert-quote-borders: hsl(var(--color-zinc-700));
    --tw-prose-invert-captions: hsl(var(--color-zinc-400));
    --tw-prose-invert-code: hsl(var(--foreground));
    --tw-prose-invert-pre-code: hsl(var(--color-zinc-300));
    --tw-prose-invert-pre-bg: var(--codeblock);
    --tw-prose-invert-th-borders: hsl(var(--color-zinc-600));
    --tw-prose-invert-td-borders: hsl(var(--color-zinc-700));

    &:where(h2)::before {
      display: block;
      marginbottom: 1rem;
      height: 3px;
      width: 1.5rem;
      background: hsl(var(--foreground));
      content: "";
    }

    &:where(h2) {
      font-family: var(--font-heading);
      font-size: var(--text-4xl);
      line-height: var(--text-4xl-line-height);
      letter-spacing: var(--tracking-wide);
      font-weight: var(--font-weight-normal);
      margin-top: 3rem;
      margin-bottom: 1.5rem;
    }

    &:where(h3) {
      margin-top: 1.3rem;
      font-weight: var(--font-weight-semibold);
      font-size: var(--text-xl);
      line-height: var(--text-xl--line-height);
    }

    &:where(blockquote p:last-of-type) {
      margin-bottom: 0;
    }

    &:where(blockquote p:first-of-type) {
      margin-top: 0;
      &::before {
        content: none;
      }
    }

    &:where(blockquote p:last-of-type)::after {
      content: none;
    }

    &:where(p + p),
    &:where(blockquote + p),
    &:where(ol),
    &:where(ul) {
      margin-top: 0;
    }

    &:where(blockquote) {
      margin-top: 0;
      font-weight: var(--font-weight-normal);
    }

    &:where(pre) {
      content: none;
    }

    &:where(code) {
      font-weight: var(--font-weight-extrabold);
      color: hsl(var(--bold)) !important;
      &::before {
        content: none;
      }
      &::after {
        content: none;
      }
    }

    &:where(a) {
      font-weight: var(--font-weight-normal);
      text-underline-offset: 1px;
    }

    &:where(figure) {
      margin-top: 1.25rem;
      margin-bottom: 1.25rem;
    }
  }
}
```

</details>
