### DISCUSSION TITLE
Dark theme using the same variable

### DISCUSSION THREAD

**Discussion by peterparker2005** [tailwindlabs/tailwindcss#15746] [Help] [answered]
Any way to use the same variable overriding it value if dark exists in `<html class="dark" />`?

```css
@import 'tailwindcss';

@custom-variant dark (&:is(.dark *));

@theme {
	--breakpoint-sm: 320px;
	--breakpoint-md: 640px;
	--breakpoint-lg: 1000px;
	--breakpoint-xl: 1600px;

	/* colors */
	--color-foreground: hsl(0 0% 13%);
	--color-background: hsl(0 0% 100%);

	--color-primary: hsl(40 80% 70%);
	--color-primary-foreground: var(--color-foreground);
	--color-primary-hover: hsl(40 82% 61%);
	--color-disabled: hsl(233 5% 34%);
	--color-disabled-foreground: var(--color-background);
}

@layer base {
	.dark {
		/* colors */
		--color-foreground: hsl(0 0% 100%);
		--color-background: hsl(274 59% 5%);

		--color-disabled-foreground: var(--color-foreground);
	}
}
```

I was using `:root` where I had `.dark {}` in v3. Why nothing like `@theme dark {}` exists in v4? :c

**Comment by wongjn** [comment]
Sorry, I don't quite understand the problem you are experiencing. Could you please elaborate more on the problem you are trying to solve?

**Reply by deebov** [reply]
I think he was asking how one can override base theme variable if a variant such as `dark` is applied.

**Reply by wongjn** [reply]
I believe that's what they are doing already, if I am not mistaken. They have the `.dark` rule which should override the values in `@theme` when `dark` is added to the `<html>` element.

**Comment by deebov** [comment]
I have the same question, how can we override base theme variables for variants like dark-mode?

**Reply by wongjn** [reply]
Pretty much like they showed above. If `dark` is not on the `<html>` element, then you may need to tag your `@theme` with `inline`:

```css
@theme inline {
  …
}
```

**Comment by hades200082** [comment, marked as answer]
Same question here.

In the old Tailwind we could define CSS vars like this:

```css
root {
  --color-primary: #ff0000;
  
  .dark { /* Assuming using class for dark mode, but selector could be changed for data attributes, etc. if needed */
    --color-primary: #660000;
  }
}
```

This meant that, with some changes to tailwind config, we could use this in out HTML like this:

```html
<div class="bg-primary size-5"></div>
<h2 class="text-primary">My heading</h2>
.. etc ..
```

... and our themes would automatically adjust to dark mode.

With the new `@theme {  }` way, how do we achieve the same?

**Reply by wongjn** [reply]
```css
@theme {
  --color-primary: #ff0000;
}

@layer theme {
  .dark { /* Assuming using class for dark mode, but selector could be changed for data attributes, etc. if needed */
    --color-primary: #660000;
  }
}
```

**Reply by melasculla** [reply]
> ```css
> @theme {
>   --color-primary: #ff0000;
> }
> 
> @layer theme {
>   .dark { /* Assuming using class for dark mode, but selector could be changed for data attributes, etc. if needed */
>     --color-primary: #660000;
>   }
> }
> ```

thanks that works just fine! 💜

**Reply by hades200082** [reply]
Awesome - this could do with being in the docs!

**Reply by czak** [reply]
Thanks for this. It works for me when dark mode is enabled by CSS class, but not with `prefers-color-scheme`. Is this :point_down: working for anyone?

```css
@theme {
  --color-primary: #ff0000;
}

@layer theme {
  @media (prefers-color-scheme: dark) {
    --color-primary: #660000;
  }
}
```

I'm still getting `#ff0000` when browser is in dark mode.
