### DISCUSSION TITLE
Custom background size and position

### DISCUSSION THREAD

**Discussion by Falci** [tailwindlabs/tailwindcss#15756] [Help] [answered]
I tried to use a custom background size with:

```html
<div class="bg-[100px_100px]"></div>
```

But the output was background position:
```css
.bg-\[100px_100px\] {
    background-position: 100px 100px;
}
```

[playground](https://play.tailwindcss.com/XWXl7pg0Jy)

What's the proper way to define custom background size?

<img width="713" alt="image" src="https://github.com/user-attachments/assets/c1e0f127-4d21-440c-b50f-678db3d92785" />
