### DISCUSSION TITLE
Multiple `:lang()` selectors added to prose styles since v0.5.12

### DISCUSSION THREAD

**Discussion by Joolyan** [tailwindlabs/tailwindcss#15763] [Ideas]
Since @tailwindcss/typography v0.5.12 (which added logical properties for RTL support), the plugin generates multiple instances of `:lang()` selectors for prose styles, which can overwrite styling added via tailwind.config.js
Here's an example of the generated CSS:

```css
.prose :where(ul):not(:where([class~="not-prose"], [class~="not-prose"] *)):not(:is(:lang(ae), :lang(ar), :lang(arc), :lang(bcc), :lang(bqi), :lang(ckb), :lang(dv), :lang(fa), :lang(glk), :lang(he), :lang(ku), :lang(mzn), :lang(nqo), :lang(pnb), :lang(ps), :lang(sd), :lang(ug), :lang(ur), :lang(yi))) {
  padding-left: 1.625em;
}
```

The issue does not occur in v0.5.11 and earlier versions of the plugin.

Supporting RTL seems to add a lot of complexity, so it would be helpful if the option to disable RTL was available.
