### DISCUSSION TITLE
[v4] How to define a functional utility with slash notation?

### DISCUSSION THREAD

**Discussion by hazae41** [tailwindlabs/tailwindcss#15775] [Help]
I want to make a simple utility that defines a text color depending on dark mode but keeps the given opacity

```css
@utility text-default/* {
  color: color-mix(in oklab, var(--color-black) --value(percentage), transparent);
  
  @variant dark {
    color: color-mix(in oklab, var(--color-white) --value(percentage), transparent);
  }
}
```

It fails with this message

```
Error: `@utility text-default*` defines an invalid utility name. Utilities should be alphanumeric and start with a lowercase letter.
```

When digging the code it's clear that the Regex doesn't support it

https://github.com/tailwindlabs/tailwindcss/blob/a8c54acaba7d51875bd332163754fb8bc40939a4/packages/tailwindcss/src/utilities.ts#L28

Is there a way to do what I want to achieve?

**Comment by royduin** [comment]
It seems like having a modifier defined will activate this functionality: https://tailwindcss.com/docs/adding-custom-styles#modifiers, related: https://github.com/tailwindlabs/tailwindcss/discussions/16167

```html
<div class="text-default">text-default</div>
<div class="text-default/50">text-default/50</div>
<hr>
<div class="text-blue">text-blue</div>
<div class="text-blue/50">text-blue/50</div>
```

```css
@import "tailwindcss";

@theme {
  --default: red;
  --blue: blue;
}

@utility text-* {
  --alpha: calc(--modifier(integer) * 1%);
  color: --alpha(--value(--*, [color]) / var(--alpha, 100%));
}
```

Demo: https://play.tailwindcss.com/kB5wRTM7Ty?file=css

**Reply by royduin** [reply]
But it only seems te work with a utility that accepts an argument, without it it's not working:
```html
<div class="text">text</div>
<div class="text/50">text/50</div>
```

```css
@import "tailwindcss";

@utility text {
  --alpha: calc(--modifier(integer) * 1%);
  color: --alpha(red / var(--alpha, 100%));
}
```
Demo: https://play.tailwindcss.com/ECphsE1vzA?file=css
