### DISCUSSION TITLE
how to change theme colors in @variant dark

### DISCUSSION THREAD

**Discussion by njacob1001** [tailwindlabs/tailwindcss#15774] [Help]
I would like to add a new color like this:

```css
@theme {
  --color-primary: oklch(20.79% 0.04 265.73);
}
```

This works, but when I try to set a new value for the dark theme, I'm not sure how the configuration should be written.

I tried:

```css
@theme {
  --color-primary: oklch(20.79% 0.04 265.73);
  @variant dark {
    --color-primary: oklch(98.38% 0.0035 247.86);
  }
}
```
and also:

```css
@variant dark {
  --color-primary: oklch(98.38% 0.0035 247.86);
}
```
Neither of these work at the moment. Could you help me figure out the correct way to set this up?
