### DISCUSSION TITLE
How to add  !important;  in tailwind version 4 ?

### DISCUSSION THREAD

**Discussion by suraj50000** [tailwindlabs/tailwindcss#15789] [Help]
How to add  **!important;**  in tailwind version 4 ?
please share an example

**Comment by aayamrajshakya** [comment]
@suraj50000, you can just add exclamation mark in front of the utility class to add `!important`.

Example:
## Tailwind example
```html
<button class="!bg-green-500">Hello</button>
```

## Vanilla CSS
```css
.button {
  background-color: green !important;
}
```
```html
<button class="button">Hello</button>
```
