### DISCUSSION TITLE
Tailwindcss 4 comes with too much defaults when all I need is utilities (migration from v3)

### DISCUSSION THREAD

**Discussion by vdegenne** [tailwindlabs/tailwindcss#15797] [Help] [answered]
Below is compiled tailwind 3 from one of my recent app:

![screenshot_2025-01-24_12-29-47](https://github.com/user-attachments/assets/b33a8dc7-32de-4ca1-b741-f22244660fdc)

As you can see, `tailwindcss` only kept the strict minimum only the css that my application needs and it's compressed into a few kilobits, great!  

Now, I haven't changed anything in my app, I just migrated to `tailwindcss` 4 right, and here's the compiled code (spoilers: it might hurt your eyes):

![image](https://github.com/user-attachments/assets/3717a88e-b7f4-47c1-9f8e-13e55574240e)

Yes Right! it's like a dozen times bigger... and I am not sure to understand the reasons because a lot of this code seems unecessary (lots of colors vars I don't even use.)

Update: I understand now why is this code injected in final build, I just wish there were an easy way to prevent that for the people that might just want to use TW4 for the layouts. In TW3 it was as easy as writting `@tailwind utilities` only.

**Comment by wongjn** [comment]
As per [the documentation](https://tailwindcss.com/docs/theme#using-your-theme-variables):

> This makes it easy to reference all of your design tokens in any of your custom CSS or inline styles.

**Reply by vdegenne** [reply]
I am not asking what are css variables for. I am familiar with those. But what if I don't need them? I mainly use Tailwindcss to layout my app (in tailwindcss 3 I just needed the utilities module)

**Reply by wongjn** [reply]
There's no API to remove the ones you don't need. You'd need to manually remove them either by:
- Selectively removing the ones you don't need.
- Disabling the default `@theme` and defining the only ones you need (optionally via `inline` so *they* don't show up either).

**Reply by vdegenne** [reply]
Ok I understand but how do you selectively remove them, or how do you disable the default theme without losing code detection?

**Reply by wongjn** [reply]
## Selective removal:

```css
@import "tailwindcss";

@theme {
  --color-blue-*: initial;
  --color-red-600: initial;
  …
}
```

## Disabling the default `@theme`:

```css
@import "tailwindcss";

@theme {
  --*: initial;

  --spacing: 4px;

  --font-body: Inter, sans-serif;
  --color-lagoon: oklch(0.72 0.11 221.19);
  --color-coral: oklch(0.74 0.17 40.24);
  --color-driftwood: oklch(0.79 0.06 74.59);
  --color-tide: oklch(0.49 0.08 205.88);
  --color-dusk: oklch(0.82 0.15 72.09);
  …
}
```
