### DISCUSSION TITLE
tailwindcss v4.0 @tailwindcss/forms "Unknown word" error

### DISCUSSION THREAD

**Discussion by MattLysinger** [tailwindlabs/tailwindcss#15818] [Help]
**ISSUE**
I just upgraded to v4.0 from v3. and when using the `@tailwindcss/forms` plugin i get a `"Unknown word"` error. When i remove the `@tailwindcss/forms` plugin i do not get this error.  I am not sure how to resolve this issue - any help is appreciated. Also, is the `@tailwindcss/forms` plugin even needed in v4.0? (i have not been able to test since i cannot get it to work).

**I HAVE TRIED**
1. I have tried removing everything in the .css file except `@import 'tailwindcss'` and `@plugin '@tailwindcss/forms'`  but it still did not work.
2. I have tried using a `tailwind.config.js` file (even though not needed in v4.0) and it still did not work.

**REFERENCES**
I am using node v20.18.1.

The error message is shown below:
![v4 unknown word error - redacted](https://github.com/user-attachments/assets/a010e8b9-db0d-4ee5-a576-98b7059aee64)

My package.json is shown below:
![packageJson](https://github.com/user-attachments/assets/ef64cf7d-c04f-47b1-9f2e-9877fca0fbbd)

My vite.config is shown below:
![viteConfig](https://github.com/user-attachments/assets/4b1452da-cff8-4ae0-9e49-803dd820bdae)

My .css file is shown below:
![indexCss](https://github.com/user-attachments/assets/9beab480-d143-4206-8e7e-86b898395216)

**Comment by wongjn** [comment]
Could you provide an example project that reproduces the issue please?

**Reply by MattLysinger** [reply]
I am working on reproducing the issue in a example project but when i made a duplicate project (same dependencies but all the unnecessary files removed) to share i am not getting the issue. I will try to share a example project that reproduces the issue as soon as i can reproduce it outside of my "main" project.

**Comment by muhammad-fiaz** [comment]
according to error message i think its due to postcss if the project uses vite try removing the postcss.config file in your project root if it found refer: [vite-installation instruction](https://tailwindcss.com/docs/installation/using-vite)

**Reply by MattLysinger** [reply]
I do not have the postcss.config file - when i upgraded to v4 i removed it.

**Reply by wongjn** [reply]
Could you provide an example project that reproduces the issue please? It may help in debugging the issue.

**Comment by MattLysinger** [comment]
Found the problem after debugging this for 5 hours. I had the following text as a class -> `[&amp;>span]:group-last:transition` <- this is what broke the `@tailwindcss/forms` plugin for me. Strange it did not break it in v3. This was some placeholder class i copied from a tailwind example months ago (through the browser dev tools) and forgot about. Would of been helpful if the error message told me what 'word' was causing the issue - could have saved me 5 hours.

**Comment by solutionsinurarea** [comment]
I'm running into this exact same issue. How did you manage to debug? The stack trace has absolutely 0 debuggable context for me as it doesn't even give me a proper snapshot of the part where the parser failed.

I feel like the tailwind upgrade docs are far too simple at the moment. With v3 tailwind would never cause loud runtime errors, any failures would be silent but still build. If it's going to fail, we need a debug path.

**Reply by wongjn** [reply]
Do you have a project we can look at please? We then might be able to help debug the issue.

**Reply by solutionsinurarea** [reply]
I don't right now since I can't expose the project I'm actually working on since it's on gitlab and not public. My suspicion at the moment is that the issue may be due to svelte's `class:` syntax it may be generating something the parser can't deal with but I'll have to create a repo myself and see if it's the case. Since I have no debug info to work with I'm not sure if that's where I should start. But my suggestion is that tailwind needs to take the lightningcss parser and show a window with the line/tokens where the parser failed or anytime something like this happens it will be impossible to find the issue in large code bases.

**Comment by MattLysinger** [comment]
I did a manual debug, meaning i made a copy of my project and started deleting code until the error stopped happening and kept doing that until i found the issue. Maybe there is a better way but that is how i did it. Yeah i was surprised that it caused my program to crash because i thought that classes that are not valid are ignored. Honestly i do not know what other way you could debug it. Because the error stops the css from compiling so you cannot look at the css, and the error message does not give you any information on where the error is in your code or what is causing the error.

**Reply by solutionsinurarea** [reply]
Thanks, unfortunately this codebase is 10s of thousands of lines and I'm not willing to do that :)

The issue is coming from the new vite plugin for sure, but it being a vite plugin means it can stop the whole code from working. I wonder if it can issue warnings for failures and keep parsing from the next component's class string instead?

**Reply by wongjn** [reply]
You could try attaching a JavaScript debugging breakpoint at the relevant stacktrace location(s) and see if any of the scopes' variables give you any clues.

**Reply by solutionsinurarea** [reply]
Thanks I'll try that in some of the entry points and see if it helps. But of course this will only help if my suspicion is true, not if the issue is in the css somewhere.

**Reply by wongjn** [reply]
I'd put the breakpoints on or near the locations of files in the error of the stack trace. For example, if we were to debug from the OP screenshot, I'd place a breakpoint at `node_modules/postcss/lib/input.js:109` and work backwards from there.

**Reply by solutionsinurarea** [reply]
Well the stacktrace is telling me where the issue is happening in the library, the parser. But I don't think putting a breakpoint in the parser will lessen my workload. I may just look and see if I can figure out a way to get lightningcss to say what tokens it failed on and potentially sumbit a PR.

**Comment by solutionsinurarea** [comment]
I've tried a few different approaches to debug this and none have worked. Since the error occurs so early in the build during pre-transform I can't get breakpoints to work or even see any output if I alter the postcss plugin file. I've never worked with vite plugins or lightningcss so I'm probably missing something but I don't have the time.

Also tried using the vite-plugin-inspector which didn't show me any output from the tailwindcss vite plugin at all once I disabled hmr to stop infinite hot reloads from failed transforms. Maybe because it exited after failing to parse.

Will have to wait for a future version of tailwind to upgrade when this problem is addressed. I think putting this validation logic as a vite plugin may be a mistake as it can break builds. Hope to be proven wrong.

**Reply by wongjn** [reply]
Do you have a project I can look at please? Perhaps even if you could send an invite privately? I then might be able to help debug the issue.

**Reply by solutionsinurarea** [reply]
Sorry, I can't due to licensing but I'm resolving the issues by temporarily switching over to `unocss` which has a fantastic debug path.

It's not a bug so I'm not opening an issue but here's the unocss output:
![2025-01-25-182728_hyprshot](https://github.com/user-attachments/assets/14ccff1c-23a9-45f6-87f3-b8a992630b2c)

And this is the cause of one of the issues:
```svelte
<script>
let width = $state(12);
const widthClass = $derived(`w-${width}`);
</script>

<div class:widthClass>...</div>
```

This is valid in svelte, but is transformed by svelte after the pre-process so it fails here, and in v3 tailwind would have failed anyway if width wasn't a commonly defined `w-` value. The solution is to do something like this instead:

```svelte
<script>
let width = $state(12);
</script>

<div class="w-(--width-val)" style:--width-val={width}>...</div>
```

Tailwind is still not happy/not building, but maybe it would be worth it for the tw team to look at uno's tooling.

**Reply by omid** [reply]
@wongjn we have this problem when we have a custom font, like:
```
@font-face {
    font-family: 'FONT';
    font-style: normal;
    font-weight: 100 900;
    font-display: swap;
   src: url(PATH/TO/FONT.woff2) format('woff2');
} 
```

**Reply by wongjn** [reply]
Consider providing a project that reproduces the unexpected behavior please.

**Reply by solutionsinurarea** [reply]
@wongjn I created a repo with issues I found all causing this error. You can checkout the v4 commit to see how each component in src/lib contains its own build-breaking issue.

https://github.com/solutionsinurarea/dbgtcss

**Reply by wongjn** [reply]
The error is caused by `src/lib/Counter.svelte`:

```ts
let count: number = $state(0);
const unparsable = $derived(`w-[${count}rem]`);
```

As per [the documentation](https://tailwindcss.com/docs/detecting-classes-in-source-files#dynamic-class-names):

> Since Tailwind scans your source files as plain text, it has no way of understanding string concatenation or interpolation in the programming language you're using.
> 
> **❌ Don't construct class names dynamically**
> 
> ```html
> <div class="text-{{ error ? 'red' : 'green' }}-600"></div>
> ```
> 
> In the example above, the strings `text-red-600` and `text-green-600` do not exist, so Tailwind will not generate those classes.
> 
> Instead, make sure any class names you’re using exist in full:
> 
> **✅ Always use complete class names**
> 
> ```html
> <div class="{{ error ? 'text-red-600' : 'text-green-600' }}"></div>
> ```
> 
> If you're using a component library like React or Vue, this means you shouldn't use props to dynamically construct classes:
> 
> **❌ Don't use props to build class names dynamically**
> 
> ```jsx
> function Button({ color, children }) {
>   return <button className={`bg-${color}-600 hover:bg-${color}-500 ...`}>{children}</button>;
> }
> ```

**Reply by solutionsinurarea** [reply]
@wongjn I'm aware of the error, I pointed it out myself in this thread. I made the repo so your team can improve the error message. UnknownWord with no context as to where to even find the 'unknown word' is terrible dx.

**Reply by solutionsinurarea** [reply]
@wongjn also (sorry if I'm spamming you) just want to make sure you saw the other two components. Each one has a different issue, and the other two are definitely unexpected cases where the parser should not fail. If they do fail, the tailwind docs should be updated with a warning.

**Reply by wongjn** [reply]
I'm not sure what you mean with the other two components. After removing the offending code from `Counter.svelte`, the project seems to compile with no errors.

**Reply by solutionsinurarea** [reply]
For me, on both windows and linux the following two classes also cause the `unknown word` build error in v4, while in v3 it correctly rendered the styles:
`[&::-webkit-inner-spin-button]:appearance-none`
`[&_li>*]:rounded-none`

The parser throws at both of these. Maybe you could try stopping and starting the server? In my testing the vite hmr server was inconsistent in reflecting the code changes on save.

**Reply by wongjn** [reply]
I did dev and build and both went through fine.

**Comment by grizhlieCodes** [comment]
Hi all, I had the same problem. I managed to get my build to work (Svelte 5, latest tailwind install in a new build)) by removing all classes that started with `[&` ...

The classes that caused the error:

```
        [&>:is(p,a,h1,h2,h3,h4,h5,h6)]:w-full
	[&>:is(p,a,h1,h2,h3,h4,h5,h6)]:max-w-[40rem]
	[&>:is(blockquote)]:max-w-[50rem] 
	[&[data-state='open']_>_*]:bg-lime-200
         [&[data-state='open']_>_*]:text-fuchsia-600
```

Once I removed ALL of them (not even 1 could remain, i tested this), the build worked. I honestly don't even remember writing them at this point. This worked with Tailwind 3.4 just fine, so I guess the way Tailwind is parsing is quite different..?

**Reply by solutionsinurarea** [reply]
@wongjn  Should we make this into an issue? Usually after a major release I would expect small patches to iron bugs out over the following days but I'm not seeing that here and I like tailwind and would want for progress to be made on this.

**Reply by screenfluent** [reply]
Thanks for sharing! It helped after 2 hours find the issue after losing almost all hair... find out that .html file I dropped into repo as reference has [& and started to break app.css compiling process. 🤯

**Comment by mychidarko** [comment]
I just run into the same issue but was unable to solve it by removing `[&`. I've tried removing all instances of `[[` and every `[` thing I could think about, but the "Unknown word" error still pops up without any proper info to trace the error

**Comment by intuitiveminds** [comment]
I also ran into this issue using the tailwind vite plugin (using v 4.0.4), I did not have any of the above mentioned classes (starting with brackets etc.) in my code. For now the only way to fix it was to revert back to the postcss plugin.

**Reply by wongjn** [reply]
Would you be able to provide a git repo that reproduces the issue please?

**Reply by intuitiveminds** [reply]
@wongjn I managed to strip down my project and created a sample repository, I sent you an invite

**Reply by wongjn** [reply]
Thank you. Seems to be the `after:content-['']` class tripping up PostCSS after Tailwind has done extra processing in build environment.

**Reply by intuitiveminds** [reply]
Do you think it is specific to this class or is there a general pattern that seems to throw PostCSS off the rails (e.g. a string in brackets in general or if the brackets are applied on certain breakpoints etc.)? From the comments above it seems there are a range of potentially different scenarios where the error takes place, so it would be nice to find a common root cause. Additionally it would help if PostCSS would provide more info as to _which_ word actually is unknown 😂

**Reply by wongjn** [reply]
I'll see if I can do some more digging and get back to you.

---
Trying to narrow down the issue. Still able to recreate the issue with:

Modified `main.css` to be:
```css
@import "tailwindcss/utilities.css";
```
Modified `index.vue` to:
```html
<script setup lang="ts">
const includedFeatures = ["Foo", "Bar", "Baz"];
</script>

<template>
  <main class="" lang="de">
    <div class="">
      <div class="">
        <div class="after:content-['']">
          <div class="">
            <img class="" src="" alt="" />
          </div>
        </div>
      </div>
    </div>
  </main>
</template>

<style scoped></style>
```
Removing the `<script>` or any element further causes the error to **not** occur.

The error occurs because this is in the CSS being passed to PostCSS:
```css
.after\\:content-\\[\\&\\#39\\;\\&\\#39\\;\\] {
  &::after {
    content: var(--tw-content);
    --tw-content: &#39;&#39;;
    content: var(--tw-content);
  }
}
```
Trying to understand why…

---

This module with `id = /path/to/project/pages/index.vue?macro=true&vue&type=script&setup=true&lang.ts` is scanned by Tailwind with the content:

```js
import { defineComponent as _defineComponent } from 'vue'
import { createElementVNode as _createElementVNode, createStaticVNode as _createStaticVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

const _hoisted_1 = {
  class: "",
  lang: "de"
}


export default /*@__PURE__*/_defineComponent({
  __name: 'index',
  setup(__props) {

const includedFeatures = ["Foo", "Bar", "Baz"];

return (_ctx: any,_cache: any) => {
  return (_openBlock(), _createElementBlock("main", _hoisted_1, _cache[0] || (_cache[0] = [
    _createStaticVNode("<div class=\\"\\"><div class=\\"\\"><div class=\\"after:content-[&#39;&#39;]\\"><div class=\\"\\"><img class=\\"\\" src=\\"\\" alt=\\"\\"></div></div></div></div>", 1)
  ])))
}
}

})
```
This has the apostrophes in the `after:content-['']` class encoded as `after:content-[&#39;&#39;]`, thus causing Tailwind to generate the rule mentioned before. The PostCSS parser then trips up on the ampersands, causing the unknown word error.

But why is this not a problem when we remove one div somewhere?

---

Because the generated code is different, that does not have the encoded HTML entities:

```js
import { defineComponent as _defineComponent } from 'vue'
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

const _hoisted_1 = {
  class: "",
  lang: "de"
}


export default /*@__PURE__*/_defineComponent({
  __name: 'index',
  setup(__props) {

const includedFeatures = ["Foo", "Bar", "Baz"];

return (_ctx: any,_cache: any) => {
  return (_openBlock(), _createElementBlock("main", _hoisted_1, _cache[0] || (_cache[0] = [
    _createElementVNode("div", { class: "" }, [
      _createElementVNode("div", { class: "after:content-['']" }, [
        _createElementVNode("div", { class: "" }, [
          _createElementVNode("img", {
            class: "",
            src: '',
            alt: ""
          })
        ])
      ])
    ], -1)
  ])))
}
}
```
And this difference happens with [a seemingly-arbitrary threshold of 5 elements in Vue's compiler](https://github.com/vuejs/core/blob/119f18c773b8d437fada3e0b8b847a282182c8dd/packages/compiler-dom/src/transforms/stringifyStatic.ts#L93-L106).

**Reply by wongjn** [reply]
Opened issue #16358

**Comment by dragonofmercy** [comment]
I have to same problem using @font-face with url definition inside one of my css file, the bug is present still v.4.0.9

```css
@font-face {
    font-family: 'Roboto';
    src: url("/vendor/dragonofmercy/gaia/src/Gui/resources/fonts/roboto-regular.woff") format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Roboto';
    src: url('/vendor/dragonofmercy/gaia/src/Gui/resources/fonts/roboto-bold.woff') format('woff');
    font-weight: bold;
    font-style: normal;
}

.font-roboto {
    font-family: 'Roboto', sans-serif;
}
```

```log
[vite] Internal server error: [postcss] C:/Users/dragon/Tailwind/build/resources/css/app.css:2931:15: Unknown word err.plugin
```

The error appear only if I use `npm run dev`, with `npm run build` there is no errors

**Reply by wongjn** [reply]
Consider providing a git repo that reproduces the unexpected behavior.

**Reply by HectorMF** [reply]
I have the same error, and only running in dev mode. The following causes the error:

@font-face {
  font-family: 'Geist Sans';
  src: url("../fonts/Geist-1.3.0/variable-woff/GeistVF.woff2") format('woff2'), url("../fonts/Geist-1.3.0/variable-woff/GeistVF.woff") format('woff');
}

**Reply by wongjn** [reply]
Consider providing a git repo that reproduces the unexpected behavior. We can then troubleshoot the issue for you.

**Comment by dantaylor** [comment]
FWIW I tried re-installing all npm packages (deleted node_modules folder and the node-package.lock file) and that worked for me. I was having the exact same error message mentioned here.  hope it helps someone.

**Comment by electrocnic** [comment]
I just want to note my wyld journey here, as I tried EVERYTHING (deleting node_modules, deleting all possible dist folders and cache folders) when I commented out a bad classname in my react ts code, and it still threw the error "unknown word".

After 1 hour it finally occurred to me, that the way how tailwind is performing its treeshaking and applying its classes to the build output, is by scanning the source code for css-looking strings.

And I verified that this also happens for commented-out strings.
Tailwind will generate something from custom classnames like `bg-[var(--my-bad-custom-classname)]` even when I used it like
```
// commented out on purpose as I wanted to try to find the error source:
// const bg = 'bg-[var(--my-bad-custom-classname)]'
return <div className=''>...</div>
```

When I renamed the commented-out classname, it still threw the same error.

**Comment by flihub** [comment]
found error. 

disable all background-image: url("data:image/svg+xml.... properties error gone.

```css
.form-checkbox {
    appearance: none;
    padding: 0;
    print-color-adjust: exact;
    display: inline-block;
    vertical-align: middle;
    background-origin: border-box;
    user-select: none;
    flex-shrink: 0;
    height: 1rem;
    width: 1rem;
    color: oklch(0.546 0.245 262.881);
    background-color: #fff;
    border-color: oklch(0.551 0.027 264.364);
    border-width: 1px;
    --tw-shadow: 0 0 #0000;
    border-radius: 0px;
    &:focus {
      outline: 2px solid transparent;
      outline-offset: 2px;
      --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
      --tw-ring-offset-width: 2px;
      --tw-ring-offset-color: #fff;
      --tw-ring-color: oklch(0.546 0.245 262.881);
      --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
      --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);
      box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
    }
    &:checked {
      border-color: transparent;
      background-color: currentColor;
      background-size: 100% 100%;
      background-position: center;
      background-repeat: no-repeat;
    }
    /* &:checked {
      background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e");
    } */
    &:checked:hover {
      border-color: transparent;
      background-color: currentColor;
    }
    &:checked:focus {
      border-color: transparent;
      background-color: currentColor;
    }
    &:indeterminate {
      /* background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 16 16'%3e%3cpath stroke='white' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M4 8h8'/%3e%3c/svg%3e"); */
      border-color: transparent;
      background-color: currentColor;
      background-size: 100% 100%;
      background-position: center;
      background-repeat: no-repeat;
    }
    &:indeterminate:hover {
      border-color: transparent;
      background-color: currentColor;
    }
    &:indeterminate:focus {
      border-color: transparent;
      background-color: currentColor;
    }
  }
  .form-radio {
    appearance: none;
    padding: 0;
    print-color-adjust: exact;
    display: inline-block;
    vertical-align: middle;
    background-origin: border-box;
    user-select: none;
    flex-shrink: 0;
    height: 1rem;
    width: 1rem;
    color: oklch(0.546 0.245 262.881);
    background-color: #fff;
    border-color: oklch(0.551 0.027 264.364);
    border-width: 1px;
    --tw-shadow: 0 0 #0000;
    border-radius: 100%;
    &:focus {
      outline: 2px solid transparent;
      outline-offset: 2px;
      --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
      --tw-ring-offset-width: 2px;
      --tw-ring-offset-color: #fff;
      --tw-ring-color: oklch(0.546 0.245 262.881);
      --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
      --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);
      box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
    }
    &:checked {
      border-color: transparent;
      background-color: currentColor;
      background-size: 100% 100%;
      background-position: center;
      background-repeat: no-repeat;
    }
    &:checked {
      /* background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3ccircle cx='8' cy='8' r='3'/%3e%3c/svg%3e"); */
    }
    &:checked:hover {
      border-color: transparent;
      background-color: currentColor;
    }
    &:checked:focus {
      border-color: transparent;
      background-color: currentColor;
    }
  }
  .form-input {
    appearance: none;
    background-color: #fff;
    border-color: oklch(0.551 0.027 264.364);
    border-width: 1px;
    border-radius: 0px;
    padding-top: 0.5rem;
    padding-right: 0.75rem;
    padding-bottom: 0.5rem;
    padding-left: 0.75rem;
    font-size: 1rem;
    line-height: 1.5rem;
    --tw-shadow: 0 0 #0000;
    &:focus {
      outline: 2px solid transparent;
      outline-offset: 2px;
      --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-color: oklch(0.546 0.245 262.881);
      --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
      --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color);
      box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
      border-color: oklch(0.546 0.245 262.881);
    }
    &::placeholder {
      color: oklch(0.551 0.027 264.364);
      opacity: 1;
    }
    &::-webkit-datetime-edit-fields-wrapper {
      padding: 0;
    }
    &::-webkit-date-and-time-value {
      min-height: 1.5em;
    }
    &::-webkit-date-and-time-value {
      text-align: inherit;
    }
    &::-webkit-datetime-edit {
      display: inline-flex;
    }
    &::-webkit-datetime-edit {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-year-field {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-month-field {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-day-field {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-hour-field {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-minute-field {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-second-field {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-millisecond-field {
      padding-top: 0;
      padding-bottom: 0;
    }
    &::-webkit-datetime-edit-meridiem-field {
      padding-top: 0;
      padding-bottom: 0;
    }
  }
  .form-select {
    appearance: none;
    background-color: #fff;
    border-color: oklch(0.551 0.027 264.364);
    border-width: 1px;
    border-radius: 0px;
    padding-top: 0.5rem;
    padding-right: 0.75rem;
    padding-bottom: 0.5rem;
    padding-left: 0.75rem;
    font-size: 1rem;
    line-height: 1.5rem;
    --tw-shadow: 0 0 #0000;
    &:focus {
      outline: 2px solid transparent;
      outline-offset: 2px;
      --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-color: oklch(0.546 0.245 262.881);
      --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
      --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color);
      box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
      border-color: oklch(0.546 0.245 262.881);
    }
    /* background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='oklch(0.551 0.027 264.364)' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e"); */
    background-position: right 0.5rem center;
    background-repeat: no-repeat;
    background-size: 1.5em 1.5em;
    padding-right: 2.5rem;
    print-color-adjust: exact;
    &:where([size]:not([size="1"])) {
      background-image: initial;
      background-position: initial;
      background-repeat: unset;
      background-size: initial;
      padding-right: 0.75rem;
      print-color-adjust: unset;
    }
  }
  .form-textarea {
    appearance: none;
    background-color: #fff;
    border-color: oklch(0.551 0.027 264.364);
    border-width: 1px;
    border-radius: 0px;
    padding-top: 0.5rem;
    padding-right: 0.75rem;
    padding-bottom: 0.5rem;
    padding-left: 0.75rem;
    font-size: 1rem;
    line-height: 1.5rem;
    --tw-shadow: 0 0 #0000;
    &:focus {
      outline: 2px solid transparent;
      outline-offset: 2px;
      --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-color: oklch(0.546 0.245 262.881);
      --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
      --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color);
      box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
      border-color: oklch(0.546 0.245 262.881);
    }
    &::placeholder {
      color: oklch(0.551 0.027 264.364);
      opacity: 1;
    }
  }
  
```
