### DISCUSSION TITLE
Tailwind v4 `@import "node_modules/package/file.css` breaks with relative path font url

### DISCUSSION THREAD

**Discussion by nunocasteleira** [tailwindlabs/tailwindcss#15824] [Help]
I have an application that I'm trying to migrate to v4.

I previously had

```css
@import "@some-package/styles/dist/css/styles-full.css";

@tailwind base;
@tailwind components;
@tailwind utilities;
```

that the CLI converted to

```css
@import "@some-package/styles/dist/css/styles-full.css" layer(base);

@import "tailwindcss";

@config '../../tailwind.config.ts';
```

On this file `styles-full.css`, I somewhere have

```css
/* file from node_modules "@some-package/styles/dist/css/styles-full.css" */

@font-face {
  font-display: swap;
  font-family: "CondensedPro-Medium";
  font-style: normal;
  font-weight: 500;
  src: local("Condensed Pro Med"), local("CondensedPro-Med"), url("../fonts/condensed-pro-medium.woff2") format("woff2"), url("../fonts/condensed-pro-medium.woff") format("woff");
}
```

And when I render the Next.js app, I get

```
Build Error
Next.js (15.1.3) out of date [(learn more)](https://nextjs.org/docs/messages/version-staleness)
Failed to compile

./src/app/globals.css:4:1
Module not found: Can't resolve '../fonts/condensed-pro-medium.woff2'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/globals.css
```

Can I fix this on my side? How can I point this "inline" import to the correct relative path for the node_module?

EDIT: Reproduction repository https://github.com/nunocasteleira/node-modules-font
