### DISCUSSION TITLE
[v4] missing block-start / block-end for margin and padding?

### DISCUSSION THREAD

**Discussion by Dodobrat** [tailwindlabs/tailwindcss#15854] [Ideas]
I am looking through the docs for the new v4 and was wondering why is there no utility for padding or margin block start / end.

I can see that the `my`, `py`, `space-y` utils use it, but there is only separate utils for padding and margin inline start / end: `ps`, `ms`, `pe` and `me`.

Wouldn't it be nice to have something like:
```css
.pb-start-<value>: { padding-block-start: <value> };
.pb-end-<value>: { padding-block-end: <value> };
.pi-start-<value>: { padding-inline-start: <value> };
.pi-end-<value>: { padding-inline-end: <value> };
```
or instead of the confusing `pb`:
```css
.p-bs-<value>: { padding-block-start: <value> };
.p-be-<value>: { padding-block-end: <value> };
.p-is-<value>: { padding-inline-start: <value> };
.p-ie-<value>: { padding-inline-end: <value> };
```
or even:
```css
.pbs-<value>: { padding-block-start: <value> };
.pbe-<value>: { padding-block-end: <value> };
.pis-<value>: { padding-inline-start: <value> };
.pie-<value>: { padding-inline-end: <value> };
```

It's not like I refuse to upgrade because of this, just a thought. 
Is it intentionally left out, are there plans to add it or if not, why wasn't it added in the first place.

Epic release though :)
