### DISCUSSION TITLE
How to align text right in table column using Tailwind Typography and Markdown parser?

### DISCUSSION THREAD

**Discussion by frank-laemmer** [tailwindlabs/tailwindcss#15863] [Help]
I have this markdown :

```md
| Category                | Share |
| ----------------------- | ----: |
| Maintenance             |   20% |
| Customer support        |   20% |
| Research & development  |   30% |
```

The colon character (:) will align text in the Share column right. I use Nuxt Content to render HTML. It looks like this:

```html
<td align="right">20%</td>
```

But in the browser it's aligned left. That is, as far as I see, because of this rule:

```css
.prose :where(th, td):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
  text-align: start;
}
```

I assume it's related to Tailwind Typography.

Now, if so, what's the best way to deal with this?
