### DISCUSSION TITLE
How to alias the new breakpoints using the old "screens" name in v4?

### DISCUSSION THREAD

**Discussion by mryechkin** [tailwindlabs/tailwindcss#15867] [Help] [answered]
I have a design token setup where tokens are defined in a separate CSS file generated by [Style Dictionary](https://styledictionary.com/), using CSS variables . All the names match the old (pre-v4) theme configuration naming conventions, ie. `theme.color` in Tailwind config maps to `--color`, `theme.screens` to `--screen`, etc.

Now that `screens` are called `breakpoints` in v4 configuration, is there a way to alias them using the old `screens` naming convention? I'd like to be able to continue using the same CSS variables, ie:
```css
@theme {
  --screen-sm: 768;
  --screen-md: 1024;
  --screen-lg: 1280;
}
```

It would be easy to set the selector to `@theme` in Style Dictionary, so that I could continue using the same source for my design tokens, and have Style Dictionary generate the new Tailwind v4 config.

I realize that I could this manually, ie:
```css
@import "tailwindcss";
@import ('my-tokens.css');

@theme {
  --breakpoint-sm: var(--screen-sm);
}
```

But I'm trying to avoid having to hand-roll a config file when Style Dictionary can do it for me automatically instead, and allow to retain the existing tokens. Is there a way to accomplish this in v4?
