### DISCUSSION TITLE
Creating light and dark mode background images

### DISCUSSION THREAD

**Discussion by timgavin** [tailwindlabs/tailwindcss#15865] [Help] [answered]
Using Tailwind v4.0. I would like to create dynamic background images and use the `bg-[]` class to display them. I can do random images with `style="background: url(light.jpg)"`, but this is hacky.

If that's not possible, then just assigning a light and dark background. Tried this but it didn't work.

```css
@theme {
    --bg-image-light: 'https://site.test/light.jpg';
    --bg-image-dark: 'https://site.test/dark.jpg';
}
```

So that I can do something like this
```html
<div class="bg-[url(var(--bg-image-light))] dark:bg-[url(var(--bg-image-dark))] bg-cover bg-center">
```

Any suggestions would be appreciated.

**Comment by wongjn** [comment, marked as answer]
You'd have the `url()` in the value in `@theme` like:

```css
@theme {
    --bg-image-light: url(https://site.test/light.jpg);
    --bg-image-dark: url(https://site.test/dark.jpg);
}
```
```html
<div class="bg-(image:--bg-image-light) dark:bg-(image:--bg-image-dark) bg-cover bg-center">
```
https://play.tailwindcss.com/CLhOIbPpQ4?file=css

You could even have these as "actual" values:
```css
@theme {
    --background-image-light: url(https://site.test/light.jpg);
    --background-image-dark: url(https://site.test/dark.jpg);
}
```
```html
<div class="bg-light dark:bg-dark bg-cover bg-center">
```
https://play.tailwindcss.com/oml8EopE38?file=css
