### DISCUSSION TITLE
Importing fonts via url('....') in config.css file no longer works in v4.0.0 but did work in the alpha. Is this expected?

### DISCUSSION THREAD

**Discussion by jamiecarter7** [tailwindlabs/tailwindcss#15862] [Help] [answered]
This code was working in the alpha versions:
```CSS
@import "tailwindcss";

@import url("https://fonts.googleapis.com/css?family=Kreon:300,400&display=swap");

@theme {
  --font-display: "Kreon";
}
```
But it no longer renders my fonts.

I am instead having to import as a <head> <link> stylesheet
This is working
```HTML
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Kreon:300,400&display=swap"
    />
```
Is this to be expected or is this a bug?

**Comment by wongjn** [comment, marked as answer]
So what is happening is as per [the MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/@import):

> An `@import` rule must be defined at the top of the stylesheet, before any other at-rule (except [@charset](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset) and [@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)) and style declarations, or it will be ignored.

So `@import "tailwindcss";` gets replaced inline with Tailwind-compiled CSS. This then leaves the font `@import` afterwards which - as per the above - causes the `@import` to be ignored.

You can work around this by placing your font `@import` before the Tailwind `@import`:

```css
@import url("https://fonts.googleapis.com/css?family=Kreon:300,400&display=swap");
@import "tailwindcss";

@theme {
  --font-display: "Kreon";
}
```
