### DISCUSSION TITLE
Custom @theme or @variant without a parent selector?

### DISCUSSION THREAD

**Discussion by anmoldovanov** [tailwindlabs/tailwindcss#15871] [Ideas]
Hi guys, is it possible to use `@variant` outside of a parent selector or create a custom `@theme`? For example, instead of writing:

```css
* {
  @variant theme-color-accent {
     --my-var: 1;
  }
}
```

I'd like to write it like this:

```css
@variant theme-color-accent {
   --my-var: 1;
}
```

to get this: 

```css
:where(:root, :host, [data-mz-accent], [data-mz-mode]) {
    --my-var: 1;
}
```

**Comment by wongjn** [comment]
You could write what you want as-is:
```css
:where(:root, :host, [data-mz-accent], [data-mz-mode]) {
    --my-var: 1;
}
```
