### DISCUSSION TITLE
[v4] Aliasing entire color sets

### DISCUSSION THREAD

**Discussion by CynicalBusiness** [tailwindlabs/tailwindcss#15938] [Help]
In v4, is it possible to alias/redefine an entire color set under a new name?

For example, if I wanted `color-green-*` to map to `color-emerald-*` for each value, how could this be done?

I've tried a few approaches but none quite seem to work.
```css
@theme inline {
  --color-green-*: var(--color-emerald-*);
  --color-green-*: value(--color-emerald-*);
  --color-green: value(--color-emerald);
  --color-green: var(--color-emerald);
  --color-green: --color-emerald;
}
```

It *does* work if I do the colors one-by-one, i.e. `--color-green-50: var(--color-emerald-50)`, but this takes quite a bit of time to set up and feels like the wrong way to do it.

A similar question was asked [back in November](https://github.com/tailwindlabs/tailwindcss/discussions/15101) where it was stated it wasn't yet possible, but some time has passed and at the very bottom of the [color docs](https://tailwindcss.com/docs/colors#default-color-palette-reference), it now says this:
> This can be useful if you want to reuse any of these scales but under a different name, like redefining `--color-gray-*` to use the `--color-slate-*` scale.

That verbiage from the docs implies there is *some* way to do it, but doesn't describe it in any further detail than that. Is it now possible, or not yet?
