### DISCUSSION TITLE
Cannot apply unknown utility class

### DISCUSSION THREAD

**Discussion by M0ggy24** [tailwindlabs/tailwindcss#15932] [Help]
it was updated by tailwindcss v4. 
But my code was occured error "Pre-transform error: Cannot apply unknown utility class: text-white".

how to solve it?
i rewrote this code.
in my old version: 
@layer components {
  .danger-button {
    @apply bg-red-500 text-white hover:bg-red-400 shadow-btn border rounded-md disabled:bg-red-400 transition-all;
  }
}
in v4 version: 
.success-button {
  @apply bg-success text-white hover:bg-[#40c88b] border border-success 
  disabled:bg-[#56836f] disabled:border-[#40c88b] hover:border-[#40c88b] transition-all;
}

**Comment by wongjn** [comment]
You might need to use [`@reference`](https://tailwindcss.com/docs/functions-and-directives#reference-directive).

---
As an aside, Adam Wathan (creator of Tailwind) does seem to advocate avoiding `@apply`:
- https://twitter.com/adamwathan/status/1226511611592085504
- https://twitter.com/adamwathan/status/1559250403547652097

**Reply by strokirk** [reply]
@wongjn do you have links to anything more current when Adam says that? That was 4 years ago (and Twitter links are not so easy to read anymore.)

**Reply by wongjn** [reply]
No, I don't have any links that are more current to hand.

**Reply by Baertie** [reply]
Hi

If Adam advocate avoiding @apply how should he/we do this
.success-button {
https://github.com/apply bg-success text-white hover:bg-[#40c88b] border border-success
disabled:bg-[#56836f] disabled:border-[#40c88b] hover:border-[#40c88b] transition-all;
}

Thanks in advance!

**Reply by wongjn** [reply]
```diff
-<div class="success-button">
+<div class="bg-success text-white hover:bg-[#40c88b] border border-success disabled:bg-[#56836f] disabled:border-[#40c88b] hover:border-[#40c88b] transition-all">
```
See https://x.com/adamwathan/status/1890404835888910467

**Reply by Baertie** [reply]
Okay everything inline is the way. But what if want to define some custom classes in a seperate css file. Like a group of classes that gets used in different components?

**Reply by wongjn** [reply]
You'd want to try to abstract those commonly-used classes to a component in your templating engine. If you *still* **really** want to create CSS, then:

```css
.success-button {
  background-color: var(--color-success);
  color: var(--color-white);
  border-width: 1px;
  border-color: var(--color-success);
  transition: all var(--tw-duration, var(--default-transition-duration)) var(--tw-ease, var(--default-transition-timing-function));

  &:hover {
    @media (hover: hover) {
      background-color: #40c88b;
      border-color: #40c88b;
    }
  }

  &[disabled] {
    background-color: #56836f;
    border-color: #40c88b;
  }
}
```
