### DISCUSSION TITLE
PostCSS Calc doesn't understand infinity

### DISCUSSION THREAD

**Discussion by JalenWasHere** [tailwindlabs/tailwindcss#15936] [Help] [answered]
The [postcss-calc](https://github.com/postcss/postcss-calc) library does not (yet) understand the `infinity` keyword. There is [an issue](https://github.com/postcss/postcss-calc/issues/210) for it in that repository that has been open since last year. This is not really a "Tailwind" problem yet it does block me from upgrading to v4.

The `rounded-full` utility is what causes this:

```css
  .rounded-full {
    border-radius: calc(infinity * 1px);
  }
```

I believe the old value was `9999px` so what I tried was to override the utility to use the old value:

```css
@utility rounded-full {
  border-radius: 9999px;
}
```

However when inspecting the compiled Tailwind CSS the `rounded-full` is not overridden instead both rules are added like such:

```css
  .rounded-full {
    border-radius: calc(infinity * 1px);
  }
  .rounded-full {
    border-radius: 9999px;
  }
```

With my utility being later in the CSS order it does take specificity however the PostCSS Calc still cant parse the file because `infinity` is still there.

Any one got an idea on how to fix this? I tried changing every `rounded-full` to `rounded-[9999px]` but I use Flowbite and it also uses this utility.
