### DISCUSSION TITLE
Issues with Intellisense after upgrading to Tailwind V4

### DISCUSSION THREAD

**Discussion by Plovst** [tailwindlabs/tailwindcss#15959] [Help]
I'm having an issue with Intellisense no longer working after upgrading to V4. I can see others have issues with this, since the tailwind.config.js is no longer mandatory. In this case I'm still using it though, since it's a Wordpress setup and I'm using values from theme.json in my config.

Amongst other things, I've tried manually pointing to the config file like this, but it doesn't work:
```
  "tailwindCSS.experimental.configFile": "./tailwind/tailwind.config.js",
``` 

My tailwind.config.js looks like this:
```javascript
/** @type {import('tailwindcss').Config} */
const includePreflight = "editor" === process.env._TW_TARGET ? false : true;

const themeJSON = require("../superego/theme.json");

const extractColors = (themeJSON) => {
  const colors = {};
  if (themeJSON?.settings?.color?.palette) {
    themeJSON.settings.color.palette.forEach((color) => {
      colors[color.slug] = color.color;
    });
  }
  return colors;
};

const colors = extractColors(themeJSON);

const fontFamilies = themeJSON.settings.typography.fontFamilies.reduce(
  (acc, font) => {
    acc[font.slug] = font.fontFamily;
    return acc;
  },
  {}
);

const fontSizes = themeJSON.settings.typography.fontSizes.reduce(
  (acc, size) => {
    acc[size.slug] = size.size;
    return acc;
  },
  {}
);

const lineHeights = themeJSON?.custom?.["line-height"] || {
  body: 1.3, // default values
  heading: 1.15, // default values
};

module.exports = {
  important: false,
  content: ["./superego/**/*.php", "./superego/theme.json"],
  theme: {
    extend: {
      fontFamily: {
        ...fontFamilies,
      },
      fontSize: {
        ...fontSizes,
      },
      colors,
      lineHeight: {
        body: lineHeights.body,
        heading: lineHeights.heading,
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1200px",
      xxl: "1600px",
      // qhd: "2000px",
    },
  },
  corePlugins: {
    // Disable Preflight base styles in CSS targeting the editor.
    preflight: includePreflight,
  },
  plugins: [
    // require("@_tw/themejson"),
    require("../superego/theme.json"),
    require("@tailwindcss/typography"),
    //require('@tailwindcss/forms'),
    require("@tailwindcss/line-clamp"),
    require("@tailwindcss/aspect-ratio"),

    function ({ addComponents, theme }) {
      addComponents({
        ".container": {
          maxWidth: "100%",
          padding: "0 1.5rem",
          marginLeft: "auto",
          marginRight: "auto",
          "@screen sm": {
            maxWidth: "640px",
          },
          "@screen md": {
            maxWidth: "768px",
          },
          "@screen lg": {
            maxWidth: "1024px",
            padding: "0 2rem",
          },
          "@screen xl": {
            maxWidth: "1200px",
          },
          "@screen xxl": {
            maxWidth: "1600px",
          },
          // "@screen qhd": {
          //   maxWidth: "1600px",
          // },
        },
        ".container-fluid": {
          maxWidth: "100%",
          padding: "0 1.5rem",
          marginLeft: "auto",
          marginRight: "auto",
          "@screen sm": {
            // maxWidth: "640px",
          },
          "@screen md": {
            // maxWidth: "768px",
          },
          "@screen lg": {
            // maxWidth: "100vw",
            padding: "0 2rem",
          },
          // "@screen xxl": {
          //   padding: "0",
          // },
        },
        ".text-h1": {
          fontSize: theme("fontSize.h1"),
          lineHeight: theme("lineHeight.heading"),
        },
        ".text-h2": {
          fontSize: theme("fontSize.h2"),
          lineHeight: theme("lineHeight.heading"),
        },
        ".text-h3": {
          fontSize: theme("fontSize.h3"),
          lineHeight: theme("lineHeight.heading"),
        },
        ".text-h4": {
          fontSize: theme("fontSize.h4"),
          lineHeight: theme("lineHeight.heading"),
        },
        ".text-h5": {
          fontSize: theme("fontSize.h5"),
          lineHeight: theme("lineHeight.heading"),
        },
        ".text-h6": {
          fontSize: theme("fontSize.h6"),
          lineHeight: theme("lineHeight.heading"),
        },
      });
    },
  ],
};
``` 

Tailwind.css looks like this:
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

@layer base {
  h1 {
    @apply text-h1;
  }

  h2 {
    @apply text-h2;
  }

  h3 {
    @apply text-h3;
  }

  h4 {
    @apply text-h5 lg:text-h4;
  }

  h5 {
    @apply text-h5;
  }

  h6 {
    @apply text-lg;
  }

  ::selection {
    background: theme(colors.accent-b);
    color: theme(colors.white);
  }

  /* Admin styling */
  .block-editor-block-list__layout {
    @apply mt-8 prose-lg text-gray-900;
  }

  .block-editor-block-list__layout .block-editor-block-list__block {
    max-width: 1480px;
  }

  .block-editor-block-list__layout .swiper-wrapper {
    display: flex;
    gap: 1rem;
  }

  .block-editor-block-list__layout .swiper-slide {
    min-width: 50%;
  }

  .block-editor-block-list__layout .isotope {
    @apply grid grid-cols-2 gap-8;
  }

  .block-editor-block-list__layout img {
    opacity: 100% !important;
  }
}
``` 

Any obvious errors I'm not seeing?
