### DISCUSSION TITLE
How can I pass parameters to a TailwindCSS plugin in a CSS-first configuration?

### DISCUSSION THREAD

**Discussion by rozsazoltan** [tailwindlabs/tailwindcss#15997] [Help] [answered]
* Source: [How can I pass parameters to a TailwindCSS plugin in a CSS-first configuration?](https://stackoverflow.com/q/79396301/15167500) - StackOverflow
* Similar: [[v4] How to add plugins?](https://github.com/tailwindlabs/tailwindcss/discussions/13292#discussioncomment-11367789) - GitHub

Starting from TailwindCSS v4, it supports the CSS-first configuration. Based on that, I would like to create a plugin that accepts, for example, a single parameter, true/false. How can I then invoke this plugin in a project and pass the value of this parameter as true/false?

```js
import plugin from 'tailwindcss/plugin'

export const myPluginName = (
  custom: boolean,
) => {
  return plugin(
    ({ addUtilities, theme }) => {
      // ...
    },
  )
}
```

If I understand correctly, the plugin creation process remains the same. So, in a CSS-first configuration, I should still be able to pass parameters, right?

```css
@import "tailwindcss";

@plugin "myPluginName";
```

The documentation isn't very verbose when it comes to the search term "plugin".

> Use the @plugin directive to load a legacy JavaScript-based plugin:
> ```css
> @plugin "@tailwindcss/typography";
> ```
> The @plugin directive accepts either a package name or a local path.

* [`@plugin` directive](https://tailwindcss.com/docs/functions-and-directives#plugin-directive)

**Comment by philipp-spiess** [comment, marked as answer]
@rozsazoltan We're going to add this to the docs too but take a look at this PR for an overview: https://github.com/tailwindlabs/tailwindcss/pull/14264

**Reply by rozsazoltan** [reply]
Thank you for the quick reply!

I'll extract the key point from the PR here:

> ```css
> @plugin "@tailwindcss/forms" {
>   strategy: base;
> }
> ```
> 
> For example, in the following plugin definition, the options that are passed to the plugin will be the correct types:
> 
> * `debug` will be the boolean value `true`
> * `threshold` will be the number `0.5`
> * `message` will be the string `"Hello world"`
> * `features` will be the array `["base", "responsive"]`
> ```
> @plugin "my-plugin" {
>   debug: false;
>   threshold: 0.5;
>   message: Hello world;
>   features: base, responsive;
> }
> ```

Example for all types: 

```css
@plugin "my-plugin" {
  is-null: null;
  is-true: true;
  is-false: false;
  is-int: 1234567;
  is-float: 1.35;
  is-sci: 1.35e-5;
  is-str-null: 'null';
  is-str-true: 'true';
  is-str-false: 'false';
  is-str-int: '1234567';
  is-str-float: '1.35';
  is-str-sci: '1.35e-5';
  is-arr: foo, bar;
  is-arr-mixed: null, true, false, 1234567, 1.35, foo, 'bar', 'true';
}     
```

* Copy: [How can I pass parameters to a TailwindCSS plugin in a CSS-first configuration?](https://stackoverflow.com/a/79396352/15167500)
