### DISCUSSION TITLE
Using @layer base { border-color } is not working for TailwindCSS ver 4

### DISCUSSION THREAD

**Discussion by titanve** [tailwindlabs/tailwindcss#16002] [Help]
**What version of Tailwind CSS are you using?**

v4.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.5.1, webpack 5.28.0

**What version of Node.js are you using?**

v20.18.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

After migrating TailwindCSS to ver 4 the borders has a black color and they were previosly gray, I'm trying this fix that you put in the website but it doesn't work (https://v3.tailwindcss.com/docs/v4-beta#default-border-color-change)

Is there any other workaround in order to fix the border color back to gray?

This is the proposed fix:
```css
@import "tailwindcss";

@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}
```

Thanks.

**Comment by RobinMalfait** [comment]
Hey!

Can you share a minimal reproduction repo and link it here?

That proposed fix seems to work as expected to me:

1. Without fix — https://play.tailwindcss.com/0mHcNpU1qd?file=css
2. With fix — https://play.tailwindcss.com/DBIDBNZvrN?file=css

**Comment by titanve** [comment]
Hi @RobinMalfait 
The problem is that all the setup is in the app for the company I work for. 

Here is the files tree view and the place I'm putting the code in:
![image](https://github.com/user-attachments/assets/00d59f72-c3f4-43ec-9d19-a80383af1adf)
![image](https://github.com/user-attachments/assets/86c99024-4fef-4edd-9e12-334b16966b9a)

Thanks.

**Comment by titanve** [comment]
Do I have to define `--color-gray-200` somewhere?
Thanks.

**Reply by RobinMalfait** [reply]
The `--color-gray-200` is coming from the default theme defined by `@import "tailwindcss";`. If you can create a minimal reproduction repo and attach it here that would be useful.

**Reply by titanve** [reply]
@RobinMalfait I think that because I am importing a legacy tailwindcss JS config file the `--color-gray-200` was not defined by default when importing `@import "tailwindcss";`, so by doing this I could fix the issue with the default border color:
```css
@import "tailwindcss";

@theme {
  --color-gray-200: #DDDDDD;
}

@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
  h1 {
    @apply text-2xl;
  }
  h2 {
    @apply text-xl;
  }
  h3 {
    @apply text-lg;
  }
}
```
Thanks.

**Comment by titanve** [comment]
@RobinMalfait 
This is how I load with postcss:
![image](https://github.com/user-attachments/assets/2ac1f2fd-c8dc-47ba-8d83-946d8a5559d1)

**Reply by RobinMalfait** [reply]
If you want to use a `tailwind.config.js` file, you have to add it to your CSS using `@config "tailwind.config.js";`.

More info: https://tailwindcss.com/docs/functions-and-directives#config-directive

**Reply by titanve** [reply]
@RobinMalfait 
I have added it here:
![image](https://github.com/user-attachments/assets/9b7c9262-4a3a-40e4-aed7-987a1223a592)

I am importing the config file after I import all the `*.scss` files (including `_base.scss` which has the `@import "tailwindcss";`)

Should I add the config file before?

**Comment by titanve** [comment]
@RobinMalfait 
If I do this the issue gets fixed, but I am not sure if that is the right fix:
```css
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    @apply border-gray-200;
  }
```

So I'm guessing I'm not getting the `default theme` because I have a JS Tailwind config file? Am I wrong?

Do I have to define `@theme` before `@layer base { ... }`?

Thanks.

**Reply by Laubeee** [reply]
the `@layer base` part gave me a hard time with my custom utility classes being overwritten when using `border-sidebar-foreground` or similar.

I ended up changing it to the tailwind-base.components layer to resolve specificity issues.
```css
@layer tailwind-base {
  @import 'tailwindcss';
}

/*
  The default border color has changed to `currentcolor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer tailwind-base.components {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentcolor);
  }
}
```
