### DISCUSSION TITLE
Better @utility ergonomics

### DISCUSSION THREAD

**Discussion by kerryj89** [tailwindlabs/tailwindcss#16032] [Ideas]
Instead of

```css
/* prettier-ignore */
@utility border-* {
    border-width: --value(--border-width-*);
}

/* prettier-ignore */
@utility border-t-* {
    border-top-width: --value(--border-width-*);
}

/* prettier-ignore */
@utility border-r-* {
    border-right-width: --value(--border-width-*);
}

/* prettier-ignore */
@utility border-b-* {
    border-bottom-width: --value(--border-width-*);
}

/* prettier-ignore */
@utility border-l-* {
    border-left-width: --value(--border-width-*);
}

/* prettier-ignore */
@utility border-x-* {
    border-inline-width: --value(--border-width-*);
}

/* prettier-ignore */
@utility border-y-* {
    border-block-width: --value(--border-width-*);
}
```

Allow like this

```css
/* prettier-ignore */
@utility {
    border-* {
        border-width: --value(--border-width-*);
    }

    border-t-* {
        border-top-width: --value(--border-width-*);
    }
    
    border-r-* {
        border-right-width: --value(--border-width-*);
    }
    
    border-b-* {
        border-bottom-width: --value(--border-width-*);
    }
    
    border-l-* {
        border-left-width: --value(--border-width-*);
    }
    
    border-x-* {
        border-inline-width: --value(--border-width-*);
    }

    border-y-* {
        border-block-width: --value(--border-width-*);
    }
}
```
