### DISCUSSION TITLE
viewport units on mobile

### DISCUSSION THREAD

**Discussion by alonronin** [tailwindlabs/tailwindcss#1610] [Help] [answered]
There is a problem with `vh` unit in chrome mobile browser:

![image](https://user-images.githubusercontent.com/846044/80125024-c207c100-8599-11ea-829d-306ac963ce48.png)

See Css Trick Article on this:  
https://css-tricks.com/the-trick-to-viewport-units-on-mobile/

Is there any way to fix it but to use `h-full` all over the place 😄?

**Comment by alonronin** [comment]
I cane across this https://dev.to/peiche/100vh-behavior-on-chrome-2hm8.

He suggest to use `@supports` in conjunction with a Chrome-specific browser hack:

```css
.h-screen {
  @supports (-webkit-appearance:none) {
    .os-android & {
      min-height: calc(100vh - 56px);
    }
  }
}
```
