### DISCUSSION TITLE
[v4] @theme variables modified with @media

### DISCUSSION THREAD

**Discussion by mikededo** [tailwindlabs/tailwindcss#16124] [Help] [answered]
Hey, I have defined CSS variables like the following example, however the changed value due to the media constraint does not apply:

```css
@theme {
  --width-something: 48px;
}

@media (width >= theme(--breakpoints-md)) {
  @theme {
    --width-something: 96px;
  }
}
```

I'm not entirely sure on how to modify the variables with breakpoints, in v4, so could be that the example is not entirely correct. I've also tried using `@layer theme` but does not work either. I couldn't find anything similar in the documentation.

**Comment by wongjn** [comment, marked as answer]
```css
@theme {
  --width-something: 48px;
}

@layer theme {
  :root {
    @variant md {
      --width-something: 96px;
    }
  }
}
```
https://play.tailwindcss.com/VcXoUmnQSx?file=css
