### DISCUSSION TITLE
v4: how to set up design restrictions

### DISCUSSION THREAD

**Discussion by vladdu** [tailwindlabs/tailwindcss#16134] [Help] [answered]
Hi! I am migrating some sites, and it feels good to work with v4, but there is something that is bothering me. I have a feeling I read something about this issue somewhere, but can't remember where. So, sorry if it's already been discussed.

One of the things I appreciated most in v3 is that it was easy to setup a design system where only certain values are available and rely on other values to simply not exist or to be clearly marked with brackets. This is no longer the case in v4, values can be dynamic and the brackets are gone. 

What would be a good way to reintroduce a less flexible system on a project, using vanilla Tailwind? I could go to DaisyUI or similar, but for internal reasons I'd prefer to stay plain if possible.

**Comment by wongjn** [comment]
You should be able to remove default theme values. To remove all and start from scatch:
```css
@theme {
  --*: intial;
}
```
To only remove some values within a namespace:
```css
@theme {
  --color-*: initial;
  --spacing: initial;
}
```

**Reply by vladdu** [reply]
Thanks, but I think I am misunderstanding. I want to only be able to have for example p-4, p-8 and p-12, all other p-* should be undefined classes. p-[7] or whatever would work, but not p-7. So it's clear what values are within the system, and which ones are wild.

**Reply by wongjn** [reply, marked as answer]
Yep, so you'd do:
```css
@theme {
  --spacing: initial;
  --spacing-4: …;
  --spacing-8: …;
  --spacing-12: …;
}
```
