### DISCUSSION TITLE
Does Tailwind CSS v4 Still Use tailwind.config.js? (React + TypeScript + Vite)

### DISCUSSION THREAD

**Discussion by cris-m** [tailwindlabs/tailwindcss#16152] [Help] [answered]
I'm using Tailwind CSS v4 in a React + TypeScript + Vite project, and it seems like my `tailwind.config.js` (or `tailwind.config.ts`) file is not being recognized.  

Here is my `tailwind.config.js`:  

```js
export default {
    darkMode: 'class',
    content: [
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: 'var(--background)',
                foreground: 'var(--foreground)',
                primary: {
                    DEFAULT: 'var(--primary)',
                    foreground: 'var(--primary-foreground)'
                },
                secondary: {
                    DEFAULT: 'var(--secondary)',
                    foreground: 'var(--secondary-foreground)'
                },
                card: 'var(--card)',
                accent: 'var(--accent)',
                dark: {
                    primary: 'var(--primary)',
                    secondary: 'var(--secondary)'
                }
            },
            backgroundColor: {
                primary: 'var(--primary)',
                secondary: 'var(--secondary)',
                dark: {
                    primary: 'var(--primary)',
                    secondary: 'var(--secondary)',
                },
            },
            textColor: {
                primary: 'var(--primary)',
                secondary: 'var(--secondary)',
                dark: {
                    primary: 'var(--primary)',
                    secondary: 'var(--secondary)',
                },
            },
            fontFamily: {
                'roboto': ['Roboto', 'sans-serif'],
                'source-han-sans': ['SourceHanSans', 'sans-serif'],
            },
        },
    },
    plugins: [],
};
```

here is my `css`:

```css
@import "./fonts";
@import "tailwindcss";

@layer base {
    :root {
        --background: white;
        --foreground: 222.2 84% 4.9%;
        --primary: 221.2 83.2% 53.3%;
        --primary-foreground: 210 40% 98%;
        --secondary: 210 40% 96.1%;
        --secondary-foreground: 222.2 47.4% 11.2%;
        --card: 0 0% 100%;
        --accent: 210 40% 96.1%;
    }

    html.dark {
        --background: black;
        --foreground: 210 40% 98%;
        --primary: 217.2 91.2% 59.8%;
        --primary-foreground: 222.2 47.4% 11.2%;
        --secondary: 217.2 32.6% 17.5%;
        --secondary-foreground: 210 40% 98%;
        --card: 222.2 84% 4.9%;
        --accent: 217.2 32.6% 17.5%;
    }
}
```

However, none of the custom configurations (colors, fonts, etc.) are being applied.  

Some questions:  
1. Does Tailwind CSS v4 still use a configuration file like `tailwind.config.js`?  
2. If so, is there anything specific that has changed in v4 that might cause this issue?  
3. Are there any additional steps required for Vite to properly recognize the config file?  

Any help would be greatly appreciated! Thanks in advance.
