### DISCUSSION TITLE
media query not work properly with theme variables

### DISCUSSION THREAD

**Discussion by Yang-Yus** [tailwindlabs/tailwindcss#16207] [Help]
**What version of Tailwind CSS are you using?**

4.0.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite

**What version of Node.js are you using?**

20.12.2

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/aYjkwS7Og5

**Describe your issue**

```
@theme {
  --color-rose-500: #FFC8EF;
  --breakpoint-sm: 40rem;
}

 /* min-width: var(--breakpoint-sm) NOT WORKING */
 .container{
  @media all and (min-width: var(--breakpoint-sm)) {
    padding-left: 100px;
    padding-right: 100px;
  }
}
```

**Comment by wongjn** [comment]
The is due to a limitation in CSS whereby CSS variables cannot be used within media queries.

As a work-around, you could consider:
- Using `@variant` like:
  ```css
  .container {
    @variant sm {
      padding-left: 100px;
      padding-right: 100px;
    }
  }
  ```
- Using `theme()` like:
  ```css
  .container {
    @media all and (min-width: theme(--breakpoint-sm)) {
      padding-left: 100px;
      padding-right: 100px;
    }
  }
  ```

**Reply by Yang-Yus** [reply]
got it, `theme()` works as expected! thanks!

**Comment by arthurlbrjc** [comment]
I have the same issue, `theme()` or `@variant` work-arounds are not working either.

- Working for reference
```css
@media screen and (min-width: 620px) {
  .container {
    width: 10vw;
  }
}
```

- Not working
```css
@media screen and (min-width: theme(--breakpoint-sm)) {
  .container {
    width: 10vw;
  }
}
```

- Not working : `Cannot use @variant with unknown variant: sm` during build
```css
@variant sm {
  .container {
    width: 10vw;
  }
}
```

- Not working : `Cannot use @variant with unknown variant: custom` during build
```css
@custom-variant custom (@media (min-width: 620px));
```
```css
@variant custom {
  .container {
    width: 10vw;
  }
}
```
