### DISCUSSION TITLE
Overriding an css variable on tailwind v4

### DISCUSSION THREAD

**Discussion by yoann54** [tailwindlabs/tailwindcss#16232] [Help] [answered]
I try to ovveride the  --tw-prose-links variable that is set by the  @tailwindcss/typography plugin, i tried to override it in @theme {} but it doesn't work. Is there a good way to do that ?

**Comment by wongjn** [comment, marked as answer]
You could use `@utility` like:

```css
@utility prose {
  --tw-prose-links: …;
}
```

**Reply by yoann54** [reply]
thanks for your answer, works perfectly.

**Comment by kevinmu17** [comment]
This solution stopped working, it doesn't take precedence over the base typography setup. I don't now what changed here, but this should be the case if you setup your .css file like
```css
@plugin "@tailwindcss/typography";
@utility prose {
    --tw-prose-body: var(--color-primary);
}
```

I would expect that my body color now honors --color-primary... (note, this worked before, versions: "@tailwindcss/typography": "^0.5.16", "tailwindcss": "^4.1.11")

**Reply by kevinmu17** [reply]
Oh, after some more debugging ( my case is more extended here )

```css
@plugin "@tailwindcss/typography";
@utility prose {
    --tw-prose-body: var(--color-primary);
    & ul.checkmark {
        li {
            @apply relative pt-2;
        }
    }
}
```
The @apply rule here breaks everything, so if you expierience the @utility isn't working this may be a case for you :)
