### DISCUSSION TITLE
Get rid of the default line-height in `text-*` classes

### DISCUSSION THREAD

**Discussion by stijns96** [tailwindlabs/tailwindcss#16231] [Ideas]
Within our team, we really dislike it that the `text-*` classes automatically comes with line-height properties. Can we somehow disable this without the need to fully disable all `text-*` classes and rewrite them? We now fix it like this:

```css
@theme {
  --text-*: initial;
  --text-2xs: 0.625rem;
  --text-xs: 0.75rem;
  --text-sm: 0.875rem;
  --text-base: 1rem;
  --text-lg: 1.125rem;
  --text-xl: 1.25rem;
  --text-2xl: 1.5rem;
  --text-3xl: 1.875rem;
  --text-4xl: 2.25rem;
  --text-5xl: 3rem;
  --text-6xl: 3.75rem;
  --text-7xl: 4.5rem;
  --text-8xl: 6rem;
  --text-9xl: 8rem;
}
```

Proposal:

```css
@theme {
    --text-*--line-height: initial;
}
```

Something like `--text-xs--line-height: initial;` is actually already working, but I want to disable it for all utils at ones
