### DISCUSSION TITLE
How to set default colour shade in v4?

### DISCUSSION THREAD

**Discussion by jovrtn** [tailwindlabs/tailwindcss#16258] [Help] [answered]
I'm curious if there's a way to set the default shade of a colour in v4. In v3 there's a `DEFAULT` property on colour definition objects in `tailwind.config`:

```
'tahiti': {
    light: '#67e8f9',
    DEFAULT: '#06b6d4',
    dark: '#0e7490',
},
```
https://v3.tailwindcss.com/docs/customizing-colors#color-object-syntax

**Comment by tahaListens** [comment]
following

**Comment by wongjn** [comment, marked as answer]
The v4 equivalent is:
```css
@theme {
  --color-tahiti-light: #67e8f9;
  --color-tahiti: #06b6d4;
  --color-tahiti-dark: #0e7490;
}
```
