### DISCUSSION TITLE
How to update CSS variable in @theme (light/dark etc)

### DISCUSSION THREAD

**Discussion by subproject22** [tailwindlabs/tailwindcss#16275] [Help] [answered]
I couldn't find any docs or guides. Let's say I have this

```
@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}
```

How to control variable value depending on something? I need to change `--foreground` outside theme config block?

**Comment by wongjn** [comment]
Update them like any CSS variable:

```css
@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}

@layer theme {
  [data-theme="dark] {
    --foreground: …;
  }
}
```

Or if the redefinition might not be on the `:root`/`:host` element:

```css
@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}

@layer theme {
  [data-theme="dark] {
    --foreground: …;
  }
}
```
