### DISCUSSION TITLE
[Feature Proposal] Auto-sized grid rows and columns with `grid-rows-*` and `grid-cols-*` utilities

### DISCUSSION THREAD

**Discussion by benface** [tailwindlabs/tailwindcss#1629] [Ideas]
I love the new Grid utilities, but I find myself needing to size individual rows or columns automatically based on their content very often, which doesn't seem possible with the default utilities. Both `grid-rows-*` and `grid-cols-*` use `minmax(0, 1fr)` for the size of the rows/columns, which means they are all the same size (based on the content of the largest row/column). This is a good default for traditional grid layouts (using `grid-cols-12` to emulate Bootstrap for instance), but I find it just as useful to be able to have differently sized columns. And for rows, actually I feel like more often than not you want each row to have its own height based on its own content. For these reasons it would be nice to have the exact same utilities with a size of `auto` instead of `minmax(0, 1fr)`. I have no idea what they could be called though; it almost feels like `grid-rows-4` should already work like that by default, but that would be a breaking change. So I'd suggest using custom properties to change the size of explicit rows/columns. For instance:

```css
.grid {
  --grid-row-size: minmax(0, 1fr);
}

.grid-row-size-auto {
  --grid-row-size: auto;
}

.grid-row-size-equal {
  --grid-row-size: minmax(0, 1fr);
}

.grid-rows-1 {
  grid-template-rows: repeat(1, --grid-row-size);
}

.grid-rows-2 {
  grid-template-rows: repeat(2, --grid-row-size);
}

/* ... */
```
