### DISCUSSION TITLE
Color switch with v4? Primary palette?

### DISCUSSION THREAD

**Discussion by subproject22** [tailwindlabs/tailwindcss#16290] [Help]
Can't figurate new config.

Let's say I want to have `--color-primary-*` styles, and I need to switch colors (between shipped Tailwind colors). Is it even possible? Weird but I can't figure out. Would be nice to have an example. The only way I found is having data-attr and **manually** defying **all** colors with attr selector...Is there more elegant way?

**Comment by wongjn** [comment]
The CSS variables defined in `@theme` become CSS variables. You can then override these CSS variables like you can in normal CSS:

```css
@theme {
  --color-primary: red;
}

@layer theme {
  [data-theme="dark"] {
    --color-primary: green;
  }
}
```
https://play.tailwindcss.com/P02BzXg7Yw
