### DISCUSSION TITLE
How can I change oklab in color-mix to use my own CSS variable?

### DISCUSSION THREAD

**Discussion by anmoldovanov** [tailwindlabs/tailwindcss#16319] [Help] [answered]
Hi, is there a way to replace oklab with var(--my-variable)?

**Comment by wongjn** [comment]
```css
@theme inline {
  --color-foo: var(--my-variable);
}
```
```html
<div class="bg-foo">
```
Produces:
```css
.bg-foo {
  background-color: var(--my-variable);
}
```
https://play.tailwindcss.com/ETfm6g4wBo

**Reply by anmoldovanov** [reply]
If I write:

```
bg-(--my-color)/10
```

I get:

```css
.bg-\(--my-color\)\/10 {
    background-color: color-mix(in oklab, var(--my-color) 10%, transparent);
}
```

How can I change oklab here?
