### DISCUSSION TITLE
share theme with variant

### DISCUSSION THREAD

**Discussion by unional** [tailwindlabs/tailwindcss#16313] [Help]
I create share themes to be used is dozens of MFEs, each defines their own prefix to avoid CSS load order conflicts.

The theme uses variants for dark color theme, for example.

I can do that in Tailwind v3, but in v4 there are 2 problems:

## `@custom-variant` cannot be nested

This mean I can't add it to the share theme to specify the common variant mechanisms.

## No theme mechanism to define variants

For example, I want the token `--color-primary` maps to `--color-red-800` in light theme and `--color-blue-800` in dark theme.

The solutions I found are:

[using class](https://play.tailwindcss.com/BQazSdAjHS?file=css)

```css

@custom-variant dark (&:where(.tw-dark, .tw-dark *));

@theme {
  --color-primary: theme(--color-gray-900);
}

.tw-dark {
  --tw-color-primary: theme(--color-blue-800);
}
```

[using data-*](https://play.tailwindcss.com/kvMrBELQkX?file=css)

```css
@import "tailwindcss" prefix(tw);

@custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));

@theme {
  --color-primary: theme(--color-red-800);
}

:root [data-theme="dark"] {
  --tw-color-primary: theme(--color-blue-800);
}
```

you can see that the `--tw-color-primary` and `.tw-dark` also make the them not sharable/portable.

Is there another way in Tailwind v4 that support this use case?

I have not only `@custom-variant dark` but also other variants, so the non-sharable part has a lot of definitions.

**Comment by wongjn** [comment]
Assuming I'm understanding you correctly and the `data-theme` or `tw-dark` is applied to `<html>`, you should be able to use `@variant` to use `@custom-variant` configuration:

```css
@layer theme {
  * {
    @variant dark {
      --color-primary: theme(--color-blue-200);
    }
  }
}
```
https://play.tailwindcss.com/SYEJ4bnAuH?file=css
https://play.tailwindcss.com/iaTkmh0O8Y?file=css

**Reply by unional** [reply]
Thanks, that's great. Thanks for your help here and on Discord.

However that doesn't work when prefix is involved.
You can see [here](https://play.tailwindcss.com/7u9dOQWA3C?file=css) that I have to use `--tw-color-primary` to get it to work:

```css
@layer theme {
  * {
    @variant dark {
      --tw-color-primary: theme(--color-blue-800);
    }
  }
}
```


Also, I noticed that when the CSS is built, it produces:

```css
@layer theme {
  @layer theme {
    * {
      &:where(.tw-dark, .tw-dark *) {
        &:where(.tw-dark, .tw-dark *) {
          --tw-color-primary: ...;
        }
      }
    }
  }
}
```

So the `@layer` and `&:where` are duplicated. Is that correct or it is a bug?
