### DISCUSSION TITLE
[v4] How to disable container?

### DISCUSSION THREAD

**Discussion by lihanspace** [tailwindlabs/tailwindcss#16323] [Help] [answered]
[v4] How to disable container?

In v3 there was a `corePlugins` option you could use to completely disable certain utilities in the framework. This is no longer supported in v4.

```cjs
/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    container: false,
  },
}
```

**Comment by wongjn** [comment]
No real way to disable it, you can only unset its properties:

```css
@utility container {
  max-width: unset;
  width: unset;
}
```
