### DISCUSSION TITLE
v4 causing build failure in vercel

### DISCUSSION THREAD

**Discussion by nahasco** [tailwindlabs/tailwindcss#16370] [Help]
`@import "tailwindcss";` is casuing the build of my Nextjs app to fail.

```
    at ScssParser.endFile (/vercel/path1/node_modules/next/node_modules/postcss/lib/parser.js:336:35)
    at ScssParser.parse (/vercel/path1/node_modules/next/node_modules/postcss/lib/parser.js:475:10)
    at scssParse (/vercel/path1/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:322)
    at new LazyResult (/vercel/path1/node_modules/next/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/vercel/path1/node_modules/next/node_modules/postcss/lib/processor.js:53:14)
    at CssMinimizerPlugin.optimizeAsset (/vercel/path1/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:48:12)
    at /vercel/path1/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:79:55
    at async Span.traceAsyncFn (/vercel/path1/node_modules/next/dist/trace/trace.js:153:20)
caused by plugins in Compilation.hooks.processAssets
CssSyntaxError: <css input>:2:88503: Unclosed block
    at Input.error (/vercel/path1/node_modules/next/node_modules/postcss/lib/input.js:93:16)
    at ScssParser.unclosedBlock (/vercel/path1/node_modules/next/node_modules/postcss/lib/parser.js:574:22)
    at ScssParser.endFile (/vercel/path1/node_modules/next/node_modules/postcss/lib/parser.js:336:35)
    at ScssParser.parse (/vercel/path1/node_modules/next/node_modules/postcss/lib/parser.js:475:10)
    at scssParse (/vercel/path1/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:322)
    at new LazyResult (/vercel/path1/node_modules/next/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/vercel/path1/node_modules/next/node_modules/postcss/lib/processor.js:53:14)
    at CssMinimizerPlugin.optimizeAsset (/vercel/path1/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:48:12)
    at /vercel/path1/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:79:55
    at async Span.traceAsyncFn (/vercel/path1/node_modules/next/dist/trace/trace.js:153:20)
> Build failed because of webpack errors
Error: Command "npm run build" exited with 1
```

After removing and adding blocks for hours it turns out the crash is caused by `@import "tailwindcss";`

I followed the docs to upgrade so I have no ideas whats the cause of this.

```
//postcss.config.mjs
const config = {
    plugins: {
        "@tailwindcss/postcss": {},
    },
}
export default config
```

```
// package.json
{
  "name": "tibian_frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbo",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "type": "tsc"
  },
  "dependencies": {
    "@heroicons/react": "^2.2.0",
    "@hey-api/openapi-ts": "^0.53.11",
    "@hookform/resolvers": "^3.10.0",
    "@internationalized/date": "^3.7.0",
    "@juggle/resize-observer": "^3.4.0",
    "@million/lint": "^1.0.14",
    "@radix-ui/react-accordion": "^1.2.3",
    "@radix-ui/react-alert-dialog": "^1.1.6",
    "@radix-ui/react-checkbox": "^1.1.4",
    "@radix-ui/react-collapsible": "^1.1.3",
    "@radix-ui/react-dialog": "^1.1.6",
    "@radix-ui/react-direction": "^1.1.0",
    "@radix-ui/react-dropdown-menu": "^2.1.6",
    "@radix-ui/react-hover-card": "^1.1.6",
    "@radix-ui/react-label": "^2.1.2",
    "@radix-ui/react-popover": "^1.1.6",
    "@radix-ui/react-scroll-area": "^1.2.3",
    "@radix-ui/react-select": "^2.1.6",
    "@radix-ui/react-slot": "^1.1.2",
    "@radix-ui/react-switch": "^1.1.3",
    "@radix-ui/react-tabs": "^1.1.3",
    "@radix-ui/react-toast": "^1.2.6",
    "@radix-ui/react-tooltip": "^1.1.8",
    "@radix-ui/react-use-escape-keydown": "^1.1.0",
    "@sentry/nextjs": "^8.54.0",
    "@stepperize/react": "^5.0.1",
    "@tailwindcss/postcss": "^4.0.4",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "cmdk": "^1.0.4",
    "date-fns": "^4.1.0",
    "eslint-config-next": "15.1.6",
    "holy-loader": "^2.3.13",
    "i": "^0.3.7",
    "i18next": "^24.2.2",
    "i18next-browser-languagedetector": "^8.0.2",
    "i18next-resources-to-backend": "^1.2.1",
    "js-cookie": "^3.0.5",
    "lucide-react": "^0.475.0",
    "motion": "^12.4.1",
    "next": "^15.1.6",
    "next-auth": "^5.0.0-beta.25",
    "next-themes": "^0.4.4",
    "npm": "^11.1.0",
    "npm-check-updates": "^17.1.14",
    "nuqs": "^2.3.2",
    "react": "^19.0.0",
    "react-aria-components": "^1.6.0",
    "react-day-picker": "^8.10.0",
    "react-dom": "19.0.0",
    "react-hook-form": "^7.54.2",
    "react-i18next": "^15.4.0",
    "react-phone-number-input": "^3.4.11",
    "react-responsive": "^10.0.0",
    "react-use-measure": "^2.1.7",
    "swr": "^2.3.2",
    "tailwind-merge": "^3.0.1",
    "tailwindcss-animate": "^1.0.7",
    "vaul": "^1.1.2",
    "zod": "^3.24.1",
    "zustand": "^5.0.3"
  },
  "devDependencies": {
    "@hookform/devtools": "^4.3.3",
    "@types/js-cookie": "^3.0.6",
    "@types/next-auth": "^3.15.0",
    "@types/node": "22.13.1",
    "@types/react": "19.0.8",
    "autoprefixer": "^10.4.20",
    "babel-plugin-react-compiler": "^19.0.0-beta-714736e-20250131",
    "encoding": "^0.1.13",
    "eslint-config-prettier": "^10.0.1",
    "eslint-plugin-prettier": "^5.2.3",
    "eslint-plugin-react-compiler": "^19.0.0-beta-714736e-20250131",
    "eslint-plugin-unused-imports": "^4.1.4",
    "postcss": "^8.5.1",
    "prettier": "^3.4.2",
    "sass": "^1.84.0",
    "tailwindcss": "^4.0.4",
    "typescript": "^5.7.3"
  },
  "overrides": {
    "@types/react": "19.0.8"
  }
}
```

```
//nextconfig.ts
import MillionLint from "@million/lint"
import type { NextConfig } from "next"
import { withSentryConfig } from "@sentry/nextjs"

const nextConfig: NextConfig = {
    reactStrictMode: true,
    experimental: {
        staleTimes: {
            dynamic: 30,
        },
        reactCompiler: true,
    },
}

// Apply MillionLint first
// const millionLintConfig = MillionLint.next({ rsc: true })(nextConfig)

// Then apply Sentry configuration
const sentryConfig = withSentryConfig(nextConfig, {
    // For all available options, see:
    // https://github.com/getsentry/sentry-webpack-plugin#options

    org: "tibian",
    project: "nextjs-tibian",

    // Only print logs for uploading source maps in CI
    silent: !process.env.CI,

    // For all available options, see:
    // https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/

    // Upload a larger set of source maps for prettier stack traces (increases build time)
    widenClientFileUpload: true,

    // Route browser requests to Sentry through a Next.js rewrite to circumvent ad-blockers.
    // This can increase your server load as well as your hosting bill.
    // Note: Check that the configured route will not match with your Next.js middleware, otherwise reporting of client-
    // side errors will fail.
    // tunnelRoute: "/monitoring",

    // Hides source maps from generated client bundles
    hideSourceMaps: true,

    // Automatically tree-shake Sentry logger statements to reduce bundle size
    disableLogger: false,

    // Enables automatic instrumentation of Vercel Cron Monitors. (Does not yet work with App Router route handlers.)
    // See the following for more information:
    // https://docs.sentry.io/product/crons/
    // https://vercel.com/docs/cron-jobs
    automaticVercelMonitors: true,
})

// Export the final configuration
export default sentryConfig
```

```
// globals.css
@import "tailwindcss";

@plugin 'tailwindcss-animate';

@custom-variant dark (&:is(.dark *));

@theme {
    --color-background: hsl(var(--background));
    --color-foreground: hsl(var(--foreground));

    --color-card: hsl(var(--card));
    --color-card-foreground: hsl(var(--card-foreground));

    --color-popover: hsl(var(--popover));
    --color-popover-foreground: hsl(var(--popover-foreground));

    --color-primary: hsl(var(--primary));
    --color-primary-foreground: hsl(var(--primary-foreground));

    --color-secondary: hsl(var(--secondary));
    --color-secondary-foreground: hsl(var(--secondary-foreground));

    --color-muted: hsl(var(--muted));
    --color-muted-foreground: hsl(var(--muted-foreground));

    --color-accent: hsl(var(--accent));
    --color-accent-foreground: hsl(var(--accent-foreground));

    --color-destructive: hsl(var(--destructive));
    --color-destructive-foreground: hsl(var(--destructive-foreground));

    --color-successful: hsl(var(--successful));
    --color-successful-foreground: hsl(var(--successful-foreground));

    --color-warning: hsl(var(--warning));
    --color-warning-foreground: hsl(var(--warning-foreground));

    --color-mainaccent: hsl(var(--mainaccent));
    --color-mainaccent-foreground: hsl(var(--mainaccent-foreground));
    --color-mainaccent-accent: hsl(var(--mainaccent-accent));

    --color-border: hsl(var(--border));
    --color-input: hsl(var(--input));
    --color-ring: hsl(var(--ring));

    --color-chart-1: hsl(var(--chart-1));
    --color-chart-2: hsl(var(--chart-2));
    --color-chart-3: hsl(var(--chart-3));
    --color-chart-4: hsl(var(--chart-4));
    --color-chart-5: hsl(var(--chart-5));

    --color-sidebar: hsl(var(--sidebar-background));
    --color-sidebar-foreground: hsl(var(--sidebar-foreground));
    --color-sidebar-primary: hsl(var(--sidebar-primary));
    --color-sidebar-primary-foreground: hsl(var(--sidebar-primary-foreground));
    --color-sidebar-accent: hsl(var(--sidebar-accent));
    --color-sidebar-accent-foreground: hsl(var(--sidebar-accent-foreground));
    --color-sidebar-border: hsl(var(--sidebar-border));
    --color-sidebar-ring: hsl(var(--sidebar-ring));

    --radius-lg: var(--radius);
    --radius-md: calc(var(--radius) - 2px);
    --radius-sm: calc(var(--radius) - 4px);

    --animate-accordion-down: accordion-down 0.2s ease-out;
    --animate-accordion-up: accordion-up 0.2s ease-out;

    @keyframes accordion-down {
        from {
            height: 0;
        }
        to {
            height: var(--radix-accordion-content-height);
        }
    }
    @keyframes accordion-up {
        from {
            height: var(--radix-accordion-content-height);
        }
        to {
            height: 0;
        }
    }
}

@layer base {
    :root {
        --background: 0 0% 100%;
        --foreground: 240 10% 3.9%;
        --card: 0 0% 100%;
        --card-foreground: 240 10% 3.9%;
        --popover: 0 0% 100%;
        --popover-foreground: 240 10% 3.9%;
        --primary: 240 5.9% 10%;
        --primary-foreground: 0 0% 98%;
        --secondary: 240 4.8% 95.9%;
        --secondary-foreground: 240 5.9% 10%;
        --muted: 240 4.8% 95.9%;
        --muted-foreground: 240 3.8% 46.1%;
        --accent: 240 4.8% 95.9%;
        --accent-foreground: 240 5.9% 10%;
        --destructive: 0 84.2% 60.2%;
        --destructive-foreground: 0 0% 98%;
        --border: 240 5.9% 90%;
        --border2: 240 5.9% 90%;
        --input: 240 5.9% 90%;
        --ring: 240 5% 64.9%;
        --radius: 0.75rem;

        --successful: 131 55% 40%;
        --successful-foreground: 210 40% 98%;

        --mainaccent: 221.2 83.2% 53.3%;
        --mainaccent-foreground: 210 40% 98%;

        --mainaccent-accent: 220 69% 97%;
        --mainaccent-accent-foreground: 221.2 83.2% 53.3%;

        --warning: 42 96% 57%;
        --warning-foreground: 210 40% 98%;

        --page-width: 1300px;
        --page-margin: 1.5rem;
        --sidebar-background: 0 0% 98%;
        --sidebar-foreground: 240 5.3% 26.1%;
        --sidebar-primary: 240 5.9% 10%;
        --sidebar-primary-foreground: 0 0% 98%;
        --sidebar-accent: 240 4.8% 95.9%;
        --sidebar-accent-foreground: 240 5.9% 10%;
        --sidebar-border: 220 13% 91%;
        --sidebar-ring: 217.2 91.2% 59.8%;

        --button: linear-gradient(180deg, #1994ff 0%, #157cff 100%);
    }

    .dark {
        --background: 240 10% 3.9%;
        --foreground: 0 0% 98%;
        --card: 240 10% 3.9%;
        --card-foreground: 0 0% 98%;
        --popover: 240 10% 3.9%;
        --popover-foreground: 0 0% 98%;
        --primary: 0 0% 98%;
        --primary-foreground: 240 5.9% 10%;
        --secondary: 240 3.7% 15.9%;
        --secondary-foreground: 0 0% 98%;
        --muted: 240 3.7% 15.9%;
        --muted-foreground: 240 5% 64.9%;
        --accent: 240 3.7% 15.9%;
        --accent-foreground: 0 0% 98%;
        --destructive: 0 62.8% 30.6%;
        --destructive-foreground: 0 0% 98%;
        --border: 240 3.7% 15.9%;
        --border2: 240 3.7% 15.9%;
        --input: 240 3.7% 15.9%;
        --ring: 240 3.8% 46.1%;
        --radius: 0.75rem;

        --successful: 131 55% 40%;
        --successful-foreground: 210 40% 98%;

        --mainaccent: 217.2 91.2% 59.8%;
        --mainaccent-foreground: 0 0% 100%;

        --mainaccent-accent: 219 79% 9%;
        --mainaccent-accent-foreground: 217.2 91.2% 59.8%;

        --warning: 42 96% 57%;
        --warning-foreground: 210 40% 98%;
        --sidebar-background: 240 5.9% 10%;
        --sidebar-foreground: 240 4.8% 95.9%;
        --sidebar-primary: 224.3 76.3% 48%;
        --sidebar-primary-foreground: 0 0% 100%;
        --sidebar-accent: 240 3.7% 15.9%;
        --sidebar-accent-foreground: 240 4.8% 95.9%;
        --sidebar-border: 240 3.7% 15.9%;
        --sidebar-ring: 217.2 91.2% 59.8%;

        --button: linear-gradient(180deg, #1994ff 0%, #157cff 100%);
    }
}

@layer base {
    *,
    ::after,
    ::before,
    ::backdrop,
    ::file-selector-button {
        border-color: var(--color-gray-200, currentColor);
    }
    button:not(:disabled),
    [role="button"]:not(:disabled) {
        cursor: pointer;
    }
}

@layer base {
    * {
        @apply border-border;
    }
    body {
        @apply bg-background text-foreground;
    }
}

html {
    box-sizing: border-box;
}
*,
*:before,
*:after {
    box-sizing: inherit;
    -webkit-tap-highlight-color: rgba(255, 255, 255, 0);
}

input[type="date"] {
    justify-content: end;
}

.PhoneInputCountry {
    gap: 0.5rem;
}

.PhoneInputInput {
    text-align: left;
    direction: ltr;
}

.error-message {
    background-color: #fae9e8;
    padding: 0.75rem;
    margin-top: 2rem;
    border-radius: var(--radius);
    color: #f85149;
}

.logo {
    font-size: 2rem;
    text-align: center;
    margin-bottom: 3rem;
    font-weight: bold;
}

.loader-wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 1rem;
}

.page_header {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

#nprogress {
    position: relative;
    z-index: 9999999;
}

#sentry-feedback {
    --inset: auto auto 0 0;
    --font-family: var(--font-janna);
    --accent-background: hsl(var(--mainaccent));
    --accent-foreground: hsl(var(--mainaccent-foreground));
    --success-color: hsl(var(--successful));
    --error-color: hsl(var(--destructive));
    --background: hsl(var(--card));
    --foreground: hsl(var(--card-foreground));
    --border: 1.5px solid hsl(var(--border2));
    --z-index: 21;
    --page-margin: 0.75rem 0.75rem 6rem 0.75rem;
    --button-primary-border-radius: var(--radius);
    --button-primary-border: 0;
    --button-border-radius: var(--radius);
}

.dialog__content {
    margin: 4rem !important;
}

@screen md {
    #sentry-feedback {
        --page-margin: 0.75rem 0.75rem 0.75rem 0.75rem;
    }
}

@theme inline {
    --animation-delay-0: 0s;
    --animation-delay-75: 75ms;
    --animation-delay-100: 0.1s;
    --animation-delay-150: 0.15s;
    --animation-delay-200: 0.2s;
    --animation-delay-300: 0.3s;
    --animation-delay-500: 0.5s;
    --animation-delay-700: 0.7s;
    --animation-delay-1000: 1s;

    --animation-repeat-0: 0;
    --animation-repeat-1: 1;
    --animation-repeat-infinite: infinite;

    --animation-direction-normal: normal;
    --animation-direction-reverse: reverse;
    --animation-direction-alternate: alternate;
    --animation-direction-alternate-reverse: alternate-reverse;

    --animation-fill-mode-none: none;
    --animation-fill-mode-forwards: forwards;
    --animation-fill-mode-backwards: backwards;
    --animation-fill-mode-both: both;

    --animate-in: var(--tw-duration, 150ms) var(--tw-ease, ease) enter;
    --animate-out: var(--tw-duration, 150ms) var(--tw-ease, ease) exit;

    --percentage-0: 0;
    --percentage-5: 0.05;
    --percentage-10: 0.1;
    --percentage-15: 0.15;
    --percentage-20: 0.2;
    --percentage-25: 0.25;
    --percentage-30: 0.3;
    --percentage-35: 0.35;
    --percentage-40: 0.4;
    --percentage-45: 0.45;
    --percentage-50: 0.5;
    --percentage-55: 0.55;
    --percentage-60: 0.6;
    --percentage-65: 0.65;
    --percentage-70: 0.7;
    --percentage-75: 0.75;
    --percentage-80: 0.8;
    --percentage-85: 0.85;
    --percentage-90: 0.9;
    --percentage-95: 0.95;
    --percentage-100: 1;

    @keyframes enter {
        from {
            opacity: var(--tw-enter-opacity, 1);
            transform: translate3d(var(--tw-enter-translate-x, 0), var(--tw-enter-translate-y, 0), 0)
                scale3d(var(--tw-enter-scale, 1), var(--tw-enter-scale, 1), var(--tw-enter-scale, 1))
                rotate(var(--tw-enter-rotate, 0));
        }
    }

    @keyframes exit {
        to {
            opacity: var(--tw-exit-opacity, 1);
            transform: translate3d(var(--tw-exit-translate-x, 0), var(--tw-exit-translate-y, 0), 0)
                scale3d(var(--tw-exit-scale, 1), var(--tw-exit-scale, 1), var(--tw-exit-scale, 1))
                rotate(var(--tw-exit-rotate, 0));
        }
    }
}

@utility delay-* {
    animation-delay: --value([duration]);
    animation-delay: calc(--value(integer) * 1ms);
    animation-delay: --value(--animation-delay- *);
}

@utility repeat-* {
    animation-iteration-count: --value(--animation-repeat- *, integer);
}

@utility direction-* {
    animation-direction: --value(--animation-direction- *);
}

@utility fill-mode-* {
    animation-fill-mode: --value(--animation-fill-mode- *);
}

@utility running {
    animation-play-state: running;
}
@utility paused {
    animation-play-state: paused;
}

@utility fade-in-* {
    --tw-enter-opacity: --value(--percentage- *);
}
@utility fade-out-* {
    --tw-exit-opacity: --value(--percentage- *);
}

@utility zoom-in-* {
    --tw-enter-scale: --value(--percentage- *);
}
@utility zoom-out-* {
    --tw-exit-scale: --value(--percentage- *);
}

@utility spin-in-* {
    --tw-enter-rotate: calc(--value(integer) * 1deg);
    --tw-enter-rotate: --value(--rotate- *, [angle]);
}
@utility spin-out-* {
    --tw-exit-rotate: calc(--value(integer) * 1deg);
    --tw-exit-rotate: --value(--rotate- *, [angle]);
}

@utility slide-in-from-top-* {
    --tw-enter-translate-y: calc(--value([percentage], [length]) * -1);
}
@utility slide-in-from-bottom-* {
    --tw-enter-translate-y: --value([percentage], [length]);
}
@utility slide-in-from-left-* {
    --tw-enter-translate-x: calc(--value([percentage], [length]) * -1);
}
@utility slide-in-from-right-* {
    --tw-enter-translate-x: --value([percentage], [length]);
}

@utility slide-out-to-top-* {
    --tw-exit-translate-y: calc(--value([percentage], [length]) * -1);
}
@utility slide-out-to-bottom-* {
    --tw-exit-translate-y: --value([percentage], [length]);
}
@utility slide-out-to-left-* {
    --tw-exit-translate-x: calc(--value([percentage], [length]) * -1);
}
@utility slide-out-to-right-* {
    --tw-exit-translate-x: --value([percentage], [length]);
}
```

Been trying to fix this for hours, I appreciate any help.

**Comment by wongjn** [comment]
Does a build fail locally as well? If so, would you be able to provide a git repository that reproduces the issue please?

**Reply by nahasco** [reply]
Its not failing locally, just on vercel. My repo is private but I invited you for access.

**Comment by Denoder** [comment]
I'm also getting this error when ran locally. If i remove `@tailwindcss/postcss': {}`, it runs fine

```
   ▲ Next.js 15.1.6
   - Environments: .env

   Creating an optimized production build ...
 ✓ (serwist) Bundling the service worker script with the URL '/sw.js' and the scope '/'...
Failed to compile.

HookWebpackError: /home/ubuntu/dev/static/css/61c923d06e1f61a9.css:2:84065: Unclosed block
    at makeWebpackError (/home/ubuntu/dev/node_modules/next/dist/compiled/webpack/bundle5.js:28:314608)
    at /home/ubuntu/dev/node_modules/next/dist/compiled/webpack/bundle5.js:28:106402
    at eval (eval at create (/home/ubuntu/dev/node_modules/next/dist/compiled/webpack/bundle5.js:13:9218), <anonymous>:58:1)
-- inner error --
CssSyntaxError: /home/ubuntu/dev/static/css/61c923d06e1f61a9.css:2:84065: Unclosed block
    at Input.error (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/input.js:106:16)
    at ScssParser.unclosedBlock (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/parser.js:574:22)
    at ScssParser.endFile (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/parser.js:336:35)
    at ScssParser.parse (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/parser.js:475:10)
    at scssParse (/home/ubuntu/dev/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:322)
    at new LazyResult (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/processor.js:53:14)
    at CssMinimizerPlugin.optimizeAsset (/home/ubuntu/dev/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:48:12)
    at /home/ubuntu/dev/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:79:55
    at async Span.traceAsyncFn (/home/ubuntu/dev/node_modules/next/dist/trace/trace.js:153:20)
caused by plugins in Compilation.hooks.processAssets
CssSyntaxError: /home/ubuntu/dev/static/css/61c923d06e1f61a9.css:2:84065: Unclosed block
    at Input.error (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/input.js:106:16)
    at ScssParser.unclosedBlock (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/parser.js:574:22)
    at ScssParser.endFile (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/parser.js:336:35)
    at ScssParser.parse (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/parser.js:475:10)
    at scssParse (/home/ubuntu/dev/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:322)
    at new LazyResult (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/home/ubuntu/dev/node_modules/next/node_modules/postcss/lib/processor.js:53:14)
    at CssMinimizerPlugin.optimizeAsset (/home/ubuntu/dev/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:48:12)
    at /home/ubuntu/dev/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:79:55
    at async Span.traceAsyncFn (/home/ubuntu/dev/node_modules/next/dist/trace/trace.js:153:20)
```
    
```css
@import 'tailwindcss';

@plugin "tailwindcss-animate";

@custom-variant dark (&:is(.dark *));

:root {
    --background: hsl(0 0% 100%);
    --foreground: hsl(240 10% 3.9%);
    --card: hsl(0 0% 100%);
    --card-foreground: hsl(240 10% 3.9%);
    --popover: hsl(0 0% 100%);
    --popover-foreground: hsl(240 10% 3.9%);
    --primary: hsl(240 5.9% 10%);
    --primary-foreground: hsl(0 0% 98%);
    --secondary: hsl(240 4.8% 95.9%);
    --secondary-foreground: hsl(240 5.9% 10%);
    --muted: hsl(240 4.8% 95.9%);
    --muted-foreground: hsl(240 3.8% 46.1%);
    --accent: hsl(240 4.8% 95.9%);
    --accent-foreground: hsl(240 5.9% 10%);
    --destructive: hsl(0 72.22% 50.59%);
    --destructive-foreground: hsl(0 0% 98%);
    --border: hsl(240 5.9% 90%);
    --input: hsl(240 5.9% 90%);
    --ring: hsl(240 5% 64.9%);
    --radius: 0.4rem;
    --success: hsl(148.24 73.91% 36.08%);
    --info: hsl(212.31 87.39% 53.33%);
    --warning: hsl(6.92 87.39% 53.33%);
    --error: hsl(348 62.99% 50.2%);
    --sidebar-background: hsl(0 0% 98%);
    --sidebar-foreground: hsl(240 5.3% 26.1%);
    --sidebar-primary: hsl(240 5.9% 10%);
    --sidebar-primary-foreground: hsl(0 0% 98%);
    --sidebar-accent: hsl(240 4.8% 95.9%);
    --sidebar-accent-foreground: hsl(240 5.9% 10%);
    --sidebar-border: hsl(220 13% 91%);
    --sidebar-ring: hsl(240 5% 64.9%);
}

.dark {
    --background: hsl(240 10% 3.9%);
    --foreground: hsl(0 0% 98%);
    --card: hsl(240 10% 3.9%);
    --card-foreground: hsl(0 0% 98%);
    --popover: hsl(240 10% 3.9%);
    --popover-foreground: hsl(0 0% 98%);
    --primary: hsl(0 0% 98%);
    --primary-foreground: hsl(240 5.9% 10%);
    --secondary: hsl(240 3.7% 15.9%);
    --secondary-foreground: hsl(0 0% 98%);
    --muted: hsl(240 3.7% 15.9%);
    --muted-foreground: hsl(240 5% 64.9%);
    --accent: hsl(240 3.7% 15.9%);
    --accent-foreground: hsl(0 0% 98%);
    --destructive: hsl(0 62.8% 30.6%);
    --destructive-foreground: hsl(0 85.7% 97.3%);
    --border: hsl(240 3.7% 15.9%);
    --input: hsl(240 3.7% 15.9%);
    --ring: hsl(240 4.9% 83.9%);
    --success: hsl(159.69 68.65% 63.73%);
    --info: hsl(200 72.29% 67.45%);
    --warning: hsl(38.97 81.82% 71.96%);
    --error: hsl(0 69.33% 70.59%);
    --sidebar-background: hsl(240 5.9% 10%);
    --sidebar-foreground: hsl(240 4.8% 95.9%);
    --sidebar-primary: hsl(224.3 76.3% 48%);
    --sidebar-primary-foreground: hsl(0 0% 100%);
    --sidebar-accent: hsl(240 3.7% 15.9%);
    --sidebar-accent-foreground: hsl(240 4.8% 95.9%);
    --sidebar-border: hsl(240 3.7% 15.9%);
    --sidebar-ring: hsl(240 4.9% 83.9%);
}

@theme inline {
    --color-background: var(--background);
    --color-foreground: var(--foreground);
    --color-card: var(--card);
    --color-card-foreground: var(--card-foreground);
    --color-popover: var(--popover);
    --color-popover-foreground: var(--popover-foreground);
    --color-primary: var(--primary);
    --color-primary-foreground: var(--primary-foreground);
    --color-secondary: var(--secondary);
    --color-secondary-foreground: var(--secondary-foreground);
    --color-muted: var(--muted);
    --color-muted-foreground: var(--muted-foreground);
    --color-accent: var(--accent);
    --color-accent-foreground: var(--accent-foreground);
    --color-destructive: var(--destructive);
    --color-destructive-foreground: var(--destructive-foreground);
    --color-border: var(--border);
    --color-input: var(--input);
    --color-ring: var(--ring);
    --color-success: var(--success);
    --color-info: var(--info);
    --color-warning: var(--warning);
    --color-error: var(--error);
    --radius-sm: calc(var(--radius) - 4px);
    --radius-md: calc(var(--radius) - 2px);
    --radius-lg: var(--radius);
    --radius-xl: calc(var(--radius) + 4px);
    --color-sidebar-ring: var(--sidebar-ring);
    --color-sidebar-border: var(--sidebar-border);
    --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
    --color-sidebar-accent: var(--sidebar-accent);
    --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
    --color-sidebar-primary: var(--sidebar-primary);
    --color-sidebar-foreground: var(--sidebar-foreground);
    --color-sidebar: var(--sidebar-background);
    --animate-accordion-down: accordion-down 0.2s ease-out;
    --animate-accordion-up: accordion-up 0.2s ease-out;

    @keyframes accordion-down {
        from {
            height: 0;
        }

        to {
            height: var(--radix-accordion-content-height);
        }
    }

    @keyframes accordion-up {
        from {
            height: var(--radix-accordion-content-height);
        }

        to {
            height: 0;
        }
    }
}

@layer base {
    * {
        @apply border-border;
    }

    html {
        @apply scroll-smooth;
    }

    body {
        @apply bg-background text-foreground overscroll-none;
        font-synthesis-weight: none;
        text-rendering: optimizeLegibility;
    }

    @supports (font: -apple-system-body) and (-webkit-appearance: none) {
        [data-wrapper] {
            @apply min-[1800px]:border-t;
        }
    }

    /* Custom scrollbar styling. Thanks @pranathiperii. */
    ::-webkit-scrollbar {
        width: 5px;
    }

    ::-webkit-scrollbar-track {
        background: transparent;
    }

    ::-webkit-scrollbar-thumb {
        background: hsl(var(--border));
        border-radius: 5px;
    }

    * {
        scrollbar-width: thin;
        scrollbar-color: hsl(var(--border)) transparent;
    }
}

@layer utilities {
    .step {
        counter-increment: step;
    }

    .step:before {
        @apply absolute w-9 h-9 bg-muted rounded-full font-mono font-medium text-center text-base inline-flex items-center justify-center -indent-px border-4 border-background;
        @apply ml-[-50px] mt-[-4px];
        content: counter(step);
    }

    .chunk-container {
        @apply shadow-none;
    }

    .chunk-container::after {
        content: "";
        @apply absolute -inset-4 shadow-xl rounded-xl border;
    }

    /* Hide scrollbar for Chrome, Safari and Opera */
    .no-scrollbar::-webkit-scrollbar {
        display: none;
    }

    /* Hide scrollbar for IE, Edge and Firefox */
    .no-scrollbar {
        -ms-overflow-style: none;
        /* IE and Edge */
        scrollbar-width: none;
        /* Firefox */
    }

    .border-grid {
        @apply border-border/30 dark:border-border;
    }

    .container-wrapper {
        @apply min-[1800px]:max-w-[1536px] min-[1800px]:border-x border-border/30 dark:border-border mx-auto w-full;
    }

    .container {
        @apply px-4 xl:px-6 2xl:px-4 mx-auto max-w-[1536px];
    }
}
```

```ts
import type { NextConfig } from 'next';
import createNextIntlPlugin from 'next-intl/plugin';
import withSerwistInit from '@serwist/next';

const withNextIntl = createNextIntlPlugin();

const withSerwist = withSerwistInit({
    swSrc: 'src/sw.ts',
    swDest: 'public/sw.js',
    disable: process.env.NODE_ENV === "development",
});

const nextConfig: NextConfig = {
    webpack: (config, options) => {
        return config;
    },
    images: {
        formats: ['image/avif', 'image/webp'],
    },
    typescript: {
        ignoreBuildErrors: true,
    },
    reactStrictMode: false,
    compress: true,
    poweredByHeader: false,
    experimental: {
        serverSourceMaps: false,
        webpackMemoryOptimizations: true
    },
};
```
