### DISCUSSION TITLE
What is a better approach of writing AB tests?

### DISCUSSION THREAD

**Discussion by aspirisen** [tailwindlabs/tailwindcss#16383] [Help] [answered]
Hello everyone, I wanted to ask if there are any utilities for ab tests?

Currently in my project the ab tests flags are placed in a class in the body and then used like this

```scss
.button {
  color: red;

  .ab_my_experiment-v1 & {
    color: blue;
  }

  .ab_my_experiment-v2 & {
    color: green;
  }
}
```

With tailwind is it possible to do smth like that?

```tsx
<h1 class="bg-sky-500 ab_my_experiment-v1#text-3xl ab_my_experiment-v1#hover:bg-sky-700">
  Hello world!
</h1>
```

And the final css compiled by tailwind would be smth like in the first example.

Or maybe there are some other technics to handle ab tests?
