### DISCUSSION TITLE
it there way to make utilities bg-*  with custom theme property like --surface-* without generating --bg-* classes with --color-* theme.(v4)

### DISCUSSION THREAD

**Discussion by YoonDongGeun** [tailwindlabs/tailwindcss#16402] [Help] [answered]
## Problem
I want to make bg-* classes with only --surface tokens. but it make bg-* classes with --color tokens too.
It's autocomplete list made with --surface-* tokens and works well.
But it overwrite existing class(ex. bg-primary-light) and define class twice(by --color-primary-light and --surface-primary-light).
And i can use not auto-completable bg-color by "--color-* themes.

**I want to define bg-* classes only once with --surface-* themes.!!** 
After i change --surface-* color list and not change code, it is hard to recognize something changed but looks fine.

### reference you can see
- #14923

```css
@theme {
  --color-*: initial;
  /* token-1st brand-color */
  --color-primary-main: var(--color-blue-300);
  --color-primary-dark: var(--color-blue-500);
  --color-primary-light: var(--color-blue-50);
  --color-secondary-main: var(--color-orange-500);
  --color-secondary-dark: var(--color-orange-600);
  --color-secondary-light: var(--color-orange-300);
  --color-neutral-white: var(--color-grey-50);
  --color-neutral-black: var(--color-grey-400);
  --color-neutral-grey: var(--color-grey-100);
  --color-status-accent: var(--color-yellow-100);
  --color-status-alert: var(--color-red-100);
  --color-status-disabled: var(--color-grey-200);
  /* token-2nd Surface-color */
  --surface-primary: var(--color-primary-main);
  --surface-primary-light: var(--color-primary-light);
  /* token-2nd Text-color */
  /* token-2nd Border-color */
}

@utility bg-* {
  background-color: --value(--surface- *);
}
```

### picture of autocomplete working well.
![image](https://github.com/user-attachments/assets/38ff8b37-d257-42f0-8906-6675bbba1c23)

### it's not autocompleted, but I can use it by "--color-*"
![image](https://github.com/user-attachments/assets/d21143ff-89e5-455d-8830-a2514ef2f567)

### picture of .bg-primary-light genereated twice by "--color-*" and "--surface-*"
![image](https://github.com/user-attachments/assets/1fcaa278-76b7-4afc-bc40-327336d43148)
