### DISCUSSION TITLE
[Feature Proposal]: Add custom scrollbar utilities

### DISCUSSION THREAD

**Discussion by ghost** [tailwindlabs/tailwindcss#1640] [Ideas]
I just wanted to suggest unified scrollbar style classes. I noticed the docs use webkit CSS selectors for their scrollbars that appear in the class tables. I'm sure that could be extended to Firefox and other browsers as well. Is there a chance you could bundle these as utility classes?

**Comment by jenstornell** [comment]
I would also like to have such support built in. The CSS code looks something like below:

```css
/* width */
::-webkit-scrollbar {
  width: 16px;
  height: 16px;
}

/* Track */
::-webkit-scrollbar-track {
  border-radius: 100vh;
  background: #edf2f7;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #cbd5e0;
  border-radius: 100vh;
  border: 3px solid #edf2f7;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #a0aec0;
}
```

I guess it would be something like this:

```html
<div class="scrollbar-thumb:bg-red-500 scrollbar-track:rounded">Content</div>
```

or a shorthand because it may be long...

```html
<div class="s-thumb:bg-red-500 s-track:rounded">Content</div>
```

or...

```html
<div class="sb-thumb:bg-red-500 sb-track:rounded">Content</div>
```

**Reply by thinyadanarsu1200** [reply]
@jenstornell  Thank you~ it works but it doesn't work in firefox .How can I write?

**Reply by sidneyyau** [reply]
> @jenstornell Thank you~ it works but it doesn't work in firefox .How can I write?

Just use the [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) property.

**Comment by luukdv** [comment]
I'd like this as well, but unfortunately there's still no way to add scrollbar styles to iOS Chrome and iOS Safari, rendering them invisible.

Adding these classes to Tailwind might give the wrong impression that they will work everywhere? Not sure.

**Comment by LaravelFreelancerNL** [comment]
I just came across this pugin: https://github.com/adoxography/tailwind-scrollbar

**Reply by withewolf-dev** [reply]
did you try the plugin?

**Comment by LaravelFreelancerNL** [comment]
Yep, seems to work fine in Chrome

**Comment by vielhuber** [comment]
Actually there is no need for a plugin.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
    .scrollbar {
        scrollbar-color: red white;
        scrollbar-width: thin;
        &::-webkit-scrollbar {
            width: 5px;
        }
        &::-webkit-scrollbar-track {
            background-color: white;
        }
        &::-webkit-scrollbar-thumb {
            background-color: red;
            border-radius: 5px;
        }
    }
}
```

**Reply by Wolfleader101** [reply]
How did you achieve this.

When i copied your code I got this

![image](https://user-images.githubusercontent.com/25214835/106895201-e698e800-672a-11eb-99cb-ad7b902c0f1e.png)

**Reply by vielhuber** [reply]
This works without any problems.
Just with npm scripts (```node-sass``` followed by ```postcss``` for tailwind)

![image](https://user-images.githubusercontent.com/3183737/106896779-5048d000-66f2-11eb-8c86-a3b9a3cdd2f7.png)

**Reply by krt-z** [reply]
You can also get it to work as written in the original post using the 'postcss-nested' plugin mentioned in the tailwind docs.

**Comment by davidrivadeneyra** [comment]
It even works with a normal configuration of your tailwindcss. Just add this code in your @layer utilities.

``` css
@layer utilities {

     /* Scroll thumb styles */
    .scrollbar::-webkit-scrollbar {
      width: .5rem;
    }
    .scrollbar::-webkit-scrollbar-thumb {
      background: #27272E; 
      border-radius: 1rem;
    }
    .scrollbar::-webkit-scrollbar-thumb:active {
      background-color: #131314;
    }
    .scrollbar::-webkit-scrollbar-thumb:hover {
      background: #3B3B46; 
      box-shadow: 0 0 2px 1px rgba(0, 0, 0, 0.2);
    }

    /* Scroll track styles (Background) */
    .scrollbar::-webkit-scrollbar-track {
      background: #131314;
      border-radius: 4px;
    }
    .scrollbar::-webkit-scrollbar-track:hover, 
    .scrollbar::-webkit-scrollbar-track:active {
      background: #131314;
    }
}
```
