### DISCUSSION TITLE
tailwindcss generate failed after 5 seconds

### DISCUSSION THREAD

**Discussion by Imlona** [tailwindlabs/tailwindcss#16417] [Help]
info  - [plugin: ./node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss service started

Rebuilding...
error - [plugin: ./node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss generate failed after 5 seconds, please check your tailwind.css and tailwind.config.js
✨  Done in 22.29s.

**Comment by Imlona** [comment]
"name": "tailwindcss",
 "version": "3.4.14",

**Comment by stephen-ics** [comment]
Hmm this is interesting, can you send your tailwind.css and tailwind.config.js files? They should look similar to this.
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
and
```css
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx,html}'],
  theme: {
    extend: {},
  },
  plugins: [],
}
```
