### DISCUSSION TITLE
hsl colors rendering issue with v4

### DISCUSSION THREAD

**Discussion by ritiksharmarj** [tailwindlabs/tailwindcss#16412] [Help]
I have defined colors inside the theme like this -
```css
@theme {
  --color-background: oklch(1 0 0);
  --color-foreground: hsl(var(--foreground));
  --color-card: hsl(0 0% 100%);
  --color-card-foreground: hsl(240 3.7% 15.9%);
}
```

```css
@layer base {
  :root {
    --foreground: 240 3.7% 15.9%;
  }
}
```

Only the background and foreground work, not the others. Why? Is there something I'm missing?

<img width="421" alt="Screenshot 2025-02-11 at 01 27 39" src="https://github.com/user-attachments/assets/b357fdf4-8346-4a87-9b20-008acd200d79" />
