### DISCUSSION TITLE
Tailwind CSS v4 Variants Not Working in "@layer components"

### DISCUSSION THREAD

**Discussion by iamaliybi** [tailwindlabs/tailwindcss#16449] [Help] [answered]
Hi everyone,

I'm experiencing an issue with Tailwind CSS v4 where variants (such as `hover`, `focus`, etc.) are not being applied correctly when using `@‌layer components`.

### Issue Description

1. When I define a class inside `@layer components`, it works as expected for base styles.
2. However, when I try to apply variants like `hover:` or `focus:`, they do not seem to work.

```
@layer components {
	.btn-success {
		display: flex;
		align-items: center;
		color: rgb(var(--c-white) / 1);
		border: 1px solid transparent;
		background-color: red;
		transition: opacity 250ms ease-in-out;
	}
}
```

### Expected Behavior
The `hover:btn-success` class should have a `red` background color when hovered over.

### Actual Behavior
The hover state does not get applied, and inspecting the generated CSS does not show the `hover:` styles.

### Steps Tried:

1. Verified Tailwind is correctly installed and working.
2. Checked Tailwind v4 documentation but didn’t find anything addressing this specifically.
3. Also, it doesn't work when I try to use `@layer utilities`.

### Questions:
Is this an expected behavior change in Tailwind v4?
Should variants be applied differently within `@layer components`?
Are there any workarounds or best practices for handling variants in `@layer components`?
Any insights or solutions would be greatly appreciated!

Thanks in advance!

**Comment by wongjn** [comment, marked as answer]
> Is this an expected behavior change in Tailwind v4?

Yes,  see https://tailwindcss.com/docs/upgrade-guide#adding-custom-utilities.

> Should variants be applied differently within `@layer components`?
> Are there any workarounds or best practices for handling variants in @layer components?

Variants don't get applied at all anymore. As per above, Tailwind v4 no longer does anything "special" for CSS inside `@layer`s.

---

So, for equivalent in v4, you'd do:

```css
@utility btn-success {
	@layer components {
		display: flex;
		align-items: center;
		color: rgb(var(--c-white) / 1);
		border: 1px solid transparent;
		background-color: red;
		transition: opacity 250ms ease-in-out;
	}
}
```

**Reply by iamaliybi** [reply]
Thank you very much, it's working. I have a question, what's the difference between `utilities` and `components`?

**Reply by wongjn** [reply]
As per the CSS:

https://github.com/tailwindlabs/tailwindcss/blob/ff8fd8c9f7aadb7a1b926ffa8348c05fad9fdcb1/packages/tailwindcss/index.css#L1

`components` comes before `utilities`, so any non-`!important` declarations in `components` can be overridden by CSS in `utilities`.

**Comment by Inventoris** [comment]
@iamaliybi you can use the following entry:

```css
@layer components {
	.btn-success {
		display: flex;
		align-items: center;
		color: rgb(var(--c-white) / 1);
		border: 1px solid transparent;
		background-color: red;
		transition: opacity 250ms ease-in-out;
                &:hover {
                  @media (hover: hover) {
                    background-color: var(--color-violet-700);
                  }
                }
	}
}
```

Here is the [doc](https://tailwindcss.com/docs/styling-with-utility-classes#using-custom-css).
