### DISCUSSION TITLE
How to upgrade `rotate-` in tailwindcss v4?

### DISCUSSION THREAD

**Discussion by Debbl** [tailwindlabs/tailwindcss#16446] [Help] [answered]
the `rotate-45` is transformed into `transform: rotate(45deg);` before v4.

see https://play.tailwindcss.com/F637QTFwch, and hover the box

<img width="868" alt="image" src="https://github.com/user-attachments/assets/96194d8c-0693-4a5d-8861-f766438ce05b" />

but in v4 it be transformed into `rotate: 45deg;`

if there is an animation that uses transform rotate, there is a problem here.

see https://play.tailwindcss.com/x7W58yQxAP, and hover the box

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/9d917518-c69c-4a9e-82f1-84080ecbedad" />

**Comment by Inventoris** [comment, marked as answer]
Hi @Debbl.

I don't see a problem, the animation from both examples works for me.

But to be more correct, you need to animate not transform, but rotate like this:

```css
@import "tailwindcss";

@theme {
  --animate-rotate-hover: animate-rotate 3s linear infinite;

  @keyframes animate-rotate {
    0%,
    100% {
      rotate: -30deg;
    }
    50% {
      rotate: 30deg;
    }
  }
}
```
