### DISCUSSION TITLE
[v4] Referenced CSS variables in a "prefixed context" don't include the prefix

### DISCUSSION THREAD

**Discussion by QuentinFrc** [tailwindlabs/tailwindcss#16455] [Ideas]
**What version of Tailwind CSS are you using?**

4.0.5

**What version of Node.js are you using?**

v22.5.1

**Reproduction url** : 

https://play.tailwindcss.com/Z6kqQK9vbr?size=540x720&file=css

**Describe your issue**:

Given this code:

```css title="theme.css"
@theme {
  --color-black: black;
  --color-background: var(--color-black);
}
```

When using this stylesheet and prefixed it like this : 
```css
@import "tailwindcss" prefix(ui);
@import './theme.css' prefix(ui);
```

The result is: 
```css title="theme.css"
:root {
  --ui-color-black: black;
  --ui-color-background: var(--color-black); /* Should be `var(--ui-color-black);` */
}
```

*Keep in mind that I can't know the prefix that will be used*
