### DISCUSSION TITLE
@screen directives replacement

### DISCUSSION THREAD

**Discussion by billy-le** [tailwindlabs/tailwindcss#16615] [Help] [answered]
I'm in the process of upgrading from v3 to v4 but I can't find any documentation of the `@screen` directive being replaced in my .css file.

Does anyone know what to use instead?

Here is an example of what I'm trying to replace:
```css
.work_year {
  @screen lg {
    top: 30%;
  }

  @screen xl {
    top: 50%;  
  }
}
```

**Comment by wongjn** [comment, marked as answer]
You use `@variant`:

```css
.work_year {
  @variant lg {
    top: 30%;
  }

  @variant xl {
    top: 50%;  
  }
}
```
