### DISCUSSION TITLE
How to generate :has utilities in TW4?

### DISCUSSION THREAD

**Discussion by smhmd** [tailwindlabs/tailwindcss#16655] [Help] [answered]
I would like to be able to do this:
```jsx
<main class="html-bg-red-500" /> // I want to add the utility in the element itself, not the html tag.
```

and generate this css
```css
html:has(.html-bg-red-500) {
  background-color: var(--color-red-500)
}
```

Why? I have many routes and each route has its own background color. Without setting the bg color on the html, hard scrolling reveals a different color in the background.

Is this doable?
