### DISCUSSION TITLE
Is there a way to define colors differently for different utilities?

### DISCUSSION THREAD

**Discussion by SamBallantyne** [tailwindlabs/tailwindcss#16665] [Help] [answered]
Today (on tailwind v3) we define colors in a utility specific way, by overriding the themes entirely in tailwind.config.js. Colors like `main` or `brand` or whatever mean different things for different utilities (text-, border-, bg-)

Minimal example:

```css
:root {
  --color-content-main: rgb(51, 67, 82);
  --color-border-main: rgb(237, 241, 245);
}

.dark {
  --color-content-main: rgb(210, 213, 223);
}
``` 

Then in the config file
```js
textColor: (theme) => ({
  main: 'rgb(var(--color-content-main) / <alpha-value>)',
  // ... 
})
borderColor: (theme) => ({
  main: 'rgb(var(--color-border-main) / <alpha-value>)',
  // ... 
})
```
 
 This helps us tune our colors, and we prefer this way of expressing dark mode. 
 
Is a tailwind.config.js file still the blessed way to do this, or is there a way in pure css?

**Comment by wongjn** [comment, marked as answer]
There is a way in CSS:

```css
@theme {
  --text-color-main: rgb(51, 67, 82); /* text-main */
  --border-color-main: rgb(237, 241, 245); /* border-main */
}
```
