### DISCUSSION TITLE
Font size inconsistency on macOS/iPadOS with Inter var font and Tailwind CSS 4.0.6

### DISCUSSION THREAD

**Discussion by MehmetCelik4** [tailwindlabs/tailwindcss#16723] [Help]
Hey there 👋

I've run into an interesting issue with the Inter variable font on Apple devices. The font is rendering noticeably larger on macOS and iPadOS compared to other platforms, even though I'm using the same Tailwind font classes everywhere.

Here's my current setup:
```css
@import url('https://fonts.googleapis.com/css2?family=Inter:wght,slnt@-10..0,100..900&display=swap');

html {
  font-family: 'Inter var', system-ui, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-feature-settings: 'cv02', 'cv03', 'cv04', 'cv11';
}
```
Same text looks bigger on macOS/iPadOS
Windows and Android show the expected size
Already tried the usual suspects like -webkit-font-smoothing: antialiased
Tech details:
Using Tailwind 4.0.6
Inter variable font
Issue shows up on all Apple devices I've tested
Has anyone else run into this? Any ideas for a fix that doesn't involve platform-specific hacks would be super helpful![Screenshots showing the difference between platforms]
