### DISCUSSION TITLE
Feature Request: Bring Back Dark-Mode-Specific CSS Variables in Tailwind 4

### DISCUSSION THREAD

**Discussion by pcoterecollective** [tailwindlabs/tailwindcss#16730] [Ideas]
## Description
In Tailwind CSS 3, defining dark-mode-specific CSS variables was straightforward, making it easy to customize themes without adding extra utility classes. However, in Tailwind CSS 4, there doesn’t seem to be a built-in way to achieve this efficiently. The current approach requires applying two separate classes (e.g., `bg-slate-200 dark:bg-slate-900 text-slate-900 dark:text-slate-100`), which can be cumbersome when handling multiple dark-mode-specific styles.

## Request
Reintroduce a way to define dark-mode-specific CSS variables within Tailwind’s configuration or provide a recommended approach for theming that avoids excessive class duplication.
Maybe something like this
```css
@import "tailwindcss";

@custom-variant dark (&:where(.dark, .dark *));

@theme inline {
  --color-background: var(--color-white);
}

@theme[dark] inline {
  --color-background: var(--color-black);
}
```
This would improve maintainability and keep styles more manageable, especially for complex themes.

Would love to see this feature reconsidered!

**Comment by wongjn** [comment]
You can sort of do this already using regular CSS with `@variant` to avoid the duplication:

```css
@import "tailwindcss";

@custom-variant dark (&:where(.dark, .dark *));

@theme inline {
  --color-background: var(--color-white);
}

@layer theme {
  * {
    @variant dark {
      --color-background: var(--color-black);
    }
  }
}
```

**Reply by tansanDOTeth** [reply]
I tried this, and it doesn't change anything. I just want to flip on dark mode

**Comment by RobinMalfait** [comment]
How did you do it in v3? It should be the same or simpler in v4.

We don't have and never had a native way of doing it so whatever technique you used should be possible in v4 as well.

**Reply by pcoterecollective** [reply]
@RobinMalfait You can find an example of a "v3" way to achieve this in the [Shadcn-UI repo](https://github.com/shadcn-ui/ui/blob/main/apps/www/styles/globals.css).

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    /* ... */
  }

  .dark {
    --background: 240 10% 3.9%;
    /* ... */
  }
}
```

There's also a "v4" example [here](https://github.com/shadcn-ui/ui/blob/main/apps/v4/app/globals.css) but I'd like to have your opinion on it before I choose to go down that road. 
The theme-related CSS vars aren't declared in a `@theme` block, which makes me doubt this is the right approach.

**Comment by felipe-miranda-marreiros** [comment]
You mean something like this?

```css

:root {
  --gray-950: 
  --gray-50:
}

@theme {
  --color-gray-950: var(--gray-950);
  --color-gray-50: var(--gray-50);
}

@media (prefers-color-scheme: dark) {
  @theme inline {
    --background: var(--gray-950);
    --foreground: var(--gray-50);
  }
}

@media (prefers-color-scheme: light) {
  @theme inline {
    --background: var(--gray-50);
    --foreground: var(--gray-950);
  }
}

body {
  color: var(--foreground);
  background: var(--background);
}
```

**Reply by pcoterecollective** [reply]
@felipe-miranda-marreiros 
Would that also work when dark-mode is driven by a class on the html tag (or other child element)?
```css
.dark,
.dark * {
  @theme inline {
    --background: var(--gray-950);
    --foreground: var(--gray-50);
  }
}
```

**Reply by felipe-miranda-marreiros** [reply]
```css

:root {
  --gray-950: hsl(0, 0%, 16%);
  --gray-50: hsl(0, 0%, 96%);
}

@layer base {
  [class='light'] {
    --background: var(--gray-50);
    --foreground: var(--gray-950);
  }

  [class='dark'] {
    --background: var(--gray-950);
    --foreground: var(--gray-50);
  }
}

@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}

```

And then (example):

```html
<button className="text-white dark:text-background">
      Undone
 </button>
```

It works.

**Reply by pcoterecollective** [reply]
Ok. So, here's what I had in mind, illustrated with what seems to be a working example:

```css
@import "tailwindcss";

:root {
	--color-background: var(--color-slate-100);
	--color-foreground: var(--color-slate-900);
	--color-border: var(--color-slate-300);
}

.dark {
	--color-background: var(--color-slate-900);
	--color-foreground: var(--color-slate-300);
	--color-border: var(--color-slate-700);
}

@theme {
	--color-background: var(--color-background);
	--color-foreground: var(--color-foreground);
	--color-border: var(--color-border);
}
```

```html
  <main class="w-screen h-screen grid grid-cols-2">
    <div class="flex items-center justify-center bg-background text-foreground">
      <div class="border-2 border-border p-4 rounded-lg">
        <h1 class="text-3xl font-bold underline">Light</h1>
      </div>
    </div>
    <div class="dark flex items-center justify-center bg-background text-foreground">
      <div class="border-2 border-border p-4 rounded-lg">
        <h1 class="text-3xl font-bold underline">Dark</h1>
      </div>
    </div>
  </main>
```
![CleanShot 2025-03-20 at 17 11 49](https://github.com/user-attachments/assets/4fd77222-4579-47a6-894e-f84316ac105b)

Thanks!
