### DISCUSSION TITLE
[bug] box-shadow doesn't work in shadow-dom due to reliance on @property

### DISCUSSION THREAD

**Discussion by snaptopixel** [tailwindlabs/tailwindcss#16772] [General]
**What version of Tailwind CSS are you using?**

v4.0.6

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwind-cli

**What version of Node.js are you using?**

v20.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://codepen.io/snaptopixel/pen/GgRZebj

**Describe your issue**

Tailwind's box-shadow based utils (ring, shadow, etc) use multiple shadow syntax with custom properties:

```css
box-shadow: var(--foo), var(--bar), var(--baz);
```

Since these vars don't have default/fallback values the whole box-shadow breaks if any one of them is undefined. In non-shadow this is a non-issue since `@property` provides default values. However in shadow-dom `@property` does nothing, so ironically, in shadow-dom you will have no shadows on your dom.

Essentially it seems there should be suitable fallbacks for any utils that currently rely on `@property` since it doesn't work in shadow-dom land.

**Comment by philipp-spiess** [comment]
Hey @snaptopixel! Unfortunately `@property` declarations do not do anything when attached within a shadow-root, you need to ensue these are attached to the root document instead. We have an issue about this open at: https://github.com/tailwindlabs/tailwindcss/issues/15005

The issue is that we rely on `@property` to make variables animatable and avoid inheritance, so using `@property` is a requirement for v4 unfortunately.

**Reply by snaptopixel** [reply]
Thanks @philipp-spiess, I'm curious why tailwind 4 made the design decision to rely on `@property` I don't think there is any required reason to use it over default variables? Is it just a convenience or "shiny new thing" feature? Looking at the other post it seems others have faced the same issue and frustration as I have. I would suggest a hard look at what it would take to refactor and be `@property` free unless it's absolutely a requirement for some reason.

**Reply by philipp-spiess** [reply]
> @snaptopixel I don't think there is any required reason to use it over default variables? 

`@property` allows us to control the inheritance properties of CSS variables and allows us to makes css variables interpolatable (read: animateable) by having a type (e.g. it would not be possible at all to animate box-shadow in Tailwind CSS without the use of  `@property`). 

I understand your frustration with how this feature works inside shadow-roots that makes it a bit inconvenient, but it's unfortunately specced like this. You can see more context on it here, for example: https://github.com/w3c/css-houdini-drafts/issues/939 If you hoist the `@property` declarations into the document root styles, it will work as expected.

**Reply by snaptopixel** [reply]
Thanks for the discussion, appreciated! How would one hoist `@property` declarations? Is there a way to output css with only the @property declarations via the CLI? For reference, I'm building a single tailwind css file and using it in shadow-dom web components via `<link>` tag. I really don't want anything bleeding out into the page. For now I'm stuck adding my own defaults under the `:host` selector as I run across issues which is less than ideal.

**Reply by snaptopixel** [reply]
For reference here's what I'm using to list of all the `@property` vars that have `initial-value` in my shadow-dom
```css
:host {
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-translate-z: 0;
  --tw-rotate-x: rotateX(0);
  --tw-rotate-y: rotateY(0);
  --tw-rotate-z: rotateZ(0);
  --tw-skew-x: skewX(0);
  --tw-skew-y: skewY(0);
  --tw-border-style: solid;
  --tw-gradient-from: #0000;
  --tw-gradient-via: #0000;
  --tw-gradient-to: #0000;
  --tw-gradient-from-position: 0%;
  --tw-gradient-via-position: 50%;
  --tw-gradient-to-position: 100%;
  --tw-shadow: 0 0 #0000;
  --tw-inset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-inset-ring-shadow: 0 0 #0000;
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-outline-style: solid;
}
```

**Reply by Gregory-Gerard** [reply]
Here's a complete reference of all Tailwind v4 CSS custom properties with their initial values (extracted from the source code as of October 2025). This is also compatible with `tw-animate-css`.

**Do not** use just `:host` for these declarations. If you only apply them to `:host` and add a `.shadow` class on a parent element, all children with rings, shadows, or other effects will inherit those values, causing unwanted side effects, because CSS variables are inherited, `*, ::before, ::after` prevent that (in part).

But, even with `*, ::before, ::after`, certain properties require `@property` declarations to work correctly. Without these type declarations:
- Line height variables (`--tw-leading`) will inherit incorrectly
- Transitions and animations won't interpolate properly (of course)

But as far as I can see, with this code, everything works pretty well. In my case, I couldn't use the technique of injecting `@property` declarations into the host page HTML (outside the shadow root) because it breaks existing applications that use Tailwind v3. The typed `@property` declarations from Tailwind v4 are fundamentally incompatible with v3's untyped CSS variables.

```css
*, ::before, ::after {
  --tw-duration: 150ms;
  --tw-animation-delay: 0s;
  --tw-animation-direction: normal;
  --tw-animation-fill-mode: none;
  --tw-animation-iteration-count: 1;
  --tw-enter-blur: 0;
  --tw-enter-opacity: 1;
  --tw-enter-rotate: 0;
  --tw-enter-scale: 1;
  --tw-enter-translate-x: 0;
  --tw-enter-translate-y: 0;
  --tw-exit-blur: 0;
  --tw-exit-opacity: 1;
  --tw-exit-rotate: 0;
  --tw-exit-scale: 1;
  --tw-exit-translate-x: 0;
  --tw-exit-translate-y: 0;

  --tw-border-spacing-x: 0;
  --tw-border-spacing-y: 0;
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-translate-z: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
  --tw-scale-z: 1;
  --tw-scroll-snap-strictness: proximity;
  --tw-space-x-reverse: 0;
  --tw-space-y-reverse: 0;
  --tw-border-style: solid;
  --tw-divide-x-reverse: 0;
  --tw-divide-y-reverse: 0;
  --tw-gradient-from: #0000;
  --tw-gradient-via: #0000;
  --tw-gradient-to: #0000;
  --tw-gradient-from-position: 0%;
  --tw-gradient-via-position: 50%;
  --tw-gradient-to-position: 100%;
  --tw-mask-linear: linear-gradient(#fff, #fff);
  --tw-mask-radial: linear-gradient(#fff, #fff);
  --tw-mask-conic: linear-gradient(#fff, #fff);
  --tw-mask-left: linear-gradient(#fff, #fff);
  --tw-mask-right: linear-gradient(#fff, #fff);
  --tw-mask-bottom: linear-gradient(#fff, #fff);
  --tw-mask-top: linear-gradient(#fff, #fff);
  --tw-mask-linear-position: 0deg;
  --tw-mask-linear-from-position: 0%;
  --tw-mask-linear-to-position: 100%;
  --tw-mask-linear-from-color: black;
  --tw-mask-linear-to-color: transparent;
  --tw-mask-radial-from-position: 0%;
  --tw-mask-radial-to-position: 100%;
  --tw-mask-radial-from-color: black;
  --tw-mask-radial-to-color: transparent;
  --tw-mask-radial-shape: ellipse;
  --tw-mask-radial-size: farthest-corner;
  --tw-mask-radial-position: center;
  --tw-mask-conic-position: 0deg;
  --tw-mask-conic-from-position: 0%;
  --tw-mask-conic-to-position: 100%;
  --tw-mask-conic-from-color: black;
  --tw-mask-conic-to-color: transparent;
  --tw-drop-shadow-alpha: 100%;
  --tw-content: "";
  --tw-outline-style: solid;
  --tw-text-shadow-alpha: 100%;
  --tw-shadow: 0 0 #0000;
  --tw-shadow-alpha: 100%;
  --tw-inset-shadow: 0 0 #0000;
  --tw-inset-shadow-alpha: 100%;
  --tw-ring-shadow: 0 0 #0000;
  --tw-inset-ring-shadow: 0 0 #0000;
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-offset-shadow: 0 0 #0000;
}
```
