### DISCUSSION TITLE
[v4] Splitting the `--value([*])` along the separator and get the nth element by `--value` or whatever new function

### DISCUSSION THREAD

**Discussion by rozsazoltan** [tailwindlabs/tailwindcss#16781] [Ideas]
I see that currently there is no way to extract just a specific value from the result of the [`--value([*])`](https://github.com/tailwindlabs/tailwindcss/blob/37ea0c34930060eacef8995931a43cdf8d7ef128/packages/tailwindcss/src/utilities.ts#L4999-L5002) function. Is there a possibility for such an implementation in the future?

```html
<img class="clipcirc-[40%_50%_50%]" src="...">
```
```css
@utility clipcirc-* {
  /* expected result: circle(40% at 50% 50%); */
  clip-path: circle(--value([percentage:1st]) at --value([percentage:2nd]) --value([percentage:3th]));
}
```

* It was inspired by [TailwindCSS `@utility` that takes several arbitrary values](https://stackoverflow.com/q/79463817/15167500)

Here, for the purpose of the request/idea, it is irrelevant whether `40%_at_50%_50%` works, as [my answer](https://stackoverflow.com/a/79464174/15167500) shows. The idea is based on the fact that we should be able to query any element along a given (currently space) separator, in any form.
