### DISCUSSION TITLE
TW 4 with Vite ignores SCSS

### DISCUSSION THREAD

**Discussion by simPod** [tailwindlabs/tailwindcss#16793] [General]
**What version of Tailwind CSS are you using?**

For example: v4.0.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 6.2.0

**What version of Node.js are you using?**

v22

**What browser are you using?**

Chrome

**What operating system are you using?**

Macos

**Reproduction URL**

https://github.com/simPod/tw-vite-repro

**Describe your issue**

I have created

index.css

```css
@import "tailwindcss";

html {
  color: red;
  @apply bg-gray-900 text-gray-100;
}

```

index.scss

```scss
@import "tailwindcss";

html {
  color: green;
  @apply bg-yellow-500 text-black;
}

```

Imported both files in index.html.

`npm run dev`

you can see TW styles from css files are applied while from scss file are not. All other styles are applied.

![Image](https://github.com/user-attachments/assets/ffb589eb-6e3f-4a64-832b-a67be972e809)

Tailwind vite plugin somehow ignores scss files.
