### DISCUSSION TITLE
[v4] How to target screen breakpoint in CSS

### DISCUSSION THREAD

**Discussion by subproject22** [tailwindlabs/tailwindcss#16811] [Help] [answered]
I need to change CSS variable depending on breakpoint. I cant find how to target it in docs?

**Comment by wongjn** [comment]
Use an [arbitrary property class](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties) like:

```html
<div class="[--my-variable:foo] md:[--my-variable:bar]">
```

**Reply by subproject22** [reply]
I need this in CSS, declaring in `@layer theme`. I know how to use utility classes, I don't know how to reference it in CSS.

**Reply by subproject22** [reply]
```
:root {
 --variable: "";
}

// now I need to use breakpoint
```

**Reply by subproject22** [reply]
It was in docs I can't find it anymore

**Reply by wongjn** [reply, marked as answer]
You can use [the `@variant` directive](https://tailwindcss.com/docs/adding-custom-styles#adding-custom-variants) like:

```css
@theme {
  --my-variable: foo;
}

@layer theme {
  :root {
    @variant md {
      --my-variable: bar;
    }
  }
}
```
