### DISCUSSION TITLE
is it possible to have custom intellisense docs?

### DISCUSSION THREAD

**Discussion by JavierBrooktec** [tailwindlabs/tailwindcss#16895] [Help]
.css file
```css
@theme {
   --spacing-rx-1: var(--space-1); /* 12px */
 }
```
.tsx file
```tsx
export default function Foo() {
  return (
      <div className='p-1 p-rx-1' />
  );
}
```

What hover prints for each class
```css
.pr-1 {
    padding-right: calc(var(--spacing) * 1) /* 0.25rem = 4px */;
}

.p-rx-1 {
    padding: var(--space-1);
}
```

Id love to have the /* 12px */  intellisense
