### DISCUSSION TITLE
[v4] Removing/Disable an existing `@custom-variant` from production CSS

### DISCUSSION THREAD

**Discussion by rozsazoltan** [tailwindlabs/tailwindcss#16900] [Ideas]
Is there a way to disable a previously created `@custom-variant` to prevent it from being included in production unnecessarily if I don't need it?

* Inspired by: [How to disable dark mode in TailwindCSS 4](https://stackoverflow.com/q/79478252/15167500) - however I'm interested not only in dark mode but in any previously declared `@custom-variant`, including dark mode itself.
    
    Here, the dependency uses dark mode and has declared `dark:` classes as well. As a result, the styles for `dark:` classes will be included in production alongside the default classes - unnecessarily. Even if I override it with `@custom-variant` as suggested in the [answer](https://stackoverflow.com/a/79478827/15167500), the class will still be included in the production CSS unnecessarily.

* [TailwindCSS v4 Playground](https://play.tailwindcss.com/MXjvkQiqFP?file=css)
* What I can imagine for disabling it: `false`, `disabled`, `none`; perhaps `none` fits the best?

![image](https://github.com/user-attachments/assets/0e6fd4e2-32dc-4733-96df-6c6a58466767)

Now generated CSS will be:
```css
.bg-red-400 {
  background-color: var(--color-red-400);
}
.dark\:bg-green-400 {
  disabled {
    background-color: var(--color-green-400);
  }
}
```

However expected result:
```css
.bg-red-400 {
  background-color: var(--color-red-400);
}
```
