### DISCUSSION TITLE
Recommended way to add style to existing class in v4 ?

### DISCUSSION THREAD

**Discussion by hexionaut** [tailwindlabs/tailwindcss#16921] [General]
Hi,

Everything is in the title but what do you recommand ?

I want for example to add `font-variation-settings: 'opsz' 32;` to my `font-sans` class.

Should I do 

```css
.font-sans {
  font-variation-settings: 'opsz' 14;
}
```

Or 

```css
@utility font-sans {
  font-variation-settings: 'opsz' 14;
}
```

Thanks !

**Comment by wongjn** [comment]
You should be able to apply `font-variation-settings` via `@theme`, as per [the documentation](https://tailwindcss.com/docs/font-family#customizing-your-theme):

```css
@theme {
  --font-sans: Foo, sans-serif;
  --font-sans--font-variation-settings: 'opsz' 14;
}
```

**Comment by hexionaut** [comment]
@wongjn it works yes (thank you). Maybe I didn't took the wright example ... 😅 What about this : 

```css
@utility prose {
  --tw-prose-bullets: var(--color-gray-800);
  --tw-prose-counters: var(--color-gray-800);
  --tw-prose-headings: var(--color-gray-950);
}

.prose :is(h1, h2, h3, h4, h5, h6) a {
  color: inherit;
  text-decoration: inherit;
  font-weight: inherit;
}

.prose ol > li::marker {
  font-weight: 700;
  font-family: var(--font-sans);
}
```
