### DISCUSSION TITLE
Use CSS types instead of new Tailwind specificity for better language alignment

### DISCUSSION THREAD

**Discussion by brandonmcconnell** [tailwindlabs/tailwindcss#16971] [Ideas]
Tailwind CSS v4's `--value()` syntax introduces types such as `integer` and `percentage`, among others (I don't see them all documented anywhere I can easily see in the official docs).

It might be beneficial, if it's feasible in terms of effort and performance, to refactor this approach to more closely align with the actual types already supported in the CSS language itself, which supports over 50 predefined types and also supports joins like `small | medium | large` and the [combination of types](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units/CSS_data_types#combinations_of_types) like [`<length-percentage>`](https://developer.mozilla.org/en-US/docs/Web/CSS/length-percentage) (a type that can accept a length or a percentage as a value).

More documentation on that can be found here:
* [CSS data types](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units/CSS_data_types) (comprehensive list of all CSS data types)
  * demonstrates [combination of types](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units/CSS_data_types#combinations_of_types) (applicable to `percentage` types)
    * `<length-percentage>`
    * `<frequency-percentage>`
    * `<angle-percentage>`
    * `<time-percentage>`
* [`@property` syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax)
  * demonstrates how to join and clarify those types
    * A '|' combinator for multiple data types
    `syntax: "<length> | <percentage>";`
    * Space-separated list of values
    `syntax: "<color>+";`
    * Comma-separated list of values
    `syntax: "<length>#";`
    * Keywords
    `syntax: "small | medium | large";`
    * Combination of data type and keyword
    `syntax: "<length> | auto";`
    * Universal syntax value
    `syntax: "*";`
* **Related specification:** [CSS Values and Units Module Level 4](https://drafts.csswg.org/css-values/)

Alternatively, Tailwind CSS could support the existing types as a faster and built-in types system but also allow for explicit CSS data types for greater specificity and type checking.

To quickly distinguish these types, Tailwind CSS could also employ the same `type()` function seen in Chromium/Blink's recent implementation of the long-awaited `attr()` function ([specification](https://drafts.csswg.org/css-values-5/#attr-notation) | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/attr)).

#### Example:

Usage for common CSS data types:
```html
<div data-foo="blue">test</div>
<style>
  div {
    color: attr(data-foo type(<color>), red); /* using type() */
  }
</style>
```

Not needed when parsing integers as CSS units:
```html
<div data-size="10">test</div>
<style>
  div {
    font-size: attr(data-size px); /* NOT using type() */
  }
</style>
```

Read more about `attr()` here: [Chrome for Developers > Blog > CSS attr() gets an upgrade](https://developer.chrome.com/blog/advanced-attr)

### How this could look in Tailwind CSS v4

Instead of this:
```css
@utility opacity-* {
  opacity: --value([percentage]);
  opacity: calc(--value(integer) * 1%);
  opacity: --value(--opacity-*);
}
```

One could write this:
```css
@utility opacity-* {
  opacity: --value(<percentage>);
  opacity: calc(--value(<integer>) * 1%); /* support integers */
  opacity: calc(--value(<number>) * 1%); /* support integers and floats */
  opacity: --value(--opacity-*);
}
```

---

Thanks to @bramus for writing up such a good article on Chrome's new `attr()` function, which introduced some of the syntax core to this proposal.
