### DISCUSSION TITLE
[V4] Warning in build with :before

### DISCUSSION THREAD

**Discussion by joffreypersia** [tailwindlabs/tailwindcss#17059] [Help] [answered]
Hi, 

I have warnings that occures on a css file compilation. 

Here is the code that causes problem : 
```css
.ql-editor.ql-blank:before {
    color: var(--color-shade-600);
    margin-top: calc(var(--spacing) * 5);
    font-weight: 400;    /* normal */
    font-style: normal;  /* override if you had "not-italic" */
    font-size: var(--text-base);

    @variant dark {
      color: var(--color-shade-400);
    }
}
```

And here is the error : 
```bash
▲ [WARNING] Unexpected ")" [css-syntax-error]

    <stdin>:2:192111:
      2 │ ...ql-editor.ql-blank:before:where(){color:var(--color-shade-400)}[...
        ╵                                    ^
````

What am I missing?

P.S. I find the new syntax using @variant ( instead of simply using @apply dark:text-shade-400 ) rather annoying, but if it’s the recommended approach according to @adamwathan, I’ll try to stick with the new format.

**Comment by wongjn** [comment]
Seems like this could be https://github.com/tailwindlabs/tailwindcss/issues/16582#issuecomment-2666747655

**Reply by joffreypersia** [reply]
Thank you @wongjn but I don't understand how I can remove the warning.

**Reply by wongjn** [reply, marked as answer]
You'd need to do something like:

```css
.ql-editor.ql-blank {
  &::before {
    color: var(--color-shade-600);
    margin-top: calc(var(--spacing) * 5);
    font-weight: 400;    /* normal */
    font-style: normal;  /* override if you had "not-italic" */
    font-size: var(--text-base);
  }

  @variant dark {
    &::before {
      color: var(--color-shade-400);
    }
  }
}
```
