### DISCUSSION TITLE
[v4] some classes not applied after migrating to react19

### DISCUSSION THREAD

**Discussion by CiernaOvca** [tailwindlabs/tailwindcss#17192] [Help]
some of the styles are not being applied properly after trying to migrate to react19
for example background color on the button (specifically on button element, it works on div element)

DOM:
![image](https://github.com/user-attachments/assets/1cd646f2-4f23-42a3-ad46-10d0e4a4d0ce)

from the devtools I can see that there's a transparent background-color applied from base, not sure 
![image](https://github.com/user-attachments/assets/90e7e6f1-5b81-44a4-9178-0c5151a7cbc6)

styles in the button component:
```tsx
const styles = classNames(
    'flex flex-row items-center justify-center text-center gap-2 px-4 py-2 rounded-md border group',
    {
      'bg-green-400 border-green-success text-white hover:bg-green-800 hover:border-green-800 focus:bg-green-800 focus:border-green-800 disabled:bg-gray-800 disabled:border-gray-800':
        variation === 'success',
    }
  );
```

index.css file:
```css
@import ".node_modules/tailwindcss";

* {
  font-family: "Studio6", sans-serif;
}

@theme {
  --color-*: initial;
  --color-transparent: transparent;
 ...
  --color-green-success: #1a892b;
...
}
```

can anyone give me an idea of what am I doing wrong?
