### DISCUSSION TITLE
Is there an equivalent to flex-row-reverse for grids?

### DISCUSSION THREAD

**Discussion by stoem** [tailwindlabs/tailwindcss#1723] [General]
Hi there,
I'm using the grid class and grid-cols-2 and would like some control over the row order when the grid moves to single column on small screens (basically I need to reverse the row order on some rows). The equivalent of flex-row-reverse I guess.

Is this possible with grid or do I need to use flex?

Cheers 

Stefan

**Comment by tehpsalmist** [comment]
I'm not sure if this will answer your specific situation, but I tend to construct my own grid templates using named grid areas like so:

```css
.my-grid {
  @apply grid row-gap-2;
  grid-template:
    'picture article' 300px
    'ad      article' auto
  / 300px    1fr;
}

.picture {
  grid-area: picture;
}

.ad {
  grid-area: ad;
}

.article {
  grid-area: article;
}

.reversed-grid {
  @apply grid row-gap-2;
  grid-template:
    'article picture' 300px
    'article ad'      auto
  / 1fr      300px;
}
```

Like I said, might not be the answer to your exact situation, but it's at least one approach with grid, in the absence of a "reverse" option.
