### DISCUSSION TITLE
Utility Class Proposal

### DISCUSSION THREAD

**Discussion by amrks7800** [tailwindlabs/tailwindcss#17241] [Ideas]
i propose adding a no-scrollbar utility class to Tailwind CSS to provide a simple, cross-browser solution for hiding scrollbars. This class would significantly streamline the process of managing visual scrollbar presence, enhancing design consistency and user interface refinement. By incorporating the following CSS, we can achieve this functionality:

CSS
`
.no-scrollbar {
  -ms-overflow-style: none; /* IE and Edge */
  scrollbar-width: none; /* Firefox */
}

.no-scrollbar::-webkit-scrollbar {
  display: none; /* Chrome, Safari, and Opera */
}
`
This utility would eliminate the need for custom CSS or inline styles, aligning with Tailwind's core philosophy of utility-first development and improving developer efficiency.

**Comment by dvzrd** [comment]
You can create a custom utility for this:

```css
@utility no-scrollbar {
  -ms-overflow-style: none; /* IE and Edge /
  scrollbar-width: none; / Firefox */
  /* Chrome, Safari, and Opera */
  &::-webkit-scrollbar {
    display: none;
  }
}
```

See docs here: https://tailwindcss.com/docs/adding-custom-styles#complex-utilities
