### DISCUSSION TITLE
border-border error issue

### DISCUSSION THREAD

**Discussion by sammynonii** [tailwindlabs/tailwindcss#17268] [Help]
I've been trying to resolve this problem for days 
![Screenshot 2025-03-18 125901](https://github.com/user-attachments/assets/8ac3bce8-6b7f-4f19-928e-38987fc191b8)
![Screenshot 2025-03-18 131016](https://github.com/user-attachments/assets/ccee02ae-fd65-430b-8b4d-766f22a57808)

**Comment by wongjn** [comment]
As the error says, `border-border` isn't a class name that Tailwind knows about.

You could replace it with one that does exist or define it yourself:

```css
@utility border-border {
  …
}
/* Or */
@theme {
  --color-border: …;
}
```
