### DISCUSSION TITLE
Unknown at rule @container tailwindcss (unknownAtRules) shown for container queries

### DISCUSSION THREAD

**Discussion by ADTC** [tailwindlabs/tailwindcss#17261] [Help]
How can I get this fixed without disabling `unknownAtRules` entirely?

<img width="480" alt="image" src="https://github.com/user-attachments/assets/e4dbd460-fff4-4a47-ae18-1eb9ed57a451" />

---

Packages (`pnpm 10` and Astro):

```json
"@tailwindcss/vite": "^4.0.9",
"tailwindcss": "^4.0.9"
// dev:
"prettier-plugin-tailwindcss": "^0.6.11"
```

VS Code settings:

```json
"files.associations": {
  "*.css": "tailwindcss",
},
```

VS Code version information:

```yaml
Version: 1.98.2
Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
Date: 2025-03-12T13:32:45.399Z
Electron: 34.2.0
ElectronBuildId: 11161602
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Darwin arm64 23.6.0
```
