### DISCUSSION TITLE
[V4] How to create custom functional utility with spacing variables and auto suggest in vs code?

### DISCUSSION THREAD

**Discussion by katerlouis** [tailwindlabs/tailwindcss#17353] [Help] [answered]
`class="mt-...` triggers intellisense to suggest values with 0-96.

I now want to create a custom utility using the new system that also suggests the same permutations.

But the docs for functional utilities (https://tailwindcss.com/docs/adding-custom-styles#functional-utilities) fail to mention how to do that.

```css
@utility foobar-* {
  padding-left: --value(--spacing-*); // does not work
  padding-right: --spacing(*); // does not work
  padding-top: --spacing(4); // does work, but obviously ignores the utilities parameter
  padding-bottom: --spacing(--value(integer)); // does sorta work, but fails to auto suggest like `mt-*` does
}
```

custom `--spacing` tokens like in v3 dont seem to be a thing anymore 🤷 

It feels like this should be trivial and I must be missing something very obvious. 

Would appreciate the help!
