### DISCUSSION TITLE
Support custom-ident data type

### DISCUSSION THREAD

**Discussion by c-harding** [tailwindlabs/tailwindcss#17414] [Ideas]
I’m looking to create a CSS utility function rule for grid-area. I would like to generate the following rule:

```css
.grid-in-header {
  grid-area: header;
}
```

where `header` can stand in for any identifier. This corresponds to the CSS data type [&lt;custom-ident>](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident).

Background: I would like to recreate https://savvywombat.com.au/tailwind-css/grid-areas in pure Tailwind/CSS.

## Feature request

Support for the following syntax

```css
@utility grid-area-* {
  grid-area: --value(custom-ident);
}
```

## What else I’ve tried

```css
@utility grid-area-* {
  grid-area: --value(*);
}
```

(Didn’t work either)

### Arbitrary values

I know I can use the class `grid-area-[header]`, but it would be nice to be able to avoid it.

```css
@utility grid-area-* {
  /* prettier-ignore */
  grid-area: --value([*]);
}
```
