### DISCUSSION TITLE
Support @theme inline-fallback when [Referencing other variables]

### DISCUSSION THREAD

**Discussion by joe223** [tailwindlabs/tailwindcss#17422] [Ideas]
By default , When defining theme variables that reference other variables, use the inline option:
```css
@import "tailwindcss";
@theme inline {
  --font-sans: var(--font-inter);
  --font-color: red;
}
```
we will get 
```css
.font-sans {
  font-family: var(--font-inter);
  color: red;
}
```

Is it possible to support `inline-fallback`, just like:

```css
@import "tailwindcss";
@theme inline-fallback {
  --font-sans: var(--font-inter);
  --font-color: red;
}
```
we will get 
```css
.font-sans {
  font-family: var(--font-sans, var(--font-inter));
  color: var(--font-color, red);
}
```
