### DISCUSSION TITLE
@property in shadow dom

### DISCUSSION THREAD

**Discussion by imshenshen** [tailwindlabs/tailwindcss#17479] [Help]
tailwind gen code like this, I put the generated css text into a shadow dom using javascript, the @property doesn't work, it is not appear in chrome devtools .

```css
@property --tw-border-style {
    syntax: "*";
    inherits: false;
    initial-value: solid
}
```
I v tried shadowRoot.adoptedStyleSheets . doesn't work
