### DISCUSSION TITLE
[v4] Support --opacity-* theme configuration

### DISCUSSION THREAD

**Discussion by Eirmas** [tailwindlabs/tailwindcss#17553] [Ideas]
In Tailwind 3, opacity was a part of the theme configuration where you could override/extend the opacity levels with your own.

It would be nice if we could do this in version 4 too.

```css
@theme {
  --opacity-disabled: 38%;
}
```
