### DISCUSSION TITLE
Text-Shadow declares font-size

### DISCUSSION THREAD

**Discussion by saschafuchs** [tailwindlabs/tailwindcss#17560] [Help]
The current version 4.1.2 declares `font-size` instead of `text-shadow`.

![Image](https://github.com/user-attachments/assets/56307a39-d2af-43e4-a6e9-3ca7a4cbd2ad)

This happens with every text-shadow class that appears in tailwind.css

```css
 .text-shadow-lg {
    font-size: var(--text-shadow-lg);
  }
  .text-shadow-md {
    font-size: var(--text-shadow-md);
  }
  .text-shadow-xs {
    font-size: var(--text-shadow-xs);
  }
```

Tailwind is used in combination with Nuxt 3.16.3 and Nuxt UI - although I don't think Nuxt UI manipulates the `text-shadow` classes. The color classes for the shadow are also all available

```css
shadow-amber-950 {
    --tw-shadow-color: var(--color-amber-950);
  }
  .shadow-neutral-900 {
    --tw-shadow-color: var(--color-neutral-900);
  }
  .shadow-neutral-900\/80 {
    --tw-shadow-color: color-mix(in oklab, var(--color-neutral-900) 80%, transparent);
  }
```
