### DISCUSSION TITLE
Proposal to change @tailwindcss/typography configuration from JS definition to CSS declaration

### DISCUSSION THREAD

**Discussion by jubalm** [tailwindlabs/tailwindcss#17582] [Ideas]
I'm really glad to see TailwindCSS shifting from JavaScript-based configuration to more CSS-driven declarations in v4. I have notice that some plugins may not be on the same spirit (yet) and it would, especially for official plugins, make sense to follow suit.

In particular, I’d love to see [`@tailwindcss/typography`](https://github.com/tailwindlabs/tailwindcss-typography) eventually support configuration via CSS variables. I don't think i've seen it in the roadmap, but I think it could be a great improvement, especially for projects already adapting their design systems around v4.

**Use-case example:**

```css
@theme {
  --color-foreground: oklch(0.51 0 0 / 1);
  /* Allow prose styles to inherit from existing design tokens */
  --tw-prose-body: var(--color-foreground);
}
```

**Comment by craigrileyuk** [comment]
Why post an issue for a different repo and even include a link to the repo you should have posted on in the first place?

**Reply by wongjn** [reply]
Feature requests are redirected to this repo's discussions, as a centralized place. See [the `.github/ISSUE_TEMPLATE/config.yml` file in the tailwindcss-typography repo](https://github.com/tailwindlabs/tailwindcss-typography/blob/632970e3ce6fc10d1bfd8fb46cc9083d0d32986d/.github/ISSUE_TEMPLATE/config.yml#L3-L5):

```yml
- name: Feature Request
  url: https://github.com/tailwindlabs/tailwindcss/discussions/new?category=ideas
  about: 'Suggest any ideas you have using our discussion forums.'
```
