### DISCUSSION TITLE
[v4] How to disable "preflight" while using "prefix"?

### DISCUSSION THREAD

**Discussion by chenkuangkuang** [tailwindlabs/tailwindcss#17594] [Help]
I use vite to configure tailwind. According to the documentation, I have made the following settings:

@import "tailwindcss" prefix(tw);

Then I want to disable "preflight", but the documentation tells me to do this:

@layer theme, base, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
- @import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css" layer(utilities);

How are the above two configurations compatible?

**Comment by adamwathan** [comment]
Hey! This should do what you want:

https://play.tailwindcss.com/RBgk7fFeQa?file=css

```css
@layer theme, base, components, utilities;
@import "tailwindcss/theme.css" layer(theme) prefix(tw);
@import "tailwindcss/utilities.css" layer(utilities) prefix(tw);
```

**Reply by phuoccss** [reply]
setting different prefixes like below does not work. is that expected?

```
@import "tailwindcss/theme.css" layer(theme) prefix(twt);
@import "tailwindcss/utilities.css" layer(utilities) prefix(twu);
```

**Reply by wongjn** [reply]
It doesn't really make sense to have different prefixes. As evidenced [in this Tailwind Play](https://play.tailwindcss.com/shoHm8bakL), Tailwind will use the prefix that is set on the `tailwindcss/theme.css` import.

**Reply by phuoccss** [reply]
just wanna confirm that it's expected behavior. cuz Adam's answer gives the perception that having different prefixes could work, cuz the below is still valid CSS

```css
.twu:mt-4 {
  margin-top: var(--twt-...);
}
```

**Reply by wongjn** [reply]
At least, `prefix()` doesn't seem to affect anything on the `tailwindcss/utilities.css` import: https://play.tailwindcss.com/calns34f5X?file=css. Furthermore in tests such as [here](https://github.com/tailwindlabs/tailwindcss/blob/62ca1ec42d6736933b5d61c5c5e870e263929ffb/packages/tailwindcss/src/prefix.test.ts) and [here](https://github.com/tailwindlabs/tailwindcss/blob/62ca1ec42d6736933b5d61c5c5e870e263929ffb/packages/tailwindcss/src/css-functions.test.ts), the `prefix()` function is only ever attached to `@theme` or the `@import "tailwindcss";`, thus affirming its relation to the `@theme` block, which is implicitly what `@import "tailwindcss/theme.css"` contains.

**Reply by adamwathan** [reply]
I think we're going to make separate prefixes work at some point but yeah right now it's the theme one that drives everything.

**Reply by phuoccss** [reply]
thanks for looking into it

**Reply by anburocky3** [reply]
Without theme layer, the class which for example w-60 in index.html is not detecting.

I have to have the following

```css
@layer theme, base, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/utilities.css" layer(utilities);

```

This generates this:

```css
/*! tailwindcss v4.3.0 | MIT License | https://tailwindcss.com */
@layer theme {
  :root,
  :host {
    --spacing: 0.25rem;
  }
}
@layer base,components;
@layer utilities {
  .w-60 {
    width: calc(var(--spacing) * 60);
  }
}

```

Do we need themes inorder to detect classes in tailwind?

**Reply by wongjn** [reply]
You do not need `tailwindcss/theme.css` to detect classes in Tailwind. However, you need some sort of theme configuration for most class candidate values, which is what `tailwindcss/theme.css` gives you. Without `tailwindcss/theme.css`, the `--spacing` theme token is not defined, which means the `60` of has `w-60` has no associated value and thus is not generated.

You don't need to `@import` `tailwindcss/theme.css`, but to use `w-60` without it, you'd need to define `--spacing` in `@theme` yourself:

```css
@layer theme, base, components, utilities;
@import "tailwindcss/utilities.css" layer(utilities);

@theme {
  --spacing: 0.25rem;
}
```
