### DISCUSSION TITLE
Add support for `text-box` (`text-box-trim`, `text-box-edge`) CSS properties.

### DISCUSSION THREAD

**Discussion by Malien** [tailwindlabs/tailwindcss#17634] [Ideas]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-box
https://caniuse.com/mdn-css_properties_text-box
https://css-tricks.com/two-css-properties-for-trimming-text-box-whitespace/

The support has landed in Safari 18.2 and Chrome 133.

Allows us to align stuff easily with the ascendants, descendants, baseline, etc.

![image](https://github.com/user-attachments/assets/b4651b79-8b4e-4d88-a903-56a275fceedd)

vs

![image](https://github.com/user-attachments/assets/966494ed-27e9-4217-95de-79d5475ba822)

It degrades gracefully on unsupported browsers (a bit uglier layout in rare-ish circumstances). 

It is pretty fresh off the release. There aren't really common ways to use it now. The most common proprety combination I've seen is `text-box: trim-both cap`

**Comment by DhyonKeyllon** [comment]
Up

**Reply by CryberCorp** [reply]
up

**Comment by rozsazoltan** [comment]
> [!WARNING]
> The `--text-*` namespace is reserved for the `text-*` utility, so the hint may unexpectedly provide three extra suggestions. For this reason, it’s advisable not to use the `--text-*` namespace, but instead something like `--trim-*`. Read more: https://github.com/tailwindlabs/tailwindcss/discussions/17634#discussioncomment-15437102
>
> <img width="963" height="244" alt="image" src="https://github.com/user-attachments/assets/787aa2fd-a420-40a4-b424-899cf6564f24" />


> [!TIP]
> Use this:
> ```css
> @theme {
>   --texttrim-both: trim-both; /* --texttrim or --trim or --ttrim or anything */
>   --texttrim-start: trim-start;
>   --texttrim-end: trim-end;
> }
> @utility text-trim-* {
>   text-box-trim: --value(--texttrim-*, "none");
> }
> 
> @utility text-edge-* {
>   text-box-edge: --value(--textedge-*, "text", "alphabetic", "ideographic", "cap", "ex", [*]);
> }
> ```
>
> <img width="946" height="229" alt="image" src="https://github.com/user-attachments/assets/a3490078-ae36-4703-bca9-da25ae334792" />

(Original answer)

You can easily declare any utility yourself using `@utility`. Utilities might be can handled like this:
```css
@theme {
  --text-trim-both: trim-both;
  --text-trim-start: trim-start;
  --text-trim-end: trim-end;
}

@utility text-trim-* {
  text-box-trim: --value(--text-trim-*, "none");
}

@utility text-edge-* {
  text-box-edge: --value(--text-edge-*, "text", "alphabetic", "ideographic", "cap", "ex", [*]);
}
```

Of course, whether we want to introduce abbreviations depends on the use cases; for example, I would leave out box from the utility name. Edge allows a secondary parameter as well, but this can be handled in arbitrary or supplemented with a modifier.

The `text-box` property by itself is not a significant feature for TailwindCSS, since having two separate utilities remains much more readable.

References:
* https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/text-box
* https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/text-box-trim
* https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/text-box-edge

**Reply by CryberCorp** [reply]
wow perfect thx

**Reply by bengry** [reply]
These utility definitions also incorrectly set `font-size`. e.g. `.text-trim-both` evaluates to:
```css
.text-trim-both {
  font-size: var(--text-trim-both) /* trim-both */;
}
.text-trim-both {
  text-box-trim: var(--text-trim-both) /* trim-both */;
}
```

**Reply by rozsazoltan** [reply]
@bengry You're right, this is because of the `--text-*` namespace; it simply shouldn't start with `--text-*` in that case.

```css
@theme {
  --custom-text-trim-both: trim-both;
  --custom-text-trim-start: trim-start;
  --custom-text-trim-end: trim-end;
}

@utility text-trim-* {
  text-box-trim: --value(--custom-text-trim-*, "none");
}

@utility text-edge-* {
  text-box-edge: --value(--custom-text-edge-*, "text", "alphabetic", "ideographic", "cap", "ex", [*]);
}
```

And can use `@theme inline` instead of `@theme`.

I wrote the reply quickly and didn't have time to come up with a sensible and appropriate namespace prefix.

**Reply by bengry** [reply]
> And can use `@theme inline` instead of `@theme`.
> 
> I wrote the reply quickly and didn't have time to come up with a sensible and appropriate namespace prefix.

I think the `@theme` can be entirely omitted here for just this:
```css
@utility text-trim-* {
  text-box-trim: --value("none", "trim-both", "trim-start", "trim-end");
}

...
```
I'm not sure if the CSS variables give any real benefit here.

By the way, if you're using [`tailwind-merge`](https://github.com/dcastil/tailwind-merge), it would conflict with things like `text-red-200` by default, so it also needs to be extended:
```ts
import { extendTailwindMerge } from "tailwind-merge";

export const twMerge = extendTailwindMerge<"text-box-trim">({
  extend: {
    // See https://github.com/dcastil/tailwind-merge/discussions/323#discussioncomment-7336816
    // for explanation of how and why this is configured this way.
    classGroups: {
      "text-box-trim": [{ "text-trim": ["none", "start", "end", "both"] }],
    },
  },
});
```

**Reply by rozsazoltan** [reply]
The goal here isn't the variable. For example, with `@theme inline` it skips the variable entirely - try testing it. But if you don't want to add mappings, then it indeed doesn't make sense.

```css
@utility text-trim-* {
  text-box-trim: --value("none", "trim-both", "trim-start", "trim-end");
}
```
```html
text-trim-none        // use "none" name for "none" value
text-trim-trim-both   // use "trim-both" name for "trim-both" value
text-trim-trim-start  // use "trim-start" name for "trim-start" value
text-trim-trim-end    // use "trim-end" name for "trim-end" value
```

The problem in your case is that this way your class becomes `text-trim-trim-both`, which is a bit ugly - I think that's why I originally wrote it using a variable. But with `@theme inline`, Tailwind CSS omits the variable in the generated CSS. With namespaces, I have the option to give a value a unique name.

```css
@theme inline { /* could use @theme inline if you don't want variables in generated CSS */
  --custom-namespace-both: trim-both;
  --custom-namespace-start: trim-start;
  --custom-namespace-end: trim-end;
}

@utility text-trim-* {
  text-box-trim: --value(--custom-namespace-*, "none");
}
```
```html
text-trim-none   // use "none" name for "none" value
text-trim-both   // use "both" name for "trim-both" value
text-trim-start  // use "start" name for "trim-start" value
text-trim-end    // use "end" name for "trim-end" value
```

(For the sake of the example, I generalized the namespace name (`--custom-namespace-`), so I'm using `-*` to indicate the name - `both` in this case - and then the value, which is `trim-both`.)

**Reply by bengry** [reply]
> The goal here isn't the variable. For example, with `@theme inline` it skips the variable entirely - try testing it. But if you don't want to add mappings, then it indeed doesn't make sense.

WDYM by "mappings"? Since you have to list all possible values anyway, does it matter if it's within the `--value()` or as part of `@theme { }`? Although I guess that's not what you meant.

**Reply by rozsazoltan** [reply]
I meant a name - value (e.g. both - trim-both) pair. I expanded on it a bit with a later edit. In your case, this is why trim ends up being repeated.

**Reply by bengry** [reply]
> I meant a name - value (e.g. both - trim-both) pair. I expanded on it a bit with a later edit. In your case, this is why trim ends up being repeated.

Just saw the edit, thanks for the thorough explanation. Much appreciated.

**Comment by michaelcummings12** [comment]
There's a tailwind plugin you can install instead of defining custom classes yourself!!

https://www.npmjs.com/package/tailwindcss-text-box-trim

**Reply by rozsazoltan** [reply]
It's not too much effort to define it ourselves; I think it's better to avoid introducing yet another dependency if possible. If this were something more complex than the anchor, I'd agree that it would be necessary.

* https://github.com/michaelcummings12/tailwindcss-text-box-trim/blob/main/index.css#L1-L21
* https://github.com/tailwindlabs/tailwindcss/discussions/17634#discussioncomment-15016605

**Reply by michaelcummings12** [reply]
I totally get what you're saying. 

For me, I want to have these classes available in multiple different projects. I am always a fan of DRYing when possible. I prefer installing a lightweight package that makes the classes available to me vs having to copy-paste the same code over and over again.

Just boils down to personal preference. Plus, it gave me a reason to publish my first npm package!!! 🚀

**Comment by sovetski** [comment]
Any "offical" update here? @adamwathan @RobinMalfait

**Comment by ryanleichty** [comment]
Here's the setup I went with to suit my needs:

```css
@utility trim {
  text-box: trim-both cap alphabetic;
}

@utility trim-cap {
  text-box: trim-both cap alphabetic;
}

@utility trim-ex {
  text-box: trim-both ex alphabetic;
}

@utility trim-none {
  text-box-trim: none;
}

@utility trim-start {
  text-box-trim: trim-start;
}

@utility trim-end {
  text-box-trim: trim-end;
}
```

**Comment by andi1984** [comment]
Any official update on this? As this now seems to have good browser support as Firefox released it as well.

Cf. https://www.youtube.com/watch?v=Tdpoa1j5fcU

**Comment by jonnitto** [comment]
As not every value is allowed, but I still want to support all my cases, I came up with this solution:


```css
@theme inline {
  --texttrim-both: trim-both;
  --texttrim-start: trim-start;
  --texttrim-end: trim-end;

  --textedge-start-text: text;
  --textedge-start-cap: cap;
  --textedge-start-ex: ex;
  --textedge-end-alphabetic: alphabetic;
  --textedge-end-text: text;
}

@utility text-trim-* {
  text-box: trim-both --value(--textedge-start-*) --modifier(--textedge-end-*, --default(alphabetic));
  text-box: trim-both --value([*]);
  text-box-trim: --value(--texttrim-*, "none");
}
```

Like this, I can write beside `text-trim-ex` also `text-trim-ex/text`.

I made a small demo of this:

https://codepen.io/editor/jonnitto/pen/01a06c5d-5e31-7851-8ca5-26b376b71ed5
