### DISCUSSION TITLE
Customizing animation repeat count and animation duration with utilities

### DISCUSSION THREAD

**Discussion by rozsazoltan** [tailwindlabs/tailwindcss#17659] [Show and tell]
### Update

After understanding the implementation of variables, you can familiarize yourself with the `animation-iteration-count` and `animation-duration` property, which has been part of the baseline since 2015.

* [`animate-repeat-*` and `animate-duration-*` with CSS variables](https://stackoverflow.com/a/79570372/15167500)
* [`animate-repeat-*` and `animate-duration-*` with CSS animation properties](https://stackoverflow.com/a/79570405/15167500)
* [CSS: `animation-iteration-count`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-iteration-count) - MDN Docs
* [CSS: `animation-duration`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-duration) - MDN Docs

```css
@import "tailwindcss";

/* Utility for Animation Timing */
@utility animate-duration-* {
  animation-duration: --value([*]);
  animation-duration: calc(--value(integer) * 1s);
}

/* Utility for Repeat Count */
@utility animate-repeat-* {
  animation-iteration-count: --value(integer, 'infinite', [*]);
}
```

* [TailwindCSS v4 Playground](https://play.tailwindcss.com/kNVGIJsGge?file=css)

### Original Code

The other day, I created utilities for customizing the repeat count and timing of any animation. I’ll leave them here in case they are useful for someone else:

* [How to stop TailwindCSS animation after a set time](https://stackoverflow.com/a/79570372/15167500)

In the final solution, I was assisted by Wongjn's answer. The default animations can be overridden by using `@theme inline` instead of `@theme` to declare the animation. This doesn’t add any extra overhead if the animations used are already part of the project, as they will end up being part of the compiled CSS anyway.

* [@utility for creating to modify the repeat count of pre-declared animations](https://stackoverflow.com/a/79570361/15167500)

### Utility for Repeat Count - `animate-repeat-*`

```css
@utility animate-repeat-* {
  --animate-bounce-count: --value(integer);
}

@utility animate-repeat-infinite {
  --animate-bounce-count: infinite;
}
```

* [TailwindCSS v4 Playground](https://play.tailwindcss.com/vFqmDEU4tq?file=css)

### Utility for Animation Timing - `animate-duration-*`

```css
@utility animate-duration-* {
  --animate-duration: calc(--value(integer) * 1s);
}
```

* [TailwindCSS v4 Playground](https://play.tailwindcss.com/vzDn9XvCZT?file=css)
