### DISCUSSION TITLE
How to make design tokens responsive in Tailwind 4?

### DISCUSSION THREAD

**Discussion by katerlouis** [tailwindlabs/tailwindcss#17655] [Help]
My `--spacing-foo` should be `20px` on mobile and `40px` on desktop. Nothing fancy; 

Yet, the following results in 40px across all viewports:

```css
/* main.css */
@theme {
  --spacing-foo: 20px;
}

@media (width > 600px) {
  @theme {
    --spacing-foo: 40px;
  }
}
```

Changing the nesting and putting media query inside `@theme` does not work as it breaks the site.

---

The workaround for that (and I fear the intended workflow) is not satisfactory for me either.

```
/* main.css */
@theme {
  --spacing-foo-small: 20px;
  --spacing-foo-large: 40px;
}
```
```html
<div class="px-foo-small @md:px-foo-large">...
```

Having to do that everywhere I want to use spacing `foo` is obnoxious and for goes against the concept of globalized design tokens. Using `@md:px-foo-large` can be easily forgotten and adding multiple breakpoints, again globally, requires to go through each and every usage instance and add `@lg:px-foo-xlarge`.

--- 

Since I could not find anything regarding this in the docs, I wanted to ask how you would realize the desired behavior?

**Comment by wongjn** [comment]
Replace the second `@theme` with `:root`:

```css
@theme {
  --spacing-foo: 20px;
}

@media (width > 600px) {
  :root {
    --spacing-foo: 40px;
  }
}
```
https://play.tailwindcss.com/XmIq4n7S04?file=css

**Reply by J-S-Bach** [reply]
Is it also possible to use tailwind breakpoints? According to [this](https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries), it is not possible to use css variables like this: 

```css
@theme {
  --spacing-foo: 20px;
}

@media (width > var(--breakpoint-md)) {
  :root {
    --spacing-foo: 40px;
  }
}
```


But maybe there is another way?

**Reply by wongjn** [reply]
You can use `@variant` like:

```css
@theme {
  --spacing-foo: 20px;
}

@variant md {
  :root {
    --spacing-foo: 40px;
  }
}
```
Or `theme()` like:
```css
@theme {
  --spacing-foo: 20px;
}

@media (width > theme(--breakpoint-md)) {
  :root {
    --spacing-foo: 40px;
  }
}
```
