### DISCUSSION TITLE
@utility for creating to modify the repeat count of pre-declared animations

### DISCUSSION THREAD

**Discussion by rozsazoltan** [tailwindlabs/tailwindcss#17658] [Help] [answered]
I wanted to declare a `@utility` called `animate-repeat-{number}`, whose function is to modify a variable at usage time; a variable I tie to the repeat count in all my animations. This works.

```css
@utility animate-repeat-* {
  --animate-repeat-count: --value(integer);
}

@utility animate-repeat-infinite {
  --animate-repeat-count: infinite;
}
```

However, when I declare the animation in `@theme` (or if it exists by default, like animate-bounce), the `.animate-bounce { ... }` class receives the animation via a variable:
```css
.animate-bounce {
  animation: var(--animate-bounce);
}
```
The problem here is that even though I override the value of `--animate-bounce`, DevTools (F12) still highlights it as `bounce 1s infinite` instead of `bounce 1s var(--animate-repeat-count, infinite)`.

* [Not working example TailwindCSS v4 Playground (with `@theme`)](https://play.tailwindcss.com/kffMrZqizU?file=css)

<img width="250" src="https://github.com/user-attachments/assets/d2fe5819-9e6f-41d5-b80c-949bf6436ab0">

<img width="250" src="https://github.com/user-attachments/assets/d3474255-4526-4e27-9033-a2db70e9d204">

If I declare the animation in `@utility`, the issue is that the default animation from `@theme` takes precedence. Overriding it with !important works fine.

Naturally, without `!important`, the `theme` layer is stronger, and I can't override it; that's why it works with `!important`.

* [Not working example TailwindCSS v4 Playground (without important)](https://play.tailwindcss.com/jHO6b4dkwZ?file=css)

<img width="250" src="https://github.com/user-attachments/assets/3db26998-cc64-4c70-9bb9-13479f85ede6">

* [Successfully example TailwindCSS v4 Playground (with important)](https://play.tailwindcss.com/MAwB1fCiVp?file=css)

<img width="250" src="https://github.com/user-attachments/assets/471280bf-ff95-4495-9d39-dc9fcbbe6a21">

**How can I make the animation declared in `@theme` work correctly by default, without having to use !important?** I would expect the following code to work the same way as the [last one from the three shared playgrounds](https://play.tailwindcss.com/MAwB1fCiVp?file=css):

```css
@theme {
  --animate-bounce: bounce 1s var(--animate-repeat-count, infinite);
}

@utility animate-repeat-* {
  --animate-repeat-count: --value(integer);
}

@utility animate-repeat-infinite {
  --animate-repeat-count: infinite;
}
```
```html
<div class="p-10 text-center">
  <button class="mx-auto animate-bounce bg-green-300 px-8 py-2 animate-repeat-2">
    Bounce animation repeated 2 times in 1s. 
  </button>
</div>
```
