### DISCUSSION TITLE
@prefix directive

### DISCUSSION THREAD

**Discussion by jameslkingsley** [tailwindlabs/tailwindcss#1781] [Ideas]
It would be awesome if there was a `@prefix` directive similar to how `@responsive` or `@screen` works. What it would do is prefix all classes inside it with the configured Tailwind prefix. This then means the prefix can be kept and maintained in one place and turned on and off based on dev/production build.

Input:
```js
/* tailwind.config.js */

{
  prefix: 'tw-'
}
```

```css
/* app.css */

@prefix {
  .foo-bar {
    color: red;
  }
}
```

Output:
```css
.tw-foo-bar {
  color: red;
}
```

It should also interpret variants, eg:

Input:
```css
@prefix {
  @variants hover {
    .foo-bar {
      color: red;
    }
  }
}
```

Output:
```css
.hover\:tw-foo-bar:hover {
  color: red;
}
```
