### DISCUSSION TITLE
Referencing prefixed utilities

### DISCUSSION THREAD

**Discussion by fedcho** [tailwindlabs/tailwindcss#17895] [Help]
Hello people. I'm building a reusable components library that will be shared across multiple projects that may or not use prefix and need to achieve something like this:

```css
@import "tailwindcss" prefix(ui);

@theme {
  /* ... */
}

/* This is comming from another file */

@utility btn-primary { /* <-- This is automatically prefixed */
  padding: --spacing(1) --spacing(2);
  background-color: blue;
  color: white;

  &.btn-flat {  /* <-- This is not automatically prefixed and I don't know the prefix, so how to make it work? */
    border: 1px solid blue;
  }

}

@utility btn-flat { /* <-- This is automatically prefixed */
  background-color: white;
  color: gray;
}

```

Any ideas on how to to do it?
Link to playground: https://play.tailwindcss.com/x08C02P0rR?file=css

Thank you!
