### DISCUSSION TITLE
(Tailwind v4) Different Color set for element like text color, background color etc

### DISCUSSION THREAD

**Discussion by keshavkatwe** [tailwindlabs/tailwindcss#17899] [Help] [answered]
How can we achieve the same behaviour in tailwind v4, Using only css file

```
module.exports = {
  theme: {
    extend: {
      textColors: {
        'primary': red,
      },
     backgroundColor: {
        'primary': blue,
     }
    }
  }
}
```

I am not able to achieve the same in tailwind v4, I have a design system with predined colors for text, background, border.
Can someone help me.?

**Comment by wongjn** [comment, marked as answer]
You can use `--text-color` and `--background-color` namespaces respectively:

```css
@theme {
  --text-color-primary: red;
  --background-color-primary: blue;
}
```

**Reply by keshavkatwe** [reply]
thank you @wongjn .

**Reply by keshavkatwe** [reply]
@wongjn How can we achieve same behaviour for space and size. I am trying below
```
@theme {
    --space-xxs: 4px;
    --space-xs: 8px;

    --size-18: 18px;
    --size-24: 24px;
}
```

this is not working.

**Reply by wongjn** [reply]
Seems to be working [in this Tailwind Play](https://play.tailwindcss.com/dQt1S5eipg) which could suggest it is something particular to your project.

**Reply by keshavkatwe** [reply]
My bad, I was trying to set spacing like padding, margin, gap and size like h,w etc. Is there a unified way to set spacing and size.

**Reply by wongjn** [reply]
For those, use `--spacing-*` like:

```css
@theme {
    --spacing-xxs: 4px;
    --spacing-xs: 8px;
}
```

**Reply by keshavkatwe** [reply]
Thank you @wongjn , I got the solution.

**Reply by JulienLecoq** [reply]
Mhh interesting, I've been searching for something like this for a long time. Is it documented somewhere?

This thing:

```css
@theme {
  --text-color-primary: red;
  --background-color-primary: blue;
 }
```
