### DISCUSSION TITLE
[v4] passing variables to predefined variables

### DISCUSSION THREAD

**Discussion by TheMikeyRoss** [tailwindlabs/tailwindcss#17927] [Help] [answered]
I want to have a custom class `rounded-inner-[10px]` where the 10px is the padding. and the returned value is:
 `var(--radius) - 10px`

How can I achieve that? I can't figure out how to let my custom class name accept arbitrary values for the padding.

**Comment by wongjn** [comment, marked as answer]
```css
@utility rounded-inner-* {
  property: calc(var(--radius) - --value([length]));
}
```
