### DISCUSSION TITLE
[v4] Removing default breakpoints not reflected in `plugin()` API/method

### DISCUSSION THREAD

**Discussion by flx-sta** [tailwindlabs/tailwindcss#17949] [Ideas]
**What version of Tailwind CSS are you using?**

`v4.0.1`

**What build tool (or framework if it abstracts the build tool) are you using?**

- @tailwindcss/cli 4.0.0
- @tailwindcss/postcss 4.0.0
- postcss 8.5.1

**What version of Node.js are you using?**

For example: v12.0.0

**What browser are you using?**

v20.13.0

**What operating system are you using?**

macOS 14.6.1 (23G93)

**Reproduction URL**

https://codesandbox.io/p/live/27a50c21-9a15-410a-be6e-f846fdbb6102

Run the `build` script and check the terminal output.

**Describe your issue**

When defining my `@theme` with :
```css
@theme {
  --breakpoint-*: initial;

  --breakpoint-phone: 30rem;
  --breakpoint-tablet: 48rem;
  --breakpoint-default: 75rem;
}
```
I was expecting for only my custom breakpoints/screens to exist.
But instead it's adding them **on top** of the existing one when definition a plugin:

```shell
{
  sm: '40rem',
  md: '48rem',
  lg: '64rem',
  xl: '80rem',
  '2xl': '96rem',
  phone: '30rem',
  tablet: '48rem',
  default: '75rem',
  __CSS_VALUES__: { phone: 0, tablet: 0, default: 0 }
}
≈ tailwindcss v4.0.1

Done in 113ms
```

-----

Unless, is it expected to use the `__CSS_VALUES__` object?
