### DISCUSSION TITLE
[V4] Declaring @utility in vue SFC

### DISCUSSION THREAD

**Discussion by Doltario** [tailwindlabs/tailwindcss#17986] [Help]
Hi everyone,

I roamed in this forum and in the issues section but I couldn't find exactly what I was looking for. Please let me know if you think the answer is somewhere else !

### Context
 I am trying to migrate a component library from TW3 to TW4 with:
```JSON
   "@tailwindcss/vite": "^4.1.6",
    "tailwindcss": "^4.1.6",
    "vue": "^3.5.13"
    "vite": "^6.3.5",
```

Since I'm implementing a design system, I have components with color variations (`alert--red`, `alert--green`, …).

So far, with TW3, the previous devs were using SCSS to generate right classes: 
```scss
 @each $color in $colors {
    .alert--#{$color} {
      @apply tw-bg-#{$color}-lighten6 tw-border-#{$color}-lighten5 tw-text-#{$color} tw-border-l-#{$color};
    }
```
And it worked just fine.

But from what I read, using pre-processors is not really tailwind-ish. So I read on how to replace SCSS.
I read [here](https://tailwindcss.com/docs/styling-with-utility-classes#when-to-use-inline-styles) that inline style is the recommanded way but I was more attracted by using `@components` [layer](https://tailwindcss.com/docs/adding-custom-styles#adding-component-classes) but the wildcard (as `@utility`) seems to not be designed that way :
```
@component mylib-alert--* {
  @apply tw:bg-[--value(--color-*)];
}
```

So I considered using the layer `utilities` accepting that my components classes would be at the same level as TW utilities. Something so: 

```css
/* style.css */
@import 'tailwindcss' prefix(tw);

@theme {
  --color-*: initial; /* Resets Tailwind default color (https://tailwindcss.com/docs/theme#overriding-the-default-theme) */
  --color-green: #00FF00;
}

@utility mylib-alert--* {
  @apply tw:bg-[--value(--color-*)];
}
```

--> This is "dynamic" enough to me and it actually works fine when the utility is defined in the global `style.css`. Nevertheless as soon as I move it to the style block of the SFC "Alert.vue" it seems it is not compiled anymore.

### Reproduction
[Here](https://stackblitz.com/edit/vitejs-vite-zbpwmnub) I tried: 
- inside a SFC "scoped" style block
- inside a SFC regular style block (no "scoped" tag)

### Questions
1/ Is it not really "tailwind-ish" to attempt to do so ? I liked the idea that my components implements their own color variation class though…
2/ What do you think about using SCSS to cover that case ?

Thanks for reading :)
