### DISCUSSION TITLE
Expand support for line height units

### DISCUSSION THREAD

**Discussion by aaronadamsCA** [tailwindlabs/tailwindcss#17997] [Ideas]
The `lh` unit is relatively new, has good browser support, and can be extremely useful:

https://play.tailwindcss.com/9H1DQZ3p72

<img width="1450" alt="image" src="https://github.com/user-attachments/assets/cb18fad2-3612-4877-8cdc-e357628a3710" />

It's currently possible to make this slightly more readable/usable with custom utilities:

```css
@utility px-lh-* {
  padding-inline: calc(--value(integer) * 1lh);
  padding-inline: calc(--value(ratio) * 1lh);
}
@utility py-lh-* {
  padding-block: calc(--value(integer) * 1lh);
  padding-block: calc(--value(ratio) * 1lh);
}
/* etc. */
```

https://play.tailwindcss.com/P5o9mhj199

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/88589a2c-a4ed-40c0-ae9a-381f27a1fd92" />

But what I'd really love to see are some first-class utilities for this, as the `lh` unit feels "very Tailwind" and could be extremely useful for component libraries.
