### DISCUSSION TITLE
Specifying border spacing scale in Tailwind V4?

### DISCUSSION THREAD

**Discussion by Aurailus** [tailwindlabs/tailwindcss#18027] [Help]
I'm making an HTML & CSS-based game which uses tailwind for layouting. In my css file, I have `@theme { --spacing: var(--scale); }` so that I can change the scale of all of the elements on the page easily. Unfortunately, the `border-n` utilities don't seem to inherit from this spacing scale. Is there a way to customize what they mean so they also use `--spacing`?

**Comment by Advait251206** [comment]
This is a good Tailwind v4 question — and the key point is:

> ❗ `border-*` utilities do NOT use the spacing scale

So what you’re trying to do (making borders scale with `--spacing`) won’t work automatically.

---

# 🧠 Root cause

In Tailwind v4:

| Utility | Uses spacing scale? |
|----------|--------------------|
| `p-*`, `m-*`, `gap-*` | ✅ yes (`--spacing`) |
| `border-*` (width) | ❌ no |
| `rounded-*` | ❌ separate radius scale |
| `outline-*` | ❌ separate system |

So:

```
border-2 → NOT derived from --spacing
```

It’s hardcoded to the **border width scale**, not spacing.

---

# ❗ Why your approach doesn’t affect borders

You did:

```css
@theme {
  --spacing: var(--scale);
}
```

That only affects:

- padding
- margin
- width/height spacing utilities
- gap
- translate, etc.

But **border width is intentionally separate** because:

> border width is a visual stroke system, not layout spacing

---

# 🟡 So can you override border scale globally?

Yes — but NOT via `--spacing`.

You must override the **border width tokens** instead.

---

# 🟢 Correct solution

## ✔ Option 1 — Override border width scale in `@theme`

```css
@theme {
  --border-1: calc(1px * var(--scale));
  --border-2: calc(2px * var(--scale));
  --border-4: calc(4px * var(--scale));
}
```

Now:

```html
border-2
```

will scale with your custom system.

---

## ✔ Option 2 — Full custom border scale (recommended for games)

```css
@theme {
  --border-1: calc(1px * var(--scale));
  --border-2: calc(2px * var(--scale));
  --border-3: calc(3px * var(--scale));
  --border-4: calc(4px * var(--scale));
  --border-8: calc(8px * var(--scale));
}
```

---

## ✔ Option 3 — If you want EVERYTHING to scale (game UI approach)

Instead of touching borders individually:

```css
@theme {
  --scale: 1.2;

  --spacing: calc(0.25rem * var(--scale));
  --border-1: calc(1px * var(--scale));
  --radius-md: calc(0.375rem * var(--scale));
}
```

This gives you:

✔ scalable UI system  
✔ consistent proportions  
✔ game-friendly zoom system  

---

# 🧠 Important mental model

Tailwind v4 separates tokens into independent systems:

```
spacing → layout
border → stroke system
radius → shape system
typography → text system
```

👉 They do NOT inherit from each other

---

# ❗ Why Tailwind does this

Because linking them would cause:

- broken visual hierarchy
- unpredictable scaling
- accessibility issues (borders becoming too thick/thin)

So border scale is intentionally isolated.

---

# 🚀 Best practice for your use case (game UI)

Since you are building a game UI:

### ✔ Treat `--scale` as a global multiplier

Then explicitly apply it:

```css
@theme {
  --scale: 1;

  --spacing: calc(0.25rem * var(--scale));
  --border-1: calc(1px * var(--scale));
  --border-2: calc(2px * var(--scale));
  --radius-md: calc(6px * var(--scale));
}
```

---

# 🟢 Final answer

- ❌ `border-*` does NOT use spacing scale
- ❌ cannot inherit from `--spacing`
- ✔ must override `--border-*` tokens directly
- ✔ best solution is scaling border tokens manually via `@theme`

---

If this answers your question, please consider marking it as the accepted answer so others with the same issue can find it more easily.

If you found my answer helpful, I'd also appreciate it if you could follow me on GitHub: https://github.com/Advait251206 and, if you like my work, consider starring my repositories. ⭐
