### DISCUSSION TITLE
Custom functional utility with color values

### DISCUSSION THREAD

**Discussion by jacksleight** [tailwindlabs/tailwindcss#18041] [Help] [answered]
What's the correct way to write a custom functional utility that uses color and opacity values? I have this:

```css
@utility overlay-* {
    border-image: linear-gradient(to top, --value(--color-*), --value(--color-*)) fill 1;
}
```

Which works when called with `overlay-black`, giving:

```css
.overlay-black {
    border-image: linear-gradient(to top, var(--color-black), var(--color-black)) fill 1;
}
```

But when called with an opacity as `overlay-black/50` no class is created.

**Comment by wongjn** [comment, marked as answer]
```css
@utility overlay-* {
    --alpha: calc(1% * --modifier(integer));
    --color: --alpha(--value(--color-*) / var(--alpha, 100%));
    border-image: linear-gradient(to top, var(--color), var(--color)) fill 1;
}
```
`--modifier()` is where the value after the slash. If there is no slash, the declaration is removed.
`--alpha()` is Tailwind syntax sugar for `color-mix()`.

https://play.tailwindcss.com/BAEVBTPuJc
