### DISCUSSION TITLE
[v4] How to have tailwind css vars applied not to :root?

### DISCUSSION THREAD

**Discussion by artaommahe** [tailwindlabs/tailwindcss#18108] [Help]
We're migrating from js-based config to tailwind-based. We have a specific case when two sets of tailwind tokens (two different themes) exist on the same page together - we're slowly migrating from the old design to the new one. 

With js-based config we've resolved conflicts with adding `important: '.new_design'` to the second config and nesting all new components under `.new_design` class. We're not using prefixes cause they make dx worse and we want to use regular tailwind classes like `p-5 text-primary` everywhere, but they should have different values for different components/themes.

With css-based config im trying to do smthing similar for the new design theme
```css
@layer theme, base, components, utilities;

@source "../new_design";

@theme inline {
  --*: initial;

  --text-color-primary: #123456;

  --spacing-5: 0.5rem;
}

.new_design {
  @import 'tailwindcss/theme' layer(theme);
  @import 'tailwindcss/utilities' layer(utilities);
}
```
Note the `initial` modifier on `@theme` - without it tailwind sets tailwind-related css vars on `:root {}` and they conflict with similarly named css vars from another config https://play.tailwindcss.com/MD1r1Zwm36?file=css.
```css
:root, :host {
  --text-color-primary: #123456;
  --spacing-5: 0.5rem;
}
.new_design {
  @layer theme;
  @layer utilities {
    .p-5 {
      padding: var(--spacing-5);
    }
    .text-primary {
      color: var(--text-color-primary);
    }
  }
}
```

Using inline works fine in general, but it doesn't allow us to use tailwind-related css variables, like `var(--text-color-primary)`, in js code https://tailwindcss.com/docs/upgrade-guide#theme-values-in-javascript or in css modules (especially to map some library's css vars to tailwind css vars) https://tailwindcss.com/docs/upgrade-guide#using-apply-with-vue-svelte-or-css-modules, cause those tailwind css vars are not set for the inlined theme.
 
Question: how to tell tailwind to set tailwind-related variables not on the `:root {}` but on some specified selector?
