### DISCUSSION TITLE
How to Create a Custom CSS Color Utility with Opacity Support (Tailwind text-* Replica)

### DISCUSSION THREAD

**Discussion by AsadGG** [tailwindlabs/tailwindcss#18124] [Help] [answered]
I'm attempting to create a custom CSS utility that behaves similarly to Tailwind CSS's built-in text-* classes, specifically for applying text colors.
in v3 i used match utilities

```js
  'ion-text': (value) => ({
            '--color': withOpacity(value),
          }),
```
but in v4
```css
@utility ion-text-* {
  --color: --value(--color- *);
}
```
This utility successfully applies the base color. However, If I try to use this utility with an opacity value (e.g., ion-text-primary/50), it fails.

i want an exact functional replica of Tailwind's text-* utility, which allows for both color application and dynamic opacity control (e.g., text-blue-500 and text-blue-500/50).

Could anyone provide guidance on how to modify this utility,  Any insights into how Tailwind achieves this with its text-* utility ?

**Comment by wongjn** [comment, marked as answer]
As per [the documentation](https://tailwindcss.com/docs/adding-custom-styles#modifiers), you'd use `--modifier()`:

```css
@utility ion-text-* {
  --foo: calc(--modifier(integer) * 1%);
  --color: --alpha(--value(--color- *) / var(--foo, 100%));
}
```

As for how Tailwind core achieves this with its `text-*` utility, start from here:

https://github.com/tailwindlabs/tailwindcss/blob/ed3cecd39dac6e6b08feb6a8f3476f8bf741465e/packages/tailwindcss/src/utilities.ts#L4999

**Reply by AsadGG** [reply]
Thanks a lot! I've added [color] into the code, and it now accepts arbitrary values.

```css
@utility ion-text-* {
  --opacity: calc(--modifier(integer) * 1%);
  --color: --alpha(--value(--color- *, [color]) / var(--opacity, 100%));
}
```

 I'm also curious about the 'alpha' you used. I thought we should do it like this:
```css
@utility ion-text-* {
  --opacity: calc(--modifier(integer) * 1%);
  --color: color-mix(
    in oklab,
    --value(--color- *, [color]) var(--opacity, 100%),
    transparent
  );
}
```
