### DISCUSSION TITLE
Allowing grouped listing of variants in the `@variant` directive, similar to how classes are grouped using colons (:).

### DISCUSSION THREAD

**Discussion by rozsazoltan** [tailwindlabs/tailwindcss#18152] [Ideas]
This is what it currently looks like if, for some reason, I want to nest at least two variants using `@variant`:
* [Tailwind Play](https://play.tailwindcss.com/zZICAEZNHQ?size=670x720&file=css)
```css
.my-element {
  background: white;

  @variant dark {
    @variant hover {
      background: black;
    }
  }

  @variant sm {
    @variant max-lg {
      background: green;
    }
  }
}
```

It would be more intuitive if Tailwind could also interpret this syntax:
* [Tailwind Play](https://play.tailwindcss.com/obF8XzZE0l?size=670x720&file=css)
```css
.my-element {
  background: white;

  @variant dark:hover {
    background: black;
  }

  @variant sm:max-lg {
    background: green;
  }
}
```
