### DISCUSSION TITLE
Final bundle (after Purge CSS) full of "--space-x-reverse"

### DISCUSSION THREAD

**Discussion by frederikhors** [tailwindlabs/tailwindcss#1815] [Help]
My final bundle (after PurgeCSS) is full of `--space-x-reverse` which take a lot of bytes.

Is there a way (similar to purgecss) to replace any `--space-x-reverse` (or similar) to their own values?

**Comment by frederikhors** [comment]
Maybe this can help: https://github.com/MadLittleMods/postcss-css-variables ?

**Comment by emartini** [comment]
I've tried using that plugin but it fails in some cases

**original**

```css
.hover\:bg-blue-500:hover {
  --bg-opacity: 1;
  background-color: #4299e1;
  background-color: rgba(66, 153, 225, var(--bg-opacity))
}
```

**after `postcss-css-variables`**
```css
.hover\:bg-blue-500:hover {
  background-color:#4299e1;
  background-color:undefined
}
```
