### DISCUSSION TITLE
Option to disable generation of @theme css custom properties

### DISCUSSION THREAD

**Discussion by phuoccss** [tailwindlabs/tailwindcss#18200] [Help]
I have a variable that's set up like this

```css
[data-theme='red'] {
  --text-color-primary: red;
}

[data-theme='blue'] {
  --text-color-primary: blue;
}

[data-theme='red'] {
  --text-color-primary: green;
}
```

To use this custom property as a utility class `.text-primary`, I have the following `@theme` config:

```css
@theme {
  --text-color-primary: var(--text-color-primary);
}
```

Note how the custom property names are the same, because of similar naming conventions.

Here's the generated output CSS, which I want to disable, since it's redundant for my use case.

```css
:root, :host {
  --text-color-primary: var(--text-color-primary);
}
```

What's the recommended way to handle this?

**Comment by wongjn** [comment]
You can't remove it via Tailwind alone but you could have one of the themes as the "default" case in @theme. Red for example:

```css
@theme {
  --text-color-primary: green;
}

* {
  [data-theme='blue'] & {
    --text-color-primary: blue;
  }
}
```

Otherwise, you can process the CSS after Tailwind has built it to remove the obsolete declaration.


~~You could try using `@theme inline` like:~~

```css
@theme inline {
  --text-color-primary: var(--text-color-primary);
}
```
Nope doesn't work, since it needs to reference itself `var(--text-color-primary);`, which causes it to be output in the `@theme` block: https://play.tailwindcss.com/rBjCuH2r5s?file=css
