### DISCUSSION TITLE
Add ability for custom breakpoints to be defined by a css variable

### DISCUSSION THREAD

**Discussion by michal-skoula** [tailwindlabs/tailwindcss#18283] [Ideas]
Normally CSS doesn't allow you to use a css variable inside of a media query:

```css
@media (width >= var(--breakpoint-sm) ) {
  display: none;
}
``` 
This only works with preprocessors.

But when i define a breakpoint in my theme:

```css
@theme {
  --breakpoint-nav: var(--breakpoint-sm);
}
```

Tailwind simply "passes" the value from the css variable into the custom one, which won't work because CSS doesn't allow it.
![image](https://github.com/user-attachments/assets/84e39512-c24f-4975-9ca5-471fc408928d)

I think it would be a really nice quality of life feature for tailwind to compile the css variable into a string like `40rem` or `640px` so that the media query still works.

P.S.: Apologies if my contribution is not following conventions, it's my first time contributing 😅
