### DISCUSSION TITLE
[V4] Is this the correct way to add element root specificity ?

### DISCUSSION THREAD

**Discussion by AsadGG** [tailwindlabs/tailwindcss#18295] [Help] [answered]
I'm trying to achieve root element specificity for Tailwind CSS classes in v4, similar to how important: '#root' works in v3. but the output CSS from Tailwind Intellisense doesn't seem to apply the #root specificity as expected.

Attempted Tailwind CSS v4 Configuration:
```css
@layer theme, base, components, utilities;

@import 'tailwindcss/theme.css' layer(theme) prefix(tw);
@import 'tailwindcss/preflight.css' layer(base);
#root {
  @import 'tailwindcss/utilities.css' layer(utilities);
}
```

Equivalent Tailwind CSS v3 Configuration:
```js
/** @type {import('tailwindcss').Config} */
export default {
  prefix: 'tw-',
  important: '#root'
}
```

Output from Tailwind Intellisense in V4:
```css
.tw\:text-red-500 {
    color: var(--tw-color-red-500) /* oklch(63.7% 0.237 25.331) = #fb2c36 */;
}
```

Output from Tailwind Intellisense in V3:
```css
#root .tw-text-red-500 {
    --tw-text-opacity: 1;
    color: rgb(239 68 68 / var(--tw-text-opacity, 1)) /* #ef4444 */;
}
```
