### DISCUSSION TITLE
Cannot get starting:translate-y to work properly in safari. Coding it in CSS works

### DISCUSSION THREAD

**Discussion by RaederDev** [tailwindlabs/tailwindcss#18304] [Help]
I'm not sure if this is a tailwind or safari bug but I ran into an issue where starting-style seems to break.
https://play.tailwindcss.com/ClQpDWz4UT
The red square is supposed to animate up to the top from the bottom. This works in Chrome and FF but not Safari 18.5.

I recreated the example with plain CSS and it works properly in Safari:
https://codepen.io/RaederDev/pen/VYLxGqx

I cannot figure out what tailwind is doing differently here or how to solve this.

**Comment by shahenwaz** [comment]
This appears to be a Safari-specific bug related to how it handles `@starting-style`, especially in combination with utility-first CSS frameworks like Tailwind.

You're right — your plain CSS demo works, but the Tailwind version uses a more complex utility stack, and Safari sometimes ignores the `@starting-style` declaration when used with dynamically generated class names.

**Why it's happening:**
- Safari (even 18.5) has partial support for `@starting-style`, and it's sensitive to where and how it's declared.
- Tailwind compiles all animations inside `@layer utilities`, which might interfere with how Safari interprets the scope of `@starting-style`.

**Workarounds:**
1. Try isolating your animation inside a custom CSS class outside of Tailwind utilities:
   ```css
   @layer components {
     .move-up {
       @starting-style {
         transform: translateY(100%);
       }
       transform: translateY(0);
       transition: transform 1s ease-out;
     }
   }
   
2. Alternatively, avoid @starting-style and use from-to keyframes with Tailwind:
```css
@keyframes move-up {
  from {
    transform: translateY(100%);
  }
  to {
    transform: translateY(0);
  }
}

@layer utilities {
  .animate-move-up {
    animation: move-up 1s ease-out;
  }
}
```
Safari can be unpredictable with newer spec features, so a keyframe fallback is your best bet if full cross-browser compatibility is a priority.

**Comment by hjaber** [comment]
Spent a long time debugging a `<dialog>`'s `starting:open:translate-y-200` and came to the same conclusion/fix as you. 

Potentially @starting-style fails to apply when the value that changes is inside a custom property.

```css
.starting\:translate-y-200 {
    @starting-style {
      --tw-translate-y: calc(var(--spacing) * 200);
      translate: var(--tw-translate-x) var(--tw-translate-y);
    }
  }
```

**Comment by atoka-tech** [comment]
It appears that things do not work correctly when using a custom property that is defined with `@property` and has `inherits: false`.

```css
@property --custom-prop {
  syntax: '*';
  inherits: false;
  initial-value: 0;
}

div {
  @starting-style {
    translate: var(--custom-prop) 100px;
  }
}
```

https://codepen.io/atoka/pen/ogLNmGB

This behavior is not limited to `translate`; the same issue occurs with other properties such as `inset`.

```css
/* not working */
div {
  @starting-style {
    inset: var(--custom-prop) 100px;
  }
}
```

Interestingly, if `inherits: true` is set, it starts working for some reason.

As a workaround, avoiding shorthand properties seems to help. For example, using `translateY` instead of `translate` works:

```html
<div class="mt-50 h-10 w-10 bg-red-500 duration-1000 starting:transform-[translateY(400px)]"></div>
```

https://play.tailwindcss.com/0cymnj8rWQ
