### DISCUSSION TITLE
Referencing prefixed custom variables

### DISCUSSION THREAD

**Discussion by auirarrazaval** [tailwindlabs/tailwindcss#18309] [Help] [answered]
I am currently migrating from v3 to v4, and I came across the following issue. 
When defining color scales in v3, with tailwind.config.js, I could add the `my-color.DEFAULT` key which would make the `my-color` alias available in the project. For v4, I'm trying to emulate this using the `@theme {}` directive ttoo define the scale, and `@theme inline {}` to define the default alias. Something like:

```css
/* /theme/colors.css */
@theme {
    /* Reset */
    --color-*: initial;

    /* Theme Colors */

    /* Primary */
    --color-primary-50: #9FA4D0; /* old: bg-weak */
    --color-primary-100: #8F97C8; /* new */
    --color-primary-200: #7F8AC7; /* new */
    --color-primary-300: #6F7DBE; /* new */
    --color-primary-400: #5F6EA4; /* old: bg-strong */
    --color-primary-500: #485A97; /* new */
    --color-primary-600: #313F89; /* old: weak */
    --color-primary-700: #202A75; /* new */
    --color-primary-800: #0C1461; /* old: primary */
    --color-primary-900: #0B114D; /* old: strong */
    --color-primary-950: #090E3A; /* old: label */
}

@theme inline {
    /* All defaults */

    --color-primary: var(--color-primary-800);
}
```

This initially works. However, I have two requirements for this project:
1. This is a ui library, so I need to add a prefix to the classes.
2. I need to be able to export the theme for other libraries to use, WITHOUT the prefix (as a standalone theme)

My entrypoint for tailwind, therefore, looks something like this:

```css
@import 'tailwindcss' prefix(tds);
@import './theme/colors';
```
Again, this correctly adds the prefix to all classes as expected, HOWEVER, it does not add it to the `var(--color-primary-800)` value in the `@theme inline` reference. This means that the produced theme looks like this:

![image](https://github.com/user-attachments/assets/10618c3f-634f-4eb0-a931-9f08502860b4)

Note that the dedfault value `tds-color-primary` is not generated.

If I change the default to:

```css
@theme static {
    /* All defaults */

    --color-primary: var(--color-primary-800);
}
```
to force the generation of the class, the default is generated, but like this:
![image](https://github.com/user-attachments/assets/a02bf554-c306-41a9-be60-0d8f7d3d54fa)

note how the referenced value is not prefixed, and therefore tailwind cannot find it and purges it. 

If I update once again to
```css
@theme inline {
    /* All defaults */

    --color-primary: var(--tds-color-primary-800); /* 'hardcoded' the prefix */
}
```
Then tailwind parses it correctly and the alias works as expected

This is not ideal, as I have to hardcode the prefix in the reference, and if I import this theme in another project that doesn't use the same prefix, it wouldn't work out-of-the-box

Am I missing a setting? Or is this actually a bug in v4?

**Comment by wongjn** [comment, marked as answer]
You can use `theme()` instead of `var()`. The `theme()` function will account for the `prefix()`:

```css
@theme inline {
    /* All defaults */

    --color-primary: theme(--color-primary-800); 
}
```
You'll get output like:
```css
.tds\:text-primary {
  color: #0C1461;
}
```

Or you can use `--theme()`:

```css
@theme inline {
    /* All defaults */

    --color-primary: --theme(--color-primary-800); 
}
```
You'll get output like:
```css
.tds\:text-primary {
  color: var(--tds-color-primary-800);
}
```
