### DISCUSSION TITLE
What might support for the ::part(...) pseudoelement look like?

### DISCUSSION THREAD

**Discussion by jamesarosen** [tailwindlabs/tailwindcss#18342] [Ideas]
Tailwind [supports](https://tailwindcss.com/docs/hover-focus-and-other-states#pseudo-elements) pseudo-elements like `::before` and `::after` with `before:mb-4 after:mt-4`.

What would it look like to support [the `::part` pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/::part), which takes a part name argument? In CSS, it's

```css
my-element::part(title) {
  font-weight: bold;
}
```

Perhaps `<my-element class="part(title):font-bold">`?

See also the [corresponding discussion on unocss/unocss](https://github.com/unocss/unocss/discussions/4753)

**Comment by jamesarosen** [comment]
It's possible to do this now with the custom selector escape hatch:

```html
<div class="m-10 p-10 border-2 [&::part(title)]:font-bold">
```

results in

```css
@layer utilities {
  .m-10 {
    margin: calc(var(--spacing) * 10);
  }
  .border-2 {
    border-style: var(--tw-border-style);
    border-width: 2px;
  }
  .p-10 {
    padding: calc(var(--spacing) * 10);
  }
  .\[\&\:\:part\(title\)\]\:font-bold {
    &::part(title) {
      --tw-font-weight: var(--font-weight-bold);
      font-weight: var(--font-weight-bold);
    }
  }
}
```
