### DISCUSSION TITLE
Suggestion: some sort of `light-dark` ish support

### DISCUSSION THREAD

**Discussion by AlexFrazer** [tailwindlabs/tailwindcss#18359] [Ideas]
When I start on projects or libraries, one of the first things I do is create variables to map to specific components, making them relatively easy to modify or override by a user. However, I have to specify both light and dark mode for every property:

```css
@theme {
  /**
  * Input component properties
  */
  --color-input-background-light: theme(color.gray.50);
  --color-input-background-dark: theme(color.neutral.900);

  --color-input-text-light: theme(color.gray.900);
  --color-input-text-dark; theme(color.gray.100);

  /** so on, so on */
}
```

And in my app, I will do something like this:
```html
<input class="bg-input-background-light dark:bg-input-background-dark text-input-text-light dark:text-input-text-dark" />
```

Of course, this gets fairly redundant and annoying to do for every variation of a color. When I set up these design tokens, I don't particularly care if the user is in dark mode or not. MDN does have [`light-dark`, which allows you to specify two different colors depending on mode](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark)

```css
@theme {
  --color-input-background: light-dark(
    theme(color.gray.50),
    theme(color.neutral.900),
  );
}
```

Of course, this won't work natively with tailwindcss, because you can use custom variants for the dark mode

Is this possible to achieve with tailwindcss? It might be cool to have a function like `--alpha`, but with light-dark

```
@theme {
  --color-input-background: --light-dark(
    theme(color.gray.50),
    theme(color.neutral.900),
  );
}
```

**Comment by wongjn** [comment]
`light-dark()` should actually work as long as you set `color-scheme` on the `<html>` appropriately:

```html
<html class="scheme-light dark:scheme-dark">
```
```css
@theme {
  --color-input-background: light-dark(
    var(--color-gray-50),
    var(--color-neutral-900)
  );
}
```
