### DISCUSSION TITLE
Utilities for `writing-mode`

### DISCUSSION THREAD

**Discussion by rozsazoltan** [tailwindlabs/tailwindcss#18362] [Show and tell]
> Doesn't tailwind 4 support [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode)? ([LoSti](https://discord.com/channels/486935104384532500/486935104384532502/1385908454681743383))

> If by "support" you mean "are there utility classes for it", then no. But you can easily just add it yourself. ([Moni](https://discord.com/channels/486935104384532500/486935104384532502/1385909395313131520))

Just a quick example:
* https://play.tailwindcss.com/mo6gw82l1F?file=css

```css
@import "tailwindcss";

@utility writing-* {
  writing-mode: --value('horizontal-tb', 'vertical-lr', 'vertical-rl', 'sideways-lr', 'sideways-rl');
}
```
```html
<div class="flex flex-col gap-4 [&>*]:w-32 [&>*]:p-4 [&>*]:bg-sky-300">
  <div class="writing-horizontal-tb">Example</div>
  <div class="writing-vertical-lr">Example</div>
  <div class="writing-vertical-rl">Example</div>
  <div class="writing-sideways-lr">Example</div>
  <div class="writing-sideways-rl">Example</div>
</div>
```

And with your own custom namespace:
* https://play.tailwindcss.com/dBQ9Z3YUqL?file=css

```css
@import "tailwindcss";

@theme {
  --writing-normal: horizontal-tb;
  --writing-vertical: vertical-lr;
  --writing-vertical-reverse: vertical-rl;
  --writing-sideways: sideways-lr;
  --writing-sideways-reverse: sideways-rl;
}

@utility writing-* {
  writing-mode: --value(--writing-*);
}
```
```html
<div class="flex flex-col gap-4 [&>*]:w-32 [&>*]:p-4 [&>*]:bg-sky-300">
  <div class="writing-normal">Example</div>
  <div class="writing-vertical">Example</div>
  <div class="writing-vertical-reverse">Example</div>
  <div class="writing-sideways">Example</div>
  <div class="writing-sideways-reverse">Example</div>
</div>
```
