### DISCUSSION TITLE
Same theme token for background color and text color

### DISCUSSION THREAD

**Discussion by kpyszkowski** [tailwindlabs/tailwindcss#18367] [Help] [answered]
Is it possible to define theme in a way where `bg-primary` and `text-primary` are different colors?
Semantically calling color primary is reasonable so primary background will be white and primary text color will be black.

The only namespace for colors I see in documentation is `--color-*`. Is it possible to differentiate between background and text colors?

**Comment by wongjn** [comment, marked as answer]
Is it possible to differentiate between background and text colors. Use `--background-color` and `--text-color` respectively:

```css
@import "tailwindcss";

@theme {
  --background-color-primary: white;
  --text-color-primary: black;
}
```
