### DISCUSSION TITLE
How to create custom utility classes and override them for different themes without confusion due to namespaces (Tailwind 4)

### DISCUSSION THREAD

**Discussion by gmoniava** [tailwindlabs/tailwindcss#18386] [Help]
Imagine I want to have several custom utility classes - such as  `button-default-background` - and also override them during dark mode (because I suppose this is one approach to create apps which support themes).

Now I could do it in following way based on tailwind 4 docs:

```
@custom-variant dark (&:where(.dark, .dark *));

@theme {
  --color-button-default-background: #eb6bd8;
}

@layer base {
  @variant dark {
    --color-button-default-background: #8e0d7a;
  }
}
```

But it would generate utilities like `bg-button-default-background` and `text-button-default-background` right? However having value named: `text-button-default-background` seems a bit strange (usage of _text_ and _background_ in the same word) isn't it?

So what is the best way to achieve what I want using tailwind 4 primitives?

**Comment by wongjn** [comment]
You could consider using theme token namespace for `background-color` only, `--background-color`:

```css
@custom-variant dark (&:where(.dark, .dark *));

@theme {
  --background-color-button-default: #eb6bd8;
}

@layer base {
  * {
    @variant dark {
      --background-color-button-default: #8e0d7a;
    }
  }
}
```
```html
<div class="bg-button-default">
```
https://play.tailwindcss.com/WQ9x09RIZh?file=css

**Reply by gmoniava** [reply]
- Yes but I could not find namespace for `background-color` [here](https://tailwindcss.com/docs/theme#theme-variable-namespaces), how did you know it existed?
- Also background color here was example someone might want to have variable for `button-default-border-color` and will still run into same issues which I described in my original question if uses standard approach.
- Also the ` * {..` you added under `base`, can you explain why you added it? Is it needed? I remember the original code from where I took my example did not use it.

**Reply by wongjn** [reply]
> * Yes but I could not find namespace for `background-color` [here](https://tailwindcss.com/docs/theme#theme-variable-namespaces), how did you know it existed?

I looked at the source code:
https://github.com/tailwindlabs/tailwindcss/blob/aa859314d9cd0a54f1914051c2a400d81bd7bed2/packages/tailwindcss/src/utilities.ts#L2668

> * Also background color here was example someone might want to have variable for `button-default-border-color` and will still run into same issues which I described in my original question if uses standard approach.

`border-color` can use the `--border-color` namespace: https://play.tailwindcss.com/Ie638r4ERK?file=css

> * Also the ` * {..` you added under `base`, can you explain why you added it? Is it needed?

Yes, without it, the compiled CSS would look like:

```css
@layer base {
  &:where(.dark, .dark *) {
    --background-color-button-default: #8e0d7a;
  }
}
```

Notice how the ampersand (`&`) has no parent selector to refer to. So, we add the universal selector (`*`) for it to anchor to.
