### DISCUSSION TITLE
[v4] How to use fade in/out transition from the `hidden` attribute?

### DISCUSSION THREAD

**Discussion by hiroya-uga** [tailwindlabs/tailwindcss#18394] [Help] [answered]
Hello, thank you for your work on TailwindCSS!

I’ve been enjoying using the `hidden` attribute in combination with CSS transitions for fade in/out effects. 
Here's an example of what I used to do:

<https://codepen.io/hiroya_uga/pen/XJbORXP>

```css
.toast {
  transition:
    opacity 0.3s ease-out,
    visibility 0.3s ease-out;
}

.toast[hidden] {
  display: block;
  opacity: 0;
  visibility: hidden;
  pointer-events: none;
}
```

However, in TailwindCSS v4, I noticed the following rule in the base layer:

```css
[hidden]:where(:not([hidden="until-found"])) {
  display: none !important;
}
```

Because this `!important` rule is defined in the lowest layer, it prevents me from calculating the box model of an element with the `hidden` attribute using standard methods.

As a workaround, I’m currently overriding the style like this:

```css
@layer base {
  .no-hidden {
    display: block !important;
  }
}
```

```jsx
<div className="no-hidden" hidden />
```

or

```jsx
// React
ref.current.style.setProperty('display', 'block', 'important');
```

Is there a way to achieve this fade in/out transition using only TailwindCSS, without needing to manually override the `display` property?

Thanks in advance!
