### DISCUSSION TITLE
How to create an highlight on refresh animation?

### DISCUSSION THREAD

**Discussion by jean-francois-labbe** [tailwindlabs/tailwindcss#1895] [Help] [answered]
Hi, I'd like to create an highlight animation that just highlights a text element when the page is displayed and fades after 2 seconds.

I have this css code that does it.

```css
@keyframes highlight {
  0% { background: #8f8; }
  100% {background: none; }
}

.highlight {
  animation: highlight 1s;
}
```
I can use it this way
```html
<div class="p-4 highlight">
  hello
</div>
```

How can I translate it into Tailwindcss?
