### DISCUSSION TITLE
Add bg-current-xxx and text-current-xxx

### DISCUSSION THREAD

**Discussion by ghost** [tailwindlabs/tailwindcss#2013] [Ideas]
It would be a helpful feature to all multiple elements to change their current background or text color on hover or focus even if they're all different colors.
![carbon (1)](https://user-images.githubusercontent.com/44789941/87193149-f04d9080-c2ac-11ea-9b18-5642a825d213.png)
![carbon](https://user-images.githubusercontent.com/44789941/87193154-f17ebd80-c2ac-11ea-873c-e2dadf1ab4ac.png)

**Comment by JNavith** [comment]
I don't think this is possible, because Tailwind can't make features that CSS doesn't support.

I would imagine that `bg-blue-200` sets
```css
/* already does this (simplified) */
background-color: #whatever200;
/* new stuff */
--bg-current: blue;
--blue-100: #whatever100;
--blue-200: #whatever200;
/* ... */
--blue-900: #whatever900;
```
and `hover:bg-current-900` sets
```css
background-color: var(--var(--bg-current)-900);
```
which is not valid syntax.

Do you expect another way for this to work?

**Reply by JNavith** [reply]
Actually, it's occurred to me that it could be possible if you reduce that all to:

```css
.bg-blue-200 {
  /* already does this (simplified) */
  background-color: #whatever200;
  /* new stuff */
  --bg-current-100: #whatever100;
  --bg-current-200: #whatever200;
  /* ... */
  --bg-current-900: #whatever900;
}

.hover\:bg-current-900 {
  background-color: var(--bg-current-900);
}
```
