### DISCUSSION TITLE
How to create native fade in animation with utility classes on render/mount/page load

### DISCUSSION THREAD

**Discussion by bennettdams** [tailwindlabs/tailwindcss#2094] [Help] [answered]
When using TailwindCSS e. g. with React, is it possible to create a fade in animation when a component mounts with the given utility classes?

Simple example to demonstrate:

```tsx
const SomeComponent = (hasError: boolean) => {
    return (
        <div className="some-component">
            {hasError ? (
                <div className="all good">All good</div>
            ) : (
                <div className="error">Some error</div> // <<< this div should fade in when it is rendered
            )}
        </div>
    );
};
```

You can easily build your own in Tailwind's input file, but is there a way to do it with the native utilities?

```css
.fade-in {
  animation: animation-fade-in 0.3s;
}

@keyframes animation-fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```

I'm aware of the `transition-opacity`, but you'll always need another pseudo-class variant like `hover` to make it work.
