### DISCUSSION TITLE
Automatically apply `important` and `prefix` to custom utilities inside `@layer utilities`

### DISCUSSION THREAD

**Discussion by benface** [tailwindlabs/tailwindcss#2128] [Ideas]
Tailwind 1.5 introduced the `@layer` at-rule, which only seems to be doing something for components at the moment. It would be nice, and make sense IMO, if all the utilities defined inside a `@layer utilities` at-rule automatically had the `important` and `prefix` options set in the Tailwind config applied to them. I could be wrong, but I believe the main reason it’s not supported is that there used to be no way to differentiate CSS-defined utilities from other custom CSS (base styles, components, etc.), but now there is!

So for instance, if you have these in `tailwind.config.js`:
```js
{
  important: ‘#app’,
  prefix: ’tw-‘,
}
```

And this custom CSS:
```css
@layer utilities {
  @responsive {
    .animation-500 {
      animation-duration: 500ms;
    }
  }
}
```

It would generate the following CSS (as well as the responsive variants):
```css
#app .tw-animation-500 {
  animation-duration: 500ms;
}
```

**Comment by benface** [comment]
This *almost* feels like a bug, because it makes it impossible to properly `@apply` custom utilities (those defined in CSS files, not via the plugin API) when `important` is set to a prefix selector (e.g. `#app`):

```css
@layer utilities {
  /* Gotta add the prefix manually here, or there will be specificity issues */
  /* (e.g. the utility won't be able to override the same property in a component) */
  #app .custom-utility {
    some-property: some-value;
  }
}

@layer components {
  .component {
    @apply custom-utility;
  }
}
```

This results in:

```
ERROR in ./src/css/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(6:3) `@apply` cannot be used with `.custom-utility` because `. custom-utility` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `. custom-utility` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```
