### DISCUSSION TITLE
Add default transition-duration to transitionProperty utility

### DISCUSSION THREAD

**Discussion by fedeci** [tailwindlabs/tailwindcss#2334] [Ideas]
What do you think about adding a default `transition-duration` to the transitionProperty utility?
This would reduce code repetition because this would become available:
```html
...
<!-- transitionDuration set as default value to 250ms -->
<div class="bg-red-700 hover:bg-blue-700 transition-colors w-10 h-10"></div>
...
```

But in case of need it could be overridden using `duration-x`:

```html
...
<div class="bg-red-700 hover:bg-blue-700 transition-colors duration-150 w-10 h-10"></div>
...
```

And the code generated would become something like this:
```css
.transition-none {
  transition-duration: 250ms;
  transition-property: none
}
```

Linked PR #2335
