### DISCUSSION TITLE
CSS Filters

### DISCUSSION THREAD

**Discussion by martinstanicio** [tailwindlabs/tailwindcss#2344] [Ideas]
# CSS Filters

Add support for [CSS Filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter).

For example:

## Grayscale

```css
.filter-grayscale-0 {
  filter: grayscale(0);
}

.filter-grayscale-25 {
  filter: grayscale(25%);
}

.filter-grayscale-50 {
  filter: grayscale(50%);
}

.filter-grayscale-75 {
  filter: grayscale(75%);
}

.filter-grayscale-100 {
  filter: grayscale(100%);
}
```

## Drop shadow

This specially useful when working with SVG:
If you use `box-shadow` the shadow is squared (unless you apply a `border-radius`), but if you use `filter: drop-shadow()` the shadow will be applied to elements in the SVG itself ([`box-shadow`](https://snipboard.io/gTC69P.jpg) vs [`filter: drop-shadow`](https://snipboard.io/RpbrKC.jpg)).

```css
.filter-drop-shadow {
  filter: drop-shadow(theme("boxShadow.<prefered-shadow>"));
}
```
