### DISCUSSION TITLE
Hide scrollbar while maintaining functionality

### DISCUSSION THREAD

**Discussion by giraffekey** [tailwindlabs/tailwindcss#2394] [Ideas]
It would be helpful to have a `.no-scrollbar` class that hides the scrollbar without removing its functionality, this is the code:
```css
/* Chrome, Safari and Opera */
.no-scrollbar::-webkit-scrollbar {
  display: none;
}

.no-scrollbar {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}
```

**Comment by arifikhsan** [comment]
nice to have this

**Comment by withewolf-dev** [comment]
How to Write inline style for the same for react

**Comment by andresgutgon** [comment]
Super nice! It solved my problem. Just one thing. If you're already using Tailwind which I guess here we all do xD

You can put in a TW layer
``` css
@layer utilities {
  @variants responsive {
    /* Chrome, Safari and Opera */
    .no-scrollbar::-webkit-scrollbar {
      display: none;
    }

    .no-scrollbar {
      -ms-overflow-style: none;  /* IE and Edge */
      scrollbar-width: none;  /* Firefox */
    }
  }
}
```

This way you can use with responsive classes like `md:no-scrollbar`
