### DISCUSSION TITLE
Composable animations⚡⚡⚡

### DISCUSSION THREAD

**Discussion by Larsklopstra** [tailwindlabs/tailwindcss#2403] [Ideas]
Hey, recently I came across something I'd love to have in Tailwind CSS.

### Case

Imagine you want a specific animation like a bouncing button to happen twice for 250ms with the `ease-in-out` transition timing. Currently, this is not possible, you'll have to do JavaScript which does something on `x` or write your own animation. This proposal will solve that.

### Current implementation

`.animate-bounce` => `animation: bounce 1s infinite;`

### Proposed implementation

`.animate-bounce .animate-250ms .animate-count-2` => `animation: bounce var(--animate-duration) var(--animate-count);`

By default, the original values will be used for the variables so it'll stay backwards compatible. You could also introduce more variables if necessary such as `animation-direction`, `animation-delay`, or even `animation-name`!

Here's a more detailed example:

```css
.animate {
  --animation-duration: 500ms;
  --animation-timing-function: linear;
  --animation-delay: 0;
  --animation-iteration-count: infinite;
  --animation-direction: forwards;

  animation-name: var(--animation-name);
  animation-duration: var(--animation-duration);
  animation-timing-function: var(--animation-timing-function);
  animation-delay: var(--animation-delay);
  animation-iteration-count: var(--animation-iteration-count);
  animation-direction: var(--animation-direction);
}

.animate-bounce {
  --animation-name: bounce;
}

.animate-ease-in-out {
  --animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
}
```

You get the idea now, don't you?

Let me know what you think, it could be a powerful method to composite animations.
