### DISCUSSION TITLE
How can use @apply for custom css

### DISCUSSION THREAD

**Discussion by anandsiddharth** [tailwindlabs/tailwindcss#2406] [Help]
Hey folks,
I have custom css on top of tailwind.
```css
/* purgecss start ignore */
@import 'tailwindcss/base';
@import 'tailwindcss/components';
/* purgecss end ignore */
@import 'tailwindcss/utilities';

@layer base {
  .dark-component {

         background: #212121;
    
  }
}
```
Is it possible to use `@apply pink-component` 
The use case is different here so I have a component wrapper inside which elements have to be dark, And I obfuscate classes, so have to use style modules in nuxt, to do so.
