### DISCUSSION TITLE
Resetting .container from a responsive variant back to full width

### DISCUSSION THREAD

**Discussion by GHNewbiee** [tailwindlabs/tailwindcss#2409] [Ideas]
Although `container` class is used with responsive variants, explicit "reset to full width" option is not available. A responsive variant of `max-w-full` has to be used. For example:

```css
<div class="sm:container md:max-w-full lg:container xl:max-w-full"> ... </div>
```
Wouldn't it be more elegant/practical/easy-to-find-out by using something like `container-{0|none}` i.e.

```css
<div class="sm:container md:container-0 lg:container xl:container-none"> ... </div>
```

A note, about how it could be reset, would also be added in the doc.

**Comment by GHNewbiee** [comment]
For the time being, I have just added the following lines:

```css
@layer utilities {
  @responsive {
    .container-0 {
      max-width: 100%;
    },
    .container-none  {
      max-width: 100%;
    }
  }
}
```

to `CSS` file.
