### DISCUSSION TITLE
Grid order reverse

### DISCUSSION THREAD

**Discussion by Hakamate** [tailwindlabs/tailwindcss#2416] [Ideas]
Hello ! :hand: 

Display Grid need a reverse order. 

A simple class which just set direction like this : 

```CSS
#container.reverse {
  direction: rtl;
}
```

Example : https://stackoverflow.com/a/50959080

That can be usefull when the parent contain flex-row-reverse for example
