### DISCUSSION TITLE
Ability to use `divide-*` and `space-*` utility together

### DISCUSSION THREAD

**Discussion by neupauer** [tailwindlabs/tailwindcss#2466] [Ideas]
Hey 👋,

I ran into an issue that utilities `divide-*` and `space-*` cannot be used at the same time. In fact, they can, however, the result is slightly different from the expected one.

I would expect the space to split equally around the divider.

So my idea is that instead of dividing the gap between items like this:
```css
.space-y-4 > :not(template) ~ :not(template) {
  margin-top: 1rem;
}
```

use this, e.g.,:
```css
.space-y-4 > :not(template) ~ :not(template) {
  padding-top: 0.5rem;
  margin-top: 0.5rem;
}
```

As a result, the divider (`border`) between the items will be divided evenly, and the example below will behave as expected.

```html
<ul class="space-y-4 divide-y">
  <li>A</li>
  <li>B</li>
  <li>C</li>
</ul>
```

_Note:_
Instead of using both (`margin` and `padding`), this can be achieved using pseudo-elements.
