### DISCUSSION TITLE
Let height and width attributes on images do their job

### DISCUSSION THREAD

**Discussion by ghost** [tailwindlabs/tailwindcss#2538] [Ideas]
I think it would be a good to add something like this into tailwind's preflight : 
```css
img[width],
img[height] {
    max-width: none;
    height: unset;
}
```
Currently, those two attributes do nothing because of [these rules](https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/css/preflight.css#L224)
