### DISCUSSION TITLE
How to reference Tailwind variable in regular SCSS ?

### DISCUSSION THREAD

**Discussion by kissu** [tailwindlabs/tailwindcss#2738] [Help] [answered]
Hi ! 👋🏻 
I do have a SCSS file containing
```css
* {
  scrollbar-color: var(--color-primary-300) var(--color-primary-700);
  scrollbar-width: 8px; // btw, this property is not supported by Firefox, but it's an example ! 😆 
}
```
and this in my `tailwind.config.js` file
```js
spacing: {
  ...
  2: '0.5rem'
  ...
},
```

How may I bring the spacing of `0.5rem` into my `scrollbar-width` property to avoid that hardcoded `8px` value ? 🙏🏻
