### DISCUSSION TITLE
Disabling --tw-shadow on * selector

### DISCUSSION THREAD

**Discussion by cossssmin** [tailwindlabs/tailwindcss#2813] [Help] [answered]
Any way to prevent (or un-register) this utility?

https://github.com/tailwindlabs/tailwindcss/blob/f5010f592afd2e3b8d4fd1d8abfc62712b0271a7/src/plugins/boxShadow.js#L6-L13

Been testing 2.0 with Maizzle and I'm getting that CSS inlined on every element... looking for a way to disable it without disabling the entire plugin.

**Comment by cossssmin** [comment]
Same with the new ring utilities, each property is generated in one of the ring plugins:

```css
* {
  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000
}
```

Since `*` isn't exactly an utility, wouldn't it make more sense to add these 'resets' to the base reset?
