### DISCUSSION TITLE
Dark Mode directive

### DISCUSSION THREAD

**Discussion by akhila-ariyachandra** [tailwindlabs/tailwindcss#2855] [Help]
Is there a dark mode directive in Tailwind 2.0 which I can use in my CSS files like `@dark` or something? I'm currently using `next-themes` to switch colors defined in my CSS.

```css
:root {
  --text: black;
}

[data-theme="dark"] {
  --text: white;
}
```

I would prefer to use Tailwind's new dark instead. For example,

```css
p {
  @apply text-black;
}

@dark {
  p {
    @apply text-white;
  }
}
```
