### DISCUSSION TITLE
Tap highlight color CSS property should be added to remove blue tap box in mobile view.

### DISCUSSION THREAD

**Discussion by smitbarmase** [tailwindlabs/tailwindcss#2984] [Ideas]
### Use to remove blue tap box over Button/Link in CSS. Tailwind doesn't provide any class to alter this.
`-webkit-tap-highlight-color: transparent;`

![Screenshot (20)](https://user-images.githubusercontent.com/37347831/100965829-8d0d1500-3551-11eb-8b9c-4f6ee85b3a58.png)

**Comment by PositiveUser** [comment]
I was about to start a discussion regarding this and I found your idea. Thank you very much!

**Comment by LeulAria** [comment]
any progress or forgotten :)

```css
@layer base {
    html {
        -webkit-tap-highlight-color: transparent;
    }
}
```
