### DISCUSSION TITLE
Regaining the power of advanced CSS selectors

### DISCUSSION THREAD

**Discussion by AndyOGo** [tailwindlabs/tailwindcss#2998] [Ideas]
I have a case where I want to style all the adjacent sibling of a tag, except the first one for every adjacent group.

```html
<div>
  <p><!-- don't style this one --></p> 
  <p></p>
  <p></p>

  <div><!-- interrupt the siblings chain --></div>

  <p><!-- don't style this one --></p>
  <p></p>
  <p></p>
</div>
```
With pure CSS the adjacent siblings selector `+` or `:last-of-type`, `:first-of-type` can be utilised to facilitate this use case, like:

```css
p {
  color: green;
}

p + p {
  color: red;
}

// or

p:not(:first-of-type, :first-of-type:last-of-type) {
 color: red;
}
```

I know that a plugin for these can be added.

I have seen such needs fairly often and would favour an official plugin for such advanced selections.
