### DISCUSSION TITLE
Octal escape sequences in list-style-type

### DISCUSSION THREAD

**Discussion by chrisg86** [tailwindlabs/tailwindcss#3005] [Help] [answered]
For a project I'm trying to do some fancy `list-style-types` using the `list-*` classes from tailwind. 
Looking at the [MDN page for list-style-type](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) (See 4th example emoji thumbs up), this should be possible by wrapping the octal escape sequence in double quotes.

I was following the tailwind documentation [here](https://tailwindcss.com/docs/list-style-type#customizing) to add custom classes to match my needs.

Here are some examples I've tried:

tailwind.config.js
```javascript
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
    listStyleType: {
      arrowRight: '\2192',
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

Css:
```css
.list-arrowRight {
    list-style-type: 92; /* Invalid property value */
}
```

---

```javascript
listStyleType: {
  arrowRight: "\2192",
}
```

Same result as above:
```css
.list-arrowRight {
    list-style-type: 92; /* Invalid property value */
}
```

---

```javascript
listStyleType: {
  arrowRight: "\"\2192\"",
}
```

CSS:
```css
.list-arrowRight {
    list-style-type: &quot; /* Invalid property value */
    92&quot: ; /* Unknown property name */
}
```

It seems the issue is that when building tailwind double quotes are escaped. Is there a way around this?

**Comment by chr-ge** [comment]
Does this work?
```js
listStyleType: {
  arrowRight: "\\2192",
},
```

**Reply by chrisg86** [reply]
I think I tried it, this will output something like this (won't work):

```css
.list-arrowRight {
    list-style-type: \2192 /* missing double quotes */
}
```

**Comment by aggreggator** [comment]
This should work:
`    
listStyleType: {
  arrowRight: "\"\\2192\"",
},
`

**Reply by chrisg86** [reply]
Sorry for the late answer. Same issue as with this:

```js
listStyleType: {
  arrowRight: "\"\2192\"",
}
```

Output
```css
.list-arrowRight {
    list-style-type: &quot; /* Invalid property value */
    \2192&quot: ; /* Unknown property name */
}
```

**Comment by chrisg86** [comment]
So I've dug a bit deeper and it seems the same thing happens when trying to use custom font families that have spaces in them. 
Example:

tailwind.config.js
```javascript
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        cursive: ['"Sansita Swashed"', 'cursive'],
      }
    }
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

In this case I am using `Sansita Swashed` which will generate the following css:
```css
.font-cursive {
    font-family: &quot;        /* Invalid property value */
    Sansita Swashed&quot: ;    /* Unknown property name */
    , cursive: ;               /* Unknown property name */
}
```

Using the double backslash also produces the "wrong" css:

tailwind.config.js
```js
cursive: ["Sansita\\ Swashed", 'cursive'],
```

css
```css
.font-cursive {
    font-family: Sansita\ Swashed, cursive;   /* Falls back to 'cursive' */
}
```

As mentioned earlier I'm sure that this is related to the escaping done by tailwind.

By the way, I am using `"tailwindcss": "^2.0.1"`
