### DISCUSSION TITLE
CSS-IN-JS for repeated properties

### DISCUSSION THREAD

**Discussion by SergiArias** [tailwindlabs/tailwindcss#3098] [General]
Hi!
I'm trying tailwind and I started creating a plugin for the font face that would output something like this:
```css
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot'); /* IE9 Compat Modes */
  src: url('webfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('webfont.woff2') format('woff2'), /* Super Modern Browsers */
       url('webfont.woff') format('woff'), /* Pretty Modern Browsers */
       url('webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('webfont.svg#svgFontName') format('svg'); /* Legacy iOS */
}
```

the problem I find is that using css in js I cannot repeat the same src property (it gets overwritten as expected). I tried some workarounds like using text only with no success. It's not an important matter as it's only for compatibility with a browser is dead already, but still I am curious how to solve a problem like this through plugins.
