### DISCUSSION TITLE
Suport mult row text overflow ?

### DISCUSSION THREAD

**Discussion by turkyden** [tailwindlabs/tailwindcss#3184] [Ideas]
## [RFC] Mult row text overflow

Utilities for controlling text overflow in an  mult row element. Preview in [Codepen &rarr;](https://codepen.io/turkyden/pen/vYXebNq)

![Demo](https://user-images.githubusercontent.com/24560160/103072269-36e73b00-4600-11eb-9fa2-c0eb61a57f8e.gif)

```css
.truncate{
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

```css
.truncate-2{
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
}
```

```css
.truncate-3{
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
}
```

...
