### DISCUSSION TITLE
Tailwind classes do not compile as expected when using CSS-Modules and :dark prefix

### DISCUSSION THREAD

**Discussion by trm217** [tailwindlabs/tailwindcss#3204] [Help] [answered]
### Describe the problem:
I was updating my website to utilize the tailwind-configuration darkMode: 'class' instead of darkMode: 'media' and noticed an unexpected behavior. In my project, I use TailwindCSS 2.0 and CSS-Modules.

When given the following code inside a CSS-module

```css
.informationName {
    @apply font-black;
    @apply text-black;
    @apply dark:text-white;
}
```

compiles to the following code when using the darkMode: 'media' configuration

```css
.PortraitSection_informationName__1iAOK {
    font-weight: 900;
    --tw-text-opacity: 1;
    color: rgba(0, 0, 0, var(--tw-text-opacity))
}

@media (prefers-color-scheme: dark) {
    .PortraitSection_informationName__1iAOK {
        --tw-text-opacity: 1;
        color: rgba(255, 255, 255, var(--tw-text-opacity))
    }
}
```
In this case, the compiled CSS is exactly what one would expect.

However with the darkMode: 'class' configuration the following CSS get's compiled

```css
.PortraitSection_informationName__1iAOK {
    font-weight: 900;
    --tw-text-opacity: 1;
    color: rgba(0, 0, 0, var(--tw-text-opacity))
}

.PortraitSection_dark__34kkQ .PortraitSection_informationName__1iAOK {
    --tw-text-opacity: 1;
    color: rgba(255, 255, 255, var(--tw-text-opacity))
}
```
I doubt that this was meant to happen since this breaks the darkMode: 'class' configuration completely when using CSS-Modules

It's obvious that this problem is caused by using CSS-Modules but unless there is a way around it CSS-Modules and the darkMode: 'class' configuration are incompatible.

**Comment by adamwathan** [comment, marked as answer]
Yeah nothing we can really do about this on our end I'm afraid — CSS modules will automatically scope all CSS inside of it like you're seeing. Whatever solution you come up with here will probably be outside of the scope of Tailwind itself. I don't know how you can write a partially global/partically scoped selector with CSS modules in general, like if you wrote this by hand:

```css
.informationName {
    font-weight: 900;
    color: #000;
}
.dark .informationName {
  color: #fff;
}
```

...the `.dark` class would still get mangled by CSS modules right? So I'm not sure if CSS modules is even compatible with the concept of a distant parent class modifier like this.

No plans to do anything in Tailwind to change this behavior but will transfer this to our discussions in case others want to chime in with ideas.

**Reply by trm217** [reply]
After thorough consideration, I believe that this would have to be resolved in order for TailwindCSS to be a viable option for larger projects. Many companies consider a long list of CSS-classes to be a deal-breaker when using a CSS-framework, also component-scoped styling is a must when working with modern JS-libraries such as React or Vue. So in order to use Tailwind while still fulfilling these criteria, there is no way around CSS-Modules.

At the same time, a toggleable dark-mode seems to be becoming the industry standard for web-applications.

Thus if Tailwind is to be used inside a large-scale component-based web-application that offers a toggleable dark-mode this incompatibility has to be resolved either in Tailwind itself or by an additional PostCSS plugin (that prevents the faulty naming of the CSS selectors when using the dark: prefix inside a CSS-Module.).

I'd be happy to help with finding a solution to this problem, but I would need some help on how to go about developing a PostCSS-plugin since I am not familiar with the framework.

**Reply by adamwathan** [reply]
I think you should start by researching how to solve this problem with plain CSS. There must be other people who want part of a selector to be global and another part to be scoped.

Tailwind works fine in large projects exactly as it is though. In fact the more classes you extract with apply instead of just using utilities, the harder you are making it to maintain large projects. Regardless, if you don’t like the approach please feel free to use something else, it works great for thousands of people working on large projects already so to say it’s “not viable” is frankly insulting and really doesn’t do much to motivate me to help you. If you’re an experienced programmer working on large projects surely you can learn new tools like PostCSS without someone else’s help.

**Reply by trm217** [reply]
I by no means meant to insult TailwindCSS by saying it's not viable to use inline CSS in large scale component-based projects.
I love TailwindCSS ever since I started using it, it has given me great flexibility in all my new projects!  🙏☺
I really appreciate TailwindLabs and all contributors for developing it. 💯
I am sorry for my poor choice of words.

However, I know many FE-developers that are simple completely against an inline CSS approach. This is also what made it rather hard for me to convince my colleagues to use Tailwind in our projects. Most of the time I managed to convince them by showing the approach of using the @apply syntax. 

Now regarding the problem, there is a way to scope CSS-class selectors globally inside a CSS-Module. I'll provide an example:

If I want to define a CSS-module class with a preceding global CSS-class one could use the [:global](https://stackoverflow.com/questions/39805537/how-to-apply-global-styles-with-css-modules-in-a-react-app) syntax provided by CSS-Modules.

Here an example

```css
// CSS inside the CSS-Module
:global(.dark) .test {
    @apply text-gray-100;
}

// CSS generated by PostCSS
.dark .PortraitSection_test__14rKg {
    --tw-text-opacity: 1;
    color: rgba(245, 245, 245, var(--tw-text-opacity))
}
```
If TailwindCSS was to generate the class :global(.dark) instead of .dark (of course this should only happen when the TailwindConfig uses "class" for it's darkMode configuration) whenever the ":dark" prefix was used inside a CSS-Module (I suppose this could be checked in the PostCSS plugin during build time by matching a regex against the input filename?) I believe the compatibility between TailwindCSS darkMode and CSS-modules would be granted.

What do you think of this approach?
