### DISCUSSION TITLE
Create a custom variant that prepends to state variants

### DISCUSSION THREAD

**Discussion by aerni** [tailwindlabs/tailwindcss#3220] [Help]
I created a pretty straight forward [plugin](https://github.com/aerni/tailwindcss-rfs/blob/master/dist/index.js) that adds a custom `rfs` variant. I need this custom variant to behave like the `responsive` and `dark` variants do. Meaning, I also need classes to be generated for all the state variants on top of the custom variant.

In my `tailwind.config.js`:

```js
variants: {
    extend: {
        padding: ['rfs', 'first'],
    },
},
```

This generates classes like this:

```css
.rfs\:p-6 {
    padding: calc(1.275rem + 0.3vw);
}

.first\:p-6:first-child {
    padding: 1.5rem;
}
```

I also need state variant classes to be generated on top of the `rfs` variant like this:

```css

.rfs\:first\:p-6:first-child {
    padding: calc(1.275rem + 0.3vw);
}
```

When source diving Tailwind's code, I came across [this file](https://github.com/tailwindlabs/tailwindcss/blob/master/src/lib/substituteVariantsAtRules.js) that seems to handle stacking the variants.

I'm not sure if there's an easy way to make this work inside a variant plugin?
