### DISCUSSION TITLE
Support font weight for variable fonts

### DISCUSSION THREAD

**Discussion by iquito** [tailwindlabs/tailwindcss#3225] [Ideas]
I recently switched a project to the Inter variable font, and then noticed that nothing was bold anymore, as `font-weight: 700;` (or any other value for font-weight) has no effect with variable fonts, it seems `font-variation-settings: 'wght' 700;` is needed specifically to adjust font weight for variable fonts.

While I don't quite understand why browser do not use font-weight for variable fonts, it seems to be a consistent behavior (tested with Chrome and Firefox). A solution Tailwind could provide for this problem is to have an opt-in to add `font-variation-settings` in addition to `font-weight` when any of the font-weight utilities is used - opt-in because adding those is only necessary when a project is mainly using a variable font, which is still relatively rare, but with the now reasonable browser support usage of variable fonts will probably increase.

**Comment by danielweck** [comment]
This reminds me of https://seek-oss.github.io/capsize/
( https://github.com/seek-oss/capsize )

Would make a nice Twind plugin.

**Comment by corywatilo** [comment]
For anyone looking for a workaround...

I added my own [utilities](https://tailwindcss.com/docs/adding-new-utilities#using-css) for the `font-variation-settings`. These get prioritized over the built-in utilities with the same names, so you can still use, for example, `font-bold` but have it pull in the `font-variation-settings` tag as outlined below.

```
@layer utilities {
    .font-thin {
        font-variation-settings: 'wght' 100;
    }
    .font-extralight {
        font-variation-settings: 'wght' 200;
    }
    .font-light {
        font-variation-settings: 'wght' 300;
    }
    .font-normal {
        font-variation-settings: 'wght' 400;
    }
    .font-medium {
        font-variation-settings: 'wght' 500;
    }
    .font-semibold {
        font-variation-settings: 'wght' 600;
    }
    .font-bold {
        font-variation-settings: 'wght' 700;
    }
    .font-extrabold {
        font-variation-settings: 'wght' 800;
    }
    .font-black {
        font-variation-settings: 'wght' 900;
    }
}
```

Reminder: these values must be supported by your variable font and the `font-weight` range as defined in the `@font-face` (like `font-weight: 100 900`).

This implementation isn't perfect because I'm only able to use a single font variation. The better solution would be to use CSS variables like in [web.dev's example](https://web.dev/variable-fonts/#font-variation-settings-inheritance).

**Comment by brandiqa** [comment]
I haven't found the need to add custom utilities in the current version of Tailwind( as of v3.0.24) This is an example of a solution that I've found that works for me:

In `app.css`: 
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

/* Variable Fonts */
@supports (font-variation-settings: normal) {
  @font-face {
    font-family: "Nunito";
    font-style: normal;
    font-weight: 100 900;
    font-display: swap;
    src: url("/fonts/variable/Nunito-VariableFont_wght.woff2") format("woff2");
    font-named-instance: "Regular";
  }

  @font-face {
    font-family: "Nunito";
    font-style: italic;
    font-weight: 100 900;
    font-display: swap;
    src: url("/fonts/variable/Nunito-Italic-VariableFont_wght.woff2")
      format("woff2");
    font-named-instance: "Italic";
  }
}

/* Static Fonts */
@supports not (font-variation-settings: normal) {
  @font-face {
    font-named-instance: Regular;
    font-display: swap;
    font-family: Nunito;
    font-style: normal;
    font-weight: 400;
    src: url("/fonts/Nunito-Regular.woff2") format("woff2");
  }

  @font-face {
    font-named-instance: Italic;
    font-display: swap;
    font-family: Nunito;
    font-style: italic;
    font-weight: 100 900;
    src: url("/fonts/Nunito-Italic.woff2") format("woff2");
  }

  @font-face {
    font-named-instance: SemiBold;
    font-display: swap;
    font-family: Nunito;
    font-style: semibold;
    font-weight: 600;
    src: url("/fonts/Nunito-SemiBold.woff2") format("woff2");
  }

  @font-face {
    font-named-instance: SemiBoldItalic;
    font-display: swap;
    font-family: Nunito;
    font-style: italic;
    font-weight: 600;
    src: url("/fonts/Nunito-SemiBoldItalic.woff2") format("woff2");
  }

  @font-face {
    font-named-instance: Bold;
    font-display: swap;
    font-family: Nunito;
    font-style: bold;
    font-weight: 700;
    src: url("/fonts/Nunito-Bold.woff2") format("woff2");
  }

  @font-face {
    font-named-instance: BoldItalic;
    font-display: swap;
    font-family: Nunito;
    font-style: italic;
    font-weight: 700;
    src: url("/fonts/Nunito-BoldItalic.woff2") format("woff2");
  }
}

:root {
  @apply antialiased font-sans;
}
```

In `tailwind.config.js`:

```javascript
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Nunito", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [],
};
```

Hope this helps.
