### DISCUSSION TITLE
How to relize :hover on sub element?

### DISCUSSION THREAD

**Discussion by MaxmaxmaximusAWS** [tailwindlabs/tailwindcss#3241] [Help] [answered]
Like this:
```css
.chat:hover .button {
  color: red
}
```

if the answer is “no way,” does that mean that the tailwindlabs idea is not inherently viable?

(Not trolling)
