### DISCUSSION TITLE
New utility for hiding num input spin buttons

### DISCUSSION THREAD

**Discussion by tasops** [tailwindlabs/tailwindcss#3275] [Ideas]
Howdy, what do you guys think about adding a class like this:

```css
.spin-button-none::-webkit-outer-spin-button,
.spin-button-none::-webkit-inner-spin-button {
  appearance: none;
}
```

Class name of course can be different. The idea is that the already available class `apperance-none` doesn't apply it to spin buttons for input of type number.

And yup, i made a custom utility just like the one above and it works, but its just an idea to maybe add it to the framework? What do you guys think.
