### DISCUSSION TITLE
[Feature] Sort variants by variantOrder when unstable_stack is true

### DISCUSSION THREAD

**Discussion by anuraghazra** [tailwindlabs/tailwindcss#3289] [Ideas]
## The Problem

While building our component library we faced this issue https://github.com/tailwindlabs/tailwindcss/discussions/1951 but after trying out every solution with [tailwind-override](https://github.com/richardgill/tailwind-override) and [tailwind-cascade](https://github.com/mariusmarais/tailwind-cascade) they did not fit our needs. 

Then we found this solution which worked like a charm https://github.com/tailwindlabs/tailwindcss/discussions/1446#discussioncomment-90315 which basically suggests to create a custom `base:` variant to handle the specificity issue. 

<details>
<summary>See `base:` plugin code</summary>

```js
plugin(function ({ addVariant, e }) {
  addVariant(
    "base",
    ({ container, separator, modifySelectors }) => {
      modifySelectors(({ selector }) => {
        return buildSelectorVariant(
          selector,
          "base",
          separator,
          (message) => {
            throw container.error(message);
          }
        );
      });
    },
    { unstable_stack: false } // hi
  );
}),
```

</details>

Now we want our variants to stack on top of other variants so we added the unstable_stack option in addVariant
Normally when `unstable_stack` is false
`variantOrder: ['base', 'DEFAULT']` will generate the following CSS

```css
/* base first */
.base\:bg-blue-100 {
  --tw-bg-opacity: 1;
  background-color: rgba(219, 234, 254, var(--tw-bg-opacity))
}
/* then default :) yey! */
.bg-yellow-100 {
  --tw-bg-opacity: 1;
  background-color: rgba(254, 243, 199, var(--tw-bg-opacity))
}
```
Which is what we want because we want the .bg-yellow-100 to override the .base:bg-blue-100.

but if we set `unstable_stack=true` tailwind does not follows the `variantOrder` and generates the following CSS which breaks the specificity.

```css
/* default first */
.bg-yellow-100 {
  --tw-bg-opacity: 1;
  background-color: rgba(254, 243, 199, var(--tw-bg-opacity))
}
/* base at end :( */
.base\:bg-blue-100 {
  --tw-bg-opacity: 1;
  background-color: rgba(219, 234, 254, var(--tw-bg-opacity))
}
```

## Solution

Make `unstable_stack=true` follow the variantOrder properly. 

I've did some experiments and this code does work :-
It sorts the remainingVariants by variantOrder.
file: https://github.com/tailwindlabs/tailwindcss/blob/master/src/lib/substituteVariantsAtRules.js#L184

```js
// substituteVariantsAtRules.js
let remainingVariants = prependStackableVariants(atRule, variants, stackableVariants)

// NEW CODE! Sorting the `remainingVariants` by `variantOrder`
remainingVariants = ensureIncludesDefault(remainingVariants).sort((a, z) =>{ 
  return config.variantOrder.indexOf(a) - config.variantOrder.indexOf(z)
})

_.forEach(_.without(remainingVariants,'responsive'), (variant) => {
  if (!variantGenerators[variant]) {
    throw new Error(
      `Your config mentions the "${variant}" variant, but "${variant}" doesn't appear to be a variant. Did you forget or misconfigure a plugin that supplies that variant?`
    )
  }
  variantGenerators[variant].handler(atRule, config)
})

```

Related PRs, Issues & Links:
https://tailwindcss.com/docs/configuration#variant-order
https://github.com/tailwindlabs/tailwindcss/discussions/1446
https://github.com/tailwindlabs/tailwindcss/discussions/1951
https://github.com/tailwindlabs/tailwindcss/pull/657
https://github.com/tailwindlabs/tailwindcss/issues/496
