### DISCUSSION TITLE
Writing plugins that loop through all spacing utilities

### DISCUSSION THREAD

**Discussion by Nick-Mazuk** [tailwindlabs/tailwindcss#3332] [Help]
I have the following plugin and want to generate different variants for all the different spacing units in TailwindCSS.

```js
plugins: [
    plugin(({ addUtilities }) => {
        const newUtilities = []

        newUtilities.push({
            '.grid-cols-w-64': {
                'grid-template-columns': 'repeat(auto-fill, minmax(256px, 1fr))'
            }
        })

        addUtilities(newUtilities, { variants: ['responsive'] })
    })
],
```

This plugin currently only generates the following css class:

```css
.grid-cols-w-64 {
    grid-template-columns: repeat(auto-fill, minmax(256px, 1fr))
}
```

Is there any way to easily also have?

```
.grid-cols-w-4
.grid-cols-w-5
.grid-cols-w-6
.grid-cols-w-8
.
.
.
.grid-cols-w-64
```

P.S. I'm still on Tailwind 1.9.
