### DISCUSSION TITLE
Is there a way to add a utility and have it permuted with all the colors?

### DISCUSSION THREAD

**Discussion by formido** [tailwindlabs/tailwindcss#3431] [Help]
On the tailwindui site they have a custom utility for background stripes. See examples on this page: 

https://tailwindcss.com/docs/box-sizing

A section from that page's CSS according to Chrome dev tools:

```css
.bg-stripes {
    background-image: linear-gradient(45deg,var(--stripes-color) 12.5%,transparent 12.5%,transparent 50%,var(--stripes-color) 50%,var(--stripes-color) 62.5%,transparent 62.5%,transparent 100%);
    background-size: 5.66px 5.66px
}

.bg-stripes-white {
    --stripes-color:hsla(0,0%,100%,0.4)}

.bg-stripes-amber-500 {
    --stripes-color:rgba(245,158,11,0.4)}
```

Is it possible to add a utility and have tailwind permute it with all the configured colors? I couldn't confirm by googling the docs.
