### DISCUSSION TITLE
[variant] sibling-checked

### DISCUSSION THREAD

**Discussion by shoxton** [tailwindlabs/tailwindcss#3497] [Ideas]
Is there something like a sibling-checked variant?

We could do things like:
```html
<div class="radio-box">
  <input id="hiddenRadioInput" type="radio" class="sr-only" />
  <div class="sibling-checked:bg-indigo sibling-checked:text-white">
    <label id="hiddenRadioInput" class="text-current">Hello world!</label>
  </div>
</div>
```

The syntax could be something like:
```css
input:checked ~ .sibling-checked:bg-indigo {
  background-color: indigo;
}

input:checked ~ .sibling-checked:text-white {
 color: white;
}
```

I went ahead and implemented a quick solution to myself. Kinda like this:

```js
// tailwind.config.js

    // extends newly created custom plugin
    variants: {
      extend: {
          backgroundColor: ['sibling-checked'],
          textColor: ['sibling-checked']
        }
    },

    // implements custom plugin
    plugins: [
        plugin(function({ addVariant, e }) {
          addVariant('sibling-checked', ({ modifySelectors, separator }) => {
            modifySelectors(({ className }) => {
              return `input:checked ~ .${e(`sibling-checked${separator}${className}`)}`
            })
          })
        })
      ]

```
