### DISCUSSION TITLE
Can't create custom responsive class

### DISCUSSION THREAD

**Discussion by renanyudimt** [tailwindlabs/tailwindcss#3594] [Help]
Im trying to create custom height classes named in example: h-50px and h-73px, Im importing all the tailwindcss and layers/variants, but i cant make those classes work into responsive breakpoint.

I dont know if im lack of knowledge, but i think it should work.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  @variants responsive {
    .h-50px {
      height: 50px;
    }
    .h-76px {
      height: 76px;
    }
  }
}
```

here is an example not working:

`<div className="h-50px lg:h-73px container flex content-around mx-auto"></div>`

Its always 50px

**Comment by alexanderbluhm** [comment]
@renanyudimt First, the "v" in "variants" should be no capital letter.
So:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  @variants responsive {
    .h-50px {
      height: 50px;
    }
    .h-76px {
      height: 76px;
    }
  }
}
```

Then, in your example you are using `lg:h-73px` but this class doesn't exist. You should use `lg:h-76px` instead. Then it is working as you wanted.
