### DISCUSSION TITLE
How to disable just .table from the display plugin?

### DISCUSSION THREAD

**Discussion by tordans** [tailwindlabs/tailwindcss#3604] [Help] [answered]
We have both Bootstrap and Tailwind in our app while migrating to Tailwind.
We want to disable the .table (.table-*) feature that are added as part of the display Plugin (https://tailwindcss.com/docs/display#table).

Is there any way to achieve this?

If not via the config, is there a (feasible) way to overwrite/modify the core Display plugin (https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/display.js) and use a custom version instead?

**Comment by tordans** [comment, marked as answer]
What we ended up doing:

Part 1: in our tailwind.config.js

```js
  corePlugins: {
    display: false,
  }
```

Part 2: in our tailwind.css

```css
/*
  Tailwind adds .table-classes as part of its display-corePlugin.
  Those are in conflict with Bootstrap's .table.
  Therefore, we disable the plugin in tailwind.config.js
  and add all but the .table*-Util classes back manually below.

  List of display corePlugin classes https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/display.js
*/
@layer utilities {
  @responsive {
    .block {
      display: block;
    }
    .inline-block {
      display: inline-block;
    }
    .inline {
      display: inline;
    }
    .flex {
      display: flex;
    }
    .inline-flex {
      display: inline-flex;
    }
    .flow-root {
      display: flow-root;
    }
    .grid {
      display: grid;
    }
    .inline-grid {
      display: inline-grid;
    }
    .contents {
      display: contents;
    }
    .hidden {
      display: none;
    }
  }
}
```
