### DISCUSSION TITLE
Setting Background Image Opacity

### DISCUSSION THREAD

**Discussion by GideonBrimleaf** [tailwindlabs/tailwindcss#3617] [Help] [answered]
Hello! 

The Tailwind docs [clearly show how to set the opacity of a background colour](https://tailwindcss.com/docs/background-opacity) but this does not seem to work when applying it to a background image.  For example:

```
<div class="bg-home-page-image bg-opacity-25">
```

Doesn't seem to change the opacity of the example image here for me and it seems that you need workarounds to mimic a transparent background image in CSS in general

Is there a way to achieve this in Tailwind?  Or would I need to use custom css like [this solution](https://www.digitalocean.com/community/tutorials/how-to-change-a-css-background-images-opacity)

**Comment by simonswiss** [comment, marked as answer]
Hey!

Currently it's not possible to add transparency to a background image since the `bg-opacity-{n}` updates the `--tw-bg-opacity` CSS variable, which affects background color classes - not background images.

I'd achieve it by having an "overlay" div with transparent background over the top of the image. Not exactly the same effect, but an overlayed image works quite well in many situations 👍

Here's an example in Tailwind Play:

https://play.tailwindcss.com/RnQTIA1FS1

![image](https://user-images.githubusercontent.com/485747/108457847-701ded80-72c7-11eb-8796-e296c42e0bc2.png)


Hope it helps!

**Reply by GideonBrimleaf** [reply]
Thanks @simonswiss - really helpful :)

**Comment by realdaly** [comment]
Why is it currently not possible? because there's no background image opacity in css?

**Reply by wongjn** [reply]
Exactly right.

**Reply by anjanesh** [reply]
Is this possible using TailWindCSS 4.1 now ?

**Reply by rozsazoltan** [reply]
There is currently no utility for it, but you can create your own like this:

* https://play.tailwindcss.com/YzIqQf1ESz?size=1152x720

```css
@utility bg-* {
  --tw-parent-bg-color: --value(--color-*);
  background-image: linear-gradient(
    color-mix(in srgb, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent),
    color-mix(in srgb, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent)
  ), --value([*]);
  @supports (color: color-mix(in lab, red, red)) {
    background-image: linear-gradient(
      color-mix(in oklab, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent),
      color-mix(in oklab, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent)
    ), --value([*]);
  }
}

@property --tw-parent-bg-color {
  syntax: "*";
  inherits: true;
  initial-value: #fff;
}
```

Reference:
* [Background Image with opacity in TailwindCSS](https://stackoverflow.com/a/79837064/15167500)
* https://github.com/tailwindlabs/tailwindcss/discussions/3617#discussioncomment-15151646

**Comment by gbrian** [comment]
This worked fine for me: https://stackoverflow.com/questions/64663368/background-image-with-opacity-in-tailwindcss

````html
<header
  class="relative bg-fixed bg-center bg-cover bg-no-repeat"
  style="background-image:linear-gradient(rgba(135, 80, 156, 0.9), rgba(135, 80, 156, 0.9)), url(img/hero-bg.jpg)">
  
</header>
````

With some tweaks:
````html
  <div class="relative bg-fixed bg-center bg-cover bg-no-repeat"
    :style="`background-image:linear-gradient(hsl(var(--b1) / 0.9), hsl(var(--b2) / 0.5)), url(${favlist.backgroundImage})`">
````

**Reply by simesy** [reply]
Thanks!

**Comment by gevuong** [comment]
For me, I wanted the background image to have an opacity of 0.4. I tried what others suggested by applying opacity to the linear gradient (from black to `#162b4c`), but I did not get the desired effect..

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      backgroundImage: {
        'publications-header':
          'url(../assets/phone_header.png), linear-gradient(to bottom, rgba(0, 0, 0, 0.4), rgba(22, 43, 76, 0.4))',
      }
    }
  }
}
```

```jsx
// rendered in jsx component
<div className="relative bg-publications-header bg-center">
  <h1 className="py-60 text-center text-5xl text-green-600">Publications</h1>
</div>
```

<img width="1264" alt="Screenshot 2024-04-27 at 10 28 00 PM" src="https://github.com/tailwindlabs/tailwindcss/assets/27314227/ee283f0c-ce22-40f9-b021-30479449ae56">

Instead, I needed to apply opacity directly on the background image like so:
I'm using the Next.js `Image` component here btw. As a result, I managed to get the desired effect.

```jsx
<div className="relative bg-gradient-to-b from-black to-[#162b4c]">
  <Image
    src={PhoneHeader}
    className="absolute h-full w-full object-cover opacity-40"
    alt=""
  />
  <h1 className="py-60 text-center text-5xl text-green-600">Publications</h1>
</div>
```

<img width="1261" alt="Screenshot 2024-04-27 at 10 18 08 PM" src="https://github.com/tailwindlabs/tailwindcss/assets/27314227/762fe019-9757-4d6e-aa90-979ca32dbbae">

**Comment by rozsazoltan** [comment]
### `<img>` element with `opacity-*`

If it's not important for you to use the `background-image` property, using an `img` element could also be considered.

* [TailwindCSS v4 Playground for `<img>` element with `opacity-*` utility](https://play.tailwindcss.com/IOtsCq0pEn)

```html
<div class="w-screen bg-amber-400 p-4 flex gap-4">
  <img class="size-16 opacity-30" src="https://picsum.photos/100/100" />
  <img class="size-16 opacity-50" src="https://picsum.photos/100/100" />
  <img class="size-16 opacity-70" src="https://picsum.photos/100/100" />
  <img class="size-16 opacity-100" src="https://picsum.photos/100/100" />
</div>
```

Source: [Background Image with opacity in TailwindCSS](https://stackoverflow.com/a/79837133/15167500)

### `bg-{image}` utility with `opacity-*` from parent element

But the previous example also works with the `background-image` property.

* [TailwindCSS v4 Playground for `bg-{image}` utility with `opacity-*` from parent element](https://play.tailwindcss.com/pxtmzk8OKl)

```html
<div class="w-screen bg-amber-400 p-4 flex gap-4">
  <div class="size-16 opacity-30"><div class="size-16 bg-[url(https://picsum.photos/100/100)]"></div></div>
  <div class="size-16 opacity-50"><div class="size-16 bg-[url(https://picsum.photos/100/100)]"></div></div>
  <div class="size-16 opacity-70"><div class="size-16 bg-[url(https://picsum.photos/100/100)]"></div></div>
  <div class="size-16 opacity-100"><div class="size-16 bg-[url(https://picsum.photos/100/100)]"></div></div>
</div>
```

Source: [Background Image with opacity in TailwindCSS](https://stackoverflow.com/a/79837133/15167500)

### `bg-{image}/{opacity}`

If you do want to use it, known CSS tricks can also be applied to extend the capabilities of `bg-*` utilities.

* [TailwindCSS v4 Playgroud for `bg-{image}/{opacity}` custom utility](https://play.tailwindcss.com/YzIqQf1ESz?size=1152x720)

```css
@utility bg-* {
  --tw-parent-bg-color: --value(--color-*);
  background-image: linear-gradient(
    color-mix(in srgb, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent),
    color-mix(in srgb, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent)
  ), --value([*]);
  @supports (color: color-mix(in lab, red, red)) {
    background-image: linear-gradient(
      color-mix(in oklab, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent),
      color-mix(in oklab, var(--tw-parent-bg-color) calc(100% - --modifier(integer) * 1%), transparent)
    ), --value([*]);
  }
}

@property --tw-parent-bg-color {
  syntax: "*";
  inherits: true;
  initial-value: #fff;
}
```

```html
<div class="w-screen bg-amber-400 p-4 flex gap-4">
  <div class="size-16 bg-[url(https://picsum.photos/100/100)]/30"></div>
  <div class="size-16 bg-[url(https://picsum.photos/100/100)]/50"></div>
  <div class="size-16 bg-[url(https://picsum.photos/100/100)]/70"></div>
  <div class="size-16 bg-[url(https://picsum.photos/100/100)]/100"></div>
</div>
```

Source: [Background Image with opacity in TailwindCSS](https://stackoverflow.com/a/79837064/15167500)
