### DISCUSSION TITLE
add small caps font variant

### DISCUSSION THREAD

**Discussion by ianstormtaylor** [tailwindlabs/tailwindcss#3680] [Ideas]
Just noticed that there are font variant settings for numerals, and there's the classic `uppercase` text transform, but it would be nice to have support for small caps.

Specifically:

```css
@layer utilities {
  .small-caps {
    font-variant: all-small-caps;
  }
}
```

These are nicer typographically than doing regular uppercase letterforms in fonts that support them.
