### DISCUSSION TITLE
[Feature Request] Gradient percentage stops

### DISCUSSION THREAD

**Discussion by michaelschufi** [tailwindlabs/tailwindcss#3682] [Ideas]
Hi

I'd like to propose a feature that extends the gradient feature with custom stop percentages.

What I'd like to have is to define, at which point the gradient starts/ends, without having to move my container or add an extra one just for this.

### Usage proposal

What we currently can do is:
```html
<div class="bg-gradient-to-r from-black"></div>
```

Proposed addition:
```html
<div class="bg-gradient-to-r from-black from-1/5"></div> <!-- black starts from 20% -->
<!-- or -->
<div class="bg-gradient-to-r from-black from-20"></div> <!-- black starts from 20% -->
<!-- and the via and to equivalents -->
```

### Idea for implementation
As far as I understand it, a CSS variable for each stop (from, to, via) could be introduced, which can then be used by the color classes.

(Haven't tried this yet)

Current
```css
/* Will stay the same */
.bg-gradient-to-r {
  background-image: linear-gradient(to right, var(--tw-gradient-stops));
}

/* Will be updated */
.from-black {
  --tw-gradient-from: #000;
  --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(0, 0, 0, 0));
}

/* Will be updated */
.via-black {
  --tw-gradient-stops: var(--tw-gradient-from), #000, var(--tw-gradient-to, rgba(0, 0, 0, 0));
}

/* stays the same */
.to-black {
  --tw-gradient-to: #3480;
}
```

New
```css
/* Will stay the same */
.bg-gradient-to-r {
  background-image: linear-gradient(to right, var(--tw-gradient-stops));
}

/* Will be updated */
.from-black {
  --tw-gradient-from: #000;
  --tw-gradient-stops: var(--tw-gradient-from) var(--tw-gradient-from-stop),
                       var(--tw-gradient-to, rgba(0, 0, 0, 0)) var(--tw-gradient-to-stop);
}

/* Will be updated */
.via-black {
  --tw-gradient-stops: var(--tw-gradient-from) var(--tw-gradient-from-stop),
                       #000 var(--tw-gradient-via-stop), 
                       var(--tw-gradient-to, rgba(0, 0, 0, 0)) var(--tw-gradient-to-stop);
}

/* stays the same */
.to-black {
  --tw-gradient-to: #000;
}

/* New */
.from-1\/5 {
  --tw-gradient-from-stop: 20%;
}

.via-1\/5 {
  --tw-gradient-via-stop: 20%;
}

.to-1\/5 {
  --tw-gradient-to-stop: 20%;
}
```
