### DISCUSSION TITLE
[Feature Proposal] Add new "ellipsis" utility

### DISCUSSION THREAD

**Discussion by benface** [tailwindlabs/tailwindcss#377] [Ideas]
I know there is a `truncate` utility:

```css
.truncate {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

But I suggest adding an `ellipsis` utility that doesn't truncate unless absolutely necessary (when the text cannot wrap anymore):

```css
.ellipsis {
    overflow: hidden;
    text-overflow: ellipsis;
}
```

**Comment by benface** [comment]
Alternatively, `white-space: nowrap;` could be removed from `.truncate`, as there is already a separate class for it: `.whitespace-no-wrap`. So to get the current behaviour you'd need `class="truncate whitespace-no-wrap"`.

**Comment by terryupton** [comment]
I favour your second option @benface. The nature of Tailwind and css utilities ideally is that each class does its own thing. So I’d say the second option seems more suited and flexible.

**Comment by adamwathan** [comment]
Can you provide an example of where this would be useful? I can't for the life of me get `text-overflow: ellipsis` to do anything without `white-space: nowrap`.

**Comment by adamwathan** [comment]
Got an example:

https://jsfiddle.net/7qhu8hmq/3/

**Comment by caneco** [comment]
I use a lot on table cells.

**Example:**
![image](https://user-images.githubusercontent.com/502041/36985032-2326ad98-208e-11e8-9564-8f08f245df13.png)

**Comment by benface** [comment]
After a discussion with Adam on Slack, I think the best solution would be a new utility that sets just one property:

```css
.ellipsis {
    text-overflow: ellipsis;
}
```

Because there is already a `overflow-hidden` utility, so you could either do:

```html
<div class="truncate">To truncate one line of text, without wrapping</div>
```

or

```html
<div class="ellipsis overflow-hidden">To truncate when the text cannot wrap anymore</div>
```

**Comment by benface** [comment]
@adamwathan Interested in a PR that adds this class?

```css
.ellipsis {
    text-overflow: ellipsis;
}
```

**Comment by benface** [comment]
Hey @adamwathan I see you've been closing many issues today, what are your thoughts about this?

**Comment by adamwathan** [comment]
Still open to adding it just not sure where it should live. Would probably want to add an "undo" utility that sets `text-overflow: clip` which makes naming trickier.

**Comment by benface** [comment]
Oh yeah, @hacknug and myself have put some thought into it here: https://github.com/benface/tailwindcss-typography/issues/5

**Comment by simensen** [comment]
`to-ellipsis` / `to-clip` look interesting, but it was quite hard for me to figure out what the name meant since I initially read it as `toEllipsis` or `toClip` like `toString`. `t-overflow-[key]`, perhaps?

**Comment by hacknug** [comment]
Yeah, I suggested `.to-[key]` because I prefer weird short _namespaces_ than longer ones like `.t-overflow-[key]` haha

Right now core uses two conventions for text utilities: `.text-[key]` and `.[key]`. Adopting the first one might cause unexpected collisions in some cases and I don't think the second one makes much sense in this case.

Another option I don't like a lot would be `.overflow-[key]`…

**Comment by simensen** [comment]
Even `.t-o-[key]` might be less ambiguous than `.to-[key]`.

Would `.text-overflow-ellipsis` and `.text-overflow-clip` be too on the nose?

**Comment by benface** [comment]
@adamwathan What do you think about:

```css
.ellipsis {
  text-overflow: ellipsis;
}
.no-ellipsis {
  text-overflow: clip;
}
```
