### DISCUSSION TITLE
@apply vs composes postcss

### DISCUSSION THREAD

**Discussion by Kepro** [tailwindlabs/tailwindcss#3802] [Ideas]
Hello, we are looking to use Tailwind CSS in our react project with CSS modules, from documentation is there to use it with `@apply` 

example:
```scss
// input
.root {
  @apply flex align-center;
}
// output
.root {
  display: flex;
  align-items: center;
}
```
so that will add more CSS to code instead of just using that class (and we have a lot of features so we want to keep size of build as small as possible) 
the second usage is with composes, but with composes, we lose "validation" if the class exists because we are referring to the global scope
```scss
// input
.root {
  composes: flex align-center from global;
}
// output
styles.root => 'root_HaSh flex align-center'
```

it's possible to create something like this?
```scss
.root {
  composes: flex align-center from tailwind // or from @tailwind
}
```
