### DISCUSSION TITLE
Tailwind throws error during production build

### DISCUSSION THREAD

**Discussion by geantas** [tailwindlabs/tailwindcss#3824] [Help] [answered]
I have faced the following issue: when I develop the Nuxt+Tailwind project and push it to GitHub, run workflow to build (or generate) the app, Tailwind shows me an error about non-existing `text-gray-50`:
```
Run ./node_modules/.bin/nuxt build --fail-on-error
[fatal] Nuxt build error
  ERROR in ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css)
  Module build failed (from ./node_modules/postcss-loader/src/index.js):
  SyntaxError
  
  (24:9) `@apply` cannot be used with `.text-gray-50` because `.text-gray-50` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.text-gray-50` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
  
  22 |
  23 |     .button-main {
  > 24 |         @apply min-w-60 bg-themeSec-reg border border-transparent rounded-md py-2 px-4 mt-4
  |         ^
  25 |         mb-6 flex items-center justify-center text-center font-medium text-base font-medium text-gray-50
  26 |         shadow-sm shadow-as-border outline-none whitespace-nowrap ring-0
  
  @ ./assets/css/tailwind.css 4:14-166
```
If I remove the `text-gray-50`, it will show an error about `whitespace-nowrap`. If I remove that, then it's complaining about `ring-0`, etc.

 If I access the `localhost:3000/_tailwind` locally, I can see the `text-gray-50` present. If I run `nuxt build` or `nuxt generate` on my local machine, it works just fine. Also, I did set `NODE_ENV=production` on my machine and it is all smooth.
My `tailwind.css` file:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind screens;

@layer components {
    .button-main {
        @apply min-w-60 bg-themeSec-reg border border-transparent rounded-md py-2 px-4 mt-4
        mb-6 flex items-center justify-center text-center font-medium text-base font-medium text-gray-100
        shadow-sm shadow-as-border outline-none whitespace-normal ring-0
        transition-all duration-200 ease-in
        hover:bg-themeSec-dark active:bg-themeSec-darker focus:outline-none active:outline-none;
    }
...
}

```
I've tried both with and without `@layer components`, also with `@layer base`, placing the `@tailwind base; etc.` to the bottom of the file, but it failed everytime.
`tailwind.config.js` file:
```js
module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'components/**/*.{vue,js}',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.{js,ts}',
      'nuxt.config.{js,ts}'
    ]
  },
....
}
```

`package.json` file:

```json
  ...
  "dependencies": {
    ...
    "@nuxtjs/tailwindcss": "^3.4.3",
    "@tailwindcss/postcss7-compat": "^2.0.3",
    "autoprefixer": "^9",
    "postcss": "^7",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat",
   ...
  }
 ...
```

Any ideas what might be wrong?
