### DISCUSSION TITLE
Make tailwindcss modal dialog with scrolling content?

### DISCUSSION THREAD

**Discussion by sergeynilov** [tailwindlabs/tailwindcss#3878] [Help]
Hello,
Basing on tailwindcss 2 modal example https://alpinetoolbox.com/examples/modal 
I make modal dialog with header/footer/ Content with many rows. 
I need header and footer always be visible. Content must be scrollable.
I try to set content with scrolling bar, like

```
<div  style="height : calc( 100vh - 120 ) !important;" >
    <div class="modal-header flex justify-between items-center pb-2">
         ...
    </div>

     <div class="modal-content py-4 text-left px-6  overflow-y-auto "  style="height : calc( 100vh - 320 ) !important;">

```                   
            
But failed. Please take a look at codepen : https://codepen.io/sergeynilov/pen/vYyPrrE

Thanks!

**Comment by olets** [comment]
Did you mean to put the `flex justify-between` on the outer div? Moving those classes from the header element to the wrapper, and adding `flex-col` will get you close, but you still need to prevent it from being taller than the screen.

There are flexbox and grid solutions to "sticky header and footer". Here is a common minimal flexbox solution: https://codepen.io/henry/pen/mdRWyyY

Its model is

```css
.wrapper {
  display: flex;
  flex-direction: flex-column;
  height: the height for your design;
  max-height: 100vh (and account for mobile browser ui if necessary)
}

.content {
  flex-grow: 1;
}
```

```html
<section class="wrapper">
  <header>...</header>
  <div class="content">...</div>
  <footer>...</footer>
</section>
```

Don't forget accessibility! Your basic options are the [`dialog` element](https://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html) or the [`"dialog"` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role)

_edit: add html snippet_
