### DISCUSSION TITLE
Add support for text underline offset

### DISCUSSION THREAD

**Discussion by mauroreisvieira** [tailwindlabs/tailwindcss#3909] [Ideas]
Hey, 

I don't know if the TailwindCSS team already has that in mind but It would be nice to have a class to set underline offset like `underline-offset-4`.

```css
.underline-offset-4 {
   text-underline-offset: 4px
}
```

That CSS property is almost supported for all browsers: https://caniuse.com/?search=text-underline-offset
