### DISCUSSION TITLE
Purge unused css in jsx files

### DISCUSSION THREAD

**Discussion by kien5436** [tailwindlabs/tailwindcss#3926] [Help] [answered]
Hello, I'm new in `tailwindcss`. I want to keep only classes used in jsx files but I can't understand how to get the right config. When I use default config, nothing is purged; when I add `enabled: true` every classes are gone! Below are my config:
`tailwind.config.js`:
```js
module.exports = {
  purge: {
    enabled: true,
    content: [
      './src/scripts/**/*.jsx',
    ],
    options: {
      keyframes: true,
    },
  },
  darkMode: 'class',
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```
`styles/index.css`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: 'Nunito', sans-serif;
}

@layer components {

  .btn {
    @apply px-5 py-3 rounded;
  }

  .btn-blue {
    @apply bg-blue-500 hover:bg-blue-600 text-white;
  }
}
```
`scripts/index.jsx`: Here, purgecss should keep classes inside jsx tag but not
```js
import '../styles/index.css';

import { h, render } from 'preact';

function App() {

  return (
    <div className="container">
      <h1 className="text-center text-4xl text-red-500">Hello</h1>
      <button type="button" className="btn btn-blue">hover me</button>
    </div>
  );
}

render(<App />, document.body);
```
`webpack.config.js`:
```js
...
 module: {
    rules: [{
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: {
                  tailwindcss: { config: resolve('tailwind.config.js') },
                  autoprefixer: {},
                }
              }
            }
          }
        ],
      },
```
`package.json`:
```json
"webpack": "4.44.1",
"postcss": "^8.2.9",
"postcss-loader": "4",
"tailwindcss": "^2.0.4",
"autoprefixer": "^10.2.5",
"css-loader": "^3.0.0",
```
Sorry for my poor English, any help will be appreciate
