### DISCUSSION TITLE
Remove "enabler" class pattern

### DISCUSSION THREAD

**Discussion by neupauer** [tailwindlabs/tailwindcss#3936] [Ideas]
## Remove "enabler" class pattern

Hi, I've found myself a few times (especially when I started with Tailwind) that I forgot to add an "enabler" class for some utilities (e.g. `.transform`).

Since the "enabler" pattern starts became used more and more (e.g., new `.filter` and `.backdrop-filter` utilities https://github.com/tailwindlabs/tailwindcss/pull/3923), I have got an idea of how to remove the need for the "enabler" class pattern.

> By **"enabler"** I mean if you want to use some utilities e.g. `.rotate-1` you must add "enabler" class ( `.transform` )

### [CSS Attribute selectors `[attr*=value]`](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#syntax)

Represents elements with an attribute name of attr whose value contains at least one occurrence of value within the string.

### Idea

Right now, if some CSS rule accepts multiple values then the "enabler" is introduced. For example, if you want to use the `backdrop-filter` you have to add `backdrop-filter` and then stack other filter functions on top of it `backdrop-blur-*`, `backdrop-sepia-*`...

```html
<div class="backdrop-filter backdrop-blur-1 backdrop-sepia-1"> <!-- Content --> </div>
```

Behind the scene, something like this is used:

```css
.backdrop-filter {
  backdrop-filter: var(--tw-backdrop-blur) var(--tw-backdrop-sepia) /* var(--tw-backdrop-...) */
}
```

What about this:

```css
[class*=backdrop-] {
  backdrop-filter: var(--tw-backdrop-blur) var(--tw-backdrop-sepia) /* var(--tw-backdrop-...) */
}

/* OR */

[class*=backdrop-blur-], [class*=backdrop-sepia-] {
  backdrop-filter: var(--tw-backdrop-blur) var(--tw-backdrop-sepia) /* var(--tw-backdrop-...) */
}
```
It will match this (without the need of `.backdrop-filter` class)

```html
<div class="backdrop-blur-1 backdrop-sepia-1"> <!-- Content --> </div>
```

This pattern can be applied also on: `filter`, `transform`, `transition` and other "enabler" like utilities.

#### Breaking chage

If the "enabler" class is used to enable/disable stacked utilities e.g. `className={predicate ? 'transform' : ''}` will need to be rewritten to something like this `className={predicate ? '' : 'transform-none'}`.

#### Performance

I am not sure how it can affect performance or how to measure it. But I think matching the regular expression will be slower than just finding an exact class.
