### DISCUSSION TITLE
Replicate Tailwind link styling using Tailwind

### DISCUSSION THREAD

**Discussion by evelynccordner** [tailwindlabs/tailwindcss#4209] [Help] [answered]
I'm hoping to replicate the styling of Tailwind Links in a project I'm working on, and I'm hoping to achieve this styling using Tailwind! 

![Screen Shot 2021-04-29 at 12 45 53 PM](https://user-images.githubusercontent.com/5140736/116609182-f0288b00-a8e8-11eb-9a92-abb130ca8413.png)

The effect we are looking for is an underlined block that overlaps the text slightly. I've tried to achieve this using a number of techniques including underlines, bottom borders, backgrounds, and shadows but have not found success.

I'm very new to Tailwind so any help would be much appreciated!

**Comment by jenstornell** [comment, marked as answer]
What I can see these functions are not built into Tailwind yet.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color

If you want to add them yourself you can do that in your `tailwind.css` class.

```css
@tailwind base;
@tailwind components;

.decoration-red-500 {
  text-decoration-color: red !important;
}

@tailwind utilities;
```

```html
<a href="#" class="underline decoration-red-500">My link</a>
```

*There is probably a better way to do it but this is quick.*
