### DISCUSSION TITLE
JIT mode default touch directory permission issue on Docker

### DISCUSSION THREAD

**Discussion by bwyx** [tailwindlabs/tailwindcss#4234] [Help] [answered]
I'm trying to setup **@vitejs** with **@tailwindcss** on Docker

using official node's official image v16
```
# ./app/Dockerfile

FROM node:16

...
```
set Docker image workdir to `~/app`
```
# ./app/Dockerfile

...
WORKDIR /home/node/app
```

mount current local volume for development
```yaml
# ./docker-compose.yml
services:
    web:
        build:
            context: ./app
        volumes: 
            - ./app:/home/node/app
```

its throw an error when Vitejs import styles which is proceeded by tailwindcss:
_[plugin:vite:css]_ **`EACCES: permission denied, mkdir '/root/.tailwindcss/touch'`**

not long after I found the answer, below..

**Comment by bwyx** [comment, marked as answer]
turn out to be tailwindcss [JIT mode default touch directory caused this](https://github.com/tailwindlabs/tailwindcss/blob/d76c55afc6bcbaf40971289475c8bf78568d9bab/src/jit/lib/setupContext.js#L35)

simply add `TAILWIND_TOUCH_DIR` or `TAILWIND_DISABLE_TOUCH` [env](https://docs.docker.com/compose/environment-variables/) will fix:

```yaml
# ./docker-compose.yml
services:
    web:
        environment: 
            - TAILWIND_TOUCH_DIR=/home/node/app.tailwindcss // allowed permission dir
            or
            - TAILWIND_DISABLE_TOUCH=true // disable writing temp files, I didn't see performance issue by disable this
        build:
            context: ./app
        ports:
            - "3000:3000"
        volumes:
            - ./app:/home/node/app
```

[Docker ENV docs](https://docs.docker.com/compose/environment-variables/)

OR --

just disable JIT mode entirely
```js
module.exports = {
// mode: "jit"
...
}
```

edit: repo permalink

**Reply by quentincaffeino** [reply]
Thanks, you have saved me from hours of grinding for the answer. Also I would suggest this setup:

```yaml
services:
  web:
    ...
    tmpfs:
      - /tmp
    environment:
      TAILWIND_TOUCH_DIR: /tmp/tailwindcss
    ...
```

[Tmpfs docs](https://docs.docker.com/storage/tmpfs/)
