### DISCUSSION TITLE
generating css file doesn't take custom classes from <style> section

### DISCUSSION THREAD

**Discussion by gregorvoinov** [tailwindlabs/tailwindcss#4247] [Help]
Hi,

if I'm using this command to create my styles

> "tailwind": "NODE_ENV=production postcss ./src/assets/index.css -o ./dist/index.css"

```js
<template>
  <div class="hello">Some text</div>
</template>

<style scoped>
.hello{
  @apply text-9xl text-pink-600
}
</style>
```
this is the result

```css
.text-9xl {
    font-size: 8rem;
    line-height: 1
}
.text-pink-900 {
    --tw-text-opacity: 1;
    color: rgba(131, 24, 67, var(--tw-text-opacity))
}
```

but how I can get a result like this?

```css
.hello {    
    font-size: 8rem;
    line-height: 1;    
    --tw-text-opacity: 1;
    color: rgba(131, 24, 67, var(--tw-text-opacity))
}
```

If I build the whole project then ".hello" is placed in my bundled js

![image](https://user-images.githubusercontent.com/9499590/117146919-fe791a00-adb4-11eb-803c-91d0ecd0a5b5.png)

But how do I get this with a seperate css file?

I have created a simplified repo
https://github.com/gregorvoinov/tailwind

**Update**

If I use @layer in file ./src/assets/index.css it works
![image](https://user-images.githubusercontent.com/9499590/118464380-1465d380-b701-11eb-95ae-6ff1c6b00e98.png)

but when I try to use @layer in my singlefilecomponent, it doesn't work 
![image](https://user-images.githubusercontent.com/9499590/118464648-63136d80-b701-11eb-8576-bf65eea858f0.png)
