### DISCUSSION TITLE
[JIT] Production build produces incorrect results

### DISCUSSION THREAD

**Discussion by therealgilles** [tailwindlabs/tailwindcss#4282] [Help]
Once in a while, I run into an issue where the production build outputs incorrect results.

I am using Tailwindcss v2.1.2 on Debian Linux 10 with laravel-mix v6.0.18 with postcss / postcss-import / postcss-nested / postcss-nested-ancestors / postcss-preset-env.

```CSS
.analytics {
	.dataTables_wrapper .dataTables_filter label,
	.dataTables_length label {
		@apply text-base;
		line-height: 40px;
	
		input[type="search"] {
			@apply bg-white;
		}
	}
}
```

The production build outputs the following:
```CSS
.analytics .dataTables_length label,.analytics .dataTables_wrapper .dataTables_filter label{font-size:16px;line-height:24px;line-height:40px;--tw-bg-opacity:1;background-color:rgba(255,255,255,var(--tw-bg-opacity))}
```

Somehow the 'input[type="search"] part disappeared and the background color styling got merged.

Please let me know if my css code is incorrect and/or if there is a way to root cause this issue.
