### DISCUSSION TITLE
Add @extend to tailwind

### DISCUSSION THREAD

**Discussion by tavrez** [tailwindlabs/tailwindcss#4293] [Ideas]
Greeting,
First, I haven't found anything similar to what I'm gonna ask, if it exists, my apologies and please link me to it :)

Can we have something like less and sass `extend` ability to use it instead of `@apply`?
For example:
```css
.btn {
@extend p-4, px-4;
}
```
would result:
```css
.p-4, .btn {
  padding: 1rem;
}
.px-4, .btn {
  padding-left: 1rem;
  padding-right: 1rem;
}
```

As far as I know this doesn't make css processing fast, but the file size will be much smaller. What do you think?
