### DISCUSSION TITLE
[Feature Proposal] Classes for `width: calc(100% + *)`

### DISCUSSION THREAD

**Discussion by hmaesta** [tailwindlabs/tailwindcss#4300] [Ideas]
![Screen-Recording-2021-05-10-at-15 42 17](https://user-images.githubusercontent.com/741969/117708606-65784380-b1a6-11eb-83ce-0916ae0d6997.gif)

→ [Working example here.](https://play.tailwindcss.com/Ikmf875wET)

---

When having an `absolute` element behind something it's easy to match the parent `relative` with `w-full`, but sometimes a little margin is welcome.

The easiest way to do that without breaking anything is using **negative `top` and `left`** and them adding the negative `left` value multiplied by 2 in `width`.

```css
.parent {
   position: relative;
}

.child {
   position: absolute;
   top: -1rem;
   left: -1rem;
   width: calc(100% + 2rem); /* `2rem` because `left` is `1rem` */
   padding: 1rem;
}
```

Currently in Tailwind CSS there is no class for width beyond 100%, so this is a **proposal** for `w-extra-*`, that would create a class for each `spacing` value.

For instance:
```css
.w-extra-1 {
  width: calc(100% + theme('spacing.1'));
}

.w-extra-2 {
  width: calc(100% + theme('spacing.2'));
}

.w-extra-3 {
  width: calc(100% + theme('spacing.3'));
}

.w-extra-4 {
  width: calc(100% + theme('spacing.4'));
}
```

A working prototype was made with play.tailwindcss.com.
Take a look how simple the code can be.
 
- **https://play.tailwindcss.com/Ikmf875wET**
