### DISCUSSION TITLE
JIT - Allow plugins access to the dynamic syntax.

### DISCUSSION THREAD

**Discussion by ShanonJackson** [tailwindlabs/tailwindcss#4368] [Ideas]
Color is extremely important to us, and our designers.

Thus in css modules we implemented our own color system with css variables that we couldn't replicate in tailwind css; However now with the JIT compiler syntax availability of   w-[700px]  can make this possible, but if we can access what values are being used in the square brackets inside tailwind config.

Old    .module.scss system.
```css
// css variable setup.
--secondary-hs: 0, 0%;
--secondary-l: 92.9%;
--secondary-color-hs: 0, 0%;
--secondary-color-l: 20%;

// helpful utility variables.
$secondary: #{"hsl(var(--secondary-hs), var(--secondary-l))"};
$secondary-color: #{"hsl(var(--secondary-color-hs), var(--secondary-color-l))"};

// Now can achieve dynamic scaling by scaling the remaining % to 100% (light) and 0% (dark) respectively. This is the methodology used by SCSS's inbuilt scale_color but instead implemented purely with css variables.

@function scalec($hslvariable, $percent) {
	$hs: hs($hslvariable);
	$lightness: l($hslvariable);
	@if $percent > 0 {
		@return #{"hsl(#{$hs}, calc(#{$lightness} + calc(100% - #{$lightness}) * #{$percent / 100}))"};
	}
	@return #{"hsl(#{$hs}, calc(#{$lightness} + #{$lightness} * #{$percent / 100}))"};
}

// usage.
background-color: scalec($secondary, -45)   // darker 45% of remaining %
```

Proposed implementation in Tailwind.css
```
usage: 

<div className={"secondary-[-45]  text-secondary-[45] "}>

{
    mode: "jit",
    // ...rest of config.
    colors: {
        "secondary": "hsl(var(--secondary-hs), var(--secondary-l))"
    }
    plugins: [
        plugin(function({something}) {
              // something here that allows me to access values within square brackets in JIT mode.
        })
    ]
}
```

Note this is completely different than just hardcoding the color scales 50->900 variants, this system isn't flexible enough for us as we use alot more scales and often weird/obscure scales like   8% lighter/darker and 18% etc. We don't want to have to specificy all the scales we're using ahead of time; Nor do we want to create a system where developers need to add the scale they want to the tailwind config before they can use it.

Because of how the scalec function works, its very easy to swap the theme yet still get an nice looking result as again you're only scaling the remaining % to white/black respectively.

**Caveat:** I'm actually quite new to tailwind css, so if there's a way to achieve this in the current setup let me know.
