### DISCUSSION TITLE
Whether you can add important to a single class name

### DISCUSSION THREAD

**Discussion by J-env** [tailwindlabs/tailwindcss#4375] [Help]
I want to add important for a single class name.

```jsx
<div className="pt-0!"></div>
```

output:
```css
.pt-0\! {
  padding-top: 0 !important;
}
```
