### DISCUSSION TITLE
Right to Left language support?

### DISCUSSION THREAD

**Discussion by scottromack** [tailwindlabs/tailwindcss#4418] [Ideas]
Is Right to Left language support a thing now? It is pretty easy to add if not.

**Comment by scottromack** [comment]
### Here is an example for .space

```css
.space-x-16 > :not(template) ~ :not(template) {
  --space-x-reverse: 0;
  margin-right: calc(4rem * var(--space-x-reverse));
  margin-left: calc(4rem * calc(1 - var(--space-x-reverse)));

    @supports (margin-inline-start: 0) {
        margin-left: unset;
        margin-inline-start: calc(4rem * calc(1 - var(--space-x-reverse)));
  }
}
```
