### DISCUSSION TITLE
Add  -webkit-fill-available for 100vh classes to fix iOS bottom navbar

### DISCUSSION THREAD

**Discussion by ZapaNOR** [tailwindlabs/tailwindcss#4515] [Ideas]
On iphone setting an element to height 100vh will actually make it larger than the viewable part of the screen, because the safari bottom navbar will cover it.

Adding (min / max) - height:  -webkit-fill-available; for the classes min-h-screen, max-h-screen and h-screen would fix this, and still fall back to 100vh for those who dont support  -webkit-fill-available.

**Comment by alvis** [comment]
I agree. Currently, I have to make a custom class like
```css
.min-safe-h-screen {
  /* equivalent to 100dvh in major browsers */
  min-height: calc(
    100vh - env(safe-area-inset-bottom, 0) - env(safe-area-inset-top, 0)
  );
}

@supports (-webkit-touch-callout: none) {
  .min-safe-h-screen {
    /* for ios safari 15, safe-area-inset-bottom is 0, so a special fix apply here */
    min-height: -webkit-fill-available;
  }
}
```

**Comment by adamwathan** [comment]
I'd recommend using this PostCSS plugin after Tailwind:

https://github.com/postcss/postcss-100vh-fix

The problem is though even the `-webkit-fill-available` fix isn't a complete solution because there's still a similar bug in Chrome for Android that you have to deal with.

Personally I have just completely given up on using 100vh ever, and rely on `height: 100%` in the `html` and `body` tags with a bunch more `h-full` drilling to make full height stuff work. Annoying but haven't found any other solution.

**Reply by ghost** [reply]
How about adding dvh, lvh and svh to Tailwind :)
https://mobile.twitter.com/jensimmons/status/1499441043930062854

**Reply by longfellowone** [reply]
@adamwathan Only issue with drilling the h-full is the content outside of the h-full overflows the body, is the ok/"proper"?

```html
<Html className="h-full">
  <body className="h-full">
    <div className="relative h-full">
      <Image src={heroImage} alt="kitchen lighting" priority objectFit="cover" layout="fill" />
    </div>
    <div className="mt-6">
      This text overflows body
    </div>
  </body>
</Html>
```

**Comment by spencerjsmall** [comment]
@alvis's solution worked in my project for setting a container's height correctly, but the primary child of the container was unable to expand with "h-full". My solution was to make the container a flex box and have the child "grow". Hope this helps anyone who encountered a similar issue.

**Comment by michael-mcgreal** [comment]
Another tip: If you only need to support newer browsers, the new `cqh` (container query height) unit defaults to the "smallest viewport height" value. 

Currently, chrome supports `cqh` and safari supports `svh`. The new tailwind supports utility can help:

`className="supports-[height:100cqh]:h-[100cqh] supports-[height:100svh]:h-[100svh]"`

(Note: You do not need to mark any divs as @containers to use this `cqh` unit.)

**Reply by marc0u** [reply]
Thanks! This is the only way that works for me, I tried the `-webkit-fill-available` method but it doesn't work. I set the parent with the class you suggest and the child with h-full.

**Reply by dinesh-hills** [reply]
Thanks you, this solution worked for me.

**Reply by jacobbinnie** [reply]
Legend - this worked for me!

**Reply by dokgu** [reply]
Would `dvh` be better than `svh` in this case?

**Comment by karelric** [comment]
Take a look into this https://web.dev/viewport-units/

**Comment by shivekkhurana** [comment]
Unrelated Fix


I had the same problem. `100svh` works on some devices (both apple and android), but its support questionable. For example, it didn't work on One plus phones. 

I ended up using a JS solution by setting the height of the div to `window.innerHeight`

![bitmoji](https://sdk.bitmoji.com/render/panel/a0b632ea-13bd-4ca7-96fe-32213b64ad84-18ee6f40-00b3-40e0-87de-e4f7808f57d4-v1.png?transparent=1&palette=1&width=246)

**Comment by kanchansapkota27** [comment]
I also encountered the same problem ...for a quick fix I created a outer div with absolute position and inset-0 and set the children to have h-full. Hope this helps anyone for a quick fix.

**Comment by ms2d** [comment]
Not sure about Chrome/Android. But this works for me on iOS:

    /* Add to style.css */
    @supports (-webkit-touch-callout: none) {
      .h-screen {
        height: 100vh;
        max-height: -webkit-fill-available !important;
      }
    }

**Reply by woutersamaey** [reply]
For the latest version is should be `.min-h-screen`, right?
Maybe someone make a PR for this?

**Reply by LeeSangMin12** [reply]
you're awsome!

**Comment by gaborvecsei** [comment]
Use this (from https://stackoverflow.com/a/66501522/5108062):

```html
<!-- this will use the whole viewport even in mobile -->
<div class="absolute inset-0">
    <div>
      lorem ipsum
    </div>
</div>
```

**Comment by ianstreator** [comment]
If you want to retain your app's content within the actual visible screen, you can use 100dvh and where ever you are setting that you also need to set that same element to relative.

_index.css_
`
html,
body {
     position: relative;
     min-height: 100dvh;
}
`

all children will now fall within the devices viewport.

**Reply by alvoscares** [reply]
It worked for me, and so easy. Thx  man 😄

**Comment by rortan134** [comment]
I ended up doing this on my project
```css
/**
 * @see: https://benborgers.com/posts/tailwind-h-screen
 */
@supports (height: 100dvh) {
    :root {
        --viewport-height: 100dvh;
    }
    .h-screen {
        height: 100dvh;
    }
    .max-h-screen {
        max-height: 100dvh;
    }
}
@supports (-webkit-touch-callout: none) and not (height: 100dvh) {
    :root {
        --viewport-height: -webkit-fill-available;
    }
    .h-screen {
        height: -webkit-fill-available;
    }
    .max-h-screen {
        max-height: -webkit-fill-available;
    }
}
@supports (height: -webkit-fill-available) and not (height: 100dvh) {
    :root {
        --viewport-height: -webkit-fill-available;
    }
    .h-screen {
        height: -webkit-fill-available;
    }
    .max-h-screen {
        max-height: -webkit-fill-available;
    }
}

```
