### DISCUSSION TITLE
CSS variables for stuff like colors

### DISCUSSION THREAD

**Discussion by ghost** [tailwindlabs/tailwindcss#4518] [Ideas]
Hello

```css
:root {
  --cool-gray-100: #F9FAFB;
  --cool-gray-100-rgb: 249, 250, 251; // because of the rgba support
}

// we can also do stuff like
.my-component: {
  background: var(--cool-gray-100)
}
```

This feature 100% needed right now.

Please upvote. We, developers, deserve full-featured tools.

**Comment by jenstornell** [comment]
In the developer tools we can see that what's generated is something like below:

```css
.bg-white {
    --tw-bg-opacity: 1;
    background-color: rgba(255, 255, 255, var(--tw-bg-opacity));
}
```

It means that for opacity you already have a value but it's set directly to1 in this case.

I've also run into this from time to time, wanting to just get a color by its name. For me it's edge cases like when I test something with inline style or using arbitrary values. I hope they find a solution for it in the future.

**Reply by ghost** [reply]
It's necessary to have a HEX and an RGB type color value.

We don't need opacity variables directly in CSS.

**Comment by VicGUTT** [comment]
Hey !
I believe you can simply do the following in your `tailwind.config.js` file:

```js
{
    theme: {
        colors: {
            white: 'var(--color-white)',
            primary: {
                50: 'var(--color-primary-50)',
                // ...
            },
        },
    },
}
```
```css
/* Some CSS somewhere */
:root {
    --color-white: #fff;
    --color-primary-50: #123456;
}
```


You may be inspired by [this solution](https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo) or you might find it useful to use a plugin like [this one](https://github.com/mertasan/tailwindcss-variables#colorvariable).

**Side note**: In the future I'd advise you to be a bit more detailed and explicit as to what your issue is, what you need help with, and how can anyone help you. Also, try to be a bit less _We, developers, deserve_ aka entitled.

Hope it helps.
