### DISCUSSION TITLE
Straightforward way as a plugin author to "handle" specific JIT features

### DISCUSSION THREAD

**Discussion by VicGUTT** [tailwindlabs/tailwindcss#4529] [Help]
Hey ! Following up on my small [Twitter thread](https://twitter.com/VictorGutt/status/1399397308027097091) where I was wondering if there are any docs/examples on taking advantages of JIT specific features as a plugin author.

I have a couple plugin ideas in mind that would benefit from a little guidance on the matter.
The one I referenced in the thread is a quick "proof of concept" of how Tailwind could handle [Container Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries).

Here the queries would need to be provided with "container sizes" and the plugin could retrieve some defined values from the user's theme but it could also let user define those sizes on demand as the sizes will probably be specific to each component the user is styling.

Here's a full example of how I was thinking it would work:

```js
// tailwind.config.js
module.exports = {
    theme: {
        containerQueries: {
            sizes: {
                // ...
                sm: '1234px',
            }
        },
    },
    variants: {
        extend: {
            backgroundColor: ['containerQueries'],
        },
    },
    plugins: [
        require('@vicgutt/tailwindcss-container-queries')({
            containerClassName: 'containment-context',
        }),
    ],
}
```

```html
<section class="containment-context">
    <article class="bg-white size:screen-sm:bg-red-500 size:sm:bg-indigo-500 size:[1400px]:bg-black">
        ...
    </article>
    <article class="bg-white size:screen-sm:bg-red-500 size:sm:bg-indigo-500 size:[1400px]:bg-black">
        ...
    </article>
</section>
```

*Output*

```css
.containment-context {
    contain: layout style inline-size;
}

/* Size from: theme('screens.sm') */
@container (min-width: 640px) {
    .size\:screen-sm\:bg-red-500 {
        background-color: rgba(...);
    }
}

/* Size from: theme('containerQueries.sizes.sm') */
@container (min-width: 1234px) {
    .size\:sm\:bg-indigo-500 {
        background-color: rgba(...);
    }
}

/* On demand size */
@container (min-width: 1400px) {
    .size\:\[1400px\]\:bg-black {
        background-color: rgba(...);
    }
}
```

*Note*: The syntax for the utilities here is not set yet, nor is providing the feature as a variant. And as far as I can tell, it will be difficult to make the above syntax work anyway.

#### Hacking away

Generating rules for the defined sizes is trivial:

```js
addVariant('containerQueries', ({ modifySelectors, separator, container }) => {
    const sizes = { sm: '123px' };

    Object.entries(sizes).forEach(([name, size]) => {
        const containerRule = postcss.atRule({ name: 'container', params: `(min-width: ${size})` });

        containerRule.append(container.nodes);
        container.append(containerRule);

        containerRule.walkRules(rule => {
            rule.selector = `.${e(`size${separator}${name}${separator}${rule.selector.slice(1)}`)}`;
        });
    });
});
```

But for the on demand sizes I'm really unsure of the possibilities the plugin system offers.

*Note*: The goal here is not to get help in making this plugin but in understanding de underlying JIT options/features when creating a plugin.
