### DISCUSSION TITLE
Multiple variants in one

### DISCUSSION THREAD

**Discussion by tkaemp** [tailwindlabs/tailwindcss#4568] [Ideas]
Assume the following CSS:
```css
a:hover > *:focus {
    color: theme(text.red.500);
}
```
Currently (to my knowledge) it is not possible to do this with native Tailwind. I would assume:
```html
<a class="hover:children:focus:text-red-500"><button>My element</button></a>
```

Also, the `children` variant does exist, however, the only place the Tailwind documentation talks about said variant is here: https://tailwindcss.com/docs/configuring-variants#default
