### DISCUSSION TITLE
[Feature Request] Add Transition Display

### DISCUSSION THREAD

**Discussion by pdevito3** [tailwindlabs/tailwindcss#4619] [Ideas]
would be great if we had an option to [transition display](https://stackoverflow.com/questions/3331353/transitions-on-the-css-display-property) like so:

```css
div {
  border: 1px solid #eee;
}
div > ul {
  visibility: hidden;
  opacity: 0;
  transition: visibility 0s, opacity 0.5s linear;
}
div:hover > ul {
  visibility: visible;
  opacity: 1;
}
```
