### DISCUSSION TITLE
Alt text for content of before and after pseudo-elements

### DISCUSSION THREAD

**Discussion by MichaelAllenWarner** [tailwindlabs/tailwindcss#4635] [Ideas]
The `content` property supports [alternative text](https://drafts.csswg.org/css-content-3/#alt) for accessibility, like these examples from the link:

```css
.new::before {
 content: url(./img/star.png) / "New!";
}
```

```css
.expandable::before {
 content: "\25BA" / "";
}
```

The alt text that screen-readers announce is what's after the slash; what's before the slash appears on the page visually. This is especially useful when you don't want the screen-reader to announce anything, as in the second example above (i.e., when the pseudo-element should be purely decorative).

It would be nice to have control over the alt-text in Tailwind (without having to make a custom `content-` class for each use-case). Perhaps it's already technically possible with the `content` utility? Would look like:

```html
<div class="before:content-[url(./img/star.png)/'New!']"></div>
```

Haven't tried it, but even if that works, it wouldn't suffice because browsers that don't yet support this (Firefox, Safari) need a fallback:

```css
{
 content: url(./img/star.png); /* necessary fallback */
 content: url(./img/star.png) / "New!";
}
```

If this could be accomplished with the fallback, something like a dedicated `alt` utility might be better:

```html
<div class="before:content-[url(./img/star.png)] before:alt-['New!']"></div>
```
