### DISCUSSION TITLE
Grouping styles with @screen

### DISCUSSION THREAD

**Discussion by JeromeDeLeon** [tailwindlabs/tailwindcss#4640] [Help]
Right now, using media query or `@screen` with `@apply` would create individual style rather than grouping them with the specified class name, is there a plan for it or this kind of thing is not possible?

```css
@screen lg {
  .sidebar {
    @apply bg-white w-60;
  }
}
```

would result in 

```css
@media (min-width: 1024px) {
  .sidebar {
    background: white;
  }
}

@media (min-width: 1024px) {
  .sidebar {
    width: 15rem;
  }
}
```

instead of 
```css
@media (min-width: 1024px) {
  .sidebar {
    background: white;
    width: 15rem;
  }
}
```
