### DISCUSSION TITLE
How Can I Hide Scroll Bar On Overflow- Auto

### DISCUSSION THREAD

**Discussion by insidecampus** [tailwindlabs/tailwindcss#4741] [Help]
I would like to add the Scroll bar on my overflow

**Comment by VicGUTT** [comment]
Hey !

I'm not sure I understand your question correctly. Are you trying to hide or show the scrollbar on an overflowing content ?
The title and description are asking for opposite things.

Does [this demo](https://play.tailwindcss.com/DZHeespKHJ) illustrates where you are at now or how you'd like it to be ?
If no, could you create a demo of what you have done so far ?

Thanks :)

**Reply by insidecampus** [reply]
I'm trying to hide the scrollbar on an overflowing content

**Reply by VicGUTT** [reply]
Well in that case you'll have to do some manual work as Tailwind does not support scrollbar customizations out of the box.

#### Before we start

But before we dive into the solutions, please take into consideration the following points:
- Hiding or styling the scrollbar to have a small clickable/touchable surface area might not be a good idea in terms of user experience or for accessibility
- We'll need to make use of non standard _(vendor-prefixes)_ or experimental CSS properties
- The implementation is not a guaranty things will work across browsers

#### Solutions

##### Webkit based browser

Webkit based browsers like Safari, Chrome _(and browsers based on Chromium for that matter)_ allow for extensive scrollbar customization through the use of the `::-webkit-scrollbar-*` property.

In our case, what we'll need to do is set a display of none to the scrollbar:

```css
/* Hide all scrollbars */
::-webkit-scrollbar {
    display: none;
}

/* Target the scrollbar of a particular element */
.some-class::-webkit-scrollbar {
    display: none;
}
```


##### Non Webkit based browser

For non Webkit based browsers like Firefox, we can hope that they have implemented the standard _(but experimental)_ way of customizing the scrollbar _(Firefox does for the most part)_.

In our case, what we'll need to do is set the scrollbar's width to none:

```css
/* Hide all scrollbars */
* {
    scrollbar-width: none;
}

/* Target the scrollbar of a particular element */
.some-class {
    scrollbar-width: none;
}
```


#### Back to Tailwind

Here's how you could customize Tailwind to make use of the solutions outilined above:

```css
@layer utilities {
    .scrollbar-hidden {
        scrollbar-width: none;
    }
    .scrollbar-hidden::-webkit-scrollbar {
        display: none;
    }
}
```

I've modified the [demo](https://play.tailwindcss.com/HOvkSDOknY?file=css) to showcase those utilities.


#### Resources

- [Webkit Styling Scrollbars](https://webkit.org/blog/363/styling-scrollbars/)
- [Custom Scrollbars in WebKit](https://css-tricks.com/custom-scrollbars-in-webkit/)
- [The Current State of Styling Scrollbars](https://css-tricks.com/the-current-state-of-styling-scrollbars/)
- [Scrollbar properties](https://css-tricks.com/almanac/properties/s/scrollbar/)
- [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars)
