### DISCUSSION TITLE
Error when build Next.js aplication

### DISCUSSION THREAD

**Discussion by DaviLhlapak** [tailwindlabs/tailwindcss#4798] [Help] [answered]
![image](https://user-images.githubusercontent.com/50346240/123265088-0e69cc00-d4d1-11eb-8eaf-c8a767d3e01f.png)

I get this error when I try to build my application in nextjs. Has anyone had this problem? it happened right after I switched tailwind from 2.1.4 to 2.2.4.

The versions I'm using are: 
"next": "^11.0.1"
"postcss": "^8.3.5"
"tailwindcss": "2.2.4"

**Comment by darrylmorley** [comment]
Have you tried disabling JIT?

**Reply by DaviLhlapak** [reply]
If I disable JIT mode I will need to extend all variations again 😬 and I don't know if that's the problem...

**Comment by deadcoder0904** [comment]
Post relevant code. Looks like your CSS has issues in `globals.css` :)

**Reply by DaviLhlapak** [reply]
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components{
    .button{
        @apply w-full h-10 flex items-center justify-center text-sm select-none p-2 cursor-pointer rounded transition-colors duration-300  filter disabled:grayscale disabled:cursor-not-allowed
    }

    .input{
        @apply w-full h-10 border border-gray-dark rounded px-4 py-2 text-sm
    }

    .heading-1{
        @apply text-3xl
    }

    .heading-2{
        @apply text-xl
    }

    .heading-3{
        @apply text-base
    }

    .paragraph-1{
        @apply text-base
    }

    .paragraph-2{
        @apply text-sm
    }

    .tooltip{
        width: 0;
        height: 0;
        border-left: 8px solid transparent;
        border-right: 8px solid transparent;
        border-top: 8px solid #333;
    }
}
```

This is my globals.css
