### DISCUSSION TITLE
Combine `:after` for multiple classes

### DISCUSSION THREAD

**Discussion by deadcoder0904** [tailwindlabs/tailwindcss#4846] [Ideas]
I am trying to recreate the top `hr` lines on https://www.framer.com/blog/posts/building-navigation-components/

It's this component which you can search on DOM:

```css
.Navigation_subnavigation__3imaJ:after {
    position: absolute;
    z-index: var(--system-depth-higher);
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    -webkit-box-shadow: inset 0 1px var(--system-color-navigationBorder);
    box-shadow: inset 0 1px var(--system-color-navigationBorder);
    content: "";
    pointer-events: none;
}
```

Now I need to write `after:absolute after:top-0 after:left-0` & so on for ever single property & it gets a bit repititive. Is there any way to write multiple `after`'s like `after:[absolute top-0 left-0]` so I don't have to write again & again?
