### DISCUSSION TITLE
First/last baseline utilities

### DISCUSSION THREAD

**Discussion by smhmd** [tailwindlabs/tailwindcss#4855] [Ideas]
Can we have `items-first-baseline` and `items-last-baseline`? Useful in being able to align baseline with the last line.

Can I use: https://caniuse.com/mdn-css_properties_align-items_flex_context_first_last_baseline
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#syntax

```css
.items-first-baseline {
  align-items: first baseline;
}
.items-last-baseline {
  align-items: last baseline;
}
```
