### DISCUSSION TITLE
Inline opacity doesn't use css variables

### DISCUSSION THREAD

**Discussion by eliottrobson** [tailwindlabs/tailwindcss#4891] [Ideas]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.3.5

### What version of Node.js are you using?

15.5.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/eliottrobson/tailwind-repro-inline-opacity

### Describe your issue

When using the inline css operator (JIT, `/`), the opacity is hard coded. It would be better to use css variables.

For example with the following two divs

```html
<div class="bg-red-500 bg-opacity-50 hover:bg-opacity-80"></div>

<div class="bg-blue-500/50 hover:bg-opacity-80"></div>
``` 

The following css is output

```css
.bg-red-500 {
  --tw-bg-opacity: 1;
  background-color: rgba(239, 68, 68, var(--tw-bg-opacity))
}

.bg-blue-500\/50 {
  background-color: rgba(59, 130, 246, 0.5)
}

.bg-opacity-50 {
  --tw-bg-opacity: 0.5
}

.hover\:bg-opacity-80:hover {
  --tw-bg-opacity: 0.8
}
```

It would be better if the `.bg-blue-500\/50` class was instead:

```css
.bg-blue-500\/50 {
  --tw-bg-opacity: 0.5;
  background-color: rgba(59, 130, 246, var(--tw-bg-opacity))
}
```

This would enable opacity modifiers to work.
