### DISCUSSION TITLE
I don't understand why my local fonts are not used

### DISCUSSION THREAD

**Discussion by alicerocheman** [tailwindlabs/tailwindcss#4905] [Help]
Hello,

I'm trying to use Open Sans locally, and I can't get it to work.

I'm using Tailwind in a Next js app.

Here's what I got:

tailwind.css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  @font-face {
    font-family: 'Open Sans';
    font-weight: 700;
    font-style: normal;
    src: url(styles/fonts/Open_Sans/OpenSans-Bold.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 700;
    font-style: italic;
    src: url(styles/fonts/Open_Sans/OpenSans-BoldItalic.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 800;
    font-style: normal;
    src: url(styles/fonts/Open_Sans/OpenSans-ExtraBold.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 800;
    font-style: italic;
    src: url(styles/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 400;
    font-style: italic;
    src: url(styles/fonts/Open_Sans/OpenSans-Italic.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 300;
    font-style: normal;
    src: url(styles/fonts/Open_Sans/OpenSans-Light.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 300;
    font-style: italic;
    src: url(styles/fonts/Open_Sans/OpenSans-LightItalic.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 400;
    font-style: normal;
    src: url(styles/fonts/Open_Sans/OpenSans-Regular.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 600;
    font-style: normal;
    src: url(styles/fonts/Open_Sans/OpenSans-SemiBold.ttf) format('ttf');
  }

  @font-face {
    font-family: 'Open Sans';
    font-weight: 600;
    font-style: italic;
    src: url(styles/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf) format('ttf');
  }
}
```
I tried `font-family: 'Open Sans';` and `font-family: Open Sans;` with no success.

If I remove the font files I get an error, so I'm guessing they're loaded properly.

and my tailwind.config.js:
```js
module.exports = {
  mode: 'jit',
  presets: [require('tailwindcss/defaultConfig')],
  purge: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Open Sans"', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [safePaddingPlugin()],
};
```

When I inspect my various elements, it shows the right font-family
<img width="391" alt="Screenshot 2021-07-06 at 15 24 15" src="https://user-images.githubusercontent.com/21168856/124607555-40cede00-de6e-11eb-9886-eb5864c07311.png">

But when I use a font inspector, I only get system fonts
```
Arial
This is a system font

Helvetica Neue
This is a system font

Palatino
This is a system font

Serif
This is a system font
```

Any help would be greatly appreciated, as I've just spent hours on this. ^^"
