### DISCUSSION TITLE
A way to use web safe fonts with Tailwind JIT - eg: font-[Verdana]

### DISCUSSION THREAD

**Discussion by andyjamesn** [tailwindlabs/tailwindcss#5011] [Ideas]
Maybe there is already a way to do this but I have not seen any mention of it nor could I get it to work

`font-[Verdana]`

would output

``` CSS
.font-verdana {
    font-family:  Verdana, sans-serif;
}
```

I guess something similar could be applied to custom fonts but the user would have to ensure it added to their page
