### DISCUSSION TITLE
An idea against overly verbose lists of class names

### DISCUSSION THREAD

**Discussion by marcelhageman** [tailwindlabs/tailwindcss#5044] [Ideas]
Hello!

I've been looking at the benefits of Tailwind CSS for my projects and I do appreciate the different approaches, and I can definitely see the benefits. The only problem I have is that it makes my HTML look overly verbose. I'd label the listing of 10 to 20 class names "abhorrent" even, and I was wondering if there could be developments towards making this more elegant without giving up any of the features and benefits.

## Take this example: the code in will be the code that comes out:

```HTML
<div class="grid grid-cols-1 sm:grid-cols-2 sm:px-8 sm:py-12 sm:gap-x-8 md:py-16">
      <h2 class="text-xl font-semibold text-white sm:text-2xl sm:leading-7 sm:text-black md:text-3xl">Beach House in Collingwood</h2>
```

## What if we turn it into this, but end up getting the **exact same output as above**?

(I repeat, the code inside your browser's dev-tools will show exactly what my first original example shows. That way we can keep the CSS package size as small as possible.)

```HTML
<div class="user_tile">
  <h2>Beach House in Collingwood</h2>
```

## And in your SCSS-file (or `styled-component`):

```SCSS
.user_tile {
  @tailwind grid grid-cols-1;
  @tailwind:sm :grid-cols-2 :px-8 :py-12 :gap-x-8;
  @tailwind:md :py-16;

  outline: 1px dotted red;
  
  h2 {
    @tailwind text-xl font-semibold text-white;
    @tailwind:sm :text-2xl :leading-7 :text-black;
    @tailwind:md :text-3xl;

    outline: 1px dotted blue;
  }
}
```

(Note: Once applied to, say, a React project, your browser's dev-tools will simply show a list of class names in the rendered version of your code. Nothing will change except a slightly different and more elegant way of developing.)

## The Webpack-plugin for Tailwind CSS would see the following:

1. Our HTML element has one or multiple class names;
2. Inside the class definition we see `@tailwind` classes being imported (like `@extend` would be for regular SCSS);
3. We get the following class names to be added to our HTML element: `grid grid-cols-1 sm:grid-cols-2 sm:px-8 sm:py-12 sm:gap-x-8 md:py-16`;
4. And we have just one line (the `outline`) of custom CSS, which will just live inside the `.user_tile` class, which is added for the list of Tailwind-classes referenced above, in #3.

## The benefits:

1. The HTML templates can become much less verbose (but people are still able to use inline class names like before, no worries);
2. It is much easier to add your own custom CSS to your elements because the custom class name already exists;
3. `@tailwind:sm` and other such prefixes will group responsive class names together which makes it easier to scan and understand;
4. Nested elements, as SASS does, allow you to only have to include (in your development-code) one class name per component instead of having to provide a class attribute for every element inside;
5. It will convince more people to use Tailwind because their biggest issue with the way Tailwind is probably the long lists of class names that make us all think of what basically amounts to inline CSS.

Would love to hear opinions and feedback on this!

Cheers!
