### DISCUSSION TITLE
Scope base layer

### DISCUSSION THREAD

**Discussion by kamnakis** [tailwindlabs/tailwindcss#5127] [Help]
Hello there.
I am creating a web component and I use tailwind for the styles.

What I need is to scope everything that is generated by tailwind so that it won't mess up the end user styles. 

I found the `important: "#someid"` option and it works great for the utilities.
What I need now is to scope all the base styles to the root component just like the utilities. 

For example:
Instead of 
```css
button {
  background: transparent
} 
```
I want 
```css
#someid button {
  background: transparent
} 
```

Is this possible with any configuration of tailwind or postcss?
