### DISCUSSION TITLE
Colored box shadows

### DISCUSSION THREAD

**Discussion by PositiveUser** [tailwindlabs/tailwindcss#5347] [Ideas]
Please add colored box shadow utilities.
Thank you very much, tailwind CSS!

**Comment by simonswiss** [comment]
I have just finished a _somewhat_ related YouTube video - it will be published sometime next week.

It does not technically use box-shadows, but is likely to achieve what you're trying to do 👍

**Reply by PositiveUser** [reply]
**Examples**
`shadow-green-500`, `shadow-pink-400`
Thank you very much

**Comment by Ashcraft316** [comment]
Thanks for the update and quick reply. I'll be sure to keep an eye on this thread.

[Dunkinrunsonyou](https://www.dunkinrunsonyou.net/)

**Comment by PositiveUser** [comment]
Obviously, I have used loops to make these CSS rules and this works. I hope you get some ideas. Thank you very much.

```css
.shadow-gray-50 {
    --shadow-clr: #f9fafb;
}
.shadow-gray-100 {
    --shadow-clr: #f3f4f6;
}
.shadow-gray-200 {
    --shadow-clr: #e5e7eb;
}
.shadow-gray-300 {
    --shadow-clr: #d1d5db;
}
.shadow-gray-400 {
    --shadow-clr: #9ca3af;
}
.shadow-gray-500 {
    --shadow-clr: #6b7280;
}
.shadow-gray-600 {
    --shadow-clr: #4b5563;
}
.shadow-gray-700 {
    --shadow-clr: #374151;
}.shadow-gray-800 {
    --shadow-clr: #1f2937;
}
.shadow-gray-900 {
    --shadow-clr: #111827;
}
.shadow-red-50 {
    --shadow-clr: #fef2f2;
}
.shadow-red-100 {
    --shadow-clr: #fee2e2;
}
.shadow-red-200 {
    --shadow-clr: #fecaca;
}
.shadow-red-300 {
    --shadow-clr: #fca5a5;
}
.shadow-red-400 {
    --shadow-clr: #f87171;
}
.shadow-red-500 {
    --shadow-clr: #ef4444;
}
.shadow-red-600 {
    --shadow-clr: #dc2626;
}
.shadow-red-700 {
    --shadow-clr: #b91c1c;
}
.shadow-red-800 {
    --shadow-clr: #991b1b;
}
.shadow-red-900 {
    --shadow-clr: #7f1d1d;
}
.shadow-yellow-50 {
    --shadow-clr: #fffbeb;
}
.shadow-yellow-100 {
    --shadow-clr: #fef3c7;
}
.shadow-yellow-200 {
    --shadow-clr: #fde68a;
}
.shadow-yellow-300 {
    --shadow-clr: #fcd34d;
}
.shadow-yellow-400 {
    --shadow-clr: #fbbf24;
}
.shadow-yellow-500 {
    --shadow-clr: #f59e0b;
}
.shadow-yellow-600 {
    --shadow-clr: #d97706;
}
.shadow-yellow-700 {
    --shadow-clr: #b45309;
}
.shadow-yellow-800 {
    --shadow-clr: #92400e;
}
.shadow-yellow-900 {
    --shadow-clr: #78350f;
}
.shadow-green-50 {
    --shadow-clr: #ecfdf5;
}
.shadow-green-100 {
    --shadow-clr: #d1fae5;
}
.shadow-green-200 {
    --shadow-clr: #a7f3d0;
}
.shadow-green-300 {
    --shadow-clr: #6ee7b7;
}
.shadow-green-400 {
    --shadow-clr: #34d399;
}
.shadow-green-500 {
    --shadow-clr: #10b981;
}
.shadow-green-600 {
    --shadow-clr: #059669;
}
.shadow-green-700 {
    --shadow-clr: #047857;
}
.shadow-green-800 {
    --shadow-clr: #065f46;
}
.shadow-green-900 {
    --shadow-clr: #064e3b;
}
.shadow-blue-50 {
    --shadow-clr: #eff6ff;
}
.shadow-blue-100 {
    --shadow-clr: #dbeafe;
}
.shadow-blue-200 {
    --shadow-clr: #bfdbfe;
}
.shadow-blue-300 {
    --shadow-clr: #93c5fd;
}
.shadow-blue-400 {
    --shadow-clr: #60a5fa;
}
.shadow-blue-500 {
    --shadow-clr: #3b82f6;
}
.shadow-blue-600 {
    --shadow-clr: #2563eb;
}
.shadow-blue-700 {
    --shadow-clr: #1d4ed8;
}
.shadow-blue-800 {
    --shadow-clr: #1e40af;
}
.shadow-blue-900 {
    --shadow-clr: #1e3a8a;
}
.shadow-indigo-50 {
    --shadow-clr: #eef2ff;
}
.shadow-indigo-100 {
    --shadow-clr: #e0e7ff;
}
.shadow-indigo-200 {
    --shadow-clr: #c7d2fe;
}
.shadow-indigo-300 {
    --shadow-clr: #a5b4fc;
}
.shadow-indigo-400 {
    --shadow-clr: #818cf8;
}
.shadow-indigo-500 {
    --shadow-clr: #6366f1;
}
.shadow-indigo-600 {
    --shadow-clr: #4f46e5;
}
.shadow-indigo-700 {
    --shadow-clr: #4338ca;
}
.shadow-indigo-800 {
    --shadow-clr: #3730a3;
}
.shadow-indigo-900 {
    --shadow-clr: #312e81;
}
.shadow-purple-50 {
    --shadow-clr: #f5f3ff;
}
.shadow-purple-100 {
    --shadow-clr: #ede9fe;
}
.shadow-purple-200 {
    --shadow-clr: #ddd6fe;
}
.shadow-purple-300 {
    --shadow-clr: #c4b5fd;
}
.shadow-purple-400 {
    --shadow-clr: #a78bfa;
}
.shadow-purple-500 {
    --shadow-clr: #8b5cf6;
}
.shadow-purple-600 {
    --shadow-clr: #7c3aed;
}
.shadow-purple-700 {
    --shadow-clr: #6d28d9;
}
.shadow-purple-800 {
    --shadow-clr: #5b21b6;
}
.shadow-purple-900 {
    --shadow-clr: #4c1d95;
}
.shadow-pink-50 {
    --shadow-clr: #fdf2f8;
}
.shadow-pink-100 {
    --shadow-clr: #fce7f3;
}
.shadow-pink-200 {
    --shadow-clr: #fbcfe8;
}
.shadow-pink-300 {
    --shadow-clr: #f9a8d4;
}
.shadow-pink-400 {
    --shadow-clr: #f472b6;
}
.shadow-pink-500 {
    --shadow-clr: #ec4899;
}
.shadow-pink-600 {
    --shadow-clr: #db2777;
}
.shadow-pink-700 {
    --shadow-clr: #be185d;
}
.shadow-pink-800 {
    --shadow-clr: #9d174d;
}
.shadow-pink-900 {
    --shadow-clr: #831843;
}
```
