### DISCUSSION TITLE
Support "after:content" with using "@apply"

### DISCUSSION THREAD

**Discussion by rowild** [tailwindlabs/tailwindcss#5492] [Ideas]
If I am not totally mistaken, it looks as if it were not possible to use `content: ''` with pseudo-classes, when working with Tailwind's `@apply`:

```css
div:before {
  @apply absolute inset-0;
  content: ``;       /* <-- no way to use @apply here */
}
```

Would be great, if this could find its way into Tailwind!
