### DISCUSSION TITLE
Issue with hover background color with JIT

### DISCUSSION THREAD

**Discussion by marco3211** [tailwindlabs/tailwindcss#5529] [Help]
Not sure if anyone is getting that same issue. When trying to apply `hover:bg-black` to an element, the compiled CSS returns me 

```css
.hover\:bg-black:hover {
	background-color: undefined;
}

.hover\:bg-black:hover:bg-black:hover {
	background-color: rgba(0, 0, 0, 1);
}
```

It's really strange. Why is it returning `undefined`? 

EDIT: Adding more info, postcss returns me this 

```css
<css input>: variable --tw-border-opacity is undefined and used without a fallback
<css input>: variable --tw-border-opacity is undefined and used without a fallback
<css input>: variable --tw-bg-opacity is undefined and used without a fallback
<css input>: variable --tw-text-opacity is undefined and used without a fallback
```

I think this is why the `undefined` is returned.
