### DISCUSSION TITLE
Support for changing the color of text selection?

### DISCUSSION THREAD

**Discussion by brandonpaldom** [tailwindlabs/tailwindcss#5534] [Help] [answered]
It would be great to consider adding some CSS classes to customize the text color selection like the following example extracted from W3Schools documentation.

```CSS
::-moz-selection { /* Code for Firefox */
  color: red;
  background: yellow;
}

::selection {
  color: red;
  background: yellow;
}
```
