### DISCUSSION TITLE
How to use CSS Grid auto-fill and auto-fit with Tailwind CSS?

### DISCUSSION THREAD

**Discussion by martinszeltins** [tailwindlabs/tailwindcss#5541] [Help] [answered]
How would I do this using Tailwind if I wanted to write CSS like this?

For example, using `auto-fill`:

`grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));`

or using `auto-fit`:

`grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));`

**Comment by simonswiss** [comment, marked as answer]
Hey @martinszeltins 👋

Two ways you can do this:

## 1. Extend the `gridTemplateColumns` object in your Tailwind config

```js
module.exports = {
  theme: {
    extend: {
      gridTemplateColumns: {
        'auto-fill-100': 'repeat(auto-fill, minmax(100px, 1fr))',
        'auto-fit-100': 'repeat(auto-fit, minmax(100px, 1fr))',
      },
    },
  },
}
```

This will create a `grid-cols-auto-fill-100` and `grid-cols-auto-fit-100` (but feel free to name them differently in the config!) 👍

---

## 2. Inline the `grid-template-column` definition in a JIT arbitrary value

The `grid-cols-*` utilities accept arbitrary values when `JIT` mode it turned on. That means you can do things like this:

```grid-cols-[repeat(auto-fill,minmax(100px,1fr))]```

Notice the absence of **spaces** in that class – you cannot have spaces in a class! Fear not, the spaces will be added back in the generated CSS from that class!

Here's a Tailwind Play showing both implementations (check both the config file and the HTML):

https://play.tailwindcss.com/gUosL2mfZ1?file=config

![image](https://user-images.githubusercontent.com/485747/134120288-59ae4944-103c-42e1-bf91-7e970e348455.png)

Hope it helps!

https://user-images.githubusercontent.com/485747/134120310-11155365-fb6f-4bdc-b8f4-cfbfeb1b079e.mov

**Reply by martinszeltins** [reply]
@simonswiss Ooh, that's perfect! Thank you man so much! I love the flexibility and customizations of Tailwind!

**Reply by simonswiss** [reply]
No problem – it was fun putting this little demo together, and the flexibility is indeed pretty cool 🙌

**Reply by thompsonmanda08** [reply]
This right here just saved me a lot of work. Appreciation all the way!

**Reply by mohit2404** [reply]
100px is a static value so if we need to specify some other value then 100px is it possible if yes then can we use arbitrary value like other properties in tailwind ex. auto-fit-[12rem] or auto-fill-[12rem]?

**Reply by Janaka-Steph** [reply]
In Tailwind.config.js
```
  plugins: [
    plugin(function ({ matchUtilities, theme }) {
      matchUtilities(
        {
          'auto-fill': (value) => ({
            gridTemplateColumns: `repeat(auto-fill, minmax(min(${value}, 100%), 1fr))`,
          }),
          'auto-fit': (value) => ({
            gridTemplateColumns: `repeat(auto-fit, minmax(min(${value}, 100%), 1fr))`,
          }),
        },
        {
          values: theme('width', {}),
        }
      )
    })]
```

**Reply by mohit2404** [reply]
@Janaka-Steph thank you for the solution

**Reply by thompsonmanda08** [reply]
@Janaka-Steph, sorry for the bother, Just at the bottom, do you mind explaining the  object with the "value" key?

**Reply by MarcosVini9999** [reply]
utils: for typescript you need to import plugin from "tailwindcss/plugin";

😀

**Reply by mohit2404** [reply]
@thompsonmanda08 the second object is the options objects, here we are setting the values option to width which is defined in tailwindcss config. theme(width, {}) is use to get the values od width defind in tailwind config, if no values are found then it defaults to an empty object

**Comment by mayurwankhade96** [comment]
just use grid-cols-[repeat(auto-fit,_minmax(400px,_1fr))] this exact thing, adjust according to your needs

**Comment by Nusab19** [comment]
As @mayurwankhade96 said, just use
```
grid-cols-[repeat(auto-fit,minmax(13rem,1fr))]
```

And change the `13rem` to your need. 

But keep in mind that, by using this, you can't use `items-center` or `justify-center` to center the div anymore.

You need to use `place-items-center` to center the div instead.

I've never used `place-items-center` before, but somehow it worked.\
And ***"Don't touch it if it works!"***

**Comment by kpietraszko** [comment]
Plugins in tailwind.config.ts seem to be deprecated, so I figured out the proper way to add this when using Tailwind V4.0. 
Add the following to your index.css:
```css
@utility auto-fill-*{
  grid-template-columns: repeat(auto-fill, minmax(min(--value([*]), 100%), 1fr));
  grid-template-columns: repeat(auto-fill, minmax(min(--value(--text-*), 100%), 1fr));
  grid-template-columns: repeat(auto-fill, minmax(min(var(--spacing)* --value(integer), 100%), 1fr));
}

@utility auto-fit-*{
  grid-template-columns: repeat(auto-fit, minmax(min(--value([*]), 100%), 1fr));
  grid-template-columns: repeat(auto-fit, minmax(min(--value(--text-*), 100%), 1fr));
  grid-template-columns: repeat(auto-fit, minmax(min(var(--spacing)* --value(integer), 100%), 1fr));
}
```
This supports all 3 forms: integers (so `auto-fill-4` will give you `1rem`), tailwind's text sizes (so `auto-fill-9xl` will give you `8rem`), and arbitrary values (for example `auto-fill-[11rem]`).
And it all gets added to intellisense 🤩
