### DISCUSSION TITLE
Enable getting unit-less values from `theme()` function

### DISCUSSION THREAD

**Discussion by dcastil** [tailwindlabs/tailwindcss#5783] [Ideas]
# Problem

I need to use values from the theme in a [`calc()`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc()) CSS function. In a usual scenario the [`theme()`](https://tailwindcss.com/docs/functions-and-directives#theme) function is perfectly suited for this.

```css
.my-class {
    some-prop: calc(100vw - theme('screens.sm'))
}
```

But in my case I need to use the theme values in a denominator.

```css
.my-class {
    some-prop: calc(100vw / theme('screens.sm'))
    /*                      ------------------- Error: Must not have unit */
}
```

Denominators can't have units in them, [only numbers](https://developer.mozilla.org/en-US/docs/Web/CSS/calc()#syntax). Otherwise the browser will ignore the property.

# Problem in practice

I need to set up a website with a linear growing rem size according to the design spec:
- 1rem = 18px for up to 640px browser width
- 1rem = linearly scale from 18px to 22px for 641-1280px browser width
- 1rem = 22px for 1281px and up browser width

The CSS to achieve that looks like following.

```css
:root {
    font-size: 18px;
}
@screen sm {
    :root {
        font-size: calc((100vw - theme('screens.sm')) / (theme('screens.xl') - theme('screens.sm')) * (22 - 18) + 18px);
        /*                            Must be unit-less ------------------------------------------- */
    }
}
@screen xl {
    :root {
        font-size: 22px;
    }
}
```

# Current workaround

I hardcode the values into the CSS. Works fine, but of course it's easy to forget to update these values in case the theme changes.

```css
@screen sm {
    :root {
        /* font-size: 20px; */
        font-size: calc((100vw - theme('screens.sm')) / (1280 - 640) * (22 - 18) + 18px);
        /*                       Hardcoded theme values ------------ */
    }
}
```

# Possible solution

I'm not too familiar with PostCSS functions, so I'm just guessing here.

Would be nice to tell the `theme()` function via a second parameter that I want to strip the unit out, e.g. with `theme('screens.sm', { noUnit: true })`. Otherwise an additional `themeUnitless()` CSS function could do it as well.
