### DISCUSSION TITLE
span captitalize does not work

### DISCUSSION THREAD

**Discussion by dillingham** [tailwindlabs/tailwindcss#5834] [Ideas]
Does not work
```html
<span class="capitalize">products</span>
```
Does work
```html
<span class="capitalize inline-block">products</span>
```

Just wondering if this could be assumed by `capitalize` behind the scenes

---

Also `inline-block` didnt autocomplete in phpstorm

**Comment by dillingham** [comment]
```css
span.capitalize {
    display: inline-block;
}
```
