### DISCUSSION TITLE
Different color in dark/light mode

### DISCUSSION THREAD

**Discussion by daishizenSensei** [tailwindlabs/tailwindcss#5921] [Help]
Hello everyone,

Do you know if it's possible to have different color in light/dark mode for a defined one?
Example :
In lightmode primary is "x"
In dark mode primary is "x darker"

Thanks

**Comment by thijssmudde** [comment]
```tsx
<div className="text-gray-400 dark:text-gray-500" />
```

**Comment by dance2die** [comment]
I'd go with @fullhdpixel's approach of using `dark` variant.  

Should you still want to go with one color name approach (e.g. `text-primary`) for both light/dark themes,  

You can declare CSS variable for the primary color (it's only for `darkMode: "class"`, define [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) as well for 'media')

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --color-primary: red;
}

@layer utilities {
  .dark {
    --color-primary: blue;
  }
}
```

then extend colors,

```js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    extend: {
      colors: {
        primary: `var(--color-primary)`,
      },
    },
  },
 ...
}

```

**Demo**: https://play.tailwindcss.com/iZ5u5zlcgm?file=config


![toggle dark with one utility](https://user-images.githubusercontent.com/8465237/139780179-12e4d889-6e15-43ea-ae38-c48eabc3cc82.gif)
