### DISCUSSION TITLE
Tailwind Responsive Chaining

### DISCUSSION THREAD

**Discussion by Aslam97** [tailwindlabs/tailwindcss#5990] [Help]
I've example like this

**Code**:

```css
.header {
   @apply xl-max-2:min-h-[60px] xl-max-2:h-auto
}
```

**Result**:
```css
@media (max-width: 1200px) {
   .header {
      height: auto;
   }
}

@media (max-width: 1200px) {
   .header {
      height: auto;
   }
}
```
from the above example generate 2 `max-width: 1200px`. can I merge it into one like this?

```css
@media (max-width: 1200px) {
   .header {
      min-height: 60px;
      height: auto;
   }
}
```

I've tried something like this

```css
.header {
   @apply xl-max-2:min-h-[60px]:h-auto
}
```

but it didn't work. basically I don't want to repeatedly type `xl-max-2`

And `xl-max-2` is extend screens

```js
screens: {
   'xl-max': { raw: '(max-width: 1280px)' },
   'xl-max-2': { raw: '(max-width: 1200px)' },
},
```

Is there any solution for this?
