### DISCUSSION TITLE
Additional SVG properties

### DISCUSSION THREAD

**Discussion by techniq** [tailwindlabs/tailwindcss#6089] [Ideas]
With the [recent](https://github.com/tailwindlabs/tailwindcss/pull/5933) addition of `fill-*` and `stroke-*` classes, it would be great if more [SVG properties](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#presentation_attributes) were added to Tailwind.

Some properties I reach for often which would be a good start (instead of having to reach for `style="..."` or adding a Svelte class). 

- [stroke-width](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width)
- [stroke-opacity](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity)
- [stroke-linejoin](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin)
- [stroke-linecap](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap)
- [stroke-dashoffset](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dashoffset)
- [stroke-dasharray](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray)
- [fill-opacity](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity)
- [fill-rule](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule)
- [text-anchor](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor)
- [alignment-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline)
- [dominant-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline)
- [paint-order](https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order)
  - Useful for adding outline / halo strokes to text
    - https://observablehq.com/@d3/radial-tree
    - https://stackoverflow.com/questions/442164/how-to-get-an-outline-effect-on-text-in-svg/26498819#26498819

Some of these will be best to primarily leverage with arbitrary values (ex. `stroke-dashoffset` / `stroke-dasharray`) although those with a defined list (ex. `stroke-linejoin` / `stroke-linecap`) should make for straight forward class names.

**Comment by felipepodesta** [comment]
+1

**Comment by gotpop** [comment]
Tailwind = Bootstrap

**Reply by nigelpasco** [reply]
> Tailwind = Bootstrap

Tailwind > Bootstrap :)

**Reply by Kathalysth** [reply]
Just started using Tailwind, and I am wondering why I didn't start sooner.

**Reply by debjotyms** [reply]
Bootstrap who?

**Comment by h0ds** [comment]
+1

**Comment by tpalecian** [comment]
+1

**Comment by eduardocque** [comment]
+1

**Comment by Pj-Thinker** [comment]
+1

**Comment by wilsonfaustino** [comment]
+1

**Comment by DarioLopes** [comment]
+1

**Comment by mreduar** [comment]
+1

**Comment by nikitastryuk** [comment]
+1

**Comment by carsonkrueger** [comment]
+1

**Comment by munezerobagira** [comment]
+1

**Comment by joevingracien** [comment]
+1

**Comment by InanisOmnia** [comment]
I would love to see this feature! +1

**Comment by icarodavi** [comment]
+1

**Comment by jimmiefriberg** [comment]
+1

**Comment by Wonkers0** [comment]
+1

**Comment by sebsobseb** [comment]
+1

**Comment by LounisBou** [comment]
+1

**Comment by bunnyxt** [comment]
+1

**Comment by Pedram-Parsian** [comment]
+1

**Comment by adamwathan** [comment]
When I need these I generally just use the SVG attributes directly, for example:

```
<svg stroke-linecap=“round”>
```

Can anyone share some real world motivating examples for needing these as classes? Are you changing these sorts of things often based on hover states or at different breakpoints?

**Reply by psirenny** [reply]
I'm using the [react-circular-progressbar](https://www.kevinqi.com/react-circular-progressbar/) library and trying to style its child elements:

```tsx
import { CircularProgressbar } from "react-circular-progressbar";

<CircularProgressBar
  className="h-4 w-4"
  classes={{
    path: "stroke-linecap-round stroke-green-600",
    text: "dominant-baseline-middle text-anchor-middle stroke-green-600",
  }}
  value={90}
/>
```

**Reply by Pedram-Parsian** [reply]
We are making custom charts using Angular and D3 for a financial dashboard; One such use-case is changing the style of the line when hovering/clicking.

Right now we're switching custom CSS classes to support changing attributes like  `stroke-dasharray`. It would be nice if we are able to use built-in tailwind classes instead.

**Reply by binaryartifex** [reply]
being able to target the dasharray and dashoffset would be nice to compliment custom keyframes in the tailwind config to animate in/out svgs....

**Reply by caseydwyer** [reply]
We use `stroke-opacity` alongside color quite a bit, especially in section backgrounds made of SVG patterns. These are (sometimes) selected from a CMS, so we want to avoid offering (an insane number of) color + opacity combinations—eg, `.stroke-green-500/10`—to avoid having to safelist and bundle all of those potential options.

**Comment by nnmax** [comment]
+1

**Comment by abuu-u** [comment]
use [Arbitrary properties](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties)

```html
<div class="[stroke-linejoin:round]">
  <!-- ... -->
</div>
```

**Comment by tri-dataxight** [comment]
+1

**Comment by IgorMilosavljevic** [comment]
+1

**Comment by Qnemes** [comment]
Bump, don't wanna mix tw classes with inline styles

**Comment by wolfspyre** [comment]
I'd love to see more examples of SVGs responding properly to tailwindcss cues .... it's been hard to find anything substantial using them that illustrates how best to get things to work.

**Comment by leo-bjorn** [comment]
+1

**Comment by adamchenwei** [comment]
can't believe tailwind still has not added this yet 😮‍💨

**Comment by devanshdsoni** [comment]
+1

**Comment by marcelotten** [comment]
+1

**Comment by Avi-Cohen-Nehemia** [comment]
+1

**Comment by by-huy** [comment]
+1

**Comment by PhillipFraThailand** [comment]
+1

**Comment by whoisaymen** [comment]
+1

**Comment by macadiz** [comment]
+1

**Comment by roberto-juniorjp** [comment]
+1

**Comment by siddhant-rl** [comment]
+1

**Comment by danilobjr** [comment]
This thread started 2021. Here we are in 2025: +1

**Comment by Shalev-Aviv** [comment]
+1

**Comment by caseyohara** [comment]
+1

**Comment by rozsazoltan** [comment]
You can continue to extend your project with your own functional utilities (in both v3 and v4). Here's a v4 example:

### `-webkit-text-stroke` custom utilities for width & color

* [**How can I use the `-webkit-text-stroke` setting similarly to the `stroke-*` utility?**](https://stackoverflow.com/a/79691173/15167500)
* https://play.tailwindcss.com/L1LLBBpyCA?file=css
* **https://caniuse.com/?search=-webkit-text-stroke** (Baseline 2017 - available Chrome, Edge, Firefox, Safari)

```css
@theme {
  --stroke-none: unset;
}

@utility text-stroke-* {
  -webkit-text-stroke-width: calc(--value(integer) * 0.5px);
  -webkit-text-stroke-width: --value(--stroke-*, [*]);

  --tw-stroke-color: --value(--color-*);
  -webkit-text-stroke-color: var(--tw-stroke-color, black);
}
```

### `stroke-width`, `stroke-color` available from v4

* https://play.tailwindcss.com/0P4u4aAL2R
* https://tailwindcss.com/docs/stroke

### `stroke-opacity`, `stroke-linejoin`, `stroke-linecap`, `stroke-dashoffset`, `stroke-dasharray` custom utilities

They are all part of Baseline 2020, so they can be safely used in Baseline 2023, which is targeted by v4.

#### `stroke-opacity`

Available by modifier:
* https://play.tailwindcss.com/DbW8Q5Q2AV

But the v3 `bg-opacity-*` can also be restored, and similarly `stroke-opacity-*` as well.
* [The bg-opacity-* utility no longer exists as of v4 - how could it still be created?](https://stackoverflow.com/a/79705012/15167500)
* https://play.tailwindcss.com/LJdF0MUwef?file=css

```css
@utility stroke-opacity-* {
  --stroke-opacity: calc(100% - --value(integer) * 1%);
}

@utility stroke-* {
  stroke: color-mix(in oklab, --value(--color-*, [*]) var(--stroke-opacity, 100%), transparent);
}
```

Or can use `stroke-opacity` CSS property:
* https://play.tailwindcss.com/DbW8Q5Q2AV

```css
@theme {
  --stroke-opacity-none: 0%;
}

@utility stroke-opacity-* {
  stroke-opacity: calc(--value(integer) * 1%);
  stroke-opacity: calc(--value(ratio, [ratio]) * 100%);
  stroke-opacity: --value(--stroke-opacity-*, [percentage]);
}
```

#### `stroke-linejoin`

* https://play.tailwindcss.com/YQnhBWD7Qy?file=css

```css
@theme {
  --stroke-join-default: 'miter';
  --stroke-join-clip: 'miter-clip';
}

@utility stroke-join-* {
  stroke-linejoin: --value('arcs', 'bevel', 'miter', 'round', --stroke-join-*);
}
```

#### `stroke-linecap`

* https://play.tailwindcss.com/w1Kd9ije3h?file=css

```css
@theme {
  --stroke-cap-default: 'butt';
}

@utility stroke-cap-* {
  stroke-linecap: --value('butt', 'round', 'square', --stroke-cap-*);
}
```

#### `stroke-dashoffset`, `stroke-dasharray`

* https://play.tailwindcss.com/HeuNx3ynEZ?file=css

```css
@theme {
  --stroke-offset-none: 0;
  --stroke-array-sos: 1 1 1 1 1 1 3 1 3 1 3 1;
}

@utility stroke-array-* {
  stroke-dasharray: --value(integer, 'none', [*], --stroke-array-*);
}

@utility stroke-offset-* {
  stroke-dashoffset: --value(integer);
  stroke-dashoffset: --value(--stroke-offset-*, [integer], [length], [percentage]);
}

@utility -stroke-offset-* {
  stroke-dashoffset: calc(-1 * --value(integer));
  stroke-dashoffset: calc(-1 * --value([integer], [length], [percentage]));
}
```

### `fill-opacity` available from v4 by modifier: `fill-sky-500/20`

* https://play.tailwindcss.com/qpd4FOh58N

But the v3 `bg-opacity-*` can also be restored, and similarly `fill-opacity-*` as well.

* [The bg-opacity-* utility no longer exists as of v4 - how could it still be created?](https://stackoverflow.com/a/79705012/15167500)
* https://play.tailwindcss.com/VQjTBVU3oA

```css
@utility fill-opacity-* {
  --fill-opacity: calc(100% - --value(integer) * 1%);
}

@utility fill-* {
  fill: color-mix(in oklab, --value(--color-*, [*]) var(--fill-opacity, 100%), transparent);
}
```

Or can use `fill-opacity` CSS property:
* https://play.tailwindcss.com/KEwzBd4BQa?file=css

```css
@theme {
  --fill-opacity-none: 0%;
}

@utility fill-opacity-* {
  fill-opacity: calc(--value(integer) * 1%);
  fill-opacity: calc(--value(ratio, [ratio]) * 100%);
  fill-opacity: --value(--stroke-opacity-*, [percentage]);
}
```

### `fill-rule`

* https://play.tailwindcss.com/G70V4xYv4c

```css
@utility fill-* {
  fill-rule: --value('evenodd', 'nonzero');
}
```
