### DISCUSSION TITLE
overflow-overlay

### DISCUSSION THREAD

**Discussion by yoobi** [tailwindlabs/tailwindcss#6212] [Ideas]
Hello, 

i was having overflow issue and I need to use the css property: `overflow: overlay` but it doesn't exist by default in tailwind, is there a reason why ?

EDIT: When checking around `overflow: overlay` seems deprecated but lot of people are still using it.

**Comment by adamwathan** [comment]
Yeah doesn't exist because it's deprecated like you discovered. You can add it yourself though if you need it 👍🏻 

```css
@layer utilities {
  .overflow-overlay {
    overflow: overlay
  }
}
```
