### DISCUSSION TITLE
Support more px values for margin

### DISCUSSION THREAD

**Discussion by ModProg** [tailwindlabs/tailwindcss#6215] [Ideas]
Currently there is also +/- 1 px for the margin classes, it would be great to have something like 1,2,4,8 like with the rem measurements.
I could imagine:
```css
.-ml-px-2{
    margin-left: -2px;
}
```
My usecase is to have it matching the border width.
