### DISCUSSION TITLE
Default values for css variables

### DISCUSSION THREAD

**Discussion by dorianmariecom** [tailwindlabs/tailwindcss#6452] [Ideas]
When using `postcss-css-variables` I get those warnings:

```
⚠  variable --tw-shadow-color is undefined and used without a fallback [postcss-css-variables]
⚠  variable --tw-shadow-color is undefined and used without a fallback [postcss-css-variables]
⚠  variable --tw-shadow-color is undefined and used without a fallback [postcss-css-variables]
⚠  variable --tw-shadow-color is undefined and used without a fallback [postcss-css-variables]
⚠  variable --tw-border-opacity is undefined and used without a fallback [postcss-css-variables]
⚠  variable --tw-bg-opacity is undefined and used without a fallback [postcss-css-variables]
⚠  variable --tw-border-opacity is undefined and used without a fallback [postcss-css-variables]
⚠  variable --tw-bg-opacity is undefined and used without a fallback [postcss-css-variables]
```

Maybe there should be default values, or fallbacks for those variables

**Comment by dorianmariecom** [comment]
Here is what I ended up with:

```css
:root {
  --tw-bg-opacity: 1;
  --tw-shadow-colored: 0 0 #0000;
  @apply opacity-100 shadow-black border-black;
}
```
