### DISCUSSION TITLE
Add a way to define `--tw-shadow-colored`

### DISCUSSION THREAD

**Discussion by dorianmariecom** [tailwindlabs/tailwindcss#6453] [Ideas]
I'm not sure where it's used but there is no way to set a default.

I just did in my css:

```
--tw-shadow-colored: inherit
```

but I feel like this relies on internals

**Comment by dorianmariecom** [comment]
Here is what I ended up with:

```css
:root {
  --tw-bg-opacity: 1;
  --tw-shadow-colored: 0 0 #0000;
  @apply opacity-100 shadow-black border-black;
}
```
