### DISCUSSION TITLE
How to add colors transparent in the theme() function

### DISCUSSION THREAD

**Discussion by ghost** [tailwindlabs/tailwindcss#6620] [Help]
Conventional
```css
.btn-blue {
  background-color: theme('colors.blue.500');
}
```
Try to add transparent , none of the following writing takes effect
```css
.btn-blue {
  background-color: theme('colors.blue.500.50');
  background-color: theme('colors.blue.500-50');
  background-color: theme('colors.blue.500/50');
}
```
