### DISCUSSION TITLE
How can i use Arbitrary properties with webkit

### DISCUSSION THREAD

**Discussion by wthks** [tailwindlabs/tailwindcss#6712] [Help]
Im trying to use this as arbitrary propertie
```css
::-webkit-scrollbar {
  width: 10px;
}
 ::-webkit-scrollbar-thumb {
  background: white; 
  border-radius: 5px;
}
```

scrollbar feature would be btw nice too
