### DISCUSSION TITLE
Safelisting variants not working for prefixed negative values

### DISCUSSION THREAD

**Discussion by leeshadle** [tailwindlabs/tailwindcss#6777] [Help]
When safelisting, if a prefixed utility class is a negative value the variant selectors don't get added 🤔:

```js
prefix: 'tw-',
safelist: [
{
	pattern: /-skew-x-2/,
	variants: ['hover','focus','md','sm','md:hover','sm:hover','md:focus','sm:focus'],
},
```

```css
.tw-skew-x-2 {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

.hover\:tw-skew-x-2:hover {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

/* below should be: .hover\:tw--skew-x-2:hover */
.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

.focus\:tw-skew-x-2:focus {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

/* below should be: .focus\:tw--skew-x-2:focus */
.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

@media (max-width: 1023px) {
	.md\:tw-skew-x-2 {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}

        /* below should be: .md\:tw--skew-x-2 */
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}

	.md\:hover\:tw-skew-x-2:hover {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}

        /* below should be: .md\:hover\:tw--skew-x-2:hover */
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}

	.md\:focus\:tw-skew-x-2:focus {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}

        /* below should be: .md\:focus\:tw--skew-x-2:focus */
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
}

@media (max-width: 767px) {
	.sm\:tw-skew-x-2 {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}

        /* below should be: .sm\:tw--skew-x-2 */
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}

	.sm\:hover\:tw-skew-x-2:hover {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}

        /* below should be: .sm\:hover\:tw--skew-x-2:hover */
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}

	.sm\:focus\:tw-skew-x-2:focus {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}

        /* below should be: .sm\:focus\:tw--skew-x-2:focus */
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
}
```
