### DISCUSSION TITLE
Dynamic value for `addVariant` plugin

### DISCUSSION THREAD

**Discussion by saadeghi** [tailwindlabs/tailwindcss#6836] [Help]
We can use [add `variant` plugins](https://tailwindcss.com/docs/plugins#adding-variants) this way:
```js
addVariant('where-class', ':where(.class)')
```
and `where-class:grid` will result:
```css
:where(.class) {
  display: grid;
}
```
But is there a way to make the value part of it dynamic? something like `where-[anything]:grid` to generate:
```css
:where(anything) {
  display: grid;
}
```

If it's possible, it also allows us to style [`::part` pseudo element](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) of web components:
```js
addVariant('part-anything', '::part(anything)')
```
```css
::part(anything) {
}
```

**Comment by adamwathan** [comment]
Not yet but something we’re gonna dig into soon 👍🏻👍🏻

**Reply by Aurailus** [reply]
Would love to see this! I was just looking at the API the other day, disappointed that this wasn't a feature :P

**Reply by Odas0R** [reply]
At the moment I guess you can `[&::part(native)]:bg-blue-500`.

**Reply by wongjn** [reply]
You can use the `matchVariant()` in v3.2 to do this now:

```js
module.exports = {
  plugins: [
    require('tailwindcss/plugin')(({ matchVariant }) => {
      matchVariant('part', (value) => `&::part(${value})`);
    }),
  ],
};
```
Then `part-[anything]:block` would produce:
```css
.part-\[anything\]\:block::part(anything) {
  display: block;
}
```
