### DISCUSSION TITLE
Utility with Duplicate / Fallback Properties

### DISCUSSION THREAD

**Discussion by aj-foster** [tailwindlabs/tailwindcss#6844] [Help] [answered]
Hello there 👋🏼 

I'm working on an application that uses `100vh` as the height of several elements. Unfortunately this can cause issues on iOS, and one possible solution is to use [`-webkit-fill-available`](https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/). (There are other solutions that may work better in other circumstances, but this is best for my use-case.)

Of course, not every browser understands `-webkit-fill-available`, so `100vh` is an appropriate fallback value. To help encode this, I hoped to create a utility:

```css
@layer utilities {
  .h-available {
    height: 100%;
    height: 100vh;
    height: -webkit-fill-available;
  }
}
```

Unfortunately, due to the [collapsing of duplicate properties](https://github.com/tailwindlabs/tailwindcss/commit/ea6f14a499ca8993c2ec56ddefd9717566f6e4cb), the output utility has only the last value:

```css
.h-available {
  height: -webkit-fill-available;
}
```

This is a valuable optimization in general, but it nullifies the fallback behavior I was hoping for.

So, **is there a more idiomatic approach to accomplishing this behavior**?

**Comment by aj-foster** [comment]
As a workaround, I'm using the following:

```css
@layer utilities {
  .h-available, .override-shim-1 {
    height: 100%;
  }

  .h-available, .override-shim-2 {
    height: 100vh;
  }
  
  .h-available {
    height: 100%;
    height: 100vh;
    height: -webkit-fill-available;
  }
}
```

This creates the desired behavior, cascading along separate rules rather than duplicated properties. However, it is non-obvious for someone who might come along later.
