### DISCUSSION TITLE
writing-mode and text-orientation

### DISCUSSION THREAD

**Discussion by imran-vz** [tailwindlabs/tailwindcss#6845] [Ideas]
These two properties [text-orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation) and [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) are used in conjunction to create sideways text.
I could have created add a class in the utilities layer, but I just love the VSCode intellisense.

These are some suggestions.

- [text-orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation)
  - `.text-sideways`

      ```css
      text-orientation: sideways;
      ```

  - `.text-upright`

    ```css
    text-orientation: upright;
    ```

  - `.text-mixed`

    ```css
    text-orientation: mixed;
    ```

  - `.text-sideways-right`

    ```css
    text-orientation: sideways-right;
    ```

  - `.text-glyph`

    ```css
    text-orientation: use-glyph-orientation;
    ```

- [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode)

  - `.writing-vertical-lr`

    ```css
    writing-mode: vertical-lr;
    ```

  - `.writing-vertical-rl`

    ```css
    writing-mode: vertical-rl;
    ```

  - `.writing-horizontal-tb`

    ```css
    writing-mode: horizontal-tb;
    ```

**Comment by imran-vz** [comment]
### This is a duplicate issue.

### Just found another issue opened earlier #5237

**Comment by jbryan11** [comment]
I like the idea to add these two properties as new utilities. I had recently used these two properties and checked that there hasn't been any utilities for these in tailwindcss.

> These two properties [text-orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation) and [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) are used in conjunction to create sideways text. I could have created add a class in the utilities layer, but I just love the VSCode intellisense.
> 
> These are some suggestions.
> 
> * [text-orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation)
>   
>   * `.text-sideways`
>     ```css
>     text-orientation: sideways;
>     ```
>   * `.text-upright`
>     ```css
>     text-orientation: upright;
>     ```
>   * `.text-mixed`
>     ```css
>     text-orientation: mixed;
>     ```
>   * `.text-sideways-right`
>     ```css
>     text-orientation: sideways-right;
>     ```
>   * `.text-glyph`
>     ```css
>     text-orientation: use-glyph-orientation;
>     ```
> * [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode)
>   
>   * `.writing-vertical-lr`
>     ```css
>     writing-mode: vertical-lr;
>     ```
>   * `.writing-vertical-rl`
>     ```css
>     writing-mode: vertical-rl;
>     ```
>   * `.writing-horizontal-tb`
>     ```css
>     writing-mode: horizontal-tb;
>     ```


I would like to suggest other class names for the rules @M0hammedImran suggested.
For the `text-orientation` rules, rather than using `text-*`, `orientation-*`(or `orient-*`) is preferable. Using `text-*` in `.text-mixed` class name makes it vague and confusing.
Using `orientation-*` prefix, it would look like this:
```CSS
.orientation-sideways { text-orientation: sideways; }
.orientation-upright { text-orientation: upright; }
.orientation-mixed { text-orientation: mixed; }
.orientation-sideways-right { text-orientation: sideways-right; }
.orientation-glyph { text-orientation: use-glyph-orientation; }
```

On `writing-mode`, I would suggest a very different naming

```CSS
.vertical-writing-lr { writing-mode: vertical-lr; }
.vertical-writing-rl { writing-mode: vertical-rl; }
.horizontal-writing-tb { writing-mode: horizontal-tb; }
```
