### DISCUSSION TITLE
word-break: break-word; and class to this.

### DISCUSSION THREAD

**Discussion by khaledYS** [tailwindlabs/tailwindcss#6952] [Ideas]
# break word 

Hey tailwind team, \
I'm using tailwind and it's so greaaaaat,\
I liked it but there is a tiny problem, a really tiny problem,\
the problem is if I want to apply the following style to an element
```css
    .random-element{
        word-break: break-word;
    }
```
there isn't any class name that apllies this style.\
I wish you add it as soon as possible.
with my whole thanks to the team.
