### DISCUSSION TITLE
Support purge ignore comment in css files again

### DISCUSSION THREAD

**Discussion by Cephyric-gh** [tailwindlabs/tailwindcss#7001] [Ideas]
When Tailwind moved away from purgecss we lost the ability to set up block scopes to ensure that the styles are always generated. I work around this currently by using the regex support on safelists (which I really appreciated when that was brought back, as maintaining a giant safelist txt file was such a pain!), but it'd be nice to just add comment scopes to force tailwind to ignore that block during purge.

To add some context - In my specific use-case I need to also use the classes as responsive variants, thus am forced to include it in the components layer which makes it subject to the purge. Being able to do something like the below would be much preferred to having a crazy regex block to stop them from being purged:

```scss
/* safelist start variants:sm,md,lg,xl,2xl */
@layer components {
    .container-fluid {
        @apply w-full mx-auto px-6;
    }

    @for $i from 1 through 12 {
        .col-#{$i} {
            @apply relative px-3 flex-grow-0 flex-shrink-0;
            flex-basis: #{(math.div(100%, 12)) * $i};
            max-width: #{(math.div(100%, 12)) * $i};
        }
    }

    .col {
        @apply flex-grow max-w-full px-3;
        flex-basis: 0;
    }

    .col-auto {
        @apply flex-min w-auto max-w-full px-3;
    }

    @for $i from 0 through 11 {
        .offset-#{$i} {
            margin-left: #{(math.div(100%, 12)) * $i};
        }
    }

    .row {
        @apply flex flex-wrap -mx-3;
    }
}
/* safelist end */
```

The concept here being that `safelist start` will protect the base classes and then being able to separately define variants that you with to protect alongside it.
The system as it stands is of course fine for my setup as I am protecting the classes via regex as I said, but IMO being able to define it like above makes it far more obvious to other devs in the team what it protected without them having to go to the config file and parse the regex in their heads.
