### DISCUSSION TITLE
at apply CSS properties change on subsequent build with PostCSS and Webpack

### DISCUSSION THREAD

**Discussion by allaire** [tailwindlabs/tailwindcss#7022] [Help]
I haven't been able to create a reproduction projet yet and my current project is private, but anyone is experiencing a similar issue since Tailwind 3.x ? Tailwind 2.x with JIT is not giving me this issue.

**What version of Tailwind CSS are you using?**

3.0.13

**What build tool (or framework if it abstracts the build tool) are you using?**

* webpack 4.46.0
* postcss 8.4.5

**What version of Node.js are you using?**

Node 12

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

N/A yet

**Describe your issue**

It looks like when I edit the file, the order of the properties is different than the initial webpack build.

**SCSS:**

```scss
...

  &__form {
    @apply relative;

    &-input {
      @apply w-full h-4 px-6 rounded-full bg-white appearance-none text-white font-semibold;

      background-color: rgba($white, 0.15);
      transition: background-color 0.2s;

      &::placeholder {
        @apply font-semibold opacity-100;

        color: rgba($white, 0.75);
      }

      @include hover {
        background-color: rgba($white, 0.2);

        &::placeholder {
          @apply text-white;
        }
      }

      @include focus {
        @apply text-greenery bg-white;

        &::placeholder {
          @apply text-greenery-300 opacity-100;
        }
      }

      @screen md {
        padding-right: 220px;
      }
    }
```

**Initial build compiled CSS:**

```css
.hero__form-input {
    height: 4rem;
    width: 100%;
    -webkit-appearance: none;
    appearance: none;
    border-radius: 9999px;
    --tw-bg-opacity: 1;
    background-color: rgb(255 255 255 / var(--tw-bg-opacity));
    padding-left: 1.5rem;
    padding-right: 1.5rem;
    font-weight: 600;
    --tw-text-opacity: 1;
    color: rgb(255 255 255 / var(--tw-text-opacity));
    background-color: rgba(255, 255, 255, 0.15);
    transition: background-color 0.2s;
}
```

**Compiled CSS after file save:**

```
.hero__form-input {
    background-color: rgba(255, 255, 255, 0.15);
    transition: background-color 0.2s;
    height: 4rem;
    width: 100%;
    -webkit-appearance: none;
    appearance: none;
    border-radius: 9999px;
    --tw-bg-opacity: 1;
    background-color: rgb(255 255 255 / var(--tw-bg-opacity));
    padding-left: 1.5rem;
    padding-right: 1.5rem;
    font-weight: 600;
    --tw-text-opacity: 1;
    color: rgb(255 255 255 / var(--tw-text-opacity));
}```

It looks like the at-apply propeties are compiled after my properties in the CSS element (background-color and transition) on subsequent run, like the order is messed up. I tried deactivating the hot-reload of webpack and it didn't work.

Any pointers of where I should start digging? Like I said, latest tailwind V2 isn't giving me any problem with this.

Thanks!
