### DISCUSSION TITLE
@variants and @responsive in TailwindCSS v3

### DISCUSSION THREAD

**Discussion by therealgilles** [tailwindlabs/tailwindcss#7026] [Help]
I am not sure how to rewrite the following code for v3:

```css
@layer utilities {
	.arrow-right-no-clip-path,
	.arrow-left-no-clip-path {
		clip-path: inset(0 0);
	}

	@variants group-hover {
		.arrow-right-clip-path {
			clip-path: inset(0 0 0 0.5rem);
		}

		.arrow-left-clip-path {
			clip-path: inset(0 0.5rem 0 0);
		}
	}
}
```

```css
@responsive {
	.slide-in-from-left {
		animation: var(--animation-duration) var(--animation-fn) var(--animation-delay) 1
			slideInFromLeft;
	}
```

Any pointers or advice would be appreciated.
