### DISCUSSION TITLE
Filters not working on production build

### DISCUSSION THREAD

**Discussion by huco95** [tailwindlabs/tailwindcss#7131] [Help] [answered]
Hi,

I am using tailwind 3.0.15 with Nuxt.js. I have a problem using the following filters with a background image:

``` html
  <section
    class="relative flex items-center justify-center min-h-screen before:content-[''] before:bg-hero-image before:absolute before:top-0 before:left-0 before:w-full before:h-full before:bg-cover before:filter before:grayscale before:brightness-50"
  >
```

On  dev build it works but not on production build.

You can see the full code here: https://github.com/huco95/don-jamon-web/blob/master/components/Hero.vue

Thanks!🙏

**Comment by Lordnibbler** [comment]
Seeing similar issues, posted my findings here: https://github.com/tailwindlabs/tailwindcss/discussions/7044

Seems to be 3.0.12 and above broke this. Try downgrading to 3.0.11 and report if it fixes for you?

**Reply by willcosgrove** [reply]
I was also running into this issue. Downgrading to 3.0.11 fixed the issue for me

**Reply by huco95** [reply]
Thanks! I will try this!

**Comment by onmax** [comment]
I think this only happens when you apply more than one filter. I don't know if that helps to solve the issue 🐕‍🦺

**Reply by Benjamin-Lee** [reply]
I don't think so, since I am only using one filter and still getting this error.

**Comment by WeaverOfTheWeb** [comment]
This still seems to be broken in v3.1.8

**Comment by ji-horak** [comment]
v3.2.1 still broken

**Comment by coaperator** [comment]
v3.2.2 still broken
downgrading to version 3.0.11 helped me

**Comment by daafbleumink** [comment]
v3.2.4 still broken.
downgrading to version 3.0.11 helped me

**Reply by prikr** [reply]
Ha Daaf, jij ook hier!

**Comment by adamwathan** [comment, marked as answer]
The issue is in your minifier, you must be using some old version of cssnano or similar that is improperly minifying the CSS.

Here's the difference between v3.0.11 and v3.0.12:

```css
/* v3.0.11 */
* {
  --tw-blur: var(--tw-empty,/*!*/ /*!*/);
  --tw-brightness: var(--tw-empty,/*!*/ /*!*/);
  --tw-contrast: var(--tw-empty,/*!*/ /*!*/);
  --tw-grayscale: var(--tw-empty,/*!*/ /*!*/);
  --tw-hue-rotate: var(--tw-empty,/*!*/ /*!*/);
  --tw-invert: var(--tw-empty,/*!*/ /*!*/);
  --tw-saturate: var(--tw-empty,/*!*/ /*!*/);
  --tw-sepia: var(--tw-empty,/*!*/ /*!*/);
  --tw-drop-shadow: var(--tw-empty,/*!*/ /*!*/);
}

/* v3.0.12 */
* {
  --tw-blur: ;
  --tw-brightness: ;
  --tw-contrast: ;
  --tw-grayscale: ;
  --tw-hue-rotate: ;
  --tw-invert: ;
  --tw-saturate: ;
  --tw-sepia: ;
  --tw-drop-shadow: ;
}
```

What we were doing in v3.0.11 was a lame hack/trick to prevent the minifier from removing the space before the semicolon. That bug was fixed in all minifiers, so we removed the `var` stuff because it was no longer necessary and introduced a performance cost.

So make sure you are on the latest version of whatever CSS minification tool you are using and everything will work. If not it is a bug in your minifier that is removing important whitespace.
