### DISCUSSION TITLE
Add utility to set position of text underline

### DISCUSSION THREAD

**Discussion by sntran** [tailwindlabs/tailwindcss#7146] [Ideas]
For example:

```css
.underline-auto {
  text-underline-position: auto;
}

.underline-under {
  text-underline-position: under;
}

.underline-left {
  text-underline-position: left;
}

.underline-under {
  text-underline-position: right;
}
```
