### DISCUSSION TITLE
Borders appear in production build with cssnano

### DISCUSSION THREAD

**Discussion by yandodov** [tailwindlabs/tailwindcss#7168] [Help]
When I build in development mode, everything's fine. When I build for production, there are borders around some elements.

**Comment by yandodov** [comment]
The problem was that cssnano messes up Tailwind's CSS preflight. It turns this:

```css
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: 'currentColor'; /* 2 */
}
```

...to this:

```css
*,:after,:before{border:0 solid "currentColor";box-sizing:border-box}
```

As you can see, the `border-*` properties are merged into a single `border` property. You can see for yourself in [the cssnano playground](https://cssnano.co/playground/).

I managed to fix it by disabling the [mergeLonghand](https://cssnano.co/docs/optimisations/mergelonghand/) option:

```js
let nano = require("cssnano")({
	preset: [
		"default",
		{
			mergeLonghand: false,
		},
	],
});
```
