### DISCUSSION TITLE
Tailwind x Preprocessor (Sass) generates unexpected rule (?)

### DISCUSSION THREAD

**Discussion by hta218** [tailwindlabs/tailwindcss#7195] [Help]
Let's say I have the below SCSS rules:

```scss
.foo {
  @apply w-full;
}
.bar {
  > .w-full {
    color: red;
  }
}
```

And the markup

```html
<div class="bar">
  <div class="foo">
  </div>
</div>
```

Somehow Tailwind (or Webpack ?) generate this unexpected rule: 
```scss
.bar > .foo {
  color: red;
}
```
(The devtool say it comes from `tailwind.css` file which includes `@base`, `@components` and `@utilities` layers)

This is my Webpack configs: 

```js
{
  test: /\.(sa|sc|c)ss$/,
  exclude: /plyr/,
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader: "css-loader",
      options: {
        sourceMap: !isProduction
      }
    },
    'postcss-loader',
    {
      // First we transform SASS to standard CSS
      loader: "sass-loader",
      options: {
        implementation: require("sass"),
        sourceMap: !isProduction
      }
    }
  ]
},
```

The `postcss.config.js` and `tailwind.config.js` files are just basic Tailwind's configs

Anyone have an idea on this?
