### DISCUSSION TITLE
Opacity shorthand use CSS custom properties instead?

### DISCUSSION THREAD

**Discussion by austenc** [tailwindlabs/tailwindcss#7253] [Ideas]
### Here's the Play example
https://play.tailwindcss.com/c6uOM7hU4l

### Description of the problem
When using the opacity shorthand, such as `bg-blue-500/50`, it doesn't play nicely with the Tailwind CSS custom properties, so code like this won't show any change on hover:
```html
<button class="bg-blue-500/50 hover:bg-opacity-100">Example</button>
```

It seems that the `bg-opacity-*` classes are now deprecated, so the "official" way of doing this is to repeat the color, like so?
```html
<button class="bg-blue-500/50 hover:bg-blue-500/100">Example</button>
```

Is it possible to make the shorthand use (and set) Tailwind's custom CSS properties? For example:
```html
<button class="bg-blue-500/50 hover:bg-opacity-100">Example</button>
```

Proposed changes would result in this generated CSS:
```css
.bg-blue-500\/50 {
  --tw-bg-opacity: 0.5;
  background-color: rgb(59 130 246 / var(--tw-bg-opacity));

  /* This is how it works currently */
  /* background-color: rgb(59 130 246 / 0.5); */
}
.hover\:bg-opacity-100:hover {
  --tw-bg-opacity: 1;
}
```

Happy to make a PR if this is something that is possible without messing up the framework in other areas. Wanted to discuss first, especially because the `bg-opacity-*` stuff seems deprecated. Thank you!
