### DISCUSSION TITLE
Add `!important` to class names

### DISCUSSION THREAD

**Discussion by alikazemkhanloo** [tailwindlabs/tailwindcss#7276] [Help] [answered]
add `!important` to class names:
```html
<MyComponent className="bg-red!" />
```
this will correspond to :
```css
bg-red! {
  background-color: red !important;
}
```

this will enable us to override classNames used in components.
