### DISCUSSION TITLE
Support ::backdrop pseudo-element

### DISCUSSION THREAD

**Discussion by jonathanstanley** [tailwindlabs/tailwindcss#7334] [Ideas]
As an option for dialogs and other elements, support for the[ `::backdrop` pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop) would be very nice (and could simplify some of the tailwindui components). this is not the same as `backdrop-filter` 

```css
/* Backdrop is only displayed when dialog is opened with dialog.showModal() */
dialog::backdrop {
  background: rgba(255,0,0,.25);
}
```

This enables many more options beyond the simple filters currently available.  I couldn't find any discussion on this, so adding as a suggestion.  ~~it may be low use because [Safari iOS doesn't yet support it](https://caniuse.com/?search=%3A%3Abackdrop).~~ Upon the [Safari 15.4 update](https://github.com/mdn/browser-compat-data/pull/14757), this will be [supported in all modern browsers](https://caniuse.com/mdn-css_selectors_backdrop).
