### DISCUSSION TITLE
Support JIT arbitrary value using theme value

### DISCUSSION THREAD

**Discussion by anhzf** [tailwindlabs/tailwindcss#7371] [Ideas]
I just want to not touch my CSS file just to apply tailwind provided values using the theme()

*So I can just write this utility*
```HTML
<div class="max-w-[spacing.60]">...</div>
```

*instead of writing this then applying it to my HTML*

CSS
```CSS
.max-w-60 {
  max-width: theme('spacing.60');
}
```

HTML
```HTML
<div class="max-w-60">...</div>
```

Thank you for any feedback! 😀
