### DISCUSSION TITLE
@apply not working in scss nesting.

### DISCUSSION THREAD

**Discussion by CodingRuo** [tailwindlabs/tailwindcss#7421] [Help]
Hy! I have a small problem and unfortunately I can not find the solution. The following code shows that I have a button class in SCSS and with the & operator the classes are inherited in the BEM notation. But I want to make the code clearer, and have written a hover function. The problem is that @apply does not work. Have I done something wrong or is this simply not possible?  

```scss
.btn {
    @apply tracking-normal font-sans text-sm normal-case bg-primary text-black rounded-none !no-underline text-center inline-block 
    align-top border-none cursor-pointer transition-all duration-200 ease-linear rounded-full;
    min-width: 196px;
    width: 100%;
    padding: 13px 0;
    line-height: 18px;
    font-size: var(--button-fontsize);
    margin: 0 0 10px;
    cursor: pointer;

    @mixin buttonHover($text-color, $bg-color) {
        &:not(:disabled):not(.disabled):hover,
        &:not(:disabled):not(.disabled):focus,
        &:not(:disabled):not(.disabled):active {
            @apply #{$text-color};
            @apply #{$bg-color};
        }
    }

    @include buttonHover(".text-white", ".bg-primary-400");

    @screen sm {
        @apply w-auto;
        margin-right: 10px;
    }

    &-secondary {
        @apply bg-secondary text-white;

        &:not(:disabled):not(.disabled):hover,
        &:not(:disabled):not(.disabled):focus,
        &:not(:disabled):not(.disabled):active {
            @apply bg-highlight-400 text-black;
        }
    }
}
```

This is my first post in general in Github, please don't be mad if I just break any rules or schemas. Thanks for the help :)
