### DISCUSSION TITLE
.appearance-none does not seem to work

### DISCUSSION THREAD

**Discussion by Vi-obb** [tailwindlabs/tailwindcss#7429] [Help]
I am trying to remove a default style from an input using `.appearance-none` but for some reason it's not working. I don't know if I got the installation wrong, everything is working perfectly except for `.appearance-none`.

This is how it appears in my output css file:

```
.appearance-none {
   -webkit-appearance: none;
      -moz-appearance: none;
           appearance: none
 }
```
I'd be grateful for any support.

**Comment by adamwathan** [comment]
Hey! What do you mean by "not working"? What exactly are you trying to do and what are you seeing happen instead? It does "work" in the sense that it does what it's intended to do, as demonstrated here in the documentation:

https://tailwindcss.com/docs/appearance#removing-default-element-appearance

Here's another demo I just created in Tailwind Play:

https://play.tailwindcss.com/s2LUB8NQoT

You can see the first select does have the dropdown arrow, and the second one doesn't because I've added `appearance-none`.

If by some chance you are actually trying to just hide an element (I can see how `appearance-none` sounds like it might be used for that), you want the `hidden` class or the `invisible` class depending on what exactly you're trying to do.

**Reply by Vi-obb** [reply]
Thanks for explaining and providing some examples. But I am trying to remove the arrows on a number input. Like I said, when I add the class, the styles are added in the output css but it doesn't reflect on what I'm working on. The arrows are not removed.

**Reply by adamwathan** [reply]
Gotcha, so the problem here is just that that’s not how you hide the arrow buttons on number inputs, you need to style special browser specific pseudo elements:

https://css-tricks.com/snippets/css/turn-off-number-input-spinners/

You could use a custom variant to target these in your HTML if you want 👍🏻

**Reply by Vi-obb** [reply]
Thanks. Will do that 👍🏾

**Reply by oxc** [reply]
For anyone else trying to find a solution, here is what works nicely for me in Chrome and Firefox:

```css
/* add to globals.css */

@layer base {
  input[type=number].appearance-none::-webkit-inner-spin-button,
  input[type=number].appearance-none::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }
  input[type=number].appearance-none {
    -moz-appearance:textfield;
  }
}
```

This way I can just keep using `appearance-none`, which is expressive enough for my taste to include this behaviour. IMHO the browsers should do that if the input has `appearance: none`.
