### DISCUSSION TITLE
How do I get rid of the preflight font-family?

### DISCUSSION THREAD

**Discussion by dotnetCarpenter** [tailwindlabs/tailwindcss#7491] [Help] [answered]
I keep seeing the [preflight.css's font-family](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L32) when I do `vite build` even though I try to overwrite `font-family` for `html` in my _tailwind.config.js_.

_preflight.css_
```css
html {
	line-height: 1.5;
	-webkit-text-size-adjust: 100%;
	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;
	font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", Segoe UI Symbol, "Noto Color Emoji"
}
```

_tailwind.config.js_
```js
module.exports = {
  content: [
    './index.html',
    './js/**/*.{html,js,mjs}',
  ],
  theme: {
    extend: {
      maxWidth: {
        'x-screen': '100vw'
      },
      colors: {
        'svv-grey': 'hsl(201, 11%, 30%)',
        'svv-yellow': 'rgb(255, 214, 31)',
        'svv-red': 'hsl(355, 85%, 52%)'
      },
    },
    fontFamily: {
      'html': '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

Is it the fault of [vite](https://vitejs.dev/) or is it impossible to overwrite Tailwind CSS's `font-family`?

Reference to Tailwind CSS docs: https://tailwindcss.com/docs/font-family#using-custom-values
