### DISCUSSION TITLE
Easier overwrite of @tailwind base

### DISCUSSION THREAD

**Discussion by dotnetCarpenter** [tailwindlabs/tailwindcss#7496] [Ideas]
Currently the only way to overwrite the default `font-family` (meaning removing it completely from CSS) is to define `theme.fontFamily.sans`, like so:

```js
module.exports = {
  theme: {
    fontFamily: {
      sans: '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
    }
  }
}
```
_tailwind.config.js_

One thing is that this is not documented at https://tailwindcss.com/docs/font-family#using-custom-values.
However, I found hints to overwriting `font-family` in https://tailwindcss.com/docs/theme#customizing-the-default-theme.

I still think this leaves much to be desired. It have taken me over 1 hour of trial and error.. If you look at the [same question on StackOverflow](https://stackoverflow.com/q/60692794/205696), you will find multiple *wrong* answers.

### How about tying this to the CSS selector, which is what you will see in devTools?

Let's say we want to customize the preflight CSS to:
```css
html {
  line-height: 1.5; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
  -moz-tab-size: 4; /* 3 */
  -o-tab-size: 4;
     tab-size: 4; /* 3 */
  font-family: "LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif; /* 4 */
}
a {
  color: inherit;
  text-decoration: brown underlined;
}
```

One approach could be to still use _tailwind.config.js_ but specifying a selector instead of a Tailwind CSS variable. Of course that might be a slippery slope if all kinds of CSS selectors are allowed or it might be a nice feature.

```js
theme: {
  fontFamily: {
    'html': '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
  },
  textDecoration: {
    'a': 'brown underline'
  }
}
```
_Example of overwriting preflight.css without having to know Tailwind CSS's variable names._

Another approach would be to use `@layer`, so that **instead** of adding to the base CSS, it would overwrite matching selectors **and** properties.

```css
@layer base {
  html {
    font-family: "LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
  }
  a {
    text-decoration: brown underlined;
  }
}
```
_This approach requires zero knowledge of Tailwind CSS and is literally how you would do it in regular CSS but now with a kind of CSS tree-shaking._

What do you think? Is it worth pursuing?
Of course, everything can also be made easier by writing specific documentation on how to overwrite the default `font-family` in Tailwind CSS.

### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7491

<div type='discussions-op-text'>

<sup>Originally posted by **dotnetCarpenter** February 16, 2022</sup>
I keep seeing the [preflight.css's font-family](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L32) when I do `vite build` even though I try to overwrite `font-family` for `html` in my _tailwind.config.js_.

_preflight.css_
```css
html {
	line-height: 1.5;
	-webkit-text-size-adjust: 100%;
	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;
	font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", Segoe UI Symbol, "Noto Color Emoji"
}
```

_tailwind.config.js_
```js
module.exports = {
  content: [
    './index.html',
    './js/**/*.{html,js,mjs}',
  ],
  theme: {
    fontFamily: {
      'html': '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
    },
    extend: {
      maxWidth: {
        'x-screen': '100vw'
      },
      colors: {
        'svv-grey': 'hsl(201, 11%, 30%)',
        'svv-yellow': 'rgb(255, 214, 31)',
        'svv-red': 'hsl(355, 85%, 52%)'
      },
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

Is it the fault of [vite](https://vitejs.dev/) or is it impossible to overwrite Tailwind CSS's `font-family`?

Reference to Tailwind CSS docs: https://tailwindcss.com/docs/font-family#using-custom-values
Reference to StackOverflow question about this: https://stackoverflow.com/q/60692794/205696
</div>

**Comment by adamwathan** [comment]
_Converting to a discussion since this isn't a bug._

Hey! The recommended approach to adding custom base styles is documented here:

https://tailwindcss.com/docs/adding-custom-styles#adding-base-styles

As with any theme-driven value in Tailwind, you can customize what `font-sans` does by customizing the `sans` key, as you discovered:

```js
module.exports = {
  theme: {
    fontFamily: {
      sans: '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
    }
  }
}
```

We don't provide any way to customize Preflight styles through your configuration, though some rules in Preflight do pull their values from the theme (the default font family is one of them).

You can find those rules by searching the Preflight source file for `theme(`:

https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css

Agree it would be a good idea to add something to the documentation specifically explaining how to customize the default font since it's something people ask about so frequently and mistakenly expect us to offer some specific configuration for. In my mind though it's just a simple custom base style, no different than setting a custom background color on the `body` tag or a default font weight on `a` tags.

No plans to add support for tree-shaking overridden Preflight rules — I think that would be better handled by a smart minifier.

**Comment by dotnetCarpenter** [comment]
>No plans to add support for tree-shaking overridden Preflight rules — I think that would be better handled by a smart minifier.

_tree-shaking_ is bit misleading. My point was that instead of overriding a CSS property as `@layer` does, Tailwind would in effect remove the property by overwriting it.

I'm completely fine with adding to the docs as a way to make it easier to overwrite _base_ CSS from tailwind. But I also thought it would be worth revisiting how tailwind works. Tailwind ~already uses~ were using PurgeCSS and still removes unused styles from the CSS output. But as far as I know, it only works for classes and not [CSS type selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Type_selectors). I don't see how anything outside tailwind can safely purge cascading styles. You would have to know all of the content to be sure that a selector is truly shadowed by another selector. Better to make overwrites explicit.

Currently there is 3 options for customizing tailwind's base CSS, neither is super desirable.

1. Override properties by using `@layer`, adding a CSS type selector to the `extend` section in _tailwind.config.js_ or add a CSS selector in your stylesheet with same or higher specificity than defined in [_preflight.css_](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css) (which evolves over time, so _preflight.css_ is a moving target).
2. Find rules by searching the Preflight source file for `theme(` and add them to _tailwind.config.js_  - as you said. Still, _preflight.css_ is a moving target. Or use `require("tailwindcss/defaultTheme")` to mutate the default theme and then export it.
3. [Disabling Preflight](https://tailwindcss.com/docs/preflight#disabling-preflight), [disabling the default configuration](https://tailwindcss.com/docs/presets#disabling-the-default-configuration) or not include `@tailwind base` in your stylesheet.

The issue with 1) is that we create duplicate CSS, which is the aim of an overwrite to remove in the first place. Number 2 feels like finding needles in a haystack and as you said, it is only some properties that can be overwritten this way. If one feel the need to go the route of disabling tailwind's CSS, the question is perhaps, why use Tailwind CSS?

Regardless, the desire to not have extraneous CSS in production should not mean you have to write/provide your own reset CSS. That will probably also create issues with tailwind's components and utilities.

Since _preflight.css_ can change between versions, documentation risk being constant out of date. So surely only relying on documentation is a poor choice as well.

**Reply by adamwathan** [reply]
Personally I guess I'm just not worried about shipping this:

```css
html {
  line-height: 1.5; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
  -moz-tab-size: 4; /* 3 */
  tab-size: 4; /* 3 */
  font-family: theme('fontFamily.sans', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"); /* 4 */
}
html {
  font-family: "LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif;
}
```

vs. this:

```css
html {
  line-height: 1.5; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
  -moz-tab-size: 4; /* 3 */
  tab-size: 4; /* 3 */
  font-family: "LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
}
```

To me it's just such a micro-optimization that it's not worth the complexity. In my opinion this is the sort of thing that is much better handled by a minifier, where this sort of optimization is the goal of the project and therefore definitely in scope.

Tailwind is semantically versioned so Preflight won't change in any breaking way until v4, and every major version has a separate documentation site.

If you really wanted to customize Preflight, the easiest way to do it is to disable Preflight, then copy our CSS for Preflight, paste it into your project, and edit it to whatever you want. You would be missing any new stuff we add to Preflight after you copy it of course, but it changes incredibly rarely, and anything we add is going to be super edge-case stuff that likely wouldn't affect you anyways.
