### DISCUSSION TITLE
`@apply` custom utilities  in Vue component and fails

### DISCUSSION THREAD

**Discussion by ShookLyngs** [tailwindlabs/tailwindcss#7529] [Help]
I added custom utilities in `index.css` like this:
```css
@layer utilities {
  .body-x {
    padding-left: var(--body-spacing-x);
    padding-right: var(--body-spacing-x);
  }
}
```

And then if I use the utility in Vue `<template>`, it works.
But when I tried to apply it in on class in `<style scoped>`, the tailwind told me that the utility does not exist:
```css
<style scoped>
  .title {
    @apply body-x;
  }
</style>
```

Error message:
```
The `body-x` class does not exist. If `body-x` is a custom class, make sure it is defined within a `@layer` directive.
```

What should I do to fix the issue?
