### DISCUSSION TITLE
Which tailwind classNames make a button pop-up on click ?

### DISCUSSION THREAD

**Discussion by ProPhycient5** [tailwindlabs/tailwindcss#7605] [Help]
Which group of css classNames helps to make a button pop-up (like bloomsome ) while clicking on it.

**Comment by ahmadshiddiq** [comment]
Is this what you mean?
https://tailwindcss.com/docs/animation#bounce

**Reply by ProPhycient5** [reply]
Yeah, but it must bounce when we click on button only.
What you have suggested, it is continuously bouncing.

**Reply by ProPhycient5** [reply]
https://daisyui.com/components/button/

If u check the button on the above link, you get what I mean.

**Comment by igortrinidad** [comment]
@ProPhycient5 i extracted the code from daisy ui and it worked for me, try it out:

```css

.btn:active {
  animation: button-pop 0.25s ease-out;
}

@keyframes button-pop {
  0% {
    transform: scale(.90)
  }
  40% {
    transform: scale(1.02)
  }
  to {
    transform: scale(1)
  }
}
```
