### DISCUSSION TITLE
Allow excluding min-width breakpoint from container-utility

### DISCUSSION THREAD

**Discussion by MichaelAllenWarner** [tailwindlabs/tailwindcss#7659] [Ideas]
I'd like to be able to specify a _subset_ of min-width breakpoints to use with the `container` utility, either with an "include" list or an "exclude" list. The reason is simply that there's not always a one-to-one correspondence between breakpoints I'm using in the project and breakpoints that I want for max-width-container purposes. For example, if the need arises to add a breakpoint for some specific styling purpose (maybe in the site-header), I don't necessarily want that breakpoint to become a new _container_ for all of my content.

I guess in the config, it might look something like:

```javascript
screens: {
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px'
},

container: {
  center: true,
  padding: 2rem,
  exclude: ['2xl']
}
```

or:

```javascript
screens: {
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px'
},

container: {
  center: true,
  padding: 2rem,
  include: ['sm', 'md', 'lg', 'xl']
}
```

**Comment by adamwathan** [comment]
Hey! I think it would be a lot simpler to just disable the container plugin and add your own container class that does what you want personally. Conceptually the container is just "an element whose width matches the current breakpoint" and honestly I already regret that it has the `center` and `padding` options, but we kept them for backwards compatibility. Adding any more stuff just feels like too much configuration for something that's easier to just express directly in CSS in my opinion 👍

In our own code we don't even use it, we just use the `max-w-{value}` classes instead.

Example of what you could do:

```js
// tailwind.config.js
module.exports = {
  corePlugins: {
    container: false
  }
}
```

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .container {
    max-width: none;
    margin: 0 auto;
    padding: 0 2rem;
  }

  @screen sm {
    .container {
      max-width: theme('screens.sm');
    }
  }

  @screen md {
    .container {
      max-width: theme('screens.md');
    }
  }

  @screen lg {
    .container {
      max-width: theme('screens.lg');
    }
  }

  @screen xl {
    .container {
      max-width: theme('screens.xl');
    }
  }
}
```
