### DISCUSSION TITLE
Classes added via JavaScript are not detected

### DISCUSSION THREAD

**Discussion by chexburger** [tailwindlabs/tailwindcss#7686] [Help]
**What version of Tailwind CSS are you using?**
3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**
npx tailwindcss

**What version of Node.js are you using?**
16.6.1

**What browser are you using?**
Opera GX

**What operating system are you using?**
Windows 11

**Reproduction URL**
This simply has code from the file that the problem is occurring in. This file will need to be built from. I was unable to find anything that would allow me to run everything with Tailwind that wouldn't defeat the purpose of showing that classes are not detected.
[tailwind_bug_code.txt](https://github.com/tailwindlabs/tailwindcss/files/8147540/tailwind_bug_code.txt)

**Describe your issue**
Documentation states that JavaScript is scanned for Tailwind CSS classes. This is clearly not the case. Classes present in any JavaScript, including script tags in files that show functionality, are not included in the final build. Happens with any classes not included in `class=` when using vanilla HTML (i.e. no inline ternary).
https://tailwindcss.com/docs/content-configuration#configuring-source-paths

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We look at all the files you register in your `content` configuration inside your `tailwind.config.js`. These files can be anything because we look at the files as raw plain text. Make sure to double check your configuration file.

If I paste your code section in Tailwind Play then I see these classes being generated:
```css
.fixed {
    position: fixed
}
.bottom-0 {
    bottom: 0px
}
.top-\[60px\] {
    top: 60px
}
.mx-1 {
    margin-left: 0.25rem;
    margin-right: 0.25rem
}
.ml-3 {
    margin-left: 0.75rem
}
.mr-3 {
    margin-right: 0.75rem
}
.flex {
    display: flex
}
.h-5 {
    height: 1.25rem
}
.h-6 {
    height: 1.5rem
}
.h-full {
    height: 100%
}
.w-5 {
    width: 1.25rem
}
.w-full {
    width: 100%
}
.w-6 {
    width: 1.5rem
}
.w-60 {
    width: 15rem
}
.flex-1 {
    flex: 1 1 0%
}
.flex-shrink-0 {
    flex-shrink: 0
}
.flex-grow {
    flex-grow: 1
}
.transform {
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
}
.flex-col {
    flex-direction: column
}
.items-center {
    align-items: center
}
.space-y-1 > :not([hidden]) ~ :not([hidden]) {
    --tw-space-y-reverse: 0;
    margin-top: calc(0.25rem * calc(1 - var(--tw-space-y-reverse)));
    margin-bottom: calc(0.25rem * var(--tw-space-y-reverse))
}
.bg-opacity-20 {
    --tw-bg-opacity: 0.2
}
.py-1 {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem
}
.px-2 {
    padding-left: 0.5rem;
    padding-right: 0.5rem
}
.pr-2 {
    padding-right: 0.5rem
}
.pl-2 {
    padding-left: 0.5rem
}
.pl-11 {
    padding-left: 2.75rem
}
.text-left {
    text-align: left
}
.text-sm {
    font-size: 0.875rem;
    line-height: 1.25rem
}
.font-normal {
    font-weight: 400
}
.text-gray-300 {
    --tw-text-opacity: 1;
    color: rgb(209 213 219 / var(--tw-text-opacity))
}
.text-gray-500 {
    --tw-text-opacity: 1;
    color: rgb(107 114 128 / var(--tw-text-opacity))
}
.text-gray-400 {
    --tw-text-opacity: 1;
    color: rgb(156 163 175 / var(--tw-text-opacity))
}
.text-purple-500 {
    --tw-text-opacity: 1;
    color: rgb(168 85 247 / var(--tw-text-opacity))
}
.transition-colors {
    transition-property: color, background-color, border-color, fill, stroke, -webkit-text-decoration-color;
    transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;
    transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, -webkit-text-decoration-color;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 150ms
}
.duration-150 {
    transition-duration: 150ms
}
.ease-in-out {
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1)
}
.group:hover .group-hover\:text-gray-400 {
    --tw-text-opacity: 1;
    color: rgb(156 163 175 / var(--tw-text-opacity))
}
.group:hover .group-hover\:text-gray-100 {
    --tw-text-opacity: 1;
    color: rgb(243 244 246 / var(--tw-text-opacity))
}
.group:hover .group-hover\:text-gray-500 {
    --tw-text-opacity: 1;
    color: rgb(107 114 128 / var(--tw-text-opacity))
}
```

If you still have an issue after double checking your `tailwind.config.js` file, then please open a new issue with a minimal reproduction repo attached so that we can debug this further.
