### DISCUSSION TITLE
How to add a custom font?

### DISCUSSION THREAD

**Discussion by paulwongx** [tailwindlabs/tailwindcss#7762] [Help] [answered]
How do I add custom fonts to my React project? I see multiple examples but the nuances make it not work currently.

I'm trying to add this custom font (Google font) called [LodrinaSolid](https://fonts.google.com/specimen/Londrina+Solid). 

In my index.css I add all the weights, but not sure 
1) Should it be `format("ttf")` or `format("truetype")` as per [this](https://github.com/tailwindlabs/tailwindcss/discussions/2060#discussioncomment-1037915) or do I need to even include it?
2) Where should the fonts folder be? In the `public` folder outside of the src, or can it be inside src? I assume outside the src folder and in the `public` folder. I currently have it in a fonts folder. And I assume url("fonts/LondrinaSolid-Black.ttf") links to the public folder.
3) Do all the @font-face's need to be wrapped in a @layer object?

```css
@font-face {
	font-family: "londrinaBlack";
	font-weight: 900;
	src: url("fonts/LondrinaSolid-Black.ttf") format("truetype");
}
@font-face {
	font-family: "londrinaLight";
	font-weight: 300;
	src: url("fonts/LondrinaSolid-Light.ttf") format("truetype");
}
@font-face {
	font-family: "londrinaRegular";
	font-weight: 400;
	src: url("fonts/LondrinaSolid-Regular.ttf");
}
@font-face {
	font-family: "londrinaThin";
	font-weight: 100;
	src: url("fonts/LondrinaSolid-Thin.ttf");
}
```

My tailwind.config.js
1) Because the fonts aren't even loading in index.css, I tried loading it with a script tag in `public>index.html` and I'm not sure if loading it here should be written as '"Londrina+Solid"', or '"Londrina Solid"'
2) Otherwise, should I be adding all the weights I loaded in `indexcss` here or somewhere else?
```js
module.exports = {
	darkMode: "class",
	content: ["./src/**/*.{js,jsx,ts,tsx}"],
	theme: {
		extend: {
			fontFamily: {
				londrina: [
					"londrinaRegular",
					"londrinaThin",
					"londrinaBlack",
					"londrinaRegular",
                    // '"Londrina+Solid"',
					"sans-serif",
				],
			},
		},
	},
	plugins: [],
};

```
