### DISCUSSION TITLE
where to assign custom linear gradients classes?

### DISCUSSION THREAD

**Discussion by Sed9yDataBank** [tailwindlabs/tailwindcss#7868] [Help]
been using tailwindcss for few weeks and i am clueless on how to use linear gradients like the one below:

`linear-gradient(274.10deg, #87ceeb 56.99%, #ff9f30 113.11%);`

currently using this by adding a css class in `global.css` file and just calling the class to my elements like the one below:

```css
.custom-gradient-bg {
  background: linear-gradient(274.10deg, #87ceeb 56.99%, #ff9f30 113.11%);
}
```

is there a cleaner way to do this? also is it a best practice to always keep the `global.css` file empty?

thanks in advance.
