### DISCUSSION TITLE
addVariant() without adding a prefix

### DISCUSSION THREAD

**Discussion by stefanfisk** [tailwindlabs/tailwindcss#7917] [Help]
I am trying to add a variant for when a 3rd party JS library adds up-active to form elements. The code below works great when used without a prefix, when prefixes are enabled they are added to the selectors.

Does anyone know how to add such a variant without it getting prefixed?

My plugin:

```js
const plugin = require('tailwindcss/plugin');

plugin(({ addVariant, e }) => {
    addVariant('up-active', ['.up-active &', '.up-active&']);
});
```

Generated CSS for up-active:hidden without prefix:

```css
.up-active .up-active\:hidden,
.up-active.up-active\:hidden {
    display: none;
}
```

Generated CSS for up-active:hidden with prefix tw-:

```css
.tw-up-active .up-active\:tw-hidden,
.tw-up-active.up-active\:tw-hidden {
    display: none;
}
```
