### DISCUSSION TITLE
[IntelliSense] Improve display for custom utilities that use @apply

### DISCUSSION THREAD

**Discussion by MartinJohns** [tailwindlabs/tailwindcss#8196] [Ideas]
The display for custom utilities that use `@apply` is very verbose. Perhaps this can be improved. I would expect the display to be grouped under one class (the one I declare), but instead the class is repeated for each applied utility.

---

Versions:
- tailwindcss: ^3.0.24
- VS Code extension: 0.8.3

In the `tailwind.config.js`:

```javascript
const plugin = require('tailwindcss/plugin');

module.exports = {
  // ...
  plugins: [
    plugin(function({ addUtilities }) {
      addUtilities({
        '.full-container': {
          '@apply absolute top-0 left-0 w-full h-full': {}
        }
      });
    })
  ]
};
```

Usage in the React component:

```html
<div className="full-container"></div>
```

What's displayed:

![image](https://user-images.githubusercontent.com/5269069/165124792-a1ebad35-09d7-449a-b942-8edf671e6e7f.png)

What I expected / want it to display:
```css
.full-container {
    position: absolute;
    top: 0px;
    left: 0px;
    height: 100%;
    width: 100%;
}
```
