### DISCUSSION TITLE
How to handle array values from function theme?

### DISCUSSION THREAD

**Discussion by vitto** [tailwindlabs/tailwindcss#8287] [Help]
I need to use `theme` function to retrieve `drop-shadow` values but I'm not sure how to do:

```css
:host {
  --drop-shadow: theme('dropShadow.lg');
  filter: drop-shadow(var(--drop-shadow));
}
```

the parameter `dropShadow.lg` returns two elements of an array: `["0 10px 8px rgba(0, 0, 0, 0.04)", "0 4px 3px rgba(0, 0, 0, 0.1)"]`, so when compiled it will be:

```css
:host {
  --drop-shadow: 0 10px 8px rgb(0 0 0 / 0.04), 0 4px 3px rgb(0 0 0 / 0.1);
  filter: drop-shadow(var(--drop-shadow));
}
```

Instead of:

```css
:host {
  --drop-shadow: drop-shadow(0 10px 8px rgb(0 0 0 / 0.04)) drop-shadow(0 4px 3px rgb(0 0 0 / 0.1));
  filter: var(--drop-shadow);
}
```
I want to avoid `@apply` for a series of reasons related to my development environment (storybook and stencil) that overrides my web component vars.

Does exists some way to gather these params without hardcode them?

**Comment by Lelectrolux** [comment]
```css
:host {
  --drop-shadow: drop-shadow(theme('dropShadow.lg.0')) drop-shadow(theme('dropShadow.lg.1'));
  filter: drop-shadow(var(--drop-shadow));
}
```
should work ?
