### DISCUSSION TITLE
Using CSS Variables for all colors

### DISCUSSION THREAD

**Discussion by alexander-schranz** [tailwindlabs/tailwindcss#8306] [Help]
I currently could not find an option that uses automatically css variables instead of inline the colors.

E.g.: `bg-primary-300`:

Is outputted as:

```css
.bg-primary-300 {
  --tw-bg-opacity: 1;
  background-color: rgb(252 211 77/var(--tw-bg-opacity));
}
```

I want the `252 211 77` not be hardcoded instead have something like `--tw-color-primary-300`. Is there any way to achieve it. I just found plugins which will expose the colors as variables but not actually using the variables for exist classes.
