### DISCUSSION TITLE
Add `snap-mandatory-x`, `snap-mandatory-y`

### DISCUSSION THREAD

**Discussion by tordans** [tailwindlabs/tailwindcss#8487] [Ideas]
My UseCase: I have a very long list which requires scrolling x and y ([Demo URL](https://radwege-check.de/hauptstrassen/?filter=bicycleLaneWidth:wide|bufferHasPhysicalProtection:true|leftOfBicycleLane:car_lanes)).

However, I only want scroll snapping mandatory on x. On y I want no snapping or proximity snapping.

Right now, the way `snap-mandatory` and `snap-proximity` ([Docs](https://tailwindcss.com/docs/scroll-snap-type)) are set up, one can only specify those for both.

My workaround: Some custom css https://github.com/FixMyBerlin/fixmy.safetycheck/commit/aa24430a19bf301f0df631f347a4952d6a20bd6a

Suggested solution: Add `snap-mandatory-x`, `snap-mandatory-y` (same for proximity) which should then take precedence over the general `snap-mandatory`.

**Comment by 2hu12** [comment]
For your workaround
```css
  .snap-x-not-y {
    scroll-snap-type: x mandatory;
    scroll-snap-type: y proximity;
  }
```
it is equivalent to
```css
  .snap-x-not-y {
    scroll-snap-type: y proximity;
  }
```
and equivalent to `snap-y snap-proximity`

right?
