### DISCUSSION TITLE
How disable default styles for :before and :after

### DISCUSSION THREAD

**Discussion by Kbrlab** [tailwindlabs/tailwindcss#8500] [Help]
Hi, I can't find an option in the documentation to disable the default styles for pseudo-elements before and after. How can I disable these styles?

https://i.imgur.com/3XmyxJt.png

**Comment by carlos-dubon** [comment]
```css
*, ::before, ::after{
  all: none !important;
}
```
