### DISCUSSION TITLE
Add font-variant-ligatures as a utility

### DISCUSSION THREAD

**Discussion by jbryan11** [tailwindlabs/tailwindcss#8516] [Ideas]
I came across with this property and tailwindcss looked like it doesn't have utility for this one.
[Ligature](https://developer.mozilla.org/en-US/docs/Glossary/Ligature) is a joining of two characters into one shape. 
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

I suggest this to be added as one of the typography utilities available in tailwindcss.

```CSS
.ligatures-none { font-variant-ligatures: none; }

.ligatures-common { font-variant-ligatures: common; }
.ligatures-discretionary { font-variant-ligatures: discretionary; }
.ligatures-historical { font-variant-ligatures: historical; }
.ligatures-contextual { font-variant-ligatures: contextual; }

.ligatures-no-common { font-variant-ligatures: no-common; }
.ligatures-no-discretionary { font-variant-ligatures: no-discretionary; }
.ligatures-no-historical { font-variant-ligatures: no-historical; }
.ligatures-no-contextual { font-variant-ligatures: no-contextual; }
```
