### DISCUSSION TITLE
Understanding circular dependency failure with @apply

### DISCUSSION THREAD

**Discussion by Poimen** [tailwindlabs/tailwindcss#8595] [Help] [answered]
We mostly work with web components using the StencilJS framework, which we have integrated Tailwind into (version 3.1.2). On some occasions we find that tailwind reports a circular dependency when using `@apply` that doesn't make much sense.

In the examples below, I have reduced the html/css to make it fit 👍 

In the example we have a web component (`omds-input-field-wrapper`) that is used as a sub-component of a bigger web component. The upper component uses inline classes to define some behaviour for the sub component:
```jsx
render() {
    const { isDisabled } = this;

    return (
      <Host>
        <omds-input-field-wrapper
          class={{
            'cursor-pointer': true,
            'cursor-auto pointer-events-none': isDisabled,
          }}
        />
      </Host>
    );
}
```

In order to affect some styling in the component `omds-input-field-wrapper` we use the `::part` selector in the upper components css:
```css
omds-input-field-wrapper::part(input-field) {
  @apply cursor-pointer;
}

omds-input-field-wrapper:not(.is-open)::part(input-field) {
  @apply cursor-pointer;
}
```

When the Stencil compiler runs, it generates a bunch of css (I have removed all the functional css and left the errant css):
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

/*!@omds-input-field-wrapper::part(input-field)*/
omds-input-field-wrapper.sc-omds-dropdown-field::part(input-field) {
  @apply cursor-pointer;
}

/*!@omds-input-field-wrapper:not(.is-open)::part(input-field)*/
omds-input-field-wrapper.sc-omds-dropdown-field:not(.is-open)::part(input-field) {
  @apply cursor-pointer;
}

/*!@.cursor-pointer*/
.cursor-pointer.sc-omds-dropdown-field {
  cursor: pointer
}
```

Here, the inline html classes have been created, and the `@apply` classes will be processed by Tailwind.

If you run this through the tailwind cli, it generates the error:
```
npx tailwindcss -i .\input.css -o .\output.css
C:\git\node_modules\.pnpm\postcss@8.4.14\node_modules\postcss\lib\input.js:148
      result = new CssSyntaxError(
               ^

CssSyntaxError: tailwindcss: C:\git\input.css:16:1: You cannot `@apply` the `cursor-pointer` utility here because it creates a circular dependency.
```

In this case it is pretty simple to revert to normal css, but I'm trying to understand the circular dependency reason. If I remove:
```css
.cursor-pointer.sc-omds-dropdown-field {
  cursor: pointer
}
```

then all works fine.

Is there any reason why Tailwind throws a circular dependency for this?

Thanks.
