### DISCUSSION TITLE
Cannot add component named according to the BEM methodology.

### DISCUSSION THREAD

**Discussion by polRk** [tailwindlabs/tailwindcss#8611] [Help]
**What version of Tailwind CSS are you using?**

"tailwindcss": "3.1.2",

**What build tool (or framework if it abstracts the build tool) are you using?**

vite": "2.9.12"

**What version of Node.js are you using?**

v18.0.0

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction URL**

If really need, i can add.

**Describe your issue**
I can not add component named according to the BEM methodology.

```js
const components = {
        '.field': {
            display: 'flex',
            width: theme('width.full'),
        },
        '.field-control': {
            padding: `0 ${theme('spacing.4')}`,
            width: theme('width.full'),
        },
        '.field-control > .switch': {
            marginLeft: 'auto',
        },
    }

    addComponents(components)
```

Result:

```css
.field {
  display: flex;
  width: 100%;
}
.\!field {
  display: flex !important;
  width: 100% !important;
}
.field-control > .switch {
  margin-left: auto;
}
```

https://en.bem.info/methodology/quick-start/
