### DISCUSSION TITLE
How to uniformly add a parent selector to the generated CSS rules

### DISCUSSION THREAD

**Discussion by Xdy1579883916** [tailwindlabs/tailwindcss#8627] [Ideas]
excuse me; When developing a chrome plugin, to prevent the injected style from affecting the host page, I need to specify that these CSS rules only affect the DOM I specify;

````css
*, ::before, ::after{
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  ...
}
.static{
  position: static;
}
.fixed{
  position: fixed;
}
.absolute{
  position: absolute;
}
.relative{
  position: relative;
}
.top-1{
  top: 4px;
}
.left-1{
  left: 4px;
}
.m-2{
  margin: 8px;
}
.mr-1{
  margin-right: 4px;
}
.mt-3{
  margin-top: 12px;
}
.mr-4{
  margin-right: 16px;
}
.mb-2{
  margin-bottom: 8px;
}
.ml-2{
  margin-left: 8px;
}
````
========= The above code will affect the global DOM ============

> If only I could provide a way to specify the parent container of these CSS rules

````css

.custom-dom *,.custom-dom ::before,.custom-dom ::after{
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  ...
}
.custom-dom .static{
  position: static;
}
.custom-dom .fixed{
  position: fixed;
}
.custom-dom .absolute{
  position: absolute;
}
.custom-dom .relative{
  position: relative;
}
.custom-dom .top-1{
  top: 4px;
}
.custom-dom .left-1{
  left: 4px;
}
.custom-dom .m-2{
  margin: 8px;
}
.custom-dom .mr-1{
  margin-right: 4px;
}
.custom-dom .mt-3{
  margin-top: 12px;
}
.custom-dom .mr-4{
  margin-right: 16px;
}
.custom-dom .mb-2{
  margin-bottom: 8px;
}
.custom-dom .ml-2{
  margin-left: 8px;
}

````

This is my idea. Maybe there are other better ideas. Please guide me
