### DISCUSSION TITLE
Custom colors with CSS variables seems not working

### DISCUSSION THREAD

**Discussion by ghost** [tailwindlabs/tailwindcss#8637] [Help]
Hello,

with the following css:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  @apply scroll-smooth antialiased;
}

@layer base {
  [data-theme="default"] {
    --background-primary: 0deg 0% 99%;
    --background-secondary: 0deg 0% 97.3%;
 }
}
```
and the config:

```javascript
     ...
     theme:
        extend: {
            backgroundColor: {
                primary: 'hsl(var(--background-primary) / <alpha-value>)',
                secondary: 'hsl(var(--backgroundColor-secondary) / <alpha-value>)',
            },
       } ...
```

```html 
<div className="bg-primary" data-theme="default">
   ...
</div> 
```

I can see via intellisense
```css
.bg-primary {
    --tw-bg-opacity: 1;
    background-color: hsl(var(--background-primary) / var(--tw-bg-opacity));
}
```
but the class is not generated in `output.css`
