### DISCUSSION TITLE
Automatically add display flex when flex-col or flex-row class is added

### DISCUSSION THREAD

**Discussion by MatissJurevics** [tailwindlabs/tailwindcss#8665] [Ideas]
I was thinking about how when you add the class "flex-col" or "flex-row"  to an element it doesn't automatically apply the flex property to that element. i.e.

**Currently**
```html
<div class="flex-row"></div> // has property flex-direction:row; but not display:flex;
```

**After**
```html
<div class="flex-row"></div> // Automatically adds both flex-direction:row; and display:flex;
```

I wouldn't mind trying to see if I could implement such a feature but I'm wondering if there is a reason why something like this isn't already done.

**Comment by rohmann** [comment]
I can see how this might feel more ergonomical at first, but unfortuntately I think there are some edge cases it creates that are difficult to disambiguate. If `flex-col` and `flex-row` gave you `display: flex;` but you started using variants like `md:*` e.g.

```html
<div class="flex-row md:flex-col"></div>
```

The CSS output would need to include `display: flex;` twice like this:
```css
.flex-row {
  display: flex;
  flex-direction: row;
}

@media (min-width: 768px) {
  .md\:flex-col {
    display: flex;
    flex-direction: column;
  }
}
```

And maybe you want to switch between grid and flexbox at different breakpoints? While probably not something you'd do every day, Tailwind should still allow it. Requiring an explicit class to set `display` helps the system remain un-opinionated in these situations.
