### DISCUSSION TITLE
[Prettier Plugin]

### DISCUSSION THREAD

**Discussion by clintongreen** [tailwindlabs/tailwindcss#8671] [Help]
Im using emberjs `ember-cli: 3.28.5` and I recently upgraded from Tailwindcss V2 to V3. I then installed the prettier plugin and ran `prettier --write .` to perform the class sorting. Surprisingly the plugin only affects `css` files in my project. I've looked but cannot find an obvious issue. Is there a problem with class sorting in handlebars(`.hbs`) files?

**Comment by thecrypticace** [comment]
Can you provide more details about your setup — for example your prettier config?

If you override the parser prettier uses for handlebars files to HTML the plugin picks up and re-sorts classes as expected.

You can add an `overrides` key to your `prettier.config.js` file (should work in package.json, `.prettierrc`, etc… — just with small syntax tweaks)
```js
module.exports = {
  // … clipped …
  overrides: [
    {
      files: '*.hbs',
      options: {
        parser: 'html',
      },
    },
  ],
}
```

**Reply by thecrypticace** [reply]
It's possible we may need to update the plugin to detect / allow sorting in handlebars files by default (if it's not a prettier limitation). I'll ask internally and see what I can find out.

**Reply by clintongreen** [reply]
Hi thanks for having a look, heres my `.prettierrc.yaml`, looks like the issue is Im using `glimmer` for my parser. I tried with `html` and that did allow the plugin to work on the handlebars files, thanks for the tip but it causes other issues. I believe the issue is that the plugin doesnt support `glimmer`, is there a way this could be supported, or could you suggest an alternative parser?
```
singleQuote: true
twConfig: 'app/tailwind/config.js' // adding this throws this error below
// [warn] Ignored unknown option { twConfig: "app/tailwind/config.js" }.
overrides:
  - files: '*.hbs'
    options:
      parser: 'glimmer'
      singleQuote: false
```
