### DISCUSSION TITLE
Text lines as new utility

### DISCUSSION THREAD

**Discussion by imMatheus** [tailwindlabs/tailwindcss#8730] [Ideas]
A proposal for a new utility class that would limit the number of lines a piece of text can take. 

Here is an example of how the code for the green box in the image underneath might look. Note that **text-lines-2** on the **p** tag is the new utility class. 

```html
<div className="w-60 rounded bg-green-200 p-4">
  <h2 className="text-xl font-bold">With line wrap</h2>
  <p className="text-lines-2 text-sm">
       Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus adipisci error commodi asperiores, site voluptate! Alias
  </p>
</div>
```
The implementation of this as for as how the **text-lines-2** CSS code would look, something like this would be my proposal.
```css
.text-lines-2 {
    overflow-wrap: break-word;
    text-overflow: ellipsis;
    white-space: unset;
    display: -webkit-box;
    overflow: hidden;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
}
```

Where **-webkit-line-clamp: 2;** is the thing that would vary depending on how many lines you would want. 

<img width="1393" alt="Screenshot 2022-06-28 at 14 12 48" src="https://user-images.githubusercontent.com/77362975/176175634-c9ff993a-1152-4164-8a13-7e76cebdde7b.png">

If this is something that the community would think would be valuable, I personally would love to give my first contribution to Tailwind and implement this myself.
