### DISCUSSION TITLE
User drag none utility class

### DISCUSSION THREAD

**Discussion by justingolden21** [tailwindlabs/tailwindcss#8733] [Ideas]
We have `select-none` but users can still drag ghost images. I think adding `drag-none` as a utility for:

```css
  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
  user-drag: none;
```

would be awesome. Thoughts?

See https://stackoverflow.com/a/32548403/4907950

**Comment by TelegramUsername** [comment]
I was looking for it in Tailwind, If it was added it would be helpful

**Comment by smithliam** [comment]
For now, you can [create your own plugin](https://tailwindcss.com/docs/plugins#adding-utilities) or use this:
https://www.npmjs.com/package/tailwindcss-addons
https://github.com/babakfp/tailwindcss-addons/tree/main/tailwindcss-addons

**Comment by TelegramUsername** [comment]
@adamwathan please consider this in TailwindCSS

**Comment by joranmulderij** [comment]
This should actually be part of TailwindCSS. `select-none` is there but `drag-none` is not. Seems inconsistent to me.

**Comment by justingolden21** [comment]
Just came into another use case for this and googled it and got back here lol. Any chance we can consider this feature?

**Comment by justingolden21** [comment]
Solution for now:

`tailwind.config.cjs`

```
const plugin = require('tailwindcss/plugin');

plugins: [
		plugin(function ({ addUtilities }) {
			addUtilities({
				'.drag-none': {
					'-webkit-user-drag': 'none',
					'-khtml-user-drag': 'none',
					'-moz-user-drag': 'none',
					'-o-user-drag': 'none',
					'user-drag': 'none'
				}
			});
		})
	]
```

https://tailwindcss.com/docs/plugins#adding-utilities

https://stackoverflow.com/a/32548403/4907950

**Reply by rozsazoltan** [reply]
From TailwindCSS v4:

```css
@utility drag-none {
  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
  user-select: none;
}
```

**Comment by adamwathan** [comment]
@justingolden21 Any reason to not use the `draggable` HTML attribute? That appears to the be standard way to handle this, with `-webkit-user-drag` being non-standard CSS that's not in the spec.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/4323180/225594466-3465ca2a-ab8a-4c08-8bf2-53474dd961c4.png">

**Reply by justingolden21** [reply]
Ooh good find, thank you!

**Comment by ZouicheOmar** [comment]
Used `pointer-events-none` on my img, worked for chrome and firefox

**Reply by EinfachHans** [reply]
Works, but you can't use click listeners anymore

**Reply by ecbalarain** [reply]
It worked like charm.

Suggestion: Combine it with `select-none` because the image is still selectable.

**Comment by MikeeNachtigall** [comment]
You can just use **[-webkit-user-drag:none]**, which is described [here](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties).

**Comment by miruji** [comment]
You can use draggable='false' for img or a. This works for me

**Comment by lymtu** [comment]
True, but we can solve this problem by creating exclusive class attribute

in root.css
```css
.user-drag-none {
  user-select: none;
  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
}
```

**Reply by rozsazoltan** [reply]
Using the [`@utility`](https://tailwindcss.com/docs/functions-and-directives#utility-directive) directive is much more convenient and provides more predictable results. You won't have any CSS specificity issues.

```css
@utility drag-none {
  user-select: none;
  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
}
```
