### DISCUSSION TITLE
How to extend existing class

### DISCUSSION THREAD

**Discussion by khafizinoh** [tailwindlabs/tailwindcss#8734] [Help]
I'm having trouble to understand on how to add properties to existing class.

Example: Current `min-h-screen` is defined as below:
```css
.min-h-screen {
  min-height: 100vh;
}
```

I want to add an additional property to cater the [notorious vh bug on mobile](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser) as below:
```css
.min-h-screen {
  min-height: 100vh;
  /* additional property */
  height: calc(var(--vh, 1vh) * 100);
}
```

How do I extend existing class property? I've tried to follow the documentation and made my `tailwind.config.js` as below:
```js
theme: {
        extend: {
            minHeight: {
                'screen': 'calc(var(--vh, 1vh) * 100)',
            }
        }
    },
```

However, when the css file is render, `min-h-screen` is override instead as below:
```css
.min-h-screen {
  min-height: calc(var(--vh, 1vh) * 100);
}
```

How do I add property as I intended without overriding current class property?

## Edit

I've update my `tailwind.config.js` as below:
```css
theme: {
        extend: {
            minHeight: {
                'screen': ['100vh', 'calc(var(--vh, 1vh) * 100)'],
            }
        }
    },
```

And it produces the result as intended. However is this the correct method to do it?
