### DISCUSSION TITLE
Are `addDefaults` and `@defaults` stable to use?

### DISCUSSION THREAD

**Discussion by wongjn** [tailwindlabs/tailwindcss#8747] [Help]
I see that there are features within Tailwind used to add default CSS variable values to the `*, ::before, ::after` selector:

```css
*, ::before, ::after {
  --tw-border-spacing-x: 0;
  --tw-border-spacing-y: 0;
  ...
}
```

After looking at how this was done in the core plugins, I can see that there is usage of `@defaults`, i.e.:

```css
@defaults my-group {
  --tw-my-value: 0;
}
```

Or `addDefaults` in the plugin API:

```js
const plugin = require('tailwindcss/plugin');
module.exports = plugin(({ addDefaults }) => {
  addDefaults('my-group', {
    '--tw-my-value': 0,
  });
});
```

However, these aspects of Tailwind are not documented and `addDefaults` is not included in the type information, so I'm just wondering if these can be used publicly, or are they private features and subject to change without notice?
