### DISCUSSION TITLE
transformThemeValue not being applied in some cases

### DISCUSSION THREAD

**Discussion by kombucha** [tailwindlabs/tailwindcss#8755] [Help]
Hi there 👋 ,

This might or might not be a bug, but at least it was surprising behaviour for me!

The following code (which is a simplified example of what I have in my code base):

`tailwind.config.js`

```js
module.exports = {
  content: [{ raw: 'display-code display-buggy-code' }],
  theme: {
    fontFamily: {
      mono: [
        'Fira Code',
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ],
    },
    extend: {},
  },
  plugins: [require('./typography.plugin')],
};
```

`typography.plugin.js`

```js
const plugin = require('tailwindcss/plugin');

module.exports = plugin(
  ({ theme, addComponents }) => {
    addComponents({
      '.display-buggy-code': {
        fontFamily: theme('typography.code.fontFamily'),
      },
      '.display-code': {
        fontFamily: theme('fontFamily.mono'),
      },
    });
  },
  {
    content: [],
    theme: {
      typography: ({ theme }) => ({
        code: {
          fontFamily: theme('fontFamily.mono'),
        },
      }),
    },
  }
);
```

Will generate the following output:

```css
.display-buggy-code {
  font-family: Fira Code;
  font-family: Menlo;
  font-family: Monaco;
  font-family: Consolas;
  font-family: Liberation Mono;
  font-family: Courier New;
  font-family: monospace;
}

.display-code {
  font-family: Fira Code, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace;
}
```

Two surprising things for me:
1. Depending on where `theme('fontFamily.mono')` is called, it will either be [serialized to a `string` already](https://github.com/tailwindlabs/tailwindcss/blob/50bed74cdc5c0b6f55f141aa580d1c314d477db0/src/util/transformThemeValue.js#L29) or remain an `array`.
2. If it's still an array, it will generate multiple instances of the CSS declaration (maybe that's desirable sometimes?)

WDYT, is that expected behaviour?
