### DISCUSSION TITLE
border hover effect

### DISCUSSION THREAD

**Discussion by Chandler-Zhu** [tailwindlabs/tailwindcss#8764] [Help] [answered]
I came across this codepen: https://codepen.io/sarath-ar/pen/dMKxxM and I wonder what is the best strategy to recreate this effect(the `btn-1`) in tailwind. Also a newbie question: why do they set  `position: absolute` but not having any `top`/`right`/`bottom`/`left` property set ? Will it just stay at the top left corner?
```css
span::before, span::after{
  content:"";
  width:2px;
  height:0;
  position: absolute;
  transition: all 0.2s linear;
  background: #fff;
}
```
