### DISCUSSION TITLE
What does --tw-content mean in preflight.css?

### DISCUSSION THREAD

**Discussion by nareshbhatia** [tailwindlabs/tailwindcss#8931] [Help] [answered]
I don't understand what `--tw-content` means here. Can someone please explain?

https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L15-L18

```css
::before,
::after {
  --tw-content: '';
}
```
