### DISCUSSION TITLE
Counteracting utilities on bigger screens

### DISCUSSION THREAD

**Discussion by Redskinsjo** [tailwindlabs/tailwindcss#8933] [Help] [answered]
Need quick help on this.
I should have this image that grow up every custom breakpoint I made.

```js
screens: {
      web: '1279px',
      web2: '829px',
      mobile: '689px',
      mobile2: '563px',
      mobile3: '469px'
    },
```

So I added utilities to my image like this:

```html
<Image
            src={'/../public/hero.png'}
            width={400}
            height={350}
            className='absolute z-0 w-[120px] h-[105px] mobile3:media-mobile3-hero-image mobile2:media-mobile2-hero-image web2:media-web2-hero-image web:media-web-hero-image '
          />
```

each utility being a component

```css
.media-web-hero-image {
    width: 350px;
    height: 400px;
  }
  .media-web2-hero-image {
    width: 320px;
    height: 280px;
  }
  .media-mobile2-hero-image {
    width: 240px;
    height: 210px;
  }
  .media-mobile3-hero-image {
    width: 160px;
    height: 140px;
  }
```

my image grows up to media-mobile3-hero-image component sizes
but stops there, and does not when setting bigger screens...

I can found the classes into the browser but CSS only takes the first media query class (media-mobile3-hero-image)

Thanks for help
