### DISCUSSION TITLE
before: class auto overrides existing before class

### DISCUSSION THREAD

**Discussion by mdrahiem** [tailwindlabs/tailwindcss#8983] [Help]
I have a scenario where I have a font class 
`.icon80 {
  &::before {
    color: $cIconFont;
    content: $iconDbsIconsOutlines80;
  }
}`

I want to add tailwind class along with the above class. For example,
`<div className="icon80 before:text-lg"/>` in this case, tailwind's `before` class overrides my existing `before` class. Is there any way to resolve this?

**Comment by wongjn** [comment]
I can think of some options:

## Option 1a

Use `--tw-content` property instead of `content` in the class and ensure it is *after* `@tailwind base`, i.e.

```css
@tailwind base;

.icon80 {
  &::before {
    color: $cIconFont;
    --tw-content: $iconDbsIconsOutlines80;
  } 
}

@tailwind components;
@tailwind utilities;
```

It needs to go after `@tailwind base` since we need to override this rule that is in Tailwind's preflight (their CSS reset) that is printed in the Tailwind base layer:

```css
::before,
::after {
  --tw-content: '';
}
```

We override `--tw-content` property as this is used as the `content` property of `before` variant classes, i.e:

```css
.before\:text-lg::before {
  content: var(--tw-content);
  font-size: 1.125rem;
  line-height: 1.75rem;
}
```

## Option 1b

Similar to 1a, but pop it in `@layer utilities` so that it would also override the preflight styles:

```css
@layer utilities {
  .icon80 {
    /* … */
  }
}
```

## Option 2

You can "brute force" it by putting the `.icon80` class declaration after all Tailwind classes so that it takes precendence.
