### DISCUSSION TITLE
Work border utils fine without Preflight

### DISCUSSION THREAD

**Discussion by k-utsumi** [tailwindlabs/tailwindcss#8984] [Ideas]
I want an option to use border easily without `Preflight`.
When the option is turned on,
it changes the [`border-width`](https://tailwindcss.com/docs/border-width)'s CSS property to `border` and sets `border-style` and `border-color` together.

<details>
<summary>Example CSS results</summary>

```
.border-0 { border: 0 }
.border { border: solid 1px theme('borderColor.DEFAULT', currentColor) }
.border-2 { border: solid 2px theme('borderColor.DEFAULT', currentColor) }
...
.border-t-0 { border-top: 0 }
.border-t { border-top: solid 1px theme('borderColor.DEFAULT', currentColor) }
.border-t-2 { border-top: solid 4px theme('borderColor.DEFAULT', currentColor) }
...
... Border color classes
... Border style classes 
```
</details>

The behavior is the same or close to Bootstrap.
https://getbootstrap.com/docs/5.2/utilities/borders/#border

### Border base style not available for Some projects

[`Preflight`](https://tailwindcss.com/docs/preflight) cannot be turned on when adding Tailwind CSS to an existing older project.
Also, the border base style cannot be added as well, since the buttons with no style applied have changed in appearance.

<kbd> ![image](https://user-images.githubusercontent.com/13148112/181738847-514aaffa-d61e-4aca-b776-ba46d731d22e.png)

<details>
<summary>Border base style</summary>

```css
*,
::before,
::after {
  border-width: 0;
  border-style: solid;
  border-color: theme('borderColor.DEFAULT', currentColor);
}
```

**Comment by k-utsumi** [comment]
As a temporary solution, I solved it by applying a style to `tw-border`.
Because older projects generally need a prefix.

```scss
// tailwind.scss
@layer components { // NOTE: set layer if required
  :where( // for Adjust Specificity
    [class*="tw-border"],
    [class*="tw-border"]::before,
    [class*="tw-border"]::after,
    [class*="tw-divide"] > *
  ) {
    border: solid 0 theme("borderColor.DEFAULT");

  }
}
```

<details>
<summary>old</summary>

```scss
// tailwind.scss
@layer components { // NOTE: set layer if required
  [class*="tw-border"],
  [class*="tw-border"]::before,
  [class*="tw-border"]::after,
  [class*="tw-divide"] > * {
    border: solid 0 theme("borderColor.DEFAULT");
  }
}
```
