### DISCUSSION TITLE
Add `overflow-undercover`

### DISCUSSION THREAD

**Discussion by ghost** [tailwindlabs/tailwindcss#9051] [Ideas]
Sometimes I need to hide the scrollbar but keep the functionality
These classes might be helpful
```css
.overflow-undercover {
  -ms-overflow-style: none;  /* IE 10+ */
  scrollbar-width: none;  /* Firefox */

   &::-webkit-scrollbar { 
    display: none;  /* Safari & Chrome */
  }
}
```
Note: not tested so much, but seems to work
