### DISCUSSION TITLE
Improving bundle size by replacing/removing CSS variable names with their actual values, when the variable name character count is greater than the value's character count

### DISCUSSION THREAD

**Discussion by phoenisx** [tailwindlabs/tailwindcss#9124] [Ideas]
I am not sure if this is possible, since I don't know `tailwindcss`s inner details.
I raised this issue because I feel this can significantly reduce the generated CSS bundle sizes.

## Suggestion
Please check this [repro](https://play.tailwindcss.com/ZI2MgigsvD?file=css), where the generated CSS file contains a lot of CSS variables, which adds to the generated CSS bundle size.

If we can replace CSS variables with their values instead, only if their text length is greater than their value's text length, the generated output would be much smaller:

E.g.

### This 
```css
.test {
  --tw-bg-opacity: 1;
  background-color: rgb(248 250 252 / var(--tw-bg-opacity));
  --tw-text-opacity: 1;
  color: rgb(15 23 42 / var(--tw-text-opacity));
}

@media (prefers-color-scheme: dark) {
  .test {
    --tw-bg-opacity: 1;
    background-color: rgb(15 23 42 / var(--tw-bg-opacity));
    --tw-text-opacity: 1;
    color: rgb(248 250 252 / var(--tw-text-opacity));
  }
}
```

### Becomes this

```css
.test {
  background-color: rgb(248 250 252 / 1);
  color: rgb(15 23 42 / 1);
}

@media (prefers-color-scheme: dark) {
  .test {
    background-color: rgb(15 23 42 / 1);
    color: rgb(248 250 252 / 1);
  }
}
```

The result has 176 fewer characters.

## CSSNano

I googled if this can be achieved using a minifier, but didn't find any proper solutions. There are some [open issues](https://github.com/cssnano/cssnano/issues/911) for this, but I feel removing CSS variables using post-processing can be tricky.

If `tailwindcss` doesn't generate such CSS variables, in the first place, post-processing won't be required for this anyways.

This feature can be behind a config toggle, if the devs want to optimize their builds.

> P.S: Thanks for this wonderful library 🎉
