### DISCUSSION TITLE
Tailwind container meet bootstrap ones

### DISCUSSION THREAD

**Discussion by ahmedmymail** [tailwindlabs/tailwindcss#9140] [Ideas]
Hello, 
I want to use Tailwind container with same breakpoints and max-width values as bootstrap
Any idea about this?
Thank in advance

**Comment by wongjn** [comment]
## Assumptions

- Emulate the latest Bootstrap's (`v5.2`) container component
- Default Bootstrap settings
- We can't use the [Tailwind's `container`](https://tailwindcss.com/docs/container) since the max-widths for it is the same as the breakpoints but Bootstrap's container widths are slightly smaller.
- We'll use the preferred strategy in Tailwind of using utilities straight in the HTML, and not creating component classname(s).

## Breakpoints 

First we need to port the [breakpoints](https://getbootstrap.com/docs/5.2/layout/breakpoints/#available-breakpoints) since the container will change from `width: 100%` to its max width at these points. We can replace Tailwind's breakpoints or we can extend them. If we do extend but also want to keep reference to Bootstrap's breakpoint names, we'll need some prefix to avoid clashes with Tailwind keys. So here and throughout, I'll be using the prefix `bs` that Bootstrap itself uses.

### [Replace](https://tailwindcss.com/docs/screens#overriding-the-defaults)

Replacing is the more straight-forward, since we can pretty much copy-paste from Bootstrap:

```js
module.exports = {
  theme: {
    screens: {
      // Don't need xs since Tailwind uses min-width approach
      // to its media queries.
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
      xxl: '1400px',
    },
  },
};
```

### Extend

With extending, we have to interweave the Bootstrap breakpoints with Tailwind's since ["breakpoints need to be sorted from smallest to largest in order to work as expected with a min-width breakpoint system"](https://tailwindcss.com/docs/screens#adding-smaller-breakpoints):

```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  theme: {
    screens: {
      // Don't need `xs` since Tailwind uses min-width approach
      // to its media queries.
      'bs-sm': 576px,
      sm: defaultTheme.screens.sm, // 640px
      // Bootstrap's `md` is the same as Tailwind's `md` but
      // added here as an alias so we can be consistent.
      'bs-md': 768px, 
      md: defaultTheme.screens.md, // 768px
      'bs-lg': 992px,
      lg: defaultTheme.screens.lg, // 1024px
      'bs-xl': 1200px,
      xl: defaultTheme.screens.xl, // 1280px
      'bs-xxl': 1400px,
      '2xl': defaultTheme.screens['2xl'], // 1536px
    },
  },
};
```

## Max width

Assign Bootstrap container max-widths to [Tailwind's `max-width` utility](https://tailwindcss.com/docs/max-width). Again, we can extend or replace, but we don't need to worry about order (as compared to the breakpoints earlier). We'll also convert to `rem` unit to be in keeping with Tailwind.

### Replace

```js
module.exports = {
  theme: {
    screens: {
      // …
    },
    extend: {
      maxWidth: {
        sm: `${540 / 16}rem`,
        md: `${720 / 16}rem`,
        lg: `${960 / 16}rem`,
        xl: `${1140 / 16}rem`,
        xxl: `${1320 / 16}rem`,
      }
    },
  },
};
```
### Extend

```js
module.exports = {
  theme: {
    screens: {
      // …
    },
    extend: {
      maxWidth: {
        'bs-sm': `${540 / 16}rem`,
        'bs-md': `${720 / 16}rem`,
        'bs-lg': `${960 / 16}rem`,
        'bs-xl': `${1140 / 16}rem`,
        'bs-xxl': `${1320 / 16}rem`,
      },
    },
  },
};
```

## Base styling

All the container classes in Bootstrap have this styling:

```css
.container, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl
  --bs-gutter-x: 1.5rem;
  --bs-gutter-y: 0;
  width: 100%;
  padding-right: calc(var(--bs-gutter-x) * .5);
  padding-left: calc(var(--bs-gutter-x) * .5);
  margin-right: auto;
  margin-left: auto;
}
```

So we can convert to Tailwind utility classes as follows.

<table>
<thead>
<tr>
<th>Bootstrap CSS declaration</th>
<th>Tailwind Class</th>
</tr>
<tbody>
<tr>
<td>

```css
width: 100%;
```

</td>
<td>

`w-full`

</td>
</tr>
<tr>
<td>

```css
--bs-gutter-x: 1.5rem;
padding-right: calc(var(--bs-gutter-x) * .5);
padding-left: calc(var(--bs-gutter-x) * .5);
```

</td>
<td>

`px-3`

</td>
</tr>
<tr>
<td>

```css
margin-right: auto;
margin-left: auto;
```

</td>
<td>

`mx-auto`

</td>
</tr>
</tbody>
</table>

So every container will have the classes `w-full px-3 mx-auto`.

## Putting it all together

| Bootstrap | Tailwind (replace) | Tailwind (extend) |
| --- | --- | --- |
| `container` | `w-full px-3 mx-auto sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl xxl:max-w-xxl` | `w-full px-3 mx-auto bs-sm:max-w-bs-sm bs-md:max-w-bs-md bs-lg:max-w-bs-lg bs-xl:max-w-bs-xl bs-xxl:max-w-bs-xxl` |
| `container-sm` | `w-full px-3 mx-auto sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl xxl:max-w-xxl` | `w-full px-3 mx-auto bs-sm:max-w-bs-sm bs-md:max-w-bs-md bs-lg:max-w-bs-lg bs-xl:max-w-bs-xl bs-xxl:max-w-bs-xxl` |
| `container-md` | `w-full px-3 mx-auto md:max-w-md lg:max-w-lg xl:max-w-xl xxl:max-w-xxl` | `w-full px-3 mx-auto bs-md:max-w-bs-md bs-lg:max-w-bs-lg bs-xl:max-w-bs-xl bs-xxl:max-w-bs-xxl` |
| `container-lg` | `w-full px-3 mx-auto lg:max-w-lg xl:max-w-xl xxl:max-w-xxl` | `w-full px-3 mx-auto bs-lg:max-w-bs-lg bs-xl:max-w-bs-xl bs-xxl:max-w-bs-xxl` |
| `container-xl` | `w-full px-3 mx-auto xl:max-w-xl xxl:max-w-xxl` | `w-full px-3 mx-auto bs-xl:max-w-bs-xl bs-xxl:max-w-bs-xxl` |
| `container-xxl` | `w-full px-3 mx-auto xxl:max-w-xxl` | `w-full px-3 mx-auto bs-xxl:max-w-bs-xxl` |
| `container-fluid` | `w-full px-3 mx-auto` | `w-full px-3 mx-auto` |

Here's an [example Tailwind Play](https://play.tailwindcss.com/uA1Mgly1xL) using the replace technique, with the Bootstrap version to compare.

**Reply by liam-ng** [reply]
Thank you for the solution!
I also put the styles in @layer directive, so that I can use (tw-)container like an alias, makes it less bloated.
```css
@layer utilities {
    .tw-container {
        @apply xxl:tw-max-w-xxl tw-mx-auto tw-w-full tw-px-3 sm:tw-max-w-sm md:tw-max-w-md lg:tw-max-w-lg xl:tw-max-w-xl;
    }
}
```
In the html, add `className='tw-container'`

**Comment by nstuyvesant** [comment]
@wongjn - Great solution. I am trying to replicate this with TailwindCSS 4.0 beta 8.  I'm getting stuck on translating the configuration above to 4.0 in combination with the use of a prefix and disabling preflight.

Here is my app.css...
```css
@layer theme, base, components, utilities;
@import 'tailwindcss/theme' layer(theme) prefix(tw);
@import 'tailwindcss/utilities' layer(utilities) prefix(tw);

@theme {
	--font-sans: 'Avenir', 'Myriad Pro', 'Helvetica Neue', sans-serif;
	--color-plum: oklch(45.31% 0.0979 300.21);
	--color-lilac: oklch(81.77% 0.0435 303.58);
	--color-error: var(--color-red-500);

	--breakpoint-bs-sm: calc(540 / 16) rem;
	--breakpoint-bs-md: calc(720 / 16) rem;
	--breakpoint-bs-lg: calc(960 / 16) rem;
	--breakpoint-bs-xl: calc(1140 / 16) rem;
	--breakpoint-bs-xxl: calc(1320 / 16) rem;

	--width-screen-bs-sm: var(--breakpoint-bs-sm);
	--width-screen-bs-md: var(--breakpoint-bs-md);
	--width-screen-bs-lg: var(--breakpoint-bs-lg);
	--width-screen-bs-xl: var(--breakpoint-bs-xl);
	--width-screen-bs-xxl: var(--breakpoint-bs-xxl);
}

@layer utilities {
	.shy-container {
		@apply tw:w-full tw:px-3 tw:mx-auto tw:bs-sm:max-w-bs-sm tw:bs-md:max-w-bs-md tw:bs-lg:max-w-bs-lg tw:bs-xl:max-w-bs-xl tw:bs-xxl:max-w-bs-xxl;
	}
}
```

Any thoughts on where I'm going wrong?

**Reply by dvzrd** [reply]
A few things wrong with this:

- @apply doesn't work in v4. You have to write out your css rules instead using variables from theme or base
- you can't define custom variables inside @theme, you have to do that inside a base layer, assigned to :root - you can only add variables with a specific prefix inside theme (https://tailwindcss.com/docs/v4-beta#namespace-reference)

```css
@layer base {
  --width-screen-bs-sm: var(--breakpoint-bs-sm);
  --width-screen-bs-md: var(--breakpoint-bs-md);
  --width-screen-bs-lg: var(--breakpoint-bs-lg);
  --width-screen-bs-xl: var(--breakpoint-bs-xl);
  --width-screen-bs-xxl: var(--breakpoint-bs-xxl);
}
```

```css
@layer utilities {
  .shy-container {
    width: 100%;
    padding-inline: 0.75rem;
    margin-inline: auto;
    max-width: var(--breakpoint-bs-sm)
  }
}
``` 

Some things to consider:

- If you want to use var(--spacing-3) for padding, you will not be able to use dynamic spacing variable. You would have to manually define a bunch of --spacing-{x} values in your theme to use spacing variables in your css.
- I think you're trying to adjust the max-width value based on the media query breakpoint so you don't need to redefine new width-screen variables if that is the case. You just need to use the breakpoint variables with media queries using the theme function like this:

```css
.shy-container {
   max-width: var(--breakpoint-bs-sm);
   
   @media (min-width: theme(--breakpoint-bs-md)) {
    max-width: var(--breakpoint-bs-md);
   }
   
   ...
}
```

You may need to create your own screen variants for the boostrap breakpoints using the @variant method/function or just override the existing ones. Not really sure about this though, I haven't had much luck getting variants to work properly yet. See docs here: https://tailwindcss.com/docs/v4-beta#adding-custom-variants

**Reply by nstuyvesant** [reply]
Thanks for this reply. From what I'm seeing, `@apply` appears to work in the config (perhaps a new capability?). For example, this works...
```css
@layer theme, base, components, utilities;
@import 'tailwindcss/theme' layer(theme) prefix(tw);
@import 'tailwindcss/utilities' layer(utilities) prefix(tw);

@theme {
	--font-sans: 'Avenir', 'Myriad Pro', 'Helvetica Neue', sans-serif;
	--color-plum: oklch(45.31% 0.0979 300.21);
	--color-lilac: oklch(81.77% 0.0435 303.58);
	--color-error: var(--color-red-500);
}

@layer utilities {
	.shy-container {
		@apply tw:w-full tw:px-3 tw:mx-auto;
	}
}
```

I inspected my div.shy-container and saw...
```css
.shy-container {
    margin-inline: auto;
    width: 100%;
    padding-inline: calc(var(--tw-spacing)* 3);
}
```
What it choked on was `tw:bs-sm:max-w-bs-sm`.

**Reply by nstuyvesant** [reply]
This version does not error...
```css
@layer theme, base, components, utilities;
@import 'tailwindcss/theme' layer(theme) prefix(tw);
@import 'tailwindcss/utilities' layer(utilities) prefix(tw);

@theme {
	--font-sans: 'Avenir', 'Myriad Pro', 'Helvetica Neue', sans-serif;
	--color-plum: oklch(45.31% 0.0979 300.21);
	--color-lilac: oklch(81.77% 0.0435 303.58);
	--color-error: var(--color-red-500);

	--breakpoint-bs-sm: calc(540 / 16)rem;
	--breakpoint-bs-md: calc(720 / 16)rem;
	--breakpoint-bs-lg: calc(960 / 16)rem;
	--breakpoint-bs-xl: calc(1140 / 16)rem;
	--breakpoint-bs-xxl: calc(1320 / 16)rem;

	--container-bs-sm: var(--tw-breakpoint-bs-sm);
	--container-bs-md: var(--tw-breakpoint-bs-md);
	--container-bs-lg: var(--tw-breakpoint-bs-lg);
	--container-bs-xl: var(--tw-breakpoint-bs-xl);
	--container-bs-xxl: var(--tw-breakpoint-bs-xxl);
}

@layer utilities {
	.shy-container {
		@apply tw:w-full tw:px-3 tw:mx-auto tw:bs-sm:max-w-bs-sm tw:bs-md:max-w-bs-md tw:bs-lg:max-w-bs-lg tw:bs-xl:max-w-bs-xl tw:bs-xxl:max-w-bs-xxl;
	}
}
```
But it does not set the max widths - only the first 3 utility classes work.

**Reply by dvzrd** [reply]
Good to know @apply worked, I was having issues with it trying to apply an import, I guess it only works with existing tailwind utilities only

You should open your stylesheet in dev tools and see if your utilities exist. Maybe the max-w utility didn't register the new breakpoint? Try your screen variant with padding to see if it works `tw:bs-xl:px-6`. Sorry bro, not too sure about how width is set, but I'm guessing it's tied to --spacing

**Reply by wongjn** [reply]
You can make a Bootstrap container without any configuration as per [this Tailwind Play](https://play.tailwindcss.com/cP2ZCOVie2) (you can now do this in v3 too).

---
As an aside, Adam Wathan (creator of Tailwind) does seem to advocate avoiding `@apply`:
- https://twitter.com/adamwathan/status/1226511611592085504
- https://twitter.com/adamwathan/status/1559250403547652097

**Reply by nstuyvesant** [reply]
Thanks everyone for the guidance! Wanted to share that this works...
```css
@layer theme, base, components, utilities;
@import 'tailwindcss/theme' layer(theme) prefix(tw);
@import 'tailwindcss/utilities' layer(utilities) prefix(tw);

@theme {
	--font-sans: 'Avenir', 'Myriad Pro', 'Helvetica Neue', sans-serif;
	--color-plum: oklch(45.31% 0.0979 300.21);
	--color-lilac: oklch(81.77% 0.0435 303.58);
	--color-error: var(--color-red-500);

	/* Not used yet */
	--breakpoint-bs-sm: calc(576rem / 16);
	--breakpoint-bs-md: calc(768rem / 16);
	--breakpoint-bs-lg: calc(992rem / 16);
	--breakpoint-bs-xl: calc(1200rem / 16);
	--breakpoint-bs-xxl: calc(1400rem / 16);

	--container-bs-sm: calc(540rem / 16);
	--container-bs-md: calc(720rem / 16);
	--container-bs-lg: calc(960rem / 16);
	--container-bs-xl: calc(1140rem / 16);
	--container-bs-xxl: calc(1320rem / 16);
}

@layer utilities {
	.shy-container {
		@apply tw:w-full tw:px-3 tw:mx-auto tw:min-[576px]:max-w-bs-sm tw:min-[768px]:max-w-bs-md tw:min-[992px]:max-w-bs-lg tw:min-[1200px]:max-w-bs-xl tw:min-[1400px]:max-w-bs-xxl;
	}
}
```
As you can see, I created --container-* CSS properties that I used for the max-w-* utilities. The utility class min-* does not appear to use the --breakpoint-* CSS properties.

My objective is to not only get a working Bootstrap-like container but also be able to use Bootstrap breakpoints for other purposes. Any thoughts as to what I need to do?

Saw that @apply is not recommended so I may create a Container.svelte so I can reuse it without the verbosity.

**Reply by wongjn** [reply]
You don't need to prefix the breakpoints with `min-*`. Also bear in mind, you should resolve the `calc()` expressions manually and write in the result. It seems Tailwind sorts them alphabetically otherwise, causing the wrong order.

https://play.tailwindcss.com/L52JvxVCMF

**Comment by nstuyvesant** [comment]
Thank you @wongjn for taking the time to clarify this! This is my first time using TailwindCSS which is why I wanted to start with 4.0 beta.

Here's my semi-final config (will take out the @apply once I create a component). The upside is that it shows what the utility classes look like with the custom breakpoints and containers.

```css
@layer theme, base, components, utilities;
@import 'tailwindcss/theme' layer(theme) prefix(tw);
@import 'tailwindcss/utilities' layer(utilities) prefix(tw);

@theme {
	--font-sans: 'Avenir', 'Myriad Pro', 'Helvetica Neue', sans-serif;
	--color-plum: oklch(45.31% 0.0979 300.21);
	--color-lilac: oklch(81.77% 0.0435 303.58);
	--color-error: var(--color-red-500);

	--breakpoint-bs-sm: 29.75rem; /* 476px */
	--breakpoint-bs-md: 48rem; /* 768px */
	--breakpoint-bs-lg: 62rem; /* 992px */
	--breakpoint-bs-xl: 75rem; /* 1200px */
	--breakpoint-bs-xxl: 87.5rem; /* 1400px */

	--container-bs-sm: 33.75rem; /* 540rem */
	--container-bs-md: 45rem; /* 720px */
	--container-bs-lg: 60rem; /* 960px */
	--container-bs-xl: 71.25rem; /* 1140px */
	--container-bs-xxl: 82.5rem; /* 1320px */
}

@layer utilities {
	.shy-container {
		@apply tw:mx-auto tw:w-full tw:px-3 tw:bs-sm:max-w-bs-sm tw:bs-md:max-w-bs-md tw:bs-lg:max-w-bs-lg tw:bs-xl:max-w-bs-xl tw:bs-xxl:max-w-bs-xxl;
	}
}
```
