### DISCUSSION TITLE
Function dark() similar to screen()

### DISCUSSION THREAD

**Discussion by danon** [tailwindlabs/tailwindcss#9164] [Ideas]
You can read here https://tailwindcss.com/docs/functions-and-directives#screen of function `screen()` which you can use in your styles to add styles for certain screens. You can also add `@screen`, which is described here https://v1.tailwindcss.com/docs/functions-and-directives#screen to do the same.

I'm missing a feature, similar to this one, but for adding styles in dark and light mode. Tailwind supports dark mode with `dark:` variant, and you can enable it in `tailwind.config.js` to be either `'class'` or `'media'`.

It would be cool to do something like

```css
@dark {
  div { color: white; }
}

@light {
  div { color: black; }
}
```
or
```css
@theme dark {
  div { color: white; }
}

@theme light {
  div { color: black; }
}
```

I know I can write my own media query for dark mode, but it won't be the same as `dark:` variant (since that depends on `tailwind.config.js`).
