### DISCUSSION TITLE
How will I automate tailwind's build process on my workflow file?

### DISCUSSION THREAD

**Discussion by 96312** [tailwindlabs/tailwindcss#9201] [Help]
### Hello all, I am using tailwindcss for the first time and I am stuck at the build process.

**Demo Project:** hugo with tailwindcss  
**Objective:** I want the workflow file on github actions to automate the build part of the css when I push to `[main]` before my `hugo` action builds the site and deploys it.  
**Problem:** I can't find any docs to help me set that specific step up.

### What I've tried so far?  
My `package.json` file has these lines for local and build purposes that work well:
```
"scripts": {
    "build": "npx tailwindcss -i ./static/input.css -o ./static/output.css",
    "watch": "npx tailwindcss -i ./static/input.css -o ./static/output.css --watch"
  }
```

> tailwindcss.config.js is configured exactly how it's outlined on the official installation page:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['content/**/*.md', 'layouts/**/*.html'],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

> The relevant portion of my workflow file is this (for your reference):

```
name: push build deploy
"on":
  push:
    branches:
      - main

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout begins
        uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm run build
      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.78.2"
      - name: Clean public directory
        run: rm -rf public
     [...] 
```

Any suggestions to help me figure this will be appreciated! Thank you.
\- Joe
