### DISCUSSION TITLE
How to translate the CSS generated by tailwindcss again?

### DISCUSSION THREAD

**Discussion by lihanspace** [tailwindlabs/tailwindcss#9255] [Help] [answered]
I use [`postcss-px-to-viewport-8-plugin`](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin) to rewrite `rpx` to `vw`, 100vw=750rpx.

[`postcss-px-to-viewport-8-plugin`](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin) is based on [`postcss-px-to-viewport`](https://github.com/evrone/postcss-px-to-viewport) and is suitable for [`postcss@^8.3.8`](https://github.com/postcss/postcss)

But I don't know how to use `postcss-px-to-viewport-8-plugin` to translate the CSS generated by `tailwindcss`

The results I want, for example:

input

```css
/* w-[750rpx] */
.w-\[750rpx\] {
  width: 750rpx;
}
```

output

```css
.w-\[750rpx\] {
  width: 100vw;
}
```

or

```css
.w-\[100vw\] {
  width: 100vw;
}
```
