### DISCUSSION TITLE
Dark mode custom selector clashing with prefix?

### DISCUSSION THREAD

**Discussion by TobbenTM** [tailwindlabs/tailwindcss#9295] [Help]
I'm wondering how the custom selector for dark mode class is supposed to work.

According to this documentation page, we should be able to use a custom class: https://tailwindcss.com/docs/dark-mode#customizing-the-class-name
And I would personally expect that to actually be custom, not subject to the tailwind prefix used?

Take a look at this playground: https://play.tailwindcss.com/OvQ91uY3yi

In this config I've set a custom selector for the dark mode class:

```javascript
module.exports = {
  content: ["./src/**/*.{html,js,vue}"],
  prefix: 'tw-',
  darkMode: ['class', '.night'],
  safelist: ['night']
}
```

I would expect Tailwind to generate a rule to respect the custom selector without adding prefix, but it's not doing that, it's adding the prefix, even after safelisting it:

```css
.tw-night .dark\:tw-text-white {
  --tw-text-opacity: 1;
  color: rgb(255 255 255 / var(--tw-text-opacity));
}
```

Is this a bug? Or is there any other way to "escape" the prefix for this class lookup?
