### DISCUSSION TITLE
Override individual form elements not possible when also overriding in @layer base?

### DISCUSSION THREAD

**Discussion by SHxKM** [tailwindlabs/tailwindcss#9301] [Help] [answered]
I'm using the excellent forms plugin.

My `styles.scss` file:

```
@tailwind base;
@tailwind components;
@tailwind utilities;


@layer base {
  input[type='text'],
  input[type='password'],
  input[type='email'],
  input[type='number'],
  input[type='url'],
  input[type='date'],
  input[type='datetime-local'],
  input[type='month'],
  input[type='week'],
  input[type='time'],
  input[type='search'],
  input[type='tel'],
  input[type='checkbox'],
  input[type='radio'],
  select,
  select[multiple],
  textarea {
      @apply shadow;
      @apply border border-zinc-600;
      @apply rounded-lg;
      @apply hover:outline-none hover:border-green-400;
      @apply focus:outline-none focus:ring-green-400 focus:ring-1 focus:border-green-400;
  }
}
```

My input `checkbox` item:

```
            <form>
                <input type="checkbox" name="notify" class="rounded-sm" id="id_notify" checked="">
            </form>
```

But I can see that `rounded-lg` from `styles.scss` is overriding the specific element's `rounded-sm`, due to it being more specific (?).

Is there anyway around this? is it not possible to both override the plugin's defaults, and also overriding our own defaults?

**Comment by adamwathan** [comment, marked as answer]
Hey! The problem in your case is selector specificity like you guessed.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/4323180/189504883-5fc98c5d-4f93-4b1e-88e8-40dd2e322f50.png">

The way we handle this in our own projects is to rip off the `input` part of the selector:

```css
@layer base {
  [type='text'],
  [type='password'],
  [type='email'],
  [type='number'],
  [type='url'],
  [type='date'],
  [type='datetime-local'],
  [type='month'],
  [type='week'],
  [type='time'],
  [type='search'],
  [type='tel'],
  [type='checkbox'],
  [type='radio'],
  select,
  multiple,
  textarea {
      @apply shadow;
      @apply border border-zinc-600;
      @apply rounded-lg;
      @apply hover:outline-none hover:border-green-400;
      @apply focus:outline-none focus:ring-green-400 focus:ring-1 focus:border-green-400;
  }
}
```

You can also use the `:where` pseudo-class to reduce specificity if you are comfortable with the browser support (it's pretty good):

```css
@layer base {
  input:where([type='text']),
  input:where([type='password']),
  input:where([type='email']),
  input:where([type='number']),
  input:where([type='url']),
  input:where([type='date']),
  input:where([type='datetime-local']),
  input:where([type='month']),
  input:where([type='week']),
  input:where([type='time']),
  input:where([type='search']),
  input:where([type='tel']),
  input:where([type='checkbox']),
  input:where([type='radio']),
  select,
  select:where([multiple]),
  textarea {
      @apply shadow;
      @apply border border-zinc-600;
      @apply rounded-lg;
      @apply hover:outline-none hover:border-green-400;
      @apply focus:outline-none focus:ring-green-400 focus:ring-1 focus:border-green-400;
  }
}
```
