### DISCUSSION TITLE
<a> tag under <strong> tag is not bolded with `prose` class

### DISCUSSION THREAD

**Discussion by baeharam** [tailwindlabs/tailwindcss#9338] [Help] [answered]
Hello, I'm using Tailwind CSS to render markdown content in my blog. I setudp `@tailwindcss/typography` and added classes like this.
```html
<article
    class="prose max-w-none prose-a:text-strong-blue prose-a:no-underline prose-a:shadow-link-underline prose-h2:text-3xl pb-6"
  >
  <h1 class="text-strong-blue">{frontmatter.title}</h1>
  <slot />
</article>
```

In this context, I wrapped `<a>` tag with `**` in `.md` file to emphasize that link. ⬇️ 
```markdown
**[race condition](https://maxrozen.com/race-conditions-fetching-data-react-with-useeffect)**
```

When I looked into chrome insepctor, I saw `<strong>` tag styling was ignoring with this class.
```css
.prose :where(a):not(:where([class~="not-prose"] *)) {
    color: var(--tw-prose-links);
    text-decoration: underline;
    font-weight: 500;
}

// Ignored class
.prose :where(strong):not(:where([class~="not-prose"] *)) {
    color: var(--tw-prose-bold);
    font-weight: 600;
}
```

How can I solve this problem? I wanna emphase `<a>` tag within markdown rendering.
Thanks for your reading! 🙇‍♂️
