### DISCUSSION TITLE
Not choosing the correct descendant CSS class for @layer components

### DISCUSSION THREAD

**Discussion by ZainMahmoodC** [tailwindlabs/tailwindcss#9353] [Help] [answered]
### Description
I want to apply a distinct CSS class, formed from a parent class and a descendant class, based upon viewport. I have largely achieved this using `@layers` directive in `components` layer. However, there appears to be an edge cases where two `lg:` classes are not applying properly. Better explained with repro (which is also explained below.)

### Reproduction URL
https://play.tailwindcss.com/4xqcZsZJZZ
_P.S. you may need to drag the output window to the left to make it 1024+px_

### Repro Explanation

On 1024px+, I believe `lg:desktop` should apply, and then `lg:big-text`. Thus, giving the color pink. However, as seen on the repro, it is applying `.desktop .small-text`. And thus, showing the color red.

Any thoughts, recommended reading, or code snippets to guide me on how this works under the hood? It doesn't feel non-deterministically applied, but that's just a hunch.

### Repro HTML:
```
<div class="mobile lg:desktop">
  <p class="small-text lg:big-text">On 1024+ resolution, it should apply .desktop .big-text.</p>
</div>
```

### Repro CSS:
```
@tailwind base;
@tailwind components;
@layer components {
  .mobile .small-text {
    font-size: 10px;
    color: blue;
    line-height: 150%;
  }
  .mobile .big-text {
    font-size: 20px;
    color: green;
    line-height: 150%;
  }
  .desktop .small-text {
    font-size: 30px;
    color: red;
    line-height: 150%;
  }
  .desktop .big-text {
    font-size: 40px;
    color: pink;
    line-height: 150%;
  }
}
@tailwind utilities;
```

**Comment by wongjn** [comment, marked as answer]
If you look in the generated CSS, it seems that Tailwind only applies `lg:` variant on one or the other class name but never both; there is no `.lg\:desktop .lg\:big-text` rule, and this is because you can't really "link" these classes together – Tailwind seems to only consider one class at a time.

I think we could use CSS variables to pass information down from the `mobile` or `desktop` parents ([Tailwind Play](https://play.tailwindcss.com/aCj8P45ugS?file=css)):
```css
.mobile {
  --small-text-font-size: 10px;
  --small-text-color: blue;
  --big-text-font-size: 20px;
  --big-text-color: green;
}
.desktop {
  --small-text-font-size: 30px;
  --small-text-color: red;
  --big-text-font-size: 40px;
  --big-text-color: pink;
}

.small-text {
  font-size: var(--small-text-font-size);
  color: var(--small-text-color);
  line-height: 150%;
}
.big-text {
  font-size: var(--big-text-font-size);
  color: var(--big-text-color);
  line-height: 150%;
}
```
This works because we have decoupled the selectors and avoid the problem of the `.lg\:desktop .lg\:big-text` never appearing but we still get contextual styling through the CSS variable inheritance.
