### DISCUSSION TITLE
How to change rem with html ?

### DISCUSSION THREAD

**Discussion by 18121A05L2** [tailwindlabs/tailwindcss#9358] [Help] [answered]
hey can anyone hep me with the , we already know that base rem for all is 16 px , I wanna change that and reduce it based on the width of the screen , how can we do this with tailwind CSS and and i am using tailwind with next js ?

**Comment by wongjn** [comment, marked as answer]
You could use [`vw` units](https://developer.mozilla.org/en-US/docs/Web/CSS/length#vw) directly, such as `m-[1vw]` for `margin: 1vw`.

Alternatively, you can alter the size of `1rem` arbitrarily by changing the font size on the `<html>`, for example:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    font-size: 75%; /* = 12px */
  }
  @screen md {
    :root {
      font-size: 87.5%; /* = 14px */
    }
  }
  @screen xl {
    :root {
      font-size: 100%; /* = 16px */
    }
  }
}
```
