### DISCUSSION TITLE
Generate tailwind Classes from HTML string programatically.

### DISCUSSION THREAD

**Discussion by yulafezmesi** [tailwindlabs/tailwindcss#9365] [Help] [answered]
Hi there,

I want to generate tailwind styles that are given HTML strings. Is there any way to use this way?

For example:

input: 
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Vue SSR Example</title>
  </head>
  <body>
    <div class='flex items-center' id="app">Hi</div>
  </body>
</html>
```

output:

```css
.flex{display:flex} .items-center:{align-items:center}
```
