### DISCUSSION TITLE
How to add utility classes to particular media query only, but not in global scope?

### DISCUSSION THREAD

**Discussion by abdulkareemnalband** [tailwindlabs/tailwindcss#9398] [Help] [answered]
I want following classes to be  generated,  
things in `[]` are placeholders

```css
.icon-[icon-name] {
  background-image: url(https://cdn/[icon-name].png);
}

@media only screen and (min-resolution: 288dpi) {
  .icon-[icon-name] {
    background-image: url(https://cdn/[icon-name]_3x.png);
  }
}
```
Here  `background-image` `url` is different based on dpi

How to write plugin for this?
