### DISCUSSION TITLE
How select by custom selectors? Eg.: `[data-state="any"]:bg-green`

### DISCUSSION THREAD

**Discussion by AdsonCicilioti** [tailwindlabs/tailwindcss#9464] [Help] [answered]
Hi guys!

On normal css owns the possibility of select an element by custom params like:

```css
button[data-state*="anything"] {
   color: red;
}
```

Is possible made this selection with inline tailwind utility classes?
