### DISCUSSION TITLE
Add linear gradient direction

### DISCUSSION THREAD

**Discussion by czernika** [tailwindlabs/tailwindcss#9475] [Ideas]
Hi there!

My idea is maybe to refactor a little `bg-gradient-to-[direction]` utilltiy [class](https://tailwindcss.com/docs/background-image) so it may accepts angle direction. This way I can change `--tw-gradient-direction` CSS variable later if I needed

For example `bg-gradient-to-tr` would generate

```css
.bg-gradient-to-tr {
    --tw-gradient-direction: to top right;
    background-image: linear-gradient(var(--tw-gradient-direction), var(--tw-gradient-stops));
}
```

And allow numerical directions like `bg-gradient-to-10` or `bg-gradient-to-[15deg]` 

```css
.bg-gradient-to-10 {
    --tw-gradient-direction: 10deg;
    background-image: linear-gradient(var(--tw-gradient-direction), var(--tw-gradient-stops));
}
```

I've created similar plugin some time ago but I'm not sure am I allowed to paste my own links)
