### DISCUSSION TITLE
@layer directive is ignored and custom @apply rules are not included in generated css

### DISCUSSION THREAD

**Discussion by ChThy** [tailwindlabs/tailwindcss#9508] [Help]
It seems that `@apply`-rules under `@layer components` are being ignored. The project is an Angular project which is set up using Nx. It contains the app itself and 2 libs (activities and shared). Components in `shared/src/lib/components` are used in `activities/src/lib/components` and those components are used by the angular `AppComponent`.

Tailwind is added by following this guide: [https://nx.dev/recipe/using-tailwind-css-with-angular-projects](https://nx.dev/recipe/using-tailwind-css-with-angular-projects)

I went for the setup where all projects are referencing the same config in `libs/tailwind-preset/tailwind-config.js`.

What I am noticing is that `@apply` rules are missing which are specified in `styles.css`. Other tailwind functionality is working fine. By example, the `darkgray` color defined in `libs/tailwind-preset/tailwind-config.js` is used in `index.html` for setting the background color and is working properly. However, custom css classes defined in `styles.css` under `@layer components` are not working. For example the classes `my-label` and `my-input` are not included in the `styles.css` that is being send to the browser even though they are used in components under `libs/shared/src/lib/components`.

What am I missing here?
Many thanks in advance!

**Versions**
Node.js version: 16.17.1
Angular version: 14
Tailwindcss version: 3.1.8

# Project structure
```
time-register-ui
  |--time-register (published Angular app)
  |    |--src
  |    |    |--app (contains AppComponent)
  |    |    |--index.html
  |    |    |--styles.css
  |    |--tailwind.config.js
  |--libs
       |--activities
       |    |--src
       |         |--lib
       |              |--components
       |--shared
       |    |--src
       |    |    |--lib
       |    |         |--components
       |    |--tailwind-config.js
       |--tailwind-preset
            |--tailwind-config.js
```

# Relevant files:
## time-register/src/styles.css:
```css
@import "../../../node_modules/bootstrap-icons/font/bootstrap-icons.css";
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  input.ng-invalid {
    @apply border-red-600;
  }
  .invert-control-icon::-webkit-calendar-picker-indicator {
    filter: invert(0.85);
  }
  .my-input {
    @apply outline-none bg-transparent border-b-2 border-slate-600 font-mono font-semibold w-full;    
  }
  .my-label {
    @apply font-medium text-xs;
  }
  .my-button {
    @apply text-neutral-300 text-base bg-sky-600 hover:bg-sky-500 py-1 px-2.5 rounded-lg font-medium;
  }
  .my-button:disabled {
    @apply text-neutral-400 bg-sky-900;
    cursor: not-allowed;
  }
}
```

## time-register/tailwind-config.js:
```js
const { createGlobPatternsForDependencies } = require('@nrwl/angular/tailwind');
const { join } = require('path');
const sharedTailwindConfig = require('../../libs/tailwind-preset/tailwind.config');

module.exports = {
  presets: [sharedTailwindConfig],
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ]
};
```

## libs/shared/tailwind-config.js:
```js
const { createGlobPatternsForDependencies } = require('@nrwl/angular/tailwind');
const { join } = require('path');
const sharedTailwindConfig = require('../tailwind-preset/tailwind.config');

module.exports = {
  presets: [sharedTailwindConfig],
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ]
};
```

## libs/tailwind-preset/tailwind-config.js: 
```js
module.exports = {  
  theme: {
    extend: {
      colors: {
        darkgray: {
          800: '#0d1117',
          900: '#010409',
        }
      }
    }
  },
  plugins: [],
};
```
