### DISCUSSION TITLE
Gap (flex, grid) support for Safari 14<

### DISCUSSION THREAD

**Discussion by lonagi** [tailwindlabs/tailwindcss#9514] [Ideas]
For old browsers this css property doesn't work. So. You can add for class gap-* some like this

```css
.gap-4>*+* 
{
    margin-left: 8rem;
}
```
it s for flex row

Also, need support fot flex-col. margin-top.
Just put it with gap property together
