### DISCUSSION TITLE
Reset autocomplete styles

### DISCUSSION THREAD

**Discussion by PringlePot** [tailwindlabs/tailwindcss#9621] [Ideas]
Maybe it would be a good idea to set some basic autocomplete styles for the tailwind Preflight. It is possible to change the chrome and safari text and background now using some css hacks.

```css
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
input:-webkit-autofill:active {
  /* Revert text color */
  -webkit-text-fill-color: white !important;
  color: white !important;
  caret-color: white !important;

  /* Revert background color */
  transition: background-color 5000s ease-in-out 0s;
}
```
