### DISCUSSION TITLE
Prefixing ! is causing all non-important selectors to be important too, in a selector list

### DISCUSSION THREAD

**Discussion by nostalgicdodo** [tailwindlabs/tailwindcss#9627] [Help]
Hi,

I have a selector list in my Tailwind base layer that goes something like this:
```css
.h1, .h2, .h3 {
  margin: 0;
}
```

And here's my HTML:
```html
<h2 class="some-other-class !h1">
```

Some background context, I am using tailwind on an **existing** codebase. I cannot remove/change class names and so in some places I find myself having to use the `!` prefix.

But what Tailwind generates is this:
```css
.h1, .h2, .h3 {
  margin: 0;
}
.\!h1, .h2, .h3 {
  margin: 0 !important;
}
```

Notice how even the non-prefixed `.h2` and `.h3` have `!important` in their styles.

I expected this:

```css
.h1, .h2, .h3 {
  margin: 0;
}
.\!h1 {
  margin: 0 !important;
}
```

In the actual code, the selector list is longer and so are the number of properties in them. I could separate each selector but would be a lot of repetition.

Is there a way around this?
