### DISCUSSION TITLE
:root is invalid in shadow dom

### DISCUSSION THREAD

**Discussion by heng1025** [tailwindlabs/tailwindcss#9633] [Help] [answered]
when i develop a chrome extension, to avoid style confict with host page style,i use shadow dom to isolate style. But in shadow dom `:root` is invalid, just `:host` is valid ,so how i can solve this problem.

**Comment by heng1025** [comment, marked as answer]
Is there a good way to change default style?
```css
:root,
:host {
  --p: 259 94% 51%;
  --pf: 259 94% 41%;
  /* ... */
}
```
