### DISCUSSION TITLE
Rendering of transactional emails in GMAIL

### DISCUSSION THREAD

**Discussion by pablofrommars** [tailwindlabs/tailwindcss#9671] [Help]
Can't get enough of tailwind, great job everyone!

I have recently encountererd an issue with tailwind css output and how gmail renders emails. It's very picky with what's allowed. The full `<style>` block is thrown away when an "incompatible" syntax is found.

Here is an example of adjustments required to make things work in gmail:

```css
/* Original */

.text-gray-400 {
  --tw-text-opacity: 1;
  color: rgb(156 163 175 / var(--tw-text-opacity));
}

/* Workaround */

.text-gray-400 {
  --tw-text-opacity: 1;
  color: rgba(156, 163, 175, var(--tw-text-opacity));
}

```

Any advice? You can imagine having to redact the tailwind output every time I make a change is impractical ;)
