### DISCUSSION TITLE
Setting font-size and line-height using `theme` function?

### DISCUSSION THREAD

**Discussion by mryechkin** [tailwindlabs/tailwindcss#9688] [Help]
I'm looking at utilizing the `theme` function in our design system's CSS files, and I'm a bit confused on how properties like `font-size` and `line-height` are supposed to work?

For example `theme('fontSize.xl')` returns `["1.25rem", {lineHeight: "1.75rem"}]` - am I understanding correctly that I can't just write `font-size: theme('fontSize.xl')` in my CSS? And how would I set `line-height` separately while still using theme tokens?

Any insight would be appreciated!

**Comment by wongjn** [comment]
> […] am I understanding correctly that I can't just write `font-size: theme('fontSize.xl')` in my CSS?

You can! Here's the test that indicates this is the intended behavior:
https://github.com/tailwindlabs/tailwindcss/blob/94d6e7299a7a4b9f94eb1698d7b1346c1572e797/tests/evaluateTailwindFunctions.test.js#L535-L565

> And how would I set `line-height` separately while still using theme tokens?

You should be able to reference a `line-height` value via the `lineHeight` key, which corresponds to the resolved `theme.lineHeight` values, i.e. `theme(lineHeight.normal)`

**Reply by bezin** [reply]
It has been some time, but the second bit is still unanswered, because the suggested way does not work:

```css
.foo {
  font-size: theme('fontSize.xl');
  line-height: theme('fontSize.xl.lineHeight'); // this will not work
}
```

The given error is: `'fontSize.xl.lineHeight' does not exist in your themne config. 'fontSize.xl' has the following valid keys: 0`.

Is there any way to get the corresponding line-height  to a font-size in my CSS via the theme function?

**Reply by wongjn** [reply]
Yes, the line height would be declared in the second element of the font size array value, so you'd reference it like `theme('fontSize.xl.1.lineHeight')`. See [this Tailwind Play of it working](https://play.tailwindcss.com/6DUMwJlkbd?file=css) (open the *Generated CSS* panel).

**Reply by adamwathan** [reply]
This will be a lot better in v4 👍 

```css
.foo {
  font-size: var(--font-size-xl);
  line-height: var(--font-size-xl--line-height);
}
```
