### DISCUSSION TITLE
Support for finer breakpoint controls by passing in object as container value (container-queries)

### DISCUSSION THREAD

**Discussion by a-y-u-s-h** [tailwindlabs/tailwindcss#9719] [Ideas]
In my tailwind config I have `screens` defined as:

```yaml
screens:
  mobile:
    max: 767px
  mobile-sm:
    max: 320px
  mobile-md:
    min: 321px
    max: 375px
  mobile-lg:
    min: 376px
    max: 425px
  mobile-xl:
    min: 426px
    max: 767px
  tablet:
    min: 768px
    max: 991px
  tabloid:
    max: 991px
  desktop:
    min: 992px
  desktop-sm:
    min: 992px
    max: 1024px
  desktop-md:
    min: 1025px
    max: 1440px
  desktop-lg:
    min: 1441px
    max: 1920px
  desktop-4k:
    min: 1921px
    max: 2560px
  desktop-8k:
    min: 2561px
```

I expected same input in `containers` but got errors when I copy pasted those values for finer control. I think it would be a nice addition, easy to guess behavior if `@tailwindcss/container-queries` adopts the optional 'container defined as an object' feature that's used previously for `screens`. I see some comments related to this from back in April here (https://github.com/tailwindlabs/tailwindcss/discussions/5482) but I thought I should open it up as a feature request.
