### DISCUSSION TITLE
Is their a way to remove some of the base style that are coming from preflight?

### DISCUSSION THREAD

**Discussion by shareef99** [tailwindlabs/tailwindcss#9732] [Help] [answered]
I am trying to use tailwindcss@3.2.1 with Mantine UI@5.6.4 when using the `Button` component from Mantine background color is not applied upon debugging I come to know that 
```css
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}
```

This particular piece of code stops the background color from applying. I also know that if I set `preflight: false` in `corePlugins` in the tailwind config, all the styles in the preflight will be gone. I only want to remove the `background-color: transparent;` from the preflight style.

I also try to override this style by adding the `@layer base` style, but that only adds extra style and doesn't remove the preflight style.
