### DISCUSSION TITLE
Having an issue with nesting

### DISCUSSION THREAD

**Discussion by knynkwl** [tailwindlabs/tailwindcss#9795] [Help]
This is my nesting:
```css
.text {
  @apply bg-gray-1;
}

.img-loader::after {
  display: block;

  .bg-gray-1 & {
    border-left-color: black;
    border-right-color: black;
  }
}
```

this is what's outputting:
```css
.text .img-loader::after {
  border-left-color: black;
  border-right-color: black;
}

.img-loader::after {
  display: block;
}

.bg-gray-1 .img-loader::after {
  border-left-color: black;
  border-right-color: black;
}
```

This is my config:
```js
const env = process.env.NODE_ENV;

module.exports = ctx => ({
  plugins: [
    require('postcss-import-ext-glob'),
    require('postcss-import'),
    require('tailwindcss/nesting'),
    require('tailwindcss'),
    require('postcss-focus-visible'),
    require('postcss-nested'),
    require('autoprefixer'),
    env === 'production' ? require('cssnano')({preset: 'default' }) : null
  ]
})

```

**Comment by adamwathan** [comment]
Hey! This output looks correct to me based on what you’re doing, what are you expecting to be different?

**Reply by knynkwl** [reply]
Hey @adamwathan 

The part that is confusing is this output:

.text .img-loader::after {
  border-left-color: black;
  border-right-color: black;
}

I would expect only the & to effect the part class, not the @apply class too

**Reply by knynkwl** [reply]
*parent class

**Reply by adamwathan** [reply]
What output are you actually expecting though? The only thing `bg-gray-1` does is set the border color of the `::after` pseudo-element on a child `.img-loader` element right, so applying it does the same thing, it sets the border color on that pseudo element for any child `.img-loader`.

**Reply by knynkwl** [reply]
@adamwathan here what I expect the output would be.

```css
.text {
  border-color: #EEEEEE;
}

.img-loader::after {
  display: block;
}

.bg-gray-1 .img-loader::after {
  border-left-color: black;
  border-right-color: black;
}
```

All I am trying to accomplish is give .img-loader a parent class of .bg-gray-1, but since .text has the apply of the same class it's adding it to that as well.

Since upgrading to 3 this is new behaviour, but maybe it's my config.

**Reply by adamwathan** [reply]
So let's look at your input after flattening the nesting:

```css
.text {
  @apply bg-gray-1;
}

.img-loader:after {
  display: block;
}

.bg-gray-1 .img-loader:after {
  border-left-color: #000;
  border-right-color: #000;
}
```

It sounds like you have some other definition of `.bg-gray-1` somewhere that you didn't include in your examples, but if you look at this code, this is what Tailwind is seeing and doing:

1. You're trying to `@apply` the `bg-gray-1` class to the `.text` selector.
2. Tailwind looks through your CSS to figure out what `bg-gray-1` is supposed to do.
3. Tailwind sees this rule:

    ```css
    .bg-gray-1 .img-loader:after {
      border-left-color: #000;
      border-right-color: #000;
    }
    ```
4. Tailwind thinks "ah I see! So `.bg-gray-1` is supposed to set the border color of any child `.img-loader::after` that is within it.
5. Tailwind "applies" that behavior to your `.text` class, making it so that any `.img-loader::after` within `.text` has the expected border color.

The way `@apply` works is by trying to apply _every behavior_ of the class you are trying to apply to the selector you are trying to apply it to. So if `bg-gray-1` exists somewhere else with a much simpler implementation, like say this:

```cs
.bg-gray-1 {
  background-color: #9592 
}
```

...then when you create a new custom CSS rule like this:

```css
.bg-gray-1 .img-loader:after {
  border-left-color: #000;
  border-right-color: #000;
}
```

...you are _extending_ the behavior of `.bg-gray-1`, because you're saying `.bg-gray-1` should now _also_ add border colors to this child element in this situation.

That's what's causing you to get the results you're seeing here, because you've extended the behavior of the `.bg-gray-1` class.

My advice would be to never extend the behavior of utility classes like this and you won't get unexpected results like this. Make `.bg-gray-1` just set the background color like it says in the name, not have extra side effects and then applying it won't have those side effects either 👍🏻 

Hope that makes sense! This is a common thing people run into and I frankly hate how complicated `@apply` is because of this sort of thing, so we have ideas for really restricting and simplifying how it works in the next major version that will hopefully make the behavior more intuitive, but I hope this at least helps you understand _why_ you are getting the results you're getting here.

**Reply by knynkwl** [reply]
Ah that makes sense. I was under the impression that `@apply` was only setting the property: value; of the class.

So I was expecting, this and nothing else. 
```css
/* input */
.text { @apply bg-grey-1; }

/* output */
.text { background-color: #efefef; }
```

So going forward, the idea situation would be to use the theme function?
```css
.text {
  background-color: theme(colors.gray.1);
}

.img-loader::after {
  .bg-gray-1 & {
    border-left-color: black;
    border-right-color: black;
  }
}
```
