### DISCUSSION TITLE
What is the best way to do this?

### DISCUSSION THREAD

**Discussion by babakfp** [tailwindlabs/tailwindcss#9916] [Help] [answered]
Hi
This is what I have:
```css
.text-gray-100 {
  --tw-text-opacity: 1;
  color: rgb(245 245 245 / var(--tw-text-opacity));
}
```
This is what I want:
```css
.text-gray-100,
.text-gray-100 svg {
  --tw-text-opacity: 1;
  color: rgb(245 245 245 / var(--tw-text-opacity));
  fill: rgb(245 245 245 / var(--tw-text-opacity));
}
```
I can get it done, but is there an easy and clean way?

**Comment by wongjn** [comment, marked as answer]
You could use the [`currentcolor` keyword](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword) which automatically uses the text color. You could apply `fill: currentColor` on the `<svg>` element via `fill-current`, or have some `base` rule like:
```css
@layer base {
  svg {
    fill: currentColor;
  }
}
```
Or via plugin API:
```js
module.exports = {
  // …
  plugins: [
    require('tailwindcss/plugin'(({ addBase }) => {
      addBase({
        svg: {
          fill: 'currentColor';
        },
      });
    }),
  ],
};
```
