### DISCUSSION TITLE
Way to targeting multiple css selectors

### DISCUSSION THREAD

**Discussion by ivanchenhz** [tailwindlabs/tailwindcss#9918] [Ideas]
The thing is we are handling the localisation, there are a few special cases we need to take care for different locale, 

So, we add the locale selector with:
```javascript
locales.forEach((locale) => {
  addVariant(`${locale}`, [`html[lang="${locale}"] &`]);
});
```

And in template we use it like:
```html
<div class="ru-RU:tw-max-w-[13rem] fr-FR:tw-max-w-[10rem] nb-NO:tw-max-w-[10rem] nl-NL:tw-max-w-[10rem] >"
```

It works fine, until we keep adding this kind of treatment for more and more locales,
so we are thinking could we somehow write the code like
```html
<div class="ru-RU:tw-max-w-[13rem] (fr-FR,nb-NO,nl-NL):tw-max-w-[10rem] >"
```

With the following css generated:
```css
html[lang="fr-FR"] .fr-FR\:tw-max-w-\[10rem\],
html[lang="nb-NO"] .nb-NO\:tw-max-w-\[10rem\],
html[lang="nl-NL"] .nl-NL\:tw-max-w-\[10rem\] {
  max-width: 10rem;
}
```

Any thoughts for this? 👍
