### ISSUE TITLE
Meaningful spaces removed from arbitrary-value selector

### ISSUE THREAD

**Issue by jamesarosen** [tailwindlabs/tailwindcss#10029]
tailwindcss@3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Calling `tailwindcss -m -i ./styles/app.css -o app/styles/app.css` directly.

**What version of Node.js are you using?**

v16.17.1

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/caV1258xHD

**Describe your issue**

This works:
```html
class="grid-cols-[1fr]"
```

But this doesn't:
```html
class="grid-cols-[1fr 1fr]"
```

On my machine, it generates
```css
@media (min-width: 768px) {
  .md\:grid-cols-\[1fr1fr\] {
    grid-template-columns: 1fr1fr;
  }
}
```
