### ISSUE TITLE
max-(sm|md|lg|xl) breakpoints don`t work with screen function

### ISSUE THREAD

**Issue by zamanruhy** [tailwindlabs/tailwindcss#10233]
Hello guys! Desktop-first breakpoints `max-(sm|md|lg|xl)` don't work with screen function. 
The following results in an error (`The 'max-sm' screen does not exist in your theme.`):

```scss
@media screen(max-sm) {
  div {
    background-color: theme(colors.indigo.500);
  }
}
```

But mobile-first keywords work fine. I'm assuming this is a bug. There is a minimal [repl](https://play.tailwindcss.com/UA5IQEgQIL?file=css)
