### ISSUE TITLE
Unable to list multiple variants in arbitrary variant

### ISSUE THREAD

**Issue by brandonmcconnell** [tailwindlabs/tailwindcss#10576]
**What version of Tailwind CSS are you using?**

v3.2.6

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli v8.4.19

**What version of Node.js are you using?**

v18.12.1

**What browser are you using?**

Chrome v109

**What operating system are you using?**

macOS Ventura

**Reproduction URL**

https://play.tailwindcss.com/7TUEdEbhJH

**Describe your issue**

I'd expect to be able to do something like `[span,h1,&_h1]:font-bold` using an arbitrary variant, but that doesn't appear to work.

To better demonstrate the issue, I'll compare the CSS generated by the above utility vs. what I _think_ would be expected:

**Expected:**

```css
span,
.\[span\,\&_h1\]\:font-bold h1 {
  font-weight: 700;
}
```

**Reality:**

```css
span {
  font-weight: 700;
}
```

This is inconvenient for a couple of reasons:
* This adds a global style that matches all spans on the page, not just those matching the class
* The `h1` in the arbitrary variant gets completely ignored

**Comment by adamwathan** [comment]
Hey! So in your expected CSS the `span` would match all spans on the page too:

```css
span,
.\[span\,\&_h1\]\:font-bold h1 {
  font-weight: 700;
}
```

That's the same as this:

```css
span {
 font-weight: 700;
}
.\[span\,\&_h1\]\:font-bold h1 {
  font-weight: 700;
}
```

I'm not really sure what the expected output should be here personally, I kinda just don't think anyone should do this 😅

What do you _actually_ want to achieve here?

I think there's a bug here in that the `span` style is being generated but will have to think through exactly what we even want to happen here instead. Generally with Tailwind stuff it's a bit unconventional to ever write CSS rules that have multiple selectors so I'm inclined to just discard these classes to avoid the surprising output in the short term.
