### ISSUE TITLE
cannot use camelCase for animation or keyframe name

### ISSUE THREAD

**Issue by Johnrobmiller** [tailwindlabs/tailwindcss#10719]
using tailwind 3.2.7

I'm just going to paste my whole tailwind.config file in, that might be easiest.
Long story short, there are two keyframe/animations named `slide-up` and `slide-down`. Originally, I named them `slideUp` and `slideDown`, but after quite a lot of debugging, I found out that these two animations would only work if they were renamed `slide-up` and `slide-down`.

I briefly looked for a duplication of this issue, and couldn't find any, although there are enough closed issues that I might have missed it.

```
/* eslint-disable @typescript-eslint/no-var-requires */
const { fontFamily } = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        primary: ['Inter', ...fontFamily.sans],
      },
      colors: {
        primary: {
          // Customize it on globals.css :root
          50: 'rgb(var(--tw-color-primary-50) / <alpha-value>)',
          100: 'rgb(var(--tw-color-primary-100) / <alpha-value>)',
          200: 'rgb(var(--tw-color-primary-200) / <alpha-value>)',
          300: 'rgb(var(--tw-color-primary-300) / <alpha-value>)',
          400: 'rgb(var(--tw-color-primary-400) / <alpha-value>)',
          500: 'rgb(var(--tw-color-primary-500) / <alpha-value>)',
          600: 'rgb(var(--tw-color-primary-600) / <alpha-value>)',
          700: 'rgb(var(--tw-color-primary-700) / <alpha-value>)',
          800: 'rgb(var(--tw-color-primary-800) / <alpha-value>)',
          900: 'rgb(var(--tw-color-primary-900) / <alpha-value>)',
        },
        dark: '#222222',
      },
      keyframes: {
        flicker: {
          '0%, 19.999%, 22%, 62.999%, 64%, 64.999%, 70%, 100%': {
            opacity: 0.99,
            filter:
              'drop-shadow(0 0 1px rgba(252, 211, 77)) drop-shadow(0 0 15px rgba(245, 158, 11)) drop-shadow(0 0 1px rgba(252, 211, 77))',
          },
          '20%, 21.999%, 63%, 63.999%, 65%, 69.999%': {
            opacity: 0.4,
            filter: 'none',
          },
        },
        shimmer: {
          '0%': {
            backgroundPosition: '-700px 0',
          },
          '100%': {
            backgroundPosition: '700px 0',
          },
        },
        "slide-down": {
          '100%': {
            height: "var(--radix-accordion-content-height)"
          },
          '0%': {
            height: 0
          }
        },
        "slide-up": {
          '0%': {
            height: "var(--radix-accordion-content-height)"
          },
          '100%': {
            height: 0
          }
        }
      },
      animation: {
        flicker: 'flicker 3s linear infinite',
        shimmer: 'shimmer 1.3s linear infinite',
        // warning: the name cannot be camelCase. It must be kebab-case. If it is camelCase, it will fail silently.
        'slide-up': 'slide-up 300ms ease-out',
        'slide-down': 'slide-down 300ms ease-out',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require("tailwindcss-radix")()
  ],
};
```

**Comment by Johnrobmiller** [comment]
This might be because CSS animation/keyframe names are case insensitive. However, without that knowledge from the offset, this is likely a very difficult issue for devs to debug.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The important part here is that they are all linked up together using their names (see: https://tailwindcss.com/docs/animation#customizing-your-theme). 

You can definitely use camelCase, but you have to make sure that the name of the animation itself and the name of the keyframes are the same. I don't think this is a Tailwind CSS bug (but we could improve this system a bit so that you don't have to think about it, not 100% sure what that would look like yet.

Thinking about this in another way, I think it might be too magic / confusing if we magically convert all animations to let's say kebab-case or camelCase behind the scenes. If we would do this, then defining animations in your css itself, or if the animations are coming from a 3rd party library then this won't work anymore. If you are using them in other places like in your JavaScript then the silent renaming won't work either. 

Here is an updated play link where all references are made consistent. This means that the key in `animation`, the used animation itself in `animation` and the key in `keyframes` are all the same. https://play.tailwindcss.com/PUrK8aarir?file=config

The generated CSS looks like this:
```css
@keyframes slideDown {
  100% {
    height: 100vh;
  }

  0% {
    height: 0px;
  }
}

.animate-slideDown {
  animation: slideDown 5s ease-out;
}

@keyframes slideUp {
  0% {
    height: 100vh;
  }

  100% {
    height: 0px;
  }
}

.animate-slideUp {
  animation: slideUp 5s ease-out;
}
```

The big difference is that there are 2 "names" going on, the name of the animation for the utility and the name for the actual keyframes linked to it. It might be a bit easier to reason about if you look at utilities like colors for example, you could write them as:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        red: 'red'
      }
    }
  }
}
```
(Example Play: https://play.tailwindcss.com/apfad1Wei3?file=config)

Then you can use it as `bg-red` for example, but you don't _have_ to following this convention. You can also give a different name to the color, for example `primary`. This way the actual name and the value are different.

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: 'red'
      }
    }
  }
}
```
(Example Play: https://play.tailwindcss.com/Ijz3hum0Kx?file=config)

Knowing this, you can apply this to your animations as well.

You can also mix them if you prefer to write `animate-slide-down` but still want `slideDown` animations. An updated link can be found here: https://play.tailwindcss.com/RyAt4XOad3?file=config

The generated css for this looks like:
```css
@keyframes slideDown {
  100% {
    height: 100vh;
  }

  0% {
    height: 0px;
  }
}

.animate-slide-down {
  animation: slideDown 5s ease-out;
}

@keyframes slideUp {
  0% {
    height: 100vh;
  }

  100% {
    height: 0px;
  }
}

.animate-slide-up {
  animation: slideUp 5s ease-out;
}
```

You should also be able to do it the other way around, where the keyframes themselves are defined in kebab-case, but the animation name in your utilities are camelCase. An updated link can be found here: https://play.tailwindcss.com/8o4Y1WWVZV?file=config

The generated css for this looks like:
```css
@keyframes slide-down {
  100% {
    height: 100vh;
  }

  0% {
    height: 0px;
  }
}

.animate-slideDown {
  animation: slide-down 5s ease-out;
}

@keyframes slide-up {
  0% {
    height: 100vh;
  }

  100% {
    height: 0px;
  }
}

.animate-slideUp {
  animation: slide-up 5s ease-out;
}
```

I hope this helps!
