### ISSUE TITLE
safeList doesn't generate dynamic classess

### ISSUE THREAD

**Issue by hodev-dev** [tailwindlabs/tailwindcss#10773]
```yml
"@types/react": "^18.0.27",
"@types/react-dom": "^18.0.10",
"@vitejs/plugin-react": "^3.1.0",
"autoprefixer": "^10.4.13",
"postcss": "^8.4.21",
"tailwindcss": "^v3.2.3",
"typescript": "^4.9.3",
"vite": "^4.1.0"
```

```typescript
/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [],
  content: [],
  safelist: [
    {
      pattern: /bg-(red|green|blue|orange)-(100|500|700)/, // You can display all the colors that you need
      variants: ['lg', 'hover', 'focus', 'lg:hover'],      // Optional
    },
  {
      pattern: /h-.*/, // You can generate all heights
      variants: ['lg', 'xs'],      // Optional
    },
  ],
  darkMode: 'media',
  theme: {},
  plugins: [],
}
```

when i run **yarn build** dynamic classes are not created
how i can fix safeList?
