### ISSUE TITLE
`hover:text-` styles do not work when `darkMode` config is `class` and you set a dark text color 

### ISSUE THREAD

**Issue by secondl1ght** [tailwindlabs/tailwindcss#10855]
**What version of Tailwind CSS are you using?**

v3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

SvelteKit 1.12.0

**What version of Node.js are you using?**

v19.6.0

**What browser are you using?**

Brave

**What operating system are you using?**

ZorinOS (Ubuntu)

**Reproduction URL**

https://github.com/secondl1ght/tailwind-bug-demo

**Describe your issue**

Steps to reproduce:

1. In `tailwind.config.cjs` set `darkMode: 'class'`
2. Add class `dark` to your root `html` element
3. On any element add `dark:text-red-500 hover:text-blue-500`
4. Note that the `hover` style does not work

Behaviour expected:
1. Element turns the text to blue

Important notes:
1. If you add `dark:hover:text-blue-500` the styles will work
2. `dark:text-red-500 hover:text-blue-500` works normally when `darkMode: 'class'` is not present in your tailwind config file
3. This appears to only be affecting the `text` class but I haven't tested them all - for example `hover:bg-blue-500` still works as expected with both dark mode configs

**Comment by AviAvinav** [comment]
Try using `dark:hover:text-blue-500` instead, it works. I feel like this is expected behavior since you might want to have different hover styles in dark and light modes, for example, you had something like this: `text-black hover:text-gray-800 dark:text-white dark:hover:text-gray-200`, because in this situation depending on your background you might want different colors.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This is expected behaviour because the `.dark` class will up the specificity. If you look at the generated CSS, then it looks like this:
```css
.hover\:text-blue-500:hover {
  --tw-text-opacity: 1;
  color: rgb(59 130 246 / var(--tw-text-opacity));
}

.dark .dark\:text-red-500 {
  --tw-text-opacity: 1;
  color: rgb(239 68 68 / var(--tw-text-opacity));
}
```

I would recommend you to be explicit, just like what @AviAvinav suggested, you can make it more explicit by typing `dark:hover:text-blue-500`. This would generate the following CSS: 
```css
.hover\:text-blue-500:hover {
  --tw-text-opacity: 1;
  color: rgb(59 130 246 / var(--tw-text-opacity));
}

.dark .dark\:text-red-500 {
  --tw-text-opacity: 1;
  color: rgb(239 68 68 / var(--tw-text-opacity));
}

.dark .dark\:hover\:text-blue-500:hover {
  --tw-text-opacity: 1;
  color: rgb(59 130 246 / var(--tw-text-opacity));
}
```

Here is a Tailwind Play that showcases this behaviour: https://play.tailwindcss.com/kSUCleOH0a

Hope this helps!
