### ISSUE TITLE
`arbitrary-values`: Handling whitespace error when using with PostCSS

### ISSUE THREAD

**Issue by thedv91** [tailwindlabs/tailwindcss#10872]
**What version of Tailwind CSS are you using?**

3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.21

**What version of Node.js are you using?**

v18.15.0

**What browser are you using?**

Headless

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/3abiQvIz2y

I have a simple code above(just for example). It worked well on the playground.

**Describe your issue**

But when I use postcss, it returns unexpected results:

This is my code

```js
const tailwind = require('tailwindcss');
const path = require('path');
const postcss = require('postcss');

const input = String.raw`
    @tailwind base;
    @tailwind components;
    @tailwind utilities;
`;

postcss([
    tailwind({
        corePlugins: { preflight: false },
        content: [
          {
            raw: `
                <div class="[&_.my\_\_button]:text-red-500">
                <div>
                <button class="my__button">AAAAAA</button>
                </div>
            </div>
                `,
            extension: 'html',
          },
        ],
    }),
    require('autoprefixer'),
  ]).process(input, {
    from: `${path.resolve(__filename)}`
  }).then(result=>{
    console.log(result.css)
  });

```

Actual output:

```css
...
.\[\&_\.my__button\]\:text-red-500 .my button {
    --tw-text-opacity: 1;
    color: rgb(239 68 68 / var(--tw-text-opacity))
}
```

My expectations:

```css
.\[\&_\.my__button\]\:text-red-500 .my__button {
    --tw-text-opacity: 1;
    color: rgb(239 68 68 / var(--tw-text-opacity))
}
```
