### ISSUE TITLE
[Feature Proposal] Provide Configuration as CSS Custom Properties

### ISSUE THREAD

**Issue by dantodev** [tailwindlabs/tailwindcss#1091]
I like to pick up the discussion from #1022. The idea of this issue was to replace `theme` with css custom properties. My proposal is to provide both alongside each other.

In fact it is already possible to use custom properties in the tailwind configuration manually like #260 described:

```css
/* main.css */
:root {
  --colors-primary: red;
}

@tailwind base;
@tailwind components;
@tailwind utilities;
```

```js
// tailwind.config.js
module.exports = {
  theme: {
    color: {
      primary: "var(--colors-primary)"
    }
  }
}:
```

But by manually using css custom properties, the usage of `theme`  is not possible on compile time anymore because now the real value is only available on runtime. If tailwind would provide both css custom properties and `theme` this would be no problem. So having both css custom properties and `theme` is not redundant.

Implementing css custom properties the right way could even enable us to override variables on runtime without any build system needed. This could open awesome new opportunities for tailwind.

Sure this idea is not fully thought through. The browser support for css custom properties could be a problem, or the fact that changing variables on runtime will not effect cases where `theme` has been used on compile time. But maybe this idea is worth further consideration.

**Comment by nemrutco** [comment]
I am not sure if this will help you but, I have been working on some idea on one of my project about smilar thing. I was looking a way to define my root colors from my color palette and dynamically create lighter and darker variations. I end up something like this:

### Sass/CSS
```scss
//color palette
$orange : #FF6F5F;
$blue : #4B78AD;
$neutral :#666;

$colors: ('primary':$orange, 'secondary':$blue, 'neutral':$neutral);

@function force-hex($color) {
    @if type-of($color)=='color' {
        $hex: str-slice(ie-hex-str($color), 4);
        @return unquote("\##{$hex}");
    }

    @return $color;
}

:root {

    @each $name,
    $color in $colors {
        --color-#{$name}-lighter: #{force-hex(lighten($color,40%))};
        --color-#{$name}-light: #{force-hex(lighten($color,14%))};
        --color-#{$name}: #{$color};
        --color-#{$name}-dark: #{force-hex(darken($color,14%))};
        --color-#{$name}-darker: #{force-hex(darken($color,40%))};
    }
}

@tailwind base;

@tailwind components;

@tailwind utilities;

```
tailwind.config.js
```typescript
module.exports = {
    theme: {
        colors: {
            white: '#fff',
            black: '#333',
            primary: {
                lighter: 'var(--color-primary-lighter)',
                light: 'var(--color-primary-light)',
                default: 'var(--color-primary)',
                dark: 'var(--color-primary-dark)',
                darker: 'var(--color-primary-darker)',
            },
            secondary: {
                lighter: 'var(--color-secondary-lighter)',
                light: 'var(--color-secondary-light)',
                default: 'var(--color-secondary)',
                dark: 'var(--color-secondary-dark)',
                darker: 'var(--color-secondary-darker)',
            },
            neutral: {
                lighter: 'var(--color-neutral-lighter)',
                light: 'var(--color-neutral-light)',
                default: 'var(--color-neutral)',
                dark: 'var(--color-neutral-dark)',
                darker: 'var(--color-neutral-darker)',
            },
        },
        extend: {

        },
    },
    variants: {},
    plugins: [],
}
```
Now i could use any of the color variation same way as tailwind provides.

```html
<p class="text-primary-light">Hello World</p>
```
I was using sass because i would like to define only main colors and dynamically create the variations. BTW root colors requires hex or rgba colors as i experienced. So in my sass i convert my colors to HEX using  force-hex function.

I think if tailwind references custom colors from root by default, overwriting will be easier without compile.

**Comment by dantodev** [comment]
This is exactly the workaround described in #260. This way you still have to define the custom properties on your own, its not happening automatically. I would like to have this behavior out of the box or atleast as a configuration I can enable in my `tailwind.config.js`.

**Comment by adamwathan** [comment]
@dantodev Can you show an example of what you'd actually want Tailwind to generate so I know I understand 100% what you're suggesting? Sometimes it's easier to just see the output you want instead of trying to piece it together from a description.

**Comment by nemrutco** [comment]
I think I have smilar points with @dantodev. This might already exists in tailwind but i still would like to know if is it possible:

Let's say we want to define our color palette in our css using :root pseudo-class and ask tailwind to figure out what are the new colors or existing colors are given and generate all variants of those colors.

```css
/*app.css*/
:root {
    --color-blue: #4267b2;
    --color-primary: #FF6F5F;
    --color-secondary: #4B78AD;
    --color-neutral : #666;
}

@tailwind base;

@tailwind components;

@tailwind utilities;
```
Is it possible without touching anything in tailwind.config file, but let tailwind automatically detect new colors from :root and generate all the 100 to 900 variants using tailwind default color generation pattern. (I am not sure if there is such an algorithm to generate color palettes like the one used in tailwind default colors 
```js
/*
* It would be great if tailwind could generate color palettes using a base color 
* and convert it to HSL like 500 to be the base color  and 100 lighter 900 darker.
*/
100: 'hsl(201, 100%, 96%)',
200: 'hsl(202, 81%, 86%)',
300: 'hsl(203, 82%, 76%)',
...
900: 'hsl(215, 41%, 28%)',

```

or is it possible to define them only in tailwind.config by adding something like "customBaseColors".
```js
module.exports = {
    theme: {
        colors: {
            white: '#fff',
            black: '#333',
        },
       customBaseColors: {
            blue: '#4267b2',
            primary: '#FF6F5',
            secondary: '#4B78AD',
            neutral :  '#666',
       }
        extend: {

        },
    },
    variants: {},
    plugins: [],
}
```

BTW if any tailwind's default colors like "blue" defined in the examples, it will re-generate or overwrite it. :

and finaly as a result we get this:
```css
/*
* Ignore the color codes they are all same.
* Consider like they are generated by the color algorithm from tailwild for each variant
*/
.text-blue {
  color: #FF6F5F;
}

.text-blue-100 {
  color: #FF6F5F;
}

.text-blue-200 {
  color: #FF6F5F;
}
...
...
.text-blue-900 {
  color: #FF6F5F;
}
...
.bg-blue-100 {
  color: #FF6F5F;
}
.bg-blue-200 {
  color: #FF6F5F;
}
...
...
.bg-blue-900 {
  color: #FF6F5F;
}
...
.text-primary {
  color: #FF6F5F;
}

.text-primary-100 {
  color: #FF6F5F;
}

.text-primary-200 {
  color: #FF6F5F;
}
...
...
.text-primary-900 {
  color: #FF6F5F;
}
...
.bg-primary-100 {
  color: #FF6F5F;
}
.bg-primary-200 {
  color: #FF6F5F;
}
...
...
.bg-primary-900 {
  color: #FF6F5F;
}
...
...
...

**Comment by nemrutco** [comment]
Just found out this:

> A common question we get is "how do I generate the 100–900 shades of my own custom colors?".

>Bad news: color is complicated and we've yet to find a tool that does a good job generating these sorts of color palettes. We picked all of Tailwind's default colors by hand, balancing them by eye. Sorry!

So, tailwind colors are defined by hand. Nothing dynamically generated, No any algorithm but there won't be any in future? I have seen some algorithms writen by java and C# but not sure if they will fit tailwind.

**Comment by hacknug** [comment]
Take a look at this https://javisperez.github.io/tailwindcolorshades/#/?blue=0000ff&tv=1

**Comment by nemrutco** [comment]
> Take a look at this https://javisperez.github.io/tailwindcolorshades/#/?blue=0000ff&tv=1

yup, exactly what i need out of the box by tailwind.

**Comment by dantodev** [comment]
To bring this issue back to its origin, imagine the following simplified configuration:

```js
// tailwind.config.js
return {
  theme: {
    colors: { red: "#FF0000" },
    spacing: { xl: "3rem" }
  }
};
```

I would like tailwind to generate one of the following outputs:

**Option 1:** Only generate CSS custom properties from tailwind configuration. Still inject the configured values in the generated CSS.

```css
// output
:root {
  --colors-red: #FF0000;
  --spacing-xl: 3rem;
}

.bg-red {
  background-color: #FF0000;
}

.p-xl {
  padding:  3rem;
}
```

**Option 2:** Not only generate the custom properties but also used them by `var()` in the generated CSS.

```css
// output
:root {
  --colors-red: #FF0000;
  --spacing-xl: 3rem;
}

.bg-red {
  background-color: var(--color-red);
}

.p-xl {
  padding:  var(--spacing-xl);
}
```

The second option would result in an slightly bigger output but would have the benefit that you could override custom properties on runtime.

I don't know if it would be worth to do this for every single configuration key or just for colors, spacings an some other. Maybe this could be configured in the tailwind configuration. Something like this:

```js
// tailwind.config.js
return {
  `customProperties: {
    mode: 'use', // "inject" => only inject custom properties in :root block
                 // "use" => use the properties in generated css
    exposedKeys: ['colors', 'spacings']
  }
};
```
