### ISSUE TITLE
@apply method is invalid after upgrade to 3.3.1

### ISSUE THREAD

**Issue by scarqin** [tailwindlabs/tailwindcss#10937]
**What version of Tailwind CSS are you using?**

v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack 5.77.0

**What version of Node.js are you using?**

v16.16.0

**What browser are you using?**
Chrome

**What operating system are you using?**

macOS

**Reproduction URL**
https://github.com/Postcatlab/postcat/blob/3411792892633e5c53d4e86466a0fd52f4599f4a/src/browser/src/app/pages/workspace/overview/project-list/project-list.component.scss

**Describe your issue**
My previous version was 3.2.4 After upgrading to the latest version of 3.3.1, @apply is invalid.
* Angular 15.2.5

```scss
:host {
  .operate-btn-list {
    display: none;
  }

  .ant-card {
    @include hover-item;
  }

  ::ng-deep {
    .ant-list-items {
      .ant-list-item {
        @apply px-[10px] rounded-[3px];
        @include hover-item;

        border: 1px solid transparent;
      }
    }
  }
}
```
previous display

![image](https://user-images.githubusercontent.com/15225835/229733712-d9d19b15-8461-4113-b2a5-7298d8cb71c4.png)

current display

![](https://user-images.githubusercontent.com/15225835/229733180-e01260c1-4772-45dd-848c-32ceb7696db1.png)
