### ISSUE TITLE
3.3.1 not handling pseudo-elements properly

### ISSUE THREAD

**Issue by codepic** [tailwindlabs/tailwindcss#10960]
**What version of Tailwind CSS are you using?**

`3.3.1`

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwindcss

**What version of Node.js are you using?**

`v18.14.0`

#### Steps to Repro

```bash
mkdir repro
cd repro
yarn global add tailwindcss@3.3.1
tailwindcss init
```

Create `repro.css` with the following content:

```css
@config 'tailwind.config.js';
::deep [a] {
    @apply bg-white;
}
```

Run `tailwindcss --input .\repro.css --output .\result.css`

```css 
/* result.css / Incorrect */
[a]::deep {
  --tw-bg-opacity: 1;
  background-color: rgb(255 255 255 / var(--tw-bg-opacity))
}
```

You can fix this by downgrading tailwindcss to 3.3.0:

```bash
yarn global add tailwindcss@3.3.0
tailwindcss --input .\repro.css --output .\result.css
```` 

And the CORRECT output

```css
/* Correct! */
::deep [a] {
  --tw-bg-opacity: 1;
  background-color: rgb(255 255 255 / var(--tw-bg-opacity))
}
```
