### ISSUE TITLE
transform variables don't work inside keyframes

### ISSUE THREAD

**Issue by gustavotcabral** [tailwindlabs/tailwindcss#11072]
**What version of Tailwind CSS are you using?**

v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss/Svelte v3.58.0

**What version of Node.js are you using?**

v18.14.0

**What browser are you using?**

Buggy on Chrome; the example works on Firefox.

**What operating system are you using?**

Ubuntu 18.04

**Reproduction URL**

The bug occurs when removing the `@property` declarations: https://play.tailwindcss.com/6r2AMqX4r9

**Describe your issue**

CSS Custom Properties are not animatable by default. I think we just need to declare all `--tw-*` variables using [`@property`](https://developer.mozilla.org/en-US/docs/Web/CSS/@property).

**Comment by thecrypticace** [comment]
Hey! So we're looking into adding `@property` declarations for v4 but still have a lot to investigate — especially around browser support. It's only just recently become supported in Safari, for instance. And hasn't yet landed in Firefox (and doesn't look like there's any movement yet to do so).

In the meantime I'd suggest you include the `@property` declarations in your own project if the browser support requirements aren't an issue. Oddly enough your Play works in Safari but only because there's a `transform` property present. Here's one that does not animate: https://play.tailwindcss.com/JmJW3IeyDN?file=css

As an aside, we'd recommend not using `@apply` with `@keyframes`. It wasn't designed to work with it and you can get it to produce some pretty comical, non-sensical results:

<img width="591" alt="Screenshot 2023-04-25 at 11 02 42" src="https://user-images.githubusercontent.com/614993/234319449-02f54769-5e21-4bef-9c65-013d4ab6fe50.png">

We're likely going to change this in v4 to produce an error when `@apply` is used inside of `@keyframes`. Instead, I'd recommend writing this using properties directly while making use of the `theme()` function:

```css
@keyframes mybounce {
  0%, 100% {
    transform: translate(theme('translate.1/2'), theme('translate.full'));
    animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
  }
  50% {
    transform: translate(theme('translate.1/2'), 150%);
    animation-timing-function: cubic-bezier(0.8, 0, 1, 1);
  }
}
```

Hope that helps! Let me know if you have any further questions. ✨
