### ISSUE TITLE
`bg-[repeating-conic-gradient(...)]` generates a `background-color` declaration instead of `background-image`

### ISSUE THREAD

**Issue by benface** [tailwindlabs/tailwindcss#11178]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Just the CLI.

**What version of Node.js are you using?**

v20.0.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/n33mDmU8bq

Look at the "Generated CSS":

<img width="702" alt="CleanShot 2023-05-08 at 00 30 42@2x" src="https://user-images.githubusercontent.com/1059139/236734266-210b75b4-9a67-4b6e-96e5-fc735e28c83b.png">

**Describe your issue**

I would expect the generated CSS rule to be:

```css
.bg-\[repeating-conic-gradient\(\#F8F9FA_0\%_25\%\2c _white_0\%_50\%\)\] {
  background-image: repeating-conic-gradient(#F8F9FA 0% 25%, white 0% 50%);
}
```

Just like it works with `bg-[conic-gradient(...)]`. Thank you!
