### ISSUE TITLE
oklch support

### ISSUE THREAD

**Issue by lukeshiru** [tailwindlabs/tailwindcss#11299]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Astro@2.5.5

**What version of Node.js are you using?**

20.2.0

**What browser are you using?**

Chrome and Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/VmeVGX02Kt

**Describe your issue**

When setting custom colors using [oklch](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch), the fractional color class names, like `bg-color-500/50` stop working. The parser that deals with that could be updated so it sets the alpha of the color using `oklch` like this:

```css
.bg-example {
  /* from this: */
  background: oklch(75% 0.2 var(--brand-hue));
  /* to this: */
  background: oklch(75% 0.2 var(--brand-hue) / 0.5);
}
```
