### ISSUE TITLE
Important selector strategy does not play well with ::-webkit-color-swatch pseudo class

### ISSUE THREAD

**Issue by mihaip** [tailwindlabs/tailwindcss#11435]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.24

**What version of Node.js are you using?**

v20.0.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/sYr56p1Qdf

**Describe your issue**

I'm using a custom property to style the `::-webkit-color-swatch` pseudo-element. It works as expected when there isn't a selector added to the generated styles (see expected rendering at https://play.tailwindcss.com/1GvAsVM2yK), but if I add one (via `important: ".my-container"`) then those utility classes stop matching.

It appears to be an issue with the `.my-container :is(....)` wrapper that Tailwind is adding to the generated CSS. It outputs:

```css
.my-container :is(.\[\&\:\:-webkit-color-swatch\]\:border-none::-webkit-color-swatch) {
  border-style: none;
}
```

If that were to be 
```css
.my-container :is(.\[\&\:\:-webkit-color-swatch\]\:border-none)::-webkit-color-swatch {
  border-style: none;
}
```

Then it would match.
