### ISSUE TITLE
Tailwind 3.3+ dark mode does not work with encapsulated angular components using @apply

### ISSUE THREAD

**Issue by MarKayS** [tailwindlabs/tailwindcss#12352]
**What version of Tailwind CSS are you using?**

v3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**

tried angular 13 and angular 16

**What version of Node.js are you using?**

v18.10.0

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

Windows, macOS

**Reproduction URL**

https://github.com/MarKayS/tailwind-angular-dark-bug

**Describe your issue**

When using @apply with dark mode set to class and angular viewEncapsulation is not disabled, the `dark:` rules are also scoped.

Using this simple css:
```scss
:host{
@apply text-amber-900 dark:text-amber-500;
}
```

This is how the dark style is generated with tailwind 3.3+:
```css
:is(.dark   )[_nghost-mxl-c11] {
    --tw-text-opacity: 1;
    color: rgb(245 158 11 / var(--tw-text-opacity))
}
```

Same style with tailwind 3.2.0:
```css
.dark   [_nghost-kar-c11] {
    --tw-text-opacity: 1;
    color: rgb(245 158 11 / var(--tw-text-opacity))
}
```

This means that I would have to add .dark class to every component, turn off viewEncapsulation or use hostBinding insted of apply.

In previous versions there were spaces after the `.dark   `. The same is true in 3.3, but the spaces are inside the :is function `:is(.dark   )`. 

I think the error comes from 
https://github.com/tailwindlabs/tailwindcss/blob/b411d04c8cd6b32e42f73695c23253bcab7d4429/src/corePlugins.js#L228

I believe changing it to the following line should resolve the issue and hopefully not break anything:
```
addVariant('dark', `:is({className}) &`)
```

Should I submit a PR?

**Comment by faileon** [comment]
I am having the same issue in my angular app.

**Comment by thecrypticace** [comment]
Hey! So, this an issue with Angular. We generate the following CSS from the above:

```css
:host {
  --tw-text-opacity: 1;
  color: rgb(120 53 15 / var(--tw-text-opacity))
}

:is(.dark :host) {
  --tw-text-opacity: 1;
  color: rgb(245 158 11 / var(--tw-text-opacity))
}
```

Then Angular processes it, removes `:host`, but does not place the data attribute in the right place. It generates `:is(.dark   )[_nghost-jja-c5]` when it should generate `:is(.dark [_nghost-jja-c5])` instead.

You can see an example of this (without Tailwind involved) [in this example](https://ng-run.com/edit/tnBESstWEQtU11CmH6dj). You'll need to peek into the compiled source in the iframe using inspect element for this it seems though.

I'll look into filing an issue with them that includes a reproduction sometime today or early next week if I can't find an existing one.

---

As an aside, we don't use `addVariant('dark', ':is({className}) &')` because that is functionally different from current version when it comes to putting multiple classes/attributes on the same element or on elements nested in a different order. I've prepped an example on [Tailwind Play](https://play.tailwindcss.com/H688gR7JTO) that showcases this.
