### ISSUE TITLE
'optimizeUniversalDefaults' does not respect 'important' configuration var

### ISSUE THREAD

**Issue by whazor** [tailwindlabs/tailwindcss#12674]
**What version of Tailwind CSS are you using?**

For example: 3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: tailwind-cli

**What version of Node.js are you using?**

For example: v18.18.2

**What browser are you using?**

For example: N/A

**What operating system are you using?**

For example: Linux

**Reproduction URL**

Reproduction: https://play.tailwindcss.com/k1etmM1OhZ?file=css

**Describe your issue**

![image](https://github.com/tailwindlabs/tailwindcss/assets/184182/1a080420-1715-47cd-a9c7-b93d6cc04219)

The issue is that the default variables get set globally and do not respect the `important` config var.

In particular, currently with `optimizeUniversalDefaults: true` and `important: ".scoped-down",`, we get:
```css
:is(.ring) {
  --tw-ring-inset:  ;
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgb(59 130 246 / 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  --tw-shadow-colored: 0 0 #0000;
}
```
But I would like to see:
```css
.scoped-down :is(.ring) {
  --tw-ring-inset:  ;
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgb(59 130 246 / 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  --tw-shadow-colored: 0 0 #0000;
}
```

Note, that without the experimental `optimizeUniversalDefaults`, the variables would be set on every element.
