### ISSUE TITLE
last-child:*:text-red-400 not working

### ISSUE THREAD

**Issue by MarkusWendorf** [tailwindlabs/tailwindcss#12810]
I expect this selector to work `last-child:*:text-red-400`.

Example: https://play.tailwindcss.com/AIGgGUvcSh
I would expect the generated css to look like the selector I manually wrote in the css tab. If you remove it, it stops working.

In contrast if you change it to be `last-of-type:*:text-red-400` it works out of the box.

:last-of-type generates:
```css
.last-of-type\:\*\:text-red-400 > *:last-of-type {
  --tw-text-opacity: 1;
  color: rgb(248 113 113 / var(--tw-text-opacity));
}
```

:last-child should generate:
```css
.last-child\:\*\:text-red-400 > *:last-child {
  --tw-text-opacity: 1;
  color: rgb(248 113 113 / var(--tw-text-opacity));
}
```
