### ISSUE TITLE
Support for css variables in box shadow

### ISSUE THREAD

**Issue by Kogomre** [tailwindlabs/tailwindcss#12861]
When I use css variables in box-shadow, the box shadow color does not work, which is why the shadow does not match the color that was specified, how can I fix this? and is it possible?

![image](https://github.com/tailwindlabs/tailwindcss/assets/43267690/9c945ead-742f-477b-bb29-23ab4d9f72af)

![image](https://github.com/tailwindlabs/tailwindcss/assets/43267690/c873b32a-be82-4834-93bf-310822686770)

**Comment by reinink** [comment]
Hey! So by default this doesn't work in Tailwind because of how we've had to implement colored box shadows. A little background on that first...

## How box-shadow colors work in Tailwind

Consider this (default) `shadow-lg` box-shadow configuration in Tailwind:

```js
lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
```

When Tailwind generates the utility for this shadow it automatically creates a `--tw-shadow-colored` variable that uses the same shadow definition, except it replaces the hard-coded colors with a `var(--tw-shadow-color)` variable.

Here's the CSS that's generated for this utility:

```css
.shadow-lg {
  --tw-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  --tw-shadow-colored: 0 10px 15px -3px var(--tw-shadow-color), 0 4px 6px -4px var(--tw-shadow-color);
  box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)
}
```

When applying a shadow color utility like `shadow-red-500`, we then set this `--tw-shadow-color` variable, and update the `--tw-shadow` variable to use the colored version of the shadow:

```css
.shadow-red-500 {
  --tw-shadow-color: #ef4444;
  --tw-shadow: var(--tw-shadow-colored);
}
```

It's a bit much to get your head wrapped around, but that's basically how you're able to use the box shadow color utilities to change the color of an existing shadow in a composable way.

## The problem with using box-shadow variables

Now let's look at your situation where you're using variables for your box shadows.

The issue when using a variable for the box-shadow is that the color variable never gets injected.

For example, this box-shadow configuration...

```js
lg: 'var(--box-shadow-lg)',
```

...results in this CSS:

```css
.shadow-lg {
  --tw-shadow: var(--box-shadow-lg);
  --tw-shadow-colored: var(--box-shadow-lg);
  box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)
}
```

Notice how both `--tw-shadow` and `--tw-shadow-colored` are both set to `var(--box-shadow-lg)`, and there is no `var(--tw-shadow-color)` anywhere? This is because Tailwind has no way of injecting it for you.

## How to use box-shadow variables with colors

That all said, you can inject the shadow color variable yourself when defining your shadow variables.

Continuing with the `shadow-lg` example, here's how you would do this:

```css
@layer base {
  * {
    --box-shadow-lg: 0 10px 15px -3px var(--tw-shadow-color, rgb(0 0 0 / 0.1)),
      0 4px 6px -4px var(--tw-shadow-color, rgb(0 0 0 / 0.1));
  }
}

```

Notice how I set a fallback of `rgb(0 0 0 / 0.1)` if no color is set — this is needed for when using the shadow without a color utility.

Here's a Tailwind Play illustrating how to do this: https://play.tailwindcss.com/utWZaUU9Me

Hope that helps! 🤙
