### ISSUE TITLE
[v4] When using a `reference` theme, `--default` variables don't work

### ISSUE THREAD

**Issue by Steffan153** [tailwindlabs/tailwindcss#13215]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Astro 4.5.2, Vite 5.1.6

**What version of Node.js are you using?**

Bun 1.0.30

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

Tailwind Play doesn't have v4 yet? But here's a link with the code (doesn't work) https://play.tailwindcss.com/NhYGudCbaL

**Describe your issue**

If I import the theme as a reference (`@import 'tailwindcss/theme' reference;`), many properties such as `transition` still look for `--default` variables:

```css
.transition-all {
    transition-property: all;
    transition-timing-function: var(--default-transition-timing-function);
    transition-duration: var(--default-transition-duration);
}
```

But those variables aren't set, so it doesn't work.
