### ISSUE TITLE
[Feature Proposal] More group targeting classes like group-hover 

### ISSUE THREAD

**Issue by royvanv** [tailwindlabs/tailwindcss#1331]
It would be nice to have more group targeting classes, such as the `group-hover` utility. 

I personally needed it to hide a child of a `last-child` element, so I wrote the following CSS.
```css
.group:last-child .last-group\:hidden {
    display: none;
}
```

Utilities I think could be useful with this new feature would be:
- first-child
- last-child
- odd-child
- even-child

Of course it would be disabled by default.
