### ISSUE TITLE
`important` option doesn't affect arbitrary properties

### ISSUE THREAD

**Issue by benface** [tailwindlabs/tailwindcss#13351]
**What version of Tailwind CSS are you using?**

For example: v3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

Tailwind Play

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/ZnkOJe6wYV

**Describe your issue**

In the reproduction, notice that because of the `important: ':root'` option, `[animation-duration:5s]` doesn't override the duration from `animate-spin`. That is because its generated CSS is:

```css
.\[animation-duration\:5s\]{
  animation-duration: 5s
}
```

instead of the expected:

```css
:root :is(.\[animation-duration\:5s\]){
  animation-duration: 5s
}
```
