### ISSUE TITLE
Generated css is not output from @tailwind directive

### ISSUE THREAD

**Issue by eloyesp** [tailwindlabs/tailwindcss#13803]
I were testing the following css:

~~~ css
@layer tailwind {
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
}

.foo {
  bar: "baz";
}
~~~

This would generate all the tailwind generated css on a real cascade layer named tailwind, and it does work as expected for most cases, but for some reason _some rules_ are generated outside of the layer and attached at the very end of the file instead:

For example: `text-black placeholder:text-red-200` on version `3.4.4` will generate: ([play](https://play.tailwindcss.com/YH2ly5iql6?file=css))

~~~ css
@layer tailwind {
  /* ! tailwindcss v3.4.4 | .. */
  .text-black {
    --tw-text-opacity: 1;
    color: rgb(0 0 0 / var(--tw-text-opacity));
  }
}
.foo {
  bar: "baz";
}
.placeholder\:text-red-200::placeholder {
  --tw-text-opacity: 1;
  color: rgb(254 202 202 / var(--tw-text-opacity));
}
~~~

Regards.

**Comment by adamwathan** [comment]
Hey! There's another rule called `@tailwind variants` that is implicitly inserted at the end of the file if it's not present. So this should work for you:

```css
@layer tailwind {
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
  @tailwind variants;
}

.foo {
  bar: "baz";
}
```
