### ISSUE TITLE
Gradients do not work in Firefox in v4.0.0-alpha.16, potentially caused by special `@supports (-moz-orient: inline)` selector

### ISSUE THREAD

**Issue by sceee** [tailwindlabs/tailwindcss#13948]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/13941 , since it is reproducible in tailwind play, I think it is indeed a bug and created the issue for it.

**What version of Tailwind CSS are you using?**

v4.0.0-alpha.16

**What build tool (or framework if it abstracts the build tool) are you using?**

`vite` v5.3.3, `@tailwindcss/vite` v4.0.0-alpha.16

**What version of Node.js are you using?**

v22.4.0

**What browser are you using?**

Chrome, Opera, Edge, Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

See the following example in Chrome vs. Firefox:
https://play.tailwindcss.com/ASf2fh5fiH

In Chrome it works but in Firefox the gradient is not displayed.
While I applied layers in the example, the same issue occurs if I just `@import 'tailwindcss';` instead:
https://play.tailwindcss.com/MPNPWOGHdL?file=css

**Describe your issue**

<div type='discussions-op-text'>

<sup>Originally posted by **sceee** July  3, 2024</sup>
Gradients do not seem to work in Firefox in `v4.0.0-alpha.16` whereas they work in Chrome.

See the following example in Chrome vs. Firefox:
https://play.tailwindcss.com/ASf2fh5fiH

In Chrome it works but in Firefox the gradient is not displayed.
While I applied layers in the example, the same issue occurs if I just `@import 'tailwindcss';` instead:
https://play.tailwindcss.com/MPNPWOGHdL?file=css

It seems in Firefox there is a special ruling applied to the element based on the `@supports (-moz-orient: inline)` selector. It seems this is injected here: https://github.com/tailwindlabs/tailwindcss/blob/62de02a37946c48c5fa6cdb800173b54198ebb9b/packages/tailwindcss/src/ast.ts#L202
```css
@supports (-moz-orient: inline) {
  @layer base {
    *, ::before, ::after, ::backdrop {
      --tw-gradient-from: #0000;
      --tw-gradient-to: #0000;
      --tw-gradient-via: transparent;
      --tw-gradient-stops: ;
      --tw-gradient-via-stops: ;
      --tw-gradient-from-position: 0%;
      --tw-gradient-via-position: 50%;
      --tw-gradient-to-position: 100%;
    }
  }
}
```

According to the Browser dev tools, `--tw-gradient-from`, `--tw-gradient-to` and `--tw-gradient-stops` are overwritten (and therefore not applied) but `--tw-gradient-via-stops` is set to [nothing] which seems to cause this issue.

If I disable the `--tw-gradient-via-stops` setting from this rule in the dev tools, the gradient also appears in Firefox.

Is this a known issue or shall I open a issue for this?</div>
