### ISSUE TITLE
Tailwindcss creates additional CSS rules when using class names with decimal fraction

### ISSUE THREAD

**Issue by obecker** [tailwindlabs/tailwindcss#13952]
**What version of Tailwind CSS are you using?**

v3.4.4

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 5.3.3 with postcss 8.4.39

**What version of Node.js are you using?**

v22.3.0

**What browser are you using?**

any

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/obecker/tailwind-issue

**Describe your issue**

When using size/spacing classes with a decimal fraction (like `m-1.5` or `size-2.5`) then tailwindcss will create extra (unused) rules for the corresponding classes without decimal fraction, i.e. there are also CSS rules for `m-1` or `size-2` like this (manually formatted for better readability):

```css
.m-1 {
    margin: .25rem
}

.m-1\.5 {
    margin: .375rem
}

.size-2 {
    width: .5rem;
    height: .5rem
}

.size-2\.5 {
    width: .625rem;
    height: .625rem
}
```

I think tailwindcss should not generate these extra CSS rules.
