### ISSUE TITLE
[v4] Border with arbitrary color using `var`

### ISSUE THREAD

**Issue by sntran** [tailwindlabs/tailwindcss#14181]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.18

**What build tool (or framework if it abstracts the build tool) are you using?**

`@tailwindcss/cli`

**What version of Node.js are you using?**

v20.12.2

**What browser are you using?**

Chrome version 127.0.6533.89 (Official Build) (arm64)

**What operating system are you using?**

macOS 14.5

**Reproduction URL**

https://play.tailwindcss.com/fCI06uutZE

**Describe your issue**

When setting a one-off border width with custom properties, Tailwind sees that as arbitrary value for color, not width.

Expected:

```html
border-b-[var(--spacing-4)]
``` 

outputs to 

```css
.border-b-\[var\(--spacing-4\)\] {
    border-bottom-width: var(--spacing-4);
}
```

Actual:

```css
.border-b-\[var\(--spacing-4\)\] {
    border-bottom-color: var(--spacing-4);
}
```
