### ISSUE TITLE
[v4] It seems that Oxide can't work with CSS Modules

### ISSUE THREAD

**Issue by mogeko** [tailwindlabs/tailwindcss#14211]
**What version of Tailwind CSS are you using?**

`v4.0.0-alpha.19`

**What build tool (or framework if it abstracts the build tool) are you using?**

vite: `v5.4.1`, @tailwindcss/vite: `4.0.0-alpha.19`

**What version of Node.js are you using?**

`v22.6.0`

**What browser are you using?**

Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-pzkrfk?file=src%2Fmain.ts

But it seems that [the node version of stackblitz](https://developer.stackblitz.com/codeflow/codeflow-faq#can-i-change-the-node-version) does not support TailwindCSS 4.0.

**Describe your issue**

I tried to use `prose.module.css`:

```css
@import '@fontsource-variable/fira-code' layer(base);

@theme {
  --font-family-mono: 'Fira Code Variable', ui-monospace, SFMono-Regular, Menlo,
    Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
}

.prose h1 {
  @apply text-4xl font-[900] lg:text-5xl font-mono;
}
```

But it looks like `@apply...` It has not been compiled.  `globals.css` is worked.

<img width="1116" alt="截屏2024-08-17 22 29 51" src="https://github.com/user-attachments/assets/8243c825-f31f-42f6-84ad-c730e5b82b29">

**Comment by philipp-spiess** [comment]
@mogeko This doesn't work because you're not referencing any `@tailwind` APIs in the CSS module file. For the tailwind compiler this means that there are no indications that you want tailwind to work in this file and we don't pull in any utilities or default themes.

How does your main Tailwind entrypoint `globals.css` file look like? What you can do is `@import` the `globals.css` from the CSS modules file if it is only extending the default Tailwind styles. e.g.:

```css
/* src/globals.css */
@import "tailwindcss";
@theme {
  /* your own theme overwrites */
}
```

```css
/* src/prose.module.css */
@import './globals.css' theme(reference);
@import '@fontsource-variable/fira-code' layer(base);

@theme {
  --font-family-mono: 'Fira Code Variable', ui-monospace, SFMono-Regular, Menlo,
    Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
}

.prose h1 {
  @apply text-4xl font-[900] lg:text-5xl font-mono;
}
```
