### ISSUE TITLE
[v4] theme() function does not work with media query range syntax operators

### ISSUE THREAD

**Issue by boylett** [tailwindlabs/tailwindcss#14320]
**What version of Tailwind CSS are you using?**
`4.0.0-alpha.21`

**What build tool (or framework if it abstracts the build tool) are you using?**
Remix, Vite

**What version of Node.js are you using?**
`22.4.1`

**What browser are you using?**
Chrome, Safari and Firefox

**What operating system are you using?**
macOS Sonoma 14.6.1

**Reproduction URL**
[https://github.com/boylett/tailwindcss-v4-theme-in-media-bug](https://github.com/boylett/tailwindcss-v4-theme-in-media-bug)

**Describe your issue**
Using `theme()` in media queries does not work when using range syntax operators such as `<=` and `>=`.
See [root.css](https://github.com/boylett/tailwindcss-v4-theme-in-media-bug/blob/main/app/root.css) in the repro.

**Comment by philipp-spiess** [comment]
@boylett Hey! Thanks for the report. In the repro you have no space between the `>=` and `theme()` function which is why it fails right now. So this should work temporarily:

```css
@import "./tailwind.css";

body {
  background: lightblue;

  /* Body correctly turns pink past 640px */
  @media (max-width: theme(--breakpoint-mobile)) {
    background: pink;
  }

  /* Body should turn lightyellow past 960px but does not */
  @media (width >= theme(--breakpoint-tablet)) {
    background: lightyellow;
  }
}
```

However, you are right that this should work even without a space after the comperator sign. I'll look into it.
