### ISSUE TITLE
[v4] @apply doesn't combine rules under a single selector

### ISSUE THREAD

**Issue by ktmn** [tailwindlabs/tailwindcss#14654]
**What version of Tailwind CSS are you using?**
v4.0.0-alpha.26

**Reproduction URL**
https://play.tailwindcss.com/UExmfuz56x?file=css

**Describe your issue**
Is it intended that 

```css
@layer utilities {
  .parent {
    @apply m-4 p-4 [&>.child]:m-4 [&>.child]:p-4;
  }
}
```

produces:

```css
.parent {
  margin: var(--spacing-4, 1rem);
  padding: var(--spacing-4, 1rem);
  &>.child {
    margin: var(--spacing-4, 1rem);
  }
  &>.child {
    padding: var(--spacing-4, 1rem);
  }
}
```

rather than:

```css
.parent {
  margin: var(--spacing-4, 1rem);
  padding: var(--spacing-4, 1rem);
  &>.child {
    margin: var(--spacing-4, 1rem);
    padding: var(--spacing-4, 1rem);
  }
}
```
