### ISSUE TITLE
[v4]: combine `peer-` with other variants

### ISSUE THREAD

**Issue by sntran** [tailwindlabs/tailwindcss#14782]
**What version of Tailwind CSS are you using?**

tailwindcss v4.0.0-alpha.29

**What build tool (or framework if it abstracts the build tool) are you using?**

@tailwindcss/cli v4.0.0-alpha.29

**What version of Node.js are you using?**

Node v20.12.2

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/hqwKODvklG

**Describe your issue**

A variant such as `is-summary` should be combinable with `peer-` to be effective, e.g. `peer-is-summary:bg-amber-400`.

Currently, the generated CSS is

```css
.\*\:peer-is-summary\:bg-amber-400 {
  :where(& > *) {
    &:is(:where(.peer):is(summary) ~ *) {
      background-color: var(--color-amber-400, oklch(0.828 0.189 84.429));
    }
  }
}
```

While that is correct with `peer-` expecting a previous sibling with `.peer` class, I can't find a way to add that when I don't have control over the markup. `*:is-summary:peer` does not work.

In this particular use case, `is-` variants are special because they already target a certain element, so requiring `.peer` may not be necessary.

Would this be a use case to have `is-*` varirants (with `*` can be any arbitrary selector) built in Tailwind?
