### ISSUE TITLE
[v4] clearing namespace for corePlugin doesn't work

### ISSUE THREAD

**Issue by rj-elias** [tailwindlabs/tailwindcss#14819]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.30

**Reproduction URL**

https://play.tailwindcss.com/bjEOmfVaL9

**Describe your issue**

```css
@theme {
  --background-color-*: initial; /* DO NOT WORK: doesn't clear the background color namespace */
  --background-color-brand: blue; /* WORKS: extends the background color namespace with brand */
}
```

`--background-color-brand: blue;` works. It extends the background color namespace with 'brand'

`--color-*: initial;` works. It clear the whole color namespace
`--background-color-*: initial;` doesn't clear the background color namespace

**Comment by rose21wiley** [comment]
There seems to be an inconsistency with how Tailwind CSS handles clearing namespaces for custom properties. Your observation that --background-color-*: initial; doesn't clear the namespace while --color-*: initial; does, suggests a possible bug or limitation in the current alpha version you're using.

Recommendations:

Verify your tailwind.config.js setup.
Simplify your calc() usage to isolate the issue.
Use custom CSS for complex transforms.
Check browser support and update all dependencies.

**Comment by rj-elias** [comment]
@cossssmin my question is more on applying colors only for `bg` or `border` rather than for all color. In v3 you can do that

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    spacing: {
      // ...
    },
    backgroundColor: {
      newcolor: '#blue-value',
    }
  }
}
```
`bg-newcolor` will exists. But `borer-newcolor` or `text-newcolor` will not.

**Comment by cossssmin** [comment]
Oh, ok, then you don't even need to reset the namespace:

```css
@import "tailwindcss";

@theme {
  --background-color-brand: blue;
}
```

```html
<!-- blue background, browser default text color -->
<p class="bg-brand text-brand">Hello world</p>
```

Demo: https://play.tailwindcss.com/jPdur1FNp2
