### ISSUE TITLE
[v4] Chaining arbitrary variants with BEM-like partial class name selectors no longer works

### ISSUE THREAD

**Issue by ktmn** [tailwindlabs/tailwindcss#14844]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha30

**Reproduction URL**

https://play.tailwindcss.com/cRu9890fAn

**Describe your issue**

With markup like this:

```html
<div class="...tailwind classes...">
  <ul class="tw3-list"><!-- 3rd-party HTML I don't control, for example -->
    <li class="tw3-list__item"></li>
    <li class="tw3-list__item tw3-list__item--active"></li>
  </ul>
</div>
```

a regression I noticed when using chained variants like `[&--active]:[&\_\_item]:[&_.tw3-list]` (which I understand should be reversed in TW4) to create a selector for `.tw3-list__item--active` no longer works with Tailwind 4 and the CSS nesting it's using.

Now it seems to generate this:

```css
.\[\&_\.tw4-list\]\:\[\&\\_\\_item\]\:\[\&--active\]\:font-black {
  & .tw4-list {
    &__item {
      &--active {
        --tw-font-weight: 900;
        font-weight: 900;
      }
    }
  }
}
```

which, when run through LightningCSS default playground, collapses to this:

```css
--active__item:is(.\[\&_\.tw4-list\]\:\[\&\\_\\_item\]\:\[\&--active\]\:font-black .tw4-list) {
  --tw-font-weight: 900;
  font-weight: 900;
}
```

I'm not sure if it was ever intended to be supported but since it used to work, and now doesn't appear to, I thought I'd mention it here. No worries if it won't be supported, there's plenty of ways to do it differently.
