### ISSUE TITLE
Special character in group-has-[xxx] not escaped

### ISSUE THREAD

**Issue by HexMox** [tailwindlabs/tailwindcss#15007]
**What version of Tailwind CSS are you using?**

v3.4.13

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.47, Next.js 14.2.8

**What version of Node.js are you using?**

v18.20.4

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

N/A

**Describe your issue**

<img width="958" alt="image" src="https://github.com/user-attachments/assets/528e5d9c-6d25-4b6c-b310-74f9f9a8154d">

The colon in css result .group:has(xxx) is unescaped

**Comment by philipp-spiess** [comment]
@HexMox Thanks for the report! Seems like to be an issue in v4 as well:

```css
.has-\[\.sm\:sticky\]\:underline:has(*:is(.sm:sticky)) {
  text-decoration-line: underline;
}
```
