### ISSUE TITLE
[v4] --letter-spacing not included in the final CSS

### ISSUE THREAD

**Issue by Maarten-Dekker** [tailwindlabs/tailwindcss#15096]
**What version of Tailwind CSS are you using?**

v4.0.0-beta.1

**Reproduction URL**

https://play.tailwindcss.com/Z3dDT7wulJ

**Describe your issue**

When the following CSS is supplied:

```css
@theme {
    --text-heading3xl: 2.25rem;
    --text-heading3xl--line-height: 3rem;
    --text-heading3xl--font-weight: 700;
    --text-heading3xl--letter-spacing: -0.03375rem;
}
```

It is translated into the following CSS output:

```css
.text-heading3xl {
    font-size: var(--text-heading3xl);
    line-height: var(--tw-leading, var(--text-heading3xl--line-height));
    font-weight: var(--tw-font-weight, var(--text-heading3xl--font-weight));
}
```

So, the provided letter spacing is missing from the final output.
