### ISSUE TITLE
[v4] disabling new :hover variant

### ISSUE THREAD

**Issue by cossssmin** [tailwindlabs/tailwindcss#15124]
**What version of Tailwind CSS are you using?**

v4.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

`@maizzle/framework@v5.0.0-beta.32` (modified for Tailwind v4 testing, repro below)

**What version of Node.js are you using?**

v20.10.0

**What browser are you using?**

N/A

**What operating system are you using?**

Windows 11

**Reproduction URL**

https://github.com/maizzle/tailwindcss.v4-test

See the [starter/_dist/emails](https://github.com/maizzle/tailwindcss.v4-test/tree/master/starter/_dist/emails) folder for the compiled HTML, with CSS.

**Describe your issue**

```hbs
<style>
	@import "tailwindcss/theme";
	@import "tailwindcss/utilities";
	@variant hover (&:hover);
</style>

<a class="hover:text-red-200">...</a>
````

Compiled CSS:

```css
.hover\:text-red-200 {
  &:hover {
    color: var(--color-red-200);
  }
}
```

Expected:

```css
.hover\:text-red-200:hover {
  color: var(--color-red-200);
}
```
