### ISSUE TITLE
[v4] Wrong value for `rounded-full` utility on build 

### ISSUE THREAD

**Issue by czernika** [tailwindlabs/tailwindcss#15155]
Using `rounded-full` both in TailwindPlay and running `dev` locally produces desired result but on a build it calculates incorrect value

```sh
vite // OK

vite build // not
```

![Снимок экрана от 2024-11-24 18-11-15](https://github.com/user-attachments/assets/86502425-6a1f-4cf1-983f-de09b99cd818)

```css
.rounded-full{
    border-radius:3.40282e2.375rem
}
```

**What version of Tailwind CSS are you using?**

v4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite v5.4.8

**What version of Node.js are you using?**

v20.18.1

**What browser are you using?**

Firefox, Chrome

**What operating system are you using?**

Linux Ubuntu 24.04 (as well as 22.04 on Docker)

**Reproduction URL**

As I said cannot reproduce it in TailwindPlay it happens only on build

**Comment by adamwathan** [comment]
Hey! Can you create a GitHub repo that reproduces? When I try this locally with Vite I get this value which is valid and works as expected in the browser:

```css
.rounded-full {
  border-radius: 3.40282e38px;
}
```
