### ISSUE TITLE
[v4] float-start and inline-start generate invalid values

### ISSUE THREAD

**Issue by ktmn** [tailwindlabs/tailwindcss#15255]
**What version of Tailwind CSS are you using?**

`v3.4.15` vs `v4.0.0-beta.4`

**What build tool (or framework if it abstracts the build tool) are you using?**

Tested in playground only

**Reproduction URL**

https://play.tailwindcss.com/AGmhqrluog

**Describe your issue**

Utilities `float-start` and `clear-start` generate this with TW3:

```css
.float-start {
  float: inline-start;
}
.clear-start {
  clear: inline-start;
}
```

and this with TW4:

```css
.float-start {
  float: start;
}
.clear-start {
  clear: start;
}
```

which seem to be "Invalid property value"-s according to Chrome/Firefox dev tools.
