### ISSUE TITLE
[v4] `group-hover/xyz` does not seem to work

### ISSUE THREAD

**Issue by sntran** [tailwindlabs/tailwindcss#15382]
**What version of Tailwind CSS are you using?**

v4.0.0-beta.6

**What build tool (or framework if it abstracts the build tool) are you using?**

`@tailwindcss/cli@4.0.0-beta.6`

**What version of Node.js are you using?**

For example: v20.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/cRzRsGwYGV

**Describe your issue**

When hovering on a group with `group/tag`, the element with `group-hover/tag` did not get styles applied.

The generated CSS is:

```css
.group-hover\/primary\:text-red-500 {
  &:is(:where(.group\/primary):hover *) {
    @media (hover: hover) {
      color: var(--color-red-500);
    }
  }
}
```
