### ISSUE TITLE
Space following child combinator in has- rule does not work.

### ISSUE THREAD

**Issue by ZebraNorth** [tailwindlabs/tailwindcss#15521]
**What version of Tailwind CSS are you using?**

v3.4.15 and v4.0.0-beta.8

**What build tool (or framework if it abstracts the build tool) are you using?**

play.tailwindcss.com

Chrome, Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/98OgkmHpXk

**Describe your issue**

The selector `has-[>.target]` works, but `has-[> .target]` does not work. The only difference is a space following the `>` symbol, which I believe should not make a difference.

Without the space, it correctly generates the CSS: 

```css
.has-\[\>\.target\]\:bg-green-400:has(>.target) {
  --tw-bg-opacity: 1;
  background-color: rgb(74 222 128 / var(--tw-bg-opacity, 1));
}
```

**No CSS at all is output the for the version with the space.**
