### ISSUE TITLE
[v4] `@apply` incorrectly generate `:dark` variant inside `:before` pseudo selector

### ISSUE THREAD

**Issue by dimaMachina** [tailwindlabs/tailwindcss#15597]
### Input

```css
h2 {
  @apply dark:before:bg-green-900;
}
```

### Output (generates `&:where(.dark *) { &::before` ) ✅ 

```css
h2 {
  &:where(.dark *) {
    &::before {
      content: var(--tw-content);
      background-color: var(--color-green-900);
    }
  }
}
```

### Input

```css
h2 {
  &:before {
    @apply dark:bg-red-500 content-['dada'];
  }
}
```

### Output  (generates `&:before { &:where(.dark *)` ) ❌ 

```css
h2 {
  &:before {
    --tw-content: 'dada';
    content: var(--tw-content);
    &:where(.dark *) {
      background-color: var(--color-red-500);
    }
  }
}
```

**Comment by RobinMalfait** [comment]
Hey!

This is on purpose, `@apply` just allows you to substitute classes and replace them with its implementation. We don't validate the output and also don't try to fix invalid CSS to generate valid CSS. Instead, the provided input should be valid already.

For example, the order of variants matter, so while it's true that it correctly generates for:
```css
h2 {
  @apply dark:before:bg-green-900;
}
```

It doesn't if you swap the `dark` and `before` variants:
```css
h3 {
  @apply before:dark:bg-green-900;
}
```

This would be the generated output:
```css
h2 {
  &:where(.dark *) {
    &::before {
      content: var(--tw-content);
      background-color: var(--color-green-900);
    }
  }
}
h3 {
  &::before {
    content: var(--tw-content);
    &:where(.dark *) {
      background-color: var(--color-green-900);
    }
  }
}
```

Notice how the `&::before` and `&:where(.dark *)`'s locations are swapped.

In your case, you should make sure that the order is swapped as well. You can do this by moving the `&:before` inside your classes as a variant. This gives you more control over its location:
```css
h2 {
  @apply dark:before:bg-red-500 before:content-['dada'];
}
```

Which now properly compiles to:
```css
h2 {
  &::before {
    content: var(--tw-content);
    --tw-content: 'dada';
    content: var(--tw-content);
  }
  &:where(.dark *) {
    &::before {
      content: var(--tw-content);
      background-color: var(--color-red-500);
    }
  }
}
```

Hope this helps!
