### ISSUE TITLE
Can't unset font-weights in v4

### ISSUE THREAD

**Issue by idan-faibish** [tailwindlabs/tailwindcss#15811]
**What version of Tailwind CSS are you using?**

v4.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

vite v6.0.3

**What version of Node.js are you using?**

v20.13.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

I just started to use tailwind (jumped straight to v4) and I'm building my existing design system under my css file. I'm not sure what I'm doing wrong but I tried plenty of options and I just cant to unset all the existing tailwind's font-weights.
```css
@theme {
    /* tried to unset this */
    --font-*: initial;
    /* and also this */
    --font-weight-*: initial;

    --font-weight-extraBold: 800;
    --font-weight-bold: 700;
    --font-weight-semiBold: 600;
    --font-weight-normal: 400;
}
```

here it what I get on intellisense, it even multiplies the stuff

![Image](https://github.com/user-attachments/assets/18316ff1-c9a5-48f6-af21-73c82a4acc88)
