### ISSUE TITLE
Bug: CSS Variables in `@theme`, `@layer base`, and `:root` do Not Inherit Inline style Values in Tailwind CSS v4

### ISSUE THREAD

**Issue by sangrepura** [tailwindlabs/tailwindcss#15874]
## What version of Tailwind CSS are you using?
v4.0.0

## What build tool are you using?
Tailwind Playground

## What version of Node.js are you using?
N/A

## What browser are you using?
Chromium to 132.0.6834.111.

## What operating system are you using?
macOS Sonoma 14.5

## Reproduction URL
[Tailwind Play](https://play.tailwindcss.com/7N0n8QrcVe)

### Expected Behavior:

CSS variables defined via `@theme`, `@layer base`, `:root`, and global scope should inherit the value set inline via `style="--var: foo;"`

#### Only these scenarios work:

- Direct Tailwind color w or w/out use of var (`text-[var(--color-red-500)])`)

- Direct Custom Tailwind color  (`text-less-cool`)

- Class-scoped variable (`text-[var(--color-class-cool)]` - i.e. when using my `.cool` class)

#### These scenarios fail:

- Theme-layer variable (`--color-theme-cool`)

- Base-layer variable (`--color-base-cool`)

- Root-scoped variable (`--color-root-cool`)

### Steps to Reproduce:

Define CSS variables using multiple scoping methods:

```css
@import "tailwindcss";

@theme {
  --color-less-cool: #A5B937;
  --color-theme-cool: var(--cool);
}

@layer base {
  :root {
    --color-base-cool: var(--cool);
  }
}

.cool {
  --color-class-cool: var(--cool);
}

:root {
  --color-root-cool: var(--cool);
}

```

```html
<h1 class="text-6xl text-[var(--color-red-500)]" style="--cool: #FE9900;">Hello</h1>

<h1 class="text-6xl text-less-cool" style="--cool: #FE9900;">Hello</h1>

<h1 class="text-6xl text-theme-cool" style="--cool: #FE9900;">Hello</h1>

<h1 class="text-6xl text-[var(--color-theme-cool)]" style="--cool: #FE9900;">Hello</h1>

<h1 class="text-6xl text-[var(--color-base-cool)]" style="--cool: #FE9900;">Hello</h1>

<h1 class="text-6xl text-[var(--color-root-cool)]" style="--cool: #FE9900;">Hello</h1>

<h1 class="cool text-6xl text-[var(--color-class-cool)]" style="--cool: #FE9900;">Hello</h1>
```

### Workaround: 

Variables scoped to a class (.cool) work correctly, suggesting a scoping/context issue with theme/base-layer variables.

### Additional Notes:

Tailwind's layer system doesn't appear to respect inline variable definitions

Variables declared in :root don't inherit values from element-scoped --cool

Only class-scoped variables work as expected

This used to work for me in v3
