### ISSUE TITLE
[v4] variants are not working on layer defined components and utilities

### ISSUE THREAD

**Issue by lubomirblazekcz** [tailwindlabs/tailwindcss#16000]
**What version of Tailwind CSS are you using?**
v4.0.0

**Reproduction URL**

v3.4.15 - https://play.tailwindcss.com/t7YcGka233
v4.0.0 - https://play.tailwindcss.com/KCVjmX1VxW

Following style should be applied, works for v3 not for v4
```css
@media (min-width: 768px) {
  .x-button:is(.md\:square) {
    --x-button-padding-block: 0;
    --x-button-padding-inline: 0;
    --x-button-inline-size: var(--x-button-block-size);
  }
}
```

**Describe your issue**

Previously on v3 components and utilities could be defined via layers, this was also recommended in docs ([v4](https://tailwindcss.com/docs/adding-custom-styles#adding-component-classes), [v3](https://v3.tailwindcss.com/docs/adding-custom-styles#adding-component-classes)). 

Variants worked on these classes, not anymore in v4. Some UI frameworks for TailwindCSS use this for component variants, eg. [DaisyUI](https://daisyui.com/components/button/#responsive-button) or [Winduum](https://winduum.dev/docs/components/button.html).

Eg: responsive button
```html
// DaisyUI
<button class="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg">Responsive</button>

// Winduum
<button class="x-button md:square">Button</button>
```

[DaisyUI v5](https://github.com/saadeghi/daisyui/blob/v5/packages/daisyui/index.js) solves this limitation in v4 by importing styles via javascript plugin. [Winduum](https://winduum.dev/docs/) tries to use CSS only configuration for v4, and [every component](https://github.com/winduum/winduum/tree/main/src/components/button) is compatibile with native CSS.

Winduum v2.1 supports TailwindCSS v4 completely, but this is the only current limitation, which is not in TailwindCSS v3.

I understand that alternative is to newly define everything via `@utility`, but that is limitng and not backward compatible with v3.

**Comment by RobinMalfait** [comment]
Hey!

You can still define components using `@layer components`, however that means that you can't use them with any variants such as `md:my-component`. This is because we are no longer hijacking `@layer`, and instead rely on real layers to put your CSS in a logical spot.

> In v4 we are using native cascade layers and no longer hijacking the @layer at-rule, so we've introduced the @utility API as a replacement:

In your case, the `btn` can still be a component defined via `@layer components` (because it's just a class, and not used with any variants or other Tailwind CSS specific features like `btn!` or with a prefix).

The part that cannot be a component, but should be a utility is the `md:square` part. The `square` should be a utility. This is because you are applying variants on top of the class.

If you use the upgrade tool then we update the `@layer components` to make use of `@utility`, so while it's a breaking change, the upgrade tool should help.

In this case, the `.square` related class is the only one that needs to go in a utility (at least, if you look at the minimal reproduction, which I appreciate!):
```css
@utility square {
  .x-button:is(&) {
    --x-button-padding-block: 0;
    --x-button-padding-inline: 0;
    --x-button-inline-size: var(--x-button-block-size);
  }
}
```

This is necessary so that the `.square` class can become `.md\:square` when using it with a variant.

As mentioned earlier, we try to be backwards compatible as much as possible and where we can't we tried to make the upgrade process as smooth as possible using the upgrade tool.

But I hope this solution works where you only need to define `@utility` for the parts that use Tailwind CSS specific features.

Hope this helps!
