### ISSUE TITLE
[v4] Cannot apply unknown utility class: group

### ISSUE THREAD

**Issue by robertjf** [tailwindlabs/tailwindcss#16034]
**What version of Tailwind CSS are you using?**

For example: v4.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 6.0.5 with vue 3.5.13

**What version of Node.js are you using?**

Node.js v22.6.0 / npm 10.8.2

**What browser are you using?**

Edge/Chrome

**What operating system are you using?**

macOS

**Describe your issue**

When I attempt to `@apply` `group` or `peer` to a class it displays the "Cannot apply unknown utility class: {group or peer}" message.

I've tried `@referencing` the tailwindcss, the configuration file, etc.  but nothing's helping.

Base Stylesheet:
```css
@import "tailwindcss";
@import "./theme/settings.css";

@import "./theme/components/umbraco-forms.css";

html, body {
  @apply antialiased;
}
```

theme/settings.css:
```css
@theme {
  --color-ys-red: #FE5C48;
  --color-ys-off-white: #F8F6F2;
  --color-ys-green: #2E4039;
  --color-ys-dark-green: #25342e;
  --color-ys-gold: #DCD0A9;
  --color-ys-black: #0F0F0F;
}
```

theme/components/forms.css (`group` on `.umbraco-forms-field` throws the error - everything else compiles just fine without it):
```css
@layer components {
    .umbraco-forms-field {
        @apply relative group rounded bg-ys-off-white text-ys-black 
        px-4.5 pb-2.5 pt-4.5
        outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-ys-gold
        in-invalid:bg-ys-red;
    }

    .umbraco-forms-label {
        @apply absolute in-focus:top-1 in-focus:text-xs not-in-placeholder-shown:text-xs not-in-placeholder-shown:top-1;
    }

    .umbraco-forms-field-wrapper {
        input, textarea {
            @apply block w-full placeholder:text-transparent in-focus:placeholder:text-gray-400 focus:outline-0 sm:text-sm/6 invalid:text-ys-red;
        }
    }
}
```

**Comment by robertjf** [comment]
Update: I just upgraded to tailwind 4.0.1 and the issue persists...

**Comment by wongjn** [comment]
You probably need to use [the `@reference` directive](https://tailwindcss.com/docs/functions-and-directives#reference-directive).
---
As an aside, Adam Wathan (creator of Tailwind) does seem to advocate avoiding `@apply`:
- https://twitter.com/adamwathan/status/1226511611592085504
- https://twitter.com/adamwathan/status/1559250403547652097

**Comment by robertjf** [comment]
@wongjn I did apply `@reference` but it made no difference...

I know, I don't like to use @apply, but in this case I'm dealing with re-styling third party markup :(

**Comment by wongjn** [comment]
Sorry, missed that you already tried that from your post the first time around.

`group` in itself is not a utility class, it is only a signifier. for the `group-*:` variant, hence the error.

Even when dealing with re-styling third-party markup, you should use regular CSS instead of `@apply`.

**Comment by RobinMalfait** [comment]
Hey!

This issue is happening because `group` is not a utility in Tailwind CSS. It's used as a marker class for other utilities e.g.: `group-hover:flex` which will generate:

```css
@media (hover: hover) {
  .group-hover\:flex:is(:where(.group):hover *) {
      display: flex;
  }
}
```

Notice the `:where(.group)`, that's the only place `.group` is used, and the variant is just looking for the `group` class.

This behavior is the same as in Tailwind CSS v3: https://play.tailwindcss.com/TaSPywcxyF?file=css

The solution is to not use `@apply group` at all, and if you are using any `group-*` variant in a child-element, you have 2 options:
1. Also make sure to use `group` as one of the classes in your HTML.
2. Instead of using `group-*` variants, you can use `in-[.umbraco-forms-field]:` to know when you are in a certain class for example (but then it gets a bit more tricky to also add variants to these classes).

I would recommend to try and not use `@apply` at all here, and if you really want to, add the `group` class on the element with `umbraco-forms-field`.

Hope this helps!
