### ISSUE TITLE
Tailwind uses incorrect css variable for `max-w-*` utilities

### ISSUE THREAD

**Issue by lid0a** [tailwindlabs/tailwindcss#16047]
**What version of Tailwind CSS are you using?**

v4.0.1

**Reproduction URL**

https://play.tailwindcss.com/1GwByGuLR3?file=css

**Describe your issue**

I have custom theme variables in my project, such as `--spacing-sm`, `--spacing-md`, etc.

When using the utility `max-w-sm`, I expect tailwind to generate the following CSS:  

```css
max-width: var(--container-sm);
```  

However, it instead generates:  

```css
max-width: var(--spacing-sm);
```  

It seems like tailwind is resolving `sm` to the `--spacing-sm` variable instead of `--container-sm` which leads to unexpected behavior.

**Comment by lid0a** [comment]
Actually, I'm confused. When I'm using `--spacing-*` variables, I expect they are applied only to "spacing" utilities (paddings, margins, gaps), not "size" utilities like `w`, `h`, `max-w`, etc. Any workarounds for my case, other than:
```css
@utility max-w-sm {
  max-width: var(--container-sm) !important;
}
```
?

**Comment by elalemanyo** [comment]
I have had the same problem as @lid0a. It is true that it seems that before it worked the same, but adding spacings like `sm`, `md` or `lg` did not break all the classes related to the sizes (`w`, `min-w`, `max-w` ...)

The problem comes from this part of the code:
https://github.com/tailwindlabs/tailwindcss/blob/83fdf373aa729bc1beae1a64c9c0bba76f3b2c2f/packages/tailwindcss/src/utilities.ts#L914-L925

I think a good idea would be to add the possibility to separate between `spacing` and `sizing`.

```js
  for (let [name, namespaces, property] of [
    ['w', ['--width', '--size', '--spacing', '--container'], 'width'],
    ['min-w', ['--min-width', '--size', '--spacing', '--container'], 'min-width'],
    ['max-w', ['--max-width', '--size', '--spacing', '--container'], 'max-width'],
    ['h', ['--height', '--size', '--spacing'], 'height'],
    ['min-h', ['--min-height', '--height', '--size', '--spacing'], 'min-height'],
    ['max-h', ['--max-height', '--height', '--size', '--spacing'], 'max-height'],
  ] as [string, ThemeKey[], string][]) {
    spacingUtility(name, namespaces, (value) => [decl(property, value)], {
      supportsFractions: true,
    })
  }
```

![Image](https://github.com/user-attachments/assets/fd390193-d3a0-445b-af89-e34174879188)

WDYT @RobinMalfait?

@lid0a For the moment the solution I have found is to re-add the default values to correct the values generated by adding the `spacing`:

```css
@theme {
  --spacing-xxs: 0.25rem;  /* 4px */
  --spacing-xs: 0.5rem;    /* 8px */
  --spacing-sm: 1rem;      /* 16px */
  --spacing-md: 1.5rem;    /* 24px */
  --spacing-lg: 2rem;      /* 32px */
  --spacing-xl: 2.5rem;    /* 40px */
  --spacing-2xl: 3rem;     /* 48px */
  --spacing-3xl: 3.5rem;   /* 56px */
  --spacing-4xl: 4rem;     /* 64px */
  --spacing-5xl: 4.5rem;   /* 72px */
  --spacing-6xl: 5rem;     /* 80px */

  --size-3xs: 16rem;
  --size-2xs: 18rem;
  --size-xs: 20rem;
  --size-sm: 24rem;
  --size-md: 28rem;
  --size-lg: 32rem;
  --size-xl: 36rem;
  --size-2xl: 42rem;
  --size-3xl: 48rem;
  --size-4xl: 56rem;
  --size-5xl: 64rem;
  --size-6xl: 72rem;
  --size-7xl: 80rem;

  --container-3xs: var(--size-3xs);
  --container-2xs: var(--size-2xs);
  --container-xs: var(--size-xs);
  --container-sm: var(--size-sm);
  --container-md: var(--size-md);
  --container-lg: var(--size-lg);
  --container-xl: var(--size-xl);
  --container-2xl: var(--size-2xl);
  --container-3xl: var(--size-3xl);
  --container-4xl: var(--size-4xl);
  --container-5xl: var(--size-5xl);
  --container-6xl: var(--size-6xl);
  --container-7xl: var(--size-7xl);

  --width-3xs: var(--size-3xs);
  --width-2xs: var(--size-2xs);
  --width-xs: var(--size-xs);
  --width-sm: var(--size-sm);
  --width-md: var(--size-md);
  --width-lg: var(--size-lg);
  --width-xl: var(--size-xl);
  --width-2xl: var(--size-2xl);
  --width-3xl: var(--size-3xl);
  --width-4xl: var(--size-4xl);
  --width-5xl: var(--size-5xl);
  --width-6xl: var(--size-6xl);
  --width-7xl: var(--size-7xl);

  --min-width-3xs: var(--size-3xs);
  --min-width-2xs: var(--size-2xs);
  --min-width-xs: var(--size-xs);
  --min-width-sm: var(--size-sm);
  --min-width-md: var(--size-md);
  --min-width-lg: var(--size-lg);
  --min-width-xl: var(--size-xl);
  --min-width-2xl: var(--size-2xl);
  --min-width-3xl: var(--size-3xl);
  --min-width-4xl: var(--size-4xl);
  --min-width-5xl: var(--size-5xl);
  --min-width-6xl: var(--size-6xl);
  --min-width-7xl: var(--size-7xl);

  --max-width-3xs: var(--size-3xs);
  --max-width-2xs: var(--size-2xs);
  --max-width-xs: var(--size-xs);
  --max-width-sm: var(--size-sm);
  --max-width-md: var(--size-md);
  --max-width-lg: var(--size-lg);
  --max-width-xl: var(--size-xl);
  --max-width-2xl: var(--size-2xl);
  --max-width-3xl: var(--size-3xl);
  --max-width-4xl: var(--size-4xl);
  --max-width-5xl: var(--size-5xl);
  --max-width-6xl: var(--size-6xl);
  --max-width-7xl: var(--size-7xl);

  --height-3xs: var(--size-3xs);
  --height-2xs: var(--size-2xs);
  --height-xs: var(--size-xs);
  --height-sm: var(--size-sm);
  --height-md: var(--size-md);
  --height-lg: var(--size-lg);
  --height-xl: var(--size-xl);
  --height-2xl: var(--size-2xl);
  --height-3xl: var(--size-3xl);
  --height-4xl: var(--size-4xl);
  --height-5xl: var(--size-5xl);
  --height-6xl: var(--size-6xl);
  --height-7xl: var(--size-7xl);

  --min-height-3xs: var(--size-3xs);
  --min-height-2xs: var(--size-2xs);
  --min-height-xs: var(--size-xs);
  --min-height-sm: var(--size-sm);
  --min-height-md: var(--size-md);
  --min-height-lg: var(--size-lg);
  --min-height-xl: var(--size-xl);
  --min-height-2xl: var(--size-2xl);
  --min-height-3xl: var(--size-3xl);
  --min-height-4xl: var(--size-4xl);
  --min-height-5xl: var(--size-5xl);
  --min-height-6xl: var(--size-6xl);
  --min-height-7xl: var(--size-7xl);

  --max-height-3xs: var(--size-3xs);
  --max-height-2xs: var(--size-2xs);
  --max-height-xs: var(--size-xs);
  --max-height-sm: var(--size-sm);
  --max-height-md: var(--size-md);
  --max-height-lg: var(--size-lg);
  --max-height-xl: var(--size-xl);
  --max-height-2xl: var(--size-2xl);
  --max-height-3xl: var(--size-3xl);
  --max-height-4xl: var(--size-4xl);
  --max-height-5xl: var(--size-5xl);
  --max-height-6xl: var(--size-6xl);
  --max-height-7xl: var(--size-7xl);
}
```
