### ISSUE TITLE
[v4] Classes defined in @layer components no longer generated with modifiers

### ISSUE THREAD

**Issue by pedenys** [tailwindlabs/tailwindcss#16110]
**What version of Tailwind CSS are you using?**

`v4.0.1`

**What build tool (or framework if it abstracts the build tool) are you using?**

Astro.js `v5.1.9` but can be reproduced with the Tailwind playground

**What version of Node.js are you using?**

`v22.11.0`

**What browser are you using?**

Firefox Developer Edition `v22.11.0`

**What operating system are you using?**

MacOS 15.2 (24C101)

**Reproduction URL**

https://play.tailwindcss.com/aRX8gpP3Vu?file=css

**Describe your issue**

It seems classes defined inside `@layer components` are no longer generated with their modifiers along-side.

Original code : 

```html
<div class="baba md:yaga hover:jeff">
  <p>Slayer</p>
</div>
```

```css
@import "tailwindcss";

@theme {
  /* ... */
}

@layer components {
  .baba {
    background-color: green;
    border-radius: var(--rounded-sm);
    padding: var(--spacing-1);
    box-shadow: var(--shadow-sm);
  }

  .yaga {
    background-color: yellow;
    border-radius: var(--rounded-xl);
    padding: var(--spacing-5);
    box-shadow: var(--shadow-xl);
  }

  .jeff {
    opacity: 0.1;
  }
}

```

Generated CSS : 

```css
/* generated css in v4.0.1 for `@layer components` */
.baba {
  background-color: green;
  border-radius: var(--rounded-sm);
  padding: var(--spacing-1);
  box-shadow: var(--shadow-sm);
}

.yaga {
  background-color: yellow;
  border-radius: var(--rounded-xl);
  padding: var(--spacing-5);
  box-shadow: var(--shadow-xl);
}

.jeff {
  opacity: 0.1;
}
```

```css
/* generated css in v3.4.17 for `@layer components`  */
.baba {
  background-color: green;
  border-radius: var(--rounded-sm);
  padding: var(--spacing-1);
  box-shadow: var(--shadow-sm);
}

.hover\:jeff:hover {
  opacity: 0.1;
}

@media (min-width: 768px) {
  .md\:yaga {
    background-color: yellow;
    border-radius: var(--rounded-xl);
    padding: var(--spacing-5);
    box-shadow: var(--shadow-xl);
  }
}
```
