### ISSUE TITLE
v4 Custom @keyframes are not working when imported

### ISSUE THREAD

**Issue by killoblanco** [tailwindlabs/tailwindcss#16192]
CSS custom @keyframes are not being populated when they are imported from other files.

**What version of Tailwind CSS are you using?**

v4.0.3

**What build tool (or framework if it abstracts the build tool) are you using?**

@tailwindcss/vite@4.0.3

**What version of Node.js are you using?**

v23.6.0

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

macOS

**Reproduction**

```css
/* main.css */
@import "tailwindcss";
@import "./animation.css";
```

```css
/* animation.css */
@theme {
  --animate-fade-in: fade-in 0.6s ease-in;

  @keyframes fade-in {
    0%: {
      opacity: 0;
    }

    100%: {
      opacity: 1;
    }
  }
}
```

**Describe your issue**

I'm building an animation like plugin for tw v4. The animation name and class are being populated as expected but the animation is not loaded by the browser even tho when the css is there.

<img width="273" alt="Image" src="https://github.com/user-attachments/assets/e09776e2-dbc8-4300-b04e-92bd1efb6cbc" />
<br /><br />

<img width="295" alt="Image" src="https://github.com/user-attachments/assets/f31d34a4-d80b-4e30-a854-cb5912cbab15" />
<br /><br />

<img width="219" alt="Image" src="https://github.com/user-attachments/assets/de54e5b6-40f1-4444-a8bd-9519e6f2e661" />
<br /><br />

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/c8aee8cc-a76f-442d-9630-33a9efd849fc" />
