### ISSUE TITLE
layer theme generates duplicate nesting style

### ISSUE THREAD

**Issue by unional** [tailwindlabs/tailwindcss#16324]
**What version of Tailwind CSS are you using?**

4.0.3

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwind cli

**What version of Node.js are you using?**

v20.0.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/7u9dOQWA3C?file=css

**Describe your issue**

The theme in the Play link will generate style like this:

```css
@layer theme {
  @layer theme {
    * {
      &:where(.tw-dark, .tw-dark *) {
        &:where(.tw-dark, .tw-dark *) {
          --tw-color-primary: ...;
        }
      }
    }
  }
}
```

ref: https://github.com/tailwindlabs/tailwindcss/discussions/16313
