### ISSUE TITLE
[v4.0.5] Used css variables are removed from @keyframes

### ISSUE THREAD

**Issue by ramrami** [tailwindlabs/tailwindcss#16374]
**What version of Tailwind CSS are you using?**

v4.0.5

**What build tool (or framework if it abstracts the build tool) are you using?**

Gulp + Postcss

**What version of Node.js are you using?**

v20

**What browser are you using?**

Brave

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/4MlgazRExq?file=css

**Describe your issue**

Given this setup
```css
@property --angle {
  inherits: true;
  initial-value: 0deg;
  syntax: '<angle>';
}

@theme {
  --animate-rotate-angle: rotate-angle 2s infinite linear;  
  @keyframes rotate-angle {
    to {
      --angle: 360deg;
    }
  }    
}
```

TW v4.0.5 removes the css var from the keyframe when the animation is used and generate the keyframe like this:

```css
@keyframes rotate-angle {
  to {
  }
}
```
