### ISSUE TITLE
[v4] Radio button selected appearance

### ISSUE THREAD

**Issue by liamduckett** [tailwindlabs/tailwindcss#16385]
**What version of Tailwind CSS are you using?**

v4.0.5

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Playground

**What browser are you using?**

Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

* [v4](https://play.tailwindcss.com/DvC8yvz0vK)
* [v3](https://play.tailwindcss.com/1rY7RpAW1Y)

**Describe your issue**

Radio button appearance has changed upon upgrading to v4. 

Apologies, I wasn't sure whether to report this as a [tailwindcss-forms](https://github.com/tailwindlabs/tailwindcss-forms) issue?

**Cause**

Previously:

```css
/* Assign checked background color - higher priority */
[type="radio"]:checked {
  /* ... */
  background-color: currentColor;
  /* ... */
}

```css
/* Assign custom background color - lower priority */
.bg-gray-100 {
  /* ... */
  background-color: rgb(243 244 246 / var(--tw-bg-opacity, 1));
}
```

but now: 

```css
/* Assign checked background color - lower priority */
@layer base {
  [type="checkbox"]:checked, [type="radio"]:checked {
    /* ... */
    background-color: currentColor;
    /* ... */
  }
}

/* Assign custom background color - higher priority */
@layer utilities {
  .bg-gray-100 {
    background-color: var(--color-gray-100);
  }
}
```

Thanks!
