### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by jibberishclient** [tailwindlabs/tailwindcss#1640]
I just wanted to suggest unified scrollbar style classes. I noticed the docs use webkit CSS selectors for their scrollbars that appear in the class tables. I'm sure that could be extended to Firefox and other browsers as well. Is there a chance you could bundle these as utility classes?

**Comment by jenstornell** [comment]
I would also like to have such support built in. The CSS code looks something like below:

```css
/* width */
::-webkit-scrollbar {
  width: 16px;
  height: 16px;
}

/* Track */
::-webkit-scrollbar-track {
  border-radius: 100vh;
  background: #edf2f7;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #cbd5e0;
  border-radius: 100vh;
  border: 3px solid #edf2f7;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #a0aec0;
}
```

I guess it would be something like this:

```html
<div class="scrollbar-thumb:bg-red-500 scrollbar-track:rounded">Content</div>
```

or a shorthand because it may be long...

```html
<div class="s-thumb:bg-red-500 s-track:rounded">Content</div>
```

or...

```html
<div class="sb-thumb:bg-red-500 sb-track:rounded">Content</div>
```
