### ISSUE TITLE
Nested CSS output by Tailwind during dev mode doesn't work in Chrome

### ISSUE THREAD

**Issue by dhruvkb** [tailwindlabs/tailwindcss#16418]
**What version of Tailwind CSS are you using?**

For example: v4.0.6

**What browser are you using?**

This bug appears on Chrome but not in Firefox.

| Firefox | Chrome |
|-|-|
| <img width="1190" alt="Image" src="https://github.com/user-attachments/assets/d457c400-d93c-4e1a-aa6a-6f5676134a2e" /> | <img width="1264" alt="Image" src="https://github.com/user-attachments/assets/072928a7-2348-4860-9624-3ce718e74d04" /> |
| No bug, works as expected. | Buggy, colors are incorrect. |

**Reproduction URL**

https://play.tailwindcss.com/aKEDzegSx4

**Describe your issue**

Nested CSS output by Tailwind doesn't work in Chrome. It works well in Firefox. When the output is built for prod, Lightning CSS flattens the output and the final version works in both browsers. Based on this, 
it is quite likely that this is a Chrome bug.

Is there a way to output flat CSS during development so that this bug can be worked around when in dev mode?

**Comment by adamwathan** [comment]
Thanks — raised this with my contacts at Google to see if there's any good reason for this or if it's a bug, will report back!

**Comment by argyleink** [comment]
bug in the output from Lightning during dev.

```css
/* doesnt work */
h1 {
  &::after { 
    &:active {
      color: red;
    }
  }
}

/* does work */
h1 {
  &:active {
    &::after {
      color: green;
    }
  }
}
```

If it helps, my Firefox and Chrome both show the same results for the provided repro URL

**Comment by adamwathan** [comment]
@argyleink This isn't a Lightning thing in this case because we don't use Lightning in Play, instead we just ship the original nested CSS to the browser.

The thing I'm confused by is why two of these work but one doesn't:

```css
/* Works */
.my-class:visited::after {
  color: orange;
}

/* Works */
.my-class {
  &:visited::after {
    color: orange;
  }
}

/* Doesn't work */
.my-class {
  &:visited {
    &::after {
      color: orange;
    }
  }
}
```

I would've thought all of these would be the same thing 🤔
