### ISSUE TITLE
--breakpoint-*: initial not working

### ISSUE THREAD

**Issue by EinfachHans** [tailwindlabs/tailwindcss#16464]
## Description

I'm trying to use

```css
@theme {
  --breakpoint-*: initial;
  --breakpoint-s: 576px;
}
```

in an angular project that i currently migrate to `v4`.

What i expect would be the default breakpoints to be removed and only the `s` breakpoint to exist.

Currently i receive this error:

```
 [ERROR] expected "{".
  ╷
4 │   --breakpoint-*: initial;
  │                          ^
  ╵

```
