### ISSUE TITLE
--text-* theme variables does not create a utility class

### ISSUE THREAD

**Issue by abusada** [tailwindlabs/tailwindcss#16468]
## Bug Report: `@theme` Not Generating All Expected Text Utilities in v4

**Description:**

Tailwind v4's `@theme` directive doesn't generate all expected text utilities from defined CSS variables. Only the first utility seems to be created.

**Steps to Reproduce:**

1. Define multiple text utilities in `@theme`:

    ```css
    @import "tailwindcss";

    @theme {
      --*: initial;

      --text-xs: 0.75rem;
      --text-xs--line-height: calc(1 / 0.75);

      --text-tiny: 0.625rem;
      --text-tiny--line-height: 1.5rem;
      --text-tiny--letter-spacing: 0.125rem;
      --text-tiny--font-weight: 500;
    }
    ```

2.  Attempt to use `text-xs` and `text-tiny` classes.

**Expected Behavior:**

Both `text-xs` and `text-tiny` utility classes should be generated and apply the defined styles.

**Actual Behavior:**

Only `text-xs` is generated. `text-tiny` is missing.

**Screenshots:**

[Tailwind Playground](https://play.tailwindcss.com/N9QZTl0dR2?file=css):

![Image](https://github.com/user-attachments/assets/36be3de6-7ff0-44e0-a23d-fc42ade9ee19)
