### ISSUE TITLE
[v4][cli] The --minify and --optimize options remove CSS from output

### ISSUE THREAD

**Issue by MariusVatasoiu** [tailwindlabs/tailwindcss#16478]
I have the following tailwind file and I get two different results when I use or not the `--minify` or `--optimize` flags. 

```css
@import "tailwindcss";

@custom-variant dark {
  &:where(.dark, .dark *) {
    @slot;
  }
  @container style(--dark-mode) {
    @slot;
  }
}
```

For this HTML:

```html
<div class="dark:hidden">Hello</div>
```

Without the `--minify` or `--optimize` flags, I get:

```css
@layer utilities {
  .dark\:hidden {
    &:where(.dark, .dark *) {
      display: none;
    }
    @container style(--dark-mode) {
      display: none;
    }
  }
}
```

With `--minify` or `--optimize` flags, I get:

```css
.dark\:hidden:where(.dark,  .dark *){
  display:none;
}
```

The `@container style(--dark-mode){...}` part is removed, even though I need it for shadow DOM. If I remove `&:where(.dark, .dark *) {...}`, then I lose support for Light DOM in Firefox and older Chrome and Safari versions.

The issue seems to be in the optimize mechanism, since minify means minify + optimize.
