### ISSUE TITLE
Tailwind v4: Global reset affecting main project when importing a library

### ISSUE THREAD

**Issue by amendezm** [tailwindlabs/tailwindcss#16552]
### Problem Description:

Since upgrading from Tailwind v3 to v4, I've encountered an issue where the global reset rules defined by 
```css
*:not(#\#), 
:not(#\#):after, 
:not(#\#):before, 
:not(#\#)::backdrop { 
    box-sizing: border-box; 
    border: 0 solid; 
    margin: 0; 
    padding: 0; 
} 
```
are being applied to my entire project, including elements I do not intend to affect. This was not a problem when using Tailwind v3.

The issue arises when importing my custom library (which uses Tailwind v4) into my main project. The styles are overriding the intended layout and design in my main project, even though the reset should ideally only affect elements within the library itself.

### Steps to Reproduce:
- Create a project using Tailwind v4.
- Import a library that uses Tailwind v4.
- Observe the global reset being applied to the entire project, which was not the case in Tailwind v3.

### Expected Behavior:
The *:not(#\#) rule (or any other global reset) should only affect elements within the library and not the entire project. This behavior was present in Tailwind v3, but now it is impacting the broader scope of my project in v4.

### Additional Context:
- Tailwind v3 did not exhibit this behavior.
- I expect the reset to be scoped more narrowly or configurable to avoid side effects in the main project.

### Environment:
- Tailwind version: v4
- Node version: 22.13.1
- React version: 19

**Comment by amendezm** [comment]
this is my `index.css` file

```css
@import 'tailwindcss';

@config '../../tailwind.config.cjs';

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}

@layer components {

  input {
    color-scheme: light;
  }

  input[type="date"]::-webkit-calendar-picker-indicator {
    width: 18px;
    margin-top: -10px;
    cursor: pointer;
  }
}

```
