### ISSUE TITLE
Custom Functional Utilities not working in V4

### ISSUE THREAD

**Issue by anthony-b-dev** [tailwindlabs/tailwindcss#16568]
I have the following code:

```css
@theme {
  --text-shadow-sm: 0 1px 2px var(--tw-shadow-color);
  --text-shadow-md: 0 2px 4px var(--tw-shadow-color);
  --text-shadow-lg: 0 8px 16px var(--tw-shadow-color);
}

@utility text-shadow-* {
  text-shadow: --value(--text-shadow-*);
}
```

But I get the following error:

![Image](https://github.com/user-attachments/assets/9f054ec7-4927-4618-8881-2394718bd128)

![Image](https://github.com/user-attachments/assets/7a18b583-4564-4629-871e-a6f4e83f0505)

Looking at the guide, I followed the example [here](https://tailwindcss.com/docs/adding-custom-styles#functional-utilities) but had to name it `text-shadow` instead of `text `because it was being picked up in the color namespace. 

My current solution is to use `textShadow `in the theme:

```css
@theme {
  --textShadow-sm: 0 1px 2px var(--tw-shadow-color);
  --textShadow-md: 0 2px 4px var(--tw-shadow-color);
  --textShadow-lg: 0 8px 16px var(--tw-shadow-color);
}

@utility text-shadow-* {
  text-shadow: --value(--textShadow);
}
```

This seems to be a bug.

**Comment by FISEM** [comment]
I've noticed something similar. For example, apha() function doen't work in @layer base

**Comment by anthony-b-dev** [comment]
> @anthony-b-dev Do you mind clarifying what the issue is? When I put your example into the playground it does seem to work: https://play.tailwindcss.com/JHQp2PLlKB?file=css
> 
> The error you showed appears to be related to the intellisense extension so this might be a dupe of http://github.com/tailwindlabs/tailwindcss-intellisense/issues/1208? 
> 
> @Nickersoft Do you mind adding a repro? Not sure what 

The "-*" syntax does not work like in the playground. I also had to name the variables in the `@theme` different from the `@utility`. Not sure if it's just intellisense as my project doesn't compile with the error there either.

**Comment by philipp-spiess** [comment]
@anthony-b-dev I see. What linter do you run in your project? Perhaps you can configure it to not run on these Tailwind CSS files? It's hard to help here without a repo that we can run locally I'm afraid.

**Comment by anthony-b-dev** [comment]
I'm using `"eslint": "^9.20.1"`. But it doesn't look like I have it configured to run on any CSS files unless that's part of the defaults from `@nx/eslint-plugin` ?

So actually, I was wrong. It does compile, but the styling does not seem to be applied, as well as showing up twice in intellisense. 

![Image](https://github.com/user-attachments/assets/0861a070-1d3f-435a-8542-49ff4b4e346c)

No text shadow applied on the title: 

![Image](https://github.com/user-attachments/assets/f5125584-95fc-426b-83cc-95beb6f20741)

Additionally, I went into the playground and input my code and it also broke in the playground when I'm using the default tailwind variables I was using that worked in V3: 

https://play.tailwindcss.com/zP81KbW2Dz?file=css

```css
@import "tailwindcss";

@theme {
  --text-shadow-sm: 0 1px 2px var(--tw-shadow-color); /* <-- I think it has to do with this variable*/
  --text-shadow-md: 0 2px 4px var(--tw-shadow-color); /* <-- When I changed this to red, the styling is applied, but the linting error is still present*/
  --text-shadow-lg: 0 8px 16px var(--tw-shadow-color);
}

@utility text-shadow-* {
  text-shadow: --value(--text-shadow-*);
}
```

**Comment by philipp-spiess** [comment]
@anthony-b-dev Ah, I see. When you reference other CSS variables you might want to use `@theme inline` so that the `--tw-shadow-color` lookup isn't put onto the `:host` element (since the vars are set on the individual elements and not the root, it would otherwise resolve to the wrong value):

- https://tailwindcss.com/docs/theme#referencing-other-variables
- https://play.tailwindcss.com/E66VYRn5zP?file=css

**Comment by anthony-b-dev** [comment]
Ok I see. Digging further I found that I also wasn't specifying the `shadow-<color>` class on the element in question either. But adding the `inline `modifier fixed that problem.

Unfortunately, I'm still seeing the linting error, current code below....

```css
@theme inline {
  --text-shadow-sm: 0 1px 2px var(--tw-shadow-color);
  --text-shadow-md: 0 2px 4px var(--tw-shadow-color);
  --text-shadow-lg: 0 8px 16px var(--tw-shadow-color);
}

@utility text-shadow-* {
  text-shadow: --value(--text-shadow-*);
}
```
And I don't understand what "term" tailwind is expecting in throwing this error....

![Image](https://github.com/user-attachments/assets/4e58d4ad-9cc1-4a9a-a824-853ea93693e9)
