### ISSUE TITLE
[v4] font-family Theme CSS Variables incorrectly applied to font-weight

### ISSUE THREAD

**Issue by pony5580** [tailwindlabs/tailwindcss#16652]
**What version of Tailwind CSS are you using?**  
v4.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**  
Next.js 15.1.6 

**What version of Node.js are you using?**  
v22.13.1

**What browser are you using?**  
Chrome

**What operating system are you using?**  
macOS

**Reproduction URL**  
https://play.tailwindcss.com/b3Kv8UrT0Z

**Describe your issue**  

It seems that defining a custom font family using a CSS variable does not work as expected in Tailwind CSS v4.  

According to the documentation, it should be possible to define a font family like this:  

```html
<div class="font-[--font-anton]">Text</div>
```

However, when using this syntax, Tailwind generates the following CSS:  

```css
.font-\(--font-anton\) {
    --tw-font-weight: var(--font-anton);
    font-weight: var(--font-anton);
}
```

This incorrectly assigns the value to `font-weight` instead of `font-family`, which prevents the custom font from being applied.  

On the other hand, specifying a font directly (e.g., `font-[Open_Sans]`) works correctly:  

```css
.font-\[Open_Sans\] {
    font-family: Open Sans;
}
```

Expected behavior:  
The generated CSS should correctly apply the `font-family` property when using a CSS variable, similar to how it works with direct font names.
