### ISSUE TITLE
[Feature proposal] Add support for ::selection

### ISSUE THREAD

**Issue by robbevp** [tailwindlabs/tailwindcss#1665]
It would be nice to be able to custimize the pseudo-selector [`::selection`](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)

I imagine this to be added as a variant that can be added for the supported properties. 
By default this should be disabled for all properties (or maybe only enabled for `background-color`)

I could take a stab at this if this would be something that could be added.

**Comment by royvanv** [comment]
My proposal would be to add an opt-in pseudo selector variant (`selection`) to use with `background-color` and `color`.

```html
<p class="selection:text-white selection:bg-black">Select this text.</p> 
```

```css
/** For each text color it adds a class */
.selection:text-white::selection {
   color: #fff; 
}

/** For each background color it adds a class */
.selection:bg-black::selection {
   color: #000; 
}
```
