### ISSUE TITLE
Important modifier with transition utilities like `ease-out!` got error

### ISSUE THREAD

**Issue by winchesHe** [tailwindlabs/tailwindcss#16664]
**What version of Tailwind CSS are you using?**

v3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Nextjs 14.3.0

**What version of Node.js are you using?**

v20.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

Here's a minimal reproduction on Tailwind Play:
[https://play.tailwindcss.com/pMH7Qk3QdS](https://play.tailwindcss.com/pMH7Qk3QdS)

**Describe your issue**

When using the important modifier with transition utilities like `ease-out!`, it generates invalid CSS:

```css
.ease-out\! {
    --tw-ease: var(--ease-out) !important;
    transition-timing-function: var(--ease-out) !important;
}
```

![Image](https://github.com/user-attachments/assets/e9be6714-4a02-4920-9204-a4e98bd9bdfd)

The issue is that `--tw-ease: var(--ease-out) !important;` is an invalid CSS rule because CSS custom properties (variables) cannot have `!important` modifiers. This makes the utility class unusable.

Expected behavior:
The `!important` modifier should only be applied to the actual CSS property (`transition-timing-function`) and not to the CSS custom property declaration.

The correct output should be:

```css
.ease-out\! {
    --tw-ease: var(--ease-out);
    transition-timing-function: var(--ease-out) !important;
}
```
