### ISSUE TITLE
!z-40 not working in Tailwind CSS v4

### ISSUE THREAD

**Issue by Navidtm** [tailwindlabs/tailwindcss#16794]
**What version of Tailwind CSS are you using?**

v4.0.8

**What build tool (or framework if it abstracts the build tool) are you using?**

[tailwind play](https://play.tailwindcss.com)

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux

**Reproduction URL**

https://play.tailwindcss.com/QP00crgkmX

**Describe your issue**

Using `!z-40` in Tailwind CSS v4 does not apply the expected

Expected
```css
.\!z-40 {
  z-index: 40 !important;
}
```

Actual
```css
.\!z-40 {
  z-index: 40;
}
```

Even testing in [Tailwind Play](https://play.tailwindcss.com/) does not produce the correct result.
