### ISSUE TITLE
Name clashing between --(text-)color and --text (font-size) variables

### ISSUE THREAD

**Issue by niels-k-86** [tailwindlabs/tailwindcss#16797]
**What version of Tailwind CSS are you using?**

v4.0.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 15.1.7

**What version of Node.js are you using?**

v20.0.0

**What browser are you using?**

All of them

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/ADM8EOMQFs

**Describe your issue**

The `--text-*` (font-size) and `--(text-)color-*` spaces clash when generating utility classes. Adding both a `--color-example` and a `--text-example` variable will generate a utility class with an invalid CSS variable:

```css
.text-body {
  font-size: var(--text-example);
}

:root {
  --text-example: 24px --text-color-example: #0000ff;
}
```
