### ISSUE TITLE
vue 3 & tailwindcss v4 @theme not working

### ISSUE THREAD

**Issue by cpt-n3mo** [tailwindlabs/tailwindcss#16808]
Using a clean Vue 3 project then  adding tailwind to vite, adding `@import "tailwindcss" ` to css file.
then importing it into  `main.ts`.

This makes tailwindcss work like a charm,
but when one uses `@theme` then tailwindcss stops working completely.

`/public/css/tailwindcss.css`
```css
@import "tailwindcss"
@theme{
  --color-primary: var(--color-green-600);
}
```

when creating a second css file then doing the same as above will make tailwindcss work again. but the custom `@theme` is not applied at all

 `/public/css/custom_theme.css`
```css
@import "tailwindcss"
@theme{
  --color-primary: var(--color-green-600);
}
```

Any ideas on why this happens..
I get no errors in console, not in browser nor on build.
