### ISSUE TITLE
[v4] Utility modifiers only work with arguments

### ISSUE THREAD

**Issue by royduin** [tailwindlabs/tailwindcss#16824]
With Tailwind 4 (4.0.9 currently); modifiers only seem to work with utilities that do have an argument, this works:

```css
@utility text-* {
  --alpha: calc(--modifier(integer) * 1%);
  color: --alpha(--value(--*, [color]) / var(--alpha, 100%));
}
```

With `text-default`, `text-default/50`, `text-blue`, `text-blue/50`, etc.

This doesn't work:

```css
@utility text {
  --alpha: calc(--modifier(integer) * 1%);
  color: --alpha(red / var(--alpha, 100%));
}
```

With just `text`, `text/50`, etc. as die modifier isn't parsed.

Demo: https://play.tailwindcss.com/ECphsE1vzA?file=css

---

Related discussion: https://github.com/tailwindlabs/tailwindcss/discussions/15775

**Comment by brandonmcconnell** [comment]
I ran into this too this past week while building a plugin and had to resort to the old JS implementation as a result.

I would love to see this fixed too.

**Comment by simonm-c** [comment]
commenting to can be notified when this is addressed

**Comment by rozsazoltan** [comment]
> [!NOTE]
> This comment doesn't change the original point of the issue - that `--modifier()` function can't be applied without `--value()` - but it highlights better usage of `--value`.

Off-topic: Just a small note - when dealing with the first `text-*` utility, it's better to restrict it to only accept namespaces that contain colors. The `[color]` value indicates that only colors are accepted as arbitrary values, but it doesn't restrict the namespace itself from using `--*`.

`--color-*` is much more precise.

```css
@theme {
  --color-default: red;
  --color-blue: blue;
}

@utility text-* {
  --alpha: calc(--modifier(integer) * 1%);
  color: --alpha(--value(--color-*, [color]) / var(--alpha, 100%));
}
```

|Before with `--*`|After with `--color-*`|
|---|---|
|https://play.tailwindcss.com/MAWl2RHvgA|https://play.tailwindcss.com/te7NvIqYce|
|**Generated not expected but invalid utility with using `--radius-4xl` namespace**<br><img width="784" height="555" alt="Image" src="https://github.com/user-attachments/assets/f1966af6-43ef-466e-91ad-933f1c4a2f0c" />|**Not generated invalid utility with using `--radius-4xl` namespace**<br><img width="477" height="328" alt="Image" src="https://github.com/user-attachments/assets/985f90b5-dddf-49d9-9ac5-0435006ba6c6" />|

You can also reference a custom namespace, but it's a good idea to prefix it to keep it separate, so you don't accidentally reference other existing namespaces.

```css
@theme {
  --custom-default: red;
  --custom-blue: blue;
}

@utility text-* {
  --alpha: calc(--modifier(integer) * 1%);
  color: --alpha(--value(--custom-*, [color]) / var(--alpha, 100%));
}
```
