### ISSUE TITLE
unexpected result when adding a custom break point ( --breakpoint-3xl:2048px; )

### ISSUE THREAD

**Issue by SusanthCom** [tailwindlabs/tailwindcss#16876]
**What version of Tailwind CSS are you using?** 

4.0.9

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CLI

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

macOS

**Describe your issue**

FILE : `input.css`

```css
@import "tailwindcss";

@theme {
  --breakpoint-3xl: 2048px;
}
```

FILE : `index.html`

```html
<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="./output.css" rel="stylesheet">
</head>

<body>
  <p class="border-b-2 border-stone-300 text-stone-500 text-xl m-4">Breakpoint Step</p>
  <div class="flex flex-col items-start">

    <div class="w-[639px]  px-5 h-8 mb-3 bg-stone-400 border-b-2 
      sm:bg-stone-100 sm:border-none">0. tiny (default) 0px to 639px</div>

    <div class="w-[767px]  px-5 h-8 mb-3 bg-red-100 sm:bg-red-500 sm:border-b-2 
      md:bg-red-100 md:border-none">1. sm 640px to 767px</div>

    <div class="w-[1023px]  px-5 h-8 mb-3 bg-green-100 md:bg-green-500 md:border-b-2 
      lg:bg-green-100 lg:border-none">2. md 768px to 1023px</div>

    <div class="w-[1279px] px-5 h-8 mb-3 bg-sky-100 lg:bg-sky-500 lg:border-b-2 
      xl:bg-sky-100 xl:border-none">3. lg 1024px to 1279px</div>

    <div class="w-[1535px] px-5 h-8 mb-3 bg-purple-100 xl:bg-purple-500 xl:border-b-2 
      2xl:bg-purple-100 2xl:border-none">4. xl 1280px to 1535px</div>

    <div class="w-[2047px] px-5 h-8 mb-3 bg-teal-100 2xl:bg-teal-500 2xl:border-b-2 
      3xl:bg-teal-100 3xl:border-none">5. 2xl 1536px to 2047px ( ERROR 🔥 🔥  : `3xl:bg-teal-100` not
      working! but `3xl:border-none` works fine! )</div>

    <div class="w-screen px-5 h-8 mb-3 bg-pink-100 3xl:bg-pink-500 3xl:border-b-2">6. 3xl 2048px and above</div>
  </div>
</body>

</html>
```

At 6th non empty line from bottom of `index.html` ---> `3xl:bg-teal-100` not working! but `3xl:border-none` works fine !!!

**Comment by RobinMalfait** [comment]
Hey!

The problem is that we cannot sort breakpoints with different units. The breakpoints in Tailwind CSS are `rem` based, and you are defining a `px` based value.

Each breakpoint _will_ be sorted in the expected order but only if they have the same unit.

The reason we can sort them is because `rem` is relative and can change at runtime based on the root font size (for media queries, it's defined by your browser). So if one of your users sets a very high value, then the sorting will be wrong again.

I would recommend to define your breakpoint in rems instead:
```diff
  @theme {
-   --breakpoint-3xl: 2048px;
+   --breakpoint-3xl: 128rem;
  }
```

Play: https://play.tailwindcss.com/HJyXwV7dU7

---

For a shorter reproduction, let's imagine you had these 3 classes: `xl:flex 2xl:flex 3xl:flex`
With PX based values, the CSS would look like this:
```css
@layer utilities {
  .\33 xl\:flex {
    @media (width >= 2048px) {
      display: flex;
    }
  }
  .xl\:flex {
    @media (width >= 80rem) {
      display: flex;
    }
  }
  .\32 xl\:flex {
    @media (width >= 96rem) {
      display: flex;
    }
  }
}
```
Notice how the `3xl` one is listed first instead of at the end.

With `rem` based values, the CSS would look like this:
```css
@layer utilities {
  .xl\:flex {
    @media (width >= 80rem) {
      display: flex;
    }
  }
  .\32 xl\:flex {
    @media (width >= 96rem) {
      display: flex;
    }
  }
  .\33 xl\:flex {
    @media (width >= 128rem) {
      display: flex;
    }
  }
}
```

Hope this helps!
