### ISSUE TITLE
The "outline-hidden" results in "outline-style: none".

### ISSUE THREAD

**Issue by phcoliveira** [tailwindlabs/tailwindcss#16894]
**What version of Tailwind CSS are you using?**

v4.0.9

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 6.0.7

**What version of Node.js are you using?**

v20.18.3

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/SOQPkOEDC9

**Describe your issue**

The documentation and also the hint provided by the Tailwind extension suggest that the class "outline-hidden" has this value.
```css
.outline-hidden {
  outline: 2px solid transparent;
  outline-offset: 2px;
}
```
But please use the dev tools on the link above and verify that the button ends up with `outline-style: none`.
