### ISSUE TITLE
v4 preflight theme variables aren't prefixed

### ISSUE THREAD

**Issue by cvharris** [tailwindlabs/tailwindcss#16945]
Versions:
- Tailwind: v4.0.9
- Vite: 5.2.11
- Node: 20.14.0
- Chrome, Mac OS

[Reproduction URL](https://play.tailwindcss.com/fPhQksGLVR)

If you look at the reproduction URL above (took awhile to prefix all those classes lol) you can see that the `--default-font-family` does not map to the prefixed `--font-sans` declared in the `@theme`. It seems that since `--default-font-family: var(--font-sans);` it isn't getting updated to map to the prefixed value later. This was not an issue in v3.

The workaround I have is to declare `--default-font-family` in my own `@layer base`:

```css
@layer base {
  html {
    --default-font-family: 'Salesforce Sans', Helvetica, Arial, sans-serif;
  }
}
```

What ought to happen is the preflight reference points to the prefixed font so that the theme can correctly override it: `--default-font-family: var(--tw-font-sans);`
