### ISSUE TITLE
[v4] used `@keyframes` are removed when using `prefix` option

### ISSUE THREAD

**Issue by dimaMachina** [tailwindlabs/tailwindcss#16966]
**What version of Tailwind CSS are you using?**

playground

**What build tool (or framework if it abstracts the build tool) are you using?**

playground

**What version of Node.js are you using?**

playground

**What browser are you using?**

chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/8k0xGZ2vL1

**Describe your issue**

generated output doesn't contain

```css
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
```
