### ISSUE TITLE
btn-disabled not work for Arbitrary

### ISSUE THREAD

**Issue by cqh963852** [tailwindlabs/tailwindcss#17057]
**What version of Tailwind CSS are you using?**

4.0.12

**What build tool (or framework if it abstracts the build tool) are you using?**

nextjs 15.2.1

**What version of Node.js are you using?**

v22.13.1

**What browser are you using?**

Chrome

**What operating system are you using?**

mac sequoia 15.3

For example: macOS, Windows

**Reproduction URL**

https://github.com/cqh963852/daisyui-demo

**Describe your issue**

btn-disabled not work for Arbitrary

bg-primary works

![Image](https://github.com/user-attachments/assets/d6df17fb-5ac4-485c-8503-29fbceea5bc5)

![Image](https://github.com/user-attachments/assets/5e09e62c-d3d3-4d10-8e40-c63b7f2a80f4)

**Comment by wongjn** [comment]
This is due to the fact that `.btn-disabled` is not registered by Daisy UI as a utility class name of itself. Daisy UI does something akin to:

```js
addComponents({
  ".btn": {
    // …
    "&:is(:disabled, [disabled], .btn-disabled)": {
      // …
    },
  },
  ".btn-primary": {
    // …
  },
});
```

With the way the legacy `addComponents()` API interface works, only the top-level selectors get registered as known class names to Tailwind. I believe it would be out of scope to get Tailwind to delve into deeper selectors, especially since this only exists as a backwards-compatibility layer.

You could consider raising this issue with Daisy UI.

Or otherwise, you can copy the CSS into your own utility class name:
```css
@utility btn-disabled {
  @layer components {
    &:not(.btn-link, .btn-ghost) {
      background-color: color-mix(in oklab, var(--color-base-content) 10%, transparent);
      box-shadow: none;
    }

    pointer-events: none;
    --btn-border: #0000;
    --btn-noise: none;
    --btn-fg: color-mix(in oklch, var(--color-base-content) 20%, #0000);

    @media (hover: hover) {
      &:hover {
        background-color: color-mix(in oklab, var(--color-base-content) 10%, transparent);
        pointer-events: none;
        --btn-border: #0000;
        --btn-fg: color-mix(in oklch, var(--color-base-content) 20%, #0000);
      }
    }
  }
}
```
