### ISSUE TITLE
[Feature Request] Space with divide gives padding

### ISSUE THREAD

**Issue by randallmlough** [tailwindlabs/tailwindcss#1712]
I really like using the new `space-X-X` and `divide-X-X` utilities, but one aspect that I wish was covered is if the element includes both space and divide it not only pushes the element, but it also gives padding to the element. This would create even spacing on each side.

**Example**
```html
<div class="divide-x-2 space-x-4">
   <a class="text-primary-500" href="#">Github</a>
   <a class="text-primary-500" href="#">LinkedIn</a>
   <a class="text-primary-500" href="#">Something Else</a>
</div>
```
**What it currently does**
![Screen Shot 2020-05-05 at 4 08 03 PM](https://user-images.githubusercontent.com/25895389/81124613-bc3fa300-8eea-11ea-8bdb-f5b614c4577a.png)

**What i wish it did**
![Screen Shot 2020-05-05 at 4 08 31 PM](https://user-images.githubusercontent.com/25895389/81125113-1bea7e00-8eec-11ea-95e6-b7b63bb0e1a9.png)

Maybe a third class can be added like `sd-X-X` if you don't want to include that type of rule on the `space-X-X` classes.

**Comment by mainej** [comment]
Consider writing that as:
```html
<div class="divide-x-2">
   <a class="text-primary-500 px-2" href="#">Github</a>
   <a class="text-primary-500 px-2" href="#">LinkedIn</a>
   <a class="text-primary-500 px-2" href="#">Something Else</a>
</div>
```
The result is slightly different than what you requested—the left side of "Github" and the right side of "Something Else" both have extra space. But, often that's desirable... you'll want extra padding on links to make the click target larger.

**Comment by randallmlough** [comment]
@mainej That's ultimately what I may do. My use case is primarily for dynamic content so I may have 1 item or many, which in my mind is a great use of the space and divide.

**Comment by adamwathan** [comment]
I can't think of a straightforward way to achieve this in CSS without things getting _really_ complex, did you have any ideas on an implementation?

This is the best I can come up with:

```css
.space-x-4 > :not(template) ~ :not(template) {
  --divide-x: 0;
  --space-x-reverse: 0;
  margin-right: calc(1rem * var(--space-x-reverse));
  margin-left: calc(1rem * calc(1 - var(--space-x-reverse)));
  padding-right: calc(1rem * var(--divide-x) * var(--space-x-reverse));
  padding-left: calc(1rem * var(--divide-x) * calc(1 - var(--space-x-reverse)));
}

.divide-x > :not(template) ~ :not(template) {
  --divide-x: 1;
  --divide-x-reverse: 0;
  border-right-width: calc(1px * var(--divide-x-reverse));
  border-left-width: calc(1px * calc(1 - var(--divide-x-reverse)));
}
```

But it comes at the extremely significant cost of completely breaking padding for all child elements:

https://jsfiddle.net/2q3y9obt/2/

...so it's not really a viable solution.

Personally I would recommend using a separate "divider" element in this case and just relying on spacing:

```html
<div class="space-x-4">
  <a class="text-primary-500" href="#">Github</a>
  <span class="border-l-2" aria-hidden></span>
  <a class="text-primary-500" href="#">LinkedIn</a>
  <span class="border-l-2" aria-hidden></span>
  <a class="text-primary-500" href="#">Something Else</a>
</div>
```

Not as nice admittedly but there's not really any other great option.
