### ISSUE TITLE
v4 swaps underline and no-underline order

### ISSUE THREAD

**Issue by gschier** [tailwindlabs/tailwindcss#17154]
**What version of Tailwind CSS are you using?**

For example: v4.0.13

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: Vite 6.2.1

**What version of Node.js are you using?**

For example: v22.8.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/gschier/tailwind-reproduction

**Describe your issue**

The class order of `underline` and `no-underline` are reversed in v4 compared to v3. I have a base `Link` component that contains `underline` and (in v3) was successfully adding the `no-underline` class to disable this in special cases. This no longer works in v4.

The v4 output is as follows:

```css
@layer components;

@layer utilities {
  .no-underline {
    text-decoration-line: none
  }

  .underline {
    text-decoration-line: underline
  }
}
```

![Image](https://github.com/user-attachments/assets/1b8e247e-d24c-44f1-967c-bd6c29e92fbd)

**Comment by RobinMalfait** [comment]
Hey!

While it's true that the order changed here, these classes are conflicting classes (even in v3).

These are conflicting classnames (even in v3) and shouldn't be used at the same time. I would recommend to conditionally render on or the other.



Play: https://play.tailwindcss.com/N0zznDzqHw

**Comment by gschier** [comment]
I understand that the order in the class attribute doesn't matter. This is not what the bug refers to. 

It's the order in the CSS that tailwind generates that matters.

Shouldn't Tailwind generate it in an order that makes the most sense?

**Comment by RobinMalfait** [comment]
> Shouldn't Tailwind generate it in an order that makes the most sense?

Tailwind sorts the classes by a few different heuristics to make sure that you get a deterministic output that makes sense. In this case it also makes sense, but let me try to list the heuristics we apply:

We sort all the utilities without variants first, then we sort the utilities with variants (we apply more rules for variants, but let's ignore them for now).

When sorting utilities, we have a few rules we look at:

1. What properties are being used by a utility — most properties have a pre-defined sort order for example `px-*` (`padding-inline`) will always be generated before the `py-*` (`padding-block`) utilities. 

   This order is also what the Prettier plugin will use when formatting your classes. It's also used by the VS Code Intellisense plugin when showing suggestions.

   The other important reason for this list is that more specific properties will always win from less specific properties. E.g.: `p-*` will be overridable by `px-*` which will in turn be overridable by `pl-*`.

   E.g.:
   ```css
   /*! tailwindcss v4.0.13 | MIT License | https://tailwindcss.com */
   .p-4 {
     padding: calc(var(--spacing, 0.25rem) * 4);
   }
   .px-2 {
     padding-inline: calc(var(--spacing, 0.25rem) * 2);
   }
   .pt-3 {
     padding-top: calc(var(--spacing, 0.25rem) * 3);
   }
   ```

1. If at least the same properties are being used, then we sort based on the amount of properties that exist.
 
   This allows you to override less specific utilities with more specific utilities (but this time it's based on multiple properties instead of a single one). 

   E.g.: `border-8` will set a `border-width` and a `border-style`, but `border-dotted` will only set the `border-style`, which allows you to have a 8px dotter border using: `border-8 border-dotted`.

1. If there is still no difference, then we will sort the utilities alphabetically

This is what is happening in your example as well:

1. Both `underline` and `no-underline` have no variants, so they will be in the first bucket
1. They both set the `text-decoration-line` property
1. They both have a single property
1. So they fallback to alphabetic sorting

We could add more rules here where we try to sort by the values of each property, and for some utilities that might be easy for others, sorting doesn't really make sense. For example, do you sort colors alphabetically, or by hue, or by something else? Should `underline` be first or `overline`, and why?

We could also special case any utility that has a `none` value to be generated last. But the original rule still exists where you just shouldn't add 2 conflicting classes at the exact same time.

This is why we currently don't spend more time on trying to get the perfect sort by applying more and more heuristics because at the end of the day `bg-red-500 bg-green-500` applied at the same time will have undefined behavior.

Maybe one remaining question is that you wonder _why_ it's different compared to v3. This is because there were different sorting heuristics at play. 

One rule we had in v3 is that we sorted by the registration order of the plugin as one of the fallback sorting heuristics. So `underline` was registered before `no-underline`, therefore this decided the sort order.

This resulted in its own problems, because this now means that 3rd party plugins will _always_ be sorted later in your CSS. Silly example, but let's say you create your own `p-4` implementation as `my-p-4` for some reason. In v3, you would do it like this:
```ts
/** @type {import('tailwindcss').Config} */
export default {
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        '.my-p-4': {
          padding: '1rem',
        },
      })
    },
  ],
}
```
Then you could use it like this:
```html
<div class="bg-blue-200 p-4 px-8">hello</div>
<hr />
<div class="bg-blue-200 px-8 my-p-4">hello</div>
```
This is what the generated CSS looks like:
```css
.p-4 {
  padding: 1rem;
}
.px-8 {
  padding-left: 2rem;
  padding-right: 2rem;
}
.my-p-4 {
  padding: 1rem;
}
```
The `px-8` is not overriding your custom `my-p-4` implementation anymore.
Play: https://play.tailwindcss.com/ZrFGWJSjQQ?file=config

If you compare this to a v4 project instead, then you would create that custom utility using:
```css
@utility my-p-4 {
  padding: 1rem
}
```
With the same HTML as above, the following CSS is generated instead:
```css
.my-p-4 {
  padding: 1rem;
}
.p-4 {
  padding: calc(var(--spacing) * 4);
}
.px-8 {
  padding-inline: calc(var(--spacing) * 8);
}
```

Now `px-8` _is_ winning from your custom `my-p-4` as expected.
Play: https://play.tailwindcss.com/9JsZbYDb4H?file=css

---

We tried to keep the sort order very similar to v3, but as long as you didn't rely on the sort order for conflicting classes you shouldn't really experience any sorting related issues. There are other utilities that are a bit different, but they have totally different set of properties that they don't matter at all.

Does this explanation make sense?
