### ISSUE TITLE
[v4] Utility classes are less specific than other classes

### ISSUE THREAD

**Issue by cybercoder-naj** [tailwindlabs/tailwindcss#17202]
**What version of Tailwind CSS are you using?**

For example: v4.0.14

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt: 3.15 & Vite: 6.1.0

**What version of Node.js are you using?**

20.18.3

**What browser are you using?**

Zen-Browser

**What operating system are you using?**

EndeavourOS

**Reproduction URL**

https://play.tailwindcss.com/8vKNss2tI2

**Describe your issue**

Since `i-mdi:hamburger` class is being used (from [NuxtIcon / Iconify](https://github.com/nuxt/icon)), their pre-defined rules are taking precedence. I want to hide the icon and increase the size but cannot do so with the important modifier. In v3, this was not the case. This results to marking all tw-styles as important (bad) or marking specific classes as important (also bad). 

Might be closely related to #16214

**Comment by RobinMalfait** [comment]
Hey!

All Tailwind utilities are in a `@layer`, all other CSS that's not in a layer is considered unlayered and will have higher precedence. 

In your case you can wrap the other CSS in a `@layer base` which will allow you to override it with utility classes:
```css

@layer base {
  :where(.i-mdi\:hamburger) {
    display: inline-block;
    width: 1em;
    height: 1em;
    background-color: currentColor;
    -webkit-mask-image: var(--svg);
    mask-image: var(--svg);
    -webkit-mask-repeat: no-repeat;
    mask-repeat: no-repeat;
    -webkit-mask-size: 100% 100%;
    mask-size: 100% 100%;
    --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='black' d='M22 13c0 1.11-.89 2-2 2H4a2 2 0 1 1 0-4h9l2.5 2l2.5-2h2a2 2 0 0 1 2 2M12 3C3 3 3 9 3 9h18s0-6-9-6M3 18c0 1.66 1.34 3 3 3h12c1.66 0 3-1.34 3-3v-1H3z'/%3E%3C/svg%3E");
  }
}
```

If you are importing this library in your CSS, you could use this:
```css
@import "library-path" layer(base);
```

Hope this helps!
