### ISSUE TITLE
CSS Generation Issue between v4.0.14 and v4.0.15 in TailwindCSS

### ISSUE THREAD

**Issue by PruthviPraj00** [tailwindlabs/tailwindcss#17346]
I have encountered a discrepancy in the generated CSS between ****v4.0.14**** and ****v4.0.15**** of TailwindCSS. The issue lies in the generated CSS for custom properties (CSS variables). The following sections highlight the differences between the two versions.

**CSS Generated in v4.0.14: not the complete file.**

[V4.0.14.md](https://github.com/user-attachments/files/19415543/V4.0.14.md)

Tailwindcss Package.json in node_module

![Image](https://github.com/user-attachments/assets/2dc39186-50c3-4379-b602-3f5d0250d1b6)

**CSS Generated in v4.0.15: not the complete file.**

[v4.0.15.md](https://github.com/user-attachments/files/19415540/v4.0.15.md)

tailwindcss Package json

![Image](https://github.com/user-attachments/assets/c2f59933-5188-4868-98c5-82354164b5b2)

**Comparison Screenshots**: On the left side is **v4.0.14**, and on the right side is **v4.0.15**.

![Image](https://github.com/user-attachments/assets/d019970e-e7b1-4190-a223-c1966c71453b)
![Image](https://github.com/user-attachments/assets/25ab8ea5-c231-4657-9dce-bdf730181443)
![Image](https://github.com/user-attachments/assets/349238b4-1db3-4914-9350-f87dbee3374c)

### **Key Differences**:

1. **Missing Custom Properties (CSS Variables) in v4.0.15**:
    - The following variables are missing in **v4.0.15**:
        - `--default-font-family`
        - `--default-font-feature-settings`
        - `--default-font-variation-settings`
        - `--default-mono-font-family`
        - `--default-mono-font-feature-settings`
        - `--default-mono-font-variation-settings`
    - These variables were present in **v4.0.14** but are not being generated in **v4.0.15**.
2. **Potential Impact**:
    - The missing variables may cause issues with font settings, particularly if they are being used for consistent typography throughout the application.
    - This could lead to rendering inconsistencies and make it difficult to maintain the project across different environments.

**Comment by wongjn** [comment]
This seems to be a change by #17036, in particular https://github.com/tailwindlabs/tailwindcss/pull/17036#discussion_r1987327968

**Comment by PruthviPraj00** [comment]
I have reviewed the changelog and come to the same conclusion, but what steps can I take to fix it?

**Comment by wongjn** [comment]
How are you using the CSS variables for in your project?

**Comment by adamwathan** [comment]
Hey! Can you explain what is actually broken in your project? The goal of that change was to remove those variables if they weren’t being used, but if they are being used they should be preserved.

**Comment by PruthviPraj00** [comment]
Hi @adamwathan,

I apologize for the confusion, but the issue actually came from a third-party plugin. Tailwind itself does not have this problem.

If possible, I would like to understand how the variable generation works in `@themes{}`.

In the image below, which is from the Tailwind CSS playground, even though `font-sans` is not being used, the variable `--default-font-family` is still being generated.

Could you explain how this happens?

Thank you for your help!

![Image](https://github.com/user-attachments/assets/3b7260e5-d1c6-4f1a-8543-702074c5ccc7)

**Comment by philipp-spiess** [comment]
@PruthviPraj00 Playground does use the `--default-font-family` variable, it's been used by Preflight and added by default:

<img width="965" alt="Image" src="https://github.com/user-attachments/assets/7a7b4792-d075-4f69-9f0f-f2171264ce0f" />

Regarding the issue you have with a third-party plugin: Can you create a minimal reproduction so we can take a look?

**Comment by PruthviPraj00** [comment]
Hello @philipp-spiess,

The third-party plugin is [FlyonUI](https://flyonui.com/), which is a UI component library built with TailwindCSS.

You can find the zip file attached below.

[flyonui.zip](https://github.com/user-attachments/files/19449110/flyonui.zip)

**Comment by GauthierPLM** [comment]
hello,

We encounter the same issue where the font set with --font-sans is ignored.
This is the code used to load the font:

```css
@import url('./assets/fonts/fonts.css') layer(base);
@import 'tailwindcss';

@config '../tailwind.config.js';

@theme {
  --font-sans: 'Inter', var(--default-font-family);
  /* ... */
}

/* ... */
```

And the font.css file imported in index.css:

```css
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url("InterVariable.woff2") format("woff2");
}

@font-face {
  font-family: "Inter";
  font-style: italic;
  font-weight: 100 900;
  font-display: swap;
  src: url("InterVariable-Italic.woff2") format("woff2");
}
```

Rolling back to 4.0.14 fixes the issue with the font applied correctly.
