### ISSUE TITLE
Proposal: `capitalize-first`

### ISSUE THREAD

**Issue by matschik** [tailwindlabs/tailwindcss#1745]
Hello !
I was thinking about a CSS class useful to capitalize only the first letter of a string. https://caniuse.com/#feat=css-first-letter

```css
.capitalize-first::first-letter {
  text-transform: uppercase;
}
```

```html
<p class="capitalize-first">welcome to my website</p>
```
What do you think ?
