### ISSUE TITLE
Custom utility duplicates when using `@source inline(…)`

### ISSUE THREAD

**Issue by madsenmm** [tailwindlabs/tailwindcss#17499]
**What version of Tailwind CSS are you using?**

v4.1.0

**What build tool (or framework if it abstracts the build tool) are you using?**

`"@tailwindcss/cli": "^4.1.0"`

**What version of Node.js are you using?**

v22.14.0

**What browser are you using?**

Chromium (Arc)

**What operating system are you using?**

macOS

**Reproduction URL**

Tailwind playground doesn't include the v4.1.0 yet, and doesn't work in the builders version?
https://play.tailwindcss.com/OAr3yqRpwD

But this generates in an environment the following, both in watch mode, and in production builds.

```css
.pb-large {
    padding-bottom: var(--padding-large);
  }
  .pb-large {
    padding-bottom: var(--padding-large);
  }
  .pb-medium {
    padding-bottom: var(--padding-medium);
  }
  .pb-medium {
    padding-bottom: var(--padding-medium);
  }
  .pb-normal {
    padding-bottom: var(--padding-normal);
  }
  .pb-normal {
    padding-bottom: var(--padding-normal);
  }
  .pb-small {
    padding-bottom: var(--padding-small);
  }
  .pb-small {
    padding-bottom: var(--padding-small);
  }
  .pb-xlarge {
    padding-bottom: var(--padding-xlarge);
  }
  .pb-xlarge {
    padding-bottom: var(--padding-xlarge);
  }
```
