### ISSUE TITLE
RSLib with postcss tailwind adding a space on emitted css when calling tailwind function  `theme(spacing. [1.5]) `

### ISSUE THREAD

**Issue by Jordan-Hall** [tailwindlabs/tailwindcss#17551]
```
System:
    OS: Windows 11 10.0.27823
    CPU: (8) x64 Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
    Memory: 4.43 GB / 15.85 GB
Browsers:
    Edge: Chromium (135.0.3179.18)
```
```json
{
  "name": "@repo/ui",
  "version": "0.0.0",
  "sideEffects": false,
  "license": "MIT",
  "exports": {
    "./alert": {
      "types": "./dist/esm/src/Alert/index.d.ts",
      "import": "./dist/esm/Alert/index.mjs",
      "require": "./dist/cjs/Alert/index.js"
    },
    "./button": {
      "types": "./dist/esm/src/Button/index.d.ts",
      "import": "./dist/esm/Button/index.mjs",
      "require": "./dist/cjs/Button/index.js"
    },
    "./navbar": {
      "types": "./dist/esm/src/Navbar/index.d.ts",
      "import": "./dist/esm//Navbar/index.mjs",
      "require": "./dist/cjs/Navbar/index.js"
    },
    "./sidebar": {
      "types": "./dist/esm/src/Sidebar/index.d.ts",
      "import": "./dist/esm/Sidebar/index.mjs",
      "require": "./dist/cjs/Sidebar/index.js"
    },
    "./types": {
      "types": "./dist/esm/src/types.d.ts"
    },
     "./style.css": "./dist/esm/style.css",
     "./utility.css": "./dist/esm/utility.css"
  },
  "files": [
    "dist",
    "./src/**/*.css"
  ],
  "scripts": {
    "build": "rslib build",
    "dev": "rslib build --watch",
    "lint": "eslint . --max-warnings 0",
    "test": "vitest run",
    "clean": "rm -rf .turbo node_modules dist"
  },
  "dependencies": {
    "@repo/crown-fw": "*"
  },
  "devDependencies": {
    "@module-federation/rsbuild-plugin": "^0.11.3",
    "@repo/eslint-config": "*",
    "@repo/typescript-config": "*",
    "@rslib/core": "^0.6.1",
    "@tailwindcss/postcss": "^4.1.2",
    "eslint": "^8.57.0",
    "postcss": "^8.5.3",
    "postcss-loader": "^8.1.1",
    "tailwindcss": "^4.1.2",
    "typescript": "5.5.4",
    "vitest": "^3.0.9"
  },
  "publishConfig": {
    "access": "public"
  }
}
```

rslib.config.ts
```
import { type LibConfig, defineConfig } from '@rslib/core'

const shared: LibConfig = {
    bundle: false,
    dts: {
        bundle: false,
    },
}

export default defineConfig({
    lib: [
        {
            ...shared,
            source: {
                entry: {
                    index: ['./src/**', '!./src/env.d.ts'],
                },
            },
            format: 'esm',
            output: {
                distPath: {
                    root: './dist/esm',
                },
                emitCss: true,
                target: 'web'
            },
        },
        {
            ...shared,
            format: 'cjs',
            source: {
                entry: {
                    index: ['./src/**', '!./src/env.d.ts'],
                },
            },
            output: {
                distPath: {
                    root: './dist/cjs',
                },
                emitCss: true,
                target: 'web'
            },
        },
    ],
    // just for dev
    server: {
        port: 3001,
    },
    plugins: [

    ],
    tools: {
        rspack: {
            module: {
                rules: [
                    {
                        test: /\.css$/,
                        use: [
                            {
                                loader: 'postcss-loader',
                                options: {
                                    postcssOptions: {
                                        // ...
                                    },
                                },
                            },
                        ],
                    },
                ],
            }
        }
    }
})
```

when you emit the following tailwind code:
```css
@utility sidebar-footer-item {
    @apply flex items-center gap-3 cursor-pointer;
    @apply text-sm;
    color: rgb(var(--color-text-muted));
    padding: theme(spacing.[1.5]) theme(spacing.[3]);
    border-radius: var(--radius-md);
    @variant hover {
        color: rgb(var(--color-text-base));
        background-color: rgb(var(--color-muted-rgb) / var(--alpha-muted-hover));
    }
}
```

It produces the following output:
```css
@utility sidebar-footer-item {
  @apply flex items-center gap-3 cursor-pointer; @apply text-sm; color: rgb(var(--color-text-muted)) ; padding: theme(spacing. [1.5]) theme(spacing. [3]) ; border-radius: var(--radius-md) ; @variant hover { color: rgb(var(--color-text-base)) ; background-color: rgb(var(--color-muted-rgb) / var(--alpha-muted-hover)) ; }
}
```

Looks ok until you look at the function code of spacing `theme(spacing. [1.5]) ` It has a space between the . and the [1.5] it should be `theme(spacing.[1.5]) `. 

I'm not sure if this is a rslib issue or a tailwind issue
