### ISSUE TITLE
Nuxt build breaks CSS with when using `@media (width <= theme('screen.lg'))`

### ISSUE THREAD

**Issue by AntonyZ89** [tailwindlabs/tailwindcss#17615]
**What version of Tailwind CSS are you using?**

4.1.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 6.2.5

**What version of Node.js are you using?**

v20.17.0

**What browser are you using?**

Chromium & Opera

**What operating system are you using?**

Linux, Arch Linux

**Reproduction URL**

https://codesandbox.io/p/devbox/autumn-snow-pgtnw9

**Describe your issue**

I have the following CSS used in `components/Logo.vue`:

```css
.logo {
  --stroke: var(--width-md);

  &.full-stroke {
    .logo-g,
    .logo-y,
    .logo-w {
      letter-spacing: var(--tracking-wide);

      text-shadow:
        calc(1px * -1) var(--stroke) var(--color),
        calc(1px * -1) calc(1px * -1) var(--color),
        var(--stroke) calc(1px * -1) var(--color),
        calc(1px * -1) 0px var(--color),
        0px var(--stroke) var(--color),
        var(--stroke) var(--stroke) var(--color);
    }
  }
}
```

In development mode, it loads correctly:

![Image](https://github.com/user-attachments/assets/904f7691-7a40-4556-a634-0cf1e8fb63d0)

However, after building the project, the CSS doesn't load as expected:

![Image](https://github.com/user-attachments/assets/e3aca315-92dd-4440-9dfe-43ab26f29ff2)

The issue seems to be caused by missing spaces in the compiled CSS output:

```css
.logo.full-stroke .logo-g[data-v-75e84bac],.logo.full-stroke .logo-w[data-v-75e84bac],.logo.full-stroke .logo-y[data-v-75e84bac] {
    letter-spacing: var(--tracking-wide);
/*                                                    \/ missing space */
    text-shadow: -1pxvar(--stroke)var(--color),-1px-1pxvar(--color),var(--stroke)-1pxvar(--color),-1px0px var(--color),0 var(--stroke)var(--color),var(--stroke)var(--stroke)var(--color)
/*                               /\ missing space */
}
```

As you can see, there are missing spaces between values like `-1px`, `var(--stroke)`, and `var(--color)`.

I have tested the same code using only Vue (without Nuxt), and this issue does not occur. The text-shadow with CSS variables renders correctly both in development and after build.

The bug apparently occurs when using `@media` with `theme()` inside a CSS block.

Causes the bug:
```css
@media (width <= theme('screens.lg')) {
  .logo {
    --stroke: var(--width);
  }
}
```

Works fine::
```css
@media (width <= var(--breakpoint-lg)) {
  .logo {
    --stroke: var(--width);
  }
}
```

It seems that using theme() directly inside a media query might break CSS parsing or value resolution during the build process (especially when combined with other custom properties).
