### ISSUE TITLE
Font-family variable not detected after reaching specific (valid) line

### ISSUE THREAD

**Issue by noook** [tailwindlabs/tailwindcss#17684]
**What version of Tailwind CSS are you using?**

For example: v4.1.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 6.1.0

**What version of Node.js are you using?**

For example: v22.0.0

**What browser are you using?**

Firefox

**What operating system are you using?**

For example: macOS

**Reproduction URL**

https://play.tailwindcss.com/YoWr0vrT1B?file=css

**Describe your issue**

The `--font-inter` (and other font-family utilities) utility class does not appear if it is inserted after a very specific line, I can't tell why.

```css
@theme {
  --color-mdm-grey-0: #ffffff;
  --color-mdm-grey-1: #f5f5f8;
  --color-mdm-grey-2: #e6e6ee;
  --color-mdm-grey-3: #cdcedd;
  --color-mdm-grey-4: #acaec5;
  --color-mdm-grey-5: #878ba5;
  --color-mdm-grey-6: #626880;
  --color-mdm-grey-7: #3f4556;
  --color-mdm-grey-8: #20252d;
  --color-mdm-grey-9: #07080A;

  /* ....... */
  
  --font-telegraf: 'PPTelegraf';

  /* // Will work *
  // --font-inter: 'Inter';
  */
  --color-alpha-black-0: --alpha(var(--color-mdm-grey-9) / 0%);
  --color-alpha-black-10: --alpha(var(--color-mdm-grey-9) / 10%);
  --color-alpha-black-20: --alpha(var(--color-mdm-grey-9) / 20%);
  --color-alpha-black-30: --alpha(var(--color-mdm-grey-9) / 30%);
  --color-alpha-black-40: --alpha(var(--color-mdm-grey-9) / 40%);
  --color-alpha-black-50: --alpha(var(--color-mdm-grey-9) / 50%);
  --color-alpha-black-60: --alpha(var(--color-mdm-grey-9) / 60%);
  --color-alpha-black-70: --alpha(var(--color-mdm-grey-9) / 70%);
  --color-alpha-black-80: --alpha(var(--color-mdm-grey-9) / 80%);
  --color-alpha-black-90: --alpha(var(--color-mdm-grey-9) / 90%);
  --color-alpha-black-100: --alpha(var(--color-mdm-grey-9) / 100%);
  
  --color-alpha-white-0: --alpha(var(--color-mdm-grey-0) / 0%);
  --color-alpha-white-10: --alpha(var(--color-mdm-grey-0) / 10%);
  --color-alpha-white-20: --alpha(var(--color-mdm-grey-0) / 20%);
  --color-alpha-white-30: --alpha(var(--color-mdm-grey-0) / 30%);
  --color-alpha-white-40: --alpha(var(--color-mdm-grey-0) / 40%);
  /* // Will work *
  // --font-inter: 'Inter';
  */
  --color-alpha-white-50: --alpha(var(--color-mdm-grey-0) / 50%);
  /* Doesn't work from this line */
  --font-inter: 'Inter';
  --color-alpha-white-60: --alpha(var(--color-mdm-grey-0) / 60%);
  --color-alpha-white-70: --alpha(var(--color-mdm-grey-0) / 70%);
  /* // Will not work *
  // --font-inter: 'Inter';
  */
  --color-alpha-white-80: --alpha(var(--color-mdm-grey-0) / 80%);
  --color-alpha-white-90: --alpha(var(--color-mdm-grey-0) / 90%);
  --color-alpha-white-100: --alpha(var(--color-mdm-grey-0) / 100%);

  /* ....... */

}
```
