### ISSUE TITLE
Group not working with ARIA states

### ISSUE THREAD

**Issue by bronisMateusz** [tailwindlabs/tailwindcss#17713]
**What version of Tailwind CSS are you using?**

v4.1.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 6.3.0

**What version of Node.js are you using?**

v20.19.0

**What browser are you using?**

ARC, but that doesn't matter here

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/D247HaVE3L

**Describe your issue**

According to documentation: https://tailwindcss.com/docs/hover-focus-and-other-states#aria-states, my code should working, but it's not. Inspecting bars with browser dev tools, we can see empty generated classes:

![Image](https://github.com/user-attachments/assets/59277fc9-0367-4805-b686-fc1bf15dff18)

After inspecting more, we see produced code, which not working:
```css
  .group-aria-expanded\:-translate-y-1\.5 {
    &:is(:where(.group)[aria-expanded="true"] *) {
      --tw-translate-y: calc(var(--spacing) * -1.5);
      translate: var(--tw-translate-x) var(--tw-translate-y);
    }
  }
  .group-aria-expanded\:translate-y-1\.5 {
    &:is(:where(.group)[aria-expanded="true"] *) {
      --tw-translate-y: calc(var(--spacing) * 1.5);
      translate: var(--tw-translate-x) var(--tw-translate-y);
    }
  }
  .group-aria-expanded\:-rotate-45 {
    &:is(:where(.group)[aria-expanded="true"] *) {
      rotate: calc(45deg * -1);
    }
  }
  .group-aria-expanded\:rotate-45 {
    &:is(:where(.group)[aria-expanded="true"] *) {
      rotate: 45deg;
    }
  }
  .group-aria-expanded\:opacity-0 {
    &:is(:where(.group)[aria-expanded="true"] *) {
      opacity: 0%;
    }
  }
```
