### ISSUE TITLE
Form placeholders are not at 50% opacity for Firefox

### ISSUE THREAD

**Issue by iquito** [tailwindlabs/tailwindcss#17723]
**What version of Tailwind CSS are you using?**

v4.1.4

**What browser are you using?**

Firefox 128.9.0esr

**What operating system are you using?**

Debian Linux with KDE

**Reproduction URL**

https://play.tailwindcss.com/lBgTaFFT1a

**Describe your issue**

In Firefox placeholders in input elements are not at 50% opacity, they are shown in the regular text color. On Chrome/Chromium the opacity works. This seems to have changed since the initial v4 release, where opacity worked in Firefox too, and is likely because of this in the base layer:

```css
::placeholder {
  opacity: 1;
}
@supports (not (-webkit-appearance: -apple-pay-button))  or (contain-intrinsic-size: 1px) {
  ::placeholder {
    color: currentcolor;
    @supports (color: color-mix(in lab, red, red)) {
      color: color-mix(in oklab, currentcolor 50%, transparent);
    }
  }
}
```

It seems the `@supports` inside the first `@supports` is not understood by Firefox and not applied.
