### ISSUE TITLE
image-set property not converting correctly

### ISSUE THREAD

**Issue by y-anzai-colsis** [tailwindlabs/tailwindcss#17835]
**What version of Tailwind CSS are you using?**

v4.0.17

**What build tool (or framework if it abstracts the build tool) are you using?**

Astro v5.5.5
@tailwindcss/vite v4.0.17

**What version of Node.js are you using?**

v22.12.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

ideal transformation
```
bg-[image-set(url(/images/header-bg.jpg.avif)_type('image/avif'),url(/images/header-bg.jpg)_type('image/jpeg'))]
↓↓↓
.bg-\[image-set\(url\(\/images\/header-bg\.jpg\.avif\)_type\(\'image\/avif\'\)\,url\(\/images\/header-bg\.jpg\)_type\(\'image\/jpeg\'\)\)\] {
  background-image: image-set(url(/images/header-bg.jpg.avif) type('image/avif'),url(/images/header-bg.jpg) type('image/jpeg'));
}
```

transformation of reality
```
bg-[image-set(url(/images/header-bg.jpg.avif)_type('image/avif'),url(/images/header-bg.jpg)_type('image/jpeg'))]
↓↓↓
.bg-\[image-set\(url\(\/images\/header-bg\.jpg\.avif\)_type\(\'image\/avif\'\)\,url\(\/images\/header-bg\.jpg\)_type\(\'image\/jpeg\'\)\)\]{
  background-image:-webkit-image-set(url(/images/header-bg.jpg.avif) 1x type("image/avif"),url(1x) type("image/jpeg"));
  background-image:image-set(url(/images/header-bg.jpg.avif) 1x type("image/avif"),url(1x) type("image/jpeg"))
}
```

url(1x) is wrong

**Comment by wongjn** [comment]
At least in [Tailwind Play](https://play.tailwindcss.com/EesiL7NTyT), it generates fine:

```css
.bg-\[image-set\(url\(\/images\/header-bg\.jpg\.avif\)_type\(\'image\/avif\'\)\,url\(\/images\/header-bg\.jpg\)_type\(\'image\/jpeg\'\)\)\] {
  background-image: image-set(url(/images/header-bg.jpg.avif) type('image/avif'),url(/images/header-bg.jpg) type('image/jpeg'));
}
```
In [Lightning CSS playground](https://lightningcss.dev/playground/#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7274496%2C%22firefox%22%3A8388608%2C%22safari%22%3A1048576%2C%22ios_saf%22%3A1048576%7D%2C%22include%22%3A449%2C%22exclude%22%3A0%2C%22source%22%3A%22.bg-%5C%5C%5Bimage-set%5C%5C(url%5C%5C(%5C%5C%2Fimages%5C%5C%2Fheader-bg%5C%5C.jpg%5C%5C.avif%5C%5C)_type%5C%5C(%5C%5C'image%5C%5C%2Favif%5C%5C'%5C%5C)%5C%5C%2Curl%5C%5C(%5C%5C%2Fimages%5C%5C%2Fheader-bg%5C%5C.jpg%5C%5C)_type%5C%5C(%5C%5C'image%5C%5C%2Fjpeg%5C%5C'%5C%5C)%5C%5C)%5C%5C%5D%20%7B%5Cn%20%20background-image%3A%20image-set(url(%2Fimages%2Fheader-bg.jpg.avif)%20type('image%2Favif')%2Curl(%2Fimages%2Fheader-bg.jpg)%20type('image%2Fjpeg'))%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) (Tailwind uses it in production), the non-prefixed version has *no* `url()` wrappers at all:
```css
.bg-\[image-set\(url\(\/images\/header-bg\.jpg\.avif\)_type\(\'image\/avif\'\)\,url\(\/images\/header-bg\.jpg\)_type\(\'image\/jpeg\'\)\)\] {
  background-image: -webkit-image-set(url("/images/header-bg.jpg.avif") 1x type("image/avif"), url("/images/header-bg.jpg") 1x type("image/jpeg"));
  background-image: image-set("/images/header-bg.jpg.avif" 1x type("image/avif"), "/images/header-bg.jpg" 1x type("image/jpeg"));
}
```
Perhaps it's some Vite thing?
