### ISSUE TITLE
Bug: breakpoint variable is not working in @media query

### ISSUE THREAD

**Issue by hanihusam** [tailwindlabs/tailwindcss#17861]
**What version of Tailwind CSS are you using?**

v4.1.5

**What build tool (or framework if it abstracts the build tool) are you using?**

React v19.1.0, Vite v6.3.2, 

**What version of Node.js are you using?**

For example: v18.19.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

[Github repo](https://github.com/hanihusam/bug-tailwindcss-breakpoint)

**Describe your issue**

I try to use breakpoint variable in the CSS like this,

```css
@import 'tailwindcss';

@theme {
  --breakpoint-sm: 640px;
  --breakpoint-md: 768px;
}

@layer components {
  .square {
    width: 100px;
    height: 100px;


    @media (min-width: var(--breakpoint-md)) {
      width: 250px;
      height: 250px;
    }
  }
}
```

But, this way doesn't work properly as expected. That would work if we put like this,

```css
/*  ... code before */

@layer components {
  .square {
    width: 100px;
    height: 100px;

    @media (min-width: 768px) {
      width: 250px;
      height: 250px;
    }
  }
}
```
