### ISSUE TITLE
Replaces --vars to their own values in final bundle

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#1815]
My final bundle (after PurgeCSS) is full of `--space-x-reverse` which take a lot of bytes.

Is there a way (similar to purgecss) to replace any `--space-x-reverse` (or similar) to their own values?

**Comment by frederikhors** [comment]
Maybe this can help: https://github.com/MadLittleMods/postcss-css-variables ?

**Comment by emartini** [comment]
I've tried using that plugin but it fails in some cases

```css
.hover\:bg-blue-500:hover {
  background-color:#4299e1;
  background-color:undefined
}
```
