### ISSUE TITLE
Incorrect formatting of valid hyphenated values placed inside a CSS function: `fit-content` becomes `fit - content`

### ISSUE THREAD

**Issue by rozsazoltan** [tailwindlabs/tailwindcss#18219]
**What version of Tailwind CSS are you using?**

For example: v4.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**Reproduction URL**

https://play.tailwindcss.com/kbBgEMHTsM

**Describe your issue**

```html
<div class="min-h-[min(fit-content,calc(100dvh-4rem))]"></div>
```

The expected result would be:

```css
.min-h-\[min\(fit-content\,calc\(100dvh-4rem\)\)\] {
  min-height: min(fit-content, calc(100dvh - 4rem));
}
```

Instead - since it's inside a `min()` function - every hyphen gets surrounded by spaces:

```css
.min-h-\[min\(fit-content\,calc\(100dvh-4rem\)\)\] {
  min-height: min(fit - content, calc(100dvh - 4rem));
}
```
