### ISSUE TITLE
When overriding `flex-1`, two utilities are generated in the output

### ISSUE THREAD

**Issue by rozsazoltan** [tailwindlabs/tailwindcss#18215]
**What version of Tailwind CSS are you using?**

For example: v4.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**Reproduction URL**

https://play.tailwindcss.com/JbMqs7VnW1?file=css

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

The expected result would be just one utility, the new one:
```css
.flex-1 {
  flex: 1 1 0px;
}
```

But the old one is also implemented:
```css
.flex-1 {
  flex: 1 1 0px;
}
.flex-1 {
  flex: 1;
}
```

If I override the entire flex-* utility, at least the specificity will be correct:

```css
.flex-1 {
  flex: 1;
}
.flex-1 {
  flex: 1 1 0px;
}
```

https://play.tailwindcss.com/yPtNMkQL2r?file=css
