### ISSUE TITLE
[Bug] `prefix()` method not working in plugin

### ISSUE THREAD

**Issue by royvanv** [tailwindlabs/tailwindcss#2080]
The `prefix()` method does not seem to work in a custom plugin, using TailwindCSS 1.5.2.

Here's a minimal example of my Tailwind config to replicate the issue:

```js
module.exports = {
  prefix: 'tw-',
  purge: [],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [
    ({ prefix, config, addUtilities }) => {
      const prefixed = `.${prefix("prefixed")}`;
      const fromConfig = `.${config('prefix')}from-config`;

      const newUtilities = {
        [prefixed]: {
          backgroundColor: "green" // Just for testing purposes
        },
        [fromConfig]: {
          backgroundColor: "green" // Same here ;)
        }
      };

      addUtilities(newUtilities, {
        respectPrefix: false,
      });
    }
  ],
}
```

**Output (CSS):**
```css
[...]

.prefixed {
  background-color: green;
}

.tw-from-config {
  background-color: green;
}

[...]
```

I expected `.tw-prefixed` here instead of `.prefixed`. As you see, the config method does return the correct prefix.
