### ISSUE TITLE
Using @apply with variants doesn't work properly with group selectors

### ISSUE THREAD

**Issue by mikelkew** [tailwindlabs/tailwindcss#2190]
Loving the new features in 1.7 so far, thank you!

Came across what seems to be an issue with the new `applyComplexClasses` feature, in that when a variant class (e.g. `hover:bg-red-400`) is applied to a rule for a group selector, the variant modifier only works for the last selector in the group.

For example, if we have the following in the CSS:
```css
.class1,
.class2 {
  @apply hover:bg-red-400;
}
```

Then I would expect the following output:
```css
.class1:hover, .class2:hover {
  --bg-opacity: 1;
  background-color: #f98080;
  background-color: rgba(249, 128, 128, var(--bg-opacity));
}
```

But this is what I am actually getting (note that the `:hover` modifier is only applied to `.class2`):

<img width="411" alt="Screenshot 2020-08-19 at 15 37 02@2x" src="https://user-images.githubusercontent.com/4648467/90597037-a1900080-e233-11ea-990a-ce2bbf6f71d1.png">

For reference I am using v.1.7.1
