### ISSUE TITLE
Responsive Container Classes dont work

### ISSUE THREAD

**Issue by Slowwie** [tailwindlabs/tailwindcss#2339]
```
module.exports = {
  purge: [],
  theme: {
    container: {
      center: true,
      padding: {
        default: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
      },
    },
```
This do not work. Just the default has an effect to the container when compiled. 

Maybe this is in conflict with my screens config:

``` 
 screens: {
      'sm': { 'min': '640px' },
      'md': { 'min': '768px' },
      'lg': { 'min': '1024px' },
      'xl': { 'min': '1280px' },
      'xxl': { 'min': '1441px' },
      'wide': { 'min': '1601px' },
      'ultrawide': { 'min': '1901px' },
      'landscape': { 'raw': '(orientation: landscape) and (max-width: 1280px)' },
      'phone-landscape': { 'raw': '(orientation: landscape) and (max-width: 1024px)' },
      'mini-landscape': { 'raw': '(orientation: landscape) and (max-width: 640px)' },
 },
```

Is this normal that this don't work that way or is this maybe a bug?
I  tinkered around 2 hours on this today but as I said - just the default has an effect for me - not the breakpoint ones. 

I hope its my bad and not a bug. 

Tailwindcss version: 1.8.3

**Comment by adamwathan** [comment]
This is the output that is generated from your config which looks perfectly correct to me.

What do you mean by "do not work"? What behavior are you expecting that is different than what you are getting?

```css
.container {
  width: 100%;
  margin-right: auto;
  margin-left: auto;
  padding-right: 1rem;
  padding-left: 1rem
}

@media (min-width: 640px) {
  .container {
    max-width: 640px
  }
}

@media (min-width: 768px) {
  .container {
    max-width: 768px
  }
}

@media (min-width: 1024px) {
  .container {
    max-width: 1024px
  }
}

@media (min-width: 1280px) {
  .container {
    max-width: 1280px
  }
}

@media (min-width: 1441px) {
  .container {
    max-width: 1441px
  }
}

@media (min-width: 1601px) {
  .container {
    max-width: 1601px
  }
}

@media (min-width: 1901px) {
  .container {
    max-width: 1901px
  }
}

@media (min-width: 640px) {
  .sm\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .sm\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .sm\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .sm\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .sm\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .sm\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .sm\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .sm\:container {
      max-width: 1901px
    }
  }
}

@media (min-width: 768px) {
  .md\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .md\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .md\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .md\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .md\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .md\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .md\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .md\:container {
      max-width: 1901px
    }
  }
}

@media (min-width: 1024px) {
  .lg\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .lg\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .lg\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .lg\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .lg\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .lg\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .lg\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .lg\:container {
      max-width: 1901px
    }
  }
}

@media (min-width: 1280px) {
  .xl\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .xl\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .xl\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .xl\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .xl\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .xl\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .xl\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .xl\:container {
      max-width: 1901px
    }
  }
}

@media (min-width: 1441px) {
  .xxl\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .xxl\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .xxl\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .xxl\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .xxl\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .xxl\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .xxl\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .xxl\:container {
      max-width: 1901px
    }
  }
}

@media (min-width: 1601px) {
  .wide\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .wide\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .wide\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .wide\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .wide\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .wide\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .wide\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .wide\:container {
      max-width: 1901px
    }
  }
}

@media (min-width: 1901px) {
  .ultrawide\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .ultrawide\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .ultrawide\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .ultrawide\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .ultrawide\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .ultrawide\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .ultrawide\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .ultrawide\:container {
      max-width: 1901px
    }
  }
}

@media (orientation: landscape) and (max-width: 1280px) {
  .landscape\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .landscape\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .landscape\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .landscape\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .landscape\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .landscape\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .landscape\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .landscape\:container {
      max-width: 1901px
    }
  }
}

@media (orientation: landscape) and (max-width: 1024px) {
  .phone-landscape\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .phone-landscape\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .phone-landscape\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .phone-landscape\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .phone-landscape\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .phone-landscape\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .phone-landscape\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .phone-landscape\:container {
      max-width: 1901px
    }
  }
}

@media (orientation: landscape) and (max-width: 640px) {
  .mini-landscape\:container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 1rem;
    padding-left: 1rem
  }

  @media (min-width: 640px) {
    .mini-landscape\:container {
      max-width: 640px
    }
  }

  @media (min-width: 768px) {
    .mini-landscape\:container {
      max-width: 768px
    }
  }

  @media (min-width: 1024px) {
    .mini-landscape\:container {
      max-width: 1024px
    }
  }

  @media (min-width: 1280px) {
    .mini-landscape\:container {
      max-width: 1280px
    }
  }

  @media (min-width: 1441px) {
    .mini-landscape\:container {
      max-width: 1441px
    }
  }

  @media (min-width: 1601px) {
    .mini-landscape\:container {
      max-width: 1601px
    }
  }

  @media (min-width: 1901px) {
    .mini-landscape\:container {
      max-width: 1901px
    }
  }
}
 ```
