### ISSUE TITLE
Purge does not purge ALL unused classes

### ISSUE THREAD

**Issue by nartc** [tailwindlabs/tailwindcss#2341]
### Describe the problem:

After setting up a new project (Create React App) with TailwindCSS with Purge enabled, running `tailwind build ...` does not purge **ALL** unused classes (basically none should be used since it's a brand new CRA application). Config file is as follow:

```js
module.exports = {
  prefix: '',
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true
  },
  purge: {
    enabled: true,
    content: ['**/*.jsx', '**/*.js']
  },
  theme: {}
}
```

Produced CSS after `tailwind build` is at follow (truncated):

```css
...
.border-collapse {
  border-collapse: collapse;
}

.border-separate {
  border-collapse: separate;
}

.rounded {
  border-radius: 0.25rem;
}
...
@-webkit-keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

@-webkit-keyframes ping {
  75%, 100% {
    transform: scale(2);
    opacity: 0;
  }
}

@keyframes ping {
  75%, 100% {
    transform: scale(2);
    opacity: 0;
  }
}
...
```

None of the classes in the output css is used. The provided reproduction below is a Create React App but the same thing occurs for an Angular application setup. 

### Link to a minimal reproduction:

[https://github.com/nartc/react-tailwind-purge-reproduce](https://github.com/nartc/react-tailwind-purge-reproduce)
Steps:
1. Clone
2. Install
3. Run `npm run build:tw`
4. Check `tailwind.output.css` file
