### ISSUE TITLE
Breakpoint prefix in wrong place when using descendant class selectors with @ responsive

### ISSUE THREAD

**Issue by ratorx** [tailwindlabs/tailwindcss#2349]
### Describe the problem:

Tailwindcss puts the breakpoint modifier in front of the wrong class when using descendant selections (i.e. selectors of the form `.class1 .class2`) when using the @responsive breakpoint with custom classes.

I'm using `postcss` with tailwind as a plugin (other plugins: `postcss-import`).

Version: 1.8.3

### Link to a minimal reproduction:

Sorry, I couldn't figure out how to make a minimal config work; if you can link me to a `tailwind.config.js` that generates nothing and only processes the `@responsive` directive, then I can attach the results of running with that.

I've extracted the relevant lines from both files though (I think):

Input:
```css
@responsive {
  .foo .bar {
    width: 1px;
  }
}
```

Relevant lines in the output using default tailwind config (just the sm breakpoint to illustrate my point):
```css
@media (min-width: 640px) {
  /* Snipped irrelevant lines */
  .foo .sm\:bar {
    width: 1px;
  }
  /* Snipped irrelevant lines */
}
```

Expected output:
```css
@media (min-width: 640px) {
  /* Snipped irrelevant lines */
  .sm\:foo .bar {
    width: 1px;
  }
  /* Snipped irrelevant lines */
}
```

**Comment by adamwathan** [comment]
This is currently by design, Tailwind prefixes the last class in the selector not the first. This is for situations like `group-hover`, so you get this sort of output:

```css
@media (min-width: 640px) {
  .group:hover .sm\:group-hover:bg-white {
    background-color: #fff;
  }
}
```

The best workaround for now is to use an attribute selector for the part you don't want prefixed:

```css
@responsive {
  .foo [class~="bar"] {
    width: 1px;
  }
}
```

I'm hoping to add a feature for Tailwind 2.0 that lets you specify explicitly which class should be the "target" for variants but no plans to change the default behavior right now since it would be a breaking change.

It'll probably be something like this:

```css
@responsive {
  [variant-target-class="foo"] .bar {
    width: 1px;
  }
}
```

...which would then output:

```css
@media (min-width: 640px) {
  /* Snipped irrelevant lines */
  .sm\:foo .bar {
    width: 1px;
  }
  /* Snipped irrelevant lines */
}
```

Again recommend the attribute selector workaround for now, and hopefully we can offer more control here in 2.0 👍
