### ISSUE TITLE
PostCSS each in conjunction with @responsive... vars are not expanded?

### ISSUE THREAD

**Issue by gremo** [tailwindlabs/tailwindcss#2369]
Assume that you have the following CSS variable:

```css
:root {
  --colors: red, green, blue;
}
```

With PostCSS each plugin I can easly loop and dynamically create 3 classes:

```css
@each $color in var(--colors) {
  .myclass-$(color) {
    color: $(color);
  }
}
```

```css
.myclass-red{
  color: red;
}

/* other classes ... */
```

Wrapping in `@responsive` doesn't work anymore, example output:

```css
@responsive {
  @each $color in var(--colors) {
    .myclass-$(color) {
      color: $(color);
    }
  }
}
```

```css
.sm\:myclass-\$\(color\) {
  color: red;
}

/* other classes ... */
```

I'm using the same syntax, just wrapping my original code with `@responsive` directive. Am I missing something or it's a bug?
