### ISSUE TITLE
Generate a "combination" of @responsive utilities when using multiple class selector

### ISSUE THREAD

**Issue by gremo** [tailwindlabs/tailwindcss#2485]
### Describe the problem:

Unable to generate a "combination" of `@responsive` utilities when using multiple class selector i.e. `.foo.bar`.

For example, given the breakpoints `md` and `lg` it's not possible to obtain a combination of multiple class selectors at specific brekpoints, that it `.foo.bar, .md:foo.md:bar, .lg:foo.lg:bar` .

This:

```css
@responsive { .foo {} }
@responsive { .bar {} }
```

Generates `.foo, .md:foo, .lg:foo, .bar, .md:bar, .lg:bar`.

This instead:

```css
@responsive { .foo {} }
@responsive { .foo.bar {} }
```

Generates `.foo, .md:foo, .lg:foo, .md:foo.bar, .lg:foo.bar`.

Of course this:

```css
@responsive { .foo {} }
@responsive { .bar.foo {} }
```

Will do the opposite `.foo, .md:foo, .lg:foo, .bar.foo, .md:bar.foo, .lg:bar.foo`.

AFAIK `@responsive` can't be nested to do what I mean?

**Comment by adamwathan** [comment]
Can you explain the behavior you actually want when you do this?

```css
@responsive {
  .foo.bar {}
}
```

And what is the use case for wanting to do this? Currently Tailwind applies variant prefixes to the last class in a selector by default, although we have considered ideas for making this configurable somehow in the future if there is a good reason for it.

**Comment by minhkun99** [comment]
Hi

**Comment by minhkun99** [comment]
Hi

**Comment by gremo** [comment]
@adamwathan I actually started a discussion in the discussion section: https://github.com/tailwindlabs/tailwindcss/discussions/2482

It's just an example, probably not the smartest one:

```css
@responsive {
  /* row flex layout, nothing special but with wrapping */
  .flex-x {
    @apply flex flex-wrap;
  }

  /* horizontal center for row flex layout */
  .flex-x.flex-x-center {
    @apply justify-center;
  }

  /* vertical center for row flex layout */
  .flex-x.flex-y-center {
    @apply items-center;
  }
}
```

Use case:

```html
<!-- the teal box is centered both vertically and horizontally -->
<div class="flex-x flex-x-center flex-y-center" style="height: 400px">
  <div class="h-24 w-24 bg-teal-700"></div>
</div>
```

Not working example (because the way the `@responsive` prefix things):

```html
<!-- not working! -->
<div class="md:flex-x md:flex-x-center md:flex-y-center" style="height: 400px">
  <div class="h-24 w-24 bg-teal-700"></div>
</div>
```

**Comment by adamwathan** [comment]
Gotcha! Any reason you aren't just doing this?

```css
@responsive {
  /* row flex layout, nothing special but with wrapping */
  .flex-x {
    @apply flex flex-wrap;
  }

  /* horizontal center for row flex layout */
  .flex-x-center {
    @apply justify-center;
  }

  /* vertical center for row flex layout */
  .flex-y-center {
    @apply items-center;
  }
}
```

I would like to add the ability for people to control what classes in a selector are the target of variant prefixes eventually but waiting for enough evidence that it's really necessary before doing it.

**Comment by gremo** [comment]
Sorry for the late response @adamwathan .

> Gotcha! Any reason you aren't just doing this?

Yes, of course I can. But I would like to make `.flex-x-center` always center horizontally, despite the fact of using `.flex-x` (horizontal layout) or `.flex-y` (vertical layout).

 That's why my question in the first place. `@responsive` utility actually doesn't care about class chaining: `.flex-x.flex-x-center` will always be `.md:.flex-x.flex-x-center` instead of `.md:.flex-x.md:flex-x-center`.

Do you plan to handle or give the ability to customize the handling of CSS class chaining in `@responsive`?

**Comment by arcanedev-maroc** [comment]
Hi @adamwathan, i think i have the same issue with the `@responsive` but with nested classes (SCSS).

This is a quick example:

```scss
@responsive {
    .list-group {
        background-color: #bada55;
        color: #bada55;

        & > .list-group-item {
            color: black;
        }
    }
}
```

The generated css:

```css
.list-group {
  background-color: #bada55;
  color: #bada55;
}

.list-group > .list-group-item {
  color: black;
}

@media (min-width: 640px){
  .sm\:list-group {
    background-color: #bada55;
    color: #bada55;
  }

  .list-group > .sm\:list-group-item {
    color: black;
  }
}

@media (min-width: 768px){
  .md\:list-group {
    background-color: #bada55;
    color: #bada55;
  }

  .list-group > .md\:list-group-item {
    color: black;
  }
}

// etc
```

So i can't use the responsive utilities by doing this:

```html
<div class="sm:list-group">
    <div class="list-group-item">Item 1</div>
    <div class="list-group-item">Item 2</div>
    <div class="list-group-item">Item 3</div>
</div>
<div class="md:list-group">
    <div class="list-group-item">Item 1</div>
    <div class="list-group-item">Item 2</div>
    <div class="list-group-item">Item 3</div>
</div>
```

Is that the intended behavior for the `@responsive` ?

What i want to be generated is this instead:

```css
.list-group {
  background-color: #bada55;
  color: #bada55;
}

.list-group > .list-group-item {
  color: black;
}

@media (min-width: 640px){
  .sm\:list-group {
    background-color: #bada55;
    color: #bada55;
  }

  .sm\:list-group > .list-group-item {
    color: black;
  }
}

@media (min-width: 768px){
  .md\:list-group {
    background-color: #bada55;
    color: #bada55;
  }

  .md\:list-group > .list-group-item {
    color: black;
  }
}

// etc
```
