### ISSUE TITLE
child selectors should exclude absolute positioned elements

### ISSUE THREAD

**Issue by smeijer** [tailwindlabs/tailwindcss#2490]
### Describe the problem:
The generated child selectors for `space` and `divide` should exclude absolute positioned elements. The current selector includes elements that have been pulled out of the document flow.

For example, `space-y-4` also applies the margin to an absolute positioned child element, and `divide-y` applies a border to it. See the codepen below.

```css
/* this should also exclude > .absolute */
.space-x-5 > :not(template) ~ :not(template) {
    --space-x-reverse: 0;
    margin-right: calc(1.25rem * var(--space-x-reverse));
    margin-left: calc(1.25rem * calc(1 - var(--space-x-reverse)));
}
```

### Link to a minimal reproduction:
https://codepen.io/smeijer/pen/vYGoVWe?editors=1010
