### ISSUE TITLE
Font family not quoted: issues with PostCSS Font Magician

### ISSUE THREAD

**Issue by gremo** [tailwindlabs/tailwindcss#2527]
### Describe the problem:

[PostCSS Font Magician](https://github.com/jonathantneal/postcss-font-magician) is a tool for "extracting" font families and adding `@font-face` rules.

The plugin [`fontFamily.js`](https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/fontFamily.js) is not adding quotes around font families, i.e:

```javascript
// tailwind.config.js
fontFamily: {
   'open-sans': ['Open Sans', 'sans-serif'],
},
```

Will result in:

```css
.font-open-sans {
  font-family: Open Sans, sans-serif;
}
```

This is not an issue normally, however the above plugin will extract it using [`getFirstFontFamily`](https://github.com/jonathantneal/postcss-font-magician/blob/master/index.js#L231) the family as `Sans` and not `Open Sans`.

This will make it work, but I think it's a good idea to quote the font family anyways:

```css
.font-open-sans {
  font-family: Open Sans, sans-serif;
}
```

**EDIT**: at least, this seems to work:

```javascript
// tailwind.config.js
fontFamily: {
   'open-sans': ['"Open Sans"', 'sans-serif'],
},
```

... but maybe it should be documented or quoted automatically?
