### ISSUE TITLE
boxShadow focus theme property is not applied correctly

### ISSUE THREAD

**Issue by pepjo** [tailwindlabs/tailwindcss#2865]
Tailwind version: 2.0.1

### Describe the problem:
I am modifying the theme to have a different `focus` styling of `boxShadow`. The configuration looks like this:
```js
module.exports = {
  theme: {
    extend: {
      boxShadow: {
      focus: '0 0 2px 5px rgba(0,0,0,0.5)',
    },
    },
  },
  variants: {},
  plugins: [],
}
```

However, the css classes generated look like this:
```css
.shadow-focus {
    --tw-shadow: 0 0 2px 5px rgba(0,0,0,0.5);
}
.group:hover .group-hover\:shadow-sm, .shadow-focus {
    box-shadow: var(--tw-ring-offset-shadow,0 0 transparent),var(--tw-ring-shadow,0 0 transparent),var(--tw-shadow);
}

.focus\:shadow-md:focus, .focus\:shadow:focus {
    box-shadow: var(--tw-ring-offset-shadow,0 0 transparent),var(--tw-ring-shadow,0 0 transparent),var(--tw-shadow);
}
.focus\:shadow:focus {
    --tw-shadow: 0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);
}
```
as you can see, the focus styles are applied to a class named `shadow-focus`, but I would like them to be applied to the variant `focus:shadow` instead.

### Link to a minimal reproduction:
https://play.tailwindcss.com/hOKmlgQH2P
