### ISSUE TITLE
Ring opacity variable being set to 1 on Ring Color

### ISSUE THREAD

**Issue by marceloadsj** [tailwindlabs/tailwindcss#2946]
### Describe the problem:

Basically, if you create a common class for a component using ring opacity, let's say:

```css
.btn {
  @apply ring-opacity-50;
}
```

Then create specific classes for each variant using ring color, example:

```css
.btn-success {
  @apply ring-green-500;
}
```

The ring color utility will set --tw-ring-opacity to 1. As it comes after the first one, it will overwrite the opacity of the common class.

Maybe, instead of the ring color being like this:

```css
.ring-green-500 {
  --tw-ring-opacity: 1;
  --tw-ring-color: rgba(16, 185, 129, var(--tw-ring-opacity));
}
```

It could be like that:

```css
.ring-green-500 {
  --tw-ring-color: rgba(16, 185, 129, var(--tw-ring-opacity, 1));
}
```

### Link to a minimal reproduction:

https://play.tailwindcss.com/TaUPvS5ZDq?file=css
