### ISSUE TITLE
dark variant not respecting bg-opacity

### ISSUE THREAD

**Issue by Yiddishe-Kop** [tailwindlabs/tailwindcss#2966]
### Describe the problem:

I have `darkMode: 'class'` in my config.

When using these classes: `bg-gray-100 bg-opacity-50 dark:bg-gray-900 `, the `bg-opacity` is only applied in light mode, but in dark mode `bg-opacity` is ignored.

I had to add the `dark` variant to: `backgroundOpacity: ['dark']`, then also add `dark:bg-opacity-50` to the element to get it to work in dark mode.

Expected behaviour: dark mode should also respect the `bg-opacity` class (unless overriden for dark).

### Link to a minimal reproduction:
https://play.tailwindcss.com/GHoILXz6cp

**Comment by Yiddishe-Kop** [comment]
I've narrowed down the issue:

`bg-opacity-40` is correctly setting `--tw-bg-opacity` to `0.4`, but `dark:bg-gray-900` is also overriding `--tw-bg-opacity` back to the default `1`.

See screenshot:
![CleanShot 2020-12-01 at 3 24 09](https://user-images.githubusercontent.com/36875437/100746466-692ebf80-33e9-11eb-85d0-d4ea48efc146.png)

I guess the order needs to be changed, so that `bg-opacity-40` shouldn't be overriden by `dark:bg-gray-900`.

**Comment by adamwathan** [comment]
Yeah this is currently by design for better or for worse, and is the same with media queries too like:

```
bg-blue-500 bg-opacity-50 md:bg-red-500
```

That won't preserve the opacity either. I can see arguments for both behaviors but unfortunately we likely can't change this as it would be a breaking change.

We should probably enable `dark` by default for the opacity utilities though, would accept a PR for that 👍🏻

**Comment by marceloadsj** [comment]
Couldn't the:

```css
.dark .dark\:bg-gray-900 {
    --tw-bg-opacity: 1;
    background-color: rgba(17, 24, 39, var(--tw-bg-opacity));
}
```

Be like this, instead?

```css
.dark .dark\:bg-gray-900 {
    background-color: rgba(17, 24, 39, var(--tw-bg-opacity, 1));
}
```

I'm not seeing any downside, but I don't have a big picture to think off right now.
