### ISSUE TITLE
Unable to purge custom utilites with specific names

### ISSUE THREAD

**Issue by smhmd** [tailwindlabs/tailwindcss#3000]
**this is perhaps upstream with purgecss.**
### Describe the problem:

Used the `?` utility from this [tweet](https://twitter.com/gavinjoyce/status/1333412203232374785) as such:
```css
@tailwind utilities;

@layer utilities {
  .\? {
    animation: wobble 0.7s ease-in-out alternate infinite;
  }

  @keyframes wobble {
    0% {
      box-shadow: inset 4px 4px rgb(236, 15, 170),
        inset -4px -4px rgb(236, 15, 170);
    }
    100% {
      box-shadow: inset 8px 8px rgb(236, 15, 170),
        inset -8px -8px rgb(236, 15, 170);
    }
  }
}
```

In dev:
```fish
$ npx tailwindcss build tailwind.css | grep -A 14 '\.\\?'
.\? {
  animation: wobble 0.7s ease-in-out alternate infinite;
}...
```
And in production:
```fish
$ NODE_ENV=production npx tailwindcss build tailwind.css | grep -A 14 '\.\\?'
.\? {
  animation: wobble 0.7s ease-in-out alternate infinite;
}...
```
Without `?` being used in any purgable file. The same for `!` and `*` classes (can be grepped with `\.\\!` and `\.\\\*`.)

Oddly enough, the class `??` is purged.

---

Note: the `@keyframes wobble` code is never purged. Could we have a `@purge` layer for dev-only classes (like a11y classes)?
```css
@layer purge {
  .\? {...}
  @keyframes wobble {...}
}
```
### Link to a minimal reproduction:

https://play.tailwindcss.com/HICw8n5aYQ
