### ISSUE TITLE
Bug in selector :not(.class)

### ISSUE THREAD

**Issue by gabrielzevedo** [tailwindlabs/tailwindcss#3034]
### Describe the problem:

Source code:
```
.class-test {
    @apply text-gray-600 font-semibold;
}

p:not(.font-semibold) {
    @apply text-red-500;
}
```

Compiled code:
```
.class-test {
    font-weight: 600;
    --tw-text-opacity: 1;
    color: rgba(75, 85, 99, var(--tw-text-opacity));
}

p:not(.font-semibold) {
    --tw-text-opacity: 1;
    color: rgba(239, 68, 68, var(--tw-text-opacity));
}

p:not(.class-test) {
    --tw-text-opacity: 1;
    color: rgba(239, 68, 68, var(--tw-text-opacity));
}
```
**p:not(.class-test)** it shouldn't exist, am I right?

### Link to a minimal reproduction:

https://play.tailwindcss.com/YEUzDzel23?file=css

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is indeed pretty odd!
I will take a look!

**Comment by RobinMalfait** [comment]
Okay so while this looks odd at first, it is the expected behaviour. 
Let's see why this happens:

When you are using `@apply some-class` you want to apply all the logic/behaviour from the `some-class` utility.

E.g.:

```css
.btn { @apply hover:bg-gray-100; }
.btn-rounded { @apply btn rounded; }
```

This results in 

```css
.btn:hover {
  --tw-bg-opacity: 1;
  background-color: rgba(243, 244, 246, var(--tw-bg-opacity));
}

.btn-rounded {
  border-radius: 0.25rem;
}

.btn-rounded:hover {
  --tw-bg-opacity: 1;
  background-color: rgba(243, 244, 246, var(--tw-bg-opacity));
}
```

Notice that we see the `:hover` behaviour twice, because you applied all the rules. In essence `btn-rounded` should behave like `btn` with extra styles on top (in this case the `rounded` utility is extra).

This also means that when you apply `font-semibold` to `class-test` that `class-test` should behave like `font-semibold` (because you applied that one). This also means that because you used `p:not(.font-semibold) { }` that this behaviour is also copied over to the `class-test` and therefore you see this behaviour.
