### ISSUE TITLE
Javascript heap out of memory running webpack-dev-server

### ISSUE THREAD

**Issue by abepark01** [tailwindlabs/tailwindcss#3072]
### Describe the problem:

I am running a rails 6.0 project with the following dependencies:

1. tailwindcss 2.0.2
2. @rails/webpacker 5.2.1
3. postcss 7.0.32
4. postcss-import 12.0.1
5. postcss-nested 4.2.3.
6. webpack-dev-server 3.11.0

When I run webpack-dev-server, I get a Javascript heap out of memory error

This particular project imports many other CSS files.

### CSS that causes the memory leak
In this case, the selector .flex is causing webpack-dev-server to hang without any error message getting displayed.

```css
.user-block__container .flex .or {
  @apply m-5 text-lg text-center text-grey-lighter;
}

.user-block__container .flex a {
  line-height: 2.08;
  cursor: pointer;
  text-transform: uppercase;
  letter-spacing: 1.7;
  text-decoration: none;
  @apply flex items-center justify-center text-center text-white border border-solid ff-ilisarniq-bold h-13 text-13px br-25px border-blue-darker bg-blue-darker pr-9 pl-9;
}
```

## Workaround
Removing the .flex in the selector (.user-block__container .flex a) fixes the issue.

##  Top-level CSS file application.css content
```css
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@import './global';
@import './layout';
@import './footer';
@import './typography';
@import './backgrounds';
@import './fonts';
@import './animations';
@import './buttons';
@import './tables';
@import './lists';
@import './forms';
@import './navs';
@import './login';
@import './landing-page';
@import './responsive';
@import './components/modal';
@import './components/card';
@import './components/breadcrumbs.css';
@import './components/flash-messages.css';
@import './components/ratings.css';
@import './components/sections';
@import './components/select2';
@import './components/switch';
@import './components/tooltips';
@import './modules/admin';
@import './modules/collective';
@import './modules/favorites';
@import './modules/google-maps';
@import './modules/one-pager';
@import './modules/payment-sources';
@import './modules/skills';
@import './modules/sponsorships';
@import './modules/stripe';
@import './modules/trix-editor';
@import './modules/venture';
@import './pages/about';
@import './pages/recruiting';
@import './pages/search';

trix-toolbar [data-trix-button-group='file-tools'] {
  display: none;
}
```

### Error Message
> <--- Last few GCs --->
> 
> [14475:0x1046d0000]  2520011 ms: Scavenge 3946.4 (4126.4) -> 3935.2 (4126.4) MB, 5.5 / 0.0 ms  (average mu = 0.331, current mu = 0.319) allocation failure
> [14475:0x1046d0000]  2520040 ms: Scavenge 3947.9 (4126.8) -> 3941.2 (4126.6) MB, 11.8 / 0.0 ms  (average mu = 0.331, current mu = 0.319) allocation failure
> [14475:0x1046d0000]  2520072 ms: Scavenge 3951.1 (4126.9) -> 3940.7 (4126.9) MB, 7.8 / 0.0 ms  (average mu = 0.331, current mu = 0.319) allocation failure
> 
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
>  1: 0x1012e2bc5 node::Abort() (.cold.1) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  2: 0x1000a5cb9 node::Abort() [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  3: 0x1000a5e1f node::OnFatalError(char const*, char const*) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  4: 0x1001e83e7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  5: 0x1001e8383 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  6: 0x100397275 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  7: 0x100398d3a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  8: 0x100394409 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
>  9: 0x100391ca1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
> 10: 0x1003a053a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
> 11: 0x1003a05c1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
> 12: 0x10036df67 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
> 13: 0x1006ecca8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
> 14: 0x100a795f9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/abepark/.nvm/versions/node/v14.15.1/bin/node]
> [1]    14475 abort      ./bin/webpack-dev-server
>
