### ISSUE TITLE
CSS file fails to get built when purge.enabled is set to true

### ISSUE THREAD

**Issue by GHNewbiee** [tailwindlabs/tailwindcss#3080]
### Describe the problem:
When `purge.enabled` is set to `true` the `css` file build fails.

*tailwindcss: 2.0.1*

### Reproduction:
A very simple config file as follows is enough to cause build failure.

*tailwind.config.js*
```js
module.exports = {
  purge: {
    enabled: true,
    content: [
      './src/**/*.html',
      './src/**/*.js',
      './src/**/*.ts',
    ],
  },
}
```
but the following ones work fine:
```js
module.exports = {
  purge: {
    enabled: false,
    content: [
      './src/**/*.html',
      './src/**/*.js',
      './src/**/*.ts',
    ],
  },
}
```
and
```js
module.exports = {
  purge: [
    './src/**/*.html',
    './src/**/*.js',
    './src/**/*.ts',
  ],
}
```

**Comment by LeLocTai** [comment]
Same here. Building also work if the glob array is empty. To be more precise, the problem is causing the css files to be passed through, keeping all the `@tailwind` directives intact. No error messages is present.

**Comment by LeLocTai** [comment]
Interestingly, using raw content work as expected:
```js
module.exports = {
	purge: {
		enabled: true,
		content: [
			{
				raw: '<html><body><div class="mx-auto"></div></body></html>',
				extension: 'html'
			},
		],
	}
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you provide more information on this case?

- Can you create a minimal reproduction repository that showcases the issue?
- Can you show the actual error that you get, apart from the "it fails to build"?
- Can you verify that files in those `./src` files exists?
- Can you share your Node version (or check that you are on node 12.13 or higher)?

I tried reproducing it with the information you mentioned, but I don't have any issues.

**Comment by GHNewbiee** [comment]
> Can you provide more information on this case?

Sure, but as my skills allow.

>  - Can you create a minimal reproduction repository that showcases the issue?

Unfortunately, it's still beyond my skills.

>    Can you show the actual error that you get, apart from the "it fails to build"?
```bash
$ npx tailwindcss build ./tailwind.css -o ./tailwind.lit.css -c ./tailwind.config.js
  
  tailwindcss 2.0.2
  
  🚀 Building: tailwind.css
  
  ✅ Finished in 21 s
  📦 Size: 9.02KB
  💾 Saved to tailwind.lit.css
```

Note that the size of the file is very small to be the correct one!

>  - Can you verify that files in those ./src files exists?

Yes, I do verify that they do exist.

>  - Can you share your Node version (or check that you are on node 12.13 or higher)?

It's 15.4.0.

> I tried reproducing it with the information you mentioned, but I don't have any issues.

Run to play lottery, it's your super lucky day!

It seems that for me and @LeLocTai, it's an unlucky day! The stars and planets are not aligned in a correct manner! -:)

**Comment by RobinMalfait** [comment]
Yeah, I can't reproduce it, I need more information... A repository that showcases the error would be best. While I wait for that.

- Can you share what the `tailwind.css` looks like?
- Can you share an example file inside `./src` that contains a tailwind class that is missing?

**Comment by GHNewbiee** [comment]
**tailwind.css**
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
**tailwind.lit.css**
```css
*,
*::before,
*::after {
  box-sizing: border-box;
}

:root {
  -moz-tab-size: 4;
  -o-tab-size: 4;
     tab-size: 4;
}

*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e2e8f0; /* 2 */
}

* {
  --tw-shadow: 0 0 #0000;
}

* {
  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
}

@-webkit-keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

@-webkit-keyframes ping {
  75%, 100% {
    transform: scale(2);
    opacity: 0;
  }
}

@keyframes ping {
  75%, 100% {
    transform: scale(2);
    opacity: 0;
  }
}

@-webkit-keyframes pulse {
  50% {
    opacity: .5;
  }
}

@keyframes pulse {
  50% {
    opacity: .5;
  }
}

@-webkit-keyframes bounce {
  0%, 100% {
    transform: translateY(-25%);
    -webkit-animation-timing-function: cubic-bezier(0.8,0,1,1);
            animation-timing-function: cubic-bezier(0.8,0,1,1);
  }

  50% {
    transform: none;
    -webkit-animation-timing-function: cubic-bezier(0,0,0.2,1);
            animation-timing-function: cubic-bezier(0,0,0.2,1);
  }
}

@keyframes bounce {
  0%, 100% {
    transform: translateY(-25%);
    -webkit-animation-timing-function: cubic-bezier(0.8,0,1,1);
            animation-timing-function: cubic-bezier(0.8,0,1,1);
  }

  50% {
    transform: none;
    -webkit-animation-timing-function: cubic-bezier(0,0,0.2,1);
            animation-timing-function: cubic-bezier(0,0,0.2,1);
  }
}

@media (min-width: 640px) {
}

@media (min-width: 768px) {
}

@media (min-width: 1024px) {
}

@media (min-width: 1280px) {
}

@media (min-width: 1536px) {
}
```

**Note**: Comments have been removed.
