### ISSUE TITLE
Font Variants doesn't work with @apply

### ISSUE THREAD

**Issue by JuanM04** [tailwindlabs/tailwindcss#3154]
### Describe the problem:

[Font Variant Numeric](https://tailwindcss.com/docs/font-variant-numeric) utility-classes doesn't work with `@apply`. More information inside the example

### Link to a minimal reproduction:

https://play.tailwindcss.com/YVSoUAWfpa

**Comment by adamwathan** [comment]
Wow this is a weird bug, thanks for reporting! Note for future self or anyone else who tries to fix this one, this input:

```css
.custom-class {
  @apply font-bold tabular-nums;
}
```

...is producing this output:

```css
.ordinal, .slashed-zero, .lining-nums, .oldstyle-nums, .proportional-nums, .tabular-nums, .diagonal-fractions, .stacked-fractions {
  --tw-ordinal: var(--tw-empty,/*!*/ /*!*/);
  --tw-slashed-zero: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-figure: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-spacing: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-fraction: var(--tw-empty,/*!*/ /*!*/);
  font-variant-numeric: var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)
}

.custom-class {
  --tw-numeric-spacing: tabular-nums;
  font-weight: 700
}
```

It makes no sense that that first declaration is being added, instead I would have expected something more like this:

```css
.custom-class {
  --tw-ordinal: var(--tw-empty,/*!*/ /*!*/);
  --tw-slashed-zero: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-figure: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-spacing: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-fraction: var(--tw-empty,/*!*/ /*!*/);
  font-variant-numeric: var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)
}

.custom-class {
  --tw-numeric-spacing: tabular-nums;
  font-weight: 700
}
```

Even that output might not give the expected results though. Two ways I can think to solve this:

1. Figure out the actual bug in `@apply` here, which we should probably do no matter what but might still leave unexpected results in this particular situation (thinking conflicts between `custom-class` and other font variant numeric rules on the same element).

2. Change the font variant numeric utilities to use `* { ... }` for the initial reset, like we do for shadows and stuff now. That is probably a better solution but would have to evaluate if it's a breaking change.

**Comment by JuanM04** [comment]
I noticed the first piece of code you shared, but then I noticed that regular `tabular-nums` also stopped working. Maybe it's purgecss fault.

Also, maybe one solution could be this (I don't know much of Tailwind CSS generation):

```css
.custom-class, ​.​ordinal​,​ .​slashed-zero​,​ .​lining-nums​,​ .​oldstyle-nums​,​ .​proportional-nums​,​ .​tabular-nums​,​ .​diagonal-fractions​,​ .​stacked-fractions​ {
  ​--tw-ordinal​: ​var​(​--tw-empty​,​/*!*/​ ​/*!*/​);
  ​--tw-slashed-zero​: ​var​(​--tw-empty​,​/*!*/​ ​/*!*/​);
  ​--tw-numeric-figure​: ​var​(​--tw-empty​,​/*!*/​ ​/*!*/​);
  ​--tw-numeric-spacing​: ​var​(​--tw-empty​,​/*!*/​ ​/*!*/​);
  ​--tw-numeric-fraction​: ​var​(​--tw-empty​,​/*!*/​ ​/*!*/​);
  ​font-variant-numeric​: ​var​(​--tw-ordinal​) ​var​(​--tw-slashed-zero​) ​var​(​--tw-numeric-figure​) ​var​(​--tw-numeric-spacing​) ​var​(​--tw-numeric-fraction​)
}
```

**Comment by adamwathan** [comment]
Nope the reason that regular `tabular-nums` stops working is because the big long reset declaration gets added an extra time, which overrides the regular `tabular-nums` class:

```css
.ordinal, .slashed-zero, .lining-nums, .oldstyle-nums, .proportional-nums, .tabular-nums, .diagonal-fractions, .stacked-fractions {
  --tw-ordinal: var(--tw-empty,/*!*/ /*!*/);
  --tw-slashed-zero: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-figure: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-spacing: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-fraction: var(--tw-empty,/*!*/ /*!*/);
  font-variant-numeric: var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)
}

.tabular-nums {
  --tw-numeric-spacing: tabular-nums;
}

.ordinal, .slashed-zero, .lining-nums, .oldstyle-nums, .proportional-nums, .tabular-nums, .diagonal-fractions, .stacked-fractions {
  --tw-ordinal: var(--tw-empty,/*!*/ /*!*/);
  --tw-slashed-zero: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-figure: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-spacing: var(--tw-empty,/*!*/ /*!*/);
  --tw-numeric-fraction: var(--tw-empty,/*!*/ /*!*/);
  font-variant-numeric: var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction)
}

.custom-class {
  --tw-numeric-spacing: tabular-nums;
  font-weight: 700
}
```

We'll figure this out for sure when we have a chance.
