### ISSUE TITLE
(Almost) duplicate preflight css styles

### ISSUE THREAD

**Issue by ahansson** [tailwindlabs/tailwindcss#3166]
### Describe the problem:

In [@2.0.2/dist/base.css](https://unpkg.com/tailwindcss@2.0.2/dist/base.css) a section of Tailwind's own base styles mostly just duplicate Sindre Sørhus' styles from modern-normalize.

Tailwind's comment block doesn't indicate that their intention was to overwrite modern-normalize by adding `Monaco` and `Courier New` (and removing `font-size`), so there may be a minor optimization opportunity here.

```css

/**---------  modern-normalize: -----------------------------------*/

/**
1. Improve consistency of default fonts in all browsers. (https://github.com/sindresorhus/modern-normalize/issues/3)
2. Correct the odd 'em' font sizing in all browsers.
*/

code,
kbd,
samp,
pre {
  font-family:
    ui-monospace,
    SFMono-Regular,
    Consolas,
    'Liberation Mono',
    Menlo,
    monospace; /* 1 */
    font-size: 1em; /* 2 */
}

/**---------- Tailwind's own style further down in base.css ---------*/

/**
 * Use the configured 'mono' font family for elements that
 * are expected to be rendered with a monospace font, falling
 * back to the system monospace stack if there is no configured
 * 'mono' font family.
 */

pre,
code,
kbd,
samp {
  font-family: 
    ui-monospace, 
    SFMono-Regular, 
    Menlo, 
    Monaco, 
    Consolas, 
    "Liberation Mono", 
    "Courier New", 
    monospace;
}
```

**Comment by adamwathan** [comment]
Hey! The main difference is that Preflight is using `fontFamily.mono` from your config file, it just happens to be the same if the user hasn't overridden it. Here's the source from preflight.css:

```css
/**
 * Use the configured 'mono' font family for elements that
 * are expected to be rendered with a monospace font, falling
 * back to the system monospace stack if there is no configured
 * 'mono' font family.
 */

pre,
code,
kbd,
samp {
  font-family: theme('fontFamily.mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace);
}
```

So while the output *can* be the same it's not always the same. If someone changes their monospace font to `Monolisa` for example then Tailwind will make that the default monospace font for code elements, whereas the styles in modern-normalize are (logically) static.
