### ISSUE TITLE
It would be helpful to have a `.no-scrollbar` class that hides the scrollbar without removing its functionality, this is the code:

### ISSUE THREAD

**Issue by FourLineCode** [tailwindlabs/tailwindcss#3190]
It would be helpful to have a `.no-scrollbar` class that hides the scrollbar without removing its functionality, this is the code:
```css
/* Chrome, Safari and Opera */
.no-scrollbar::-webkit-scrollbar {
  display: none;
}

.no-scrollbar {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}
```

_Originally posted by @GiraffeKey in https://github.com/tailwindlabs/tailwindcss/discussions/2394_
