### ISSUE TITLE
Bug about @apply rule, hover-active order and :focus

### ISSUE THREAD

**Issue by mingcenwei** [tailwindlabs/tailwindcss#3306]
### Describe the problem:

```css
@layer components {
	.test-1 {
		@apply text-black underline;
	}
	.test-1:hover,
	.test-1:focus {
		@apply text-red-500;
	}
	.test-1:active {
		@apply text-white bg-red-500;
	}
	.another-class-1 {
		@apply test-1;
	}
}
```

Expected: When either `.test-1` or `.another-class-1` is clicked (and hovered over), its text color will turn white.
Actual: When `.test-1` is clicked (and hovered over), its text color will remain red; nevertheless, when `.another-class-1` is clicked (and hovered over), its text color will turn white.

```css
@layer components {
	.test-2 {
		@apply text-black underline;
	}
	.test-2:hover {
		@apply text-red-500;
	}
	.test-2:active {
		@apply text-white bg-red-500;
	}
	.another-class-2 {
		@apply test-2;
	}
}
```

If we remove the :focus pseudo-class, then `.test-2` will function properly.

```css
@layer components {
	.test-3 {
		@apply text-black underline;
	}
	.test-3:hover,
	.test-3:focus {
		@apply text-red-500;
	}
	.test-3:active {
		@apply text-white bg-red-500;
	}
}
```

Also, if we keep the :focus pseudo-class, but instead remove the class `.another-class-3` which applies `.test-3`, then `.test-3` will function properly as well.

### Link to a minimal reproduction:

https://play.tailwindcss.com/HBIUNTOOZW?file=css

**Comment by adamwathan** [comment]
Definitely a bug! I don't know if I have time to try and fix right now but for my future self, here is a minimal reproduction of the issue:

```css
/* Input */
.test-1:hover, .test-1:active {
  @apply float-left;
}
.another-class-1 {
  @apply test-1;
}

/* Output */
.test-1:hover, .test-1:active {
  float: left
}
.another-class-1:hover, .another-class-1:active {
  float: left
}
.test-1:hover, .test-1:active {
  float: left
}
```

For some reason the `test-1` classes are duplicated and inserted at the end, which is what is causing the unexpected specificity issues. The correct output should be:

```css
/* Desired output */
.test-1:hover, .test-1:active {
  float: left
}
.another-class-1:hover, .another-class-1:active {
  float: left
}
```
