### ISSUE TITLE
Bug with @font-face

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindcss#3329]
### Describe the problem:

In my file CSS, i have :

```css
@font-face {
    font-family: 'Inter var';
    font-weight: 100 900;
    font-display: swap;
    font-style: normal;
    font-named-instance: 'Regular';
    src: url('../fonts/Inter-roman.latin.var.woff2') format('woff2');
}

@font-face {
    font-family: 'Inter var';
    font-weight: 100 900;
    font-display: swap;
    font-style: italic;
    font-named-instance: 'Italic';
    src: url('../fonts/Inter-italic.latin.var.woff2') format('woff2');
}
```

My postcss.config.js is :
```js
module.exports = {
    plugins: {
        'postcss-import': {},
        'tailwindcss': {},
        'autoprefixer': {}
    }
}
```

My generated CSS is : 
```css
@font-face {
  font-family: 'Inter var';

  font-weight: 100 900;

  font-display: swap;

  font-style: normal;

  font-named-instance: 'Regular';

  src: url(/build/fonts/Inter-roman.latin.var.aaa17e8f.woff2) format('woff2');
}

@font-face {
  font-family: 'Inter var';

  font-weight: 100 900;

  font-display: swap;

  font-style: italic;

  font-named-instance: 'Italic';

  src: url(/build/fonts/Inter-italic.latin.var.b2bf31d1.woff2) format('woff2');
}
```

If postcss.config.js is :
```js
module.exports = {
    plugins: {
        'postcss-import': {},
        'autoprefixer': {}
    }
}
```

Generated CSS is:
```css
@font-face {
    font-family: 'Inter var';
    font-weight: 100 900;
    font-display: swap;
    font-style: normal;
    font-named-instance: 'Regular';
    src: url(/build/fonts/Inter-roman.latin.var.aaa17e8f.woff2) format('woff2');
}

@font-face {
    font-family: 'Inter var';
    font-weight: 100 900;
    font-display: swap;
    font-style: italic;
    font-named-instance: 'Italic';
    src: url(/build/fonts/Inter-italic.latin.var.b2bf31d1.woff2) format('woff2');
}
```

I think there is a problem when using @font-face.
