### ISSUE TITLE
`@apply` does not work with multiple css definitions of the same selector

### ISSUE THREAD

**Issue by RobinMalfait** [tailwindlabs/tailwindcss#3360]
### Describe the problem:

When you use `@apply`, and the rules contain multiple definitions for the same classes/key. For example:

```css
.aspect-w-1 {
  position: relative;
}

.aspect-w-1 {
  --tw-aspect-w: 1;
}
```

Then only the contents of the last one is applied. I am assuming that this is because our lookup table has the key of `aspect-w-1` and it just overrides it with the new data.

This behaviour results in issues where you can't `@apply` aspect ratio related classes: https://github.com/tailwindlabs/tailwindcss-aspect-ratio/issues/2

### Link to a minimal reproduction:

I'll open a PR with a broken test soon, and will update this PR!

**Comment by RobinMalfait** [comment]
When I manually add the aspect-ratio plugin styles in a test, I do get the expected behavior:

<details>

<summary>Input:</summary>

```css
    .aspect-w-16 {
      position: relative;
      padding-bottom: calc(var(--tw-aspect-h) / var(--tw-aspect-w) * 100%);
    }

    .aspect-w-16 > * {
      position: absolute;
      height: 100%;
      width: 100%;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
    }

    .aspect-w-16 {
      --tw-aspect-w: 16;
    }

    .aspect-h-9 {
      --tw-aspect-h: 9;
    }

    .sixteen-by-nine {
      @apply aspect-w-16 aspect-h-9;
    }
```

</details>

<details>

<summary>Output:</summary>

```css
    .aspect-w-16 {
      position: relative;
      padding-bottom: calc(var(--tw-aspect-h) / var(--tw-aspect-w) * 100%);
    }

    .aspect-w-16 > * {
      position: absolute;
      height: 100%;
      width: 100%;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
    }

    .aspect-w-16 {
      --tw-aspect-w: 16;
    }

    .aspect-h-9 {
      --tw-aspect-h: 9;
    }

    .sixteen-by-nine {
      position: relative;
      padding-bottom: calc(var(--tw-aspect-h) / var(--tw-aspect-w) * 100%);
    }

    .sixteen-by-nine > * {
      position: absolute;
      height: 100%;
      width: 100%;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
    }

    .sixteen-by-nine {
      --tw-aspect-w: 16;
      --tw-aspect-h: 9;
    }
```

</details>


---

However, when I reproduce it using the actual plugin (you can also see that behaviour in the playground: https://play.tailwindcss.com/LMtlgPrsqU) it results in the following:

<details>

<summary>Input:</summary>

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.sixteen-by-nine {
  @apply aspect-w-16 aspect-h-9;
}
```

</details>

<details>

<summary>Output:</summary>

```css
.sixteen-by-nine {
  --tw-aspect-w: 16;
  --tw-aspect-h: 9;
}
```

This is the only result in the whole output.css file for `sixteen-by-nine`.
Purging is not configured, so it is not related to that either.

</details>
