### ISSUE TITLE
.dark class ends up in the middle of selector instead of start

### ISSUE THREAD

**Issue by philippbosch** [tailwindlabs/tailwindcss#3417]
### Describe the problem:

I have Tailwind set up to use dark mode using the `.dark` class on the `html` element. This works except for this one issue. 

```css
.my-component {
    p {
        @apply text-white dark:bg-black;
    }
}
```

I use [postcss-nested](https://github.com/postcss/postcss-nested) and the **expected result** is this:

```css
.my-component p {
    --tw-text-opacity: 1;
    color: rgba(255, 255, 255, var(--tw-text-opacity))
  }
  .dark .my-component p {
    --tw-bg-opacity: 1;
    background-color: rgba(0, 0, 0, var(--tw-bg-opacity))
  }
```

But the **actual result** is this:

```css
.my-component p {
    --tw-text-opacity: 1;
    color: rgba(255, 255, 255, var(--tw-text-opacity))
  }
  .my-component .dark p {
    --tw-bg-opacity: 1;
    background-color: rgba(0, 0, 0, var(--tw-bg-opacity))
  }
```

The difference is the position of the `.dark` bit in the second selector.

I'm aware that the nesting of `.my-component` and `p` is maybe not best practice but this here is a special case.

Not sure tbh if this is an issue with Tailwind CSS, PostCSS or me doing something wrong. 

### Link to a minimal reproduction:

The repro repo is here: https://github.com/philippbosch/tailwind-dark-issue, and then `npm run build`
