### ISSUE TITLE
Custom utilities added with `@layer utilities` should respect `important` option, like `addUtilities()` does by default

### ISSUE THREAD

**Issue by benface** [tailwindlabs/tailwindcss#3496]
### Describe the problem:

In my projects, I always set the `important` option to a selector like `#app`. I depend on that for ensuring that utilities *always* override declarations from component rules, like in this example:

```css
@layer components {

  .btn {
    /* default button styles */
  }
  
  .btn-group--dark .btn {
    @apply bg-primary-dark text-white;
  }

}
```

```html
<div class="btn-group btn-group--dark">
  <button type="button" class="btn"> This button is dark </button>
  <button type="button" class="btn"> This one too </button>
  <button type="button" class="btn bg-primary-light text-black"> But this one is light </button>
</div>
```

The `bg-primary-light text-black` classes on the 3rd button wouldn't have any effect without `important`, because the `.btn-group--dark .btn` selector has higher specificity than `.bg-primary-light` or `.text-black`.

This works well with core utilities and those added by plugins, but a feature of Tailwind that I really appreciate is the ability to write custom utility classes directly in the CSS, and have it work the same way it does for utilities defined in JS, thanks to the `@layer utilities`, `@responsive`, and `@variants` at-rules.

Well... almost the same way. It turns out that utilities created this way do not honor the `important` option (or the `prefix` option for that matter, which I feel it should as well for consistency, but it's less of an issue). It's an issue for use cases like the following:

```css
@layer utilities {
  @responsive {

    .text-shadow-black {
      text-shadow: black 0px 1px 1px;
    }

    .text-shadow-white {
      text-shadow: white 0px 1px 1px;
    }

  }
}

@layer components {
  .rich-text h1 {
    @apply font-bold text-4xl text-white text-shadow-black;
  }
}
```

```html
<div class="rich-text">
  <h1 class="text-black text-shadow-white">Hello World</h1>
</div>
```

Of the two utility classes applied to the `<h1>` element directly in the HTML, `text-black` will override the `text-white` set in `.rich-text h1` because the selector Tailwind generates for it is `#app .text-black`, but  `text-shadow-white` won't override the `text-shadow-black`, because its generated selector is simply as it is written in `@layer utilities` (`.text-shadow-white`, which is less specific than `.rich-text h1`).

Now you might think "no big deal, I'll just add the `#app` prefix myself in the custom CSS", like this:

```css
@layer utilities {
  @responsive {

    #app .text-shadow-black {
      text-shadow: black 0px 1px 1px;
    }

    #app .text-shadow-white {
      text-shadow: white 0px 1px 1px;
    }

  }
}

@layer components {
  .rich-text h1 {
    @apply font-bold text-4xl text-white text-shadow-black;
  }
}
```

But this has the *really weird* effect of generating a `#app .rich-text h1` selector for the component, instead of just `.rich-text h1`. So it doesn't fix the problem, because the specificity of `#app .rich-text h1` is higher than that of `#app .text-shadow-white` (and even if it did fix the problem, it's obviously not expected behavior).

I feel like a sensible solution would be to make `@layer utilities` work like the plugin API's `addUtilities()` function, in the sense that the `important` and `prefix` options would be respected by default (and maybe there could eventually be a way to opt out of that). I know, it's much easier said than done, and it's a breaking change, but here we are.

### Link to a minimal reproduction:

https://play.tailwindcss.com/SW0B5Hnlcf

**Comment by debrice** [comment]
I cannot judge if what you are describing is a bug or working as intended but I may be able to make a recommendation. By making sure you never reference (`@apply`) a composite class name (`#app .class-name`) it should prevent the issue: 

```css
@layer utilities {
  @responsive {
    .-text-shadow-black {
      text-shadow: black 0px 1px 1px;
    }

    #app .text-shadow-black {
      @apply -text-shadow-black;
    }

    #app .text-shadow-white {
      text-shadow: white 0px 1px 1px;
    }
  }
}

@layer components {
  .rich-text h1 {
    @apply font-bold text-4xl text-white -text-shadow-black;
  }
}

@tailwind base;
@tailwind components;
@tailwind utilities;
```
