### ISSUE TITLE
Some styles from preflight.css and modern-normalize overlap which resolves into useless CSS output even after PurgeCSS

### ISSUE THREAD

**Issue by ymatuhin** [tailwindlabs/tailwindcss#3635]
### Describe the problem:

I run default configuration with purge, after build I see this CSS (some lines were removed, they are not important for this topic)

```css
/*! tailwindcss v2.0.3 | MIT License | https://tailwindcss.com */
/*! modern-normalize v1.0.0 | MIT License | https://github.com/sindresorhus/modern-normalize */
*, ::after, ::before {
    box-sizing:border-box
}

html {
    line-height: 1.15;
    -webkit-text-size-adjust:100%
}

body {
    margin:0
}

body {
    font-family: system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'
}

html {
    font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    line-height:1.5
}

body {
    font-family: inherit;
    line-height:inherit
}

*, ::after, ::before {
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color:#e5e7eb
}
```

So I see double `box-sizing:border-box`, html `line-height`, `font-family` 3 times. It happened because of different approaches in modern-normalize.css and preflight.css. These duplicates can be removed.

Purge configuration:
```js
  purge: {
    preserveHtmlElements: false,
    options: {  keyframes: true, variables: true  },
  }
```
