### ISSUE TITLE
[Feature Proposal] Add new "ellipsis" utility

### ISSUE THREAD

**Issue by benface** [tailwindlabs/tailwindcss#377]
I know there is a `truncate` utility:

```css
.truncate {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

But I suggest adding an `ellipsis` utility that doesn't truncate unless absolutely necessary (when the text cannot wrap anymore):

```css
.ellipsis {
    overflow: hidden;
    text-overflow: ellipsis;
}
```
