### ISSUE TITLE
Unwanted classes generated when using tailwind classes in selector

### ISSUE THREAD

**Issue by shaffe-fr** [tailwindlabs/tailwindcss#3796]
Hi,

In a CSS file, when a tailwind class is used in both selector and `@apply`, unwanted class combinations are generated.

```css
.foo {
    @apply underline;
}

.bar {
    @apply underline;
}

.baz.underline {
    @apply font-bold;
}
```

Expected output:
```css
.foo {
  text-decoration: underline;
}

.bar {
  text-decoration: underline;
}

.baz.underline {
  font-weight: 700;
}
```

Actual output:

```css
.foo {
  text-decoration: underline;
}

.baz.foo {
  font-weight: 700;
}

.bar {
  text-decoration: underline;
}

.baz.bar {
  font-weight: 700;
}

.baz.underline {
  font-weight: 700;
}
```

I'm using Tailwind 2.0.4, without any plugin.
I tried to make a simple example, so it doesn't make much sense.

Thanks!
