### ISSUE TITLE
Transition (transition-colors) doesn't apply to placeholder

### ISSUE THREAD

**Issue by parsch** [tailwindlabs/tailwindcss#3813]
### What version of Tailwind CSS are you using?

2.0.2

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

Firefox

### What operating system are you using?

macOs

### Reproduction repository

https://play.tailwindcss.com/W56dCrvQI7

As illustrated in https://play.tailwindcss.com/W56dCrvQI7 a `transition-colors` on an `input` doesn't affect the `placeholder`. Would be nice if color transitions included placeholders as well.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I'm afraid that this won't be as easy without bloating the css a lot. This is because you can transition `translate-property`'s which is currently implemented for the `transition-colors` as follows:
```css
.transition-colors {
  transition-property: background-color, border-color, color, fill, stroke;
}
```

However, a placeholder is not a property, but a pseudo element, implemented as:
```css
.placeholder-indigo-400::placeholder {
  --tw-placeholder-opacity: 1;
  color: rgba(129, 140, 248, var(--tw-placeholder-opacity));
}
```

In this case we would have to generate additional rules for each pseudo element which may be okay now that `jit` mode is available. but it will still be a lot. However, I'm not sure if we will enable this by default. One thing you can do for now is to add this to your css:

```css
::placeholder {
  @apply transition-colors;
}
```
