### ISSUE TITLE
Alpha-less colors 

### ISSUE THREAD

**Issue by ayrton** [tailwindlabs/tailwindcss#3963]
### What version of @tailwindcss/jit are you using?

0.1.18

### What version of Node.js are you using?

14.x

### What build tool (or framework if it abstracts the build tool) are you using?

postcss@^8.2.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

N/A

When certain core plugins have been disabled (eg. `backgroundOpacity`) `tailwind-jit` does not output alpha-less colors like `tailwind` does. 

Is this is an intended breaking change or missing functionality? Happy to contribute if there is interest in supporting this use case.

__Implementation difference:__
[`tailwind-jit`](https://github.com/tailwindlabs/tailwindcss-jit/blob/main/src/corePlugins/backgroundColor.js#L18-L23) vs. [`tailwind`](https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/backgroundColor.js#L11-L21)

## Example 

With the following config:

```js
module.exports = {
  corePlugins: {
    backgroundOpacity: false,
  },
}
```

__Outcome:__

```css
.bg-gray-100{
	--tw-bg-opacity: 1;
	background-color: rgba(243, 244, 246, var(--tw-bg-opacity));
}
```

__Expected outcome:__

```css
.bg-gray-100{
	background-color: #F3F4F6;
}
```
