### ISSUE TITLE
Multiple Rules Got Merged into One

### ISSUE THREAD

**Issue by binotaliu** [tailwindlabs/tailwindcss#3964]
### What version of @tailwindcss/jit are you using?

v0.1.18

### What version of Node.js are you using?

v14.16.0

### What build tool (or framework if it abstracts the build tool) are you using?

laravel-mix v6.0.13

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/binotaliu/tailwindcss-test

given following source ([test.css](https://github.com/binotaliu/tailwindcss-test/blob/4cc053827dfafb08e4e1809e5691d44262f30518/test.css)) :

```css
.content {
  ul:not(:first-of-type),
  .content-list ul {
    @apply list-none m-0 mb-[2.5em] p-0;
    li {
      @apply relative block pl-5 mb-4 text-[.89em] text-gray-700 leading-[1.714em];
      a {
        @apply no-underline;
      }
      code {
        @apply text-[.875em];
      }
    }
  }
}
```

with `NODE_ENV=production`, the compiled result is ([dist.css](https://github.com/binotaliu/tailwindcss-test/blob/4cc053827dfafb08e4e1809e5691d44262f30518/dist.css)):
```css
.content .content-list ul,
.content ul:not(:first-of-type) {
  margin: 0 0 1rem;
  list-style-type: none;
  padding: 0;
  padding: 0 0 0 1.25rem;
  display: block;
  font-size: 0.89em;
  line-height: 1.714em;
  --tw-text-opacity: 1;
  color: rgba(55, 65, 81, var(--tw-text-opacity));
  text-decoration: none;
  font-size: 0.875em
}
```

----

I tried to not use `postcss-nested`, so use following source ([test-without-nested.css](https://github.com/binotaliu/tailwindcss-test/blob/4cc053827dfafb08e4e1809e5691d44262f30518/test-without-nested.css)):
```css
@tailwind components;
@tailwind utilities;
@layer components {
  .content .content-list ul,
  .content ul:not(:first-of-type) {
    @apply list-none m-0 mb-[2.5em] p-0;
  }
  
.content .content-list ul li,
  .content ul:not(:first-of-type) li {
    @apply relative block pl-5 mb-4 text-[.89em] text-gray-700 leading-[1.714em];
  }
  
.content .content-list ul li a,
  .content ul:not(:first-of-type) li a {
    @apply no-underline}
  
.content .content-list ul li code,
  .content ul:not(:first-of-type) li code {
    @apply text-[.875em]}
}
```

this looks fine, and I can compile it with `@tailwindcss/jit` and get a expected result ([dist-without-nested.css](https://github.com/binotaliu/tailwindcss-test/blob/4cc053827dfafb08e4e1809e5691d44262f30518/dist-without-nested.css)) :
```css
.content .content-list ul,
.content ul:not(:first-of-type) {
  margin: 0 0 2.5em;
  list-style-type: none;
  padding: 0
}

.content .content-list ul li,
.content ul:not(:first-of-type) li {
  position: relative;
  margin-bottom: 1rem;
  display: block;
  padding-left: 1.25rem;
  font-size: 0.89em;
  line-height: 1.714em;
  --tw-text-opacity: 1;
  color: rgba(55, 65, 81, var(--tw-text-opacity))
}

.content .content-list ul li a,
.content ul:not(:first-of-type) li a {
  text-decoration: none
}

.content .content-list ul li code,
.content ul:not(:first-of-type) li code {
  font-size: 0.875em
}
```

----

Looks like it is a bug that only happen when using in combination with nested rules and `,` selector.

**Comment by therealgilles** [comment]
I'm having the same issue.

**Comment by therealgilles** [comment]
From my analysis, the problem lies with Tailwindcss, not with postcss-nested.

**Comment by therealgilles** [comment]
Here is my css:

```CSS
	.dataTables_wrapper .dataTables_filter label,
	.dataTables_length label {
		@apply text-base;
		line-height: 40px;

		input[type='search'] {
			@apply bg-white;
		}
	}
```

If I disable Tailwindcss, I get this, which looks correct:

```CSS
.analytics .dataTables_length label,.analytics .dataTables_wrapper .dataTables_filter label{@apply text-base;line-height:40px;}
.analytics .dataTables_length label input[type=search],.analytics .dataTables_wrapper .dataTables_filter label input[type=search]{@apply bg-white}
```

When I enable Tailwindcss, I get this, which is incorrect:

```CSS
.analytics .dataTables_length label,.analytics .dataTables_wrapper .dataTables_filter label{font-size:16px;line-height:24px;line-height:40px;--tw-bg-opacity:1;background-color:rgba(255,255,255,var(--tw-bg-opacity))}
```

The input[type=search] white background property got merged with the label parent properties.
