### ISSUE TITLE
How to write some unusual styles

### ISSUE THREAD

**Issue by awnawnawn** [tailwindlabs/tailwindcss#3973]
### What version of @tailwindcss/jit are you using?

0.1.18

### What version of Node.js are you using?

14.16.0

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/awnawnawn/awnawnawn.github.io

I want to give it to `div` style to `transform-style: preserve-3d` and `transition-delay: 0ms`
```html
<div class="mt-[123px] transform-style-[preserve-3d] delay-[0] mb-[321px]"></div>
```
After compilation
```css
.mt-\[123px\] {
	margin-top: 123px;
}
.mb-\[321px\] {
	margin-bottom: 321px;
}
```
How should I write it ?
