### ISSUE TITLE
Better explaining of safelist.txt?

### ISSUE THREAD

**Issue by rayventerprise** [tailwindlabs/tailwindcss#4029]
### What version of Tailwind CSS are you using?

2.1

### What version of Node.js are you using?

14

### What browser are you using?

NA

### What operating system are you using?

Linux

### Reproduction repository

https://youtube.com

### Describe your issue

"Advanced PurgeCSS options like safelist aren't supported yet since we aren't actually using PurgeCSS. We'll add a way to safelist classes for sure though. For now, a safelist.txt file somewhere in your project with all the classes you want to safelist will work fine."

Can we have more clarification on how to make this work? do I put a space between the classes? does it support regex? are you sure its anywhere in the project? I placed it in my project and it doesnt appear to be safe listing the css classes i provided

currently i have ONLY 'col-span-6' in my safelist.txt as a test and it is still being purged.

Thanks.

**Comment by adamwathan** [comment]
Hey! Yeah I will update the docs to explain this better but essentially you just make any file you want that lists all the classes you want to keep and make sure that file is included in your `purge` config:

```txt
// banana-sandwich.txt
col-span-6
bg-red-300
font-bold
...
```

```js
// tailwind.config.js
module.exports = {
  mode: 'jit',
  purge: [
    './banana-sandwich.txt',
    // Your actual template paths...
  ]
}
```

It's not like an actual feature or anything special, it's literally just the idea of using an arbitrary file with class names in it as a conceptual safelist to ensure those classes are generated, since Tailwind has no idea if that file is actually part of your apps UI or not.

**Comment by therealgilles** [comment]
Does this mean that safelist.txt does not support regular expressions?

**Comment by adamwathan** [comment]
Correct, there is no way to easily support regular expression safelisting in JIT mode at the moment, just because of the on-demand nature of things. It might be something we can come up with a clever solution for at some point but in the mean time you will have to list each class explicitly. I would consider writing a short script to generate your safelist if it's a really cumbersome list.

**Comment by therealgilles** [comment]
@adamwathan: Thank you for clarifying. I think it would be great to add a comment on TailwindCSS website so that new JIT mode users are aware of the non-support for regular expressions.

I think my safelist has grown over time because of issues I encountered with the production build and did not have time or the knowledge to root cause. JIT mode seems to be working well in development. Somehow in production mode, classes get merged and I end up with incorrect css, so I'm disabling JIT for my production build. I don't have a testcase unfortunately.

Here is the relevant CSS extract:

```CSS
/* Styles for generic pages */
body.bbwp-generic-styles,
body .bbwp-generic-styles {
	.article-content {
		@apply mt-8;

		p:not(:last-child),
		ul:not(:last-child) {
			@apply mb-4;
		}

		p {
			@apply text-body font-body text-charcoal;

			&.small {
				@apply text-sm;
				line-height: inherit;
			}
		}

		p + ul {
			@apply -mt-2;
		}

		ul {
			@apply ml-4 list-disc list-outside text-body font-body text-charcoal;
		}

		a {
			@apply relative text-orange;

			&:after {
				@apply absolute bottom-0 block w-0 h-px left-1/2 bg-orange;
				content: '';
				transition: width 0.3s ease 0s, left 0.3s ease 0s;
			}

			&:hover:after {
				@apply left-0 w-full;
			}
		}

		.article-h1 {
			@apply mb-8 text-center;
		}
	}
}
```

Here is what I get in the production build output:

```CSS
body.bbwp-generic-styles .article-content, body .bbwp-generic-styles .article-content {
    margin-top: 2rem;
    margin-bottom: 1rem;
    font-family: APRegular;
    font-size: 18px;
    line-height: 30px;
    --tw-text-opacity: 1;
    color: #3a373e;
    color: rgba(58,55,62,var(--tw-text-opacity));
    font-size: 14px;
    line-height: 21px;
    line-height: inherit;
    margin-top: -.5rem;
    margin-left: 1rem;
    list-style-position: outside;
    list-style-type: disc;
    font-family: APRegular;
    font-size: 18px;
    line-height: 30px;
    --tw-text-opacity: 1;
    color: #3a373e;
    color: rgba(58,55,62,var(--tw-text-opacity));
    position: relative;
    --tw-text-opacity: 1;
    color: #ff9961;
    color: rgba(255,153,97,var(--tw-text-opacity));
    position: absolute;
    bottom: 0;
    left: 50%;
    display: block;
    height: 1px;
    width: 0;
    --tw-bg-opacity: 1;
    background-color: rgba(255,153,97,var(--tw-bg-opacity));
    content: "";
    transition: width .3s ease 0s,left .3s ease 0s;
    left: 0;
    width: 100%;
    margin-bottom: 2rem;
    text-align: center;
}
```

It's as if a number of classes got merged together.

Here are the postcss plugins I use: postcss-import, postcss-nested-ancestors, postcss-nested, postcss-preset-env. And as I said, I don't have this kind of issue without JIT mode enabled.

Let me know if you have any advice on how to debug this.
