### ISSUE TITLE
[JIT] Disabling opacity core plugins doesn't change output of color plugins

### ISSUE THREAD

**Issue by cossssmin** [tailwindlabs/tailwindcss#4071]
### What version of Tailwind CSS are you using?

v2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

Maizzle v3.3.0

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/maizzle/maizzle

### Describe your issue

When enabling JIT, you cannot disable core plugins:

```js
module.exports = {
  mode: 'jit',
  purge: [
    'src/**/*.*',
  ],
  corePlugins: {
    textOpacity: false,
  },
}
```

```html
<div class="text-red-400">example</div>
```

Result:

```css
.text-red-400 {
  --tw-text-opacity: 1;
  color: rgba(248, 113, 113, var(--tw-text-opacity));
}
```

Expected:

```css
.text-red-400 {
  color: #f87171;
}
```

Note I've only tested with the opacity plugins.
