### ISSUE TITLE
[JIT] group variants like group-hover not working  with tailwindcss-theme-variants plugin

### ISSUE THREAD

**Issue by Kuirak** [tailwindlabs/tailwindcss#4111]
### What version of Tailwind CSS are you using?

v2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What version of Node.js are you using?

v12.19.0

### What browser are you using?

Chrome

### What operating system are you using?

WSL

### Reproduction repository

https://github.com/Kuirak/jit-tailwindcss-theme-variants/

### Describe your issue

Hello, 

group variants like `group-hover` or `group-focus`  are generating wrong css with [tailwindcss-theme-variants](https://github.com/JakeNavith/tailwindcss-theme-variants) plugin. 
I don't know if it is a bug in tailwindcss-theme-variants repo or  in tailwindcss JIT so I will [cross post it](https://github.com/JakeNavith/tailwindcss-theme-variants/issues/14)

Here is a reproduction repo:
https://github.com/Kuirak/jit-tailwindcss-theme-variants/

Expected Output:
```css
:root.dark-theme .dark\:group:hover .dark\:group-hover\:bg-amber-300 {
	--tw-bg-opacity: 1;
	background-color: rgba(252, 211, 77, var(--tw-bg-opacity));
}
```

Output 
```css
:root.dark-theme .dark\:group:hover .group-hover\:bg-teal-300 {
	--tw-bg-opacity: 1;
	background-color: rgba(94, 234, 212, var(--tw-bg-opacity));
}

:root.dark-theme .dark\:group:hover .group-hover\:bg-amber-300 {
	--tw-bg-opacity: 1;
	background-color: rgba(252, 211, 77, var(--tw-bg-opacity));
}
```
