### ISSUE TITLE
[Bug]: Strange / unexpected behavior with custom component, @apply, and :not()

### ISSUE THREAD

**Issue by joemsak** [tailwindlabs/tailwindcss#4264]
### What version of Tailwind CSS are you using?

package.json:
npm:@tailwindcss/postcss7-compat

Gemfile:
tailwindcss-rails v0.3.3

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 4 via rails webpacker / webpack-dev-server

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/joemsak/the-guidebook

### Describe your issue

Hey there. I'm fairly new to developing in Tailwind so please forgive me if I'm missing something. I'm finding it difficult to search for a meaningful solution or anyone else experiencing this.

I have a custom component like so:

```scss
@layer components {
  .btn {
    @apply inline-block;
    @apply rounded-sm;
    @apply shadow-sm;
    @apply bg-blue-400;

    @apply py-1;
    @apply px-4;

    @apply text-sm;
    @apply text-white #{!important}; // I had to add this as my workaround for now
    @apply font-bold;

    @apply cursor-pointer;

    @apply hover:bg-blue-900;

    @apply active:translate-x-1;
    @apply active:translate-y-1;

    @apply transform;
    @apply transition-colors;
    @apply duration-300;
  }
}
```
and then I have this in my base layer:

```scss
@layer base {
  a:not(.btn) {
    @apply text-blue-400;
    @apply hover:text-blue-900;
    @apply transition-colors;
    @apply duration-300;
    @apply cursor-pointer;
  }

  button,
  input[type=submit] {
    @apply btn;
  }
}
```
This is resulting in the following computed CSS in my browser:

```css
a:not(button), a:not(input[type="submit"]) {
  transition-property: background-color, border-color, color, fill, stroke;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 150ms;
  transition-duration: 300ms;
  cursor: pointer;
}
```
So as you can see, it's taking the selectors that use `@apply btn` and filling that in for the `:not()` selector when what I want is literally the class `.btn` to be there.

Any help or advice appreciated, thanks so much for your time.

**Comment by adamwathan** [comment]
Hey! This is the expected behavior, `@apply` is designed to make extracting components work the exact same way as if the classes were present on the element, so take this example:

```html
<input type="submit" class="btn">
```

In that case the `a:not(.btn)` rule would apply to that element right? So if you want that element to behave exactly like it had `btn` present on it when you extract the styles with `@apply`, we need to copy _all_ of the styles using `.btn` and make them apply to the new selector.

If we didn't do that, then the behavior would be different when using the `btn` class directly vs. applying the `btn` class, and the goal is for the behavior to be the same.

I see why it looks silly in your case because of course `a:not(button)` is a bit odd, all `a` tags are not `button` tags, but it's important that _all_ of the styles are applied for it to actually behave the same.

Here's an example from our test suite:

```css
test('applying a class applies all instances of that class, even complex selectors', () => {
  const input = `
    h1 > p:hover .banana:first-child * {
      @apply bar;
    }
    .bar {
      color: blue;
    }
    @media (print) {
      @supports (display: grid) {
        .baz .bar:hover {
          text-align: right;
          float: left;
        }
      }
    }
    `
  const expected = `
    h1 > p:hover .banana:first-child * {
      color: blue;
    }
    @media (print) {
      @supports (display: grid) {
        .baz h1 > p:hover .banana:first-child *:hover {
          text-align: right;
          float: left;
        }
      }
    }
    .bar {
      color: blue;
    }
    @media (print) {
      @supports (display: grid) {
        .baz .bar:hover {
          text-align: right;
          float: left;
        }
      }
    }
  `

  expect.assertions(2)

  return run(input).then((result) => {
    expect(result.css).toMatchCss(expected)
    expect(result.warnings().length).toBe(0)
  })
})
```

**Comment by joemsak** [comment]
@adamwathan Thank you very much for your explanation. But perhaps I wasn't clear enough about my problem then. 

I am trying to style all anchor tags which do not have the class 'btn' to have a blue color. 

All elements that do have btn class should have the same blue as background with white color. 

The outcome in my case is that my anchor tag with class btn is getting the blue color on top of the blue background. 

Is there a way in tailwind to preserve the original css behavior of defining styles on all anchor tags that do not have the class btn, while using the class btn as a component which is @apply'd in the way I have done above?

**Comment by joemsak** [comment]
**UPDATE**

I am now noticing that what I expect is happening in production, but not development. This shows up in my production css, but not during development locally:

```css
a:not(.btn) {
 transition-property:background-color,border-color,color,fill,stroke;
 transition-timing-function:cubic-bezier(.4,0,.2,1);
 transition-duration:.15s;
 transition-duration:.3s;
 cursor:pointer
}
```
Kinda feel like my issue has been misunderstood closed a bit hastily
