### ISSUE TITLE
[Bug]: Responsive wariant of break-word

### ISSUE THREAD

**Issue by Triloworld** [tailwindlabs/tailwindcss#4340]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Nuxt

### What version of Node.js are you using?

v16.0.0

### What browser are you using?

Chrome v90.0.4430.93 (Official version) (x86_64)

### What operating system are you using?

macOS

### Reproduction repository

Propably no need / will be added in future

### Describe your issue

Hello,
Found that this proper version:

```css
break-word: break-all
```

In mobile show us this one that isn't overriding property:

```css
@media (min-width: 320px)
.xs\:break-words {
    overflow-wrap: break-word;
}

```

Proper one what work as overriding method:
```css
word-break: break-word;
```

I don't mind if mobile version is little different as long as it work, right now it isn't and text break in all places.
This property fix mobile when email/text is too long and need to be cut in some place

**Comment by Triloworld** [comment]
I mean this one line:
https://github.com/tailwindlabs/tailwindcss/blob/b442c912e2d052ad026fd2e3d31bc450f620a784/src/plugins/wordBreak.js#L10

**Comment by Triloworld** [comment]
Ah yes, there is 'deprecated' info. But nonetheless it don't work. 
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

My fix to be updated:
```css
@media (min-width: 320px){
  .xs\:break-words {
    overflow-wrap: break-word;
    word-break: normal;
  }
}
```
