### ISSUE TITLE
[Bug]: Output order of responsive appended to final file instead of imports

### ISSUE THREAD

**Issue by RedKenrok** [tailwindlabs/tailwindcss#4443]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

PostCSS

### What version of Node.js are you using?

16.1.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/RedKenrok/tailwind-issue-output-order

### Describe your issue

The output of tailwindcss does not follow the order the imports are written.

If my imports look like the following:

```CSS
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@import './custom.css';

.custom-class {
  background-color: turquoise;
}
```

I expect all of tailwind's classes to appear above my custom CSS. However the responsive variants are placed below my custom style sheet as well as any css in the file after the tailwind imports.

```CSS
.hidden {
  display: none;
}

@media (min-width: 768px) {
  .sm\:hidden {
    display: none;
  }
}

.imported-custom-class {
  background-color: turquoise;
}

.custom-class {
  background-color: turquoise;
}
```

The actual results:

```CSS

.hidden {
  display: none;
}

.imported-custom-class {
  background-color: turquoise;
}

.custom-class {
  background-color: turquoise;
}

@media (min-width: 768px) {
  .sm\:hidden {
    display: none;
  }
}
```
