### ISSUE TITLE
JIT adding new lines

### ISSUE THREAD

**Issue by rightaway** [tailwindlabs/tailwindcss#4468]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

webpack

### What version of Node.js are you using?

14.16

### What browser are you using?

all

### What operating system are you using?

linux

### Reproduction repository

https://github.com/rightaway/demo

### Describe your issue

In tailwind jit it takes several `@apply` statements and puts them onto a single line. It should preserve the newlines of the original file just like tailwind always has done so that formatting the file doesn't have to become necessary in tailwind jit which it never was before.

```css
.class {
  @apply block; /* comment */
  @apply h-full; /* comment */
  @apply w-full; /* comment */
}

/* tailwind */
.class {
  display: block; /* comment */
  height: 100%; /* comment */
  width: 100% /* comment */
}

/* tailwind jit */
.class {
  display: block; /* comment */ height: 100%; /* comment */ width: 100% /* comment */
}
```

**Comment by rightaway** [comment]
Also a problem with tailwind jit when a class contains some `@apply` and some not. It's splitting it into 2 selectors when it used to be just 1 without jit.

```css
.class {
  @apply block;
  width: 100%;
  height: 100%;
}

/* tailwind */
.class {
  display: block;
  width: 100%;
  height: 100%;
}

/* tailwind jit */
.class {
  display: block;
}
.class {
  width: 100%;
  height: 100%;
}
```

**Comment by rightaway** [comment]
Here's another strange one. It splits definitions if the class list has newlines in between.

```css
.class1,
.class2,
.class3 {
  @apply w-full;
  display: block;
  @apply h-full;
}

/* tailwind jit */
.class1, .class2, .class3 {
  width: 100%;
}

.class1,
.class2,
.class3 {
  display: block;
}

.class1, .class2, .class3 {
  height: 100%;
}
```

But without newlines it's what it should be.

```css
.class1, .class2, .class3 {
  @apply w-full;
  display: block;
  @apply h-full;
}

/* tailwind jit */
.class1, .class2, .class3 {
  width: 100%;
  display: block;
  height: 100%
}
```
