### ISSUE TITLE
[FEATURE PROPOSAL] utility for animation

### ISSUE THREAD

**Issue by vortechron** [tailwindlabs/tailwindcss#456]
e.g.

```
<div class="delay-1s duration-2s iteration-infinite">

</div>

```

**Comment by ricricucit** [comment]
you might be interested in participating here: https://github.com/tailwindcss/tailwindcss/pull/378

**Comment by royvanv** [comment]
@ricricucit This issue is about animations, not transitions. Although I see some discussion about animations in there too.

I propose animations could be added in the Tailwind config file and be added in the HTML via a class `animation-[name]`. 

**Config:**
```js
// tailwind.config.js
	animations: {
		siren: {
			from: {
				backgroundColor: "red",
			}
			to: {
				backgroundColor: "blue",
			}
		}
	}
```

**Output:**
```css
.animation-siren {
    animation-name: siren;
}

@keyframes siren {
  from {background-color: red;}
  to {background-color: blue;}
}
```

**Usage:** 
```html
<div class="delay-1s duration-2s iteration-infinite animation-siren">
```
