### ISSUE TITLE
Using postcss-preset-env for nesting causes creation of multiple class rules

### ISSUE THREAD

**Issue by rowild** [tailwindlabs/tailwindcss#4634]
### What version of Tailwind CSS are you using?

2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.3.2

### What version of Node.js are you using?

v14.16

### What browser are you using?

Chrome

### What operating system are you using?

macOS 10.15.7

### Reproduction repository

https://github.com/rowild/tailwindcss-postcss-preset-env-test

### Describe your issue

1. Install postcss-preset-env
2. configure it with postcss.config.js
```js
const postcss = require('postcss');
const postcssPresetEnv = require('postcss-preset-env');

module.exports = {
    plugins: {
        tailwindcss: {},
        'postcss-preset-env': {
            stage: 1
        },
        autoprefixer: {},
    }
}
```
3. Add a nested rule:
```css
#waveform {
  @apply relative w-full border bg-green-100 mx-0 mb-5;

  & .grid {
   @apply border-2 border-red-500 p-3;
  }
}
```
4. Run `npm run build`

Result:
```css
#waveform{
  position:relative;
  margin-left:0;
  margin-right:0;
  margin-bottom:1.25rem;
  width:100%;
  border-width:1px;
  --tw-bg-opacity:1;
  background-color:rgba(209,250,229,var(--tw-bg-opacity))
}
#waveform .grid{
  border-width:2px
}
#waveform .grid{
  --tw-border-opacity:1;
  border-color:rgba(239,68,68,var(--tw-border-opacity))
}
#waveform .grid{
  padding:.75rem
}
```

There are 3 `#waveform .grid` rules, which is not optimised css.
