### ISSUE TITLE
`peer-focus:peer-valid:*` generates wrong output

### ISSUE THREAD

**Issue by kripod** [tailwindlabs/tailwindcss#4726]
### What version of Tailwind CSS are you using?

v2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.0

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/kripod/next-starter-strict/blob/main/src/components/inputs/Input.tsx

### Describe your issue

While trying to apply `peer-focus:peer-valid:border-blue-500` to avoid a precedence clash with `peer-invalid:border-red-500`, it turns out that the former generates the following input, which is invalid:

```css
.peer:focus:valid ~  ~ .peer-focus\:peer-valid\:border-blue-500 {
  --tw-border-opacity: 1;
  border-color: rgba(59, 130, 246, var(--tw-border-opacity));
}
```

Tailwind should generate something like below instead, making `peer-*` utilities composable:

```css
.peer:focus:valid ~ .peer-focus\:peer-valid\:border-blue-500 {
  --tw-border-opacity: 1;
  border-color: rgba(59, 130, 246, var(--tw-border-opacity));
}
```
