### ISSUE TITLE
PostCSS imports not working with CLI

### ISSUE THREAD

**Issue by mattwaler** [tailwindlabs/tailwindcss#4747]
### What version of Tailwind CSS are you using?

2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

TailwindCSS CLI

### What version of Node.js are you using?

14.17.0

### What browser are you using?

N/A

### What operating system are you using?

MacOS

### Reproduction repository

https://github.com/mattwaler/tailwindcss-bug

### Describe your issue

The import directive works with tailwind's utilities, but every relative import simply gets copied as is into the built CSS file, like so:

```css
.content-none {
  content: none;
}

@import './test.css';

@media (min-width: 640px) {
  .sm\:container {
    width: 100%;
  }
```
