### ISSUE TITLE
`transform` overrides `translate` vars when using `@apply` on multiple classes

### ISSUE THREAD

**Issue by ajmnz** [tailwindlabs/tailwindcss#4755]
### What version of Tailwind CSS are you using?

2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.0

### What version of Node.js are you using?

v16.1.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/ajmnz/tw-apply-bug

### Describe your issue

`.transform` sets all transform-related vars to its initial value. When using `@apply` on multiple classes that use both `transform` and `translate`, it gets compiled in a way that all transform-related vars stay in its initial value.

Say we're using the following classes to center elements

```css
.center-xy {
  @apply absolute top-2/4 left-2/4 transform -translate-x-1/2 -translate-y-1/2;
}

.center-left {
  @apply absolute top-2/4 left-0 transform -translate-y-1/2;
}

.center-right {
  @apply absolute top-2/4 right-0 -translate-y-1/2;
}

.center-y {
  @apply absolute top-2/4 -translate-y-1/2;
}

.center-x {
  @apply absolute left-2/4 -translate-x-1/2;
}
```

It works while running `next dev`, but the problem comes when it is compiled with `next build`, as the resulting css looks something like this:

```css
.center-xy {
 left: 50%;
 --tw-scale-y: 1;
 --tw-translate-x: -50%;
 --tw-translate-y: -50%
}

.center-left,
.center-xy {
 position: absolute;
 top: 50%;
 --tw-translate-x: 0;
 --tw-translate-y: 0;
 --tw-rotate: 0;
 --tw-skew-x: 0;
 --tw-skew-y: 0;
 --tw-scale-x: 1;
 transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
}
```

Now, we could use the transform class on each element directly instead of on each apply, but it is less convenient.
I don't really know if this is fixable at all, but thought it was worth pointing it out.
