### ISSUE TITLE
`@apply` directive causing problem inside `@keyframes`

### ISSUE THREAD

**Issue by mamunongithub** [tailwindlabs/tailwindcss#4844]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Gatsby v3.6.2 | PostCSS v8.3.5

### What version of Node.js are you using?

14.6.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

N/A

### Describe your issue

```postcss
/* without `@apply` (working) */

.animate-slide-up {
  animation: slide-up 1s;
}

@keyframes slide-up {
  from {
    opacity: 0;
    transform: translateY(-2rem);
  }
  to {
    opacity: 1;
    transform: translateY(0rem);
  }
}

/* with `@apply` (not working properly) */

.animate-apply-slide-up {
  animation: apply-slide-up 1s;
}

@keyframes apply-slide-up {
  from {
    @apply opacity-0 -translate-y-8;
  }
  to {
    @apply opacity-100 translate-y-0;
  }
}
```

https://play.tailwindcss.com/zdDSmhAqJj?file=css

Why  `.animate-apply-slide-up` not working properly?

**Comment by adamwathan** [comment]
Hey! This is not currently supported but ideally we would throw an exception here.

Imagine this:

```css
@keyframes whatever {
  to {
    @apply opacity-0 hover:opacity-100;
  }
}
```

There's no way to generate any sensible output for that unfortunately.

Best bet if you want to reference your theme values in custom keyframes is to use the `theme` function:

```css
.animate-apply-slide-up {
  animation: apply-slide-up 1s;
}

@keyframes apply-slide-up {
  from {
    opacity: 0;
    transform: translateY(theme('translate.-8'));
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
```
