### ISSUE TITLE
Output size comparison 2.0.4 – 2.2.4 – 2.2.4-jit

### ISSUE THREAD

**Issue by RafaelKr** [tailwindlabs/tailwindcss#4979]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

laravel-mix 6.0.25 with postcss 8.3.5

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux Mint

### Reproduction repository

https://github.com/RafaelKr/tailwind-output-size-comparison

### Describe your issue

I updated a project from tailwindcss 2.0.4 to 2.2.4. I noticed a little size increase of the compiled css files. It's not very much, but maybe it gets larger when the project grows.

Interestingly it also differs between 2.2.4 with jit disabled and enabled.
These are the sizes (in byte) of the output files:
```
4298 tailwind-2.0.4.css
4326 tailwind-2.2.4.css
5390 tailwind-2.2.4-jit.css
```

I created a reproduction with an empty `tailwind.css` file. I also created an empty `index.html` and added it to the purge config. The build is always in production mode. It is prettified afterwards for better comparison.

The biggest difference is, that in [tailwind-2.2.4-jit.css](https://github.com/RafaelKr/tailwind-output-size-comparison/blob/3021bb9ed60a354ffb4d488691cc059dd10695f8/dist/tailwind-2.2.4-jit.css) some browser vendor specific rules ([lines 71-112](https://github.com/RafaelKr/tailwind-output-size-comparison/blob/3021bb9ed60a354ffb4d488691cc059dd10695f8/dist/tailwind-2.2.4-jit.css#L71-L112)) and a lot more CSS vars for `*,:after,:before` ([lines 216-254](https://github.com/RafaelKr/tailwind-output-size-comparison/blob/3021bb9ed60a354ffb4d488691cc059dd10695f8/dist/tailwind-2.2.4-jit.css#L216-L254)) are added.

[tailwind-2.0.4.css](https://github.com/RafaelKr/tailwind-output-size-comparison/blob/3021bb9ed60a354ffb4d488691cc059dd10695f8/dist/tailwind-2.0.4.css) and [tailwind-2.2.4.css](https://github.com/RafaelKr/tailwind-output-size-comparison/blob/3021bb9ed60a354ffb4d488691cc059dd10695f8/dist/tailwind-2.2.4.css) are pretty similiar.

To test it yourself run the following:
```sh
git clone https://github.com/RafaelKr/tailwind-output-size-comparison
cd tailwind-output-size-comparison
npm i
npm start
```

If you want to test another version checkout that branch and run it again.
```sh
git checkout 2.0.4 # or 2.2.4 or 2.2.4-jit
npm i
npm start
```

**Comment by adamwathan** [comment]
Hey! JIT produces slightly different CSS in certain situations because of how some features work, all of the CSS variables you are seeing for example come from this change:

https://blog.tailwindcss.com/tailwindcss-2-2#simplified-transform-and-filter-composition

...and the extra reset rules are because the JIT engine doesn't purge the base style layer, so all base styles are currently preserved whereas in non-JIT mode we use PurgeCSS to remove those rules.

No bugs or anything here, all known/deliberate/expected stuff 👍🏻

**Comment by RafaelKr** [comment]
Hey! Thanks for the clarification, it does make a lot of sense now.

I have a little one pager. When prettified it has 1228 lines of CSS in non-JIT mode, 1249 lines with JIT. Nevertheless, my resulting minified CSS is 2.56KB larger with JIT.

You wrote "all base styles are currently preserved", does that mean you're planning to purge this somehow in the future?
Maybe it would make sense to also use PurgeCSS for jit in production mode by default (when no watch is running). Or a similiar way to detect what's used and what's not. I know you already have something in place to only generate styles for the classes which are used.

For example I noticed in the JIT file it produces styles with this long selectors:
```css
.aspect-w-1,.aspect-w-2,.aspect-w-3,.aspect-w-4,.aspect-w-5,.aspect-w-6,.aspect-w-7,.aspect-w-8,.aspect-w-9,.aspect-w-10,.aspect-w-11,.aspect-w-12,.aspect-w-13,.aspect-w-14,.aspect-w-15,.aspect-w-16 {
  padding-bottom: calc(var(--tw-aspect-h)/var(--tw-aspect-w)*100%);
  position: relative;
}

.aspect-w-1>*,.aspect-w-2>*,.aspect-w-3>*,.aspect-w-4>*,.aspect-w-5>*,.aspect-w-6>*,.aspect-w-7>*,.aspect-w-8>*,.aspect-w-9>*,.aspect-w-10>*,.aspect-w-11>*,.aspect-w-12>*,.aspect-w-13>*,.aspect-w-14>*,.aspect-w-15>*,.aspect-w-16>* {
  bottom: 0;
  height: 100%;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  width: 100%;
}
```

whereas in the non-JIT file it produces this:
```css
.aspect-w-1 {
  padding-bottom: calc(var(--tw-aspect-h)/var(--tw-aspect-w)*100%);
  position: relative;
}

.aspect-w-1>* {
  bottom: 0;
  height: 100%;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  width: 100%;
}
```

and there are many small differences like this quickly summing up to 2.56KB for this small page.

But apart from this very little issue, the JIT mode is absolutely brilliant, thanks for that!
