### ISSUE TITLE
Breaking change after upgrade related to border-color

### ISSUE THREAD

**Issue by rainerborene** [tailwindlabs/tailwindcss#5039]
### What version of Tailwind CSS are you using?

v2.2.6

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 5.37.0

### What version of Node.js are you using?

v14.1.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### Describe your issue

This [line](https://github.com/tailwindlabs/tailwindcss/compare/v2.2.4...v2.2.6#diff-9ee8cc681e96609c5b1f7333181e342604ed5465ac7b25c0df91f1bf879f3d31L15) has a huge impact on the default styles and it was removed on the recent version. Most Tailwind examples out there uses something like: 

```html
<div class="text-black">
  <div class="border">
     <!-- Expected: border should not be black -->
  </div>
</div>
```

And it was used by the `hr` tag as well. Please, revert this change if possible. Thank you!

**Comment by adamwathan** [comment]
Which line? Your link goes to this page:

![image](https://user-images.githubusercontent.com/4323180/126626446-2d8156e2-0d4b-40d7-83fd-daadd44fc155.png)

Can you provide a reproduction? I tested the snippet you provided and the border is gray like expected, not black.

![image](https://user-images.githubusercontent.com/4323180/126626741-741fd714-06fe-4a7f-841c-8454b278be27.png)

**Comment by rainerborene** [comment]
@adamwathan I figured out why this is happening. Turns out it is related to some invalid selectors. Say you have a custom style like:

```css
.form-control {
  &[type="file"] {
    @apply bg-white border focus:outline-none focus:ring-1 cursor-pointer px-3 py-2;
  }

  &::file-selector-button {
    @apply rounded-none border-0 border-gray-300 border-solid px-3 py-2 -mx-3 -my-2 bg-gray-100 leading-6 transition pointer-events-none;
    margin-inline-end: theme('spacing.3');
    border-inline-end-width: 1px;
  }

  &:hover::file-selector-button {
    @apply bg-gray-200;
  }

  &::-webkit-file-upload-button {
    @apply rounded-none border-0 border-gray-300 border-solid px-3 py-2 -mx-3 -my-2 bg-gray-100 leading-6 transition pointer-events-none;
    margin-inline-end: theme('spacing.3');
    border-inline-end-width: 1px;
  }

  &:hover::-webkit-file-upload-button {
    @apply bg-gray-200;
  }
}
```

For some reason `tailwindcss` or `postcss` inlines only `&::-webkit-file-upload-button` which is an invalid selector. By the way, this is my `postcss.config.js`:

```javascript
const path = require("path")

module.exports = ctx => ({
  plugins: [
    require("postcss-import")({
      path: path.resolve(__dirname + "/frontend/styles")
    }),
    require("tailwindcss")(`frontend/styles/tailwind.${path.basename(ctx.file, ".css")}.js`),
    require("postcss-nested"),
    require("postcss-flexbugs-fixes"),
    require("postcss-color-mod-function")({unresolved: "warn"}),
    require("postcss-preset-env")({
      stage: 3,
      autoprefixer: {
        flexbox: "no-2009"
      }
    })
  ]
})
```
