### ISSUE TITLE
v2.2.8 not generating global variables

### ISSUE THREAD

**Issue by mattiaz9** [tailwindlabs/tailwindcss#5059]
### What version of Tailwind CSS are you using?

2.2.6

### What build tool (or framework if it abstracts the build tool) are you using?

vite 2.4.3, postcss 8.3.6, typescript 4.3.5

### What version of Node.js are you using?

v14

### What browser are you using?

Safari, Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/mattiaz9/tailwind-global-variable-issue

### Describe your issue

I believe is the same issue as this: https://github.com/tailwindlabs/tailwindcss/issues/5034

What I noticed is that the problem occurs when using `@apply` rather than utility classes.

To run the reproduction repository: `yarn && yarn dev`

**Comment by adamwathan** [comment]
Reverted the main piece of the changes that cause this stuff for v2.2.7, check that out and see if it helps. Hopefully can resolve the underlying issues and bring these improvements back soon.

**Comment by mattiaz9** [comment]
@adamwathan looks like it's working (mostly), but I noticed that the var `--tw-backdrop-filter` is missing and the backdrop filter doesn't work.
Apparently this issue is there since the version 2.2.5.

**Comment by Alessandra725** [comment]
Global variable are the variables possessing constant value throughout the project. These variables are beneficial when they are to be shared among various Test Case(s)/Function library/Gherkin/Sparkin/Service Repository/Suite.

**Comment by bstro** [comment]
I also seem to be experiencing a similar issue. 2.2.7

**Comment by jcasanova** [comment]
Hi @mattiaz9 thanks for reporting it

Same issue here, noticed kind of bug between v2.2.4 (working) and latest v2.2.16 (broken).

From the output of `*, ::before, ::after` it looks like the shadow/ring utility is breaking something.
I tried removing the experimental `optimizeUniversalDefaults` flag, upgrading/downgrading several versions around this optimization without any luck.

@adamwathan thepoint is filter related vars are not defined

## Globals from 2.2.4 (working)
![image](https://user-images.githubusercontent.com/1027644/134983666-1b5780f6-d054-4789-b37b-3d937131ceff.png)

## Globals from 2.2.16 (broken)
![image](https://user-images.githubusercontent.com/1027644/134985492-ba824b7a-2a65-41ae-a761-f16c02e09875.png)

**Comment by jcasanova** [comment]
Another fix for this issue, instead of downgrading to 2.2.4 is to add missing vars to your utility section :
```css

@layer utilities {

   ...

    *, ::before, ::after {
        --tw-blur: var(--tw-empty,/*!*/ /*!*/);
        --tw-brightness: var(--tw-empty,/*!*/ /*!*/);
        --tw-contrast: var(--tw-empty,/*!*/ /*!*/);
        --tw-grayscale: var(--tw-empty,/*!*/ /*!*/);
        --tw-hue-rotate: var(--tw-empty,/*!*/ /*!*/);
        --tw-invert: var(--tw-empty,/*!*/ /*!*/);
        --tw-saturate: var(--tw-empty,/*!*/ /*!*/);
        --tw-sepia: var(--tw-empty,/*!*/ /*!*/);
        --tw-drop-shadow: var(--tw-empty,/*!*/ /*!*/);
        --tw-filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
        --tw-backdrop-blur: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-brightness: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-contrast: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-grayscale: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-hue-rotate: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-invert: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-opacity: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-saturate: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-sepia: var(--tw-empty,/*!*/ /*!*/);
        --tw-backdrop-filter: var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia);
    }
}
```
