### ISSUE TITLE
Some base styles are being compiled even though preflight is disabled

### ISSUE THREAD

**Issue by kayewrobleski** [tailwindlabs/tailwindcss#5157]
### What version of Tailwind CSS are you using?

v2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind CLI

### What version of Node.js are you using?

v12.22.1

### What browser are you using?

N/A

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/kayewrobleski/tailwind-issue

### Describe your issue

Some base styles are being added to the compiled css file, even though `preflight` is disabled in `tailwind.config.js`.

#### Steps to replicate
```
# clone repo
git clone https://github.com/kayewrobleski/tailwind-issue.git

# install dependencies
cd tailwind-issue
npm install

# build tailwind styles
npx tailwindcss -o build/tailwind.css
```

#### Actual Behavior

The following Preflight styles appear in `build/tailwind.css`

```css
*, ::before, ::after {
  --tw-border-opacity: 1;
  border-color: rgba(229, 231, 235, var(--tw-border-opacity))
}
```

#### Expected Behavior

No Preflight styles should appear in `build/tailwind.css`.

**Comment by crswll** [comment]
This code comes from the `borderOpacity` plugin but disabling it doesn't stop the selector from being generated.

You can get it to browser defaults with this if you'd like:

```css
@layer base {
  *, ::before, ::after {
    border-color: #000;
  }
}
```
