### ISSUE TITLE
Stacked custom variants are not generated properly

### ISSUE THREAD

**Issue by sarahdayan** [tailwindlabs/tailwindcss#5332]
### What version of Tailwind CSS are you using?

2.2.8

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.1.0

### What version of Node.js are you using?

v14.17.3

### What browser are you using?

Firefox 91.0.2 (but I reproduce in Chrome 92.0.4515.159)

### What operating system are you using?

macOS Big Sur 11.4

### Reproduction repository

https://play.tailwindcss.com/CpByN9yrfi

### Describe your issue

Hey Tailwind team!

I'm having issues stacking custom variants. I'm trying to replicate a placeholder in a `contenteditable` element, and I want to display the placeholder when the element is empty and focused.

I'm using a `::before` pseudo-element to display the placeholder together with `content: attr(placeholder)`. Here's what the element looks like:

```html
<div placeholder="Start typing" contenteditable="true" />
```

The selector I'm trying to generate should work like the following:

```css
[contenteditable='true']:focus:empty:before {
  content: attr(placeholder);
}
```

This CSS works. To reproduce this using Tailwind, I created custom variants:

```js
const plugin = require('tailwindcss/plugin')

module.exports = {
  mode: 'jit',
  plugins: [
    plugin(function ({ addVariant, e }) {
      addVariant('before', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `.${e(`before${separator}${className}`)}::before`
        })
      })
      addVariant('empty', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `.${e(`empty${separator}${className}`)}:empty`
        })
      })
    }),
    plugin(({ addUtilities }) => {
      const contentUtilities = {
        '.placeholder': {
          content: 'attr(placeholder)',
        },
      }

      addUtilities(contentUtilities, ['before', 'empty', 'focus'])
    }),
  ],
}
```

Which I'm trying to use like the following on my element:

```html
<div placeholder="Start typing" class="focus:empty:before:placeholder" contenteditable="true" />
```

Unfortunately, the generated CSS doesn't work. Here's what I would expect:

```css
.focus\:empty\:before\:placeholder:focus:empty::before {
    content: attr(placeholder);
}
```

And here's what Tailwind generates instead:

```css
.focus\:empty\:before\:placeholder:focus:empty {
    content: attr(placeholder);
}
```

<img width="557" alt="Capture d’écran 2021-08-29 à 19 49 18" src="https://user-images.githubusercontent.com/5370675/131261029-458ae7e3-a073-4608-82c1-2d5e4d021a8f.png">

I toyed with it a bit, tried to change the order of the variants, and it seems that Tailwind always ignores the last variant. For example, when I switch `:empty` and `:before`:

```html
<div placeholder="Start typing" class="focus:before:empty:placeholder" contenteditable="true" />
```

Tailwind generates this CSS:

```css
.focus\:before\:empty\:placeholder:focus::before {
    content: attr(placeholder);
}
```

**Any idea what I'm doing wrong? Any missing step?**

Thanks in advance for the help, and let me know if I can clarify anything!
