### ISSUE TITLE
Usage with haml files: error when parsing classes following by variable

### ISSUE THREAD

**Issue by jibees** [tailwindlabs/tailwindcss#5408]
### What version of Tailwind CSS are you using?

v2.2.9

### What build tool (or framework if it abstracts the build tool) are you using?

@rails/webpacker 5.4.2

### What version of Node.js are you using?

v16.2.0

### What browser are you using?

N/A

### What operating system are you using?

N/A

### Reproduction repository

https://github.com/jibees/tailwind-example

### Describe your issue

The view file is:
```haml
%h1 Articles#index
- name = "Find me in app/views/articles/index.html.erb"
%p.text-yellow-50.text-lg=name
%p.text-yellow-100.text-sm
  = name
```

the generated css file is
```css
.text-sm {
  font-size: 0.875rem;
  line-height: 1.25rem;
}

.text-yellow-50 {
  --tw-text-opacity: 1;
  color: rgba(255, 251, 235, var(--tw-text-opacity));
}

.text-yellow-100 {
  --tw-text-opacity: 1;
  color: rgba(254, 243, 199, var(--tw-text-opacity));
}
```
and nothing about `.text-lg`

The `text-lg` is not parsed by tailwind, probably due to the following `=name` which is a valid syntax in haml.
