### ISSUE TITLE
[Feature Proposal] Add more table display utilities

### ISSUE THREAD

**Issue by cossssmin** [tailwindlabs/tailwindcss#567]
👋

Would you be open to adding a few more `display` utilities for tables?

Specifically, these:

```css
.table-row-group {
    display: table-row-group;
}
.table-header-group {
    display: table-header-group;
}
.table-footer-group {
    display: table-footer-group;
}
.table-column-group {
    display: table-column-group;
}
.table-column {
    display: table-column;
}
.table-caption {
    display: table-caption;
}
```

I know these might not be as used for _web_ development - found myself needing them mostly for doing reverse column stacking on mobile, when using Tailwind in [Maizzle](https://maizzle.com). Of course, I can totally generate them myself - just thought I'd ask if you think this would make sense to be included in core.

Thanks!
