### ISSUE TITLE
[JIT] apply: duplicate transform properties

### ISSUE THREAD

**Issue by trurl-master** [tailwindlabs/tailwindcss#5806]
**What version of Tailwind CSS are you using?**

2.2.15 (also tested with 3.0.0-alpha.1 and 2.2.17)

**Reproduction URL**

https://play.tailwindcss.com/KkuBVniu30?file=css

**Describe your issue**

Using multiple transform-based properties (like translate-x and translate-y) results in duplicated `transform` property, eg

```css
.absolute-center {
  @apply absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2;
}

```

Generates:

```css
.absolute-center {
    position: absolute;
    top: 50%;
    left: 50%;
    --tw-translate-x: -50%;
    transform: var(--tw-transform);
    --tw-translate-y: -50%;
    transform: var(--tw-transform);
    transform: var(--tw-transform);
}
```
