### ISSUE TITLE
@apply class order not working

### ISSUE THREAD

**Issue by rainerborene** [tailwindlabs/tailwindcss#5855]
**What version of Tailwind CSS are you using?**

v2.1.2

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack 5.11.0, postcss 8.1.6

**What version of Node.js are you using?**

v14.1.0

**What browser are you using?**

For example: Firefox

**What operating system are you using?**

For example: Ubuntu

**Reproduction URL**

Here is the source code:

```css
.input-group .input-group-prepend {
  @apply inline-flex items-center px-3 rounded-l-md border border-r-0 border-slate-300 bg-gray-50 text-gray-500;
}
```

And compiled version:

```css
.input-group .input-group-prepend {
 --tw-bg-opacity:1;
 --tw-text-opacity:1;
 align-items:center;
 background-color:rgba(249,250,251,var(--tw-bg-opacity));
 border-bottom-left-radius:.375rem;
 border-color:#d1d5db;
 border-color:var(--color-slate-300);
 border-right-width:0;
 border-top-left-radius:.375rem;
 border-width:1px;
 color:rgba(107,114,128,var(--tw-text-opacity));
 display:inline-flex;
 padding-left:.75rem;
 padding-right:.75rem
}
```

**Describe your issue**

As you can see on the above code the `border-width` should not go after `border-right-width` according to the `@apply` rules.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should work in newer versions, please upgrade to a newer version: 
- Using AOT mode: https://play.tailwindcss.com/MMvsj89JV7
- Using JIT mode (only mode in v3): https://play.tailwindcss.com/BAK6y3qebX

This generates:
```css
.input-group .input-group-prepend {
    display: inline-flex;
    align-items: center;
    border-top-left-radius: 0.375rem;
    border-bottom-left-radius: 0.375rem;
    border-width: 1px;
    border-right-width: 0px;
    --tw-border-opacity: 1;
    border-color: rgba(212, 212, 216, var(--tw-border-opacity));
    --tw-bg-opacity: 1;
    background-color: rgba(249, 250, 251, var(--tw-bg-opacity));
    padding-left: 0.75rem;
    padding-right: 0.75rem;
    --tw-text-opacity: 1;
    color: rgba(107, 114, 128, var(--tw-text-opacity))
}
```
