### ISSUE TITLE
CSS `@supports` is not working

### ISSUE THREAD

**Issue by dibasdauliya** [tailwindlabs/tailwindcss#5938]
Hello, I'm using this code with `CSS @supports` in `@layer utilities`, but the code inside `@supports` is not working (but it is supported in the browser I'm using). 

![image](https://user-images.githubusercontent.com/51583004/139522656-570ec9f7-1f0e-4d8e-be74-a9bf33fbab7a.png)

**Comment by dibasdauliya** [comment]
Solved this specific problem by [making a new variant just to target Firefox](https://play.tailwindcss.com/tfMKv6L7ci?file=config) [helped by someone from Tailwind discord server], but I'd love to have `CSS @supports` feature.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a **minimal** reproduction repo that reproduces this issue?
One thing I noticed is that you have `blur(1)` instead of `blur(1px)`. You can only leave off the unit if you are using `0`. E.g.: `blur(0)`

I created a play.tailwindcss.com repro (https://play.tailwindcss.com/Br6lM1vO5V?file=css) and it generated this:

```css
.test {
  background-color: red;
}

@supports ((-webkit-backdrop-filter: blur(1px)) or (backdrop-filter: blur(1px))) {
  .test {
    background-color: green;
  }
}
```

I also opened a PR with a test and it does keep the `@supports` layer: https://github.com/tailwindlabs/tailwindcss/blob/2fbb916c86be4f7066e330627307824b5caa9dcc/tests/layer-at-rules.test.js#L303-L338
