### ISSUE TITLE
The input focus style cannot be overridden

### ISSUE THREAD

**Issue by ouweiya** [tailwindlabs/tailwindcss#6036]
### What version of @tailwindcss/forms are you using?

^0.4.0-alpha.2

### What version of Node.js are you using?

v14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/ouweiya/tailwindcss-forms-Dom

### Describe your issue

The input focus style should be able to be overridden, but it cannot be overridden because the css variable is incorrectly referenced.

Only by modifying the css variable can it be solved.

```css
#list [type='text']:focus {
  --tw-ring-shadow: 0 0 #0000;
}
```
