### ISSUE TITLE
@apply with peer variants does not work when the selector contains multiple levels

### ISSUE THREAD

**Issue by fschuetz04** [tailwindlabs/tailwindcss#6062]
**What version of Tailwind CSS are you using?**

v2.2.19

**What build tool (or framework if it abstracts the build tool) are you using?**

SvelteKit v1.0.0-next.192, PostCSS v8.3.11

**What version of Node.js are you using?**

v14.18.1

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/qityfE6eF9?file=css

**Describe your issue**

When using `@apply` with `peer-hover`, `.peer:hover ~` is prepended before the selector. This only works if the selector does not contain multiple levels. Consider the following definitions:

```css
.without-wrapper {
  @apply peer-hover:text-red-500;
}

.wrapper .with-wrapper {
  @apply peer-hover:text-red-500;
}
```

Currently, TailwindCSS generates the following rules:

```css
.peer:hover ~ .without-wrapper {
	--tw-text-opacity: 1;
	color: rgba(239, 68, 68, var(--tw-text-opacity));
}

.peer:hover ~ .wrapper .with-wrapper {
	--tw-text-opacity: 1;
	color: rgba(239, 68, 68, var(--tw-text-opacity));
}
```

The second rule does not work, as can be seen at the Tailwind Play link: The second "Second" does not turn red when hovering over the second "First". The following rule should be generated instead, inserting `.peer:hover ~` at the last space of the selector:

```css
.wrapper .peer:hover ~ .with-wrapper {
	--tw-text-opacity: 1;
	color: rgba(239, 68, 68, var(--tw-text-opacity));
}
```

**Comment by thecrypticace** [comment]
Hey, thanks for the report. This is definitely weird but expected behavior (for now at least).

## Summary

The short version of this is that, as of right now, we're not going to fix this one as it might open a can of worms that we're not ready to tackle yet and it would also technically be a breaking change for anyone relying on the current behavior. However, we may decide to revisit this in the future once we have a good solution on how to handle all of these situations in a consistent, predictable manner.

At a high-level `@apply` tries to have a consistent set of rules on how it modifies selectors based on the class being applied:
1. It breaks apart a class and it's applies into a separate set of rules for each class
2. It will nest a rule inside any At Rules to match the structure of the applied class (e.g. surrounding with a media query because you applied `sm:font-bold`)
3. It modifies the selector by replacing the _last_ item in the applied class with the selector you're applying something to. (This is a bit simplified but it'll do for this)
4. It applies *all* instances of a class, even when they're involved in other complex selectors.

These rules apply to rules created by Tailwind CSS and by your own CSS. We don't special case our own rules / variants / etc… internally as we want a consistent, predicable behavior that the user can replicate. The only exception we make is to specialize the error messages we show for the `group`, `peer`, and `dark` classes themselves for a slightly better developer experience.

## An semi-in-depth look at `@apply`

To understand *why* `@apply` works this way lets take a look at three different variants:
- `peer-hover` — the one this issue is about
- `group-hover` — this one is like a spiritual cousin of `peer-hover` as it is also based on hierarchy
- `dark` — When using `darkMode: 'class'` a user can mark either the whole document as being in dark mode by adding a class to `<html>` or a subset by adding a class to a parent `<div>`

_Note: For the purposes of simplifying the code I've also disabled the `textOpacity` plugin._

Each of these variants generate classes that look like this:
```css
.group:hover .group-hover\:text-black {
  color: #000;
}

.peer:hover ~ .peer-hover\:text-black {
  color: #000;
}

.dark .dark\:text-black {
  color: #000;
}
```

When you `@apply` each of these to a non-nested class then there is a well defined behavior. We replace the last segment (`group-hover\:text-black`, `peer-hover\:text-black`, `dark\:text-black`) with whatever you've written, copy the declarations in, and then wrap that rule in the necessary at-rules.

```css
/* Input */
.foo { @apply group-hover:text-black; }

/* Output */
/* Original selector: .group:hover .group-hover\:text-black */
.group:hover .foo {
  color: #000;
}

/* Input */
.foo { @apply peer-hover:text-black; }

/*  Output */
/* Original selector: .peer:hover ~ .peer-hover\:text-black */
.peer:hover ~ .foo {
  color: #000;
}

/* Input */
.foo { @apply dark:text-black; }

/* Output */
/* Original selector: .dark .dark\:text-black */
.dark .foo {
  color: #000;
}
```

However, if you have a more complicated selector with descendants the "correct" solution could be one of many and may not be the same for each variant.

To illustrate this we're going to use this slightly more complex selector and discuss each variant individually:

```css
.outer .inner .my-class {
  @apply classes go here;
}
```

### The `group-hover` variant

```css
/* Input */
.outer .inner .my-class {
  @apply group-hover:text-black;
}

/* Output */
.group:hover ~ .outer .inner .my-class {
  color: #000;
}
```

The intent of the `group-hover` variant (and any of the `group-*` variants) is that you can wrap an element with another one with a `group` class and the state of that element is what controls it's children. For example in a list with multiple items where you want to control the color of all of the children by hovering over the list item. In this case **depth does not matter** as long as it is at least a parent element.

With that we could have 5 separate possibilities for how we generate the class above:
- `.outer .inner .group:hover .my-class`
- `.outer .inner.group:hover .my-class`
- `.outer .group:hover .inner .my-class`
- `.outer.group:hover .inner .my-class`
- `.group:hover .outer .inner .my-class`

The first is not necessarily wrong by any means but it does prevent you from having an element `group` outside of `.inner` or `.outer` that affects `.my-class`. In fact, neither `.outer` nor `.inner` can have group on them either because they would not match. In the second, we've somewhat fixed this by attaching `.group:hover` to the `.inner` class but it still exhibits the same problem just with the `.outer` class. We can repeat this process until we end up at the end with `.group:hover .outer .inner .my-class`. I want to note that, based on the situation, any one of these could be valid. But what may work for your use case may not work for someone else's. Another option is to generate *all* of these but that would massively increase the size of the generated CSS for little benefit.

When I read this:

```css
.outer .inner .my-class {
  @apply group-hover:text-black;
}
```

I think "when the group containing `.outer .inner .my-class` is hovered then change the color to black" and that checks with the generated CSS.

Tailwind CSS uses the last approach because it's consistent and affords the user the most flexibility.

### The `dark` variant

```css
/* Input */
.outer .inner .my-class {
  @apply dark:text-black;
}

/* Output */
.dark .outer .inner .my-class {
  color: #000;
}
```

The intent of the `dark` variant is that you can control what an element looks like when a user's system is in dark mode. However, when paired with `darkMode: 'class'` we give the developer a little more control over toggling dark mode and what parts of the site respond to it. For example, you can add `dark` to *any* element. Not just an `<html>` element.

If we have a website where the dark mode controls maybe the sidebar on some pages but not the long-form article content (perhaps because it has infographics and such) then you can absolutely do something like this where toggling dark mode adds/removes it from the `aside` element:
```html
<main>
  <aside class="dark">
    <div class="dark:text-white">
      This text is white in dark mode
    </div>
  </aside>
  <article>
    This never considered to be in dark mode no matter what.
    <div class="dark:text-white">So this text is still black or text-gray-800 or whatever</div>
  </article>
</main>
```

To reiterate, the intent when paired with `darkMode: 'class'` is that you can control what is dark mode and can do it at any level. It's just that most of the time people happen to put this on the `html` element because it will then affect everything.

With that knowledge in mind, and the explanation about `group-hover` from above let's take a look a list of possible selectors:
- `.outer .inner .dark .my-class`
- `.outer .inner.dark .my-class`
- `.outer .dark .inner .my-class`
- `.outer.dark .inner .my-class`
- `.dark .outer .inner .my-class`

Each of these isn't necessarily wrong however there is only one item that actually makes sense *and* gives the developer the flexibility of placing `dark` on *any* parent element (even the `<html>` element) — the last one. In all other cases you lose a capability you had previously.

Again, in this case, Tailwind CSS uses the last approach because it's consistent, affords the user the most flexibility, and happens to be the sensible choice.

### The `peer-hover` variant

Now, with all that in mind, let's take a look at `peer-hover`

```css
/* Input */
.outer .inner .my-class {
  @apply peer-hover:text-black;
}

/* Output */
.peer:hover ~ .outer .inner .my-class {
  color: #000;
}
```

Now, I can look at this one and say it is *obviously* incorrect from an experience point of view. This is because the intent of the `peer` variant is to style something based on the state of a prior "peer" or "sibling". It would make the most sense that the thing in question that has siblings is `.my-class`. This does not necessarily need to be the case though. It is possible that you'd want to style something inside `.outer` when an element before `.outer` is hovered.

We could have any one of these selectors generated:
- `.outer .inner .peer ~ .my-class`
- `.outer .inner.peer ~ .my-class`
- `.outer .peer ~ .inner .my-class`
- `.outer.peer ~ .inner .my-class`
- `.peer ~ .outer .inner .my-class`

And the big problem here is that they all mean slightly different things:
1. A peer of `.my-class` that is inside of `.outer .inner` was hovered
2. The peer is itself  `.inner` so `.my-class` isn't actually inside `.inner` like could be in the original selector.
3. A peer of `.inner` has been hovered and will affect `.my-class`
4. Like option 2 but weirder: The peer itself is `.outer` so neither `.inner` nor `.my-class` can be inside `.outer` as in the original selector.
5. A peer of `.outer` (or rather: a peer of the whole selector) in which `.outer .inner .my-class` can be styled (like in the original selector).

Of these, options 2 amd 4 are definitely incorrect because there's a major behavioral change and it requires restructuring your HTML. Any one of 1, 3, and 5 could be valid but placing it in the middle of a selector like in option 3 would be really unexpected. So that means we're left with either option 1 or option 5. And both of these could be completely correct! We see, from your issue, where the first one is definitely correct. However, there could be situations in which option 5 would be the preferred one.

To illustrate this in more detail I'm going to deviate from the example. This definitely a contrived one but let's say that your app has a "help" feature. And as part of this feature your app will highlight related items. For example, hovering a `<label>` would highlight the relevant `<input>` element(s). In a situation like this I would most likely use Javascript to toggle classes *but* it is possible to do in CSS:

```css
.form-cell .form-input {
  @apply peer-hover:outline-dashed peer-hover:outline-2 peer-hover:outline-purple-400;
}

.form-cell .form-input-optional {
  @apply peer-hover:outline-dashed peer-hover:outline-2 peer-hover:outline-gray-400;
}
```

```html
<div>
  <label class="peer">Name (hover over me)</label>
  <div class="form-cell">
    <input type="text" name="name" class="form-input" placeholder="First Name">
    <input type="text" name="name" class="form-input" placeholder="Last Name">
    <input type="text" name="name" class="form-input-optional" placeholder="Title">
  </div>
</div>
```

In this situation hovering the `label` would highlight each of the form inputs with either purple or gray based on whether or not it's required for that form. And yeah you could totally use the `[required]` attribute and some more custom CSS — like I said this was definitely a contrived example. However, as you can see, in this situation the current behavior of `peer` would be preferred. And, since the rules for `@apply` are the same for Tailwind CSS as they are for your own CSS we can't necessarily know the intent of the class being used inside an `@apply`.

Therefore, once again, Tailwind CSS uses the last approach (prefixing the whole selector) because it's consistent with the way `@apply` works for all other variants and custom CSS.

All in all, we know this is definitely weird and feels unexpected based on the usage, but we're not likely to change this behavior any time soon. And, again, all of this applies right now — we may very well decide to change this in the future.
