### ISSUE TITLE
Invert class

### ISSUE THREAD

**Issue by LucasLpc** [tailwindlabs/tailwindcss#6204]
I'm not an expert but I don't think this can work because of the name of the CSS variable and I encountered a problem with this class on Brave Navigator.

<img width="265" alt="Capture d’écran 2021-11-26 à 15 24 49" src="https://user-images.githubusercontent.com/36164636/143595189-0d4b44da-4f3b-4a11-b05f-93113713d34d.png">

**Comment by adamwathan** [comment]
Works great in Brave:

![image](https://user-images.githubusercontent.com/4323180/143597500-9919b618-9e57-4ec3-8c53-f0eeab643940.png)

https://play.tailwindcss.com/yaNUemZFsZ

The names `--tw-invert` and `--tw-filter` are both fine variable names. There is more to how this works than that one class though, the full CSS is this:

```css
/* In base layer */
* {
  --tw-blur: ;
  --tw-brightness: ;
  --tw-contrast: ;
  --tw-grayscale: ;
  --tw-hue-rotate: ;
  --tw-invert: ;
  --tw-saturate: ;
  --tw-sepia: ;
  --tw-drop-shadow: ;
  --tw-filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast)
    var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate)
    var(--tw-sepia) var(--tw-drop-shadow);
}

/* In utilities layer */
.invert {
    --tw-invert: invert(100%);
    filter: var(--tw-filter);
}
```

So `--tw-filter` references `--tw-invert`, and the `.invert` class just changes `--tw-invert` from ` ` to `invert(100%)` and adds the `filter` property using the `--tw-filter` class defined earlier that references `--tw-invert`. Hope that helps explain how it works.
