### ISSUE TITLE
Ring not working with @apply in tailwindcss v3

### ISSUE THREAD

**Issue by zynth17** [tailwindlabs/tailwindcss#6328]
**What version of Tailwind CSS are you using?**

For example: v3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss 8.4.4, Vue 3.2.23, Vite 2.7.1,sass 1.44.0

**What version of Node.js are you using?**

For example: v14.0.0

**What browser are you using?**

Brave

**What operating system are you using?**
Windows 11

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-bnujfo?file=src/components/HelloWorld.vue

**Describe your issue**

Ring not working if using @apply.
it does work normally when i move it to the html classes attribute.

**Comment by agusterodin** [comment]
Possibly related to #6194

**Comment by zynth17** [comment]
> Possibly related to #6194

oh right, didn't check it. thankyou!

**Comment by agusterodin** [comment]
Honestly I would reopen your issue. Yours is more general than mine and mine hasn't gotten any attention for a few weeks. Plus you have a repro set up.

**Comment by zynth17** [comment]
> Honestly I would reopen your issue. Yours is more general than mine and mine hasn't gotten any attention for a few weeks. Plus you have a repro set up.

allright. hope this got fix asap, since this is such a critical problem

**Comment by reinink** [comment]
Hey folks! This should be fixed now as of `v3.0.2` 👍

Ultimately these are the same issues: https://github.com/tailwindlabs/tailwindcss/issues/6409 https://github.com/tailwindlabs/tailwindcss/issues/6391 https://github.com/tailwindlabs/tailwindcss/issues/6437

And the fix: https://github.com/tailwindlabs/tailwindcss/pull/6461

Please let us know if you're still experiencing this issue on the latest version.

**Comment by solamichealolawale** [comment]
I am using `^3.0.12` and I am still having this issue on production
I am using Nuxtjs with Tailwind v3 and whenever I ran `npm run generate` it doesn't show

**Comment by Francismori7** [comment]
> I am using `^3.0.12` and I am still having this issue on production I am using Nuxtjs with Tailwind v3 and whenever I ran `npm run generate` it doesn't show

Same here. In product on GatsbyCloud, the ring styles are non-functioning, using @apply or not.

**Comment by filipppp** [comment]
For me, it still doesn't work, I have to manually add 

`--tw-ring-inset: var(--tw-empty, );`

so that the box-shadow propertyis working..

I'm using the Version `3.0.22`

**Comment by chrismllr** [comment]
Can confirm on version 3.0.22... Only seeing the issue in production build of the css. 

I am using ember, which has an extra "minifyCss" step within the build process using `broccoli-clean-css`, which wraps an outdated version of `clean-css`. Adding a resolution to version 5.4.3 of clean-css fixed this issue for me (possibly related issue?: https://github.com/clean-css/clean-css/issues/1196)

Unsure what `clean-css` configuration caused it, but this entire block of css was missing from the non-working minified CSS, but present in the working CSS:
```css
:after,
:before {
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  --tw-skew-y: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
  --tw-pan-x: ;
  --tw-pan-y: ;
  --tw-pinch-zoom: ;
  --tw-scroll-snap-strictness: proximity;
  --tw-ordinal: ;
  --tw-slashed-zero: ;
  --tw-numeric-figure: ;
  --tw-numeric-spacing: ;
  --tw-numeric-fraction: ;
  --tw-ring-inset: ;
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  --tw-shadow-colored: 0 0 #0000;
  --tw-blur: ;
  --tw-brightness: ;
  --tw-contrast: ;
  --tw-grayscale: ;
  --tw-hue-rotate: ;
  --tw-invert: ;
  --tw-saturate: ;
  --tw-sepia: ;
  --tw-drop-shadow: ;
  --tw-backdrop-blur: ;
  --tw-backdrop-brightness: ;
  --tw-backdrop-contrast: ;
  --tw-backdrop-grayscale: ;
  --tw-backdrop-hue-rotate: ;
  --tw-backdrop-invert: ;
  --tw-backdrop-opacity: ;
  --tw-backdrop-saturate: ;
  --tw-backdrop-sepia: ;
}
```
