### ISSUE TITLE
Watch issues on Docker on Windows

### ISSUE THREAD

**Issue by Sieabah** [tailwindlabs/tailwindcss#6343]
**What version of Tailwind CSS are you using?** 

3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

ng build (Angular)

**What version of Node.js are you using?**

Docker node:v14

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows, but app is built within Docker

**Describe your issue**

JIT is a great concept until the expected watch API doesn't work. When working within a docker container on windows file events are not correctly propagated. This creates issues for build systems that do not support polling.

I got around this in v2.2 by disabling purge in development mode and enabling it for builds. Now with JIT the styles are not properly recreated when I change a component template.

**Comment by eblaauw** [comment]
Same issue here - I've tried:

`purge: false`
`purge: []`
`purge: ['*']`
`content: []`
`content: ['*']` 

and they all did not work.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a **minimal** reproduction repo with docker that showcases this issue?

**Comment by blackjak231** [comment]
By looking at the normalizer in tailwind, it seems the `purge.enabled` option has completely disappeared from the options.

Is it possible to disable the purge any other way ?

**Comment by oller** [comment]
It seems 

> Since Tailwind no longer uses PurgeCSS under the hood

https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

Encountering similar issues, as `safelist` now only refers to internal tailwind classes, not broader purge options.  Looks like we'll need to bring this back in as an external dep.  Shall park this upgrade branch for now!

**Comment by Sieabah** [comment]
> Hey! Thank you for your bug report! Much appreciated! 🙏
> 
> Can you create a **minimal** reproduction repo with docker that showcases this issue?

Literally any configuration of tailwind inside of a docker container from windows will not work in any capacity. So I could create a repo but it might end up working if you're using it from mac or linux since they share similar enough file events.

**Comment by zackdotcomputer** [comment]
I was running into this issue with RedwoodJS and couldn't figure out why it was happening there but not in NextJS. I'll take that issue up with their team.

For the purposes of helping folks who wind up in this thread, though, I found [this troubleshooting tip](https://v2.tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files) from the V2 Tailwind site fixed my issue. TLDR; I needed to set the env variable `TAILWIND_MODE=watch` when developing to kick the JIT compiler into rebuilding the css files every time my sources changed. It might be worth promoting that tip to the v3 getting started guide now that JIT is the default?

**Comment by dotdiego** [comment]
Disabling the purge is really helpful too for Visual Studio (not Code) since we do not have a dedicated tailwindcss intellisense plugin we can see all the classes availables when it's built in the .css files.

**Comment by Sieabah** [comment]
@aizaiz That's a huge component of my workflow is playing around with classes before changing it in the source. It's a shame there doesn't seem to be a way to disable purge or even allowing polling. Postcss seems to support it but I'm not sure if it will work with Angular or with HMR.

@zackdotcomputer I have that in my environment and it doesn't help when the file events aren't properly handled like with Docker on windows. There simply is no file events that ever get emitted when a file changes. 

@RobinMalfait If you require a min repo for this to be considered a bug all I'm going to do is the following.

```
npm i -g @angular/cli
ng new sample
cd sample
npm i --save-dev tailwindcss

#tailwind config with content = './src/**/*.{html,ts}'
ng serve --poll 2500
```

That's all I'm willing to do because this should occur on any configuration within containers on windows due to how the file system is mounted.

Regardless I've had to downgrade to v2 until there is some fix that allows me to disable purging in development or allows polling so the JIT can work with containers consistently.

**Comment by DanielSpravtsev** [comment]
@aizaiz @dotdiego Agree with you. I don't know how it's on VC Code, but PHPStorm built-in tailwindcss plugin not working as expected and with purging enabled there are no classnames to hint by IDE

**Comment by dotdiego** [comment]
@DanielSpravtsev about Jetbrains IDEs they're tracking that issue ([WEB-48464](https://youtrack.jetbrains.com/issue/WEB-48464#focus=Comments-27-5656656.0-0) on their issue tracker). It seems there's a regression on all IDEs 2021.3

**Comment by HepplerDotNet** [comment]
Still (3.0.5) no option to disable purging during development?
One workaround is to use `<script src="https://cdn.tailwindcss.com"></script>` during development

**Comment by Sieabah** [comment]
@HepplerDotNet This works perfectly!

**Comment by leeshadle** [comment]
### Purging via safelisting

As @HepplerDotNet shared, it looks like you can disable purging via safelisting:

```js
safelist: [
  {
    pattern: /./,
  },
]
```

And then to account for variants such as hover:, focus:, and responsive variants (lg:,md:,sm:) this works:
```js
safelist: [
  {
    pattern: /./,
    variants: ['hover','focus','sm','md'],
  },
]
```

And then to safelist chained variants such as md:hover:, sm:hover, md:focus, sm:focus this works:
```js
safelist: [
  {
    pattern: /./,
    variants: ['hover','focus','md','sm','md:hover','sm:hover','md:focus','sm:focus'],
  },
]
```

This was hard to figure out 🤔...

I used the appendix at the link below for referencing the variant types to use with safelist patterns and then figured out the chaining through trial and error: 
https://tailwindcss.com/docs/hover-focus-and-other-states#quick-reference

### Safelisting with Prefixes (tw-) and negative utility class values doesn't seem to work? 🤔
With that being said, if you use a prefix such as tw-, I can't get the safelisting to work with negative values ( such as for margin, skew, rotate, scale, translate utilities):
```js
prefix: 'tw-',
safelist: [
{
	pattern: /-skew-x-2/,
	variants: ['hover','focus','md','sm','md:hover','sm:hover','md:focus','sm:focus'],
},
```

```css
.tw-skew-x-2 {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

.hover\:tw-skew-x-2:hover {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

.focus\:tw-skew-x-2:focus {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

@media (max-width: 1023px) {
	.md\:tw-skew-x-2 {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.md\:hover\:tw-skew-x-2:hover {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.md\:focus\:tw-skew-x-2:focus {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
}

@media (max-width: 767px) {
	.sm\:tw-skew-x-2 {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.sm\:hover\:tw-skew-x-2:hover {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.sm\:focus\:tw-skew-x-2:focus {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
}
```
