### ISSUE TITLE
[3.x] Transforms not working (Laravel Mix)

### ISSUE THREAD

**Issue by marcreichel** [tailwindlabs/tailwindcss#6432]
**What version of Tailwind CSS are you using?**

v3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**

- Laravel 8.75
- Laravel Mix 6.0.39

**What version of Node.js are you using?**

14.17.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/marcreichel/tailwind3-transforms-reproduction

Screenshot:

![image](https://user-images.githubusercontent.com/7645035/145727757-997149ae-cb09-49a6-b9e6-b6255133a10d.png)

**Describe your issue**

The "base transform" selector is not generated. Therefore any transform utilities do not work.
Basically the there should be at least the following css code:

```css
.rotate-90, .translate-x-1\/2 {
    /* --tw-... */
    transform: rotate(var(--tw-rotate)) translateX(var(--tw-translate-x)) /* and so on ... */;
}
```

But this is completely missing.
