### ISSUE TITLE
Styling class and then using variant on that class leaks output

### ISSUE THREAD

**Issue by minimit** [tailwindlabs/tailwindcss#6451]
**What version of Tailwind CSS are you using?**

    "tailwindcss": "^3.0.1"

**What build tool (or framework if it abstracts the build tool) are you using?**

    "postcss": "^8.4.5",
    "postcss-cli": "^9.1.0",

**What version of Node.js are you using?**

v14.18.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/minimit/twbug-custom-variant-leak

**Describe your issue**

When css styling tailwind class selectors (e.g `relative`) and then applying custom variants to that tailwind class:

```
.test-custom-css.relative {
  position: absolute;
}

.test-custom-variant {
  @apply hover:relative;
}
```

the output leaks some styles in this way:

```
.test-custom-css.relative {
  position: absolute;
}

.test-custom-variant:hover {
  position: relative;
}

.test-custom-css.test-custom-variant:hover {
  position: absolute;
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

While the output looks very strange, I think this is the correct behaviour right now. The short answer is "don't include utilities in your selectors" the long answer is a bit more nuanced, fairly complex and a brain twister for sure 😬. Let me try and explain, ready for a ride?

## Preface: What does `@apply` allow you to do?

### 1) Interchangeability

The `@apply` feature allows you to take a set of classes from your html, move it to a new selector in your css and then replace it with the new selector. At that point it should become interchangeable with what you had before. This is important, because if it wasn't interchangeable then you just broke your site/app by refactorring.

Imagine you have this:
```html
<div class="underline font-bold"></div>
```
Play: https://play.tailwindcss.com/ixtLlJBswd

...and you use `@apply` like this:
```css
.custom {
  @apply underline font-bold;
}
```

Then you should be able to use the `custom` class instead of the `underline font-bold` and it should behave exactly the same.

```html
<div class="custom"></div>
```
Play: https://play.tailwindcss.com/K8vtdlcEuh

### 2) Variants / modifiers

So far so good, the next thing you have to know is that you can apply variants on top of utilities / component even though those don't really exists. What I mean by that is that the utility `relative` exists, but the utility `.hover\:relative` does not exist. Instead we take the `relative` utility and apply the `hover` variant on top to create the new utility.

Let's look at another example:
```css
@layer components {
  .btn {
    @apply px-4 py-3 rounded-full;
  }

  .btn-blue {
    @apply btn bg-blue-500 text-white;
    /*     ─┬─                                                    
     *      ╰─── This is referring to the `.btn` definition from above
     */
  }

  .btn-green {
    @apply btn bg-green-500 text-white;
    /*     ─┬─                                                    
     *      ╰─── This is referring to the `.btn` definition from above
     */
  }

  .btn-primary {
    @apply btn-blue;
    /*     ───┬────                                                    
     *        ╰────── This is referring to the `.btn-blue` from above
     */

    @apply hover:btn-green;
    /*     ──┬── ────┬────
     *       │       ╰─────── This is referring to the `.btn-green` from above
     *       │             ╭─
     *       ╰─────────────┤ ... but it also happens to have a modifier, but they are
     *                     │ still linked as if you wrote something like hover:relative
     *                     ╰─
     */
  }
}
```

So while we never defined a `hover:btn-green` it still applies the `hover` modifier to the defined `btn-green`.

This is because you want to be able to swap `btn-blue hover:btn-green` with `btn-primary` in this case:

```html
<button class="btn-blue hover:btn-green">Without abstraction</button>
<button class="btn-primary">Abstracted to `.btn-primary`</button>
```
Play: https://play.tailwindcss.com/YKuv2u2cKE

So in short this means:
1. We have a utility `x`
2. We use `hover:x` but this was never defined, instead we use the definitions of `x` and apply a `hover` on top. Now we have `x` and `hover:x` in our css.

### 3) All definitions are taken into account

The next thing that you have to know is that when you are applying a class is that you apply all the rules/definitions at the same time (in order). This is important and it is also how css works. For example:

```css
.btn { color: blue }
.btn { font-weight: bold }
.btn { text-decoration: underline }
```

This also applies all those rules to the DOM element, not just the first one.
```html
<button class="btn">I should be a bold blue underlined text</button>
```
Play: https://play.tailwindcss.com/OLJyqhEAGg

## What is evening happening?!

Alright, onto your example, if you have this in your css:
```css
.test-custom-css.relative {
  position: absolute;
}

.test-custom-variant {
  @apply hover:relative;
}
```

What makes this complex in your example is the fact that you started using existing utilities in both the `@apply` section and as part of the selector itself AND that you are applying variants on top of it.

So if we keep all the rules that we described above into account:
1. Should be interchangeable with the individual classes you had before.
2. Generates new classes (variants + base class).
3. Applies _all_ definitions we know.

Then we can explain what happens in your example. For starters now multiple definitions exists for the `relative` class.
1. The `relative` utility itself in Tailwind CSS
2. The `relative` class that is used in the selector here: `.test-custom-css.relative`

Next in your `test-custom-variant` example:
```css
.test-custom-variant {
  @apply hover:relative;
}
```

We apply a `hover:relative`, again this `hover:relative` itself doesn't exist, so we take all the definitions of `relative` which will be:
1. `.relative {}`
2. `.test-custom-css.relative {}`

And then we apply `hover` on top of those:
```css
/* A: This is your definition that includes .relative */
.test-custom-css.relative {
  position: absolute;
}

/* B: This is the result of `@apply hover:relative` where `relative` is referring to the Tailwind CSS utility + the `hover` variant on top. */
.test-custom-variant:hover {
  position: relative;
}

/* C: This is the result of `@apply hover:relative` where `relative` is referring to your definition (A) + the `hover` variant on top. */
.test-custom-css.test-custom-variant:hover {
  position: absolute;
}
```

So is this weird? Totally...
Is this expected behaviour I'm afraid so 😅

I don't know if it makes sense or if it helps you, but this is what happens and why you end up with that output.
