### ISSUE TITLE
Possible Bug: Tailwind CLI generates duplicate selector

### ISSUE THREAD

**Issue by enjidev** [tailwindlabs/tailwindcss#6718]
**What version of Tailwind CSS are you using?**

v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CLI

**What version of Node.js are you using?**

v14.16.0

**What browser are you using?**

N/A

**What operating system are you using?**

Arch Linux

**Reproduction URL**

https://stackblitz.com/edit/node-omyzvd?file=tailwind.config.js

**Describe your issue**

This code works as expected:
```JS
addComponents({
  '.button': {
    cursor: 'pointer',
    '@apply bg-red-400': {},
    // sub-selector comes last
    '.dark &': {
      backgroundColor: 'maroon',
    },
  },
});
```
Result:
```CSS
.button {
  cursor: pointer;
  --tw-bg-opacity: 1;
  background-color: rgb(248 113 113 / var(--tw-bg-opacity));
}

.dark .button {
  background-color: maroon;
}
```

But this code generates duplicated `.button2` selector:
```JS
addComponents({
  '.button2': {
    cursor: 'pointer',
    // sub-selector comes before @apply
    '.dark &': {
      backgroundColor: 'maroon',
    },
    '@apply bg-red-400': {},
  },
});
```

Result:
```CSS
.button2 {
  cursor: pointer;
}

.dark .button2 {
  background-color: maroon;
}

.button2 {
  --tw-bg-opacity: 1;
  background-color: rgb(248 113 113 / var(--tw-bg-opacity));
}
```

**Comment by Ratko-Solaja** [comment]
I don't think you're referencing the color properly.

Try this:
```const plugin = require('tailwindcss/plugin')

module.exports = {
  theme: {
    extend: {
      // ...
    },
  },
  plugins: [
    plugin(function({ addComponents, theme }) {
      addComponents({
        '.button': {
          cursor: 'pointer',
          backgroundColor: theme('colors.red.400'),
          '.dark &': {
            backgroundColor: 'maroon',
          },
        },
      })
    })
  ],
}
```

**Comment by thecrypticace** [comment]
Hey thanks for the report & reproduction! Appreciate the time you took to file the issue!

Long story short: This is expected behavior.

If your curious about why read on:

We component styles using postcss-js and postcss-nested to handle nesting.

The component your adding turns into the following css:
```css
.button2 {
  cursor: pointer;
  .dark & { background-color: maroon; }
  @apply bg-red-400;
}
```

Which is then expanded to:
```css
.button2 { cursor: pointer; }
.dark .button2 { background-color: maroon; }
.button2 { @apply bg-red-400; }
```

Which then produces the following:
```css
.button2 { cursor: pointer; }
.dark .button2 { background-color: maroon; }
.button2 {
  --tw-bg-opacity: 1;
  background-color: rgb(248 113 113 / var(--tw-bg-opacity));
}
```

The two reasons are:
- Apply expands in place to honor the CSS cascade
- postcss-nested expands nesting in a sass-compatible manner

Take this example using apply and multiple declarations:
```css
.button2 { padding: 2rem; }
.button2 { @apply py-4; }
.button2 { padding-top: 3px; }
```

Thie expands to:
```css
.button2 { padding: 2rem; }
.button2 { padding-top: 1rem; padding-bottom: 1rem; }
.button2 { padding-top: 3px; }
```

which results in a button with the following padding:
```css
padding-top: 3px;
padding-right: 2rem;
padding-bottom: 1rem;
padding-left: 2rem;
```

And if you were to reorder any of them the results would be a different padding.

Now, finally, If we take this logic and follow it through you end up with these steps:
```css
/* 1. Starts with the component styles */
.button2 {
  cursor: pointer;
  .dark & { background-color: maroon; }
  @apply bg-red-400;
}

/* 2. Expand them */
.button2 { cursor: pointer; }
.dark & { background-color: maroon; }
.button2 { @apply bg-red-400 }

/* 3. Which ultimately result in this */
.button2 { cursor: pointer; }
.dark .button2 { background-color: maroon; }
.button2 {
  --tw-bg-opacity: 1;
  background-color: rgb(248 113 113 / var(--tw-bg-opacity));
}
```

I hope this explanation helps. If you have any further questions please feel free to leave a comment!
