### ISSUE TITLE
@layer with nested styles generates invalid css

### ISSUE THREAD

**Issue by helmuthdu** [tailwindlabs/tailwindcss#6946]
**What version of Tailwind CSS are you using?**

3.0.11

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.5

**What version of Node.js are you using?**

14.16.0

**What operating system are you using?**

macOS

[**Reproduction URL**](https://stackblitz.com/edit/node-lvmcsk)

**Describe your issue**

Using the @layer function with nested classes does not generate a valid CSS after the build. Like the example bellow:

```css
.btn {
  &.btn-primary {
    --tw-bg-opacity: 1;
    background-color: rgb(59 130 246 / var(--tw-bg-opacity))
  }
  &.btn-primary {
    --tw-text-opacity: 1;
    color: rgb(255 255 255 / var(--tw-text-opacity))
  }
}
```
