### ISSUE TITLE
PostCSS Import Order with base styles not working

### ISSUE THREAD

**Issue by onasman** [tailwindlabs/tailwindcss#7298]
**What version of Tailwind CSS are you using?**

v3.0.16

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5, react-scripts 5.0.0

**What version of Node.js are you using?**

v14.7.0

**Describe your issue**

#7049 describes my issue very well as it's the exact same one. I'll copy down below:

I am adding some style classes after tailwind/base and tailwind/components via an import that for some reason gets overridden 

when I inline the styles from button.css, the styles work perfectly, and overwrite the tailwind styles, due to css order. (both selectors have a specificity of 010)
once I move them to the imported file, the custom styles seem to be loaded before the tailwind styles, and break.

i can reproduce the issue with a brand new CRA5:
`yarn create react-app my-app --template=typescript`

apply these changes:
```
<!-- append to src/App.tsx -->
<input
    type="submit"
    className="btn btn-primary mt-8 px-5 py-3"
    value="Login"
 />
```
```css
/* add to top of src/index.css */
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "./button.css";

@import "tailwindcss/utilities";
```
```css
/* src/button.css */
.btn {
  @apply cursor-pointer inline-block rounded-md text-base tracking-wide font-medium px-4 py-2;
}
.btn-primary {
  @apply bg-indigo-500 text-white;
}
.btn-primary:hover {
  @apply bg-indigo-400;
}
```
```css
// tailwind.config.js
module.exports = {
  content: ["./src/**/*.tsx", "./src/**/*.ts"],
  theme: {},
};
```
the applied styles in the devtools look like this:
![149301711-90d6215c-f69e-4589-8a55-66c0239d4ba3](https://user-images.githubusercontent.com/59735181/152122717-0879464f-84eb-437c-88d7-e85ea9744d3d.png)

you see that this definition overwrites our button styles, even though they should be loaded before our button styles.
```css
button, [type='button'], [type='reset'], [type='submit'] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
```
