### ISSUE TITLE
Easier overwrite of @tailwind base

### ISSUE THREAD

**Issue by dotnetCarpenter** [tailwindlabs/tailwindcss#7495]
Currently the only way to overwrite the default `font-family` (meaning removing it completely from CSS) is to define `theme.fontFamily.sans`, like so:

```js
module.exports = {
  theme: {
    fontFamily: {
      sans: '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
    }
  }
}
```
_tailwind.config.js_

One thing is that this is not documented at https://tailwindcss.com/docs/font-family#using-custom-values.
However, I found hints to overwriting `font-family` in https://tailwindcss.com/docs/theme#customizing-the-default-theme.

I still think this leaves much to be desired. It have taken me over 1 hour of trial and error.. If you look at the [same question on StackOverflow](https://stackoverflow.com/q/60692794/205696), you will find multiple *wrong* answers.

### How about tying this to the CSS selector, which is what you will see in devTools?

Let's say we want to customize the preflight CSS to:
```css
html {
  line-height: 1.5; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
  -moz-tab-size: 4; /* 3 */
  -o-tab-size: 4;
     tab-size: 4; /* 3 */
  font-family: "LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif; /* 4 */
}
a {
  color: inherit;
  text-decoration: brown underlined;
}
```

One approach could be to still use _tailwind.config.js_ but specifying a selector instead of a Tailwind CSS variable. Of course that might be a slippery slope if all kinds of CSS selectors are allowed or it might be a nice feature.

```js
theme: {
  fontFamily: {
    'html': '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
  },
  textDecoration: {
    'a': 'brown underline'
  }
}
```
_Example of overwriting preflight.css without having to know Tailwind CSS's variable names._

Another approach would be to use `@layer`, so that **instead** of adding to the base CSS, it would overwrite matching selectors **and** properties.

```css
@layer base {
  html {
    font-family: "LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
  }
  a {
    text-decoration: brown underlined;
  }
}
```
_This approach requires zero knowledge of Tailwind CSS and is literally how you would do it in regular CSS but now with a kind of CSS tree-shaking._

What do you think? Is it worth pursuing?
Of course, everything can also be made easier by writing specific documentation on how to overwrite the default `font-family` in Tailwind CSS.

### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7491

<div type='discussions-op-text'>

<sup>Originally posted by **dotnetCarpenter** February 16, 2022</sup>
I keep seeing the [preflight.css's font-family](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L32) when I do `vite build` even though I try to overwrite `font-family` for `html` in my _tailwind.config.js_.

_preflight.css_
```css
html {
	line-height: 1.5;
	-webkit-text-size-adjust: 100%;
	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;
	font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", Segoe UI Symbol, "Noto Color Emoji"
}
```

_tailwind.config.js_
```js
module.exports = {
  content: [
    './index.html',
    './js/**/*.{html,js,mjs}',
  ],
  theme: {
    fontFamily: {
      'html': '"LFT Etica", "Lucida Sans Unicode", "Lucida Grande", sans-serif'
    },
    extend: {
      maxWidth: {
        'x-screen': '100vw'
      },
      colors: {
        'svv-grey': 'hsl(201, 11%, 30%)',
        'svv-yellow': 'rgb(255, 214, 31)',
        'svv-red': 'hsl(355, 85%, 52%)'
      },
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

Is it the fault of [vite](https://vitejs.dev/) or is it impossible to overwrite Tailwind CSS's `font-family`?

Reference to Tailwind CSS docs: https://tailwindcss.com/docs/font-family#using-custom-values
Reference to StackOverflow question about this: https://stackoverflow.com/q/60692794/205696
</div>
