### ISSUE TITLE
Postcss tailwind plugin - filters broken when using @apply

### ISSUE THREAD

**Issue by guillaume-net** [tailwindlabs/tailwindcss#7530]
**What version of Tailwind CSS are you using?**

v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 9.1.0
postcss: 8.4.6

**What version of Node.js are you using?**

v16.3.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://codesandbox.io/s/sveltekit-sandbox-forked-g8p2ll?file=/src/routes/index.svelte

**Describe your issue**

Expected: All filter css-vars (like --tw-blur, --tw-contrast...) should be initialized with a whitespace (e.g. `--tw-blur: ;`)
Issue: When using tailwind postcss plugin, these whitespaces are stripped (`--tw-blur:;`). Thus, filters won't work.

**I don’t use any minifier** and use all the latest versions of packages. 
Please check out the Reproduction URL

**Comment by adamwathan** [comment]
Hey! I've reproduced this issue in your sandbox without using Tailwind at all, so one of the other tools involved (SvelteKit, esbuild, or possibly Codesandbox) or incorrectly minifying the CSS:

https://codesandbox.io/s/sveltekit-sandbox-forked-bxjpgx?file=/src/routes/index.svelte

Here's the CSS that should work but isn't:

```css
<div class="gdw">Grayscale doesn't work</div>

<style>
  .gdw {
    padding: 25px;
    background: blue;
    --blur: ;
    --grayscale: grayscale(1);
    filter: var(--blur) var(--grayscale);
  }
</style>
```

Here's the same code running in JSFiddle where you can see it works fine:

https://jsfiddle.net/4jfyw238/3/

So this isn't caused by Tailwind, since it happens even when Tailwind isn't being used.

Here's a GitHub repo demonstrating it, feel free to use this as a reproduction if you'd like to open an issue against SvelteKit to try and get to the bottom of it:

https://github.com/adamwathan/sveltekit-css-minification-bug/blob/main/src/routes/index.svelte
