### ISSUE TITLE
Commas and screen size variants conflict

### ISSUE THREAD

**Issue by TastyPi** [tailwindlabs/tailwindcss#7727]
**What version of Tailwind CSS are you using?**

For example: v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 9.1.0

Though I can reproduce using Tailwind Play

**What version of Node.js are you using?**

For example: v17.6.0

**What browser are you using?**

For example: N/A

**What operating system are you using?**

For example: Linux

**Reproduction URL**

https://play.tailwindcss.com/4VAY61rg9B

**Describe your issue**

If you have a CSS rule using a comma-separated list of selectors then using a screen size variant on any selector in the list copies all other selectors *without the screen size variant* into the @media query.

e.g. the following CSS:

```css
@layer components {
    .a, .b {
        color: red;
    }
}
```

and the following HTML:

```html
<div class="a text-green-700">I should always be green</div>
<div class="sm:b">I'm here to add sm:b to the mix</div>
```

produces the following:

```css
.a {
    color: red
}

.text-green-700 {
    --tw-text-opacity: 1;
    color: rgb(21 128 61/var(--tw-text-opacity))
}

@media (min-width: 640px) {
    .a, .sm\:b {
        color: red
    }
}
```

when I would have expected the following:

```css
.a {
    color: red
}

.text-green-700 {
    --tw-text-opacity: 1;
    color: rgb(21 128 61/var(--tw-text-opacity))
}

@media (min-width: 640px) {
    .sm\:b {
        color: red
    }
}
```

This is what the Tailwind Play link reproduces
