### ISSUE TITLE
cssnano removes empty custom properties

### ISSUE THREAD

**Issue by jonnitto** [tailwindlabs/tailwindcss#7801]
**I opened also a bug report on the cssnano repo:** https://github.com/cssnano/cssnano/issues/1350

### Describe the bug

In TailwindCSS, many custom properties are set, like `--tw-grayscale:  ;` A class like `.blur` sets following CSS:
```css
.blur {
  --tw-blur: blur(8px);
  filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
}
```

The problem is, if the class `.grayscale` is not used (who set a value, just like blur) the custom property gets removed and the class `blur` doesn't work anymore.
