### ISSUE TITLE
Pseudo element "file" not adding to jit compiler

### ISSUE THREAD

**Issue by thalaeg** [tailwindlabs/tailwindcss#7875]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7857

<div type='discussions-op-text'>

<sup>Originally posted by **thalaeg** March 15, 2022</sup>
I have the following `file` directives I am trying to add to an element. 
![image](https://user-images.githubusercontent.com/21165278/158480091-af9dfc49-ff26-4f9f-8ad8-47436ac9bcc6.png)

However, most are not build/added by the `jit` compiler (I believe).

Before I add these styles and build my output file, these are the only references to the word "file" in my output.css file.

```css
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Change font properties to `inherit` in Safari.
*/

::-webkit-file-upload-button {
  -webkit-appearance: button;
  /* 1 */
  font: inherit;
  /* 2 */
}
[type='file'] {
  background: unset;
  border-color: inherit;
  border-width: 0;
  border-radius: 0;
  padding: 0;
  font-size: unset;
  line-height: inherit;
}

[type='file']:focus {
  outline: 1px auto -webkit-focus-ring-color;
}
```
Once I compile the stuff I have the follow references to "file" in my output.css. You will notice that many/most of the styles are missing. Indeed it is not styled upon checking the front end.
```css
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Change font properties to `inherit` in Safari.
*/

::-webkit-file-upload-button {
  -webkit-appearance: button;
  /* 1 */
  font: inherit;
  /* 2 */
}
[type='file'] {
  background: unset;
  border-color: inherit;
  border-width: 0;
  border-radius: 0;
  padding: 0;
  font-size: unset;
  line-height: inherit;
}

[type='file']:focus {
  outline: 1px auto -webkit-focus-ring-color;
}

.file\:text-gray-800::-webkit-file-upload-button {
  --tw-text-opacity: 1;
  color: rgb(31 41 55 / var(--tw-text-opacity));
}

.file\:text-gray-800::file-selector-button {
  --tw-text-opacity: 1;
  color: rgb(31 41 55 / var(--tw-text-opacity));
}
.hover\:file\:bg-gray-200::-webkit-file-upload-button:hover {
  --tw-bg-opacity: 1;
  background-color: rgb(229 231 235 / var(--tw-bg-opacity));
}

.hover\:file\:bg-gray-200::file-selector-button:hover {
  --tw-bg-opacity: 1;
  background-color: rgb(229 231 235 / var(--tw-bg-opacity));
}
```

Here is my `tailwind.config.js` (which is good as far as I know..) (I tried to even safelist a couple classes to see if they would be added and they were not).
```javascript
module.exports = {
    content: [
        "./**/*.{html,razor,cshtml,cs}",
        "../myProject/**/*.{html,razor,cshtml,cs}",
    ],
    //safelist: [
    //    'file:font-medium',
    //    'file:text-sm',
    //    'file:cursor-pointer',
    //    'file:py-2.5',
    //],
    theme: {
        extend: {
            colors: {
                // some custom colors
            },
        },
    },
    plugins: [
        require('@tailwindcss/aspect-ratio'),
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/line-clamp'),
    ],
}
```
and my `package.json`
```json
{
  "scripts": {
    "build-styles": "npx tailwindcss -i ./Styles/app.css -o ./wwwroot/css/main.css"
  },
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/typography": "^0.5.0",
    "@tailwindcss/line-clamp": "^0.3.1",
    "autoprefixer": "^10.3.1",
    "postcss": "^8.3.6",
    "tailwindcss": "^3.0.23"
  },
  "-vs-binding": {
    "AfterBuild": [
      "build"
    ]
  }
}
```
</div>
