### ISSUE TITLE
`addVariant` can generate CSS that isn't used

### ISSUE THREAD

**Issue by olets** [tailwindlabs/tailwindcss#8124]
**What version of Tailwind CSS are you using?**

3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

Tailwind Play

**What browser are you using?**

Chrome Version 100.0.4896.88 (Official Build) (arm64)

**What operating system are you using?**

macOS 12.3.1 (21E258

**Reproduction URL**

https://play.tailwindcss.com/Oi1TN4H1eJ

**Describe your issue**

`addVariant`'s variant definition can be an array `VariantDefinition[]`. If CSS is built for any of the entries in the array, CSS is built for all of them regardless of whether they appear in the `theme.content`

Given

```js
// tailwind.config.js
//...
    ({ addVariant }) => {
      addVariant('my-variant', ['[my-attr] &', '[my-attr]&'])
    },
//...
```

and

```html
<div my-attr class="my-variant:text-red-500">hello world</div>
```

I expect the generated CSS

```css
[my-attr].my-variant\:text-red-500 {
  --tw-text-opacity: 1;
  color: rgb(239 68 68 / var(--tw-text-opacity));
}
```

The actual generated CSS is

```css
[my-attr] .my-variant\:text-red-500 {
  --tw-text-opacity: 1;
  color: rgb(239 68 68 / var(--tw-text-opacity));
}

[my-attr].my-variant\:text-red-500 {
  --tw-text-opacity: 1;
  color: rgb(239 68 68 / var(--tw-text-opacity));
}
```

(Notice thanks to the new Generated CSS panel! Great feature!)
