### ISSUE TITLE
screen directive generates wrong media query

### ISSUE THREAD

**Issue by yshrsmz** [tailwindlabs/tailwindcss#8159]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

--

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/lsmASJpXqw?file=css

**Describe your issue**

While I am trying to create a repro for a different issue on Tailwind Play, I found below.

This postcss

```postcss
@tailwind base;
@tailwind components;
@tailwind utilities;

.page-title {
  @apply text-gray-700 text-center py-5 border-b border-gray-200;

  @screen sm {
    width: auto;
  }
}
```

generates below CSS

```css
.page-title {
  border-bottom-width: 1px;
  --tw-border-opacity: 1;
  border-color: rgb(229 231 235 / var(--tw-border-opacity));
  padding-top: 1.25rem;
  padding-bottom: 1.25rem;
  text-align: center;
  --tw-text-opacity: 1;
  color: rgb(55 65 81 / var(--tw-text-opacity));
  @media (min-width: 640px) {
    width: auto;
  }
}

```

but it should generate something like

```css
.page-title {
  border-bottom-width: 1px;
  --tw-border-opacity: 1;
  border-color: rgb(229 231 235 / var(--tw-border-opacity));
  padding-top: 1.25rem;
  padding-bottom: 1.25rem;
  text-align: center;
  --tw-text-opacity: 1;
  color: rgb(55 65 81 / var(--tw-text-opacity));
}

@media (min-width: 640) {
  .page-title {
    width: auto;
  }
}
```
