### ISSUE TITLE
Nested and grouped scss selector doesn't work with responsive utility variants

### ISSUE THREAD

**Issue by mimamuh** [tailwindlabs/tailwindcss#8233]
**What version of Tailwind CSS are you using?**
`3.0.24`

**What build tool (or framework if it abstracts the build tool) are you using?**
```
laravel-mix: 6.0.43 (abstracts webpack with:)
webpack: 5.60.0
postcss-loader: 6.2.0
sass-loader: 12.6.0
postcss: 8.4.12
sass: 1.51.0
```

**What version of Node.js are you using?**
`v16.14.1`

**What browser are you using?**
Chrome, Firefox

**What operating system are you using?**
macOS

**Reproduction URL**

[Repro on GitHub](https://github.com/mimamuh/tailwind-issue-with-nested-scss-selectors)

**Describe your issue**

I have a _SCSS_ file `./src/main.scss` with a utility rule added to the `@components` layer using _Tailwind_ with _SASS_:

```scss
@layer components {
  .base {
    /* NOTE: These grouped and nested rules causes the 
    bug when the `base` utility is combined with a breakpoint 
    like `md:base` */
    .foo,
    .bar {
      @apply bg-rose-600;
    }
  }
}
```

Then there is some _HTML_ `./index.html` using the new utilities together with a responsive utility variant `sm:`:

```html
<!-- This div uses the md:base here -->
<div class="flex gap-4 md:base">
  <!-- And the foo should render something red -->
  <button class="p-2 border-2 border-zinc-600 foo">Should be red</button>
  <!-- And also bar should render something red -->
  <button class="p-2 border-2 border-zinc-600 bar">Should be red</button>
  <button class="p-2 border-2 border-zinc-600">As is</button>
</div>
```

As `.foo, .bar` is grouped, the generated _CSS_ of _Tailwind_ is this:

```css
@media (min-width: 768px) {
  .md\:base .foo,
  .base .bar {
    --tw-bg-opacity: 1;
    background-color: rgb(225 29 72 / var(--tw-bg-opacity));
  }
}
```

Instead of this:

```css
@media (min-width: 768px) {
  .md\:base .foo,
  .md\:base .bar {
    --tw-bg-opacity: 1;
    background-color: rgb(225 29 72 / var(--tw-bg-opacity));
  }
}
```

**It basically applies the breakpoint only to the first grouped and nested utility combo `.base .foo`, but not to the second `.base .bar`.**
