### ISSUE TITLE
Transparency doesn't work when using CSS variables

### ISSUE THREAD

**Issue by RobinBoers** [tailwindlabs/tailwindcss#8472]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

Just `npx tailwindcss -i ./css/global.css -o ./css/main.css -w`

**What version of Node.js are you using?**

v16.13.2

**What browser are you using?**

N/A

**What operating system are you using?**

ElementaryOS (Which is based on Ubuntu, Linux)

**Reproduction URL**

https://play.tailwindcss.com/09ovE5pnk1?file=css

**Describe your issue**

Hi! I'm trying to built a color scheme switcher for my website (like mxb.dev has), and I thought I'd use CSS variables that I can manipulate using JS. So I looked it up, and everywhere online people say I need to do this:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
    --black: #0d2b45;
    --white: #ffecd6;
    --accent: #ffaa5e;
}
```

```js
module.exports = {
    theme: {
        colors: {
            black: "var(--black)",
            white: "var(--white)",
            accent: "var(--accent)",
        },
...
```

It works fine, but transparency doesn't seem to work (example: `text-black` works but `text-black/40` doesn't).
