### ISSUE TITLE
 Error: Cannot find module '@tailwindcss/forms'

### ISSUE THREAD

**Issue by PaulineTW** [tailwindlabs/tailwindcss#8494]
### What version of @tailwindcss/forms are you using?

@tailwindcss/forms": "^0.5.2

### What version of Node.js are you using?

v14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

WSL2

### Describe your issue

I'm getting this error when building container with docker
```
app_1  | 09:20:56 web.1  | started with pid 10
app_1  | 09:20:56 js.1   | started with pid 11
app_1  | 09:20:56 css.1  | started with pid 12
app_1  | 09:20:57 css.1  | yarn run v1.22.18
app_1  | 09:20:57 js.1   | yarn run v1.22.18
app_1  | 09:20:57 js.1   | $ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --watch
app_1  | 09:20:57 css.1  | $ tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify --watch
app_1  | 09:20:59 js.1   | [watch] build finished, watching for changes...
app_1  | 09:21:05 css.1  | node:internal/modules/cjs/loader:933
app_1  | 09:21:05 css.1  |   const err = new Error(message);
app_1  | 09:21:05 css.1  |               ^
app_1  | 09:21:05 css.1  |
app_1  | 09:21:05 css.1  | Error: Cannot find module '@tailwindcss/forms'
app_1  | 09:21:05 css.1  | Require stack:
app_1  | 09:21:05 css.1  | - /kinship4lab/tailwind.config.js
app_1  | 09:21:05 css.1  | - /kinship4lab/node_modules/tailwindcss/lib/cli.js
app_1  | 09:21:05 css.1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
app_1  | 09:21:05 css.1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
app_1  | 09:21:05 css.1  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
app_1  | 09:21:05 css.1  |     at require (node:internal/modules/cjs/helpers:102:18)
app_1  | 09:21:05 css.1  |     at Object.<anonymous> (/kinship4lab/tailwind.config.js:9:5)
app_1  | 09:21:05 css.1  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
app_1  | 09:21:05 css.1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
app_1  | 09:21:05 css.1  |     at Module.load (node:internal/modules/cjs/loader:981:32)
app_1  | 09:21:05 css.1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
app_1  | 09:21:05 css.1  |     at Module.require (node:internal/modules/cjs/loader:1005:19) {
app_1  | 09:21:05 css.1  |   code: 'MODULE_NOT_FOUND',
app_1  | 09:21:05 css.1  |   requireStack: [
app_1  | 09:21:05 css.1  |     '/kinship4lab/tailwind.config.js',
app_1  | 09:21:05 css.1  |     '/kinship4lab/node_modules/tailwindcss/lib/cli.js'
app_1  | 09:21:05 css.1  |   ]
app_1  | 09:21:05 css.1  | }
app_1  | 09:21:05 css.1  | error Command failed with exit code 1.
app_1  | 09:21:05 css.1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1  | 09:21:06 css.1  | exited with code 1
app_1  | 09:21:06 system | sending SIGTERM to all processes
app_1  | 09:21:06 web.1  | terminated by SIGTERM
app_1  | 09:21:06 js.1   | exited with code `1`
```
package.json

```
{
  "name": "app",
  "private": "true",
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify"
  },
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.1",
    "esbuild": "^0.14.38"
  },
  "devDependencies": {
    "@tailwindcss/forms": "^0.5.2",
    "autoprefixer": "^10.4.7",
    "postcss": "^8.4.14",
    "stylelint-config-recommended": "^7.0.0",
    "tailwindcss": "^3.0.24"
  }
}
```
tailwind.config.js

```
module.exports = {
  content: [
    './app/views/**/*.html.erb',
    './app/helpers/**/*.rb',
    './app/assets/stylesheets/**/*.css',
    './app/javascript/**/*.js'
  ],
  plugins: [
    require('@tailwindcss/forms')
  ]

}
```
docker-compose.yml
```
version: "3.9"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/kinship4lab
      - exclude:/kinship4lab/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
  db:
    image: "postgres:14-alpine"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: kinship4lab
      POSTGRES_PASSWORD: kinship4lab
      POSTGRES_DB: kinship4lab

```
Dockerfile

```
# syntax=docker/dockerfile:1.3
FROM ruby:3.1.2-alpine

RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
    ln -s /var/cache/apk /etc/apk/cache \
    && apk upgrade \
  && apk add bash build-base nodejs npm redis zlib-dev libxml2-dev libxslt-dev tzdata yaml-dev sqlite-dev libpq-dev gcompat

WORKDIR /kinship4lab
ADD . /kinship4lab
RUN bundle install
RUN npm install --global yarn
RUN gem install foreman
RUN yarn install

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]
```

Any could help? i have been stuck for few hours now.

Thanks heaps
