### ISSUE TITLE
tailwindcss does not support content in monorepo packages

### ISSUE THREAD

**Issue by polRk** [tailwindlabs/tailwindcss#8613]
Try to reproduce it in Tailwind Play. If you can’t reproduce it there then unfortunately the issue is very unlikely to be in Tailwind.

_Originally posted by @adamwathan in https://github.com/tailwindlabs/tailwindcss/issues/8606#issuecomment-1153227090_

**Comment by polRk** [comment]
That's how it works.

```json
    content: [
        './index.html', 
        './src/**/*.{css,ts,tsx}', 
        paths.pkg('ui') + '/**/*.{css,ts,tsx}'
   ],
```

 This means that tailwind does not see the contents of another package in the monorepo

**Comment by polRk** [comment]
https://github.com/polRk/tailwindcss-monorepo-bug.git

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Sorry what is your _exact_ issue you are seeing? How can I reproduce your issue, and what is the expected behaviour?

---

When I run `npm run dev` in the `apps/demo/` folder and go to http://localhost:8080/ I can see `Demo` and `Email` on the screen, inspecting the css that's generated looks like this:
```css
.caption {
  padding: 0.25rem 0;
  color: var(--label-color-secondary);
  font-weight: 500;
  white-space: pre;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-transform: uppercase;
}
.label {
  color: var(--label-color-primary);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  white-space: pre;
}
.hint {
  color: var(--label-color-secondary);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.field {
  display: flex;
  width: 100%;
}
.field-control {
  padding: 0 1rem;
  width: 100%;
}
.field-control > .switch {
  margin-left: auto;
}
```
Which seems to match the code that you defined in your `@betteraskbot/tailwind-plugin` package. This also means that Tailwind properly generated the code you defined in your plugin.

You have to indeed use `paths.pkg('ui') + '/**/*.{css,ts,tsx}'` in your tailwind.config.js file but that's expected since we require paths to all the files you use Tailwind classes in.
