### ISSUE TITLE
the problem of adding mutlti at-rule with `addVariant` API

### ISSUE THREAD

**Issue by iczer** [tailwindlabs/tailwindcss#8795]
**What version of Tailwind CSS are you using?**

v3.1.4

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.14, Vue 2.2.37, vite 2.2.4

**What version of Node.js are you using?**

v12.20.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

I encountered a problem wthen using the `addVariant` API to register custom variant. I wanted to add two at-rules named @media for my custom variant style, but actually only got one (it  work well in `tailwindcss@v2.2.19`). The code and result are as follows:

* code in tailwind.config.js
```js
const plugin = require('tailwindcss/plugin');

module.exports = {
  purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  plugins: [
    plugin(function ({ addVariant, postcss }) {
      addVariant('mdx', ({ container }) => {
        const mediaRule1 = postcss.atRule({
          name: 'media',
          params: '(min-width: 1200px)',
        });
        const mediaRule2 = postcss.atRule({
          name: 'media',
          params: '(min-width: 1040px)',
        });
        mediaRule1.append(container.nodes);
        container.push(mediaRule1);
        container.push(mediaRule2);
        mediaRule1.walkRules((rule) => {
          rule.selector = `.mdx\\:${rule.selector.slice(1)}`;
          mediaRule2.append(rule.clone());
        });
        mediaRule2.walkRules((rule) => {
          rule.selector = `.collapsed ${rule.selector}`;
        });
      });
    }),
  ],
};
```
When using class `mdx:col-span-3` in component, the result style code that I actually got is:
```css
@media (min-width: 1200px) {
  .collapsed .mdx\:col-span-3 {
    grid-column: span 3 / span 3;
  }
}
```

but the result style code I want to get is:
```css
@media (min-width: 1200px) {
  .mdx\:col-span-6 {
    grid-column: span 6 / span 6;
  }
}

@media (min-width: 1040px) {
  .collapsed .mdx\:col-span-6 {
    grid-column: span 6 / span 6;
  }
}
```
