### ISSUE TITLE
Escaping underscores in JavaScript contexts can cause mismatched class selectors

### ISSUE THREAD

**Issue by nbrombal** [tailwindlabs/tailwindcss#8881]
**What version of Tailwind CSS are you using?**

v3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Create React App v5.0.1

**What version of Node.js are you using?**

v16.15.0

**What browser are you using?**

Observed in Firefox 103 and Chrome 103

**What operating system are you using?**

macOS 12.4

**Reproduction URL**

https://github.com/nbrombal/tailwind-escape-conflict

**Describe your issue**

Tailwind's method of [escaping underscores within arbitrary values](https://tailwindcss.com/docs/content#using-spaces-and-underscores) conflicts with JavaScript when Tailwind classes are applied in a JavaScript context. For example, when using Tailwind classes in JSX as part of a ternary expression, or as a function argument for the popular [classnames](https://www.npmjs.com/package/classnames) library. This can lead to the HTML that is ultimately rendered to the page not matching the CSS that Tailwind generates.

My specific situation is one where I want to use underscores in the content attribute of a pseudo-selector. In the following examples, `expand_more` is the name of an icon in [the Material Symbols icon font](https://fonts.google.com/icons), and the `font-symbols` utility applies that icon font so its ligature feature will translate the name into the icon.

I'm not the first person to have run into this (that would be @FelixZY in [this discussion](https://github.com/tailwindlabs/tailwindcss/discussions/8356)), but I don't believe the cause of this edge case has been articulated until now.

## Plain String, single escaped (working as intended)

The JSX source contains a simple string for the className prop:

```jsx
<span className='before:font-symbols before:content-["expand\_more"]' />
```

&check; The generated HTML class is as expected.

```html
<span class="before:font-symbols before:content-[&quot;expand\_more&quot;]"></span>
```

&check; The generated CSS rule is as expected.

```css
.before\:content-\[\"expand\\_more\"\]::before {
  --tw-content: "expand_more";
  content: var(--tw-content);
}
```

## JavaScript String, single escaped

The JSX source uses a string in a JavaScript context (note that this runs afoul of my ESLint/Prettier config, YMMV):

```jsx
/* eslint-disable no-useless-escape, prettier/prettier */
<span className={'before:font-symbols before:content-["expand\_more"]'} />
```

&cross; Because of the JS context, the slash has been removed from the HTML class.

```html
<span class="before:font-symbols before:content-[&quot;expand_more&quot;]"></span>
```

&check; The generated CSS rule is as expected, but of course it now doesn't match our slash-less HTML class.

```css
.before\:content-\[\"expand\\_more\"\]::before {
  --tw-content: "expand_more";
  content: var(--tw-content);
}
```

## JavaScript string, double escaped

The JSX source uses a string in a JavaScript context:

```jsx
<span className={'before:font-symbols before:content-["expand\\_more"]'} />
```

&check; The generated HTML class is now as expected since we escaped our escape character.

```html
<span class="before:font-symbols before:content-[&quot;expand\_more&quot;]"></span>
```

&cross; However, the generated CSS rule now incorporates the extra slashes, so it doesn't match the HTML class.

```css
.before\:content-\[\"expand\\\\_more\"\]::before {
  --tw-content: "expand\_more";
  content: var(--tw-content);
}
```

This could probably be resolved by having Tailwind use a different method to escape underscores that doesn't match the way JavaScript does it. I've struggled to come up with an alternative to suggest because any option risks breaking existing content strings, but for simplicity's sake I lean towards suggesting a single underscore to represent a space (which is the current behavior), and a double underscore to represent an underscore.

**Comment by jean343** [comment]
This has to be fixed, I spent countless hours trying to solve this problem!

**Comment by nbrombal** [comment]
I did a little digging to satisfy my curiosity and found [the location of the underscore replacement logic](https://github.com/tailwindlabs/tailwindcss/blob/bdd9ae001dc7ea35923add95befce06ce066f0c3/src/util/dataTypes.js#L29-L36), just to ease the burden of anyone that may want to dig in further.

I'd be happy to open a PR, but preferably not before there's been some discussion on the best solution.

**Comment by Holthaus789** [comment]
Could you provide a screenshot or more details about how the internal error message shows up?

**Comment by jaulz** [comment]
Not 100% sure if it covers exactly the same issue but I also noticed that classes are not generated correctly using Vue templates:
````html
class="[&_.card\_\_footer]:!pb-0"
````

will produce
````css
.\[\&_\.card\\_\\_footer\]\:\!pb-0 .card__footer {
  padding-bottom: 0px !important;
}
````

but the generated HTML is
````html
class="[&_.card__footer]:!pb-0"
````

Consequently, the `\` is escaped again in the generated style class and the styles should rather be like this (note the difference between "card" and "footer"):
````css
.\[\&_\.card\_\_footer\]\:\!pb-0 .card__footer {
  padding-bottom: 0px !important;
}
````
