### ISSUE TITLE
Custom variant utilities sometimes incorrectly get prefixed

### ISSUE THREAD

**Issue by GC-Mark** [tailwindlabs/tailwindcss#8906]
**What version of Tailwind CSS are you using?**

v3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Laravel Mix

**What version of Node.js are you using?**

v16.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/crlyVAimAY

**Describe your issue**

First thing to mention, we use a `prefix` of `tw-`.

We have created a custom variant called `lighthub`. This variant only gets applied when a parent element has the class `.tw-lighthub` applied

e.g.

```html
<body class="tw-lighthub">
    <div class="lighthub:bg-gray-500">Lorem ispum</div>
</body>
```

The above example works absolutely fine, but we have just come across a situation that didn't work.

```html
<body class="tw-lighthub">
    <div class="lighthub:tw-bg-gray-500 lighthub:tw-space-y-6">Lorem ispum</div>
</body>
```

In the above example, the `tw-space-y-6` was not being applied.

When we looked at the generated CSS, we can see the following...

```css
.tw-lighthub .tw-lighthub\:tw-space-y-6 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(1.5rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(1.5rem * var(--tw-space-y-reverse));
}

.tw-lighthub .lighthub\:tw-bg-slate-400 {
  --tw-bg-opacity: 1;
  background-color: rgb(148 163 184 / var(--tw-bg-opacity));
}
```

It seems that the `lighthub` variant is being incorrectly prefixed for the `tw-space-y-6` utility.

This is what our `addVariant` plugin looks like.

```javascript
plugins: [
    plugin(function ({ addVariant, e }) {
      addVariant('lighthub', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          const element = e(`lighthub${separator}${className}`);
          return `.lighthub .${element}`;
        });
      });
    })
  ],
```
