### ISSUE TITLE
Cannot build CSS - Garbage Collection, js heap Out of Memory (OOM), mark-compacts near heap limit

### ISSUE THREAD

**Issue by optimizasean** [tailwindlabs/tailwindcss#8954]
Cannot build css - memory issues?

Trying to run command:
```sh
BlazorSamples % npm run build:css

> BlazorSamples@1.0.0 build:css
> tailwind build -i styles.css -o wwwroot/css/tailwind.css


<--- Last few GCs --->

[15696:0x7f96a8028000]   197589 ms: Mark-sweep 3915.9 (4129.0) -> 3900.3 (4130.0) MB, 1959.6 / 0.0 ms  (average mu = 0.136, current mu = 0.034) allocation failure; scavenge might not succeed
[15696:0x7f96a8028000]   199619 ms: Mark-sweep 3916.8 (4130.0) -> 3901.5 (4131.0) MB, 1963.2 / 0.0 ms  (average mu = 0.095, current mu = 0.033) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10e1d9ef2 node::Abort() [/usr/local/Cellar/node/18.6.0/bin/node]
 2: 0x10e1db025 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/18.6.0/bin/node]
 3: 0x10e34a55d v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/18.6.0/bin/node]
 4: 0x10e34a4f5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/18.6.0/bin/node]
 5: 0x10e4a6363 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node/18.6.0/bin/node]
 6: 0x10e4a8b66 v8::internal::Heap::ComputeMutatorUtilization(char const*, double, double) [/usr/local/Cellar/node/18.6.0/bin/node]
 7: 0x10e4a6b76 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/usr/local/Cellar/node/18.6.0/bin/node]
 8: 0x10e4a4919 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/18.6.0/bin/node]
 9: 0x10e49a029 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/18.6.0/bin/node]
10: 0x10e49a849 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/18.6.0/bin/node]
11: 0x10e484197 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/Cellar/node/18.6.0/bin/node]
12: 0x10e77a472 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/Cellar/node/18.6.0/bin/node]
13: 0x10e02e7b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/Cellar/node/18.6.0/bin/node]
14: 0x11c4b802d 
/var/folders/v7/06n56dsd2tqgq1d39b9t7plw0000gp/T/buildcss-dfb83252.sh: line 1: 15696 Abort trap: 6           tailwind build -i styles.css -o wwwroot/css/tailwind.css
BlazorSamples % 
```

styles.css
```css
/**
 * This injects Tailwind's base styles and any base styles registered by
 * plugins.
 */
 @tailwind base;



/**
 * This injects Tailwind's component classes and any component classes
 * registered by plugins.
 */
@tailwind components;



/* CUSTOM TAILWIND UTILITIES */

/* none created yet */

/* END CUSTOM TAILWIND UTILITIES END */



/**
 * This injects Tailwind's utility classes and any utility classes registered
 * by plugins.
 */
@tailwind utilities;



/* BLAZOR REQUIRED CLASSES */
#blazor-error-ui {
    @apply bg-yellow-300 bottom-0 shadow hidden left-0 fixed px-5 py-3 w-full z-50;
}

#blazor-error-ui .dismiss {
    @apply cursor-pointer absolute right-0 mr-2 top-0 my-1;
}
/* END BLAZOR REQUIRED CLASSES *



/* BLAZOR DEFAULT APPLIED CLASSES */
.validation-message {
    @apply my-1 text-red-800 rounded text-sm font-normal tracking-tight leading-none;
}

.valid {
    @apply bg-white text-black border-gray-300 border-solid border;
}

.modified {
    /* NONE */
}

.invalid {
    @apply bg-red-100 text-red-800 border-red-600 border-solid border;
}
/* END BLAZOR DEFAULT APPLIED CLASSES */

/* BLAZOR .NET6p4 default app.css

html, body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
}

a, .btn-link {
    color: #0366d6;
}

.btn-primary {
    color: #fff;
    background-color: #1b6ec2;
    border-color: #1861ac;
}

.content {
    padding-top: 1.1rem;
}

.valid.modified:not([type=checkbox]) {
    outline: 1px solid #26b050;
}

.invalid {
    outline: 1px solid red;
}

.validation-message {
    color: red;
}

#blazor-error-ui {
    background: lightyellow;
    bottom: 0;
    box-shadow: 0 -1px 2px rgba(0, 0, 0, 0.2);
    display: none;
    left: 0;
    padding: 0.6rem 1.25rem 0.7rem 1.25rem;
    position: fixed;
    width: 100%;
    z-index: 1000;
}

    #blazor-error-ui .dismiss {
        cursor: pointer;
        position: absolute;
        right: 0.75rem;
        top: 0.5rem;
    }

.blazor-error-boundary {
    background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTYiIGhlaWdodD0iNDkiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIG92ZXJmbG93PSJoaWRkZW4iPjxkZWZzPjxjbGlwUGF0aCBpZD0iY2xpcDAiPjxyZWN0IHg9IjIzNSIgeT0iNTEiIHdpZHRoPSI1NiIgaGVpZ2h0PSI0OSIvPjwvY2xpcFBhdGg+PC9kZWZzPjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMCkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0yMzUgLTUxKSI+PHBhdGggZD0iTTI2My41MDYgNTFDMjY0LjcxNyA1MSAyNjUuODEzIDUxLjQ4MzcgMjY2LjYwNiA1Mi4yNjU4TDI2Ny4wNTIgNTIuNzk4NyAyNjcuNTM5IDUzLjYyODMgMjkwLjE4NSA5Mi4xODMxIDI5MC41NDUgOTIuNzk1IDI5MC42NTYgOTIuOTk2QzI5MC44NzcgOTMuNTEzIDI5MSA5NC4wODE1IDI5MSA5NC42NzgyIDI5MSA5Ny4wNjUxIDI4OS4wMzggOTkgMjg2LjYxNyA5OUwyNDAuMzgzIDk5QzIzNy45NjMgOTkgMjM2IDk3LjA2NTEgMjM2IDk0LjY3ODIgMjM2IDk0LjM3OTkgMjM2LjAzMSA5NC4wODg2IDIzNi4wODkgOTMuODA3MkwyMzYuMzM4IDkzLjAxNjIgMjM2Ljg1OCA5Mi4xMzE0IDI1OS40NzMgNTMuNjI5NCAyNTkuOTYxIDUyLjc5ODUgMjYwLjQwNyA1Mi4yNjU4QzI2MS4yIDUxLjQ4MzcgMjYyLjI5NiA1MSAyNjMuNTA2IDUxWk0yNjMuNTg2IDY2LjAxODNDMjYwLjczNyA2Ni4wMTgzIDI1OS4zMTMgNjcuMTI0NSAyNTkuMzEzIDY5LjMzNyAyNTkuMzEzIDY5LjYxMDIgMjU5LjMzMiA2OS44NjA4IDI1OS4zNzEgNzAuMDg4N0wyNjEuNzk1IDg0LjAxNjEgMjY1LjM4IDg0LjAxNjEgMjY3LjgyMSA2OS43NDc1QzI2Ny44NiA2OS43MzA5IDI2Ny44NzkgNjkuNTg3NyAyNjcuODc5IDY5LjMxNzkgMjY3Ljg3OSA2Ny4xMTgyIDI2Ni40NDggNjYuMDE4MyAyNjMuNTg2IDY2LjAxODNaTTI2My41NzYgODYuMDU0N0MyNjEuMDQ5IDg2LjA1NDcgMjU5Ljc4NiA4Ny4zMDA1IDI1OS43ODYgODkuNzkyMSAyNTkuNzg2IDkyLjI4MzcgMjYxLjA0OSA5My41Mjk1IDI2My41NzYgOTMuNTI5NSAyNjYuMTE2IDkzLjUyOTUgMjY3LjM4NyA5Mi4yODM3IDI2Ny4zODcgODkuNzkyMSAyNjcuMzg3IDg3LjMwMDUgMjY2LjExNiA4Ni4wNTQ3IDI2My41NzYgODYuMDU0N1oiIGZpbGw9IiNGRkU1MDAiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjwvZz48L3N2Zz4=) no-repeat 1rem/1.8rem, #b32121;
    padding: 1rem 1rem 1rem 3.7rem;
    color: white;
}

    .blazor-error-boundary::after {
        content: "An error has occurred."
    }
*/

/**
 * Use this directive to control where Tailwind injects the responsive
 * variations of each utility.
 *
 * If omitted, Tailwind will append these classes to the very end of
 * your stylesheet by default.
 */
@tailwind screens;
```

tailwind.config.js:
```js
module.exports = {
    content: [
        './wwwroot/index.html',
        './Pages/*.razor',
        './Layouts/*.razor',
        './Components/*.razor'
    ],
    safelist: [
        {
            pattern: /.*/,
            variants: [
                "first",
                "last",
                "odd",
                "even",
                "visited",
                "checked",
                "empty",
                "read-only",
                "group-hover",
                "group-focus",
                "focus-within",
                "hover",
                "focus",
                "focus-visible",
                "active",
                "disabled",
            ],
        },
    ],
    theme: {
      extend: {
        listStyleType: {
          //none: 'none',
          //disc: 'disc',
          decimal: 'decimal',
          square: 'square',
          circle: 'circle',
          roman: 'upper-roman',
          smallroman: 'lower-roman',
          lower: 'lower-alpha',
          upper: 'upper-alpha',
        },
      },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/line-clamp'),
        require('@tailwindcss/aspect-ratio')
    ],
  }
```

Tailwind version is 3.1.4+
