### ISSUE TITLE
React CSS modules can't use `dark:` variants

### ISSUE THREAD

**Issue by murderteeth** [tailwindlabs/tailwindcss#8960]
**What version of Tailwind CSS are you using?**

`^3.1.6`

**What build tool (or framework if it abstracts the build tool) are you using?**

`create react app 5.0.1, etc.`

**What version of Node.js are you using?**

`v16.15.0`

**What browser are you using?**

`Chrome, Brave`

**What operating system are you using?**

`macOS`

**Reproduction URL**
https://charming-mooncake-2fc871.netlify.app/
https://github.com/murderteeth/react-css-modules-w-darkmode

**Describe your issue**
In my react projects dark mode variants work great when I use them from a regular style sheet. Dark mode variants _do not work_ when I use them from css modules.

This is similar to https://github.com/tailwindlabs/tailwindcss/issues/6388, but the resolution doesn't seem to apply to css modules, per https://github.com/tailwindlabs/tailwindcss/issues/6388#issuecomment-1010106111.

https://user-images.githubusercontent.com/89237203/181102570-5be1c21d-15f8-4176-9483-7eccbe438777.mp4

**Comment by adamwathan** [comment]
Hey! So this is because CSS modules mangles the class names — you can see this is the output that it generates:

```css
.App_dark__TE4we .App_darkModeClassThatDoesntWork__O9hyv {
  --tw-bg-opacity: 1;
  --tw-text-opacity: 1;
  background-color: rgb(248 250 252 / var(--tw-bg-opacity));
  background-color: rgb(15 23 42 / var(--tw-bg-opacity));
  color: rgb(255 255 255 / var(--tw-text-opacity));
}
```

This means you need to add the `App_dark__TE4we` class to the root of your document instead of the `dark` class, since CSS modules is changing the class name after Tailwind adds it. I don't even know how to predict what the class name will be or what you should actually do here I'm afraid since I don't personally use CSS modules but there's nothing we can really "fix" in Tailwind here — it's simply the result of you using another tool that mangles the CSS after Tailwind generates it.

Personally I would never use CSS modules with Tailwind, just a recipe for problems to mix two different CSS paradigms and toolsets like that. Sorry can't be more helpful but hope that explanation makes sense.
