### ISSUE TITLE
--2022-08-17: not found

### ISSUE THREAD

**Issue by johansmitsnl** [tailwindlabs/tailwindcss#9123]
**What version of Tailwind CSS are you using?**

`v3.1.8` / `https://github.com/tailwindlabs/tailwindcss/releases/download/v3.1.8/tailwindcss-linux-x64`

**What build tool (or framework if it abstracts the build tool) are you using?**

`tailwindcss-linux-x64`

**What version of Node.js are you using?**

`v16.0.0`

**What browser are you using?**

N/A

**What operating system are you using?**

Debian Testing

**Describe your issue**

```sh
wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.1.8/tailwindcss-linux-x64 -o ~/bin/tailwindcss
chmod +x ~/bin/tailwindcss
tailwindcss -i style/main.scss -o static/main.css --minify
```

Error output:
```
/home/user/bin/tailwindcss: 1: --2022-08-17: not found
/home/user/bin/tailwindcss: 2: Syntax error: "(" unexpected
```

`style/main.scss`
```scss
@tailwind base;
@tailwind components;
@tailwind utilities;

.background-radial-gradient {
  background-color: hsl(72, 56%, 51%);
  background-image: radial-gradient(650px circle at 0% 0%,
          hsl(72, 41%, 35%) 15%,
          hsl(72, 41%, 30%) 35%,
          hsl(72, 41%, 20%) 75%,
          hsl(72, 41%, 19%) 80%,
          transparent 100%),
  radial-gradient(1250px circle at 100% 100%,
                  hsl(72, 41%, 45%) 15%,
                  hsl(72, 41%, 30%) 35%,
                  hsl(72, 41%, 20%) 75%,
                  hsl(72, 41%, 19%) 80%,
                  transparent 100%);
}
```

`tailwind.config.js`
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.html"],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
```
