### ISSUE TITLE
Responsive container variants don't get proper paddings set

### ISSUE THREAD

**Issue by FRSgit** [tailwindlabs/tailwindcss#9199]
**What version of Tailwind CSS are you using?**

3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite@2.9.14, postcss@8.4.14

**What version of Node.js are you using?**

v16.16.0

**What browser are you using?**

Chrome 104

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/UDRYIpLn4a?file=css

**Describe your issue**

In tailwind.config I've set the settings:
```js
  {
    container: {
      center: true,
      padding: {
        DEFAULT: '2rem',
        md: '1.5rem',
        xl: '1rem',
      },
    },
  },
```

But unfortunately for `2xl:container` all of the paddings are being generated inside double nested media query:
```css
@media (min-width: 1536px) {
  @media (min-width: 640px) {
    .\32xl\:container {
      max-width: 640px;
    }
  }

  @media (min-width: 768px) {
    .\32xl\:container {
      max-width: 768px;
      padding-right: 1.5rem;
      padding-left: 1.5rem;
    }
  }
  
  /* etc */
}
```

Which makes paddings applied effectively unusable when using breakpoint variants :(

I would expect that padding declarations would be only in a single media queries, like:
```css
  .\32xl\:container {
      padding-right: 1rem;
      padding-left: 1rem;
  }

  @media (min-width: 768px) {
    .\32xl\:container {
      padding-right: 1.5rem;
      padding-left: 1.5rem;
    }
  }
```

**Comment by adamwathan** [comment]
Hey! This is behaving correctly, the class `2xl:container` says "make this element behave like a container when the `2xl` breakpoint is active".

You can see here that when the viewport is at 1536px or higher, the padding is there:

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/4323180/187052927-70b4b41b-3653-47e6-9ff7-0fdaef416f85.png">

At sizes below that, the class is doing literally nothing, just like how `hover:bg-black` does nothing unless you are hovering 👍🏻 

So generated CSS and behavior here is all intended. Hope that helps you figure out what you should be doing instead here if this isn't the behavior you're looking for 🍻

**Comment by FRSgit** [comment]
@adamwathan Thank you for the response!
Okay, that makes sense. Then, the only idea for me is to style `container` classes additionally with padding by myself.

I'm leaving the SCSS script to do so for the future travelers:
```scss
@mixin prefix ($class, $prefixes...) {
  $selector: '.' + $class;
  @each $prefix in $prefixes {
    $selector: $selector + ',.#{$prefix}\\:#{$class}';
  }

  #{$selector} {
    @content;
  }
}

@mixin responsive ($class) {
  $responsive-prefixes: 'sm', 'md', 'lg', 'xl', unquote('\\32xl');
  @include prefix($class, $responsive-prefixes...) {
    @content;
  }
}

@include responsive('container') {
  padding-left: theme('spacing.4');
  padding-right: theme('spacing.4');

  @media (min-width: theme('screens.md')) {
    padding-left: theme('spacing.6');
    padding-right: theme('spacing.6');
  }

  @media (min-width: theme('screens.xl')) {
    padding-left: theme('spacing.20');
    padding-right: theme('spacing.20');
  }
}
```
