### ISSUE TITLE
Bug with dynamic value in cutom plugin after vite build

### ISSUE THREAD

**Issue by Semdevmaster** [tailwindlabs/tailwindcss#9274]
**What version of Tailwind CSS are you using?**

"tailwindcss": "3.1.8"

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite

**What version of Node.js are you using?**

v16.17.0

**What browser are you using?**

Any

**What operating system are you using?**

Windows 10

**Describe your issue**
Custom plugin
```js
const plugin = require('tailwindcss/plugin')
const iconComponent = plugin(function ({matchComponents}) {
  matchComponents({
      icon: (value) => ({
        maskImage: `url('../img/icons/${value}.svg')`
      })
    },
  )
})
module.exports = iconComponent
```
HTML
```html
<div class="icon-[search]"></div><!--does not process-->
<div class="after:icon-[search]"></div><!--process ok-->
<div class="before:icon-[search]"></div><!--process ok-->
```
Result CSS
```css
.icon-\[search\] {
  -webkit-mask-image: url(../img/icons/search.svg);
  mask-image: url(../img/icons/search.svg)
}

.after\:icon-\[search\]:after {
  content: var(--tw-content);
  -webkit-mask-image: url(/assets/v1/img/icons/search-9ccc80b4.svg);
  mask-image: url(/assets/v1/img/icons/search-9ccc80b4.svg)
}

.before\:icon-\[search\]:before {
  content: var(--tw-content);
  -webkit-mask-image: url(/assets/v1/img/icons/search-9ccc80b4.svg);
  mask-image: url(/assets/v1/img/icons/search-9ccc80b4.svg)
}
```

As you can see, the url function in the class "icon-[search]" did not pass the correct processing

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is an issue with the plugin that does the processing for you and not a Tailwind CSS issue.

Tailwind doesn't resolve/build your assets, so if I use your plugin and your HTML in the Tailwind Playground: https://play.tailwindcss.com/ZN6hvHaf1N

Then the final result looks like this (see generated tab > components):
```css
.icon-\[search\] {
  -webkit-mask-image: url('../img/icons/search.svg');
          mask-image: url('../img/icons/search.svg');
}

.before\:icon-\[search\]::before {
  content: var(--tw-content);
  -webkit-mask-image: url('../img/icons/search.svg');
          mask-image: url('../img/icons/search.svg');
}

.after\:icon-\[search\]::after {
  content: var(--tw-content);
  -webkit-mask-image: url('../img/icons/search.svg');
          mask-image: url('../img/icons/search.svg');
}
```

This CSS (as a PostCSS AST) is then passed to the other plugins in line which will do the rest of the processing.
