### ISSUE TITLE
Adding custom utilities that use `:where()` selector, generates empty CSS selector when used with a responsive prefix

### ISSUE THREAD

**Issue by saadeghi** [tailwindlabs/tailwindcss#9303]
**What version of Tailwind CSS are you using?**

3.1.8

**Reproduction URL**

https://play.tailwindcss.com/6lUxA2zYzo?file=config

**Describe your issue**

This works:
```html
<div class="sm:make-it-red">
```
```js
addUtilities({
  '.make-it-red': {
    backgroundColor: 'red',
  },
}),{
  variants: ["responsive"],
}
```
But this doesn't work:
```html
<div class="sm:make-it-pink">
```
```js
addUtilities({
  ':where(.make-it-pink)': {
    backgroundColor: 'hotpink',
  },
}),{
  variants: ["responsive"],
}
```
Expected CSS:
```css
@media (min-width: 640px) {
  .sm\:make-it-red {
    background-color: red
  }

   :where(.sm\:make-it-pink){
    background-color: hotpink
  }
}
```
Generated CSS:
```css
@media (min-width: 640px) {
  .sm\:make-it-red {
    background-color: red
  }

   {
    background-color: hotpink
  }
}
```
As you can see [here](https://play.tailwindcss.com/6lUxA2zYzo?file=config) it generates empty selector name.

I wonder if there's a way to make it work to have `:where()` selectors with responsive prefixes.
