### ISSUE TITLE
Gap (flex, grid) support for Safari 14<

### ISSUE THREAD

**Issue by lonagi** [tailwindlabs/tailwindcss#9518]
For old browsers this css property doesn't work. So. You can add for class gap-* some like this

```css
.gap-4,
.gap-4:not(.flex-col) >*+* 
{
    margin-left: 1rem;
}
```
it s for flex row

Also, need support fot flex-col. margin-top.
Just put it with gap property together
