### ISSUE TITLE
TW 3.2.0 regression: `@apply` incorrectly modifies selectors containing pseudo-classes

### ISSUE THREAD

**Issue by Techn1x** [tailwindlabs/tailwindcss#9668]
**What version of Tailwind CSS are you using?**

Appears in 3.2.0, also occurs in 3.2.1 (current latest)

**What build tool (or framework if it abstracts the build tool) are you using?**

"ember-cli-postcss": "^8.2.0",
"postcss": "^8.4.18",

**What version of Node.js are you using?**

v16.17.0

**What browser are you using?**

N/A

**What operating system are you using?**

ubuntu

**Reproduction URL**

I attempted to create a Tailwind Play link, but couldn't figure out how to add tailwind nesting plugin :( The plugins property in config expects an array, but the docs on tailwind website has plugins as an object!

Here it is, if you can get `tailwindcss/nesting` working...
https://play.tailwindcss.com/cm3UJrabZH?file=css

**Describe your issue**

This very specific input (I think the `&:not([some-attribute])` plays a big part here)
```css
.check {
  &:not([some-attribute]) {
    &.but-deeply-nested {
      .tailwind-value {
        @apply bg-black;
        color: red;
      }
    }
  }
}
```
ends up in the following output

tailwind 3.1.8 :green_circle: 
```css
.check:not([some-attribute]).but-deeply-nested .tailwind-value {
  --tw-bg-opacity: 1;
  background-color: rgb(0 0 0 / var(--tw-bg-opacity));
  color: red;
}
```

tailwind 3.2.0+ :red_circle: (the tailwind apply results in an incorrect interpretation of the selector it was in)
```css
.check.but-deeply-nested.tailwind-value:not([some-attribute])  {
  --tw-bg-opacity: 1;
  background-color: rgb(0 0 0 / var(--tw-bg-opacity));
}

.check:not([some-attribute]).but-deeply-nested .tailwind-value {
  color: red;
}
```

**Comment by guilhermetod** [comment]
Same here. Using tailwind with Angular resulted in the following code:

```scss
:host.class .nested {
    @apply text-center;
  }
}
```

Instead of the expected output

```css
.class[_nghost-xak-c153] .nested {
  text-align: center;
}
```

resulted in:


```css
.class.nested[_nghost-xak-c153] {
  text-align: center;
}
```

However, I can get the desired result if I change the syntax to:

```scss
:host(.class) .nested {
  @apply text-center;
}
```

I took a look at  the changelog and the changes that happened in the lock file and I believe this can be related to [`postcss-nested@6.0.0`](https://github.com/postcss/postcss-nested).
