### ISSUE TITLE
Nested SCSS selectors breaking `@apply` directive

### ISSUE THREAD

**Issue by shengslogar** [tailwindlabs/tailwindcss#9742]
**What version of Tailwind CSS are you using?**

v3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Laravel Mix v6.0.49

**What version of Node.js are you using?**

v16.18.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS Ventura

**Reproduction URL**

https://github.com/shengslogar/tailwind-scss-nesting-bug-report/blob/main/output.css#L469-L493

**Describe your issue**

Complex nested SCSS selectors seem to be breaking the `@apply` directive.

### Input:
```
.foo {
  &:not(.bar) {
    @apply bg-red-100;
    background: red;

    &.baz > .bam {
      @apply bg-orange-100;
      background: orange;
    }
  }
}
```

### Output:
```
.foo:not(.bar) {
  --tw-bg-opacity: 1;
  background-color: rgb(254 226 226 / var(--tw-bg-opacity));
  background: red;
}

.foo.baz.bam:not(.bar) >  {
  --tw-bg-opacity: 1;
  background-color: rgb(255 237 213 / var(--tw-bg-opacity));
}

.foo:not(.bar).baz > .bam {
  background: orange;
}
```

### Expected Output:
```
.foo:not(.bar) {
  --tw-bg-opacity: 1;
  background-color: rgb(254 226 226 / var(--tw-bg-opacity));
  background: red;
}

.foo:not(.bar).baz > .bam {
  --tw-bg-opacity: 1;
  background-color: rgb(255 237 213 / var(--tw-bg-opacity));
  background: orange;
}
```

Thanks in advance! 🙏

**Comment by adamwathan** [comment]
This seems to generate the wrong CSS even without Sass or nesting at all, so just dropping this reproduction here since it might help us trace it down faster:

https://play.tailwindcss.com/a12qnV4sVd?file=css

Thanks for reporting!

**Comment by adamwathan** [comment]
I was expecting this might be the same bug as this one: https://github.com/tailwindlabs/tailwindcss/issues/9668

...but it still seems to behave incorrectly even on our `insiders` build, so will look at it next week 👍

**Comment by adamwathan** [comment]
Actually it is generating _better_ output in `insiders` — output that is correct but could be minified better:

```css
/* v3.2.1 */
.foo:not(.bar) {
  --tw-bg-opacity: 1;
  background-color: rgb(254 226 226 / var(--tw-bg-opacity));
  background: red;
}

.foo.baz.bam:not(.bar) >  {
  --tw-bg-opacity: 1;
  background-color: rgb(255 237 213 / var(--tw-bg-opacity));
}

.foo:not(.bar).baz > .bam {
  background: orange;
}

/* Insiders */
.foo:not(.bar) {
  --tw-bg-opacity: 1;
  background-color: rgb(254 226 226 / var(--tw-bg-opacity));
  background: red;
}

.foo.baz:not(.bar) > .bam {
  --tw-bg-opacity: 1;
  background-color: rgb(255 237 213 / var(--tw-bg-opacity));
}

.foo:not(.bar).baz > .bam {
  background: orange;
}
```

The last two rules should be able to be collapsed so will leave this open as a reminder to look at that, but the behavior should at least be correct in the insiders build.
