### ISSUE TITLE
Subtraction in `calc()` arbitrary values not always normalized properly

### ISSUE THREAD

**Issue by wongjn** [tailwindlabs/tailwindcss#9832]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play, Webpack v5

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu 18.04 via WSL

**Reproduction URL**

https://play.tailwindcss.com/KnpyuskR45

**Describe your issue**

A value like `calc(1-(var(--something)*0.5))` or `calc(1-var(--something)*0.5)` in an arbitrary variant is not normalized properly, with spaces missing around the subtraction operator:
```css
.mt-\[calc\(1-var\(--something\)\*0\.5\)\] {
  margin-top: calc(1-var(--something) * 0.5);
  /* expected margin-top: calc(1 - var(--something) * 0.5); */
}
```
I would have expected this function consistently akin to the other mathematical operators which seem to be fine:
```css
.mt-\[calc\(1\+\(var\(--something\)\*0\.5\)\)\] {
  margin-top: calc(1 + (var(--something) * 0.5));
}
```
