### ISSUE TITLE
"disabled:" modifier is not working when the class is extended by a pseudo-element

### ISSUE THREAD

**Issue by horans** [tailwindlabs/tailwindcss#9976]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.19, sass 1.56.1, vue 3.2.45, vite 3.2.4

**What version of Node.js are you using?**

18.12.1

**What browser are you using?**

chrome 107

**What operating system are you using?**

win 10

**Reproduction URL**

```html
<button class="test-disabled" disabled>test</button>
```

```sass
  .test-disabled {
    @apply hover:opacity-50;            // working
    @apply disabled:cursor-not-allowed; // not working
  }

  .test-extend::file-selector-button {
    @extend .test-disabled;
  }
```

**Describe your issue**

When we applied a couple of classes (including disabled modifier) to a button, everything worked fine.
But later on when we was trying to extend the style to the `::file-selector-button` from `<input type="file">`,
the `disabled:` modifier stopped working while `hover:`, `active:` worked just fine.

However if we switch modifier into SASS selector, it will work again:

```sass
  .test-disabled {
    &:disabled {
      @apply cursor-not-allowed; // working
    }
  }

  .test-extend::file-selector-button {
    @extend .test-disabled;
  }
```

Further more, if we extend with some other pseudo-elements(eg., `::before`, `::selection`),
`hover:` and `active:` modifiers will not work as well.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you provide a reproduction about what "not working" means exactly?

Using `test-disabled` on its own (https://play.tailwindcss.com/c2cO0qIaRG) produces:
```css

.test-disabled:hover {
  opacity: 0.5;
}

.test-disabled:disabled {
  cursor: not-allowed;
}
```

Using `test-extend` as well (https://play.tailwindcss.com/77yYdQxYmU) produces:
```css
.test-disabled:hover {
  opacity: 0.5;
}

.test-disabled:disabled {
  cursor: not-allowed;
}

.test-extend::-webkit-file-upload-button:hover {
  opacity: 0.5;
}

.test-extend::file-selector-button:hover {
  opacity: 0.5;
}

.test-extend::-webkit-file-upload-button:disabled {
  cursor: not-allowed;
}

.test-extend::file-selector-button:disabled {
  cursor: not-allowed;
}
```

Which looks like the expected result to me. If this is still a problem for you, then please provide a minimal reproduction repo or Tailwind Play that showcases the issue.

Hope this helps!

**Comment by horans** [comment]
@RobinMalfait thanks for the reply.
CSS do generated, but cursor will not changed if you actually hover on the file input button (while the opacity will change).
```css
.test-extend::file-selector-button:disabled { // not working
  cursor: not-allowed;
}
```

However, with SASS `@`, the `:disabled` part will go right after the class(other than after the pseudo-element), and do the trick.
```css
.test-extend:disabled::file-selector-button { // working
  cursor: not-allowed;
}
```
